### ISSUE TITLE
[REQ] Add graphical representation of tables and relations

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#101]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=101
Reporter:schlabbe...@gmail.com Date:2008-11-26 13:22:22 Status:Accepted

I'm thinking of something like

<a href="http://www.webyog.com/images/screenshots/SD_StandardView.jpg" rel="nofollow">http://www.webyog.com/images/screenshots/SD_StandardView.jpg</a>
<a href="http://www.mysql.com/common/images/products/workbench_visual_design.gif" rel="nofollow">http://www.mysql.com/common/images/products/workbench_visual_design.gif</a>
<a href="http://www.koffice.org/kexi/pics/relations.png" rel="nofollow">http://www.koffice.org/kexi/pics/relations.png</a>
...

Not really that important as only InnoDB (and Rails?) actually makes use of
foreign keys, so this is for the later list :)

**Comment by fulldecent** [comment]
Recommending to close as out of scope for now.

Too many issues are open and this may not be addressed any time soon.

**Comment by fulldecent** [comment]
Here are some related screenshots

![scaled-v3-main](https://cloud.githubusercontent.com/assets/382183/24383023/29716040-1328-11e7-9883-ce7cf70eb33b.png)
![weblog3](https://cloud.githubusercontent.com/assets/382183/24383024/2971df66-1328-11e7-9ca2-01f2a41350dd.png)
