### ISSUE TITLE
Select multiple files or complete directories to import

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#1047]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1047
Reporter:singlecy...@gmail.com Date:2011-05-05 09:30:02 Status:Accepted

Select multiple files or complete direcotries for import.

I believe multiple file selection is possible from the Mac oS X open file dialogue.
From here several data dump files could be selected to import multiple files
if one has a complete DB that was dumped using individual files.

Even a complete directory/folder could be selected to import.

BTW Kudos that .gz dumps can be imported

many thanks
michael

**Comment by GC-Mark** [comment]
Any imminent plan to include this?
