### ISSUE TITLE
[REQ] Export to SQLite

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#1054]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1054
Reporter:apersaud Date:2011-05-12 19:32:19 Status:Accepted

I would like to have a method from within the app to export the data (database or table) to a SQLite3 compatible .sql file for importing into a sqlite3 database.

**Comment by fuzzy76** [comment]
I'd really love this. It would let me develop locally without having a database server running.
