### ISSUE TITLE
Do not include password flag if no password is specified

### ISSUE THREAD

**Issue by ghost** [sequelpro/sequelpro#1065]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1065
Reporter:ryanecr...@gmail.com Date:2011-05-23 07:48:11 Status:WontFix Closed:2011-07-01

<b>What steps will reproduce the problem?</b>
1. Connect to server over ssh connection (specify user/pass for ssh, only specify user for mysql - blank/empty password field)
2. Get successful ssh connection, by get mysql error &quot;Access denied for user 'root'@'localhost' (using password: NO)&quot;
3. If I use Terminal to ssh to the machine, and run &quot;mysql&quot; or &quot;mysql -u root&quot; I connect to the db just fine. If I run &quot;mysql -u root -p&quot; and provide a blank password (i.e. just hit return) then I get the same error as Sequel Pro gives me. 

<b>What is the expected output? What do you see instead?</b>
I expect to connect without an error message. 

I would expect that if no password is specified, then it would not use the &quot;-p&quot; flag or their would be a check box that differentiates between &quot;no password&quot; vs &quot;blank password&quot; (if there is a difference)

<b>What version of Sequel Pro are you using? What version of MySQL are you</b>
<b>connecting to on the server?</b>
I am using 0.9.8.1 (rev 2492), but I also confirmed this is still a problem with the latest nightly build (rev 3311)

MySQL version - 5.0.92-community-log

<b>Please provide any additional information below.</b>

**Comment by DavidCWGA** [comment]
I understand that this issue has been closed for a while, but it isn't fixed. I have exactly the same problem.

"mysql -u root" connects fine.
"mysql -u root -p" connects fine with a blank password.
Sequel Pro, with the password field left blank, fails to connect, throwing the error "MySQL said: Access denied for user 'root'@'localhost'"

MariaDB 10.1.22 and Sequel Pro 1.1.2

**Comment by dmoagx** [comment]
Please open a new issue. This issue has been closed since 2011!
