### ISSUE TITLE
[REQ] Provide in place help when adding datatypes

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#1090]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1090
Reporter:schlabbe...@gmail.com Date:2011-06-25 13:25:32 Status:Accepted

Attached is a screenshot from HeidiSQL.

Two thinks I like about this:
- The datatypes are grouped by their usage making it easier to see what is available
- It provides direct help as to what a datatype is capable of. This is useful as many developers don't have the actual size of a datatype in mind.

The tooltip in HeidiSQL will only appear when you use the mouse to hover over the items, that way it doesn't get in your way when you know what you want (in which case I usually start by typing the name out).
![heidi](https://cloud.githubusercontent.com/assets/5793864/11015814/7c639ec0-856d-11e5-80b6-f00e02d5d2d7.png)

**Comment by dmoagx** [comment]
I'll leave this issue open, as the current solution probably won't work for the App Store.
