### ISSUE TITLE
[REQ] Don't wrap query placeholders in backticks

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#1120]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1120
Reporter:and...@avit.ca Date:2011-07-20 00:46:25 Status:New

I have a query like this, it helps me show integer columns as the timestamps they actually represent:

CONVERT_TZ(
  FROM_UNIXTIME( ${1:¦¦$SP_ASLIST_ALL_FIELDS¦¦} ), 
  '${2:-05:00}',
  '${3:-07:00}'
) AS $1_parsed

The $1 placeholder automatically gets wrapped in `backticks` when I use this snippet and select the field name from the list. This means that I can't reuse the field name elsewhere, like the &quot;AS $1_parsed&quot; clause. The result looks like this:

AS `added_at`_parsed

As the authors of our own saved queries, we can put the backticks around table names ourselves: this would make it more versatile.

**Comment by briantully** [comment]
Any update on this? It seems as though the automatic backticks essentially make placeholders useless in the query editor
