### ISSUE TITLE
sequel pro update - all databases are gone?!

### ISSUE THREAD

**Issue by ghost** [sequelpro/sequelpro#1129]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1129
Reporter:josephth...@gmail.com Date:2011-07-26 12:02:29 Status:Invalid Closed:2011-08-01

<b>What steps will reproduce the problem?</b>
1. sequel pro asked if i need to update it
2. I clicked &quot;yes sure go ahead&quot;
3. boom headshot! all the databases are gone!

<b>What is the expected output? What do you see instead?</b>

<b>What version of Sequel Pro are you using? What version of MySQL are you</b>
<b>connecting to on the server?</b>

<b>Please provide any additional information below.</b>

**Comment by garfry** [comment]
I had this problem. This is a problem with the "Users" of the database in cpanel. If you create a new user and give all the privileges it will work. I upgraded my hosting and it made the user info freakout.
