### ISSUE TITLE
[REQ] Allow localhost as MySQL host for SSH connections

### ISSUE THREAD

**Issue by ghost** [sequelpro/sequelpro#1146]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1146
Reporter:michael....@gmail.com Date:2011-08-09 14:26:02 Status:Invalid Closed:2011-08-01

It's currently possible to set up a SSH connection that uses 127.0.0.1 as the MySQL host. It's also currently impossible to use &quot;localhost&quot; as the MySQL host with an SSH connection. Sequel Pro gives this prompt in that case: <a href="http://d.pr/kRhy" rel="nofollow">http://d.pr/kRhy</a>

In this particular case, the MySQL server is configured with a user &quot;admin&quot; who only has access for the &quot;localhost&quot; host and does not have access for the 127.0.0.1 host.

In my opinion this is probably actually a defect. If I'm using SSH, it would be really useful for me to be able to have Sequel Pro basically issue this command for me inside the SSH session:

mysql -h localhost -u admin -p

Thanks!

**Comment by ne0c0de** [comment]
Hi,

I'm experiencing the same issue.

I entered the host name as localhost on SSH tunnel connection but it's changing it to 127.0.0.1 and the connection was failed.

I grant my root user to allow on 127.0.0.1 GRANT ALL PRIVILEGES ON *.* TO 'root'@'127.0.0.1' IDENTIFIED BY 'xxx'; and mysql is listening 127.0.0.1 but still can't connect to server. what should i do in this case?

**Comment by MrUpsidown** [comment]
Yeah just close it. And 6 years later this has still not been addressed! Good bye Sequel Pro.
