### ISSUE TITLE
[REQ] Don't close tab when selecting 'Close Connection' when connection is lost

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#1158]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1158
Reporter:gfguth...@gmail.com Date:2011-08-24 03:19:34 Status:New

I often find that I lose a connection to one of my DBs for various reasons (signing in &amp; out of VPN, etc.) and the dialog for a lost connection does not let me do anything else in Sequel Pro unless I address it.

This presents a problem when I know that I've lost the connection:
1) I don't want to lose the queries that I've got in the tab for the lost connection
2) I also want to do work in other tabs where I have a connection, but can't until I address the dialog for the tab that lost its connection

I suppose then there are two solutions:
1) Don't close the tab when I click on &quot;Close Connection&quot;
2) Allow me to use one of my other tabs if one tab has lost its connection

These are potentially two separate issues, but solving either will resolve the issue.

**Comment by TehShrike** [comment]
YES

PLEASE

SO FRUSTRATING TO LOSE ALL MY QUERIES

arstoienarsotienaryubsoybulhyosalhboayuthboanrstioenarsiotenaroisenvozyuxclbyzuxlbcyuzlxcyvulzxcvairjalrsotyularostyulaorsytulaorstyularosytuarlst

**Comment by cmiller86** [comment]
Please address this. A lost connection in one tab should not affect the other tabs. Ideally, it shouldn't throw any warning dialogs until you are trying to perform an action in a lost connection tab.

**Comment by TehShrike** [comment]
To reiterate: there exists in Sequel Pro a case in which tabs will close without the users consent, without giving the user any chance to save or recover their work in the editor.

I consider this a bug.  I believe this issue is miscategorized as a feature request.

**Comment by collinstocks-oscar** [comment]
What's the best way to help get this issue resolved? This was originally reported in August 2011.

**Comment by TehShrike** [comment]
Would a project maintainer please add the "Bug" label to this issue?

**Comment by dmoagx** [comment]
@collinstocks-oscar Sequel Pro's current architecture is heavily dependent on there being a connection available. The sole reason for this (indisputably annoying) dialog is that none of the code is designed to work without a connection and SP would likely crash right away if you tried to keep the connection window open after closing the connection.
This probably requires a major internal redesign of the way we interact with MySQL in general.

**Comment by TehShrike** [comment]
I figured something like that was the case.

I don't know if the re-architecture is worth it in general, I don't have the knowledge of the codebase to start guessing at that.

I would totally accept hacky workarounds like "pop up an optional file save dialog before finally recognizing the connection as closed" or even "optionally write the tab contents to the clipboard before closing".

Even acknowledging the large scope of the rewrite for a "proper" fix, I think it's still correct to consider this behavior a bug, and not a missing feature.

**Comment by collinstocks-oscar** [comment]
A "Save Query" option would solve all the pain I've seen caused by this.
