### ISSUE TITLE
Changing favorite password gives error -25300

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#1214]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1214
Reporter:agenciab...@gmail.com Date:2011-10-19 14:43:23 Status:Fixed Closed:2011-10-01

<b>What steps will reproduce the problem?</b>
1. go to favorites
2. try to change de password
3. go to another favorite to save the password shows the error -25300

<b>What is the expected output? What do you see instead?</b>
Was expecting to save the password on favorite and it's not working

<b>What version of Sequel Pro are you using? What version of MySQL are you</b>
<b>connecting to on the server?</b>
Bightly build 3448

<b>Please provide any additional information below.</b>

**Comment by chrisncampbell** [comment]
I'm seeing this issue again in the latest version on osx 10.11.5. There is no longer a keychain repair option.

**Comment by abhibeckert** [comment]
Thanks @chrisncampbell, I'll look into it.

**Comment by abhibeckert** [comment]
Cannot reproduce.
