### ISSUE TITLE
[REQ] Add UI support for creating composite FKs

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#1224]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1224
Reporter:sidgrabo...@gmail.com Date:2011-11-02 00:15:47 Status:New

Composite (multi-column) Foreign Key relations are possible under the InnoDB engine.

Currently, it is not possible to create them directly through the GUI within the &quot;Relations&quot; pane.

Furthermore, manually-created composite foreign key constraints appear in the Relations pane as if they are single-column foreign keys.

Screenshot 1 (attached) shows the Relations pane with 2 foreign keys applied to a table.
&quot;courses_ibfk_1&quot; is in actuality a composite foreign key constraint.

Screenshot 2 shows the SQL from the CREATE TABLE syntax, verifying that it is indeed a composite key.

The current state is misleading and inaccurate.

MySQL 5.1.44
Sequel Pro 0.9.9.1

**Comment by laszlokorte** [comment]
Is there any progress regarding this? I've been using SequelPro for years now and beside SublimeText it's one of my favorite developer tools. Creating Composite FKs is the only feature I am 
missing regularly.
