### ISSUE TITLE
[REQ] Warn before executing DML statements without WHERE clause

### ISSUE THREAD

**Issue by ghost** [sequelpro/sequelpro#1231]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1231
Reporter:sick...@gmail.com Date:2011-11-22 10:51:42 Status:WontFix Closed:2012-01-01

Much like Gmail will remind users if they use keywords such as attach in the email without actually attaching a file, sequel pro should have the option to warn users if they hastily execute an insert/update/delete query without any where clause.

**Comment by admehta01** [comment]
This would be a great feature, something that HeidiSQL does and can save a database.
