### ISSUE TITLE
Unable to (easily) clear the "is empty"/NULL/NOT NULL and other filters on the table

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#1243]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1243
Reporter:skinny.b...@gmail.com Date:2011-12-06 04:23:45 Status:Accepted

<b>What steps will reproduce the problem?</b>
1. get to content view
2. in top search select a column and is empty

Unlike the &quot;is&quot;/=/LIKE filters most of others does not have an (x) to disable them. So you have to select some other filter (and clear it) to get to the unfiltered content.

I suggest adding an (x) not to a search's text field, but rather after a &quot;Filter&quot; button. The 3451 has just a nice place there for it.

Thank you!

**Comment by jameswagoner** [comment]
I too run into this issue, I have to close and reopen the connection to get those filters to close.
