### ISSUE TITLE
[REQ] Warn before closing tab

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#1248]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1248
Reporter:gjr...@gmail.com Date:2011-12-15 12:30:14 Status:OpinionPoll

Currently, with the way the tab structure works, it's fairly easy (and unfortunately all too common for me) to close your tab while you currently have an open, unsaved query written.  While I love Sequel Pro, it currently handles tabs a bit differently than some other database clients.

Example:
As a user, I'm writing a rather long and complex query, utilizing tables where I might not have the structure memorized.  In such cases, I'll click on the appropriate table in the tables list, and then click on the Structure button above the tab bar.  I'm now viewing the structure of the table in the same tab that my long, complex query is currently written in.  For one reason or another, an user can forget they currently have that query written in the background (they get pulled away from their desk, they're using many tabs, etc.), since they only see the structure of the table.  As such, they close the tab forgetting the query is there.  Since there's no notification or warning telling them that they have a query written in the background, the tab promptly closes and now their query is gone.  A feature prompting the user to save before closing the tab (if there is code written in the background) would be a valuable feature potentially saving users from themselves.

Currently, both SQL Server and Toad for Oracle (the only other two database clients I'm really familiar with) allow you to view the structure of a table while also writing your code.

SQL Server handles this in two different ways:
1. A tree structure for the database -&gt; table -&gt; columns views.  You're able to expand your database, which then allows you to see your tables, which you can then expand to see your columns, all while still seeing your code in the main window.
2. If you were to want to view the full structure of a table (columns, data types, contraints, etc.), double-clicking on the table along the left side will open up that structure in a new tab, keeping your query open in its original tab.

Toad for Oracle has a similar feature to the &quot;Show Table Information&quot; pop up that Sequel Pro has - when selecting a table in the table browser, you are able to view the structure of that table in the little table information pane, while still keeping your code open in the main window.

Again, I think this would be a valuable feature and create a little bit of safety for the users from themselves (me in particular).

Regardless, I'm a huge fan of Sequel Pro and continue to use it on a daily basis.  Thank you.

**Comment by jayshepherd** [comment]
+1

I also have lost important queries because I quit accidentally. This isn't limited to just tabs, but to the app itself (or last tab?)

If it's against a standard or maybe potentially annoying, there could be a flag in settings for enabling it. (See Google Chrome's "Warn before Quitting")

One of the reasons I tend to lose work is because apps like Sublime Text quit, but keep your unsaved work in temporary / auto-saved files. IMO, that would be the ideal solution because I can also go back and review prior work without having to worry about saving.

**Comment by djansyle** [comment]
+1

I think this should be added, also experiencing closing the application accidentally and there with important queries. I think saving session, on close without prompt is a much better way if you really wanted to eliminate popups then, whenever you open the app it will automatically load the last session.
