### ISSUE TITLE
[REQ] Rightclick behavior in table pane

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#1250]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1250
Reporter:sukram.r...@googlemail.com Date:2011-12-19 23:59:36 Status:Accepted

When doing a rightclick on the left handed table pane, it opens the rightclicked table in the current tab, immediately. This is nasty, when I just want to do a context sensitive action like emptying or opening in a new tab/window.

**Comment by marcusfritze** [comment]
I think this should be fixed.

It's very annoying, when I have a table selected and want to look at another table with "right click open in new tab". The data of the right-click-elected table will be loaded.

Like in Finder, there is a "right-click-selection" (only border highlight) and "left-click-selection" (full highlight).

Like in Finder, the "right-click-selection" doesn't load the content, but the "left-click-selection" does.

Thanks.

**Comment by webmaestro** [comment]
+1 to FIX!

Just checked Finder in Mac OS X 10.11.5 (15F34) El Capitan. It does _not_ switch current tab. It leaves old tab alone & opens a new Tab w the selected location.

Please fix! I often need to open multiple tables (e.g., browse `server` and need to compare w relation tables, `server_ip`, `server_status`, `server_fun`) so I can compare and contrast.

**Comment by webmaestro** [comment]
BTW, I have two obvious kludge-workarounds:

1. Open the CURRENT table in a new tab, and then, in the newly opened 'clone' tab, open the one I really want.
2. Use the 'Open Table in New Tab' contextual menu item to open the table I want in a new tab, then switch back to the other 'cloned' tab, and hit the 'Back' button.

I do the 1st if I REMEMBER the Open Table in New Tab's annoying behavior. I do the 2nd if I FORGET the Open Table in New Tab's annoying behavior.
