### ISSUE TITLE
[REQ] Add SQLite support

### ISSUE THREAD

**Issue by ghost** [sequelpro/sequelpro#1260]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1260
Reporter:vashisht...@gmail.com Date:2012-01-13 22:14:17 Status:Duplicate Closed:2012-01-01

SQLite has become increasingly popular due to its use in iOS as well as Android applications. Is there a possibility that SQLite support will be added to Sequel Pro?

**Comment by Ahti** [comment]
I am not familiar with the SequelPro code base. Could someone who is maybe take a minute to come up with a short overview of what would be required to implement this? Am I right in the assuming that this would be more of a model job rather than UI?

**Comment by dmoagx** [comment]
Duplicate of #362
