### ISSUE TITLE
[REQ] Jump to first / last page

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#1264]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1264
Reporter:m...@dthought.net Date:2012-01-28 02:54:33 Status:Accepted

Just a simple one - it would be nice to be able to jump to the first or last page of a list of data. I know it's possible to just type a really large number into the jump list, but that isn't really intuitive.

Generally, the data I want to see is usually at either the start or the end rather than the middle, so being able to quickly get there would be excellent.

I guess two extra buttons could be added to the page jump, or alternatively a keyboard modified could change the buttons (with feedback, e.g. like when creating a Smart Playlist in iTunes).

Thanks!

**Comment by emjayess** [comment]
2013...2017 - has this feature been implemented? I've been looking for it.
