### ISSUE TITLE
[REQ] option to remember the (last) table sorting

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#1268]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1268
Reporter:skinny.b...@gmail.com Date:2012-02-06 02:43:56 Status:OpinionPoll

How about adding an option to remember the (last) table sorting order in content viewer? We do a lot of editing in here and sorting by id desc every time we come here is... well, annoying :)

**Comment by lostminds** [comment]
Hello, I'd just like to support this feature request. I'm not sure about the technical caching issues you've been discussing, but from a usability point of view it would be great to have Sequel Pro just remember the last sorting order I used in Sequel when viewing a specific table. 

Use-case: Typically I have tables with a lot of rows (so only the first 1000 are loaded), with one of the later columns being a date or timestamp. I often want to view the newest rows, so when viewing the table I'll change the sorting order to date by clicking this column header, and then again to get it reversed. In other words I'll often have to load the table three times to get the view I want. If the application would remember and load the sorting order I last used this would eliminate two of these loads.
