### ISSUE TITLE
ERM

### ISSUE THREAD

**Issue by ghost** [sequelpro/sequelpro#1277]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1277
Reporter:charlesm...@gmail.com Date:2012-02-15 21:14:20 Status:Duplicate Closed:2012-03-01

Hi,

So far I found sequel pro very easy and simple to use, I use it for my freelance projects and also school stuffs.

I was wondering if it would be possible to implement ERM with UI to drag between the entities and to be able to download it as image, I have attached a sample below from sqleditor.

Although I see there is a relationship tab but I don't really get how it works, it only links me the table.

Thanks,
![design-medium](https://cloud.githubusercontent.com/assets/5793864/7518691/c44d4082-f4dc-11e4-9cc6-e2b2fc1338ac.png)

**Comment by CIRCLE73** [comment]
I'm also hoping to see this feature implemented in a near future.
I came here to ask for this same feature and found this request.
Sequel Pro managed to create the simplest database manager in the world so I'm wondering how would they implement such a feature like EER modeling.
Thank you for your great work and I very hope you to implement this request ;)

**Comment by dmoagx** [comment]
Duplicate of #101
