### ISSUE TITLE
[REQ] Export multiple databases from a server at once

### ISSUE THREAD

**Issue by ghost** [sequelpro/sequelpro#1299]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1299
Reporter:wouter.a...@gmail.com Date:2012-03-18 10:39:03 Status:WontFix Closed:2012-05-01

When I reinstall my OSX (with testserver) I export all the mySQL databases on a mySQL server at once. This is at the moment the only reason why I still have phpmyadmin installed next to Sequel Pro.

**Comment by solebox** [comment]
makes no sense
