### ISSUE TITLE
[REQ] Allow changing of keyboard shortcuts

### ISSUE THREAD

**Issue by ghost** [sequelpro/sequelpro#1310]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1310
Reporter:swro...@gmail.com Date:2012-03-26 14:02:22 Status:WontFix Closed:2012-05-01

I'd really like to be able to change keyboard shortcuts, specifically one: Command+S to &quot;Save Query&quot; rather than &quot;Save Connection&quot;. I have a lot of query files that I work with and I want to be able to save them quickly. It would also be nice if you're working with a file you've previously saved, or opened from a .sql file, that &quot;Save Query&quot; would save over the same file rather than prompting every time.

**Comment by slifin** [comment]
Presumably this works with other commands, is there a list of menu items that are possible to assign somewhere?

**Comment by lsunol** [comment]
> Presumably this works with other commands, is there a list of menu items that are possible to assign somewhere?

I'd like to overwrite the "Run current query or selection" but that text doesn't seem to work...

**Comment by casivido** [comment]
> I'd like to overwrite the "Run current query or selection" but that text doesn't seem to work... Would be great if we could have that list of assignable items.
