### ISSUE TITLE
Can't change export path

### ISSUE THREAD

**Issue by ghost** [sequelpro/sequelpro#1326]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1326
Reporter:powell....@gmail.com Date:2012-05-02 05:59:50 Status:WontFix Closed:2012-06-01
1. Select database
2. File &gt; Export &gt; Change... &gt; Select Directory

Export path fails to update...

Sequel Pro 0.9.9.1 Build 3408
MySQL 5.5.20 (installed from Homebrew)

**Comment by hoboken** [comment]
It is hard to fathom the exact same difficulty is encountered over five and a half years later. 
<img width="489" alt="Screen Shot 2019-08-08 at 5 52 05 PM" src="https://user-images.githubusercontent.com/2238171/62740251-55e22e80-ba05-11e9-8f3d-77defaac9831.png">
on macOS High Sierra
Version 10.13.4
In this case, one is exporting results, The little gear on the bottom, choose Export result, as csv file, in the popup window by input field "Path:" which is not editable, select the button to right, "Change", try to change the path and it won't accept whatever is chosen. 
 Please reopen this ticket or let me know I should file another.
