### ISSUE TITLE
[REQ] Connection set charset

### ISSUE THREAD

**Issue by ghost** [sequelpro/sequelpro#1329]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1329
Reporter:devzone...@gmail.com Date:2012-05-02 13:09:09 Status:WontFix Closed:2012-06-01

Need connect to server set charset encoding manual

**Comment by micate** [comment]
It's something like this:

* in SQLYog:
> You can put a command in the '初始化命令', eg: 
> ```sql
set charset utf8;
> ```
> ![qq20150630-1 2x](https://cloud.githubusercontent.com/assets/433481/8424233/02ec0e46-1f2a-11e5-95f6-2b020f0526d2.png)

* in Navicat:
> You can uncheck the '使用 MySQL 字符集' option, choose '编码' manually
> ![qq20150630-2 2x](https://cloud.githubusercontent.com/assets/433481/8424237/0eb26392-1f2a-11e5-99a4-d7aaebff5577.png)
