### ISSUE TITLE
[REQ] Allow setting wildcard privileges in user management

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#1371]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1371
Reporter:k.an...@gmail.com Date:2012-06-11 08:31:59 Status:New

MySQL allows users to have wildcard privileges. This allows you to grant a user a set of permissions on a set of databases. This is useful in the context where you have an application which generates separate databases for its users, yet the application itself needs blanket access to all these databases (but: it doesn't need global access). Sequel Pro currently does not support this, because in the user privilege manager the schema can only be chosen from a list of actually existing schemata.

To clarify with an example (assume _ to be properly escaped all the time, for clarity's sake).

-- begin example --
For each customer the application creates a database following the format app_c_&lt;customer_id&gt;, and For each database, it creates a matching user &quot;app_c_&lt;customer_id&gt;&quot;, which is granted SELECT, UPDATE and INSERT privileges on its own database. The purpose of this is to ensure each user of the application is strictly separated from other users' data (and is a business requirement). So, each customer that is logged in connects using their own limited database user account... so far so good!

Admins, however, need to be able to perform actions across customer databases. In order for that to work, an extra MySQL user is created called app_admin. This user gets wildcard permissions on app_c_% for SELECT, CREATE, ALTER, DROP and INDEX. This means that it has access to all the databases running under app_c_#, with other permissions. It's this part that does not play well with Sequel Pro, because we can not select app_c_% as the target for the permissions, since Sequel Pro only allows us to select the (currently existing!) databases. The wildcard has the distinct advantages of also matching newly created databases without having to alter the permissions on the app_admin user.
-- end example --

In the GUI, I would propose a + button to be added to the list, allowing me to type in a custom schema value, instead of being restricted to the list currently present.

**Comment by bhuvidya** [comment]
any progress on this?

**Comment by abhibeckert** [comment]
@bhuvidya nobody is currently working on it. Feel free to submit a pull request.
