### ISSUE TITLE
Add Copy/Paste and Drag/Drop support for table content

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#138]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=138
Reporter:schlabbe...@gmail.com Date:2009-01-05 20:39:31 Status:Accepted

When working with development/production servers I often have to add
fields/columns to a table on the development server and then later on the
production server.
So today it occured to me that the most intutive way to migrate the
production server would be to select all rows on server A and then drop
them in the table on server B, neither seems possible at the moment (<a href="/p/sequel-pro/source/detail?r=290">r290</a>).

**Comment by fulldecent** [comment]
Copy / export is implemented in #106 recommending close issue.

**Comment by abhibeckert** [comment]
Copy is implemented, but not paste.

And it's not possible to drag/drop either. We will keep this open.
