### ISSUE TITLE
[REQ]  Pin tables

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#1391]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1391
Reporter:tim.stcl...@gmail.com Date:2012-07-02 18:03:23 Status:New

I would like to be able to pin tables and views so that when a search changes, the pinned tables stay visible. I currently have to have multiple tabs connecting to the same DB and switch this way. you currently have &quot;current selection&quot; maintained when re-filtering the list; pinned tables would work like that - always visible.

**Comment by DomBlack** [comment]
I feel the ability to pin tables in the filtered table list (even if they don't match current criteria) would be incredibly useful. I find when working on features I'm often switching back between three or four tables in a single database using the filter. The UI which shows "current" selection is perfect for pinned tables.

<img width="200" alt="screen shot 2016-12-05 at 15 33 16" src="https://cloud.githubusercontent.com/assets/236641/20890805/30785748-bb00-11e6-99ae-e44a33b692cf.png">

**Comment by nawlbergs** [comment]
I too would really enjoy this.  Our database has around 100 tables... when working with 3 or more tables.. its very hard to switch between them easily.

**Comment by coreysan** [comment]
+1 this must be a very common use-case and is my only real gripe in a very well-written application

**Comment by ajant** [comment]
+1

**Comment by Sofianio** [comment]
+1
was thinking of manually organizing them, but this work too

**Comment by robertding** [comment]
is this feature still in progress?

**Comment by Sofianio** [comment]
My workaround, if anyone needs it
![sc](https://user-images.githubusercontent.com/14220889/56565688-dbea7e80-65a8-11e9-97e6-f725c501452c.png)

The order is still alphabetic tho :/

**Comment by robbie-thompson** [comment]
+1

**Comment by marcomasotti** [comment]
Any news about this feature?
