### ISSUE TITLE
Importing &gt; Update Database 

### ISSUE THREAD

**Issue by ghost** [sequelpro/sequelpro#1392]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1392
Reporter:jazzybea...@gmail.com Date:2012-07-02 18:28:44 Status:WontFix Closed:2013-10-24

<b>What steps will reproduce the problem?</b>
1. Export DB Table in CVS file
2. Import DB Table CVS file
3. Select Import Method Update
4. Import button is disabled ???

<b>What is the expected output? What do you see instead?</b>
I'm tyring to update db tabels. But I can't gt Import button when i select Import method UPDATE.

<b>What version of Sequel Pro are you using? What version of MySQL are you</b>
<b>connecting to on the server?</b>
Latest version on my locale.

**Comment by JeremyRYoung** [comment]
wow i have been struggling with this for years, ever since I started using SequelPro! I had been assuming there was a problem with my database structure.  It works perfectly now but that really is a bit too cryptic.
