### ISSUE TITLE
[REQ] Export favorites

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#1405]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1405
Reporter:saltzman...@gmail.com Date:2012-07-19 08:28:38 Status:Accepted

Just like we have Query Favorites it would be nice to have Export Favorites. I find myself updating my local db with info from my Live DB to test things before I make them live. I may have to do the same export of specific tables multiple times.

**Comment by stuconnolly** [comment]
Exporting connection favourites has been support for quite a while now.
