### ISSUE TITLE
[REQ] Notification Center Support

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#1420]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1420
Reporter:schlabbe...@gmail.com Date:2012-08-09 13:52:44 Status:Accepted

Now with 10.8 we should add support for Notification center.

This should probably be an option group in Prefs between Growl / Notification Center
- On 10.8 default to Notification Center
- On older versions only show a Growl checkbox
- DIsable the Growl option if it is not installed (and show a little help text)

**Comment by stuconnolly** [comment]
Added in 918324e. Already available in 1.1.2
