### ISSUE TITLE
Content filter placeholder remains

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#1430]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1430
Reporter:johan.so...@gmail.com Date:2012-08-17 07:01:33 Status:Accepted

<b>What steps will reproduce the problem?</b>
1. Edit -&gt; Find to bring up content filter. 
2. Filter operator is LIKE '%@%'
3. Enter filter text in a column, for example john

Expected WHERE query: `name` LIKE '%john%'
Instead I get `name` LIKE '%john@%'
The placeholder is still there and the query doesn't work. 

Nightly build 3778

**Comment by stuconnolly** [comment]
Considering OS X 10.6 is over 7 years old now and this was raised over 4 years ago, this is unlikely to be fixed.

Support for any OS version before either 10.8 or 10.9 is going to be dropped in the very near future.
