### ISSUE TITLE
[REQ] Update Sequel Pro icons to be Retina resolution

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#1432]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1432
Reporter:mattlangtree Date:2012-08-19 18:56:29 Status:Started

With the introduction of the &quot;retina&quot; resolutions and the Retina MacBook Pro more apps are updating their icons to show nicely at these high resolutions.

It would be great to have crisp, pretty icons like all of the Apple apps!

N.B - On Lion there was a way to set your Mac to make its pixels behave in the same way as the new retina Macs do, but I can't find a way to do that in Mountain Lion anymore on my 27&quot; iMac.

This request affects both Lion and Mountain Lion.

**Comment by stuconnolly** [comment]
All icons/images have been high resolution for a while now. The discussion around the 'suitability' of the icon is a different matter.
