### ISSUE TITLE
[REQ] Copy ASCII Table to Clipboard

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#1436]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1436
Reporter:t...@timheckman.net Date:2012-08-21 22:27:18 Status:New

It's often, when collaborating with colleagues, that I'd like to be able to copy an ASCII table of results to my clipboard (such as how the MySQL CLi prints out the results).  I can then include this in a pastebin, or an email, without having an issue where the other column copy method doesn't properly line up the information.

**Comment by jontebol** [comment]
+1

Would be awesome to be able to copy/paste directly into a Github issue (and get Github's table formatting)! Currently I export as a CSV, open in Numbers, copy the table there and then paste into Github. That works, but would be awesome to do it directly from SequelPro like the JSON-copy-function.
