### ISSUE TITLE
[REQ] Browsing relations usability maximization 

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#1444]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1444
Reporter:pavel.p...@gmail.com Date:2012-08-30 13:14:07 Status:New

Hi, I really love the way I can browse within related tables (according to foreign keys). I have a couple of suggestions to maximize this user experience:
1. allow browsing in related content in query results (as it is done in plain table contents view) - with the combination of favourite queries this would be a killer feature
2. allow swipe on the trackpad to go back and forward in table history (like in Safari)
3. allow browsing in &quot;back-tracked&quot; relations. Now you can browse from the source table to the destination. But many times you need to find the source from the destination (more source foreign keys pointing to one destination). You could display a small &quot;popup&quot; with the selection of possible source tables and let user to choose one.

Thank you a lot for your effort, your app is the best for MySQL!

**Comment by jmisur** [comment]
+1 This would be an awesome enhancement (#3) - @sequelpro is there any plan to actually implement this?
