### ISSUE TITLE
[REQ] Query Editor code commenting

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#1478]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1478
Reporter:bradley....@gmail.com Date:2012-10-08 09:31:07 Status:New

Highlight code in Query Editor and have one or all of the following options:
1. Edit -&gt; Comment Selected Code
2. Gear -&gt; Comment Selected Code
3. Right Click -&gt; Comment Selected Code
4. Command &quot; -&gt; Comment Selected Code
    Shift Command &quot; -&gt; Un-Comment Selected Code

Regards,
Bradley Giesbrecht

**Comment by iBobik** [comment]
Also on MacBooks with Czech keyboard it is not working with shortcut cmd+/

**Comment by iBobik** [comment]
Why?


4. 1. 2017 v 20:24, Max Lohrmann <notifications@github.com>:

**Comment by abhibeckert** [comment]
@iBobik because this is an enhancement issue and you're describing a bug - which is higher priority and will be worked on sooner.

**Comment by iBobik** [comment]
Now understands. Thanks :-)
