### ISSUE TITLE
[REQ] Allow for parameters in queries

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#1525]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1525
Reporter:kuehn.k...@gmail.com Date:2013-01-07 10:52:33 Status:New

When working with Sequel Pro for development work my queries usually are parameterized in the code I am working on, but while writing them I need to use hard-coded values in Sequel Pro. This leaves me with a bit of work to do every time I move my queries into or out of Sequel Pro. Just to make perfectly clear:

In hypothetical code that I am troubleshooting I have the following query:

select id, name from widgets where id = ?
or (if allowed in the language)
select id, name from widgets where id = %(widgetId)d

As it currently stands I would have the replace the &quot;?&quot; or &quot;%(widgetId)d&quot; with my test value on the way in, and the once I had the corrected version done I would have to un-replace them on the way back out. In my example this would not be very hard, but I have a number of queries that I run that have hundreds of lines, with ten or more parameters (typically the same one pushed into multiple subqueries for performance reasons).

I would rather that Sequel Pro would add in an optional pane/dropdown that could allow me to specify the parameters that I wanted, and then either pass this along to the MySQL driver, or (if need be) do the replacements itself before passing it along to the driver.

As indicated above, it would be nice to have both the ordered form of parameters, as well as the named version (the latter is really helpful to me in my big queries to not have to count out the right patters). My idea on that is to have one or more modes, e.g.: Perl/?, Python (array), Python (dict), etc...

**Comment by renatogcarvalho** [comment]
Any idea if we can get this implemented in the UI anytime soon?

In my opinion is a very important feature that we don't have in Sequel Pro right now for the biggest reason that in most environments queries are parameterized (or prepared) in a given language is to avoid SQL Injection. 

I also find myself searching/replacing the parameters if I have to debug a query from an application.

Renato.
