### ISSUE TITLE
[REQ] Main Toolbar icon revamp

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#1526]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1526
Reporter:mattlangtree Date:2013-01-07 19:19:05 Status:New

Update the main toolbar to use Round Textured buttons (ala Safari, Mail, et al).

Background:
In the process of designing/upgrading to Retina-quality graphics in the 1.0 release I found it increasingly common that icons had to be completely redone from scratch to generate the higher resolutions required. When I was researching other apps and the actions their icons were depicting I found a trend that most apps were moving away from full colour detailed icons towards vector-based shapes in round-textured buttons.

See the NSTexturedRoundedBezelStyle here: <a href="http://developer.apple.com/library/mac/#documentation/userexperience/conceptual/applehiguidelines/Controls/Controls.html%23//apple_ref/doc/uid/TP30000359-SW5" rel="nofollow">http://developer.apple.com/library/mac/#documentation/userexperience/conceptual/applehiguidelines/Controls/Controls.html%23//apple_ref/doc/uid/TP30000359-SW5</a> and any recently released app window frames.

There seems to be an aesthetic shift towards this icon style and I would like to see Sequel Pro follow the trend. Constructive feedback/possible designs are welcome in the comments.

**Comment by stuconnolly** [comment]
Personally don't see any issue with the current icons and given this was logged in 2013 the style of icons being referred to isn't really relevant anymore.

Any change in icons should be covered under #2730.
