### ISSUE TITLE
[REQ] Copy results should give a table

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#1535]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1535
Reporter:haavard.pedersen Date:2013-01-21 01:52:59 Status:New

When copying results I should be able to paste them into a Word document or other rich text editor as a table. As it is now, people ask me for a specialized query, I write it, paste the results into an email, and its completely unreadable. :(

**Comment by samuelbradshaw** [comment]
A workaround is to copy and paste into a spreadsheet program, then copy from the spreadsheet into a rich text editor.
