### ISSUE TITLE
[REQ] Make DB Export Settings Persistent

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#1538]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1538
Reporter:bcorco...@gmail.com Date:2013-01-22 10:45:02 Status:New

The database export settings reset on every launch of the program, with some settings resetting for every new export.

It would be nice to have (at least as an option) to keep the last used DB export settings.

Main reasons:
- Having to check &quot;Auto increment value&quot; on every export
- Having to change the DB export folder on every application load

The odd part is, certain things _are_ persistent (or so it seems?), such as the compression method, so it seems this behavior is at least partially implemented.

**Comment by dland** [comment]
Hear, hear.

I find myself constantly unchecking "Put field names in first row", setting Terminate to \t and Wrap to '' (empty). When I need to export a result set, it's because I'm going to do some data munging, and tab-separated is trivial to deal with in AWK or Perl.
