### ISSUE TITLE
Duplicate Database won't copy default encoding

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#1558]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1558
Reporter:yhben...@gmail.com Date:2013-01-29 17:26:33 Status:New

<b>What steps will reproduce the problem?</b>
1. Create database in Sequel Pro, set default character encoding to something non-default (in example below, utf8), or select existing database
2. Select Database | Duplicate Database
3. Observe that new database has server-wide character default, not character encoding of original database

<b>What is the expected output?</b>
Console log of the above should be:
/\* Create original database _/
CREATE DATABASE `test_utf8` DEFAULT CHARACTER SET `utf8`;
USE `test_utf8`;
/_ Duplicate database to test_utf8_duplicate */
CREATE DATABASE `test_utf8_duplicate` DEFAULT CHARACTER SET `utf8`;
USE `test_utf8_duplicate`;

<b>What do you see instead?</b>
CREATE DATABASE `test_utf8` DEFAULT CHARACTER SET `utf8`;
USE `test_utf8`;
CREATE DATABASE `test_utf8_duplicate`; /\* Should have character set info */
USE `test_utf8_duplicate`;

When running:
select DEFAULT_CHARACTER_SET_NAME from information_schema.SCHEMATA where SCHEMA_NAME = 'test_utf8_duplicate';
Expected value should be 'utf8'.  It is 'latin1' in my case, the server default.

What version of Sequel Pro are you using? 1.0 (Build 3991)
What version of OS X are you using? 10.8.2
What version of MySQL are you connecting to on the server? MySQL 5.5.27-log

<b>Please provide any additional information below.</b>

**Comment by stuconnolly** [comment]
This was actually fixed by #2082 in March 2015.
