### ISSUE TITLE
Crashes on connect to Sphinx server

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#1596]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1596
Reporter:andrew.m...@gmail.com Date:2013-02-06 07:11:35 Status:New

<b>What steps will reproduce the problem?</b>
1. Start up the Sphinx searchd daemon, with a `listen = localhost:9306:mysql41 to development.sphinx.conf`in the searchd block.
2. Connect via sequel pro to the port 9306 on localhost

<b>What is the expected output?</b>

Sphinx supports the MySQL 4.1 protocol for searching their full text indexes; you can use the `mysql` command line client to connect to it and issue queries and see results. I was hoping to see the list of indexes as tables, and then be able to issue custom queries and see the results in the GUI.

<b>What do you see instead?</b>

It crashes on startup. I send the bug report with the stacktrace.

<b>What version of Sequel Pro are you using?</b>

1.0.1 build 4004

<b>What version of OS X are you using?</b>

10.8.2

<b>What version of MySQL are you connecting to on the server?</b>

I'm using Sphinx 2.0.3 (<a href="/p/sequel-pro/source/detail?r=3043">r3043</a>)

<b>Please provide any additional information below.</b>

More details about Sphinx support for the MySQL protocol can be found here

<a href="http://sphinxsearch.com/docs/1.10/sphinxql.html" rel="nofollow">http://sphinxsearch.com/docs/1.10/sphinxql.html</a>

**Comment by 2ge** [comment]
would be great if connecting to SphinxSearch (SphinxQL) is supported. Is there some workaround on this ? It is be compatible with mysql 4.1 protocol

Using Sequel Pro 1.0.2 b4096

**Comment by dmoagx** [comment]
Sequel Pro should no longer crash when connecting to sphinxql (see #2302) but that doesn't mean Sphinx will work now, either.

**Comment by larspohlmann** [comment]
It's crashing for me.
