### ISSUE TITLE
System Profile info in Sparkle broken

### ISSUE THREAD

**Issue by ghost** [sequelpro/sequelpro#1602]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1602
Reporter:schlabbe...@gmail.com Date:2013-02-08 05:46:42 Status:Accepted

See attached screenshot.
This issue has been present for quite some time now IIRC

![bildschirmfoto 2013-02-08 um 14 45 11](https://f.cloud.github.com/assets/5793864/2304249/fea5516e-a20f-11e3-923f-bb8776c4fa18.png)

**Comment by abhibeckert** [comment]
We don't collect any of this data anyway, and chances are we'd have to upgrade our server if we wanted to.

We should disable the feature.
