### ISSUE TITLE
Can't change ENUM via dropdown while in field editor mode

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#1603]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1603
Reporter:e...@stockopedia.co.uk Date:2013-02-08 06:28:51 Status:Accepted

<b>What steps will reproduce the problem?</b>
1. click the arrrow in an ENUM field while on the content view of a table
2. select an ENUM field from the dropdown

What is the expected output?  I expect the field to change to the selection
What do you see instead?  Nothing happens - (there is no way to change an enum field now !)

Another issue - what steps will reproduce the problem?
1. click the actual ENUM field while on the content view of a table

What is the expected output?  I expect to see a dropdown of ENUM options
What do you see instead?  A text editor !!!!

What version of Sequel Pro are you using?  1.0.1
What version of OS X are you using?   Mountain Lion
What version of MySQL are you connecting to on the server?   unsure - it's the latest !

<b>Please provide any additional information below.</b>

**Comment by fulldecent** [comment]
Duplicate (mostly) of #160. Recommend to close this issue and discuss there.
