### ISSUE TITLE
No support for english language on systems with other languages

### ISSUE THREAD

**Issue by ghost** [sequelpro/sequelpro#1607]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1607
Reporter:henrik.c...@gmail.com Date:2013-02-11 04:08:24 Status:Duplicate Closed:2013-02-01

<b>What steps will reproduce the problem?</b>
1. Open the application
<b>2.</b>
<b>3.</b>

<b>What is the expected output?</b>
English language

<b>What do you see instead?</b>
My OS language

<b>What version of Sequel Pro are you using?</b>
1.0.1 build 4004

<b>What version of OS X are you using?</b>
10.8.2 build 12C3012

<b>What version of MySQL are you connecting to on the server?</b>
Various 5.0, 5.1, 5.5

<b>Please provide any additional information below.</b>

Support to switch language inside the application without using third-party tools.

**Comment by max4ever** [comment]
I have german 🇩🇪 mac with italian 🇮🇹 language installed, yet sequel pro insists on loading german language. That's not the desidered effect :man_facepalming:.
