### ISSUE TITLE
[REQ] Copy as SQL insert without Primary Key

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#1618]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1618
Reporter:belly...@gmail.com Date:2013-02-13 03:29:39 Status:New

Please implement a feature where you can copy the SQL as INSERTs without the primary key to help copy and paste data for testing purposes where there might be primary key conflicts.

**Comment by chlab** [comment]
+1, came here to request this. This makes it way easier to copy data between databases. I have a project where I have certain data like mail templates in the database. This feature would make it really easy to quickly copy my new templates to a staging server.

**Comment by PsycoZL** [comment]
+1, looking for this feature as well.  Created an account specifically to comment that this is wanted.  ;)

**Comment by nafarius333** [comment]
+1, this would be very useful
