### ISSUE TITLE
[REQ] Solarized color schemes for query editor

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#1623]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1623
Reporter:hakamad...@gmail.com Date:2013-02-14 08:58:13 Status:New

I've created two color schemes for the query editor based on the Solarized (<a href="http://ethanschoonover.com/solarized" rel="nofollow">http://ethanschoonover.com/solarized</a>) color palette.  You'd be welcome to add them to the app or make them available via the Sequel Pro website; some web developers might like them for a more consistent look and feel.

**Comment by stuconnolly** [comment]
Adding attachments from Google Code issue:

* [Solarized Light.spTheme](https://github.com/sequelpro/sequelpro/files/888093/Solarized.Light.spTheme.txt)
* [Solarized Dark.spTheme](https://github.com/sequelpro/sequelpro/files/888094/Solarized.Dark.spTheme.txt)
