### ISSUE TITLE
[REQ] Remove spaces from time token, or provide hours/minutes tokens

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#1654]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1654
Reporter:jjea...@gmail.com Date:2013-03-05 10:00:23 Status:New

Currently, the time token outputs time like this: &quot;9-57 AM&quot;

It would be great to be able to output the hours and minutes separately, so you can have an export filename like this:

export_2012-02-09-0955.sql

At the very least, if it would be possible to replace the space between the minutes and the AM/PM designation or choose the 24 hour clock, it would be preferable to having a space in the filename.

**Comment by allybee** [comment]
+1 for using removing AM/PM and replacing with 24 hour clock

**Comment by Visiluna** [comment]
+1 for 24 hour clock instead of AM/PM

**Comment by abhibeckert** [comment]
@Visiluna export does use a 24 hour clock if you enable that in System Preferences -> Language and Region.
