### ISSUE TITLE
Sequel Pro crashes when the user changes from one view to another and doesn't have enough permissions

### ISSUE THREAD

**Issue by ghost** [sequelpro/sequelpro#1655]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1655
Reporter:dani.bae...@frogtek.org Date:2013-03-05 23:59:57 Status:Duplicate Closed:2013-06-21

<b>What steps will reproduce the problem?</b>
1. Import a large database with some views (mine is 3 GB large)
2. Make sure this import creates some views owned by a user which is not previously created on mysql
3. Open Sequel Pro and open that view
4. Sequel Pro complains about lack of permissions
5. Open another view without permissions
6. Sequel Pro crashes (and I couldn't send a crash report from there)

<b>What is the expected output?</b>
It should just complain, so I can assign correct permissions or replace my view to get right ownership
<b>What do you see instead?</b>
A crash where I cannot open the details section and can't send an error report. I just can quit using Cmd + Q

<b>What version of Sequel Pro are you using?</b>
1.0.1 Build 4004
<b>What version of OS X are you using?</b>
10.8.2
<b>What version of MySQL are you connecting to on the server?</b>
5.6.10 Source distribution

<b>Please provide any additional information below.</b>

**Comment by dmoagx** [comment]
Duplicate of #1742
