### ISSUE TITLE
[REQ] Export filtered results to SQL

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#1659]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1659
Reporter:mattcg Date:2013-03-07 10:17:42 Status:New

Currently there's no ability to export filtered results to SQL. Only XML, CSV and Dot are allowed.

Using 'Copy as SQL INSERT' kind of works, but doesn't allow users to take advantage of all the other exporting features like gzip/bzip compression.

Currently what I'm doing to export a ton of records to a compressed SQL file is 'Copy as SQL...' pasting into a file and compressing that file manually. For much larger result sets I run some SQL to copy the records into a new table then export that table.

Allowing users to export filtered results directly would allow them to avoid that workaround and work faster.

**Comment by xlcrr** [comment]
The only way I was able to do this is to "limit" the table by the number of rows requested, filter and export like so
