### ISSUE TITLE
[REQ] support for UTC_TIMESTAMP() when editting contents of datetime field

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#1671]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1671
Reporter:sir...@gmail.com Date:2013-03-19 12:15:52 Status:New

It is already possible to type NOW() in a datetime field to set it to the current date+time. It would be nice if it was possible to type UTC_TIMESTAMP() as well to set it to the current UTC time.

**Comment by bericp1** [comment]
Is this supported yet?

`NOW()` definitely works but when I try to use `UTC_TIMESTAMP()` when inline editing a row, it fills in with `0000-00-00 00:00:00` even though if I manually type out the UDPATE query in the "Query" tab using `UTC_TIMESTAMP()`, it uses the appropriate and correct UTC timestamp.
