### ISSUE TITLE
[REQ] Copy as CSV or simplify export dialog

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#1673]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1673
Reporter:firehed Date:2013-03-21 12:47:38 Status:New

It would be really helpful to have a &quot;copy as CSV&quot; option (similar to the copy as json bundle), and/or a much cleaner+quicker way to export a query result as CSV. The current way to export a result set to CSV is, to put it mildly, tedious - the export dialog is way too complicated with the nonstandard filename section (the number of times I've wanted to use the tokens for automatic file naming in hundreds of exports over several years: one; the number times it's gotten in my way because I literally wanted the word &quot;day&quot; in the file name: more than I can count)

**Comment by tordans** [comment]
I wonder if this was solved via https://github.com/sequelpro/sequelpro/issues/233?
The solution "copy with header" does not format it as a csv with comma, but its pretty close.
Maybe close this an reopen it again if needed @sequelpro?
