### ISSUE TITLE
[REQ] Add "mysql" url scheme

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#1681]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1681
Reporter:ggrit...@gmail.com Date:2013-04-02 01:11:30 Status:New

It would be nice to create links like

mysql://username:password@server:port/databasename

best regards

Gabriel

**Comment by brtdv** [comment]
+1

**Comment by ezzatron** [comment]
+1

**Comment by darianbr** [comment]
+1

**Comment by klickagent** [comment]
+1

**Comment by schmunk42** [comment]
:+1:

**Comment by dmoagx** [comment]
This has been added in the commit above.
Supported URL format for now:
```
mysql://[user[:password]]@][host[:port]][/database]
```

**Comment by schmunk42** [comment]
Works great btw.

**Comment by wesleylancel** [comment]
Is this supposed to work in the latest release? It doesn't seem to have registered the URL handler.

**Comment by dmoagx** [comment]
No, this currently only works in nightly builds.

**Comment by wesleylancel** [comment]
Ah, thanks. Seeing the commit was tagged with `1.1.0.1` I thought it would be in that release.

**Comment by PanMan** [comment]
Is this also supposed to work when creating a connection? Because that would be great! If the host field understood this, and filled the right fields

**Comment by weitzman** [comment]
Any chance this could be expanded to support SSH connections?

FYI, this is still only in the nightly builds - https://sequelpro.com/test-builds

**Comment by dmoagx** [comment]
If there is an existing standard for SSH URLs we'd like to use it before inventing our own, but I don't know any...

**Comment by weitzman** [comment]
Thanks for the reply.

I dont think there is a standard for this. i propose using the url fragment for this. The value is another url with ssh:// scheme. Building upon the current spec (simplified):

`mysql://user:password@host:port/database#ssh://ssh-user:ssh-pass@ssh-host:ssh-port`

- We could require url encoding of `://` in the fragment so that typical url parsing works properly.

**Comment by PanMan** [comment]
Wouldn't the reverse make more sense? The SSH first, as the MySQL goes over the SSH connection, not the other way around.

**Comment by weitzman** [comment]
In that respect your proposal makes sense, But many users dont use ssh
connections, and they would be forced to add null values at the beginning
and then put all their useful data in the fragment. So I think this meets
expectations better.

**Comment by dmoagx** [comment]
I think the fragment is a bad place in general, because it is sometimes considered as optional and stripped. SVN has `svn+ssh://` URLs, but with MySQL the scheme would be more difficult.

**Comment by markcarver** [comment]
Fragments, while possible, are not really appropriate as you can only have one.

[MySQLX](https://dev.mysql.com/doc/connector-net/en/connector-net-ssh-tunneling.html#connector-net-ssh-tunneling-example-5) uses a custom protocol and semi-query string syntax (uses `;` as separators):

```
mysqlx://myUser:test@localhost:33060?sshHostName=10.0.0.2;sshUserName=mySshUser;sshPassword=sshTest
```

Why not just use normal query string parameters instead?

```
mysql://user:password@host:port/database?ssh=user:password@host:port
```

Alternatively, a key could be provided as well:

```
mysql://user:password@host:port/database?ssh=user@host:port&sshKey=~/.ssh/other
```
