### ISSUE TITLE
[REQ] Export to another server

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#1706]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1706
Reporter:to...@7bamboo.com Date:2013-05-03 15:12:41 Status:New

Right now if I want to backup/move to another server, it's sort of a trapeze act of dumping SQL, then uploading it to a new server.

It'd be nice if I could skip that step, and export directly to another server.  Ideally, I'd like to clone all databases from server A to server B.

**Comment by marqu3s** [comment]
I'm also wanting this. Something like HeidiSQL does on Windows. It allows you to another server and database to export tables directly to it. Pretty handy!

**Comment by pdesterlich** [comment]
+1 this would be a great feature and a very useful one
