### ISSUE TITLE
[REQ] Shortcut to scroll to column in the Content view

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#1709]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1709
Reporter:macd...@gmail.com Date:2013-05-08 09:47:57 Status:Accepted

My tables usually have a lot of columns. I always need to scroll left/right to find the one I need information from, which is annoying.

How about an option &quot;Scroll to column…&quot; in the &quot;View&quot; menu (with some shortcut) that I would type a column name and the view would be scrolled to the column? What's more, it could show suggestions, so one could just type &quot;crea&quot; and &quot;created_at&quot;, &quot;created_id&quot; would appear for faster choosing.

**Comment by jimlongo56** [comment]
Is this issue still on the roadmap? It would really be an improvement for navigating across very wide tables.

**Comment by inovek** [comment]
Same question as jumlongo56, this function is something I really miss in Sequel Pro. Because working with tables is mostly combined with much columns and if you don't have luck, customers with tables who don't following any logical concept.
