### ISSUE TITLE
Wrong interface language: Russian instead of English

### ISSUE THREAD

**Issue by ghost** [sequelpro/sequelpro#1734]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1734
Reporter:goo...@jabberwocky.nl Date:2013-06-02 12:26:59 Status:Invalid Closed:2013-07-14

<b>What steps will reproduce the problem?</b>
1. Open the application
<b>2.</b>
<b>3.</b>

<b>What is the expected output?</b>
Interface in English, as it was before.
<b>What do you see instead?</b>
A Russian interface. I can only open it in English now by using an application named 'Language Switcher'.

<b>What version of Sequel Pro are you using?</b>
1.0.2 build 4096
<b>What version of OS X are you using?</b>
10.6.8
<b>What version of MySQL are you connecting to on the server?</b>
I do not know, but it hasn't changed these last days.

<b>Please provide any additional information below.</b>
My language is Dutch and I was using Sequel Pro in English. I had a kernel panic the day before yesterday and Sequel Pro was probably open. I had to (re)start my Mac. I don't know if that has anything to do with the issue. But now I open the application and I only get a Russian interface. There doesn't seem to be a way to set the language and I'm also worried if it could be caused by a Russian hack.

Any help will be highly appreciated!

**Comment by alemachado** [comment]
Hi ghost

The same issue has just happen with me. I was using in Italian (that is my default language on Language Preferences on the OS) but today I found all interface on portoghese (that is my second language on Language Preferences).

**Comment by wangalice** [comment]
I met the same pro and the answer above was worked well to me.

**Comment by vbilenko78** [comment]
Worked for me, thank you.

**Comment by abbychau** [comment]
I would more love to have an option for language explicitly.
