### ISSUE TITLE
[REQ] Database information and stats

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#174]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=174
Reporter:gabrielr...@gmail.com Date:2009-02-20 03:00:25 Status:Accepted

It would be great if Sequel Pro would show more information and stats about the database, in 
addition to table info.

The type of info I'd would find useful is: number of tables, total size, creation date, overhead, etc.

Another way to do this would be with a new view, showing the list of tables with their info, like the 
Structure view in PhpMyAdmin. Double clicking would select the table.

I like a lot the table information area under the panel list. This area could be used to show the total 
number of rows and the size of the selected tables. If no table is selected, the database information 
would be displayed. Same goes for the Table Status tab.

**Comment by fulldecent** [comment]
More info shown in database report.

![screen shot 2017-03-27 at 8 09 41 pm](https://cloud.githubusercontent.com/assets/382183/24383163/64c89d24-1329-11e7-8398-498d5c73f4e5.png)

![screen shot 2017-03-27 at 8 10 01 pm](https://cloud.githubusercontent.com/assets/382183/24383166/67cb2be0-1329-11e7-8695-a151b0cf8993.png)

Recommending close as fixed.
