### ISSUE TITLE
Auto-complete is not working within context (displays non-relevant options)

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#1740]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1740
Reporter:pavel.p...@etnetera.cz Date:2013-06-14 02:59:22 Status:WaitingOnUser

<b>What steps will reproduce the problem?</b>
1. type any SQL select statement until where
2. start typing name of the column
3. wait until auto-complete window shows
4. you will see probably all possible options in all databases, whether applicable or not. In the previous version this could be workaround by defining an alias for the table in the select statement and use alias + dot for displaying only columns from that table but now it displays all options, even when I try to use alias+dot

<b>What is the expected output?</b>
auto-complete options based on the context (do not offer options not applicable in that place)

<b>What do you see instead?</b>
all options

<b>What version of Sequel Pro are you using?</b>
1.0.2 (Build 4096)

<b>What version of OS X are you using?</b>
10.8.4

<b>What version of MySQL are you connecting to on the server?</b>
version = 5.5.28-29.1

**Comment by dmoagx** [comment]
Issue is too old to be able to triage it now and since it was imported from Google Code we have no way to contact the original reporter, either. Closing.
