### ISSUE TITLE
[REQ] Add a disconnect button

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#1744]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1744
Reporter:gruber.k...@gmail.com Date:2013-06-20 00:38:31 Status:New

Sequel Pro is missing a very important feature: a disconnect button. Every time when I am connected to a server, and want to connect to an another one, either I have to close the window, open a new one and connect to the other server or do the same with tabs. I think it would be much better if I could just press a disconnect button.

**Comment by joelstein** [comment]
I would also really like something like this. I often want to disconnect from the current database and choose another favorite, but to do this I have to take several actions:

* New tab
* Select new database favorite
* Close original tab

Perhaps you could add to the interface a way to switch favorites?

**Comment by billynoah** [comment]
+1

I am surprised this still hasn't been added with the release of 1.1.  Please, please, please add this feature.  I've made a personal monetary contribution to this project if that counts for anything.  At the very least can we get a response from the development team about whether or not this is on the radar?

**Comment by dmoagx** [comment]
Well there is a rather easy workaround: close the tab and open a new one.

On the other hand resetting a tab to its initial state will probably require a much higher coding effort, so this is a very low priority issue.

**Comment by billynoah** [comment]
In that case as a short term solution, could there just be a button "DISCONNECT" that performs both of those actions at once?  It would be a single button the removes the need for user doing a workaround by making it part of the UI.

**Comment by slamorte** [comment]
If you have code open in the query window, and close the tab to open a new connection, the code needs to be copy-paste to the new tab. Would be so much easier to have an option to Close Connection and then open another connection.

**Comment by zak-tribe** [comment]
> Well there is a rather easy workaround: close the tab and open a new one.
> 
> On the other hand resetting a tab to its initial state will probably require a much higher coding effort, so this is a very low priority issue.

Unfortunately closing the tab does not disconnect from the mysql server immediately, I learnt the hard way when I hit my maximum connections by closing Sequel Pro tab and re-opening it too many times. Would be really good to see this feature

**Comment by hroger1030** [comment]
Why does this feature not exist? Is closing the entire app the way that one is expected to disconnect the last db connection? You can close tabs for all but the last tab, why don't you just show the tab bar at all times?

**Comment by DanDawson** [comment]
It is six years after the initial post, and here I am searching Google for how to disconnect and it leads me to this issue. I have discovered of course that closing the window disconnects in the background, but I have also experienced closing the window causing an application crash. Seems to be working for me at the moment though.

**Comment by janacm** [comment]
Still no disconnect button. On Mac, press `cmd + t` to open a new tab, and then `cmd+w` to close the old tab once you switched over to it.

**Comment by okadots** [comment]
I am also experiencing an issue where if you close the active window, the app reliably crashes.

**Comment by dartworksnz** [comment]
Yip, me too, its actually quite a pain, as this happens consistently on my mac and many times a day.

**Comment by Shaun1** [comment]
9 years later and this is feature is still missing. What the heck?
