### ISSUE TITLE
Double-click to edit in Content view jumps to different row, regularly

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#1756]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1756
Reporter:RickTuck...@gmail.com Date:2013-07-05 15:31:40 Status:New

<b>What steps will reproduce the problem?</b>
1. Double-click to open a TEXT field.  Pop-up edit box appears.  I make changes. I click OK.
2. I then double-click another TEXT field, typically the one just below the one just edited.
3. Instead of the desired TEXT field pop-up edit box appearing, a pop-up edit box for another row appears, and the row selected is the new row.

This happens repeatedly.  It doesn't seem to happen if I ESC or Cancel out of the edit box, but does if I OK out of the edit box. To avoid it, I use the UP-ARROW cursor key and then DOWN-ARROW cursor key, and then I can double-click on the row I want and it comes up in the edit box.

I am editing each entry of a field that already has text in it (I have a filter on: ColumnName is not empty). I am going down row by row, editing some and not others.  So for example, now I am currently editing a row that's around 20% down in the list of rows, and when after the errant jump to another row occurs, I am around 67% down in the list of rows.

<b>What is the expected output?</b>
<b>What do you see instead?</b>

<b>What version of Sequel Pro are you using?</b>
<b>What version of OS X are you using?</b>
<b>What version of MySQL are you connecting to on the server?</b>

<b>Please provide any additional information below.</b>

**Comment by samuelbradshaw** [comment]
This happens to me regularly as well. It is an ongoing problem, and it's not just in TEXT fields – it also happens for VARCHAR, INT, etc.

Sequel Pro nightly build, 5 Dec 2015.
OS X 10.11
MySQL

**Comment by dmoagx** [comment]
Most likely you have "Reload after: editing row" enabled in Prefs and the row position changes after editing because of some parallel changes by someone else.

**Comment by samuelbradshaw** [comment]
I do have "Reload after editing row" checked, but I'm the only user that has access to the database. I'll try disabling that and seeing if it helps.
