### ISSUE TITLE
BIT(M) fields always padded to 8,16,32,64 (>= M)

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#1774]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1774
Reporter:jason.ri...@email.com Date:2013-08-06 22:40:43 Status:Accepted

Query a database table with bit/boolean values.

<b>What is the expected output?</b>
1 or 0
<b>What do you see instead?</b>
00000001 or 00000000

<b>What version of Sequel Pro are you using?</b>
1.0.2
<b>What version of OS X are you using?</b>
10.8.4
<b>What version of MySQL are you connecting to on the server?</b>
Unknown, but relatively recent

<b>Please provide any additional information below.</b>

**Comment by dmoagx** [comment]
This is fixed as a side effect of #2254

**Comment by dmoagx** [comment]
Issue fixed in 1.1.1
See http://www.sequelpro.com/blog/2016.02/sequel-pro-1-1-1/

**Comment by Husterknupp** [comment]
Thank you guys. Appreciate it very much :tada:
