### ISSUE TITLE
[REQ]  Convert filtered data into query

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#1782]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1782
Reporter:christatedavies Date:2013-08-14 01:09:12 Status:New

I sometimes use the filter box at the top of the 'Content' window, it would be nice if there was a button next to the Filter button that would actually convert the query used to filter the view, and put it into the Query view. 

Its only a lazy 'nicety' but I often find myself filtering the view and then realising I need to filter them more, so I end up writing a query to do so.

**Comment by pablomedok** [comment]
Exactly. 

P.S. Sorry for duplication of this issue.
