### ISSUE TITLE
[REQ] Query history improvements

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#1816]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1816
Reporter:sohrab.k...@gmail.com Date:2013-09-30 03:45:37 Status:New

As of the 1.0.2, the query history

\ is limited to 100 queries which is a little tight for my current use of Sequel Pro. If wouldn't mind seeing that limit increased to potentially infinity.

\ All queries go the the history irrespectively of which database/connection (from the favorites) they where run actually against. It'd help to keep have one query history per database/connection and a general one for non favorite connections.

\ Some minor structuring would be most welcome. Specifically, I mean having a simple header showing the date on which a query was run and a small time preamble, with some indentation, e.g.:

Monday, May 22:
    08:07 am:  SELECT X, Y FROM...
    08:03 am:  SELECT COUNT(..

Friday, May 19:
    07:20 pm:  SELECT X, Y, Z FROM...
    07:16 pm:  DELETE FROM...
    07:14 pm:  INSERT INTO...

**Comment by guero235** [comment]
i also like more than 100 queries - more is better.  I also like the idea of haven't a different history for the different databases
