### ISSUE TITLE
Window title bar loses name of current connection/database

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#1819]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1819
Reporter:pbien...@gmail.com Date:2013-10-03 06:47:56 Status:New

<b>What steps will reproduce the problem?</b>
1. Open a connection
2. Open a new tab with CMD+T
3. Close the new tab

<b>What is the expected output?</b>
The window title to display the current connection/database

<b>What do you see instead?</b>
The window title remains &quot;Sequel Pro&quot;

<b>What version of Sequel Pro are you using?</b>
1.0.2

<b>What version of OS X are you using?</b>
10.8.5

<b>What version of MySQL are you connecting to on the server?</b>
5.5.24

<b>Please provide any additional information below.</b>

**Comment by stuconnolly** [comment]
Can't reproduce this and given how long ago this was logged it's likely been fixed at some point.
