### ISSUE TITLE
Application crashes if a connection goes down and you try to reconnect 

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#1826]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1826
Reporter:matei.st...@gmail.com Date:2013-10-15 08:34:54 Status:New

<b>What steps will reproduce the problem?</b>
1.Connect to a remote host / database
2.Shut down the connection remotely (e.g. kill the remote mysql service)
3.Make the remote connection available
4.In the notification window that lets you know the connection is lost, click &quot;Reconnect&quot; 

What is the expected output? I should be able to continue working on the remote db
What do you see instead? Sequel Pro crashes

What version of Sequel Pro are you using? 1.0.2 (build 4096) 
What version of OS X are you using? 10.8.5
What version of MySQL are you connecting to on the server? 5.5.27

<b>Please provide any additional information below.</b>

**Comment by shmert** [comment]
I am experiencing the same behavior. Had three tabs open. Third tab was inaccessible due to network restrictions on the server (was accessible at a previous location). Tried reconnecting. Application crashed. This is repeatable. Thanks!
