### ISSUE TITLE
[REQ] Adding Events to the Sidebar when viewing a Database

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#1828]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1828
Reporter:josha...@gmail.com Date:2013-10-16 05:54:10 Status:New

Request Summary: Events should be visible in the Sidebar

=== Why should this be added? ===
- Currently there is no way to manage events built into Sequel Pro that I've been able to find.
- This means that to manage events a user has to manually run `SHOW EVENTS`, manually copy the event name from the response, and then manually run a query to modify the event they want (like to drop, disable or update it).
- It would be much easier if Sequel Pro had UI for quickly toggling and editing events.

=== How should this be implemented? ===
- Since Events are stored on a per-Database basis, it should be as easy to modify them as Procedures and Functions which already are visible in the sidebar.
- Events should be visible in their own section, and clearly show if they are enabled or disabled. Here's a mockup: <a href="http://i.imgur.com/gzF6hyX.png" rel="nofollow">http://i.imgur.com/gzF6hyX.png</a>
- Right clicking An event would give the option of 'Enable Event' or 'Disable Event' depending on its current state.

=== Personal Experience ===
- In my local development workflow I seed my databases through Laravel's migration system, and before seeding I often just manually select and clear all elements in the sidebar.
- Since the events I migrated are still running, they will now spam the mysql error log because the proc/funcs they call no longer exist. 
- If I could select and delete the events as easily as procs/funcs, but just selecting them all and choosing 'Delete Items' then this would not happen.

**Comment by camden-bassett** [comment]
I second adding this feature. Would be very helpful to be able to see and manage events from the sidebar.

**Comment by pierresh** [comment]
Hello,

Yes, I confirm that this would be very useful because that is not that easy to manage events through lines of SQL..
