### ISSUE TITLE
[REQ] Client compatibility with auth_pam.so

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#1836]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1836
Reporter:jle...@squareup.com Date:2013-10-24 16:41:49 Status:New

We would like to be able to switch clients over to pam based auth on our mysql servers and we have started to do some testing and we have hit a wall. The error we get with Sequel Pro is as follows

&quot;MySQL said: Authentication plugin 'dialog' cannot be loaded: dlopen(/usr/local/mysql/lib/plugin/dialog.so, 2): image not found&quot;

I did some digging around on how to fix this and it seems as though this might be a client side feature request.

<a href="https://bugs.launchpad.net/percona-server/+bug/1166938" rel="nofollow">https://bugs.launchpad.net/percona-server/+bug/1166938</a>
<a href="http://www.percona.com/doc/percona-server/5.5/management/pam_plugin.html" rel="nofollow">http://www.percona.com/doc/percona-server/5.5/management/pam_plugin.html</a>

Is this something that can be put on the roadmap? Giving users a unified system password via pam would help reduce authentication fatigue as well as creating a unified authentication story to streamline security process.

Thanks!

**Comment by dmoagx** [comment]
I looked into it a bit. `LIBMYSQL_ENABLE_CLEARTEXT_PLUGIN` is not a compile-time option, but an environment variable. Setting it in a Terminal and launching Sequel Pro will actually work.

However there is a way to achieve this in code:
```c
BOOL t = YES;
mysql_options(theConnection,MYSQL_ENABLE_CLEARTEXT_PLUGIN,&t);
```

The thing is that MySQL usually only sends a password hash, so adding that option would make things considerably more insecure. Therefore I don't want to add that option as a default.

Just adding it when using a SSL connection might be fine, but probably won't be enough to satisfy everyone.

But then, adding a checkbox for such an obscure option on the connection screen is IMHO a bad idea.

Adding a hidden default doesn't make sense either, that is already there (see above).

So I'm not really sure what to do about this.

**Comment by dmoagx** [comment]
Additional risk:

Implementing this as a preference (even hidden) would enable s.o. to steal passwords.
Sequel Pro allows to change a host but retain the saved password. This is normally only a limited risk, because MySQL only sends a hash of the password.
However with cleartext enabled and the possibility to change the destination host someone could easily gain access to a saved password, which normally would at least require the user to enter the login password (in Keychain Access).

**Comment by abhibeckert** [comment]
It might  be possible for ClearText to allow an attacker to decrypt everything Sequel Pro stores in keychain. We're not going to do that.

**Comment by dmoagx** [comment]
See https://github.com/sequelpro/sequelpro/issues/2996#issuecomment-372862012
