### ISSUE TITLE
[REQ] HTTP Proxy

### ISSUE THREAD

**Issue by ghost** [sequelpro/sequelpro#185]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=185
Reporter:schlabbe...@gmail.com Date:2009-03-05 14:13:03 Status:Accepted

When working with MySQL-Servers of Web Hosting companies it is often a problem that they 
limit access to the mysql-server to their own servers.
Some MySQL Clients support circumventing this by using a script that will be uploaded to the 
website and will then act as a proxy between client and mysql server.

Depending on how far Sequel Pro abstracts the Database connection this should not even be too 
difficult using NSURLConnection and NSXML:

Sequel Pro could make a request like

<a href="http://example.com/proxy.php?" rel="nofollow">http://example.com/proxy.php?</a>
host=db.example.com&amp;user=web&amp;password=1234&amp;proxyPass=5678&amp;query=SHOW%20TABLES;

where proxy.php then would return something like

&lt;result state=&quot;success&quot; rows=&quot;2&quot;&gt;
    &lt;row&gt;
        &lt;Tables_in_test&gt;tbl1&lt;/Tables_in_test&gt;
    &lt;/row&gt;
    &lt;row&gt;
        &lt;Tables_in_test&gt;tbl2&lt;/Tables_in_test&gt;
    &lt;/row&gt;
&lt;/result&gt;

However I think when supporting such a proxy there needs to be a secure authentication 
mechanism to prevent abuse (maybe request encryption, or request signing with a unique client 
key) as well as a session mechanism for speed

**Comment by frees11** [comment]
Hi could please someone tell, if there is some progress with this feature? I started to use new hosting gandi.net, which is extremely good in simple hosting variant, but there is no way how to remotely connect to database.

**Comment by dmoagx** [comment]
You'd have to ask @ramonfritsch about that.

**Comment by ramonfritsch** [comment]
Hi there, I didn't had the chance to work on that anymore. I'll have a look later. Was working on it before version 1 so I think I'll have to change some bits from what I had.

**Comment by frees11** [comment]
Hi any progress?

**Comment by ramonfritsch** [comment]
I had a tag with some development on this feature but don't know what happened since the transfer to github. Feel free to pick up the work from there.

**Comment by ramonfritsch** [comment]
[httpTunnel](/sequelpro/sequelpro/tree/httpTunnel) <-  👍

**Comment by fulldecent** [comment]
Sequel Pro now supports SSH tunneling. Does this solve everyone's issue? Can we close this issue?

**Comment by abhibeckert** [comment]
Some databases are not available over SSH.

**Comment by shiroamada** [comment]
HTTP Tunnel and SSH Tunnel is a different approach. HTTP Tunnel required a php file upload to the server and access via the URL.

**Comment by ramonfritsch** [comment]
@fulldecent @abhibeckert @shiroamada yep, some servers would allow SSH and SequelPro already has it but others are very restrictive and HTTP tunnel is the only way to connect remotely.

I don't have much time to contribute now but would love to see this feature being taken into consideration on the next release.

**Comment by goldenages1989** [comment]
any progress?

**Comment by goldenages1989** [comment]
@ramonfritsch thank you so so so much, but i get errors when i compile it with xcode. whether there is a dmg file?

**Comment by hcarsten** [comment]
just working with sequel pro for the last 10 years (or so). Anyway is this feature (so the httptunnel feature) still working with the current releases? I would appreciate to have such a feature, mostly to access clients systems running on managed servers. So where SSH is not an option.
I would like to contribute to this feature, but just missing the right starting point. So maybe branch this from the current HEAD and try to merge the things from the httptunnel branch ? This is 6 years old no idea how much things had been done from then.

best

Carsten

**Comment by Woodehh** [comment]
+1
