### ISSUE TITLE
Console stops to show actions made after midnight

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#1856]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1849
Reporter: s...@apserver.org.ua Date: 2013-11-11

What steps will reproduce the problem?
1. Do any actions before midnight and do not close Sequel Pro and do some other actions after midnight
2. Open console

What is the expected output?
SQL log before and after midnight

What do you see instead?
SQL log before midnight

What version of Sequel Pro are you using?
1.0.2

What version of OS X are you using?
OS X 10.7.5

What version of MySQL are you connecting to on the server?
5.1

**Comment by stuconnolly** [comment]
Unable to reproduce. The console is correctly displaying queries when crossing midnight.
