### ISSUE TITLE
Export table as SQL dump, displays proper custom filename but exported file name wrong

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#1858]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1851
Reporter: kcrossen Date: 2013-11-13

**What steps will reproduce the problem?**
1.Right click table, Export > As SQL dump...
2.Expand Customize Filename
3.xxx- (database) - (table) - (year) (month) (day)
4. Customized filename displays as: 'xxx-mydb-mytable-20131113.sql'
5. Actual saved file is: 'xxx-mydb--20131113.sql'

**What version of Sequel Pro are you using?** 1.0.2

**What version of OS X are you using?** 10.8 (Mountain Lion)

**What version of MySQL are you connecting to on the server?** 5.5

**Please provide any additional information below.**

**Comment by tmelvin** [comment]
Yea, this still appears to be a problem; when exporting SQL the table name is omitted from the file name when saved to the filesystem.

**Comment by dmoagx** [comment]
Issue fixed in 1.1.1
See http://www.sequelpro.com/blog/2016.02/sequel-pro-1-1-1/
