### ISSUE TITLE
Exporting Views sets the definer as well

### ISSUE THREAD

**Issue by nasht00** [sequelpro/sequelpro#1871]
When I export my database to SQL, and it comes to views, it looks something like:
```
CREATE ALGORITHM=UNDEFINED DEFINER=`nasht00`@`%` SQL SECURITY DEFINER VIEW `content_tag` AS ...
```
It's forcing a DEFINER. When I send my backup file to a co-worker, he can't import it because he doesn't have this user. I have to manually remove the unnecessary parts.

Why doesn't simply export as 
```CREATE VIEW `content_tag` AS ...```

**Comment by alexmglover** [comment]
I know this is an old issue, but an option to not export the definer would be fantastic.

**Comment by simPod** [comment]
Hello, any news? It's painful :/

**Comment by johngrogg** [comment]
We run into this issue regularly at work, and with the current size of our database it's become very bothersome to deal with manually stripping out the DEFINER statements.
