### ISSUE TITLE
Support user names greater than 16 characters in MariaDB

### ISSUE THREAD

**Issue by raphaeltraviss** [sequelpro/sequelpro#1886]
As of MariaDB 5.5.31, it allows a user name length up to 80 characters long; see https://mariadb.atlassian.net/browse/MDEV-4332 and https://mariadb.com/kb/en/create-user/#user-names

I have set up a database with said usernames on the command line.  However, when I use Sequel Pro to inspect the database, it still causes repeated 'User is too long' errors to appear when the  Database>>User Accounts menu is accessed.  If I try to continue past the errors, and set schema permissions or do other things with this user, then Sequel Pro crashes.

**Comment by tom--** [comment]
Please don't make me use PMA.

**Comment by stissot** [comment]
Same problem for us, using Sequel Pro 1.1 connected to a MariaDB 10.0.21 server with some user names longer than 16 characters. Sequel won't let us edit existing users or add a new user. Please fix this issue 👍

**Comment by Martouf** [comment]
:+1:

**Comment by sambaptista** [comment]
👍

**Comment by PowerKiKi** [comment]
Would one of you, OSX users, try to recompile after changing `USERNAME_CHAR_LENGTH` to 80 in [Frameworks/SPMySQLFramework/MySQL%20Client%20Libraries/include/mysql_com.h](https://github.com/sequelpro/sequelpro/blob/master/Frameworks/SPMySQLFramework/MySQL%20Client%20Libraries/include/mysql_com.h#L26) ? 

My guess is that it should do the trick...

**Comment by dmoagx** [comment]
Nope, that won't help.
That constant would only affect Sequel Pros ability to connect with usernames > 16 chars.
And you would need to recompile the mysql client libs for that to actually change.

**Comment by PowerKiKi** [comment]
@dmoagx would you be able to give some pointers to what should be done, so that someone else could submit a PR ?

**Comment by dmoagx** [comment]
Well, removing the limit itself is a trivial change to xcdatamodel file.
However that does not take care of error handling and would cause problems if the username turns out to be too long.

**Comment by dmoagx** [comment]
I've added support for longer usernames in dfe9c477aac50a859e283e0eb6316682458e3e39
That does however not mean, that you can actually connect with Sequel Pro and a username > 16 chars.

You can try a development build from http://nightly.sequelpro.com/ but you should check that the executed commands are actually as desired.

**Comment by stissot** [comment]
Thank you very much. I've tested with the nightly build on a MariaDB 10.x server, and I was able to grant access, connect and execute various queries with a username > 16 chars :)

**Comment by mcfedr** [comment]
Also since MySQL 5.7 it supports longer usernames, up to 32 chars, https://github.com/sequelpro/sequelpro/issues/2198

**Comment by ecederstrand** [comment]
Same symptoms here ("User is too long" alerts), connecting to a MariaDB 10.1 server with 16+ character usernames. I can confirm that the latest nightly build fixes the problem.

**Comment by mitchumowen** [comment]
I'm connecting to MySQL 5.7.18 (local docker), and getting the following errors related to this ticket when I try to view the user editor panel:
"user is too long."
"Multiple validation errors occurred."

The names in use are fine.  I can connect using those names from another application without issues.  Sequel Pro just doesn't seem to like them.

What's strange though, is that names of similar length are used in another MySQL database 5.7.16  (aws production), and Sequel Pro does not throw an error.

It seems the issue with Sequel Pro and the local docker MySQL 5.7.18.

Any ideas?
Thanks

**Comment by nicholasgm** [comment]
I got similar issues, although for Amazon's RDS mysql (version 5.7.11) not for MariaDB or local docker.  As mcfedr noted mysql 5.7 now supports 32 char usernames.  

Downloading the latest Sequel Pro test build resolved this for me.  Posting here incase it helps anyone else.

I had created a user with an 18 character username on RDS mysql manually.  When I open up the 'Users' tab in Sequel Pro (latest release verison, 1.1.2) I got multiple warnings of "User too long." (no hint which user is too long though).  This then stopped me adding other users (with shorter user names).

Downloading latest test build (Snapshot build 5222) fixed this.

**Comment by FrozenBeard** [comment]
Why hasn't this been fixed yet?

**Comment by BookOfGreg** [comment]
@dmoagx please release a new build. This is an extremely frustrating issue.

**Comment by dmoagx** [comment]
@BookOfGreg I can't do release builds.

**Comment by tristanbes** [comment]
What's the status of this ? I keep having this issue (MariaDB 10.2) with SequelPro.

**Comment by stissot** [comment]
@tristanbes We need a release. Support for long user names has been fixed but not yet released (planned for Sequel Pro 1.2), you can use the latest test build in the meantime: https://sequelpro.com/test-builds

**Comment by tristanbes** [comment]
good. i'll go with test build. Any ETA before releasing a stable version ?

**Comment by ehausen** [comment]
Currently the latest test build Download on https://sequelpro.com/test-builds is:
Build 3477d22387
Age: 8 months, 25 days
2017-09-05 12:42:48 UTC

Is this really ok? Something I'm missing?

**Comment by BookOfGreg** [comment]
Summoning all members of the SequelPro organization:
@dmoagx 
@abhibeckert
@avenjamin
@mattlangtree
@stuconnolly

Can you please clarify if this is a dead project or not?
If members are not able to craft releases then there is no longer any point contributing to the source without forking this project.
The last release was almost 9 months ago but there are valuable bugfixes and features that @dmoagx and others have contributed to release.

**Comment by PowerKiKi** [comment]
@dmoagx has been by far the [most active contributor in the last 4 years](https://github.com/sequelpro/sequelpro/graphs/contributors?from=2014-03-31&to=2018-05-31&type=c). It think it would only be fair to promote him as project leader, or at the very least give him whatever he need to create release build.

**Comment by ricosalomar** [comment]
Well the test build (3477d22387) seems to solve the long names issue for me.
But the ability to click on a FK and have it go to the table with the row selected doesn't work.
This is one of my favorite features. :(

**Comment by BookOfGreg** [comment]
@dmoagx There has been no response here. Would you like to fork this repo yourself, or at least put up a sponsor/maintainer notice, see if anyone wants to take on actively releasing this again?

**Comment by ricosalomar** [comment]
I think the answer may be Querious

**Comment by dmoagx** [comment]
Please stay on topic!
If you want to discuss the state of the project you can do that in #3034, #2953

**Comment by kossanah** [comment]
In the mean time anyone running mariadb and facing this issue should use the terminal to create users.

**Comment by microdesign** [comment]
Did anyone find a fix of this?

**Comment by B-Prod** [comment]
Great that the issue ic closed, however fixing it would have been great.

> In the mean time anyone running mariadb and facing this issue should use the terminal to create users.

This issue with user name is not only when creating users, but also when managing permissions.

SequelPro is a Gui to specifically avoid using the console, but your comment was probably ironic :)
