### ISSUE TITLE
Option for alphabetical ordering of filter columns

### ISSUE THREAD

**Issue by grantoz** [sequelpro/sequelpro#1919]
Some tables in the popular commerce framework Magento have over 150 columns.  It would be really helpful to have the option to alphabetically order the column filters in the content view!

Thanks.

**Comment by yefb** [comment]
I would second this.
I don't work with Magento, but sometimes I'm working on a table with several fields, which tends to be hard to navigate in my 13" display.
What I tend to do is go to the Structure tab to see "where is the field I'm looking for" and then go to the resulset to search my column.

**Comment by jakedowns** [comment]
+1 for this. Would rather have the option to filter by field name in the structure tab. But alphabetical ordering would be a decent compromise.
