### ISSUE TITLE
[REQ] Vertical View for Data

### ISSUE THREAD

**Issue by JakOutreach** [sequelpro/sequelpro#1926]
It would be useful in some cases if data could be viewed with the column names down the left hand side instead of across the top.

**Comment by taejoong** [comment]
+ 1

**Comment by jhogervorst** [comment]
Agree! I have some big tables (with tens of columns). Often I need to inspect just one row. With the current table view, this is pretty annoying (you need to carefully scroll to the right columns). If I would be able to select one row and display that data vertically (with the columns on the left), that would be so much easier.
