### ISSUE TITLE
MariaDB 10.x

### ISSUE THREAD

**Issue by oxoocoffee** [sequelpro/sequelpro#1935]
I was wondering if there are any plans to support 10.x release.

**Comment by abhibeckert** [comment]
MariaDB's has a short list of incompatibilities between MySQL and MariaDB 10, and none of these affect Sequel Pro.

**Comment by montywi** [comment]
I added a link to Sequel Pro from the MariaDB Knowledgebase.
Feel free to edit if I got something wrong or you want to enhance the article!

https://mariadb.com/kb/en/library/graphical-and-enhanced-clients-sequel-pro/
