### ISSUE TITLE
Nightly page: star animation obstructs download buttons

### ISSUE THREAD

**Issue by dmoagx** [sequelpro/sequelpro#1936]
Tested with Safari 7.0.3:

The star animation in the background is actually rendered in foreground, thereby making the topmost download links inaccessible most of the time:

![bildschirmfoto 2014-05-03 um 02 09 12](https://cloud.githubusercontent.com/assets/5793864/2869061/ac92237a-d257-11e3-9dad-d9f6a7bf353f.png)
Mouse cursor is on one of the links.

**Comment by stuconnolly** [comment]
Page no longer exists any more. Has been replaced by the following:

https://sequelpro.com/test-builds
