### ISSUE TITLE
utf8mb4 encoded emoji not properly displayed when a View Encoding is selected

### ISSUE THREAD

**Issue by FransGH** [sequelpro/sequelpro#1950]
To reproduce:
- manually remove  "LastViewMode" from ./Library/Preferences/com.sequelpro.SequelPro.plist 
- confirm that nothing is selected in Database -> View Using Encoding
- create a table using utf8mb4 encoding
- insert some emoji characters
- confirm that emoji is showing correctly
- select UTF-8 in Database -> View Using Encoding
- emoji now appears as questions marks
- manually remove  "LastViewMode" from ./Library/Preferences/com.sequelpro.SequelPro.plist 
- emoji re-appears

See https://groups.google.com/forum/#!topic/sequel-pro/oTmIf_N9P_E for original conversation.

**Comment by atartanian** [comment]
+1

**Comment by awendland** [comment]
+1

**Comment by dmoagx** [comment]
MySQLs "utf8" does not support emoji characters.
Sequel Pro 1.1 has added the "utf8mb4" Encoding to the "View Using Encoding" menu which supports them: http://www.sequelpro.com/blog/2015.08/sequel-pro-1-1-rc2/

**Comment by iamryandrake** [comment]
+1 

Any update on this?

**Comment by ye** [comment]
:+1:

**Comment by dmoagx** [comment]
Closing (see my comment above).
