### ISSUE TITLE
Update Code Signature for 10.9.5+

### ISSUE THREAD

**Issue by dmoagx** [sequelpro/sequelpro#1970]
According to Apple, 10.9.5 will require a new code signature:

> Beginning with OS X version 10.9.5, there will be changes in how OS X recognizes signed apps. Version 1 signatures created with OS X versions prior to Mavericks will no longer be recognized by Gatekeeper and are considered obsolete.

https://developer.apple.com/library/prerelease/mac/technotes/tn2206/_index.html#//apple_ref/doc/uid/DTS40007919-CH1-TNTAG205

```
$ codesign -dv /Applications/Sequel\ Pro.app
[...]
Sealed Resources version=1 rules=4 files=324
[...]
```

Cc: @rowanbeentje

**Comment by rowanbeentje** [comment]
Addressed in 47506fb777390a4657a51ffd2e520b33ed1e08d9... but I might still need to update the nightly script, oops.
