### ISSUE TITLE
Error: "Unexpected number of rows deleted"

### ISSUE THREAD

**Issue by nathan815** [sequelpro/sequelpro#1973]
I'm not sure whether this is an issue with Sequel Pro or my database setup, but I've been getting this error:

> **Unexpected number of rows deleted**
> One row was not removed. Reload the table to be sure that the contents have not changed in the 
> meantime. Check the Console for possible errors inside the primary key(s) of this table!

I have a table called `debates` and a table called `comments`. On the `debates` table, I have this _after delete_ trigger:

```
BEGIN
    DELETE FROM votes WHERE postid = OLD.id;
    DELETE FROM comments WHERE postid = OLD.id;
END
```

And on the `comments` table I have this _after delete_ trigger:

```
BEGIN
    UPDATE debates SET comments_count = comments_count-1 WHERE id = OLD.postid;
END
```

I believe this may be what is causing the error, but I don't see why. Does anyone know how I can stop this error? Is it a problem with Sequel Pro?

Thanks!

**Comment by saqueib** [comment]
I am getting this if there is a foreign key constraint fails.

**Comment by quanguyen** [comment]
I also got the same issue

![Screenshot_6_15_19__2_28_PM](https://user-images.githubusercontent.com/11938078/59548496-7e582a00-8f7a-11e9-959b-9ddb43da8365.png)

Then I tried to delete using query, and get this error:

<img width="853" alt="Menubar_and__MySQL_5_7_12__Aurora_IoT_IoT_Accessory_and_AWS_Developer_Forums__Amazon_Relational_Database_Service" src="https://user-images.githubusercontent.com/11938078/59548503-a778ba80-8f7a-11e9-9286-3440b52d7364.png">

I checked other tables that have foreign keys referring to this table, all are CASCADE for ON DELETE/UPDATE. My database does not have TRIGGERS.

What would cause this issue? I have debugged this problem for 3 days but still no clues.

Any help is appreciated

Thanks
