### ISSUE TITLE
Disable keyboard shortcuts (selectively)

### ISSUE THREAD

**Issue by kytrinyx** [sequelpro/sequelpro#1974]
Is there a way to selectively remap or disable shortcuts?

In almost all the software I use, the key combination control-h (`^h`) acts as delete. I haven't used backspace for years (and I avoid stack-overflow and other sites where `^h` is remapped to mean something else, because it's so incredibly frustrating to type when every typo triggers something rather than deleting stuff).

**Comment by thisiswei** [comment]
@kytrinyx @abhibeckert  Awesome! I just ran into the same problem, what do I need to do to remap ^H to delete?

**Comment by kytrinyx** [comment]
@thisiswei if you get the nightly build then you need to change the two shortcuts listed above (help for word, help for selection). Once those are defined to be something other than ^h, then ^h for deletion will work.

**Comment by thisiswei** [comment]
@kytrinyx Great! Do you experience any problems with the nightly build?

**Comment by kytrinyx** [comment]
@thisiswei No I update regularly and have never experienced any problems.

**Comment by thisiswei** [comment]
@kytrinyx  Great!

**Comment by twlz0ne** [comment]
```sh
defaults write com.sequelpro.SequelPro NSUserKeyEquivalents '{
    "MySQL Help for Selection" = "@^h";
    "MySQL Help for Word" = "@^h";
    "back-word" = "^h";
}'
```

**Comment by killrazor** [comment]
Came here to find ⌘ + return to execute a query (like MySQL Workbench). 

Found that I can map using mac Key bindings with the names of `Run Current Query` and `Run Previous Query`. 

If you want to do it how @twlz0ne suggested it would be:
```
 defaults write com.sequelpro.SequelPro NSUserKeyEquivalents '{
        "Run Current Query" = "@\\U21a9";
        "Run Previous Query" = "@\\U21a9";
    }'
```

**Note:** you may have to restart the app.
