### ISSUE TITLE
Comment after queries

### ISSUE THREAD

**Issue by andy964** [sequelpro/sequelpro#1980]
Hi Guys,

When I Run Query or Run All Queries followed by a comment the results are not displayed but the number of rows etc are returned.  Example:

SELECT 1+2;
-- Comment after query

No errors; 1 row affected in total, by 2 queries taking 08.2ms

I'm currently using version V1.0.2 Build 4096 - not sure if this is a bug or whether I should just not have comments after a query.

Cheers.

**Comment by yefb** [comment]
Hi @dmoagx, what do you mean by:
> Instead of always showing the last result from multiple queries, show the last result with actual contents?

So if my last query didn't get any results, we won't show it? It might be confuse, I guess.
I agree with the first question, btw
