### ISSUE TITLE
Archived SQL dumps are no longer importable

### ISSUE THREAD

**Issue by pnomolos** [sequelpro/sequelpro#1983]
Ever since build 310fb079c7 (I think it's that one, and possibly earlier) I have been unable to import archived files (bz2 in particular).  I get a warning back:

```
File read error

An error occurred when reading the file, as it could not be read in the encoding you selected (Autodetect - Greek (Windows)).

Only 0 queries were executed.
```

It would appear that SequelPro isn't detecting that it's an archived file?  I'm on OS X 10.9.5, build 13F12

**Comment by Emerson** [comment]
Just a heads up – seeing this issue again on El Capitan (10.11.2) with Sequel Pro 1.1 (Build 4499)

**Comment by Emerson** [comment]
Ah, disregard – false alarm, my file was corrupt
