### ISSUE TITLE
problems when import UTF8 bulk data. 

### ISSUE THREAD

**Issue by sharq88** [sequelpro/sequelpro#1986]
There are some issue with the import and export in sequel pro. I crawled all the settings, but couldn't solve it. 

When exporting a database all fine, when importing it's going crazy sometimes with UTF8. 
When I do the import via phpmyadmin it works fine. 
![4tvgudlorxl4nkhiqee7vdy9kpfvxml5rffoezzgiek](https://cloud.githubusercontent.com/assets/5793864/4313984/c1503d20-3ed5-11e4-8b95-d7b96af3d577.png)

Settings I have or I have tried
![wqrldpfnz-b3ulzmim7w0yij4n9e6qae36es5pwaf4g](https://cloud.githubusercontent.com/assets/5793864/4313985/c8369044-3ed5-11e4-8b99-901dcbdbd833.png)
![zotolp5d5z_bm_td0aro_2rqpolxgz76imvg0v01flu](https://cloud.githubusercontent.com/assets/5793864/4313986/ca35b5a0-3ed5-11e4-841e-b53cb1b733b1.png)
![ibwlq40imw4pr6g5ttjkehzg78hpp9zter3czdafsts](https://cloud.githubusercontent.com/assets/5793864/4313987/cc60e156-3ed5-11e4-96b9-3cddf1773d36.png)

Sequel version up-to-date
![hk3mks0kjdxzxxiycp88iaurgqy9naanv01pmuiazfg](https://cloud.githubusercontent.com/assets/5793864/4313988/d0abcbcc-3ed5-11e4-99be-1c647f3574a1.png)

MAC version
OSX 10.8.5

I tried both way, insert into the text area, and click on import button
![freptt31uhmejwwfuwdmxelfb8vgsrxu5azhfow8uoo](https://cloud.githubusercontent.com/assets/5793864/4313989/d5a716cc-3ed5-11e4-8264-2790b7cbb571.png)

**Comment by dmoagx** [comment]
Closing after no feedback from user.

**Comment by sharq88** [comment]
Sorry! I never seen your response! Might missed the email notif... 
Thanks for the inline images, will do so in the future.

Is the first screenshot from the same file or are those different exports?
> Yes, same file.
Have you tried importing via "File > Import…"?
> Yes.
Does data exported with phpmyadmin import fine with Sequel Pro?
> I've done the export with phpmyadmin. Import didn't work correctly.
Can you provide sample files?
> I don't have that file anymore, sorry. I installed phpmyadmin, as I was unsure what the issue was and needed fast resolution.
What do you mean regarding #1964 ? That issue is about CSV files, not SQL files.
> Not sure. Ignore it. 
Also please set charset in Preferences to Autodetect. That is preferable in nearly all cases.
> Thanks
Are the database contents changing while you are doing an export?
> No

I stopped using it, and restarted later with a newer version. 
I haven't experienced any problem since.
