### ISSUE TITLE
[REQ] Implement more client-side checking of field settings

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#199]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=199
Reporter:rowanb@gmail.com Date:2009-03-16 11:03:09 Status:Accepted

Currently field creation/editing isn't validated within SP at all, meaning that the interface is quite 
happy to let you create invalid fields, including:
- Unsigned varchars
- Doubles with length 255
- Enums with a default not included in the definition
- Numeric fields with a text default.

Attempting to save this therefore throws a MySQL error - which sometimes makes sense (&quot;invalid 
default for...&quot;), and is sometimes the generic &quot;error in your SQL syntax&quot;.  It would therefore be very 
useful to provide more client-side checking and provide more useful error messages/limiting.

**Comment by fulldecent** [comment]
See also #160
