### ISSUE TITLE
Can't connect to remote server any longer under Yosemite Beta 4 - OS X 10.10 (14A379b)

### ISSUE THREAD

**Issue by gadgetto** [sequelpro/sequelpro#1994]
Since I installed public beta 4 of Yosemite SequelPro doesn't connect to my remote server any longer.
There was no problem under Public Beta 3 of Yosemite.
Can't say whats going wrong, I only get the message:

MySQL-Error: Can't connect to MySQL server on '(server address)' (4)

I already tried to increase the timeout limit but without success.

With Coda (my editor) the same connection works like a charm.

**Comment by dmoagx** [comment]
Closing after no feedback.
