### ISSUE TITLE
Reference to preference file on homepage is wrong

### ISSUE THREAD

**Issue by skovmand** [sequelpro/sequelpro#2000]
The FAQ on the homepage states the following:

The connections strings are stored in the following preference file:
~/Library/Preferences/com.google-code.sequel-pro.plist

However, I haven't found that file on OS X Mavericks. Instead this file is present:
~/Library/Preferences/com.sequelpro.SequelPro.plist

(Page URL: http://www.sequelpro.com/docs/Frequently_Asked_Questions#)

**Comment by stuconnolly** [comment]
Not sure when, but this has since been fixed.
