### ISSUE TITLE
Fix table list  & tab view to look proper in Yosemite

### ISSUE THREAD

**Issue by feens** [sequelpro/sequelpro#2003]
The tabs and list of tables look pretty bad in Yosemite.  The tabs should match the proper Yosemite styles (i.e. Safari).

![screen shot 2014-10-21 at 12 45 40 pm](https://cloud.githubusercontent.com/assets/3578317/4725617/2690662a-595b-11e4-95d0-f8dcbc488f33.png)

**Comment by dmoagx** [comment]
The tab bar colors have been fixed already.
The sidebar color looks fine in the current 10.10 release, too.
The button positioning has also been fixed.

I'll close this issue now.
