### ISSUE TITLE
Text Garbled on Import screen with Yosemite

### ISSUE THREAD

**Issue by benmcmath** [sequelpro/sequelpro#2012]
When importing CSV and mapping data to rows, the highlighted row's text is all garbled.   This is with version 1.0.2 on OS X Yosemite.

![screen shot 2014-10-29 at 8 34 52 am](https://cloud.githubusercontent.com/assets/448350/4825717/06a86b24-5f68-11e4-8a72-5d5499851a26.png)

**Comment by markroland** [comment]
I have also noticed this for quite some time.
