### ISSUE TITLE
Laggy UI importing csv on Yosemite

### ISSUE THREAD

**Issue by gattol** [sequelpro/sequelpro#2025]
User interface become nearly unusable when trying to import a csv into the database. Same issue occurs with latest nighly build (efe07637ac) and recompiling from source.

**Comment by dmoagx** [comment]
Small update: The nightly builds are back online and should now include the fix.

**Comment by aborland** [comment]
I checked the nightly builds. They still look broken. Do you have a link to the dmg?

**Comment by aborland** [comment]
It's fixed now. Thanks. :) Got the build. 

http://nightly.sequelpro.com/builds/Sequel_Pro_rdb64bd1b5a.dmg

**Comment by AndrewAtkinson** [comment]
I finally got a chance to test the fix and its very fast now. Thanks!

**Comment by dmoagx** [comment]
Nobody has started screaming so far, so I'll assume this is fixed now.

**Comment by AndrewAtkinson** [comment]
Yea I have used this several times and its worked without fault every time
