### ISSUE TITLE
Spinning wheel while trying to reconnect

### ISSUE THREAD

**Issue by arvidbjorkstrom** [sequelpro/sequelpro#2037]
While ssh tunneled connections try to reconnect in the background Sequel locks up with a spinngin wheel for a little while until Sequel switches to the window in question and you get the "Connection lost would you like to reconnect" dialogue. Not sure it's limited to ssh tunneled connections, but I only have that kind of sql connections..
This should not lock up the whole application. And ideally, since it's initiated in the background, it should stay in the background and just silently add the dialogue to the affected window for you to see when you switch to that window.

It's really annoying when you're hard at work in another window and Sequel just locks up and stops letting you do anything, and even more annoying if you had a few windows open that have now lost connection and you end up sitting there half a minute or more...

For the record I'm running OS X 10.10 (i think I had the same issue in 10.9 though) and Sequel Pro 1.0.2 build 4096. My connections are SSH tunneled connections, and the ones loosing connections connecting via a VPN tunnel (that disconnects after a bit of computer sleep).

**Comment by neurogenesis** [comment]
Related to #2838
