### ISSUE TITLE
Syntax highlighting wrong with composite characters (Emoji)

### ISSUE THREAD

**Issue by dmoagx** [sequelpro/sequelpro#2044]
When the query editor contains composite characters, that require 4 bytes in UTF-16 (such as Emoji) the syntax highlighter is thrown off.

From a quick check it looks like our `utf8strlenfortoken` function for calculating string length is the "problem":
```
"🎍"
```
(emoji used was "pine decoration" if not displayed)

For this text our function will report 3 characters (which is correct). NSString on the other hand thinks those are 4 characters, which misplaces the highlighting.

**Comment by dmoagx** [comment]
Looking closer at our highly optimized strlen function I'm not sure how to proceed.

The function uses a trick of UTF-8 by only really counting the continuation bytes (see table [here](http://en.wikipedia.org/wiki/UTF-8#Codepage_layout)) and subtracting that number from the string length in bytes. (for the example above: 6 bytes - 3 continuation bytes = 3 chars)

This however blocks the un-optimization we need to do (namely mapping 3 and 4 byte sequences to 2 chars instead of 1) because only the initial byte contains the length of the character and we ignore that one.

flex doesn't support utf16, so we can't just switch to using utf16 and byte counting, either.

**Comment by dmoagx** [comment]
Another observation:
Our flex definition has an issue too, because it will split some 4-byte UTF8 characters into a 1-byte and a 3-byte token.
Some definitions look off too:
```
alpha	[a-z_\.À-ﾟ]
```
The last part of that clause is `C3 80 2D EF BE 9F` and since flex [does not support UTF-8](http://stackoverflow.com/questions/9611682/flexlexer-support-for-unicode) it will just assume we meant any byte in the range `80` to `EF` as well as the bytes `C3`, `BE`, `9F`.

**Comment by Bibiko** [comment]
Hi, I'll try to find a way which fixes the correct length calculation of any UTF8 byte sequence. Unfortunately this is a stony way since the function which we're using "size_t utf8strlen(const char * _s)" is VERY specialised in terms of absolute speed. 

Re: alpha   [a-z_\.À-ﾟ] This is a "only" a compromise for detecting letters which directly follow a numeric symbol as in "123abc" to mark such sequences as WORD not as numbers.

Regards, Hans

**Comment by dmoagx** [comment]
Hi Hans,

(haven't heard from you in a while. Hope you are doing well!)
I made a prototype implementation:
```
// This function works inverse to the original function, in that it counts only the first
// byte of each character whereas the original function counts only continuation bytes and
// substracts them from the strlen in bytes.
size_t utf16_unichars_for_utf8string(const char * _s)
{
	const char *s;
	size_t count = 0;
	size_t u;
	unsigned char b;
	
	/* Handle any initial misaligned bytes. */
	for (s = _s; (uintptr_t)(s) & (sizeof(size_t) - 1); s++) {
		b = *s;
		
		/* Exit if we hit a zero byte. */
		if (b == '\0')
			goto done;
		
		// 0xxx xxxx -> 1 (ASCII range)
		// 10xx xxxx -> 0 (cont. byte, not counted)
		// 110x xxxx -> 1
		// 1110 xxxx -> 1 (note: those are 3 bytes in UTF-8 but only 2 bytes in UTF-16!)
		// 1111 xxxx -> 2
		count += (((b >> 7) & (b >> 6) & (b >> 5) & (b >> 4)) << 1) | ((unsigned char)(~b) >> 7) | ((b >> 7) & (b >> 6) & ((~b) >> 5)) | ((b >> 7) & (b >> 6) & (b >> 5) & ((~b) >> 4));
	}
	
	/* Handle complete blocks. */
	for (; ; s += sizeof(size_t)) {
		/* Prefetch 256 bytes ahead. */
		__builtin_prefetch(&s[256], 0, 0);
		
		/* Grab 4 or 8 bytes of UTF-8 data. */
		u = *(size_t *)(s);
		
		/* Exit the loop if there are any zero bytes. */
		if ((u - ONEMASK) & (~u) & (ONEMASK * 0x80))
			break;
		
		/* Count bytes which are NOT the first byte of a character. */
		//u = ((u & (ONEMASK * 0x80)) >> 7) & ((~u) >> 6);
		size_t sf = (u & (ONEMASK * 0x80)); //sf enthält pro byte nur das höchste bit
		u = (((sf >> 7) & (u >> 6) & (u >> 5) & (u >> 4)) << 1) | (((~sf) >> 7) & ONEMASK) | ((sf >> 7) & (u >> 6) & ((~u) >> 5)) | ((sf >> 7) & (u >> 6) & (u >> 5) & ((~u) >> 4));
		
		count += (u * ONEMASK) >> ((sizeof(size_t) - 1) * 8);
	}
	
	/* Take care of any left-over bytes. */
	for (; ; s++) {
		b = *s;
		
		/* Exit if we hit a zero byte. */
		if (b == '\0')
			break;
		
		count += (((b >> 7) & (b >> 6) & (b >> 5) & (b >> 4)) << 1) | ((unsigned char)(~b) >> 7) | ((b >> 7) & (b >> 6) & ((~b) >> 5)) | ((b >> 7) & (b >> 6) & (b >> 5) & ((~b) >> 4));
	}
	
done:
	return count;
}
```
This function is pretty much exactly 1x slower than the original
```
 *				utf8	utf16
 * 1,9MB HTML	~1.8ms	~3.0ms (±0.5ms)
 * 16MB SQL		~9ms	~17ms
 * 290MB Log	~168ms	~327ms (±30ms)
```

But I think there are still some edge cases not covered.

**Comment by Bibiko** [comment]
Hi Max,
did you by chance try my code fix sent to your private mail address? --Hans

**Comment by dmoagx** [comment]
Hi Hans,
sorry, took me some time to get to it.

From the few unit tests I did, your code works as expected.

Speedwise it seems to be about equal to the original function for the 290MB ASCII file (0.2s±10%). 
For the Unicode HTML file both take ~ 1ms (with mine taking 2x as long).

Given that it's much rather Apples TextView that has massive problems even with 2MB files, I don't think we need to spend more time on optimizing what has already been pretty fast to begin with :smile: 

So I'll go ahead and merge it.
