### ISSUE TITLE
Adding SQL Functions

### ISSUE THREAD

**Issue by jgacuca567** [sequelpro/sequelpro#2046]
When using Sequel Pro, For example I can use the Datetime Function. But when I add content the date is 0000-00-00 00:00:00.

How do I make the text show the actual date?

**Comment by jgacuca567** [comment]
In a table, I am using the DATETIME Function. For example the table name is
id, firstname and datecreated. For the date created if I want to get a
timestamp such as the actual date instead of 0000-00-00-00: 00, see the
screenshot below.

**Comment by dmoagx** [comment]
Are you saying you want to insert the result of an expression via the table editor?

This only works for two special cases: `NOW()` and `CURRENT_TIMESTAMP` - Every other value is treated like a normal string (and mysql assumes unparsable strings have a value of `0000-00-00 00:00:00` in datetime/timestamp columns)

**Comment by jgacuca567** [comment]
Yes. I want to insert the result meaning that  In my SQL statement, I am
using NOW() function which works properly.

However When I manually insert data using Sequel Pro, The datetime string
is 0000-00-00 00:00:00 .

Should I use the Now Function and Current Timestamp in the TYPE?

**Comment by dmoagx** [comment]
You still haven't explained what you are doing.
Describe *precisely* what steps you do.

**Comment by jgacuca567** [comment]
Create a simple table use id, firstname and datetime from the structure tab
Go to the Content Tab, add some data
After adding a firstname, press the tab key
The datetime automatically is created but it is 0000-000-000, not the
default timestamp.

I would like to know, when not using SQL Statements and adding data
manually using the Content Tab, how do you make the datetime give the exact
timestamp instead of 0000-000-00

**Comment by jgacuca567** [comment]
I figured it out, when creating data in the datetime - I place NOW() and press the tab key, It brings the Correct Timestamp. Thanks
