### ISSUE TITLE
Crash when adding a new user

### ISSUE THREAD

**Issue by nebbian** [sequelpro/sequelpro#2047]
Sequel Pro crashes when a user is added via the menu.  Subsequently, when asked if I want to notify the developers, that process crashes as well.
![screen shot 2015-01-07 at 14 46](https://cloud.githubusercontent.com/assets/489642/5641941/4c429646-967c-11e4-9261-463532830013.png)

**Comment by dmoagx** [comment]
Duplicate of #1961
