### ISSUE TITLE
SequelPro shows only one row from any table in database

### ISSUE THREAD

**Issue by TrogWarZ** [sequelpro/sequelpro#2048]
Hello!

I have:
– Mac OS X 10.10.1 (14B25)
– SequelPro 1.0.2 (4096)
– Remote server on Ubuntu 12.04.5 LTS
– Remote MySQL server 5.5.40

After importing database on server like `mysql -uUSER -pPASS DBNAME < dump.sql` SequelPro always shows me just one row from any table in database.
If i try to see db contents from, for example, mysql console or some php wrapper – database is good and contains all rows.

What additional info you need to debug and solve problem?
What can i do in this situation?

Thank you!

**Comment by dmoagx** [comment]
* What does it say at the bottom of the window ("Showing rows X to…")
* Open the console (cmd+shift+K) and reload the table. What queries are logged? (If you don't see any go to Prefs > Events and enable logging)

**Comment by TrogWarZ** [comment]
Bottom bar shows:
`rows 1 to 370 508`

Console shows:
```sql
/* 10:12:10 db.example.com */ SHOW VARIABLES;
/* 10:12:10 db.example.com */ SELECT @@global.max_allowed_packet;
/* 10:12:10 db.example.com */ SHOW DATABASES;
/* 10:12:13 db.example.com */ USE `my_database`;
/* 10:12:14 db.example.com */ SHOW VARIABLES LIKE 'character_set_database';
/* 10:12:14 db.example.com */ SHOW /*!50002 FULL*/ TABLES;
/* 10:12:14 db.example.com */ SELECT * FROM information_schema.routines WHERE routine_schema = 'my_database' ORDER BY routine_name;
/* 10:12:15 db.example.com */ SHOW TABLE STATUS LIKE 'cities';
/* 10:12:15 db.example.com */ SHOW CREATE TABLE `cities`;
/* 10:12:16 db.example.com */ SELECT * FROM `cities` LIMIT 0,1000;
/* 10:12:16 db.example.com */ SELECT COUNT(1) FROM `cities`;
```

**Comment by dmoagx** [comment]
Hmm, haven't heard of that issue.
* I guess you already tried relaunching Sequel Pro?
* Does this affect all connections to all servers or only one server?
* Please restart your Mac and try again
* If that doesn't help please create a new user account on your Mac and try it under that account to rule out corrupt preferences

If you have a test/dev database you can also try a recent development build from http://nightly.sequelpro.com/

**Comment by TrogWarZ** [comment]
Solved, thank you!

* Relaunched many times and rebooting mac.
* Affect all servers.
* New user (crated via mac os x tools) has same error.
* Installed http://nightly.sequelpro.com/ and problem is gone for both users.
