### ISSUE TITLE
Dollar sign combined as $1$ in favorite not stored well

### ISSUE THREAD

**Issue by kuspito** [sequelpro/sequelpro#2049]
If I save a favorite containing $1$  as example:

```SQL
select ENCRYPT('j244rwt', CONCAT('$1$', SUBSTRING(SHA(RAND()), -16)))
```
it stores something like
```SQL
select ENCRYPT('j244rwt', CONCAT('$', SUBSTRING(SHA(RAND()), -16)))
```

**Comment by dmoagx** [comment]
Actually what's happening here is Sequel Pro supports variables in query favorites.
For example
```sql
select $1.* from ${0:¦$SP_ASLIST_ALL_TABLES¦} as ${1:alias} 
```
could be used to quickly build an aliased select statement.

To literally insert `$1` you would have to escape it as `\$1` when adding the query favorite.
However there seems to be a bug that will cause the `\` to not be removed when inserting the favorite.
