### ISSUE TITLE
Error scrolling list of tables and submit error feedback

### ISSUE THREAD

**Issue by alexdrag** [sequelpro/sequelpro#2051]
Here is my screenshot: https://www.dropbox.com/s/eyhrg7hef914abn/Screenshot%202015-01-11%2012.45.37.png?dl=0

I opened our database and I started scrolling list of tables. I saw an error. I tried to submit that error using modal dialog, but you can see on my screenshot I couldn't.

System: https://www.dropbox.com/s/d7ycjkm0802r3ng/Screenshot%202015-01-11%2012.46.39.png?dl=0

Preferences: https://gist.github.com/alexdrag/e34dbb659fcecdb993da

Crash log: https://gist.github.com/alexdrag/f5d02d9004d8c9a73102

Console: https://gist.github.com/alexdrag/5e2c6e51357b09dac97d

Exception: https://gist.github.com/alexdrag/2e545039e8703e70b64b

**Comment by dmoagx** [comment]
Submitting the report failed because the server storing them currently has no disk space left.

About the real issue:
What were you doing when it happened?
How often does it happen?

**Comment by alexdrag** [comment]
I saw this error only twice, and I can not reproduce it again. I have connected to the server (SSH tunnel), and selected database from dropdown (above Select Database label). Then I was trying to scroll down to the last tables in the list. I have around 80 tables in that database, and around 100 in the second database. Also I checked memory and CPU, and everything look normal (CPU ~10%, RAM ~ 6GB).

**Comment by alexdrag** [comment]
I've updated SequalPro to the latest Nightly Build, and I do not have issues anymore.
