### ISSUE TITLE
SSH socket forwarding

### ISSUE THREAD

**Issue by dmoagx** [sequelpro/sequelpro#2054]
OpenSSH 6.7 added forwarding of UNIX domain sockets.

This means we have to rework the connection UI as SSH can now be seen as a connection parameter (much like SSL).

Low priority issue as Apples OpenSSH version in 10.10 is still 6.2p2 so it will probably take some time until non-brew/macports/fink/... users can actually use that (also the server has to support it as well).

**Comment by bajax** [comment]
It's already possible to connect to an SQL server socket via an SSH connection-- but the configuration dialog doesn't allow it.

**Comment by bajax** [comment]
I'm writing to request this enhancement.  I have to work with several SQL instances where MySQL's inability to bind to multiple interfaces without binding them all has ruled out my using Sequel Pro with them.  They have to allow connections from an internal, non-public network, but for security reasons, we've disallowed the kind of access I need via that interface--I have to be able to log in via socket.

It seems other clients (Workbench, HeidiSQL) must invoke the SQL client on the remote end to allow this, but it looks like Sequel Pro actually sets up proper SSH tunnels.

When Apple supports this feature I hope you will too.

**Comment by paskal** [comment]
It will be really nice to have it implemented.

**Comment by adminnu** [comment]
When do you already implement it? 4 years have passed. I constantly have to add 127.0.0.1 to the rules, and on some hosts only localhost cannot be changed.

**Comment by paskal** [comment]
@adminnu I'm sorry, are you a paid customer to ask such questions? I think at this very moment answer to "when it will be implemented" is "when you do it yourself and send PR for it".

**Comment by andrews05** [comment]
macOS OpenSSH is now at 7.9p1 so socket forwarding is widely supported now.

While we're waiting for Sequel Pro to implement this, you can forward the socket yourself in Terminal:
```ssh -L /tmp/mysql.sock:<remote_socket> <host>```
(On my mariadb installation the remote socket is `/var/run/mysqld/mysqld.sock`.)
Once done you can just connect in Sequel Pro via Socket.

**Comment by ggedde** [comment]
It would be nice if I can use SSH + Socket, but that doesn't seem to be an option yet.
