### ISSUE TITLE
Help file missing

### ISSUE THREAD

**Issue by nicholas-r-karp** [sequelpro/sequelpro#2057]
Using 1.0.2 b4096, Help->Online Help gives a "not found" error. Working on a 2011 iMac, in OS X Yosemite. Browser is Chrome. All up-to-date.
![screen shot 2015-01-16 at 5 51 37 pm](https://cloud.githubusercontent.com/assets/10457602/5785763/bba7ef8a-9da8-11e4-95e0-fa4bc9d42acf.png)

**Comment by sequelpro** [comment]
Fixed. http://www.sequelpro.com/docs
