### ISSUE TITLE
Typing two subsequent single quotes adds a third one

### ISSUE THREAD

**Issue by juradoz** [sequelpro/sequelpro#2060]
Adding two subsequent single quotes i.e when adding some plain string value, Sequel Pro adds a third one, probably due to code completion bug.

What steps will reproduce the problem?
Type two subsequent single quotes ('') anywhere on Query window.

What is the expected output?
Two subsequent single quotes where I can navigate back using keyboard arrow keys so I can fill quoted data.
i.e. (| means cursor position)
select \* from Test where foo = ''| 

What do you see instead?
A third single quote is added right before cursor
i.e. (| means cursor position)
select \* from Test where foo = '''|

What version of Sequel Pro are you using?
Sequel Pro Nightly Build 4366 (db64bd1)

What version of OS X are you using?
10.10.1

What version of MySQL are you connecting to on the server?
5.5.28

**Comment by dmoagx** [comment]
Are you perhaps talking about backticks?
Both `'` and `"` work fine for me.

**Comment by dmoagx** [comment]
No feedback from reporter for > 1 month, closing.
