### ISSUE TITLE
Add Byte Order Mark when exporting CSV files

### ISSUE THREAD

**Issue by touzoku** [sequelpro/sequelpro#2062]
When exporting CSV files in UTF-8 encoding, sequel pro doesn't add BOM (0xEF, 0xBB, 0xBF sequence) in the beginning of the file. Hence, Microsoft Excel (and some other Windows software) can't open these CSV files properly.

Patch should be super simple — just output 0xEF, 0xBB, 0xBF before dumping the results.

**Comment by dmoagx** [comment]
It's not *that* simple.
From my experience a lot of other programs will fail reading files with a BOM, so this would need a GUI checkbox.
