### ISSUE TITLE
HTML Preview

### ISSUE THREAD

**Issue by HHLEARN** [sequelpro/sequelpro#2065]
Since last Yosemite update 10.10.2, the HTML preview for a TEXT field does not work, you just get a blank page.

**Comment by dmoagx** [comment]
Well, normal QuickLook on html files doesn't work either for me on 10.10.2, so this is most likely Apples fault.

**Comment by HHLEARN** [comment]
It worked just fine until the update last week.

**Comment by dmoagx** [comment]
Most stuff works fine until something changes.

https://discussions.apple.com/thread/6803599
https://discussions.apple.com/thread/6818594
http://apple.stackexchange.com/questions/169948/updating-to-os-x-10-10-2-broke-quick-look-previews-for-html-files
http://forums.macrumors.com/showthread.php?t=1842219
...
