### ISSUE TITLE
Autocomplete does not work unless using the databas

### ISSUE THREAD

**Issue by csogilvie** [sequelpro/sequelpro#2067]
I write this having been used to using Heidi SQL on Windows, to using SequelPro on a Mac, so this is something I've spotted...

If I write a query:

SELECT u.user FROM database.user u WHERE u.

I would be expecting to see the list of columns in this table. To fill you in on how Heidi works, this seems to then do a:

SELECT `DEFAULT_COLLATION_NAME` FROM `information_schema`.`SCHEMATA` WHERE `SCHEMA_NAME`='database';
SHOW TABLE STATUS FROM `database`;
SHOW FUNCTION STATUS WHERE `Db`='database';
SHOW PROCEDURE STATUS WHERE `Db`='database';
SHOW TRIGGERS FROM `database`;
SELECT `DEFAULT_COLLATION_NAME` FROM `information_schema`.`SCHEMATA` WHERE `SCHEMA_NAME`='information_schema';
SHOW TABLE STATUS FROM `information_schema`;
SHOW FUNCTION STATUS WHERE `Db`='information_schema';
SHOW PROCEDURE STATUS WHERE `Db`='information_schema';
SHOW TRIGGERS FROM `information_schema`;
SHOW EVENTS FROM `information_schema`;
SELECT *, EVENT_SCHEMA AS `Db`, EVENT_NAME AS `Name` FROM information_schema.`EVENTS` WHERE `EVENT_SCHEMA`='database';
SHOW CREATE TABLE `database`.`user`;
SHOW COLLATION;

and then populates the Autocomplete dropdown.

It would be nice if Sequelpro had this feature.

Note, that I'm using the released version and have not pulled down and compiled my own version.

**Comment by dmoagx** [comment]
Sequel Pro currently only supports autocompletion for the current database.
