### ISSUE TITLE
Hangs when opening double clicking mediumtext field to after select

### ISSUE THREAD

**Issue by jeffwrule** [sequelpro/sequelpro#2068]
created a table with multiple mediumtext fields in mysql.

after select, I double click on the field and the tools just spins and spins never comes back.

The field is not exceptionally large probably less the 1K of data.

Let me know if there is something I can provide to help debug this issue.

**Comment by dmoagx** [comment]
Exact OS X Version?
Exact Sequel Pro Version?
What connection type?
Does it happen on all tables/all databases/all servers?

**Comment by dmoagx** [comment]
Closing after no feedback from user.
