### ISSUE TITLE
Comment showing in fieldname

### ISSUE THREAD

**Issue by richardbiddle** [sequelpro/sequelpro#2069]
The following query displays the hashed out comment "shouldn't see this" into the field name: 
SELECT 1, #shouldn't see this 
sum(2);
Outputs:
1   #shouldn't see this 
sum(2)
1   2

Should output:
1   sum(2)
1   2

**Comment by dmoagx** [comment]
I compared the mysql cli client and Sequel Pro and the difference between them is, that the mysql client removes the comment before sending the query whereas Sequel Pro sends the query as-is.

Trying the same in PHP:
```php
<?php

	error_reporting(E_ALL|E_STRICT);

	$c = mysql_connect('127.0.0.1', '...', '...');
	
	$q = mysql_query("SELECT 1, #shouldn't see this
sum(2);");
	
	print_r(mysql_fetch_assoc($q));
	
	mysql_close($c);

?>
```
Matches Sequel Pros behavior:
```
Array
(
    [1] => 1
    [#shouldn't see this
sum(2)] => 2
)
```

MySQL documentation is quite explicit in that it says the **MySQL server** supports those comments (not the client). http://dev.mysql.com/doc/refman/5.5/en/comments.html

So IMHO Sequel Pro is behaving correct here.
