### ISSUE TITLE
Scrolling Produces "shakey" effect on 10.10.2

### ISSUE THREAD

**Issue by 9ae8sdf76** [sequelpro/sequelpro#2070]
When scrolling through tables that have multiple rows/columns, it appears that the columns are resizing themselves in such a way that it produces a shakey effect. I've attached a GIF demonstrating the behavior. Also, not sure if this matters or not, but I am using an Apple Magic Mouse to scroll. 

![sequelproshakyscrolling](https://cloud.githubusercontent.com/assets/2528463/6151237/83231c90-b1e2-11e4-95d4-f3650255b02c.gif)

**Comment by dmoagx** [comment]
Looks to me like this could be a feature of apples "rubberband scrolling" stuff.
I only have a 10.10 VM and that feature doesn't work there, so I can't test that.

**Comment by dohpaz42** [comment]
I didn't note this in my original report, but this only just started happening after updating to the latest nightly build.

**Comment by itised** [comment]
i have the same "shaky" issue, and I've been on 1.0.2 for a while. It may have begun recently with an OS update, but I'm definitely seeing the same issue on OS X 10.10.2 running Sequel Pro 1.0.2 (Build 4096)

**Comment by dmoagx** [comment]
no recent nightly builds changed code related to the main table view.
I think it's much more likely the 10.10.2 update is causing this.

Can you try and check if the same thing happens when using a regular scrollwheel mouse?

**Comment by MikeRich88** [comment]
I have this issue on 10.12.6 using the MacBook Air built in trackpad.

It only happens for me if the table has a horizontal scroll bar.

Going to say with 99% certainty this has to do with the "rubber band" scrolling stuff.

It should be an easy fix, no? Just changing whatever property of that table/view to disable that.
