### ISSUE TITLE
Favs folders get the color of the item above

### ISSUE THREAD

**Issue by yanncoupin** [sequelpro/sequelpro#2074]
![sequel_pro](https://cloud.githubusercontent.com/assets/209176/6266047/fd5a8cfc-b834-11e4-9e3b-a90577baa668.jpg)

The item pointed by the arrow keeps the color of the item above.

Confirmed by changing the order to an item of another color.

The color is updated to the color of the item above, probably because folder don't have a color of their own and the value isn't reset while iterating over the list

**Comment by dmoagx** [comment]
Yeah, after having a night of sleep it was pretty obvious why that happened :)
Fixed in 5f3c003919903c597b2d6aeb7fcc064b0d6d9ef3

**Comment by yanncoupin** [comment]
Ok for me too. It's always amazing how sleep can change one's perspective on things :)
