### ISSUE TITLE
10.10: Font weight optimizations?

### ISSUE THREAD

**Issue by dmoagx** [sequelpro/sequelpro#2076]
Font rendering on Yosemite looks pretty terrible on Non-Retina screens in general, but it seems there are some optimization techniques.
This is a screenshot from Xcode 6 and Sequel Pro nightly on 10.10.2:
![bildschirmfoto-2015-02-19-um-22 33 23](https://cloud.githubusercontent.com/assets/5793864/6276640/9557e3bc-b888-11e4-9d95-5d4d4e690727.png)

As you can see both fonts are the exact same size (red lines) as well as same width (blue lines), which rules out font variants.
Still the Xcode one is much better legible because anti-aliasing gave the text a higher priority than in Sequel Pro.
So there has to be some way to get the same effect in Sequel Pro.

**Comment by abhibeckert** [comment]
It's not font weight, the text in sequel pro is simply not fully opaque. Xcode is not following the default colours in yosemite.

Enabling Increase contrast in System Preferences » Accessibility » Display makes Sequel Pro look the same as Xcode.

Alternatively, we could set a custom background colour for the outline view (light grey) and custom text colour for the text cell (black). That also makes it look exactly the same as Xcode.
