### ISSUE TITLE
[REQ] Provide option to re-run active query every N interval 

### ISSUE THREAD

**Issue by jhoffmann** [sequelpro/sequelpro#2080]
It would be nice to have a method to re-run the current query in the query window every N seconds/minutes.

We have a job queue that lives in our database, and I routinely like to monitor it for failures while I'm making changes.  Currently, I have to periodically switch back to SequelPro and hit R.

I imagine it could be something that lives in the current 'Run Current/Run All' dropdown menu between the query/results panes,

**Comment by jbrahy** [comment]
This would be awesome.
