### ISSUE TITLE
Crash on Saving User Accounts in Yosemite

### ISSUE THREAD

**Issue by phongmedia** [sequelpro/sequelpro#2081]
Using OSX Yosemite, Macbook Pro 2010 - every time when using the user accounts `Database > User accounts...` settings and then editing settings, every time I press save, Sequel Pro hard-crashes. It just completely closes without any warnings or errors.

I can re-produce this scenario very consistently as it happens every single time when saving settings, so if you need any help reproducing this or getting samples, let me know.

**Comment by dmoagx** [comment]
Duplicate of #1961
