### ISSUE TITLE
Encoding of database is changed when changing database name

### ISSUE THREAD

**Issue by luffyke** [sequelpro/sequelpro#2082]
database name: test1
encoding: utf-8
after changing database name to test2, the encoding is still selected 'utf-8' in toolbar, but the table encoding is marked as 'inherit from database(latin1)' when creating new table in database test2, and encoding of the table is really created as latin1, that is incorrect.

**Comment by dmoagx** [comment]
Verified in 8b1ff9c.
This is because renaming a database will actually clone it and drop the original.
However Sequel Pro forgets to set the encoding when creating the copy.

**Comment by dmoagx** [comment]
This will be fixed in an upcoming nightly build (once our webserver has some space left on disk again) :no_mouth:

**Comment by luffyke** [comment]
thanks for your quickly fix. :+1:
