### ISSUE TITLE
Support for non-standard SSH

### ISSUE THREAD

**Issue by kabo** [sequelpro/sequelpro#2083]
I've installed the latest version of OpenSSH through macbrew to [enable better security for SSH](https://stribika.github.io/2015/01/04/secure-secure-shell.html). Then I've added a few lines to my .ssh/config (e.g. `KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256`). This is not something that the standard SSH supports. So when I try to use the SSH tunnel option in Sequel Pro I get:

```
debug1: Reading configuration data /Users/xxx/.ssh/config
debug1: /Users/xxx/.ssh/config line 5: Applying options for *
Unsupported KEX algorithm "curve25519-sha256@libssh.org"
/Users/xxx/.ssh/config line 6: Bad SSH2 KexAlgorithms 'curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256'.
```

I think that if there was an option available so I could point out another path to SSH (`/usr/local/bin/ssh`) that would solve it, but that may not be enough. But this could potentially be a simple fix.

**Comment by dmoagx** [comment]
Nightly build 9f2e5a6b0f added an option in Preferences to use a custom SSH client.
Please try it and give feedback.

**Comment by kabo** [comment]
Beautiful, worked like a charm :)
Thanks!
