### ISSUE TITLE
Website: old, outdated repository info

### ISSUE THREAD

**Issue by robertoschwald** [sequelpro/sequelpro#2084]
On, http://www.sequelpro.com/docs/Source_Code, it mentions the old svn repo and not the GitHub URL.

**Comment by dmoagx** [comment]
Coincidentally Google decided today to shutdown Google Code: http://google-opensource.blogspot.de/2015/03/farewell-to-google-code.html

**Comment by dmoagx** [comment]
Has been fixed now.
Thanks for reporting.
