### ISSUE TITLE
Varchar editing launches edit window

### ISSUE THREAD

**Issue by dasuchin** [sequelpro/sequelpro#2088]
My Sequel Pro is all of a sudden launching the large edit window when editing a varchar type. Not sure what happened, but previous to a few days ago it would just let me edit inline. Now it's acting like I'm editing a text type rather than varchar.

Anyone else having this issue, or is this a new feature or something? It'd be nice to be able to just edit it inline like previously.

**Comment by dmoagx** [comment]
This is a feature.
Go to Edit menu and disable "Edit all fields in Popup Sheet."
