### ISSUE TITLE
[REQ] Linking and navigating tables using foreign key

### ISSUE THREAD

**Issue by ghost** [sequelpro/sequelpro#209]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=209
Reporter:christia...@gmail.com Date:2009-03-27 06:39:52 Status:Duplicate Closed:2011-01-01

Navigating between mysql tables could use the relationships made by foreign keys.

So for example, say that you have a PRODUCT table with a cat_id 5, there would be a small itunes-
like arrow next to that 5, so that clicking that arrow would go to the CATEGORY table, filtered to the 
row with id=5.

Nice to have:

Knowing the foreign key relationships, one could also have a dropdown next to that 5, so that 
opening the dropdown would show not only all possible valid choices (limited to a max number), 
but also arrows next to them so you could instantly navigate to that choice, like above.

**Comment by Sofianio** [comment]
It seems this amazing functionality was dropped in recent builds, please bring it back
