### ISSUE TITLE
Don't overwrite user-supplied connection name

### ISSUE THREAD

**Issue by mattsharkey** [sequelpro/sequelpro#2091]
Changing the connection information will cause any user-supplied connection name to be overridden.

STEPS TO REPRODUCE
1. Enter the name for a new connection.
2. Enter the host for the connection. The name will be replaced by the host.

DESIRED BEHAVIOR:
If a custom name has been given, changing the host or username should not modify it. If no custom name has been given, a name is generated based on the connection information.

**Comment by jfi** [comment]
Agreed on this - can see why current functionality is there, but it is annoying.

**Comment by dmoagx** [comment]
Can't reproduce with either 1.0.2 nor 1.1rc2.
If this is still an issue please clarify the steps to reproduce.

**Comment by dmoagx** [comment]
Closing after no feedback.
