### ISSUE TITLE
Dialog window too large on Import

### ISSUE THREAD

**Issue by tlueker** [sequelpro/sequelpro#2092]
I'm running version 1.0.2 build 4096, on Yosemite 10.10.2 (14C1514)

Whenever I use File/Import, the main Sequel Pro window shifts to the top of my display and the file selection dialog opens full screen with the buttons unreadable.  There is no way to resize the window.

If I drop the resolution on my monitor, and then increase it, the dialog will shrink, and I can resize it.  However, when I reboot my computer, the oversized dialog returns.

Here is a screen shot before I open the dialog:
![screen shot 2015-04-01 at 17 51 30](https://cloud.githubusercontent.com/assets/520097/6953521/cb4c1194-d897-11e4-9728-13fd51586e0d.png)

Here is a screen shot of the import dialog.
![screen shot 2015-04-01 at 17 54 42](https://cloud.githubusercontent.com/assets/520097/6953572/3474bdd8-d898-11e4-97c9-67113ea13bea.png)
dialog open:

**Comment by abhibeckert** [comment]
We're not doing anything to control the panel size. I suggest sending a bug report to https://bugreport.apple.com instead.

**Comment by tlueker** [comment]
Thanks for the fast reply and link.

**Comment by willtcarey** [comment]
http://sixcolors.com/post/2014/11/attack-of-the-50-foot-save-sheet/

You might try taking a look at this post and seeing if it works for you. The dialog box expanding is a known Yosemite bug

**Comment by tlueker** [comment]
Super.  Thanks for the link willtcarey. I only encountered this issue with SequelPro imports (I do lots of them throughout the day).  I'm glad to learn Im not the only one with this issue and that it is a known Yosemite bug. My searches did not uncover it, so I guess I need to work on my search skills ;-)

**Comment by dmoagx** [comment]
>  there’s a bug in Yosemite that causes a sheet to grow taller by 22 pixels every time you use it.

Heh, yeah I've seen that myself, too.

For reference:
> Daniel Ericsson points out that if you hold down the shift key and drag inward on the edge of the save sheet, the sheet will get shorter—even if there’s no room for the sheet to actually get narrower!
