### ISSUE TITLE
Sequel Pro 1.0.2 (OSX 10.10.2 + 10.10.3) crashes after adding new user

### ISSUE THREAD

**Issue by mhmli** [sequelpro/sequelpro#2095]
Every time! (The add works though.)

**Comment by dmoagx** [comment]
Duplicate of #1961.
Please search for existing issues before creating a new one!

**Comment by mhmli** [comment]
Apologies. Opened a new ticket as a) http://nightly.sequelpro.com/ doesn't work any more and b) #1961 hasn't been touched for the last few months.
