### ISSUE TITLE
Stale data keeps being displayed when querying Percona DB

### ISSUE THREAD

**Issue by checketts** [sequelpro/sequelpro#2097]
I believe the core of this problem is related to autocommit not working quite right.

When I connect to a percona DB with Sequel Pro and view a table's contents, the data is cached and stale if it is updated externally (like some running code makes an update).

Even if I run a manual query I see the stale data, unless I issue a `commit` before running my query.

Order of operations:
1- Query DB - `select age from users where id = 1` -. result 25
2- Other DB user updates the row to 35 and commits it
3- Rerun query in step 1 and see that result is still 25
4- rerun query in step one preceded with a 'commit' call and get the correct value.

Similar issues occur if I issue an update statement. I'd love to set some sort of `autocommit = true`, but I can't seem to find a setting anywhere.

We didn't see this behavior with our old MySQL DBs, only began manifesting itself once we switched to Percona. Also other DB clients (like MySQL Workbench and raw JDBC connections) aren't running into this problem.

**Comment by dmoagx** [comment]
Sequel Pro does not change the autocommit and transaction isolation settings.
The default behavior of MySQL is to have autocommit enabled.
Your server probably has a different default configuration.

Sequel Pro does not do transaction handling because no one has come up with a good solution for handling the mix of MyISAM and InnoDB tables.

**Comment by checketts** [comment]
Are there any hooks that I can setup in Sequel Pro so when it connects it run a command? ie `set autocommit=1`

**Comment by checketts** [comment]
Additional information: my coworker isn't running into this problem. He is running Version 1.0.2M Build 4135. I'm running 1.0.2 4096

Now to find where build 4135 might be downloadable to try it out....
