### ISSUE TITLE
[REQ] Committable table structure changes

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#210]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=210
Reporter:christia...@gmail.com Date:2009-03-27 06:44:12 Status:Accepted

The suggestion is to allow for table changes to be committed atomically instead of immediately like 
now (at least the option).

The reason is, if there is a lot of data in a mysql table, a single change can take literally an hour or 
more. The current instant change method is good and works great for prototyping, however when 
you work with a table with 10 million records and you add a column and make a mistake it is 
problematic.

Suggestion is an edit mode button, so that you enter an edit mode in which changes are stored but 
not committed. When the user is done, he can either cancel this mode or commit. I suggest 
showing a window with the SQL changes about to be made first, editable, so the user can manually 
customize, and then having a commit button to really apply the changes.

**Comment by fulldecent** [comment]
Manually uploading old screenshot from Google Code:

![sqlp](https://cloud.githubusercontent.com/assets/382183/24383345/662cc356-132a-11e7-92b6-46d578128593.png)

**Comment by huhx** [comment]
I think this is a very import issue
