### ISSUE TITLE
Text field opens for VARCHAR

### ISSUE THREAD

**Issue by vanamerongen** [sequelpro/sequelpro#2103]
Up until about 10 minutes ago, when I entered a value in a VARCHAR field, I could type the value straight into the column. Now, suddenly, all my VARCHAR columns open up a text field as if they were TEXT columns. (See screenshot).

edit: Just checked, it seems to do it with any other type of column as well.
edit2: v 1.0.2, b 4096

![varchar](https://cloud.githubusercontent.com/assets/12083998/7296891/fce9a03a-e9c3-11e4-9702-251102267990.png)

**Comment by willtcarey** [comment]
@vanamerongen I believe this was answered in #1814

**Comment by dmoagx** [comment]
Indeed. → Duplicate
