### ISSUE TITLE
Add option to select different theme for each connection

### ISSUE THREAD

**Issue by jiri-neuman** [sequelpro/sequelpro#2104]
It would be nice to have the option to select different theme for each configured connection. This would help in differentiating different types of connection (e.g. production vs. test).

For example, seeing red background color on the open connection tab, you will instantly know that you are working with production database and this might save you a lot of time rolling back changes that were meant to be executed on test environment instead.

**Comment by mmoline** [comment]
Couldn't agree more!  Made the production vs. test mistake more than once.  :-(

**Comment by graudeejs** [comment]
Just wanted to create exactly the same feature request

**Comment by Jellyfrog** [comment]
Tab colours aren't enough?
![screenshot 2015-07-22 16 40 04](https://cloud.githubusercontent.com/assets/759887/8828084/9325a00e-3090-11e5-88d0-4d351bd92638.png)

**Comment by mmoline** [comment]
How’d you do that?!

**Comment by Jellyfrog** [comment]
Just set a color on the saved connection, if you don't see it, download the pre-release/nightly
![screenshot 2015-07-22 17 51 51](https://cloud.githubusercontent.com/assets/759887/8830043/5edbf64a-309a-11e5-8f6b-a6c8340b60b8.png)

**Comment by mmoline** [comment]
aha!  I can’t do pre-release on production database.  I’ll wait till it makes it into official release.

**Comment by jiri-neuman** [comment]
I agree this will be completely sufficient solution when it is released. I am looking forward to the stable release with this feature implemented.

**Comment by webmaestro** [comment]
@jiri-neuman - Can this be closed, since it appears to be LIVE now and appears to COMPLETELY rock!? ;-)

**Comment by jiri-neuman** [comment]
Sure, the feature is exactly what was needed. Closing.
