### ISSUE TITLE
XML Export Entities

### ISSUE THREAD

**Issue by designermonkey** [sequelpro/sequelpro#2108]
Our database contains a lot of html entities, which are being escaped as `&amp;nbsp;` (for example) which shouldn't be happening. Entities here are my problem to provide as numeric or alter post export, but it is harder to do when the software is escaping the ampersand.

The HTML elements are escaped, but I would expect this behaviour to prevent invalid XML syntax (like a floating `<` in the middle of content.

Another example is a numeric entity from our content that is being escaped too:

```xml
<introduction>&lt;p&gt;Amor Em Peda&amp;#195;&amp;#167;os ( Love in Pieces )  Fruit pie - a tradicional Minas Gerais recipe&lt;/p&gt;</introduction>
```

So, while HTML elements are being escaped correctly, all other entities in the content should really be left alone.

**Comment by dmoagx** [comment]
> So, while HTML elements are being escaped correctly, all other entities in the content should really be left alone.

No, every entity in the content has to be escaped upon export.
This must be done as an import would unescape every entity it finds.
Therefore if we exported
> Peda&#195;&#167;os
as it were, after importing again it would become
> PedaÃ§os

Just for reference, here is what `mysqldump` does:

```xml
<?xml version="1.0"?>
<mysqldump xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<database name="test">
	<!-- ... -->
	<table_data name="こんにちは">
	<row>
		<field name="id">1</field>
		<field name="data">hallo&amp;nbsp;welt</field>
	</row>
	</table_data>
</database>
</mysqldump>
```

```sql
-- MySQL dump 10.13  Distrib 5.5.33, for osx10.6 (i386)
--
-- Host: localhost    Database: test
-- ------------------------------------------------------
-- Server version	5.5.33

-- ...
INSERT INTO `こんにちは` VALUES (1,'hallo&nbsp;welt');
-- ...
```
