### ISSUE TITLE
Application stalls

### ISSUE THREAD

**Issue by pretty** [sequelpro/sequelpro#2109]
Hi Guys,

So I use SSH to connect to my databases. I have a pretty decent sized database but often after a while of switching tables it just hangs and stops responding. It won't show any error and I have to quit and re-open.

Thanks,
Stefan

**Comment by dmoagx** [comment]
Go to Activity Monitor, select Sequel Pro when it hangs and then do "Analyze Process" and post the output here.

**Comment by pretty** [comment]
I'm on Mountain Lion. It let me do a sample:

However, when I went back to app it let me submit a error report. I have added a message so you know it's me.

Let me know if you want the process sample.

Stefan

**Comment by dmoagx** [comment]
Related reports: 
http://log.sequelpro.com/view/4113
http://log.sequelpro.com/view/4116

This might be related to #1925

**Comment by dmoagx** [comment]
If you have a test environment, please try a recent nightly build from http://nightly.sequelpro.com/ and report your results.
You should not use those with production databases!

**Comment by dmoagx** [comment]
Closing after no feedback from user.
