### ISSUE TITLE
Unknown collation: 'utf8bm4_unicode_ci'

### ISSUE THREAD

**Issue by greg-prefer** [sequelpro/sequelpro#2112]
With the release of Wordpress 4.2, Wordpress will now [auto-upgrade](https://codex.wordpress.org/Version_4.2#Database) to utf8bm4 for sites where the version of MySQL supports it. When I try to import a database from a site that has upgraded, I get the unknown collation error.

**Comment by dmoagx** [comment]
That is a mysql server error. Nothing we can do about that.
