### ISSUE TITLE
invalid updates in query results

### ISSUE THREAD

**Issue by jdwuzhere** [sequelpro/sequelpro#2113]
This was _horrible_. Ran in nightly 4454.

```sql
CREATE TABLE `tttz` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `user` char(10) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM

INSERT INTO `tttz` (`id`, `user`) VALUES (NULL, 'aaaa');
INSERT INTO `tttz` (`id`, `user`) VALUES (NULL, 'cccc');
INSERT INTO `tttz` (`id`, `user`) VALUES (NULL, 'bbbb');
INSERT INTO `tttz` (`id`, `user`) VALUES (NULL, 'bbbb');
INSERT INTO `tttz` (`id`, `user`) VALUES (NULL, 'aaaa');
```
Now let's go to the query tab and run the following 
```
select * from tttz order by id

1	aaaa
2	cccc
3	bbbb
4	bbbb
5	aaaa
```
OK, result is obvious. Now select second row (id=2) in results part and double click (to edit) “cccc”. Somewhere in another MySQL connection issue

delete from tttz where id='2'

CAREFULLY (not to lose editing focus from “cccc”) return to the Sequel Pro query window and hit Cmd-R to execute the same “select * from tttz order by id”.

The result of refreshed query window will be
```
1	aaaa
3	cccc <=====
4	bbbb
5	aaaa
```
Now id=2 is gone as expected BUT WTF? id=3 now has user=‘cccc’! Behind the scenes the Sequel Pro issued
```sql
select * from tttz order by id; -- <==== our query
SHOW COLUMNS FROM `test`.`tttz`;
SELECT COUNT(1) FROM `test`.`tttz` WHERE (`id`='3');
UPDATE `test`.`tttz` SET `test`.`tttz`.`user` = 'cccc' WHERE (`id`='3') LIMIT 1;
```
WHY?!

**Comment by dmoagx** [comment]
Issue reproducible in 1.0.2 and nightly 4454.

**Comment by sequelpro** [comment]
The order of the events here will be at fault - committing the cell edit after the refresh keypress has been processed.  Ordering of the edit-end event may well have changed across OS X versions…

**Comment by rowanbeentje** [comment]
Apparently replying to notifications email posted as the project group.  Apologies :)
