### ISSUE TITLE
Retina icons confusion

### ISSUE THREAD

**Issue by dmoagx** [sequelpro/sequelpro#2115]
Sequel Pro somehow seems to get confused by Retina icons.

For example "button_action" exists as regular and retina version, but Sequel Pro always used the regular version, even on retina screens (same for "button_refresh").
![bildschirmfoto 2015-05-14 um 23 43 54 kopie](https://cloud.githubusercontent.com/assets/5793864/7642682/58768546-fa93-11e4-853a-3301462e192c.png)
(screenshot on retina screen, 2x image on the left for reference)

Then "button_info_pane_*" also exists in both versions and Sequel Pro picks the correct version based on screen.
![bildschirmfoto 2015-05-14 um 23 48 01 kopie](https://cloud.githubusercontent.com/assets/5793864/7642859/b12e0ab4-fa94-11e4-9501-f464de3a4d15.png)

I added another retina icon and for that Sequel Pro always uses the retina version, even on regular screens.

**Comment by abhibeckert** [comment]
I don't know what it was, but there was something in the metadata for all the 2x images that stopped them from being used.

I opened in pixelmator, re-exported, and all the 2x images work now.
