### ISSUE TITLE
forgets sort setting when changing tables

### ISSUE THREAD

**Issue by feens** [sequelpro/sequelpro#2119]
I'm running the nightlies (currently on c7488d7bd4) and noticed that now when you switch tables, the sorting is dropped when you go back. i.e. it used to work such that if I sorted by a field on table a, then went to table b, and back to table a, table a was still sorted by my previous selection.

**Comment by dmoagx** [comment]
Works for me.
Please provide detailed steps to reproduce.

**Comment by feens** [comment]
pretty simple...I click on a table, sort it by any column, click on another table, then click back to the first table and it's no longer sorted. I did a quick screen recording to show the issue which you can find here: https://dl.dropboxusercontent.com/u/163317/sequel%20pro%20sort%20issue.mov

**Comment by dmoagx** [comment]
Works for me:
https://www.youtube.com/watch?v=DY0lSaicTVM

Please backup your preferences file `~/Library/Preferences/com.sequelpro.SequelPro.plist` and delete it to see if that changes anything.

**Comment by feens** [comment]
I updated to the next nightly build (f94aeb5) and that seems to have fixed it.  Odd but good.
