### ISSUE TITLE
Crash when connection is lost

### ISSUE THREAD

**Issue by amirabiri** [sequelpro/sequelpro#2123]
Setup is virtual box VMs (using vagrant). VMs run mysql instances. Sequel pro runs on host connecting to these VMs via vagrant forwarded ports.

Sequence of events is:

1. Window or tab open with a connection to one of these VMs.
2. Respective VM is shut down.
3. Query is run in another window or tab.
4. Sequel pro shows error message saying connect is lost.
5. Click on 'close connection'.

--> crash.

Sequel pro version 1.0.2 build 4096.

I tried submitting this through the 'feedback' popup that open up when Sequel pro is run after the crash, but that also failed with an error message saying 'error submitting your feedback to the server'.

**Comment by willpower232** [comment]
I shut down a vagrant without closing the tab in sequel pro the other day but I got a message saying the connection had been lost rather than the whole program crashing.

Are you connecting over SSH or directly through the MySQL port?

**Comment by amirabiri** [comment]
I use vagrant's port forwarding. I'm guessing that means SSH, but I don't know for sure what they use.

**Comment by willpower232** [comment]
Do your connection settings resemble this screenshot?

![screen shot 2015-05-28 at 14 05 15](https://cloud.githubusercontent.com/assets/1619102/7860632/a1187c1e-0542-11e5-8749-3c581d678bf5.png)

**Comment by amirabiri** [comment]
Nope:

![screen shot 2015-05-28 at 4 07 55 pm](https://cloud.githubusercontent.com/assets/351013/7860679/df765498-0553-11e5-938f-68f609f7a7d0.png)

And the relevant Vagrantfile snippet:

![screen shot 2015-05-28 at 4 11 46 pm](https://cloud.githubusercontent.com/assets/351013/7860731/47a6160c-0554-11e5-88d1-b511912ae5e3.png)

**Comment by willpower232** [comment]
Aha I see.

So the question is: **how well does sequel pro cope with the disappearance of a MySQL server without being properly disconnected beforehand** as I imagine the Vagrant part is largely irrelevant...

**Comment by dmoagx** [comment]
Please try a development build from http://nightly.sequelpro.com/ first and see if that works better.

**Comment by dmoagx** [comment]
Closing after no feedback from user.
