### ISSUE TITLE
Adding a database user crashes the application

### ISSUE THREAD

**Issue by mfronmark** [sequelpro/sequelpro#2128]
I have had this issue since installing version 1.0.2.

No matter the host or mysql version, the application crashes after I add a database user. Doens't matter if I add rights or not.

**Comment by dmoagx** [comment]
Duplicate of #1961.
Please search for existing issues before creating a new one.

**Comment by mfronmark** [comment]
Wow, that was fast. I did search but didn't find anything when I did.
