### ISSUE TITLE
[REQ] Transaction support

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#213]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=213
Reporter:schlabbe...@gmail.com Date:2009-03-27 19:11:45 Status:Accepted

Maybe we should add support for transactions.
The 3 relevant MySQL commands are BEGIN, COMMIT and ROLLBACK.

My idea would be to add a toolbar Item &quot;Transaction Mode&quot; that enables transactions.
Now there would be two ways to continue from here:

1) The item has an on/off state and when pressed the second time a sheet will appear asking you 
whether you want to commit or rollback.

2) The item will only enable transaction mode. We will then watch out for 
INSERT,UPDATE,DELETE,... queries and when they occur add a yellow bar below the toolbar 
saying &quot;You made unsaved changes to the database&quot; and two buttons &quot;Save&quot; and &quot;Revert&quot;. (I think 
of it like the Popup warning bar in Camino). See <a href="http://s3.amazonaws.com/cbo/img/feature-" rel="nofollow">http://s3.amazonaws.com/cbo/img/feature-</a>
ab-lg.jpg

Also: <a href="http://dev.mysql.com/doc/refman/5.1/en/commit.html" rel="nofollow">http://dev.mysql.com/doc/refman/5.1/en/commit.html</a>

**Comment by fulldecent** [comment]
I like the transaction toolbar button that is only enabled if transactions are supported by the server.

**Comment by abhibeckert** [comment]
I think transactions are dangerous, there are too many things that will automatically commit a transaction or just not be part of the transaction, which could result in data loss.

Or a connection could be dropped, would also result in a loss of all the work done under the transaction.

Experienced users can already begin/end a transaction with a custom query and they could create a bundle if this is frequently needed.

My feeling is transactions are designed to exist for a few milliseconds. They're not suitable left open for a long time.

Better to keep changes in memory on the client and apply them all at once, which might be possible after 2.0. We have multiple issues open for this, and should close all but one as a duplicate.

**Comment by RAlfoeldi** [comment]
@abhibeckert Well that last comment made my decision to go back to DbVisualizer very easy. I was looking for a native Mac client and trying out Sequel Pro, but not supporting transactions is a no go - and your comment "transactions are dangerous" very ... ahhh .... strange? Bye.

**Comment by abhibeckert** [comment]
@RAlfoeldi my point was simply that MySQL transactions aren't designed for this use case and we would need to be very careful not to cause data loss – since there are so many places where an active transaction will be ignored or will be implicitely commited without warning or error.

**Comment by mrjones2014** [comment]
@abhibeckert transactions are not working for me even when using `START TRANSACTION;` and `ROLLBACK;`

**Comment by calthomson** [comment]
@mrjones2014 

Try
```
SET autocommit = 0;
START TRANSACTION;
...
```

**Comment by rubenjleon** [comment]
@RAlfoeldi 

> You can use sequel pro with transactions by typing start transaction; commit; rollback; into the custom query pane.

That's exactly what I've always done and it works perfectly for me.  I explicitly control the changes I want to make.  Thanks!  But you should know... it's perfectly viable for transactions to last longer than a few milliseconds as after I make changes, I check and validate them before I commit them.  That takes longer.

**Comment by gdowdy3** [comment]
I have an existing table called `TempTable`.  To test the transaction/rollback functionality, I am executing the following queries in sequence:

```
set autocommit = 0;
start transaction;
alter table `TempTable` add `TestCol` varchar(30);
rollback;
```

Given what I've read above, I would expect the column `TestCol` to disappear after the `rollback` query, but it doesn't.  Am I doing something wrong?

**Comment by dmoagx** [comment]
https://dev.mysql.com/doc/refman/8.0/en/cannot-roll-back.html

**Comment by gdowdy3** [comment]
That is unfortunate... But thanks for informing me. :)
