### ISSUE TITLE
10.11: Switch to HTTPS for Feedback Reporter and Sparkle

### ISSUE THREAD

**Issue by dmoagx** [sequelpro/sequelpro#2131]
It seems like Apple wants to introduce a HTTPS requirement with 10.11:

https://developer.apple.com/library/prerelease/mac/releasenotes/MacOSX/WhatsNewInOSX/Articles/MacOSX10_11.html#//apple_ref/doc/uid/TP40016227-DontLinkElementID_17

This will probably become a requirement for the App Store, so we should update our service endpoints as well.

**Comment by abhibeckert** [comment]
What network requests do we make other than Sparkle, which won't be needed for an App Store build?

Sparkle depends on code signing which is stronger security than TLS, so it's not needed for that.

Still, I would definitely like our website to have SSL. I'll look into it.

**Comment by dmoagx** [comment]
Right, didn't think about that.
Would Feedback Reporter be included or do App Store apps have to use Apples crash reporter?

We'd also have to look at how this impacts the Bundles.
