### ISSUE TITLE
Some cut UI Strings and/or not translated (Spanish)

### ISSUE THREAD

**Issue by SamdeVega** [sequelpro/sequelpro#2134]
![captura de pantalla 2015-06-10 a las 16 04 21](https://cloud.githubusercontent.com/assets/10880609/8086414/3fdd1b4e-0f8d-11e5-8a62-7baa7d7c9113.png)
The "Bin..." String at the first image is cut.

![captura de pantalla 2015-06-10 a las 16 03 16](https://cloud.githubusercontent.com/assets/10880609/8086449/5abb4940-0f8d-11e5-9fb9-4e2c8af3b990.png)
Translations for Index columns names:
- “Comment” equals “Comentario”
- “Non_unique” equals “No único”
- “Key_name” equals “Nombre de la clave”
- “Seq_in_index” equals “Orden en el índice” (if “Seq” means sequence)
- “Column_name” equals “Nombre de la columna”
- “Cardinality” equals “Cardinalidad"
- “Sub_part” equals “Subparte”
- “Packed” is a polisemic word. I am not sure what it means there. I can try to translate it by context if it is used in a sentence.

![1](https://cloud.githubusercontent.com/assets/10880609/8101418/f2948c64-100e-11e5-933e-5ba78831e260.png)
Menu Bar > Database > Go to Database... (and title in the popup menu when you click on it)
- "Go to Database..." equals "Ir a la base de datos..."

![2](https://cloud.githubusercontent.com/assets/10880609/8101448/286de7ae-100f-11e5-88b6-50ec5ce30bdb.png)
- "Display Binary Data as Hex" equals "Mostrar datos binarios como hexadecimales"

![3](https://cloud.githubusercontent.com/assets/10880609/8101473/5ef196b8-100f-11e5-8abc-424abd8a42b9.png)
- "Enable notifications" equals "Habilitar notificaciones"
- "Notification Center will be used for sending notifications. Install Growl for advanced control over notifications." equals "El centro de notificaciones será usado para enviar notificaciones. Instale Growl para un control avanzado sobre las notificaciones."

Regards.

**Comment by dmoagx** [comment]
1.1rc1 includes the translations up to the point where 1.1rc1 was built.
If you added the translations afterwards they are not yet included (but will be in the next build).

You can either try a more recent development build from http://nightly.sequelpro.com/ or click on the Spanish flag at the bottom of http://dev.sequelpro.com/translate/languages/es/sequelpro

Then right click on your local copy of Sequel Pro and select "Show Package Contents".

Go to "Contents" > "Resources" and delete the "es.lproj" folder and replace it with the one you just downloaded.

**Comment by SamdeVega** [comment]
I see. I will try development builds.

Thank you for your explanation.

Regards.
