### ISSUE TITLE
Cannot Login with Blank Password

### ISSUE THREAD

**Issue by yuchunc** [sequelpro/sequelpro#2153]
Hi 

In my development environment, I have set root to use a blank password, so something like this would work.

$ mysql -uroot -p
Password: <Enter> 

However, when using Sequel Pro's login form, an empty password box doesn't grant me any privileges after login. I believe it is behaving more or less like the following. 

$ mysql -uroot

Am I doing something I shouldn't do? or is it missing the function?

Thanks for the awesome APP!

Mickey

**Comment by rowanbeentje** [comment]
Hi @yuchunc - I *think* the behaviour of `mysql -uroot` and `mysql -uroot -p` with an empty password is the same - I thought both cases are essentially treated as no password.

With Sequel Pro are you using a Socket connection type, or are you using a Standard connection with a local hostname?  The two do behave a bit differently depending on how MySQL is set up...

**Comment by dmoagx** [comment]
For me it's the same:
```
# mysql -uroot
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
# mysql -uroot -p
Enter password: 
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
```
(note the "using password: NO")

**Comment by jnesbitt** [comment]
This is still an issue.  No need to wait on a response from the original submitter.  Should be simple to set up a test and verify.

**Comment by dmoagx** [comment]
This issue is closed and as shown above Sequel Pro behaves exactly like the MySQL CLI client so we don't intent to change anything.

**Comment by juliocanares** [comment]
got into this today

**Comment by albertski** [comment]
I'm able to run `mysql -u root` without any issues and I don't have a password, but when leaving password blank in SQL Pro I'm getting the following error:

```
Unable to connect to host 127.0.0.1, or the request timed out.

Be sure that the address is correct and that you have the necessary privileges, or try increasing the connection timeout (currently 10 seconds).

MySQL said: Authentication plugin 'caching_sha2_password' cannot be loaded: dlopen(/usr/local/lib/plugin/caching_sha2_password.so, 2): image not found
```

**Comment by dt-justin** [comment]
I am having the exact same, testing on the command line

`mysql -u root` works

```
# mysql -u root
Welcome to the MySQL monitor.  Commands end with ; or \g.
```

`mysql -u root -p` fails

```
# mysql -u root -p
Enter password: 
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
```

And I can't get Sequel Pro to use mysql -u root without -p at all. :\\. maybe Sequel Pro needs to use a catch exception to try both version when password is empty?
