### ISSUE TITLE
Selecting badly encoded UTF8 shows NULL

### ISSUE THREAD

**Issue by 007** [sequelpro/sequelpro#2155]
Selecting badly-encoded UTF8 characters shows NULL instead of displaying garbage or any error value:

`SELECT title, HEX(title), UNHEX(HEX(title)) FROM data;`

title | HEX(title) | UNHEX(HEX(title))
--- | --- | ---
NULL|ED82A4EDA6A3383234393B3FEBA7A4EBA6A3383234393B3FEC958420EC84B8EC8381EC979020EC98A820EAB283EC9D8420ED9998EC9881ED95A9EBA6A3383234393B3FEBA6A3383234393B3F21|í¤í¦£8249;?ë§¤ë¦£8249;?ì ì¸ìì ì¨ ê²ì íìí©ë¦£8249;?ë¦£8249;?!
NULL|ED82A4EDA6A3383234393B3FEBA7A4EBA6A3383234393B3FEC958420EC84B8EC8381EC979020EC98A820EAB283EC9D8420ED9998EC9881ED95A9EBA6A3383234393B3FEBA6A3383234393B3F21|í¤í¦£8249;?ë§¤ë¦£8249;?ì ì¸ìì ì¨ ê²ì íìí©ë¦£8249;?ë¦£8249;?!
NULL|ED82A4EDA6A3383234393B3FEBA7A4EBA6A3383234393B3FEC958420EC84B8EC8381EC979020EC98A820EAB283EC9D8420ED9998EC9881ED95A9EBA6A3383234393B3FEBA6A3383234393B3F21|í¤í¦£8249;?ë§¤ë¦£8249;?ì ì¸ìì ì¨ ê²ì íìí©ë¦£8249;?ë¦£8249;?!
NULL|ED82A4EDA6A3383234393B3FEBA7A4EBA6A3383234393B3FEC958420EC84B8EC8381EC979020EC98A820EAB283EC9D8420ED9998EC9881ED95A9EBA6A3383234393B3FEBA6A3383234393B3F21|í¤í¦£8249;?ë§¤ë¦£8249;?ì ì¸ìì ì¨ ê²ì íìí©ë¦£8249;?ë¦£8249;?!
NULL|ED82A4EDA6A3383234393B3FEBA7A4EBA6A3383234393B3FEC958420EC84B8EC8381EC979020EC98A820EAB283EC9D8420ED9998EC9881ED95A9EBA6A3383234393B3FEBA6A3383234393B3F21|í¤í¦£8249;?ë§¤ë¦£8249;?ì ì¸ìì ì¨ ê²ì íìí©ë¦£8249;?ë¦£8249;?!
NULL|ED82A4EDA6A3383234393B3FEBA7A4EBA6A3383234393B3FEC958420EC84B8EC8381EC979020EC98A820EAB283EC9D8420ED9998EC9881ED95A9EBA6A3383234393B3FEBA6A3383234393B3F21|í¤í¦£8249;?ë§¤ë¦£8249;?ì ì¸ìì ì¨ ê²ì íìí©ë¦£8249;?ë¦£8249;?!

Selecting with the cmdline MySQL client shows the correct (invalid) data:

 title | HEX(title) | UNHEX(HEX(title))                                                             
--- | --- | ---
 키???8249;?매릣8249;?아 세상에 온 것을 환영합릣8249;?릣8249;?!                  | ED82A4EDA6A3383234393B3FEBA7A4EBA6A3383234393B3FEC958420EC84B8EC8381EC979020EC98A820EAB283EC9D8420ED9998EC9881ED95A9EBA6A3383234393B3FEBA6A3383234393B3F21 | 키???8249;?매릣8249;?아 세상에 온 것을 환영합릣8249;?릣8249;?!                  |
 키???8249;?매릣8249;?아 세상에 온 것을 환영합릣8249;?릣8249;?!                  | ED82A4EDA6A3383234393B3FEBA7A4EBA6A3383234393B3FEC958420EC84B8EC8381EC979020EC98A820EAB283EC9D8420ED9998EC9881ED95A9EBA6A3383234393B3FEBA6A3383234393B3F21 | 키???8249;?매릣8249;?아 세상에 온 것을 환영합릣8249;?릣8249;?!                  |
 키???8249;?매릣8249;?아 세상에 온 것을 환영합릣8249;?릣8249;?!                  | ED82A4EDA6A3383234393B3FEBA7A4EBA6A3383234393B3FEC958420EC84B8EC8381EC979020EC98A820EAB283EC9D8420ED9998EC9881ED95A9EBA6A3383234393B3FEBA6A3383234393B3F21 | 키???8249;?매릣8249;?아 세상에 온 것을 환영합릣8249;?릣8249;?!                  |
 키???8249;?매릣8249;?아 세상에 온 것을 환영합릣8249;?릣8249;?!                  | ED82A4EDA6A3383234393B3FEBA7A4EBA6A3383234393B3FEC958420EC84B8EC8381EC979020EC98A820EAB283EC9D8420ED9998EC9881ED95A9EBA6A3383234393B3FEBA6A3383234393B3F21 | 키???8249;?매릣8249;?아 세상에 온 것을 환영합릣8249;?릣8249;?!                  |
 키???8249;?매릣8249;?아 세상에 온 것을 환영합릣8249;?릣8249;?!                  | ED82A4EDA6A3383234393B3FEBA7A4EBA6A3383234393B3FEC958420EC84B8EC8381EC979020EC98A820EAB283EC9D8420ED9998EC9881ED95A9EBA6A3383234393B3FEBA6A3383234393B3F21 | 키???8249;?매릣8249;?아 세상에 온 것을 환영합릣8249;?릣8249;?!                  |
 키???8249;?매릣8249;?아 세상에 온 것을 환영합릣8249;?릣8249;?!                  | ED82A4EDA6A3383234393B3FEBA7A4EBA6A3383234393B3FEC958420EC84B8EC8381EC979020EC98A820EAB283EC9D8420ED9998EC9881ED95A9EBA6A3383234393B3FEBA6A3383234393B3F21 | 키???8249;?매릣8249;?아 세상에 온 것을 환영합릣8249;?릣8249;?!                  |

**Comment by dmoagx** [comment]
What exact version of Sequel Pro?
What exact version of MySQL?

Please also provide the `CREATE TABLE` and `INSERT` statements for your test data.
