### ISSUE TITLE
Update "Edit" menu

### ISSUE THREAD

**Issue by dmoagx** [sequelpro/sequelpro#2156]
Apple has added some items to the "Edit" menu in recent OS X versions.
We should probably change our MainMenu.xib accordingly.

**Comment by nacho4d** [comment]
@dmoagx  do you mean you want to add "Start dictation" and "Emojis and Symbols"? Or maybe any other stuff in mind?

Below is a screenshot of Finder on OS X 10.10.5
<img width="402" alt="screen shot 2015-08-22 at 16 15 04" src="https://cloud.githubusercontent.com/assets/111651/9422977/200beff8-48e9-11e5-9f7a-f6874c906262.png">

**Comment by dmoagx** [comment]
Mostly "Spelling & Grammar", "Substitutions" and "Speech"
![bildschirmfoto 2015-08-22 um 19 36 30 716](https://cloud.githubusercontent.com/assets/5793864/9425129/28205064-4905-11e5-8476-f1b8a67ac65a.png)

**Comment by nacho4d** [comment]
@dmoagx I Added three menus to edit:
"Spelling and Grammar" (replacing current "Spelling")
"Substitutions"
"Speech"

https://github.com/sequelpro/sequelpro/pull/2211

Probably you already know but apparently "Transformations" menu is also new. In Sequel there is "Convert". Probably we should rename "Convert" to "Transformations" as standard OS X menus.
