### ISSUE TITLE
empty release notes on nightly site and in the app itself

### ISSUE THREAD

**Issue by jdwuzhere** [sequelpro/sequelpro#2162]
this is it.

**Comment by dohpaz42** [comment]
Came here to basically say the same thing. When clicking on the "View All" link from the app, the URL http://nightly.sequelpro.com/release-notes?all only shows the header and footer, but no actual content from the Changes Feed. HTH

**Comment by dmoagx** [comment]
@rowanbeentje fixed it.

**Comment by rowanbeentje** [comment]
And added some monitoring.  Sorry :)
