### ISSUE TITLE
Search by word rather than individual letters in Database -> Go To Database?

### ISSUE THREAD

**Issue by alanhartless** [sequelpro/sequelpro#2165]
Thanks for the suggestion on how to search databases!! However, in RC 1.1 (not sure if it's in 1.0), it's filtering by each individual letter rather than the word.  Is there a way to get it to search by word? It kind of pulls in the majority of the databases when I search because it's matching anything that has the letters of the search field in the sequential order.  Wasn't for sure if this is by design or not?

Thanks!!
Alan

**Comment by dmoagx** [comment]
I re-added the possibility to search for whole words in 1b09381.
Just wrap the search term in quotes.

**Comment by dmoagx** [comment]
Closing after no feedback from user.
Assuming fixed.

**Comment by alanhartless** [comment]
Hi!

Sorry! Yes it was fixed in the nightly previews but it doesn't seem to be working since 1.1 stable was released.  Is it not part of that release?

Thanks!
Alan

**Comment by dmoagx** [comment]
No, it was too late and too big of a change to be included in 1.1.
For now you'll have to stay with the nightlies.
