### ISSUE TITLE
Duplicate Database doesn't respect primary IDs

### ISSUE THREAD

**Issue by Schrank** [sequelpro/sequelpro#2169]
A database with primary IDs 0 (such as magento) are changed while duplicating to the next auto_increment value. This shouldn't be the case.

**Comment by dmoagx** [comment]
Duplicate of #1978 
This fix is already included in 1.1rc1: http://www.sequelpro.com/blog/2015.06/sequel-pro-1-1-rc1/

**Comment by Schrank** [comment]
Damn, gave my best to find it before opening. Sorry for bothering, thanks for fixing!
