### ISSUE TITLE
Sequel Pro quits after creating new user

### ISSUE THREAD

**Issue by eriktobben** [sequelpro/sequelpro#2171]
Operating system: Mac OS X 10.10.4
Sequel Pro: 1.0.2

When trying to create a new user, assign a database and permissions and then Applying settings, the program quits. It seems to create the user with accurate information, but I have to start Sequel Pro again.

**Comment by dmoagx** [comment]
Duplicate of #1961.
This is already fixed in 1.1rc1 http://www.sequelpro.com/blog/2015.06/sequel-pro-1-1-rc1/
Please search for existing issues before creating a new one!
