### ISSUE TITLE
"Authentication plugin" error in El capitan 

### ISSUE THREAD

**Issue by RareAbhi** [sequelpro/sequelpro#2172]
Hi I have installed the latest release candidate and still getting the error 

MySQL said: Authentication plugin 'mysql_clear_password' cannot be loaded: plugin not enabled

**Comment by dmoagx** [comment]
Sequel Pro does not support `mysql_clear_password`.
Perhaps you can do this from Terminal:
```
export LIBMYSQL_ENABLE_CLEARTEXT_PLUGIN=1
/Applications/Sequel\ Pro.app/Contents/MacOS/Sequel\ Pro
```

**Comment by RareAbhi** [comment]
Hi @dmoagx  Thanks for helping out. Your fix works. I had a follow up query regarding the same. Before upgrading to El capitan I never had to set this flag. Why do I need to set the flag now and I am connection to the same database instance.

**Comment by dmoagx** [comment]
Have you perhaps updated from 1.0.2 to 1.0.2 (r4135) (this one was included with MAMP) or 1.1rc1?

**Comment by RareAbhi** [comment]
Yes @dmoagx  I am using 1.1rc1. But I upgraded only because the version that I had installed stopped working after the el capitan upgrade.

**Comment by dmoagx** [comment]
Then I'll merge this with #1836
