### ISSUE TITLE
Filtered table refresh

### ISSUE THREAD

**Issue by jdwuzhere** [sequelpro/sequelpro#2179]
In "content" view when you 
0. have a nightly build de096a38ff
1. have a "like" filter on CHAR(120) column
2. refresh the table
3. get empty result
because
2a the following is being sent to the server: /* 00:26:00 iiii+ provs */ SELECT * FROM `asns` WHERE `name` LIKE BINARY '%ojsc%' ORDER BY `added` DESC LIMIT 0,1000;

where added is timestamp column.

Initial filter sends just /* 00:25:20 iiii+ provs */ SELECT * FROM `asns` WHERE `name` LIKE '%ojsc%' ORDER BY `added` DESC LIMIT 0,1000;

The BINARY keyword is sent always during all the subsequent refreshes.

**Comment by dmoagx** [comment]
Can reproduce, but only if I press cmd+R. 
Using the refresh button works fine.
