### ISSUE TITLE
Crash on User Permissions Edit

### ISSUE THREAD

**Issue by Gasgeber** [sequelpro/sequelpro#2182]
Hi,
I use Sequel regularyl and I think its a really good tool. 
I have a really annoying bug which is reproducable (at least for me) and I hope you can fix this.
When I edit user permissions and I click on save Sequel crashes in 80% of the cases. Sometimes even on cancel. Good luck the settings are saved, but it is quite annoying to restart Sequel each time.
I have it running on OSX Yosemite.
Thanks 
Timo

**Comment by dmoagx** [comment]
Duplicate of #1961.
This is already fixed in 1.1rc1 http://www.sequelpro.com/blog/2015.06/sequel-pro-1-1-rc1/
Please search for existing issues before creating a new one!
