### ISSUE TITLE
Using SequelPro corrupts Mysql bin log

### ISSUE THREAD

**Issue by bbreukelen** [sequelpro/sequelpro#2184]
On my server, using sequelPro to make any transactions in a mysql database makes the mysql binlog unusable.

See screenshot:
![screen shot 2015-07-24 at 15 05 44](https://cloud.githubusercontent.com/assets/1590898/8874907/80d18540-3215-11e5-94d2-de43a24b0cf3.png)

The insert done by SequelPro generates a weird character behind the statement that mysql does not like. Mysql's behaviour during an import of this SQL file is unpredictable. It will not always throw an error but the row will not be inserted.

All database char% variables are set to utf-8 and so is the encoding setting on sequelPro.

Any idea how to fix this issue? A single update/insert/delete/alter from my client makes the entire binlog unusable.

Thanks

**Comment by dmoagx** [comment]
* What exact version of Sequel Pro?
* What exact version of MySQL?
* What are you trying to do (Running a SQL script, executing a custom query, changing a field via the table editor, ...)?

**Comment by bbreukelen** [comment]
Sequel Pro 1.0.2 build 4096
Platform: Mac OS X 10.7.5
Mysql 14.14 dist. 5.5.44 running on Debian x86_64

Examples of when this occurs are changing/deleting/adding a row in the table editor, altering/creating a table, manually executing an INSERT/UPDATE statement from the custom query console.

**Comment by dmoagx** [comment]
Please try 1.1rc1 first to check if the issue still exists: http://www.sequelpro.com/blog/2015.06/sequel-pro-1-1-rc1/

**Comment by bbreukelen** [comment]
I tried 1.1rc1 but it has the same result, puts the character right behind the statements.
Thanks

**Comment by dmoagx** [comment]
OK, can confirm this is a bug in Sequel Pro.

We basically do (simplified)
```c
cQueryStringLength = strlen(cQueryString) + 1;
queryStatus = mysql_real_query(mySQLConnection, cQueryString, cQueryStringLength);
```
which is wrong according to the mysql doc, as `mysql_real_query` interprets the input as a byte buffer, not as a C-Style string (like `mysql_query` does).

**Comment by bbreukelen** [comment]
Thanks a lot for the quick response. Any idea when a will be released? Thanks again!

**Comment by dmoagx** [comment]
Recent nightly builds from http://nightly.sequelpro.com/ should fix this.
Otherwise wait for 1.1rc2 or 1.1

**Comment by bbreukelen** [comment]
Wow, I used the nightly build and verified that the issue has been fixed.
Thanks a lot for the above and beyond!!
