### ISSUE TITLE
Component not having automatic width

### ISSUE THREAD

**Issue by mourawaldson** [sequelpro/sequelpro#2187]
When translated to Portuguese the following strings couldn't fit properly, this component should expand the width according the text length

![captura de tela 2015-07-26 as 5 33 56 pm](https://cloud.githubusercontent.com/assets/612061/8896017/934eea3e-33bc-11e5-941e-6283e48def47.png)
![captura de tela 2015-07-26 as 5 34 11 pm](https://cloud.githubusercontent.com/assets/612061/8896016/934efd6c-33bc-11e5-92f5-1eeed167528e.png)

**Comment by mourawaldson** [comment]
More components..
![captura de tela 2015-07-26 as 5 50 37 pm](https://cloud.githubusercontent.com/assets/612061/8896099/2f7373ce-33bf-11e5-9503-eecf11266d49.png)

**Comment by dmoagx** [comment]
Yeah, right now we have to fix those issues by hand by making the boxes larger.
This will probably improve after 1.1 release when we switch to 10.8 as minimum OS.
