### ISSUE TITLE
Couldn't find string to translate

### ISSUE THREAD

**Issue by mourawaldson** [sequelpro/sequelpro#2188]
According what I searched on the code, I'm not sure if the condition is matching properly to show the expected message.

https://github.com/sequelpro/sequelpro/blob/c124db7ac403cdd92cc2c26e572f37f7b7d4ae75/Source/SPDataImport.m

![captura de tela 2015-07-26 as 5 31 47 pm](https://cloud.githubusercontent.com/assets/612061/8896044/78c06110-33bd-11e5-8b6a-174ee5b32ff1.png)

**Comment by mourawaldson** [comment]
![captura de tela 2015-07-26 as 6 21 17 pm](https://cloud.githubusercontent.com/assets/612061/8896228/4dbe1d4e-33c3-11e5-8303-e5f62fe2a9e6.png)

**Comment by dmoagx** [comment]
"Query was empty" is an error message from the MySQL server. There is no need to translate those.

The column names in the second screenshot don't need translation either as those are explicit names. Translating that would perhaps even be more confusing for some users.
