### ISSUE TITLE
[Feature Request] Datepicker for date/time field types

### ISSUE THREAD

**Issue by Jellyfrog** [sequelpro/sequelpro#2190]
It would be nice to have a datepicker popping up when modifying date/time fields, like this:
![image](https://cloud.githubusercontent.com/assets/759887/8981174/7a3ff586-36b6-11e5-8b52-3f46a004c066.png)
The image is from; https://github.com/ThesaurusSoftware/TFDatePicker

**Comment by adius** [comment]
YES! YES! YES! 😜
