### ISSUE TITLE
SSH Tunnels fail on OS X 10.11 Betas

### ISSUE THREAD

**Issue by apemsel** [sequelpro/sequelpro#2195]
Somehow the command line uses slashes instead of colons for the port forwarding argument, resulting in the following error when trying to connect:

Used command:  /usr/bin/ssh -v -N -o ControlMaster=no -o ExitOnForwardFailure=yes -o ConnectTimeout=10 -o NumberOfPasswordPrompts=3 -o TCPKeepAlive=no -o ServerAliveInterval=60 -o ServerAliveCountMax=1 -p 24 apemsel@xxx.xxxxx.de -L 54347/127.0.0.1/3306

Bad local forwarding specification ' 54347/127.0.0.1/3306'

**Comment by Jellyfrog** [comment]
If you would search you would see there is tons of issues already reported;
https://github.com/sequelpro/sequelpro/issues/2189
https://github.com/sequelpro/sequelpro/issues/2176
https://github.com/sequelpro/sequelpro/issues/2166
https://github.com/sequelpro/sequelpro/issues/2050

Use 1.1-rc1...

**Comment by apemsel** [comment]
Oh I am sorry. Actually I searched, but the default filter was to search just the open issues, not the closed ones ;-)
