### ISSUE TITLE
Add support for JSON data type

### ISSUE THREAD

**Issue by dmoagx** [sequelpro/sequelpro#2199]
Since 5.7.8 MySQL has a new column type `JSON`.
There are also a number of new `JSON_*` functions we need to add to syntax highlighting.
Maybe also think about a GUI editor (like Apple's plist editor) and delta updates (e.g. `UPDATE ... SET col = JSON_INSERT(col, ...)`)

See:
http://dev.mysql.com/doc/refman/5.7/en/json.html
http://dev.mysql.com/doc/refman/5.7/en/json-functions.html

**Comment by abhibeckert** [comment]
I don't use MySQL 5.7 but I do frequently use TEXT columns with "_json" as a suffix on the column name.

It would be nice if these were also treated the same as JSON columns in the GUI.

**Comment by ivan-kleshnin** [comment]
MySQL 5.7.9 is now default Homebrew version. I would also like to see this supported.

**Comment by calebeaires** [comment]
:+1:

**Comment by yadounis** [comment]
I think this feature is the most important one to add.

**Comment by lucidlive** [comment]
I was surprised this feature didn't exist. I have to use another app just to update my columns to JSON type...

**Comment by calebeaires** [comment]
@lucidlive - the nightly build has this feature, I have using it as my primary app!

**Comment by SuperSeb92** [comment]
I'm unable to edit JSON using nightly build, on 5.7.10. I get the error:

> The row was not written to the MySQL database. You probably haven't changed anything.

**Comment by jessereitsma** [comment]
+1

I get the following error:
```MySQL said:

Cannot create a JSON value from a string with CHARACTER SET 'binary'.
```

**Comment by dmoagx** [comment]
@jessereitsma See https://github.com/sequelpro/sequelpro/issues/2647#issuecomment-278757124

**Comment by jessereitsma** [comment]
@dmoagx I don't see that option.
And I don't want a export of my database (/dump)
I was trying to duplicate a row.

**Comment by gabrielalack** [comment]
+1  this is forcing me to migrate to mysql workbench

**Comment by scgm11** [comment]
use nightly that has the feature

**Comment by turigeza** [comment]
+1

**Comment by murilozilli** [comment]
+1

**Comment by bistik** [comment]
+1

**Comment by JamesTheHacker** [comment]
Was forced to switch to MySQL workbench because of this problem :(

**Comment by turigeza** [comment]
While we are waiting this to be implemented I use a "Query Favorite" which is saved globally to convert TEXT column to JSON. 
 
So I would first enter the field as a TEXT default NULL. Move it around where I want it, name it and then convert the field type from TEXT to JSON.

It might help some of you 

> ALTER TABLE `my_table` CHANGE `my_text_column` `my_json_column` JSON;

The column name does not actually has to change
> ALTER TABLE `my_table` CHANGE `my_json_column` `my_json_column` JSON; 

While it is still a pain this helps me a lot. 
<img width="569" alt="screen shot 2017-07-03 at 14 10 27" src="https://user-images.githubusercontent.com/9335740/27794288-7597f254-5ff9-11e7-990c-7b8f440b3e4c.png">

**Comment by jonasbalius** [comment]
is there any chance this will ever happen?

**Comment by dmoagx** [comment]
@jonasbalius This has been answered _at least_ twice in this ticket already.

**Comment by gregblass** [comment]
Any idea when the next version will be released with this? Forced to use MySQL Workbench until then unfortunately.

**Comment by abhibeckert** [comment]
@gregblass just use a test build in the interim - it's stable right now and you can disable auto-update to make sure you it doesn't update to one that may be buggy.

The delay is mostly localisation which could take some time to fix.

**Comment by gregblass** [comment]
Got it. Where/how does one get the test build?

**Comment by paveljanda** [comment]
Also the export function fails to export JSON field.

**Comment by raymondjplante** [comment]
Any word on release when next release?  Been about 1/2 year since the last time someone @gregblass  asked this...

**Comment by billnbell** [comment]
Please support Mariadb 10.2 with JSON!.  It is erroring like nuts.

**Comment by nikhiltri** [comment]
+1 regarding the export function not working with JSON fields. I have to open up all my exports in Sublime and do a find and replace to get the file to import properly into another DB:

Find: `(X'[^,\)]*')`
Replace: `CONVERT($1 using utf8mb4)`

**Comment by Marco-Kawon** [comment]
Any news on this one? It's becoming critical four my dev team as our new project is using MySQL JSON Columns and import/export still fails

Cannot create a JSON value from a string with CHARACTER SET 'binary'.

**Comment by gregblass** [comment]
Looks like it may be done, but they're holding off on a release due to another feature?

Also looks like the maintainer is recommending building from source. I'm not sure if he understands that not everyone that works with MySQL on a Mac works with Xcode and is familiar or comfortable doing that. IMO it seems a little much to ask.

Personally I don't understand why an interim version can't be released before this other feature is finished, unless branch management got mismanaged or something.

**Comment by dmoagx** [comment]
I don't remember that we ever recommended building Sequel Pro from source, except for debugging very specific problems.

JSON support has been available in development builds for the past two years: https://sequelpro.com/test-builds

When will it be released?
No idea, releases require a number of different people with different personal schedules in different parts of the world.

**Comment by nikhiltri** [comment]
Two years seems like a long time for a feature to be in development builds and not make it's way to an official release.

**Comment by zebulonj** [comment]
I’m as eager as the next person to see this released, but think it’s unreasonable to complain about the release schedule for free software.

Many thanks to the maintainers. Glad to know this is in the dev builds/downloads. I’d previously overlooked that.

**Comment by gregblass** [comment]
For sure. I get that it is free, and I really appreciate that.

But I think that even with free software, there is some level of obligation for maintaining it. For instance, this was opened two and a half years ago. If things are taking that long, then the overall health of the project may need to be examined, and new maintainers may need to get involved.

**Comment by packytagliaferro** [comment]
Is there any update on this? I have been running into issues since I have JSON columns and cant export from my DEV to Staging environments with the JSON, get a binary error. I am happy to pay for something like Sequel Pro or any other option but exporting/importing JSON is becoming some major parts of my builds

**Comment by murilozilli** [comment]
@packytagliaferro Use the nightly build that has this feature

**Comment by dhcmega** [comment]
Hi
Is this the area from where to download the nightly build?
https://sequelpro.com/test-builds
Thanks

**Comment by gregblass** [comment]
@packytagliaferro I found a paid alternative, "Table Plus", and have never looked back. It's really great, has full JSON support, and also supports PostgreSQL. Highly recommended.

**Comment by afilina** [comment]
It would be nice if this was addressed instead of closing it.

**Comment by afilina** [comment]
Seeing as this project is effectively abandoned, it would be nice to archive it, to avoid any confusion about why 5-year-old issues get auto-closed for inactivity. Maybe the `stale` bot can also direct people to the pinned issue instead of suggesting to open a new issue.
