### ISSUE TITLE
Add support for generated columns

### ISSUE THREAD

**Issue by dmoagx** [sequelpro/sequelpro#2200]
MySQL 5.7.6 supports "Generated columns" i.e. columns where the value is the result of an expression.
Not sure how to support that in UI, but we probably need to take care to adapt the `CREATE TABLE` parser.

See:
http://dev.mysql.com/doc/refman/5.7/en/create-table.html#create-table-generated-columns

**Comment by awHamer** [comment]
+1, can't import a dump exported with SequelPro if there are one or more generated columns, it exports them as regular columns and it causes some errors.

**Comment by dmoagx** [comment]
I looked at `mysqldump` and they simply run `SHOW FIELDS FROM $table` and if the `Extra` column matches `STORED GENERATED` or `VIRTUAL GENERATED` they skip the column in output.

**Comment by razvanphp** [comment]
+1 please, tried with nightly build, still not there..

**Comment by cfh2sf** [comment]
+3 Please this would be so useful. Namely just exporting.

**Comment by frjok** [comment]
+1 I agree - should be very useful (I did not know this type of column but it seems very interesting to use…)
+ the fact it is badly presented right now : it shows nothing but 'Can NULL'

**Comment by natbentley** [comment]
+1 from me, and all my team - this is one issue that rears its ugly head on a daily basis, and kills Sequel Pro for us.  @dmoagx hit the nail on the head with the solution - if Sequel Pro was written in a language I could write in, I'd happily offer a PR, but it's way outside my comfort zone.

**Comment by razvanphp** [comment]
This is still needed, please reopen.

**Comment by Page-Carbajal** [comment]
+4 This really is a something important.

**Comment by cjsfj** [comment]
FWIW sequel Pro has been transitioned to the Sequel Ace project, which is downloadable via the Mac App Store

https://github.com/sequelpro/sequelpro/issues/3705

**Comment by olaoluwa-98** [comment]
This is still needed 😪
