### ISSUE TITLE
No utf8mb4 encoding or collations

### ISSUE THREAD

**Issue by samholmes** [sequelpro/sequelpro#2209]
I don't see utf8mb4 as an option under the available encodings. Does Sequel Pro not support this encoding yet? 

Also, it seems like when I connect to my database (hosted on AWS RDS), the `collation_connection` is always set to `'utf8_general_ci'` instead of my server's default for this parameter, `'utf8mb4_unicode_ci'`. I'm assuming the issue is that SP is not recognizing utf8mb4_* collations, so it's using the default utf8 collation (because it somewhat understand utf8mb4, maybe?).

What's going on here?

**Comment by dmoagx** [comment]
What version of Sequel Pro?
What MySQL version?

**Comment by samholmes** [comment]
Sequel Pro 1.0.2
MySQL 5.6.22

**Comment by dmoagx** [comment]
Please upgrade to at least 1.1rc2 http://www.sequelpro.com/blog/2015.08/sequel-pro-1-1-rc2/

**Comment by dmoagx** [comment]
Closing after no feedback from reporter.
