### ISSUE TITLE
Low Priority UI bug with closing tabs

### ISSUE THREAD

**Issue by tjchambers** [sequelpro/sequelpro#2221]
If I do the following: 

- open a tab and connect to a database
- open a second tab and connect to a database
- open a third tab, do nothing with it,  then click the x to remove the tab (Heading says 'Sequel Pro")

then 

- when it reverts to the last open tab the heading of the window is still 'Sequel Pro' (default on fresh tab) - NOT the MySQL version and database/table name like it normally shows when a connected tab is selected.

**Comment by dmoagx** [comment]
Reproducable in 1.1rc2
