### ISSUE TITLE
build with Xcode 7 throws openssl exception

### ISSUE THREAD

**Issue by aballi1** [sequelpro/sequelpro#2223]
Hi sequel Team, build fails due to missing openssl library in Xcode 7 (File: SPDataAdditions.m)
see attachment.

Best, Andre

<img width="1018" alt="bildschirmfoto 2015-09-11 um 23 47 26" src="https://cloud.githubusercontent.com/assets/10725082/9827131/95081006-58df-11e5-8bc7-bbecba3b4e27.png">

**Comment by dmoagx** [comment]
You probably are not building with the 10.8 SDK selected.
