### ISSUE TITLE
Cannot establish connection via SSH OS X El Capitan

### ISSUE THREAD

**Issue by deringer** [sequelpro/sequelpro#2225]
It would appear that the paremters for the `-L` option of SSH has changed in El Capitan.

```
Used command:  /usr/bin/ssh -v -N -o ControlMaster=no -o ExitOnForwardFailure=yes -o ConnectTimeout=10 -o NumberOfPasswordPrompts=3 -o TCPKeepAlive=no -o ServerAliveInterval=60 -o ServerAliveCountMax=1 user@host -L 53685/host/3306

Bad local forwarding specification ' 53685/host/3306'
```

Running the same command but replacing the `/` characters in the `-L` option with `:`, the forwarded SSH connection is successful:

```
/usr/bin/ssh -v -N -o ControlMaster=no -o ExitOnForwardFailure=yes -o ConnectTimeout=10 -o NumberOfPasswordPrompts=3 -o TCPKeepAlive=no -o ServerAliveInterval=60 -o ServerAliveCountMax=1 user@host -L 53685:host:3306
```

**Comment by Jellyfrog** [comment]
Use the search function; https://github.com/sequelpro/sequelpro/issues?utf8=%E2%9C%93&q=ssh

**Comment by deringer** [comment]
Thanks - foiled by the default open issue search.

Any indication on when 1.1 will reach release, or should I just install the nightly build?

**Comment by Jellyfrog** [comment]
If you don't want nightly use the RC; https://github.com/sequelpro/sequelpro/releases/tag/release-1.1-rc2

**Comment by deringer** [comment]
Thanks!
