### ISSUE TITLE
Readonly-mode

### ISSUE THREAD

**Issue by dfatt** [sequelpro/sequelpro#2227]
Add readonly-mode before connection to database.

**Comment by nehemiahjacob** [comment]
+1 for this. Should be simple validation before each query, But will be a valuable feature.

**Comment by stuconnolly** [comment]
As mentioned on #2739 this can be implemented using the variables that the startup option `--safe-updates` uses.

Should probably be a connection option with the values (defaults listed) for the following variables as preferences (either exposed or hidden).

    sql_safe_updates=1
    sql_select_limit=1000
    max_join_size=1000000

**Comment by jeffpeiyt** [comment]
+1

**Comment by dfatt** [comment]
I've mark bookmarks color
Production — purple
Dev — green
<img width="787" alt="screenshot at may 22 12-01-19" src="https://user-images.githubusercontent.com/1622674/40352634-fc99428c-5db7-11e8-905a-66a23c2197f6.png">

**Comment by dfatt** [comment]
@dohpaz42 of course. @stuconnolly proposed a solution.

**Comment by dohpaz42** [comment]
@dfatt I understand. However, the ticket he referenced is closed as well. The issue is now no longer active and being tracked.

**Comment by Sciscitator** [comment]
+1

**Comment by dohpaz42** [comment]
@stuconnolly please reopen this or #2739 so that this issue can continue to be tracked. Thank you. :)

**Comment by berz01** [comment]
+1

**Comment by faramund** [comment]
+1

**Comment by Juanpaie** [comment]
+1

**Comment by 5ay3h** [comment]
🤦
