### ISSUE TITLE
Large process list causes Sequel Pro to crash

### ISSUE THREAD

**Issue by JerVoo** [sequelpro/sequelpro#2228]
When trying to load the process list on a server which has a lot of open connections, Sequel Pro crashes.

This happens when the auto refresh is enabled and the list is being refreshed for the first time, but also happens after I kill a process and the process list is being reloaded.

The server I'm working currently has ~80 open connections which is a lot, but should not be too much.

**Comment by dmoagx** [comment]
Well, 80 isn't exactly a "large" list.

Are you using 1.1? http://www.sequelpro.com/blog/2015.08/sequel-pro-1-1-rc2/
What refresh interval is selected?
What is the actual crash report?

**Comment by dmoagx** [comment]
Closing after no feedback from user.
