### ISSUE TITLE
Use descending order when sorting default column for the first time

### ISSUE THREAD

**Issue by Alhadis** [sequelpro/sequelpro#2230]
Only a minor usability issue, but it's one that drives me nuts every time, and I figure it could do with a UX enhancement.

Consider the following scenario, after just having opened a table for the first time:

![figure-1](https://cloud.githubusercontent.com/assets/2346707/9924435/e1fb1676-5d42-11e5-8e5d-8bfd4a605ceb.png)

![figure-2](https://cloud.githubusercontent.com/assets/2346707/9924438/eb13d41e-5d42-11e5-814e-c35968bdb7f5.png)

![figure-3](https://cloud.githubusercontent.com/assets/2346707/9924446/f19247e4-5d42-11e5-9781-81633538ebb5.png)

**Comment by dmoagx** [comment]
Hold down shift while clicking on the column header to sort in the opposite direction.

I don't feel like we should go against the OS X default of sorting as used by virtually all other apps.

**Comment by Alhadis** [comment]
Actually had no idea you could do that.

![jjsdevl](https://cloud.githubusercontent.com/assets/2346707/9933391/dfb7044c-5d8d-11e5-85bc-1440dde1b704.jpg)

Thanks!

**Comment by rowanbeentje** [comment]
Hmm, I quite like this as a bit of ease of use though!  If there's a primary key perhaps we should always apply an ascending sort by default so the column is pre-selected as sorted...?

**Comment by dmoagx** [comment]
I think you mean descending?

We could perhaps do that for the PRIMARY key if it is a numeric field, but we'd have to check the effects on performance.

**Comment by rowanbeentje** [comment]
To match the default last-records-at-the-bottom view... I think that's ascending for ids etc, isn't it...? Anyway, to match the default current appearance :)

I think it'd definitely only be for numeric keyed columns, to avoid big performance issues, but that's probably a big percentage of the tables out there (I'd guess!)

**Comment by Alhadis** [comment]
Just tried this, and holding the `shift` key before pressing it does nothing.

I'm using Mavericks, and have strictly zero desire to upgrade to to Yosemite or El Capitan, due to each OS's interface looking like Technicolor/pastel-coloured flattened vomit. Have elaborated on this solely out of my hatred for the interface's lifeless look.

**Comment by dmoagx** [comment]
That feature was added after 1.0.2.
Try this: http://www.sequelpro.com/blog/2015.08/sequel-pro-1-1-rc2/

**Comment by Drusy** [comment]
> I don't feel like we should go against the OS X default of sorting as used by virtually all other apps.

Sometimes changes are good, right :smile:  ?

Most of the databases use auto increment fields as a PRIMARY key, which is often at the first position in the database structure.
Would it be possible (acceptable) to sort descending by default in this case ? What is your opinion on this ?

**Comment by chn42** [comment]
It's not that much of an OS X default, it's just the order in which the rows are stored in the database. If you want to change this to a sorting by something else, this will produce an unpredictable amount of load to your database server.

Changing this default as a setting would be an option, but I strongly suggest to not change the current default behavior.

p.s. clicking at an unsorted column with shift is working for me in current nightly.
