### ISSUE TITLE
Number rows in output

### ISSUE THREAD

**Issue by bernini** [sequelpro/sequelpro#2231]
When I'm running SELECT statements, I'd like for the rows to be numbered in the output. There are times I want to eyeball and know the number of rows that fit a criteria, without re-running the query or exporting to csv and counting there.

**Comment by dmoagx** [comment]
The number of rows is always displayed at the bottom window corner. What's wrong with that?

**Comment by bernini** [comment]
The full number is great, but sometimes I want to see what percentage of the results something represents. So for example, if my query is ordered by amount, I might want to see what percentage of the results is under $100. So I could scroll to $99.99 in my query and be able to tell at a glance that it's row X out of Y results.
