### ISSUE TITLE
Can't set CURRENT_TIMESTAMP as default value on DATETIME columns.

### ISSUE THREAD

**Issue by bajax** [sequelpro/sequelpro#2240]
According to what I'm reading, this was fixed a while ago but it looks like an old bug has resurfaced.

I'm running Sequel Pro version 1.0.2 connecting to a server running MySQL 5.6.19 on Ubuntu 14.04.

Basically, when I try to change a DATETIME column's default value to CURRENT_TIMESTAMP, Sequel Pro wraps it in quote marks, as if it were meant to be a string literal.  This obviously fails. 

I can work around this by copy-pasting the query, removing the quote marks, and running it manually, but I thought I'd bring this to your attention in case it isn't something I've messed up along the way.

![query failed](https://cloud.githubusercontent.com/assets/10482540/10108347/6340999e-638e-11e5-8edb-023eccfa322b.jpg)

Thank you for making this application available.

**Comment by dmoagx** [comment]
1.0.2 is oooooold. Try 1.1: http://www.sequelpro.com/blog/2015.08/sequel-pro-1-1-rc2/

**Comment by bajax** [comment]
Thanks, that got it.  The GUI told me there were no updates available, so I just assumed since the last mention of this bug fix was a couple of years ago that it had made it into my "most recent" version.

**Comment by dmoagx** [comment]
Well, technically speaking 1.0.2 is still the most recent release version.
RC builds are not distributed via the regular update channel, but 1.1 should be released pretty soon.

**Comment by samuelfine** [comment]
Unfortunately, I'm still seeing this issue:

![image](https://cloud.githubusercontent.com/assets/695568/10746206/da13649a-7c1e-11e5-92c6-7ed0047d1b20.png)

Version 1.1 (build 4499) on OS X 10.11.1. If there are any additional details that might be useful, let me know!

**Comment by mezod** [comment]
I had the same problem and also solved it updating my MySQL. If you are using MAMP, the latest version as of now 3.3 is still bundling MySQL 5.5, so you'll have to manually upgrade your MySQL.

**Comment by aniket-bheeshma** [comment]
The problem is due to microseconds added in default value in mysql new versions. See http://tekina.info/default-datetime-timestamp-issue-mysql-upgrading-5-6/ for solutions.
