### ISSUE TITLE
'openssl/aes.h' not found in SPDataAdditions.m

### ISSUE THREAD

**Issue by Commenter123** [sequelpro/sequelpro#2242]
I cloned the repo, opened it in Xcode, pressed Run.
Error: 'openssl/aes.h' not found in SPDataAdditions.m

How to resolve this issue?

**Comment by dmoagx** [comment]
OpenSSL is no longer being used.
If you want to build an older branch you have to supply the OpenSSL headers yourself.
Duplicate of #2223

**Comment by rowanbeentje** [comment]
(As t'other thread says, for the 1.1 branch or other, using the 10.8 SDK is best.  master shouldn't have references to aes.h at all)
