### ISSUE TITLE
Allow use of UUID() function in text fields

### ISSUE THREAD

**Issue by NielsJanssen** [sequelpro/sequelpro#2245]
Often I have to make an entry into a table which primary key is a UUID, for which I'd have to write a full INSERT query to fill just to dynamically set the ID field. It would be awesome to be able to use the UUID() function in a way similar to the NOW() function support in DATETIME fields.

**Comment by jbrooksuk** [comment]
What field type do you use with UUID?

**Comment by NielsJanssen** [comment]
We're using a CHAR(36).

**Comment by holtkamp** [comment]
:+1:

**Comment by abhibeckert** [comment]
Re-opening since the pull request only improved UUID handling, didn't make it perfect

**Comment by abhibeckert** [comment]
We need to support other column types (especially binary) and also a preference to include or strip hyphens.

This feature should also be exposed somewhere in the user interface (perhaps a right click menu item or bundle)

**Comment by dmoagx** [comment]
As mentioned in the PR:

If the column type is `BINARY(16)` and the user enters `UUID()` we can just convert that to `UNHEX(REPLACE(UUID(),'-',''))`.

A 16 byte binary field wouldn't be able to contain a 36 byte string uuid, anyway, so there should be no ambiguity about what the user wants.
Additionally we could do `REPLACE(UUID(),'-','')` for `[VAR]CHAR(32)` type fields.

**Comment by abhibeckert** [comment]
Also we should have a preference to use v4 UUIDs.
