### ISSUE TITLE
Can no longer connect to MySQL - mysql_clear_password error

### ISSUE THREAD

**Issue by mccall114** [sequelpro/sequelpro#2247]
Getting an error about mysql_clear_password when trying to connect to a MySQL server using SSL:

"Unable to connect to host <server>, or the request timed out.
Be sure that the address is correct and that you have the necessary privileges, or try increasing the connection timeout (currently 10 seconds).
MySQL said: Authentication plugin 'mysql_clear_password' cannot be loaded: plugin not enabled"

I already have LIBMYSQL_ENABLE_CLEARTEXT_PLUGIN=y and didn't have any issues with the prior version of Sequel Pro. When I upgraded, it no longer worked, so I had to downgrade.

**Comment by dmoagx** [comment]
> I already have LIBMYSQL_ENABLE_CLEARTEXT_PLUGIN=y 

That should still work.
Try setting it explicitly. From Terminal do:
```
LIBMYSQL_ENABLE_CLEARTEXT_PLUGIN=y /Applications/Sequel\ Pro.app/Contents/MacOS/Sequel\ Pro
```

**Comment by rgilchrist** [comment]
Hi 
I have the same issue as mccall114, Sequel Pro was working prior to the upgrade this morning. Now when I try and connect to a MySQL Server I get the message 

"MySQL said: Authentication plugin 'mysql_clear_password' cannot be loaded: plugin not enabled"

I have tried dmoagx's suggestion of setting it explicitly from the terminal and it does allow me to connect as long as its running in the terminal.

Cheers
Rob

**Comment by jdeliege** [comment]
Hello.
The Terminal command works, but it would be nice to have an "more user friendly" way to achieve the same result.
I'm also stuck with this new behavior.

**Comment by dmoagx** [comment]
> but it would be nice to have an "more user friendly" way to achieve the same result.

See my comments on #1836

**Comment by jdeliege** [comment]
We establish first a SSH connection to the MariaDB server, then a pam-ldap authentication locally (user has only @'127.0.0.1') 
So risk of clear password intercept is irrelevant in this case.

**Comment by eagleeyec** [comment]
We are using pam-ldap too and connecting with SSL. I agree with jdeliege it would be great to have a more user friendly way to set this please.

**Comment by michaelgmiller** [comment]
+1

**Comment by lgonzalez-silen** [comment]
@dmoagx you wrote in the other thread:

> Just adding it when using a SSL connection might be fine, but probably won't be enough to satisfy everyone.

Can you please do this? At least a good number of people will be satisfied. We only authenticate through keys, so enabling the plugin is not an issue.

It's really annoying not to be able to open the app directly. Otherwise, great app, thanks!

**Comment by dmoagx** [comment]
@lgonzalez-silen 
Even then we need some safeguards as some SSL configurations would still allow MITM attacks.

I looked at the code again and thought we might be able to replace the regular cleartext plugin with a custom cleartext plugin we have control over, but it looks like MySQL will always load the regular cleartext plugin first and not allow later plugins to override it.
Since there are no other hooks we could use, either, we'd have to patch the mysql source code, which I want to avoid.

**Comment by ArondeParon** [comment]
Is this still something being considered?

Being able to use cleartext authentication [is a requirement](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.Connecting.AWSCLI.html) when using IAM Authentication on AWS RDS, for example.

**Comment by adoering-te** [comment]
We had an employee have this occur today as well.

He does:
alias mysqlctenv="launchctl setenv LIBMYSQL_ENABLE_CLEARTEXT_PLUGIN 1"
mysqlctenv
Launches Sequel Pro
Receives error in https://github.com/sequelpro/sequelpro/issues/2247#issue-109188508

However, this only broke AFTER updating to 10.14.4. Following @dmoagx advice and running this:

> LIBMYSQL_ENABLE_CLEARTEXT_PLUGIN=y /Applications/Sequel\ Pro.app/Contents/MacOS/Sequel\ Pro

Works fine, but the question is why this broke ONLY for SequelPro after the upgrade to 10.14.4 (CLI client was working fine). We don't understand why this is occurring.

**Comment by hubertmine** [comment]
On macOS 10.14.5, using 
```
LIBMYSQL_ENABLE_CLEARTEXT_PLUGIN=y /Applications/Sequel\ Pro.app/Contents/MacOS/Sequel\ Pro
``` 
does not work for me. 

I've set up authentication for RDS MySQL via IAM as mentioned [here](https://github.com/sequelpro/sequelpro/issues/2247#issuecomment-363791300)

This works when using directly the command line with `mysql --enable-cleartext-plugin` 
First got an error regarding SSL on the db side `[ERROR] Authentication requires SSL encryption.` (while SSL in not enforced and CLI successfully connects without it), then using SSL got `Access denied for user `

**Comment by amazingandyyy** [comment]
@hubertmine hi did you manage to clean up the `Access denied for user` error?

I am following the same RDS and IAM auth docs.... after having the `--enable-cleartext-plugin` flag, I got `Access denied for user`
