### ISSUE TITLE
ssh connection fail

### ISSUE THREAD

**Issue by hedii** [sequelpro/sequelpro#2249]
hi,
OSX el capitan, sequel pro 1.0.2.
After the yesterday's update, a working favorite is not working anymore (i changed nothing):

````
Used command:  /usr/bin/ssh -v -N -o ControlMaster=no -o ExitOnForwardFailure=yes -o ConnectTimeout=10 -o NumberOfPasswordPrompts=3 -o TCPKeepAlive=no -o ServerAliveInterval=60 -o ServerAliveCountMax=1 -p 1987 hedi@123.456.789 -L 49868/127.0.0.1/3306

Bad local forwarding specification ' 49868/127.0.0.1/3306'
````
![capture d ecran 2015-10-01 a 08 56 44](https://cloud.githubusercontent.com/assets/5358048/10214639/71f5e7e2-681a-11e5-980e-d4233f218560.png)

**Edit:**
I see that this is already reported, but i cannot find the solution

**Comment by hedii** [comment]
Well...
there was another update which is working. i close

**Comment by dmoagx** [comment]
Duplicate of #2050
