### ISSUE TITLE
SSH tunnel failing: "bad local forwarding specification"

### ISSUE THREAD

**Issue by afoster** [sequelpro/sequelpro#2253]
Hi

Since I upgraded to OS X El Capitan today I can't connect to hosts via an SSH tunnel. The app reports "SSH connection failed! - The SSH tunnel has unexpectedly closed" and the detail dialog has something like:

```
Used command:  /usr/bin/ssh -v -N -o ControlMaster=no -o ExitOnForwardFailure=yes \
  -o ConnectTimeout=10 -o NumberOfPasswordPrompts=3 -o TCPKeepAlive=no \
  -o ServerAliveInterval=60 -o ServerAliveCountMax=1 sol1@10.1.13.14 \
  -L 55749/127.0.0.1/3306

Bad local forwarding specification ' 55749/127.0.0.1/3306'
```

If I run that command on a terminal I get the same output.

If I substitute the slashes in the `-L` argument with colons the tunnel is established successfully.

I can see that on previous versions of OSX, the ssh client might have supported slashes (it works under Mavericks and OpenSSH_6.2.p2, OSSLShim 0.9.8r for example) but no longer it seems?

My current ssh client version reports OpenSSH_6.9p1, LibreSSL 2.1.7.

Thanks!

**Comment by dmoagx** [comment]
Duplicate of #2050 
This has already been fixed since 1.1: http://www.sequelpro.com/blog/2015.09/sequel-pro-1-1-a-touch-of-colour-for-your-databases/
Please search for existing issues, before creating a new one.

**Comment by afoster** [comment]
Apologies, I only searched open issues. You're too fast!

**Comment by mattymess** [comment]
I just upgraded my computer to El Capitan and am running 1.1, but still getting this error. Any ideas?

**Comment by afoster** [comment]
@mattymess Do you get the same "Bad local forwarding specification" message or just "SSH tunnel has unexpectedly closed"? What does `ssh -v` say your SSH version is?

**Comment by mattymess** [comment]
"Bad local forwarding...". 

I'm using **OpenSSH_6.9p1, LibreSSL 2.1.8**

**Comment by afoster** [comment]
Is it possible you have multiple versions of SSH installed, such as through homebrew or macports?

**Comment by mattymess** [comment]
Not that I know of. This is a fresh El Capitan install and I haven't installed SSH with homebrew or macports. AFIK, El Capitan comes installed with openssh

**Comment by mattymess** [comment]
I should also not that I can also ssh into servers fine in my terminal

**Comment by afoster** [comment]
Can you post the full content of the error's detail dialog?

**Comment by mattymess** [comment]
```
Used command:  /usr/bin/ssh -v -N -S none -o ControlMaster=no -o ExitOnForwardFailure=yes -o ConnectTimeout=10 -o NumberOfPasswordPrompts=3 -o TCPKeepAlive=no -o ServerAliveInterval=60 -o ServerAliveCountMax=1 matt@54.234.34.45 -L 54484:db1.c0ehwl.us-east-1.rds.amazonaws.com:3306:3306

Bad local forwarding specification ' 54484:db1.c0ehwl.us-east-1.rds.amazonaws.com:3306:3306'
```

**Comment by afoster** [comment]
I would say the double 3306:3306 at the end of the tunnel is what's causing ssh to throw the error. Do you have an explicit value in the MySQL port field for this connection?

**Comment by mattymess** [comment]
LOL. I copied it straight from RDS without realizing that the appended the port onto the hostname. Thanks for the second set of :eyes:!!

**Comment by afoster** [comment]
:laughing:

**Comment by eugenedw** [comment]
Just upgraded to El Capitan as well and can't tunnel using sequel pro anymore. I don't have the repeated local mysql port. Here's what I'm seeing (destination IP intentionally masked):

Used command:  /usr/bin/ssh -v -N -o ControlMaster=no -o ExitOnForwardFailure=yes -o ConnectTimeout=10 -o NumberOfPasswordPrompts=3 -i /Users/eugene/Downloads/aws-sandbox.pem -o TCPKeepAlive=no -o ServerAliveInterval=60 -o ServerAliveCountMax=1 ec2-user@xx.xx.xx.xx -L 51141/127.0.0.1/3306

Bad local forwarding specification ' 51141/127.0.0.1/3306'

**Comment by eugenedw** [comment]
Sorry, just upgraded to 1.1.0.1, build 4500 - all is good.

**Comment by wonjun27** [comment]
LGTM

**Comment by Avnikaur** [comment]
Hello Everyone,

I am getting the same error for the following command:
ssh -N -L 5555:127.0.0.1:80 -i "DEV2.pem" ubuntu@ec2-54-210-156-51.compute-1.amazonaws.com

Bad local forwarding specification '5555:127.0.0.1:80 '
Any thoughts?

**Comment by abhibeckert** [comment]
@Avnikaur that's not the same problem, can you please open a new issue and provide more details? Eg what version of sequel pro and what version of OS X.

**Comment by Avnikaur** [comment]
# @Abhi 
I have never used sequel pro before. My OS X version is 10.11.5. A few days ago, I was able to run this command.

**Comment by abhibeckert** [comment]
@Avnikaur please open a new issue as this using this one sends unnecessary email notifications to a bunch of people.
