### ISSUE TITLE
Freezing with large tables, no option to cancel action

### ISSUE THREAD

**Issue by rickmills** [sequelpro/sequelpro#2267]
When working with a large database if you select a table that's locked as it's having something done against it, the whole app will lock up with a loading overlay. No option to 'cancel' or switch tables at all, meaning the only option is to force quit the entire app.

It's extremely frustrating.

**Comment by rickmills** [comment]
I might as well close this as its not going to be addressed.

**Comment by JamesVanWaza** [comment]
@rickmills follow all new development on https://github.com/Sequel-Ace/Sequel-Ace
