### ISSUE TITLE
Support other connection types

### ISSUE THREAD

**Issue by neildexter** [sequelpro/sequelpro#2270]
I love many things about Sequel Pro's user interface, key shortcuts, and aesthetic design. However, it does not appear that there is any support for many other types of connections or custom JDBC drivers (in my case, for Impala/Hive connections). This would be a very helpful feature as it would allow me the flexibility to work on those other platforms with my favorite client.

Thanks!

**Comment by dmoagx** [comment]
JDBC won't be happening. As the J implies, JDBC is a Java feature. Sequel Pro is ObjC/Cocoa.

Support for other databases is a well-known request: #362
