### ISSUE TITLE
CMD+number to for tabs instead of buttons

### ISSUE THREAD

**Issue by hanoii** [sequelpro/sequelpro#2274]
Maybe is a personal preference, but I wonder if it could be made a feature. I am very used to doing CMD+1 to switch tabs, it's the customary thing in Chrome, FF and finally in OSX 10.10 on Safari as well. I normally have a few sql instances open, so I'd appreciate switching a keyboard shortcut to switch fast between those, I seldomly change that much across buttons for the table.

**Comment by seybsen** [comment]
+1, would love this too
