### ISSUE TITLE
Search field loses focus too easily

### ISSUE THREAD

**Issue by goodtimeclub** [sequelpro/sequelpro#2276]
The filter's search field loses focus when you click away.

Specs: OS X El Capitan, SP nightly(and older builds)

For instance, let's say I click in the field to add a value I want to filter results by. When I select 1Password mini in the menu bar to click-to-paste something, the field unfocuses/centers the placeholder text("Search") with an animation.

**Comment by dmoagx** [comment]
There are like 6 different search fields in Sequel Pro. Which one are you talking about?

**Comment by goodtimeclub** [comment]
I'm referring to the Table Content Tab, where there is a Search form with a menu of columns to filter by, followed by a submit button labelled "Filter".

Most inputs simply retain focus when you switch apps but this one doesn't.

![screen shot 2015-10-08 at 5 18 25 pm](https://cloud.githubusercontent.com/assets/3542372/10380211/8cc5030c-6de0-11e5-9f4f-384941ebf1da.png)

**Comment by goodtimeclub** [comment]
I may have been mistaken when pegging this as a Sequel Pro issue - looks like the default behaviour in OS X Finder is the same. Not sure why a UI element should fail to retain focus when you switch back to an app. Please disregard this, I will investigate further on my own

**Comment by dmoagx** [comment]
No feedback from reporter for > 1 month, closing.
