### ISSUE TITLE
ECDSA private key support for SSH tunneling

### ISSUE THREAD

**Issue by chdeliens** [sequelpro/sequelpro#2279]
Hi,

Looks like ECDSA private keys are not supported by SequelPro regarding SSH tunneling.
When using them, it always prompts for a password then fails.

Debug logs is as follows:
```
debug1: Trying private key: /Users/obfuscated/.ssh/id_ecdsa
debug1: key_parse_private_pem: PEM_read_PrivateKey failed
debug1: read PEM private key done: type <unknown>
Saving password to keychain failed
debug1: key_parse_private_pem: PEM_read_PrivateKey failed
debug1: read PEM private key done: type <unknown>
```

Is the ECDSA support somewhere in the roadmap? :)

Thanks!
Chris

**Comment by dmoagx** [comment]
Sequel Pro supports what your systems SSH client supports.
We don't do anything with the files beyond passing them to ssh.

**Comment by chdeliens** [comment]
That's odd as I can connect to that server using SSH and my ECDSA key. Any clue where the issue could be? Thanks for your support!

**Comment by rowanbeentje** [comment]
@chdeliens Do you use a custom ssh build?  (eg does `which ssh` output `/usrbin/ssh`?)

**Comment by chdeliens** [comment]
@rowanbeentje could be that MacPorts does. ```which ssh``` outputs ```/opt/local/bin/ssh```

**Comment by dmoagx** [comment]
Sequel Pro uses `/usr/bin/ssh`. You can change that in Prefs.

**Comment by chdeliens** [comment]
@dmoagx Works! Thanks!
