### ISSUE TITLE
Can I edit the comment of the table (not column) ?

### ISSUE THREAD

**Issue by wanyaxing** [sequelpro/sequelpro#2285]
I did not find the way to edit the comment of the table.

If sequelpro can not do this, Is there any plan to support this feature? 

thanks.

**Comment by rowanbeentje** [comment]
Hi @wanyaxing,
You can edit the table comment on the "Table info" screen - it'll save once you're done.
We should perhaps make it clearer somehow that the comment is editable but the creation syntax isn't...

**Comment by wanyaxing** [comment]
cool, get it.

It was hidden in my sequelpro. -.-!!!

![qq20151013-0 2x](https://cloud.githubusercontent.com/assets/7940795/10449281/1e04ca40-71c5-11e5-8156-d25176e71c63.png)
