### ISSUE TITLE
Allow database rename on Export

### ISSUE THREAD

**Issue by leonar15** [sequelpro/sequelpro#2287]
I'd like to be able to set a new database name when exporting an existing database.

E.g Existing database is called "original_db" and I'd like to import schema and content to "new_db". Hard to manually edit a 500 MB .sql export

**Comment by dmoagx** [comment]
This seems like a highly specific use case to me (ie. too specific to include in Sequel Pro).
You should probably use a different tool for that (e.g. `sed`).
