### ISSUE TITLE
Trigger Painel - Bug Language

### ISSUE THREAD

**Issue by rasj** [sequelpro/sequelpro#2289]
If the language is not English, click triggers and click to edit a trigger, the options of "Action Time" always comes as "After" and "Event" always comes as "Insert"

It can occur in an unwanted change :-1:

**Comment by dmoagx** [comment]
Well it certainly looks correct to me and I too am using "not English".
![bildschirmfoto 2015-10-14 um 23 01 22 340](https://cloud.githubusercontent.com/assets/5793864/10497690/8cea3672-72c7-11e5-88da-a1cff2a6ad1d.png)

**Comment by rasj** [comment]
Always "Before" rather than "After", sorry ..
Languages with problems are:
- pt
- fr
- ru
- sv

I think it's because the value of the selects had its value changed by translation.

In other languages, the value of select keeps in "After", "before", "Insert", "Delete" and "Update"

<img width="924" alt="captura de tela 2015-10-15 as 00 11 40" src="https://cloud.githubusercontent.com/assets/2250535/10504064/fbae3c92-72d2-11e5-8802-ddebd2096414.png">
<img width="909" alt="captura de tela 2015-10-15 as 00 12 07" src="https://cloud.githubusercontent.com/assets/2250535/10504065/fbaf2468-72d2-11e5-9648-3bdffd1e0cc2.png">
<img width="890" alt="captura de tela 2015-10-15 as 00 15 13" src="https://cloud.githubusercontent.com/assets/2250535/10504066/fbb34d04-72d2-11e5-8063-1005072062fe.png">
<img width="804" alt="captura de tela 2015-10-15 as 00 15 20" src="https://cloud.githubusercontent.com/assets/2250535/10504068/fbb40082-72d2-11e5-902d-e051e1b5debd.png">
<img width="785" alt="captura de tela 2015-10-15 as 00 16 44" src="https://cloud.githubusercontent.com/assets/2250535/10504069/fbb3f182-72d2-11e5-9cd0-444381158140.png">
<img width="804" alt="captura de tela 2015-10-15 as 00 16 55" src="https://cloud.githubusercontent.com/assets/2250535/10504067/fbb37108-72d2-11e5-82ef-d663764e47ff.png">
<img width="752" alt="captura de tela 2015-10-15 as 00 17 27" src="https://cloud.githubusercontent.com/assets/2250535/10504070/fbc775b8-72d2-11e5-8832-7defee264459.png">
<img width="786" alt="captura de tela 2015-10-15 as 00 17 40 1" src="https://cloud.githubusercontent.com/assets/2250535/10504071/fbcc9174-72d2-11e5-9bb8-36d56a518d41.png">

**Comment by dmoagx** [comment]
I see. The panel was not properly prepared for localization.
This should be fixed now.

**Comment by dmoagx** [comment]
Issue fixed in 1.1.1
See http://www.sequelpro.com/blog/2016.02/sequel-pro-1-1-1/
