### ISSUE TITLE
Add support for LZMA (xz) compression

### ISSUE THREAD

**Issue by dmoagx** [sequelpro/sequelpro#2290]
We could add support for lzma compression on export.
`liblzma` is actually part of Apples OS X SDK, they just don't have added the headers.
`lzma_version_string()` returns:

| OS X | liblzma |
| --- | --- |
| 10.6 | (not present) |
| 10.7 | ? |
| 10.8 | ? |
| 10.9 | 5.0.3 |
| 10.10 | ? |
| 10.11 | ? |

This might be a good exercise for XPC.

**Comment by stuconnolly** [comment]
Should be done along with #1911

**Comment by Jellyfrog** [comment]
+1
