### ISSUE TITLE
Tabs disappear sometimes

### ISSUE THREAD

**Issue by cameronlockey** [sequelpro/sequelpro#2292]
Occasionally, if I have a fullscreen window with tabs that have been open for a while, the tabs will disappear. Only toggling fullscreen brings them back. Not a huge issue, but its a UI bug so I figured I'd report it. In the attached screenshot, you can see the tab-bar is no longer rendered — its just white.

![screenshot](https://cloud.githubusercontent.com/assets/2140971/10516043/58f6a244-7324-11e5-895d-04c37bcf2f9e.png)

**Comment by robindwilliams** [comment]
This happens to me whenever I leave the app in full screen and navigate away to other apps for a short period of time. Quite annoying, as you have to take the app out of full screen to get them back.
