### ISSUE TITLE
Need Save As in addition to Save in v1.1

### ISSUE THREAD

**Issue by JodyKampmeier** [sequelpro/sequelpro#2293]
The previous version of Sequel Pro always prompted for name & location on "Save Query". In v1.1 it appears to only prompt when it is a new query. I often edit existing queries and need the option to save it to a new file. When I execute "Save Query" under these circumstances, I overwrite the existing query. :-/ Please add a "Save Query As" option.

**Comment by dmoagx** [comment]
That feature is already there.
Just hold down the Shift key while clicking on "Save Query"
