### ISSUE TITLE
Can't open more than one .spf file

### ISSUE THREAD

**Issue by zledwon** [sequelpro/sequelpro#2294]
If I have a connection open (manually or from saved .spf file) Sequelpro won't open next .spf file, just starts empty new connection.
MacBook Pro late 2011, El Capitan

**Comment by dmoagx** [comment]
What do you mean by manually?

Opening an SPF file works fine for me. I can even open the same file multiple times to create multiple connection windows (from Finder and from File > Open...).

Try saving the SPF file again with 1.1 and see if that changes something.
If yes, open them both in TextMate/SublimeText/etc. and look for differences.

**Comment by zledwon** [comment]
By "manually" I mean - entering connection data to the connection form (instead of opening SPF file).

All my SPF files are saved with v. 1.1, and these are 'connection' files.

Take a look at this video https://youtu.be/QZOR8zoMdkQ to see how it happens.
I open one SPF file - it works fine; then I open another one but it just opens new empty connection.
Then I open those two files in reverse order, and the result is the same: first file always works fine and the next is just opening empty connection window.

**Comment by dmoagx** [comment]
Instead of Path Finder, can you try regular Finder or from Terminal (with the `open` command)?

**Comment by zledwon** [comment]
I tried all 3 (Finder, Terminal and PF) - works exactly the same, but since I tested it a bit more I have new clues:
- first spf always opens normally
- second NEVER opens (just opens new empty connection)
- third, fourth and next ones opens (but in the background - empty connection window stays on top)

If I close the empty connection window and try to open another spf - it will not work, just opens new empty connection.

**Comment by dmoagx** [comment]
* Do you have any system enhancements (e.g. SIMBL or tools using Accessibility Services)?
* Check Console.app for messages when you open a spf file
* Please create a new user account on your Mac and try it there.

**Comment by zledwon** [comment]
- I do use any system enhancements
- checked the Console but no messages showed up during opening spf files
- created and checked on new user account - same results, same behaviour

**Comment by dmoagx** [comment]
OK, this issue seems to be limited to 10.11

**Comment by dmoagx** [comment]
So it looks like Apple made a change to the window handling.

When opening a new window, Sequel Pro relies on the new window being in front, which has always been the case in the past.
However in 10.11 the new window is created in the back and only later moved to the front.

That is too late for Sequel Pro, which will just take the window that was already open instead and try to restore a connection there (which doesn't work, of course).

**Comment by dmoagx** [comment]
The last commit should hopefully fix that.
You can try a development build from http://nightly.sequelpro.com/

I'm not entirely sure how much of that change to backport for 1.1.1

**Comment by zledwon** [comment]
Yes. This was it. Problem is gone in 'nightly' :)

**Comment by dmoagx** [comment]
Issue fixed in 1.1.1
See http://www.sequelpro.com/blog/2016.02/sequel-pro-1-1-1/
