### ISSUE TITLE
ipv6 access?

### ISSUE THREAD

**Issue by lanzalibre** [sequelpro/sequelpro#2295]
Hi,

Google Cloud SQL now offers Mysql access through IPv6 (free) and Ipv4 addresses (for a minimum price). I try to connect through the ipv4 address and it works but it doesn't through ipv6.

**Comment by dmoagx** [comment]
From a quick test IPv6 works fine with Sequel Pro.
I don't have a "Google Cloud SQL" account, so I can't test further.
Most likely you are facing general IPv6 connectivity issues.

**Comment by lanzalibre** [comment]
General Ipv6 connectivity issues? Can you provide any hints?

[Here](https://drive.google.com/folderview?id=0B6_dMCCqdP-hS0FXVkVHSW02RDg&usp=sharing) you can see what I see. The only difference is the ip address. According to Google both ip's point to the same database so, why is it not working?

**Comment by dmoagx** [comment]
65 is the OS X error code for "no route to host", so it looks like your Mac has no IPv6 connectivity.

**Comment by lanzalibre** [comment]
Thanks, that was fast!

2015-10-21 10:33 GMT+02:00 Max Lohrmann <notifications@github.com>:

**Comment by dmoagx** [comment]
I'll assume the issue was somewhere else...

**Comment by pthieu** [comment]
@lanzalibre: I'm trying to connect using my ipv4 address to my google postgresql db server. I have allowed the server to be publicly accessible `(0.0.0.0/0)`. But when I use my credentials, it cannot connect, looks like it times out. How did you set up your db configuration?
