### ISSUE TITLE
Elliptical Curve Cryptography

### ISSUE THREAD

**Issue by geddes** [sequelpro/sequelpro#2296]
As far as I can tell sequelpro ships with yassl, which does not support ECC. The same is true for MySQLWorkbench Community Edition. However, MySQL itself does work with ECC, and at least one non-free client (MySQLWorkbench **Enterprise** Edition), ships with OpenSSL 1.0.1 and allows you to connect to a MySQL server configured with ECC-based keys, certs, and CAs. My testing shows that the MySQL CLI client works with ECC as well, at least on my machine. 

Would love to see ECC support in sequelpro, which could be achieved by shipping with OpenSSL.

**Comment by dmoagx** [comment]
OpenSSL won't be happening. Apple is currently in the process of dropping OpenSSL from OS X, and bundling sequel pro with OpenSSL is not something we want to do (esp. given how often it needs updates).

The alternative, which I've been thinking about would be using Apples SecureTransport, but that will probably require quite some integration work.

**Comment by geddes** [comment]
Max, thanks for the quick response and your reasoning. Didn't realize apple was dropping OpenSSL from OS X. Will close, but just wanted to let you know there is a vote for ECC! :) Thanks as always for your hard work on SequelPro.

**Comment by dmoagx** [comment]
> Didn't realize apple was dropping OpenSSL from OS X.

See https://developer.apple.com/library/watchos/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/SecureNetworking/SecureNetworking.html
> For this reason, linking to the built-in copy of OpenSSL is deprecated as of OS X v10.7. If you want to use OpenSSL, provide your own copy of the library

Starting with the 10.11 SDK Apple also no longer provides headers for OpenSSL (see #2223)
