### ISSUE TITLE
Quick create SELECT qeury from a filter and/or multiple filters

### ISSUE THREAD

**Issue by pablomedok** [sequelpro/sequelpro#2303]
It's a pretty common situation: I've created a filter in table results and understand that I need to narrow results a bit more. The only way to do it now is to switch to Editor and write a SELECT statement manually. Frankly speaking, I feel lazy about that. It's easy, but I have to do it too frequently. 

It would be good if there was a way to  covert current filter to SELECT statement in query editor. Alternatively or additionally it would be  good to be able to apply filter to multiple fields.

**Comment by ersinakkaya** [comment]
+1

**Comment by Bibiko** [comment]
> On 22 Oct 2015, at 13:17, pablomedok <notifications@github.com> wrote:
> 
> It's a pretty common situation: I've created a filter in table results and understand that I need to narrow results a bit more. The only way to do it now is to switch to Editor and write a SELECT statement manually. Frankly speaking, I feel lazy about that. It's easy, but I have to do it too frequently.
> 
> It would be good if there was a way to covert current filter to SELECT statement in query editor. Alternatively or additionally it would be good to be able to apply filter to multiple fields.

Hi,

by the way did you try "Advanced Filter Content" [Menu: Table > Advanced Filter Content :: SHIFT+CMD+F] ? 

In a row you can create "AND"-clauses and different rows create "OR"-clause. I use it all the day ;) [and you can copy the automatically generated WHERE-clause ;)]

Cheers, Hans

**Comment by pablomedok** [comment]
thanks, @Bibiko. I tried, but that's not quite what I'm talking about. Usually that happens after you've applied the first filter and need more. creating WHERE is not the most "lazy" part. Retyping SELECT * FROM x WHERE over and over could become easier.
