### ISSUE TITLE
export table

### ISSUE THREAD

**Issue by Patrikkbbc** [sequelpro/sequelpro#2305]
![screen shot 2015-10-22 at 12 48 18 pm](https://cloud.githubusercontent.com/assets/8640860/10662168/43643c24-78bb-11e5-952f-ea50219662a9.png)

When I export any table in the name of the exported file it does not have the name of the table but only the name of the database

**Comment by dmoagx** [comment]
Issue reproducible with 1.1

**Comment by dmoagx** [comment]
Duplicate of #1858
