### ISSUE TITLE
Use ~/.ssh/id_rsa for SSH tunel

### ISSUE THREAD

**Issue by Alvaroctal** [sequelpro/sequelpro#2308]
Hi, 

Today using MongoHub I saw it has de possibility of using the user rsa certificate instead of user/passwd in order to authenticate in a ssh tunel.

what do you think?

**Comment by dmoagx** [comment]
What do you mean?

Sequel Pro has supported SSH PubKey authentication for a few years now.
You don't even have to configure anything in Sequel Pro. Just leave the SSH password field empty.

**Comment by Alvaroctal** [comment]
OOOOOk, didn't noticed at all, thank you very much.

sorry for the post.
