### ISSUE TITLE
Error opening Key File message 

### ISSUE THREAD

**Issue by jcormir** [sequelpro/sequelpro#2309]
When attempting to use a private key file that was passphrase protected, Sequel Pro failed the connection with the error message:

MySQL said: SSL connection error: Unable to get private key

The error message undoubtedly comes from a MySQL framework / library call. An apt description of the private key file being password protected would be helpful in this situation, if it's even possible to detect a passphrase protected private key file.

I was able to get the connection working by removing the password with the following command:

openssl rsa -in client.key -out client-no-password.key

**Comment by dmoagx** [comment]
mysqls SSL support is rather terrible to work with, because it provides nearly no info at all.
yaSSL, the SSL library they use even provides support for passphrase protected key files via `SSL_CTX_set_default_passwd_cb` but libmysql (at least our version) makes no use of that, so we can't either.
