### ISSUE TITLE
Keyboard shortcuts: Triggers occupy the wrong spot

### ISSUE THREAD

**Issue by OlofT** [sequelpro/sequelpro#2311]
Cmd-4 should go to table-info but now goes to "Triggers" (which should have cmd-6)

And there are no way to modify shortcuts.

**Comment by dmoagx** [comment]
The order was changed in 1.1 to reflect the default order in the View menu and the toolbar. If it now looks wrong to you that means you have customized your toolbar.

And yes, the keyboard shortcuts can be changed. 
See #1310
