### ISSUE TITLE
Spreadsheet style table content view

### ISSUE THREAD

**Issue by mrballcb** [sequelpro/sequelpro#2313]
There are times that I'll start a long-running query (anything longer than 10 seconds) that prints several columns of data, such as "id, sum(size), email".  If I only want to copy the list of results from the id column, I have to adjust the SELECT portion to only show id, and rerun the whole query.  Then I select all and copy the entire set of results.  I'd like to be able to run just the first query, and select the entire id column, and copy it.  Then I can paste it into another query in a different tab running against a different database.  Currently, when you click on the column, it sorts it (very nice) but there is no way to right click and select the whole column (that I could find).

If this might already be something the nightlies can do, I'd be quite happy with that.

Environment: I'm running the standard release 1.1 on Mac OSX 10.11.1 (El Capitan) and I have no issues with lockups or ssh tunnels failing nor using RDS directly.  It all works properly for me with the standard release.

**Comment by dmoagx** [comment]
The problem is OS X' table view: It does not allow column or field selection. Only whole rows can be selected.

For anything like Excel or Numbers can do, we'd have to write our own table view from scratch – and that is arguably one of the most complicated UI controls in OS X.

**Comment by mrballcb** [comment]
Ok sounds good.  Closing the request since it's not supported by the framework.  Thank you for the speedy reply!

**Comment by abhibeckert** [comment]
We have received enough requests for this I'm re-opening it for **_potential_** inclusion in Sequel Pro 2.0. NSTableView is too primitive for our needs.

A better option is NSCollectionView which works similar to icon view in Finder, however it's not ideal either, we really need a hybrid between NSTableView and NSCollectionView.

I propose writing a custom view that behaves similar to the grid in a spreadsheet program. For a good example of how this would improve selection, export a table as CSV and open it in Numbers.app:

![screen shot 2016-03-02 at 08 06 32](https://cloud.githubusercontent.com/assets/266088/13443665/cf54bb10-e04d-11e5-872a-f521820e27e1.jpg)
![screen shot 2016-03-02 at 08 06 52](https://cloud.githubusercontent.com/assets/266088/13443679/dff792d0-e04d-11e5-96db-2e511fc0540e.jpg)
![screen shot 2016-03-02 at 08 07 04](https://cloud.githubusercontent.com/assets/266088/13443691/ee3ee370-e04d-11e5-9da5-d08eebeb13e5.jpg)

**Comment by abhibeckert** [comment]
The version 2.0 roadmap is maintained here: https://github.com/sequelpro/sequelpro/wiki/Release-2.0
