### ISSUE TITLE
Feature Request:  Automatically create a backup when deleting data.

### ISSUE THREAD

**Issue by davidsev** [sequelpro/sequelpro#2314]
It would be nice if there was an option so when I use the context menu to truncate or delete a table or delete some rows, Sequel Pro would automatically create an SQL dump and chuck it in a designated folder.

Could perhaps throw it straight into the trash with everything else I delete, to avoid issues with an ever growing folder.

**Comment by samuelbradshaw** [comment]
Perhaps this is where the [⌘-del] vs [del] distinction could come in:
https://github.com/sequelpro/sequelpro/issues/2333
