### ISSUE TITLE
Request: View table contents or structure while writing query

### ISSUE THREAD

**Issue by jreljac** [sequelpro/sequelpro#2326]
I would find it very useful to be able to have either a content view or structure view open for a specific table while writing a query.  I often will open a second Sequel Pro window to be able to look at structure while writing a query and it would be great to have it all in one.

(I'm not a fan of auto-complettion when writing queries but I do like to reference table structure, etc.)

A toolbar button that opens a new window set to the current server/database would be helpful if the above is not possible.

**Comment by dmoagx** [comment]
Have you tried "View" > "Show Navigator" ?

**Comment by jreljac** [comment]
No, I hadn't until now...I'm going to play around with that a bit.  Looks like that might really help.  Thanks for pointing it out.

**Comment by jreljac** [comment]
Looks like the Navigator gets me what I'm looking for.  Thanks again.
