### ISSUE TITLE
Add Copy/Paste functionality to one or multiple selected columns

### ISSUE THREAD

**Issue by phantasma2983** [sequelpro/sequelpro#2328]
Hey there,

I'm coming from HeidiSQL. It has a very useful functionality to select columns and copy them to clipboard. You can then paste them in any other table from any database. Is there any chance you can add this to Sequel Pro?

Thanks,
Daniel

**Comment by abhibeckert** [comment]
Thanks for the feedback, this is difficult due to limitations in NSTableView, but we might include it in version 2.0. See #2313
