### ISSUE TITLE
Slow queries under El Capitan

### ISSUE THREAD

**Issue by pflind** [sequelpro/sequelpro#2329]
I don't know if this is a bug in El Capitan or in Sequel Pro.

Queries run considerable slower under El Capitan than under any previous OS X version.

The behavior is somewhat strange. If you switch to another desktop the queries run at a normal, fast speed. When you switch back to the Sequel Pro desktop it instantly slows down again.

On erlier versions of Sequel Pro the same slowness happened when you opened the console window. But on El Capitan it makes no difference if the console window is opened or not, the queries seem to run at the same slow speed no matter if the console window is opened or closed. Enabling/disabling logging seems to make no difference either.

Tested on different 2 Macs with Sequel Pro 1.1 and 1.0.2.

**Comment by dmoagx** [comment]
And what do you mean by "considerable slower" in numbers?
How do you measure it?

**Comment by pflind** [comment]
My test query takes less than 10 seconds if I switch desktop and more than 1 minute if I don't switch desktop. Tested multiple times, same result each time.

I can't upload my test query but it contains about 50 tables and less than 10.000 rows.

One example:

DROP TABLE IF EXISTS countries;
CREATE TABLE countries (
  countries_id int NOT NULL auto_increment,
  countries_name varchar(64) NOT NULL,
  countries_localname varchar(64) NOT NULL,
  countries_iso_code_2 char(2) NOT NULL,
  countries_iso_code_3 char(3) NOT NULL,
  address_format_id int NOT NULL,
  country_visible int(1) DEFAULT '1' NOT NULL,
  PRIMARY KEY (countries_id),
  KEY IDX_COUNTRIES_NAME (countries_name)
);

INSERT INTO countries VALUES (1,'Afghanistan','Afghanestan','AF','AFG','1','0');
INSERT INTO countries VALUES (2,'Albania','Shqiperia','AL','ALB','1','0');
INSERT INTO countries VALUES (3,'Algeria','Al Jaza\'ir','DZ','DZA','1','0');
INSERT INTO countries VALUES (4,'American Samoa','American Samoa','AS','ASM','1','0');

**Comment by dmoagx** [comment]
Do you run that from "Import SQL" or from Query editor?

**Comment by pflind** [comment]
From the Query editor.

**Comment by dmoagx** [comment]
50 tables and 10.000 rows is still a lot more than what the Query editor was designed for.
You should use "Import" instead.

While the query is running, please go to Activity Monitor, select Sequel Pro, go to View > Sample process and post the results. Make sure to only sample the time where Sequel Pro is busy (i.e. if the query finishes before the sample, you need to redo it).

If you have Xcode installed, a sample using Instruments would be preferable.

**Comment by dmoagx** [comment]
No feedback from reporter for > 1 month, closing.
