### ISSUE TITLE
Option to Quickly Collapse Columns

### ISSUE THREAD

**Issue by Haravikk** [sequelpro/sequelpro#2330]
Basically I'd like the option to quickly collapse a column, either via a right-click contextual menu (which would be useful also because it could allow specific selection of ascending/descending order) and also a shortcut such as command + click.

A collapsed column would only be wide enough to display its name and no-more, repeating the action would restore it to whatever its previous width was.

Really I just find that when viewing contents I don't need to see most columns, but don't necessarily want to hide them, so being able to "collapse" the widest to make more room would be useful. Either that or hide them completely, though the latter would require some interface for re-enabling hidden columns.

**Comment by samuelbradshaw** [comment]
I think it'd be nice to shrink columns even smaller than their column name sometimes when they are rarely edited.

A contextual menu would be nice, but maybe an intermediate step would be double-clicking the line between columns – currently, it just expands the column to fit the longest item in the column, like Excel does. You could have it toggle between expanding to the longest item, collapsing to the column name, and fully collapsing.

**Comment by dmoagx** [comment]
An option to hide columns is something I've been wanting to implement for some time now – but, like anything with a codebase that large, it's not trivial :see_no_evil:

**Comment by nafmarcus** [comment]
With a table with many columns, the Table Content view becomes less and less useful because most of the data is off the screen.

**Comment by ls-chloe-schoreisz** [comment]
Any news on this ?
