### ISSUE TITLE
Export/Import Binary data invalid

### ISSUE THREAD

**Issue by beppert** [sequelpro/sequelpro#2337]
When exporting tables containing column type BIT(1) using "SQL" style content export from mysql-5.5.46 on ubuntu linux and re-importing to mysql-5.5.46 on Mac OS X (el capitan) the BIT columns are incorrect (when viewed using BIN(column_name)). File produced by mysqldump and piped to the mysql command line client work correctly.

**Comment by dmoagx** [comment]
Duplicate of #2254 / #2262 
Please search for existing issues before opening a new issue!

**Comment by beppert** [comment]
ah, sorry, did actually search but realize now the search keywords were not well chosen.
