### ISSUE TITLE
always edit in popup sheets toggle does nothing

### ISSUE THREAD

**Issue by heaversm** [sequelpro/sequelpro#2338]
clicking the icon for editing table rows in popup sheets toggles the icon between blue and gray, but does nothing in terms of actually preventing the popup from showing (popup always shows for me). Using Sequel Pro 1.1 on Mac OSX 10.9.5

**Comment by dmoagx** [comment]
The popup editor will always be used for TEXT and BLOB types.
For other types it works as expected for me.

**Comment by dmoagx** [comment]
Closing after no feedback from user.
