### ISSUE TITLE
SSH tunneling not working

### ISSUE THREAD

**Issue by webtoolbox** [sequelpro/sequelpro#2347]
Hi,

I saw that this was fixed in sequel pro 1.1. That is the version I am using. However, I'm still facing the issue. I'm using the latest version of OSX El Capitan and Sequel Pro 1.1. It works when I SSH tunnel in using Workbench, but does not work with sequel pro. When I try to connect, it says:

Unable to connect to host [omitted], or the request timed out.

Be sure that the address is correct and that you have the necessary privileges, or try increasing the connection timeout (currently 10 seconds).

MySQL said: Can't connect to MySQL server on '127.0.0.1' (4)

**Comment by dmoagx** [comment]
4 is a system interrupt eror code, but what I read from Google for MySQL it can mean network congestion.

Does the error occur immediately after connecting or after some time?
Have you tried increasing the connection timeout in Prefs > Network?

**Comment by webtoolbox** [comment]
I changed ISPs and it is working now. That's very odd that it worked with Workbench on the old ISP but didn't work with Sequel Pro. Well, it's working now so I'm going to close the issue. Thanks for your fast response!
