### ISSUE TITLE
Altering table often causes Sequel Pro to hang

### ISSUE THREAD

**Issue by samuelbradshaw** [sequelpro/sequelpro#2349]
If I change, for example, the name of a field in a table, or if I add a field to a table, Sequel Pro often goes into beach-ball mode. Occasionally it doesn't do anything for several minutes and has to be force-quit.

Currently I'm using the Nightly Build, but I've been having this problem for several months.

The main databases I connect to are over SSH, if that makes a difference.

Sometimes it seems to work better if I close all the connections, and open a new connection, choose a table I don't need to edit, switch there from Content to Structure (to keep from loading the content of the table I want to edit), then switch to the table I want to edit. But it doesn't always help.

**Comment by dmoagx** [comment]
ALTER statements are not threaded in Sequel Pro.
That means it will beachball as long as the mysql server takes to complete the operation (for which it often has to duplicate the whole table).

I guess that's what you are seeing.

**Comment by dmoagx** [comment]
Closing after no feedback from user.

**Comment by samuelbradshaw** [comment]
Thanks, sorry I didn't respond. Yes, I think that this is the threading issue (https://github.com/sequelpro/sequelpro/issues/710).
