### ISSUE TITLE
Disable "Relations" tab on non-InnoDB tables

### ISSUE THREAD

**Issue by samuelbradshaw** [sequelpro/sequelpro#2350]
Currently you can go to the "Relations" tab and it loads a view that says "This table currently does not support relations. [...]"
Instead, I would expect the relations button to be grayed out.

**Comment by dmoagx** [comment]
Even though Sequel Pro does not allow to add relations on MyISAM this is still technically possible and has been used by some Web 2.0 frameworks in the past - MySQL will just not enforce them.
So it still makes sense to have that view.
