### ISSUE TITLE
Refresh Tables shortcut doesn't do anything.

### ISSUE THREAD

**Issue by Arcrammer** [sequelpro/sequelpro#2355]
There's an option in the `Database` list that says `Refresh Tables`, but it doesn't do anything. Ideally the application could check for new tables silently in the background because they change often when working with migrations.

**Comment by dmoagx** [comment]
...and how did you conclude that it "doesn't do anything"?

**Comment by Arcrammer** [comment]
After selecting the option the tables in the sidebar stay the same, even when there are new ones and some have been dropped. There's actually a lot of missing functionality like this. I'm using OS X El Capitan. Should it be refreshing them?

**Comment by rowanbeentje** [comment]
Certainly should be - an import also triggers that command itself at the end.

Does a manual `SELECT * FROM information_schema.routines WHERE routine_schema = '{{Insert your database name here}}' ORDER BY routine_name;` give the correct list of tables?

**Comment by Arcrammer** [comment]
That yielded an empty set.

**Comment by rowanbeentje** [comment]
Is there a chance the MySQL server version has been updated without running the `mysql_upgrade` script?  That'll leave various MySQL internal states broken.

**Comment by Arcrammer** [comment]
Potentially. Would running `mysql_upgrade` repair it? I'll go ahead and try.

**Comment by rowanbeentje** [comment]
Yup - won't do any harm if it's already up-to-date; if it says it's upgraded things, also good to stop/start the server to fully apply the changes.

**Comment by Arcrammer** [comment]
Restarting didn't help, either.

**Comment by rowanbeentje** [comment]
Aargh.  Would help if I didn't share just the command for procedures and functions.  Try `SHOW /*!50002 FULL*/ TABLES;` as well (which is what sequel pro uses)

**Comment by Arcrammer** [comment]
Yes! My tables are there.

**Comment by rowanbeentje** [comment]
So that's correct after changes, but the table list isn't showing some of those?  Any pattern to what doesn't show or is it essentially a cache of the tables when first looking at the database?

**Comment by Arcrammer** [comment]
Umm... It's working now... * ahem * 😰

**Comment by rowanbeentje** [comment]
So potentially flaky, or potentially fixed by `mysql_upgrade` (which does cover all manner or weirdness if it changed anything, and I wonder if something clever could be done with table versions to see if a warning could be shown...)

Keep an eye out for recurrences.

**Comment by Arcrammer** [comment]
I will. Thanks for this!
