### ISSUE TITLE
feature request: Fill Down Support

### ISSUE THREAD

**Issue by curiouslybrown** [sequelpro/sequelpro#2360]
Hello,

Thank you for a great product. I have one feature request: the ability to have an excel like "Fill Down" feature. For my workflow it is pretty time-consuming to have to break out into excel then import back into sequel pro. I don't think Github has the ability to offer a bounty, but I will offer $100 if this is implemented. Thank you.

**Comment by dmoagx** [comment]
Sorry, I don't understand what you mean. Please be more specific in explaining what you need.

**Comment by dmoagx** [comment]
Closing after no feedback from user.
