### ISSUE TITLE
Trouble connecting to local server

### ISSUE THREAD

**Issue by thedivi** [sequelpro/sequelpro#2364]
I have read countless posts on how to connect to the local server. But nothing is working for me.

I had a SQLpro connection before I restarted my Mac. Now I can't connect. The SQL server is in fact running on my machine, so that's not a problem. 

I'm using 127.0.0.1 as the host and "root" as the username. I tried ALL my passwords, but none of them are working.

Can someone please help???

Thanks.

**Comment by huijing** [comment]
I have an issue connecting with localhost that did not use to happen before. I'm not sure if it's the same issue as yours though. Mine occurs after I click on the Connect button, then I get an error dialog from Sequel Pro saying an unexpected error occured.

        NSInvalidArgumentException

        *** -[NSPlaceholderString initWithString:]: nil argument

        (
            0   CoreFoundation                      0x00007fff8d8dcae2 __exceptionPreprocess + 178
            1   libobjc.A.dylib                     0x00007fff95e77f7e objc_exception_throw + 48
            2   CoreFoundation                      0x00007fff8d8dc98d +[NSException raise:format:] + 205
            3   Foundation                          0x00007fff81285d4a -[NSPlaceholderString initWithString:] + 96
            4   Sequel Pro                          0x000000010002e6a9 -[SPDatabaseDocument setConnection:] + 384
            5   Foundation                          0x00007fff812d5d4b __NSThreadPerformPerform + 279
            6   CoreFoundation                      0x00007fff8d7ec5c1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
            7   CoreFoundation                      0x00007fff8d7de41c __CFRunLoopDoSources0 + 556
            8   CoreFoundation                      0x00007fff8d7dd93f __CFRunLoopRun + 927
            9   CoreFoundation                      0x00007fff8d7dd338 CFRunLoopRunSpecific + 296
            10  HIToolbox                           0x00007fff865e6935 RunCurrentEventLoopInMode + 235
            11  HIToolbox                           0x00007fff865e676f ReceiveNextEventCommon + 432
            12  HIToolbox                           0x00007fff865e65af _BlockUntilNextEventMatchingListInModeWithFilter + 71
            13  AppKit                              0x00007fff944510ee _DPSNextEvent + 1067
            14  AppKit                              0x00007fff9481d943 -[NSApplication _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 454
            15  AppKit                              0x00007fff94446fc8 -[NSApplication run] + 682
            16  AppKit                              0x00007fff943c9520 NSApplicationMain + 1176
            17  Sequel Pro                          0x0000000100001994 start + 52
        )

**Comment by rowanbeentje** [comment]
@thedivi - are you're talking about SQL server and `SQLpro`, not MySQL and Sequel Pro?  SQLpro renamed themselves recently and unfortunately very close to our project name.  I suggest you contact http://www.hankinsoft.com/forum/viewforum.php?f=7 for support.

@huijing - it sounds like you're running into https://github.com/sequelpro/sequelpro/issues/2302 , short summary you may need to run `mysql_upgrade` if you recently updated your MySQL version.

**Comment by huijing** [comment]
@rowanbeentje OMG, thanks for that. Everything is good now. Sorry for hijacking the issue.
