### ISSUE TITLE
Update Nightly Build Icon to more closely match main icon

### ISSUE THREAD

**Issue by mattlangtree** [sequelpro/sequelpro#2372]
Per this comment by @rowanbeentje 
https://github.com/sequelpro/sequelpro/pull/2370#issuecomment-170188749 we should update the nightly build app icon to more closely match the main icon.

The build script that substitutes in the alternative icon will need to be updated to reflect the new icon.

I'm pretty happy with the design that Rowan has put together, but have created this ticket to see what the rest of the team think.

![af078db0-b6bd-11e5-8149-2430efd2fff5](https://cloud.githubusercontent.com/assets/771266/12225188/197a2ad0-b859-11e5-99bf-c8a433ec4743.png)

**Comment by avenjamin** [comment]
It may be a little subtle for some - but personally I like it berry much.

**Comment by abhibeckert** [comment]
I'm going to update the icon so the main one on github, and also nightlies, has no syrup. It's a bit boring and "not quite ready to eat" but a huge improvement over our current nightly.

Also removing our actual icon from github will make it clearer that any forks/etc should not be using our icon.

The main icon will be added to release builds only as part of the build process.
