### ISSUE TITLE
Remember filter between table switch in content view

### ISSUE THREAD

**Issue by zlobme** [sequelpro/sequelpro#2374]
Remember filter is missing through update from 1.0.2 to 1.1.0
Use case: need to view and/or edit related data in 2 or more tables

1 select table
2 apply filter
3 switch to another table
4 switch to previous table
5 result empty filter

**Comment by bronius** [comment]
For anyone who may think about reporting this as a new issue, say against Sequel Pro Nightly build for revision 97c1b85783, a simple restart of Sequel Pro did the trick for me. Cheers! 🥳
