### ISSUE TITLE
Sidebar has black background when tab is pulled out to new window

### ISSUE THREAD

**Issue by daviestar** [sequelpro/sequelpro#2382]
Hey,

When I open a new tab in Sequel Pro (1.1), then pull the tab out of the tabs list to create a new window, the new window sidebar background is black, making the table names hard to read:

![screenshot](http://i.imgur.com/F12XSgs.jpg)

I'm on OS X 10.11.2 (El Capitan).  

I thought it might be the new setting System Preferences > General > Use dark menu bar and Dock, but I tried turning it off and it doesn't appear to fix it (although I didn't try a restart with this setting off).

Cheers.

**Comment by dmoagx** [comment]
Duplicate of #2286
