### ISSUE TITLE
Refreshing a table submits changes not yet committed.

### ISSUE THREAD

**Issue by jdwuzhere** [sequelpro/sequelpro#2383]
When you directly edited a field in a row and decided to cancel all the changes by presssing CMD-R your changes are first committed to table and only than refresh occurs.

**Comment by jdwuzhere** [comment]
Sequel Pro 1.1 (4499)

**Comment by dmoagx** [comment]
Well, that's how it is designed to work.
Reloading a table ends all pending edits and by ending them, they will be saved.
Pressing `esc` will cancel the edit.

Do you have any OS X system app or Apple HIG document that says different?
