### ISSUE TITLE
[REQ] Control contents of Query Editor using the URL scheme

### ISSUE THREAD

**Issue by camilopayan** [sequelpro/sequelpro#2386]
Would it be possible to send a query into Sequel Pro and have it show up as the query in the editor, with the results in that view?

I've been experimenting with the `sequelpro://` URLs (and frankly, haven't gotten them working, I never get anything in `SP_QUERY_RESULT_STATUS_FILE`) and I'm trying to find away to control Sequel Pro's Query view from outside Sequel Pro.

Some other Sequel Pro URLs do change what shows in the Sequel Pro UI, like SelectDatabase will go ahead and change the db and table (if specified)

The end goal for me is to be able to edit a query in my editor of choice or be able to copy and send a query from my codebase without needing to copy/paste over to Sequel Pro.

**Comment by dmoagx** [comment]
If you wanted to control Sequel Pro from another app then the way to go would be via AppleScript.
URL commands are only designed to be used by bundles which are executed from within Sequel Pro.

That being said, I don't think what you are asking for is available via AppleScript either currently.
