### ISSUE TITLE
[REQ] Ability to copy SQL Alter statement to clipboard

### ISSUE THREAD

**Issue by phcorp** [sequelpro/sequelpro#2387]
Hi @sequelpro !

I am just in love with the choice that appears when right clicking on a result row: `Copy SQL INSERT command`.

Could you extend this feature:
- in the table "Structure" pane that would make: `Copy SQL ALTER syntax`
- ~~in the table list in the sidebar that would make : `Copy SQL INSERT syntax`~~

Love & chocolate

**Comment by dmoagx** [comment]
What would be the difference to the "Copy CREATE syntax" context-option that already is in the sidebar?

**Comment by phcorp** [comment]
Sorry that's what I meant.
I didn't notice it already existed: when I do a right click in the sidebar on a table name, which is not active, the choice is disabled. I have to do a left click first for this choice to be enabled.
So my feature request concerns only the structure pane : ```Copy SQL ALTER syntax``` :smiley:
