### ISSUE TITLE
Error Thrown on Timestamp Default Value

### ISSUE THREAD

**Issue by 19peaches** [sequelpro/sequelpro#2391]
I have two columns for timestamps `created_at` and `updated_at` with default values of `0000-00-00 00:00:00`

Anytime I try to make changes to a table I get an error that my default values are invalid:
```
An error occurred when trying to change the field 'created_at' via

ALTER TABLE `ocx_offers` CHANGE `created_at` `created_at` TIMESTAMP
 NULL
 DEFAULT '0000-00-00 00:00:00'

MySQL said: Invalid default value for 'created_at'
```

![screen shot 2016-01-30 at 10 04 25 pm](https://cloud.githubusercontent.com/assets/1456472/12700394/e5601422-c79d-11e5-86e5-945fae322577.png)

I never had this issue prior to upgrading to 1.1.0.1 Build 4500 (2d9145d)

**Comment by dmoagx** [comment]
Nope, this is a change introduced with MySQL 5.7 (or 5.6) and unrelated to Sequel Pro.
See http://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_allow_invalid_dates to disable it or remove the "0000-00-00 00:00:00", since it is an invalid date.

**Comment by kelvinkuiper** [comment]
There is no way to change the default value because on save it will get the same error..
