### ISSUE TITLE
Cannot see any of the content

### ISSUE THREAD

**Issue by thepwnerer** [sequelpro/sequelpro#2394]
Pretty straight forward...content tab turns into this what is shown below whenever any table is selected. Connection and number of records are being shown...so what do?

I installed the update. I'm an idiot. I will never do this again. I thought updates were supposed to fix things :(. I'm running Mavericks 10.9.5 OSX. 
![screen shot 2016-02-05 at 1 02 34 pm](https://cloud.githubusercontent.com/assets/8645417/12857707/da0f05d2-cc08-11e5-9992-a5d79ec92fff.png)

**Comment by dmoagx** [comment]
Sometimes the update process can fail to replace all files correctly.
Just delete the app and reinstall the full version from http://www.sequelpro.com/download

**Comment by dmoagx** [comment]
Closing after no feedback from user.
