### ISSUE TITLE
"Double-click to insert new row" causes inadvertent inserts, cannot be disabled

### ISSUE THREAD

**Issue by willcodeforfood** [sequelpro/sequelpro#2401]
Please forgive me if I am just not finding the way to disable this feature, but I would very much like to. If I could just disable this feature entirely, I would be happy. I'm perfectly content with having to right-click and click "Add New Row" to insert.
## How to reproduce

Browse a table without any NOTNULL constraints, using the "Content" tab.
Double-click the white area. This lets you type in values for the new insert.
Left click anywhere in the blank area, without typing anything.
## What happens

Left clicking will send the INSERT query to the server, inserting a new row with all default values. This can break an entire website/app.
## What should happen

If you have not changed any of the values in any of the inputs, the left-click should behave just like pressing Escape (hiding the inputs, and NOT inserting anything.) An easier option might be to just let users disable this double-click-to-insert feature.
## Using filters makes this issue much worse
1. If you had a filter applied, there are less rows visible, and therefore the likelihood of accidentally double-clicking in the blank area is increased.
2. After the un-intended INSERT, an auto-refresh occurs, so you don't actually see or notice that you just inserted a new row with all NULL/DEFAULT values. This can cause said website/app to remain broken for some minutes or hours while developers scramble to understand the cause.

**Comment by tarky17** [comment]
As this problem actually occurred in my local development environment, I would also like you to improve this issue.
I think that the problem will be solved if it becomes possible to change the behavior of double click in setting.

For example, in the option of check box "Insert record with double click".
* checked: The same behavior as now
* unchecked: do nothing
