### ISSUE TITLE
Cursor can move outside of selection in case of query runtime error

### ISSUE THREAD

**Issue by yanncoupin** [sequelpro/sequelpro#2410]
Take a query that contains repeating parts, for instance:

``` sql
select field_a from table_a
union
select field_a from table_b
```

Select second part of the union to use the "execute selection" mode. If that selection contains an error (e.g. table_b doesn't contain field_a), then the selection is changed and replaced by the first occurrence of the `field_a` text that lies outside the manual selection. That first occurrence wasn't part of the query, so the search should start after the beginning of the selection at the time of the query.

That's in the latest nightly.

**Comment by dmoagx** [comment]
Related to: #1152, #1653

**Comment by yanncoupin** [comment]
I guess I didn't use the correct terms for my search of related / duplicates. Yet it's not completely the same but commenting one of those should have been enough. Feel free to close as duplicate.
