### ISSUE TITLE
Sync favorites over dropbox or any other cloud 

### ISSUE THREAD

**Issue by lordton** [sequelpro/sequelpro#2411]
Hey guys!
Is there any was to sync my favorites between 4-5 machines?
I have 50-60 bookmarks, that change passwords often.

**Comment by sequelpro** [comment]
Favourites and passwords are stored in separate databases, so need to be treated individually.

For favourites, the only officially supported method is to export and import favourites manually using the Gear menu on the favourites screen.

You could try a symbolic link in `~/Library/Application Support/Sequel Pro` to dropbox... I'm not sure how well this will work in practice, but it's worth a try (make sure you have backups).

For passwords, these are stored in Keychain Access. I'm not aware of any good way to sync that – your best option is to use 1Password or similar – although this won't be quite as efficient as keychain access.

We do plan to improve this in future, keep an eye on issue #1843.
