### ISSUE TITLE
History larger than 99

### ISSUE THREAD

**Issue by balsagoth** [sequelpro/sequelpro#2415]
Why isn't possible to set a larger number? Any technical limitations? 
Should also write to a log file.

**Comment by rowanbeentje** [comment]
At the moment the history is in the normal preferences .plist, which isn't designed for a lot of a data (a large query in your history can already cause lots of performance problems as plists get read and written a lot...).

To increase the limit the history ideally needs to be split out to an external file/files with smarter handling of very large queries.

**Comment by balsagoth** [comment]
Ok, thanks.

**Comment by abhibeckert** [comment]
One #687 is closed, we'll do this too.
