### ISSUE TITLE
File read error on certain databases exported via SSH and MySQLDump

### ISSUE THREAD

**Issue by tr33m4n** [sequelpro/sequelpro#2419]
Hi there,

Been experiencing an issue when a database has been exported over SSH to stdout, eg:

`something@somewhere 'mysqldump -u user -p database' > local.sql`

When importing the database into Sequel Pro, the following error is received at certain table rows:

File Read Error
An error occurred when reading the file, as it could not be read in the encoding you selected (Autodetect - Unicode (UTF-8)).

Only 263 queries were executed.

Just wondering whether you know if this might be an issue with how the database is exported/issues server side or whether it might be a Sequel Pro issue?

Cheers,

**Comment by dmoagx** [comment]
Well, if SP says it could not read the file as UTF8 then there is a high chance the file is not UTF8 and you have to actually pick the correct encoding.

**Comment by tr33m4n** [comment]
We tried forcing the encoding with MySQL dump, but this did not fix the
issue. As far as I'm aware the databases we're importing are all utf8 and
do not change on any tables. They all pass mysqls sanity checks... Curious

**Comment by rowanbeentje** [comment]
@tr33m4n Try opening the files in a text editor as UTF8 and take a look at the queries for those certain table rows.  Typically doing a `mysqldump > foo.sql` can screw up encodings - see http://makandracards.com/makandra/595-dumping-and-importing-from-to-mysql-in-an-utf-8-safe-way but also pay attention to the encoding setting on the server you're exporting from...

**Comment by abhibeckert** [comment]
If rowan's suggestions don't fix it, try the `--tables tablename` option to only export one table at a time until you find the one with bad data, then use a text editor to delete rows from the dump until you can find the one with bad data.

**Comment by dmoagx** [comment]
Closing after no feedback from user.
