### ISSUE TITLE
Saved Query missing characters

### ISSUE THREAD

**Issue by billynoah** [sequelpro/sequelpro#2420]
I use a query like this to update passwords on my mailserver:

```
UPDATE virtual_users
SET `password` = ENCRYPT('n00bezBeware', CONCAT("$6$", SUBSTRING(SHA(RAND()), -16))) 
WHERE email = 'johndoe@example.com';
```

I can save the query and verify that it does save correctly, but for some reason when I load the query from Query Favorites it's missing the `6$` from the `CONCAT()` function and loads like this:

```
UPDATE virtual_users
SET `password` = ENCRYPT('n00bezBeware', CONCAT("$", SUBSTRING(SHA(RAND()), -16))) 
WHERE email = 'johndoe@example.com';
```

**Comment by dmoagx** [comment]
`$6` is interpreted as placeholder 6 by Sequel Pro.
Edit the favorite and change it to `\$6`.

Though, this should probably automatically happen when saving a query as favorite.

**Comment by billynoah** [comment]
Thanks that works.  Would be nice to see this patched in an upcoming release.

**Comment by abhibeckert** [comment]
On a side note... you should not be using `encrypt()` for password storage.

**Comment by billynoah** [comment]
Thanks @abhibeckert. Let's continue this discussion via email.
