### ISSUE TITLE
Is there a reason autocommit=0 does not work?

### ISSUE THREAD

**Issue by gajus** [sequelpro/sequelpro#2421]
I am using Sequel Pro to run the following queries:

```sql
SET autocommit = 0;
START TRANSACTION;
SET @country_id = (SELECT `id` FROM `country` WHERE `code` = 'de');
INSERT INTO `cinema` SET `country_id` = @country_id, `country` = 'de', `nid` = 'yorck1';
```

which should do nothing because I never `COMMIT`. However, the row is inserted to the table.

**Comment by abhibeckert** [comment]
Unless you roll back the transaction, all queries within the connection will see the row that hasn't been committed yet.

So even without committing, switching to Sequel Pro's browse pane will show the new row. To test this, try making a second connection to the same server in Sequel Pro. That connection will not show the un-committed insert.

Also note that MyISAM tables don't fully support transactions, so the insert is committed immediately.

**Comment by gajus** [comment]
> So even without committing, switching to Sequel Pro's browse pane will show the new row. To test this, try making a second connection to the same server in Sequel Pro. That connection will not show the un-committed insert.

I did try opening a new connection and I can confirm that the row is getting inserted without committing the transaction.

I am using READ-COMMITTED isolation.

**Comment by abhibeckert** [comment]
Can you provide some more details how to reproduce it?

I tested on my system and transactions are not auto-committed.

**Comment by gajus** [comment]
It is 6AM. Need to grab some sleep. Will try later today.

**Comment by gajus** [comment]
I cannot replicate the bug. Must have been a case of sleep deprivation.

**Comment by SteveByerly** [comment]
@gajus @abhibeckert i can see the same behavior, with slightly different setup.

When connected to a server with `autocomit=0` and running queries I can:
1. see changes in the `Content` pane of my current tab
2. see changes in a new tab of the same connection window
3. see changes in a new connection window

After closing all connection tabs for this server, then opening a new one, the data is no longer visible.

I would have assumed the new tab/window would not show this new data, but it must be using the same connection?

**Comment by dmoagx** [comment]
What you describe sounds like you are using an improper transaction isolation level. See: https://dev.mysql.com/doc/refman/5.7/en/innodb-transaction-isolation-levels.html
