### ISSUE TITLE
'Fields terminated by' forgets last used value

### ISSUE THREAD

**Issue by melino** [sequelpro/sequelpro#2424]
Some minor but annoying thing:

When importing a CSV file, the selector “Fields terminated by” on the first dialog page where you select the file does not store the selection, e.g. semicolon.
While e.g. the “Encoding” input choice is stored and recalled (e.g. “Western (ISO Latin 1)”) when importing another CSV, the terminator is always reset to the first value of the selection, so colon.

It would be a huge help for me if that could be “fixed”.

**Comment by stuconnolly** [comment]
This technically isn't a bug, but more of an annoyance if you're importing delimited files with an extension of either .csv of .tsv which actually use something other than a comma or tab to delimit the fields. 

Sequel Pro will save whatever is input and will restore on subsequent use of the import dialog, but selecting a .csv or .tsv file will cause the setting to be updated to match.

**Comment by melino** [comment]
Alright, thanks for the notice, two an a half years later. :-)
