### ISSUE TITLE
[Security Bug] User Passwords were reseted to 'no password'

### ISSUE THREAD

**Issue by stefanbauer** [sequelpro/sequelpro#2426]
I had a very strange behaviour: I set some new passwords, for some users. Everything fine. And after some minutes/seconds the passwords were gone. Gone means: Empty. I thought.. WHAT? It took me a lot of time to find out what the problem is. And at least i find out, that Sequel is the problem. See also attached screenshot. To test it, i used another tool and set passwords for different users. Everything was working. I used Sequel to connect and checked the mysql.user table. Everything fine.. I played little bit around.. still everything fine. BUT: As soon you open the user (GUI) tab, as you can see in my console log. Sequel fires 4 queries to set for this users the password to nothing. This is a high security bug in my eyes. Can you fix that? If you need any more information, please let me know.

OS X El Capitan,
Sequel Pro Nightly 4667 

<img width="989" alt="screenshot 2016-02-28 12 25 20" src="https://cloud.githubusercontent.com/assets/3192662/13378916/58e5e7b2-de16-11e5-8824-a6961817f236.png">

**Comment by dmoagx** [comment]
This is a duplicate of #2418
