### ISSUE TITLE
App locks on reconnect

### ISSUE THREAD

**Issue by midlettuce** [sequelpro/sequelpro#2428]
When the app loses connection (i often use mysql over ssh), reconnect locks the app.

It's especially frustrating when i'm working on a local DB, and a background tab loses connection. The entire app locks.

Surely this can happen in background?

**Comment by abhibeckert** [comment]
Can you provide steps so we can reproduce this situation?

**Comment by dmoagx** [comment]
Closing after no feedback from user for over 1 month.
