### ISSUE TITLE
Add options to select and copy data from a single column of results in various formats

### ISSUE THREAD

**Issue by ozzyogkush** [sequelpro/sequelpro#2429]
When you return a query with multiple columns, sometimes you need to simply copy and paste values from a single column. Frequently, the format can change based on need - sometimes you just need the values line separated, sometimes the values need to be in quotes with commas (ie for an array).

It would be great if there were a built in option for being able to select a single column from results and copy its contents, and let the user select a format from a list. Can be as simple as right-click a column header and it pops up the options.

**Comment by abhibeckert** [comment]
Thanks for the feedback, this is difficult due to limitations in NSTableView, but we might include it in version 2.0. See #2313
