### ISSUE TITLE
ENUM datatype - can't select from dropdown

### ISSUE THREAD

**Issue by MateuszKoguc** [sequelpro/sequelpro#2430]
Hi guys,
I am using newest Sequel pro 1.1.1 (build 4529) on my el capitan 10.11.3.
In database I have a field of ENUM type, where I am able to select from dropdown predefined values. But always, when I click on any options, it opens popup window where I need to put value manually.
Please have a look on screenshots.
Cheers

1)
<img width="396" alt="1" src="https://cloud.githubusercontent.com/assets/7289778/13492879/8071c354-e132-11e5-8d8d-90132b5cd32f.png">

2)
![2](https://cloud.githubusercontent.com/assets/7289778/13492972/057204b0-e133-11e5-8ba0-5391d407af85.jpg)

3)
<img width="560" alt="3" src="https://cloud.githubusercontent.com/assets/7289778/13492878/807083b8-e132-11e5-8071-4c37c2a24464.png">

**Comment by chn42** [comment]
You see the checkbox "Edit All Fields in Pop-up Sheet" in your third screenshot? It's not a default setting.

**Comment by MateuszKoguc** [comment]
Thanks @chn42 

It works, but could be more intuitive for example: single click would select from dropdown, and double click would open popup...
