### ISSUE TITLE
Table structure popup menus have no shadow

### ISSUE THREAD

**Issue by abhibeckert** [sequelpro/sequelpro#2435]
On Sequel Pro `1.1.1`, `1.1.2 RC 2` and the latest nightly the table structure pop up has no drop shadow:

![screen shot 2016-03-05 at 07 15 05](https://cloud.githubusercontent.com/assets/266088/13540428/24d3e9f2-e2a2-11e5-8961-adb402681a42.jpg)

However when I do a build on my Mac, I cannot reproduce the bug.

**Comment by dmoagx** [comment]
This seems to only happen when building against 10.8 SDK
