### ISSUE TITLE
Bundle Editor Color Scheme

### ISSUE THREAD

**Issue by mikezahno** [sequelpro/sequelpro#2440]
It would be nice if the bundle editor could use the query editor color scheme.

**Comment by dmoagx** [comment]
We implemented a lexer for SQL to support syntax highlighting in some views.

However the Bundle Editor can use any scripting language available and is a rather auxiliary feature.
There is no chance we could implement lexers for all the other languages out there.
So with the current architecture I see no way to make this happen.

This would only make sense if we could find some lightweight, reusable, open source text editor component that already has support for syntax highlighting and a variety of languages.
