### ISSUE TITLE
docs on creating custom Content Filters?

### ISSUE THREAD

**Issue by jm3** [sequelpro/sequelpro#2441]
Are there docs online that show the syntax for making custom Content Filters? I mostly figured it out via trial and error, but it would be nice to read the docs.

**Comment by rowanbeentje** [comment]
Hmm.  These used to live at http://www.sequelpro.com/docs/Content_Filters but they seem to have disappeared...

**Comment by abhibeckert** [comment]
I can't find the page anywhere either, will ask around maybe someone else has a backup older than mine.

In the mean time, this is the full list of built in filters if that's any help: https://gist.github.com/abhibeckert/b28dc08e58ef17901efd

**Comment by jm3** [comment]
bump.
