### ISSUE TITLE
[REQ] Database overview with tables statistics

### ISSUE THREAD

**Issue by iBobik** [sequelpro/sequelpro#2447]
phpMyAdmin has nice page where we can get quick overview of storage consumption per table:
![snimek obrazovky 2016-03-16 v 12 56 47](https://cloud.githubusercontent.com/assets/614232/13811541/ba4c4416-eb76-11e5-8c98-5d555166b4f1.PNG)
Could you add table like this? (With rows, type, size and basic operations.)

**Comment by Bibiko** [comment]
> On 16 Mar 2016, at 13:01, Jan Pobořil <notifications@github.com> wrote:
> 
> phpMyAdmin has nice page where we can get quick overview of storage consumption per table:
> 
> Could you add table like this? (With rows, type, size and basic operations.)

Hi,

you can find a basic report under "Bundles" > "Report" > "Database Report". Since it's a bundle command which can be modified by the user you can enhance it ;)

Cheers, Hans

**Comment by iBobik** [comment]
Thanks, very well hidden :-)

So suggestion is only to make this overview at hand (e.g. like phpMyAdmin
has it top of tables list sidebar).

Also UX of bundle editor should be better. I am coder and I did not found
way how to edit this report.



Jan Pobořil

2016-03-16 13:40 GMT+01:00 Hans-Jörg Bibiko <notifications@github.com>:

>

**Comment by Bibiko** [comment]
> On 16 Mar 2016, at 17:07, Jan Pobořil <notifications@github.com> wrote:
> 
> Also UX of bundle editor should be better. I am coder and I did not found
> way how to edit this report.

"Bundles" > "Bundle Editor" > "General" > "Report" > "DB Report"

It's written in Bash ;) 

-H

**Comment by abhibeckert** [comment]
> So suggestion is only to make this overview at hand (e.g. like phpMyAdmin
has it top of tables list sidebar).

Good idea, I just created #2448 for that.
