### ISSUE TITLE
Add option to remove definer from SQL exports

### ISSUE THREAD

**Issue by FaimMedia** [sequelpro/sequelpro#2449]
When exporting a database structure, the definer is included in create trigger query.
The real problem exists when importing this file on an other system and you insert/update a row with the trigger, the user account in the definer doesn't exists and you get an error that doesn't lead directly back to the trigger.

Sure, I could manually replace this everytime I export a database or table, but why is this included in the first place?

```
DELIMITER ;;
/*!50003 CREATE */ /*!50017 DEFINER=`faimmedia`@`localhost` */ /*!50003 TRIGGER `package_before_insert` BEFORE INSERT ON `package` FOR EACH ROW BEGIN

SET NEW.created_on = NOW();

END */;;
DELIMITER ;
```

Could this please be removed from the export or added as an export option?

**Comment by dmoagx** [comment]
>  but why is this included in the first place?

Because that is how MySQL returns the create statement.

**Comment by MacGritsch** [comment]
Hi,

that would be a great enhancement - also for stored functions and procedures.

There is also a "--skip-definer" parameter in mysqldump version 5.7: https://dev.mysql.com/doc/refman/5.7/en/mysqlpump.html#option_mysqlpump_skip-definer

Thank you very much for all that great work!

**Comment by MacGritsch** [comment]
Hi @sequelpro, @dmoagx

could something like that be added (so its a hidden pref):

```
--- sequelpro-master/ORIG/Source/SPSQLExporter.m	2018-03-20 18:13:56.000000000 +0100
+++ sequelpro-master/PATCHED/Source/SPSQLExporter.m	2018-03-31 14:41:16.000000000 +0200
@@ -745,7 +745,15 @@
 				// END */;;
 				//
 				// Build the CREATE PROCEDURE string to include MySQL Version limiters
-				[metaString appendFormat:@"/*!50003 CREATE*/ /*!50020 DEFINER=%@*/ /*!50003 %@ */;;\n\n/*!50003 SET SESSION SQL_MODE=@OLD_SQL_MODE */;;\n", escapedDefiner, procedureBody];
+				
+				if ([[NSUserDefaults standardUserDefaults] boolForKey:@"HIDDEN_PREF_SKIP_DEFINER_ON_SQL_DUMP"])
+				{
+					[metaString appendFormat:@"/*!50003 CREATE %@ */;;\n\n/*!50003 SET SESSION SQL_MODE=@OLD_SQL_MODE */;;\n", procedureBody];
+				}
+				else
+				{
+					[metaString appendFormat:@"/*!50003 CREATE*/ /*!50020 DEFINER=%@*/ /*!50003 %@ */;;\n\n/*!50003 SET SESSION SQL_MODE=@OLD_SQL_MODE */;;\n", escapedDefiner, procedureBody];
+				}
 				
 				[procedureInfo release];
 				[proceduresList release];
```

Or should it be added as an advanced option in the export window?
If you want, I can fork, patch and create a PR.

thank you for that great application!

**Comment by bardiir** [comment]
@MacGritsch I'd say a hidden preference would already be a great addition. Currently I have to manually do a text search and replace between exporting and importing to remove the definers otherwise the target database won't accept the import. It's still easier than using mysqldump manually but it's still quite unnecessary in my opinion.
