### ISSUE TITLE
404 on website

### ISSUE THREAD

**Issue by henricavalcante** [sequelpro/sequelpro#2450]
I dont know if here is the better place to report this bug but the link http://www.sequelpro.com/download is showing a 404 error.
![screen shot 2016-03-17 at 7 14 28 pm](https://cloud.githubusercontent.com/assets/2352034/13862878/c7cb64b0-ec74-11e5-810f-df0c946b2e5c.png)

**Comment by YesThatAllen** [comment]
The URL is working for me at this time.

**Comment by jgacuca567** [comment]
@henricavalcante please try again the page is now working.

**Comment by abhibeckert** [comment]
Our server does this occasionally, we're aware of it and working on a fix.

**Comment by henricavalcante** [comment]
What if you change 404 message to something like:

" Woops, that page is missing.

If you're trying to download a sequelpro please visit https://github.com/sequelpro/sequelpro/releases/latest to download latest release. "

It's just an idea. ;)
