### ISSUE TITLE
Query History saved by DB

### ISSUE THREAD

**Issue by kf6spf** [sequelpro/sequelpro#2456]
It would be very appreciated if the Query tab "Query History" pulldown could save based on the current database you're using.

I work with lots of DBs and have to search through a lot of queries to find the ones I was working on for the particular DB I'm on at the moment.

**Comment by MrAnderson7** [comment]
I would also like to delete an individual entry in the history with something like
right-click -> delete or press the key-board delete key.  I often create uses and would like to clear the create with the password line.

Where is the history stored?
