### ISSUE TITLE
[REQ] Fuzzy matching on table name search/filter

### ISSUE THREAD

**Issue by flynniec6** [sequelpro/sequelpro#2459]
### Table Filter

For the table name filter, it would be great to be able to use fuzzy matching with spaces. Right now I have tables with underscores, I'd like to be able to type "switch port" and match on "switch_port, switch_port_type", etc.

**Comment by dmoagx** [comment]
The table filter has regex matching.

**Comment by flynniec6** [comment]
Thanks, that will tide me over!
