### ISSUE TITLE
Off-topic: PayPal donation doesn't work

### ISSUE THREAD

**Issue by ricardo-lewis** [sequelpro/sequelpro#2461]
I'm posting this here because [this page](http://www.sequelpro.com/docs/Contact_the_developers) doesn't work.

I've tried donating via PayPal twice this morning and both times PayPal returns an ambiguous error stating that the last action couldn't be completed.

I used the "non-login" option with a corporate credit card in an attempt to donate.

Can someone on the team check with PayPal regarding this?

**Comment by abhibeckert** [comment]
Thanks we're looking into it.

**Comment by ricardo-lewis** [comment]
Contact Page is working now, I'll try contacting the developers via email.

**Comment by abhibeckert** [comment]
@ricardo-lewis I am one of the developers, is the paypal page still not working for you?

**Comment by ricardo-lewis** [comment]
It works now, thanks!

**Comment by abhibeckert** [comment]
Thanks for letting us know
