### ISSUE TITLE
Don't break on changed SSH signature

### ISSUE THREAD

**Issue by Firesphere** [sequelpro/sequelpro#2464]
Especially when using Vagrant boxes (or Docker, or whatever), connection to the box is denied because the host key changed.
I understand that the host key change is not a good sign, but I would prefer to get the option saying something like "yes, I know, continue anyway". (Like IntelliJ is doing)

**Comment by dmoagx** [comment]
Sequel Pro uses the system's SSH client and if that rejects the host key there is nothing we can do.

If you want to disable host key checking you'll have to reconfigure your SSH client. E.g. see this guide: http://www.shellhacks.com/en/HowTo-Disable-SSH-Host-Key-Checking
