### ISSUE TITLE
Show Execution Time in the Console

### ISSUE THREAD

**Issue by nthdesign** [sequelpro/sequelpro#2465]
When viewing the list of previously executed statements in the console, it would be very helpful to see the execution time (duration) for each statement.

**Comment by dstuecken** [comment]
I like this one. Would you accept a PR?

**Comment by dmoagx** [comment]
Yes, in general.
Just try to match our code style and when changing xib files remove all unnecessary changes.

Also see the discussion in #264 - those times are not too helpful right now.
