### ISSUE TITLE
Option for using sudo

### ISSUE THREAD

**Issue by Fudge0952** [sequelpro/sequelpro#2466]
In our development team in order to access mysql on our server we ssh into the box and then have to `sudo mysql` to get into the database. No password is required but could be an option too?

Thoughts?

**Comment by dmoagx** [comment]
Well, would your PHP/Rails/Django/whatever application be able to connect via `sudo mysql`?

**Comment by Fudge0952** [comment]
The production server does not use my specific user login credentials. It used an access control list with our accounts to allow us access via sudo but disallow regular logins

**Comment by abhibeckert** [comment]
I think your server has a `.my.conf` file containing the MySQL username/password as cleartext, correct?

I suppose we could read that file over SSH instead of requiring the user do it, but I'm not sure how many people use this setup?

**Comment by dmoagx** [comment]
It seems my little hint above didn't get across.

So, no, Sequel Pro cannot be used unless you can open a TCP channel between your Mac and the MySQL server.
`sudo mysql` is a "display" channel.
