### ISSUE TITLE
Use [up] [down] button to select table when typing in table filterbox

### ISSUE THREAD

**Issue by odejonge** [sequelpro/sequelpro#2468]
I love to use your tool. But I constantly find myself, when typing a table name in the filterbox (top left), trying to open the tables presented to me in the list by using the [down] button and then press [enter]. But that doesn't work. I would really like to have that feature! Could you take this in consideration. Thanks!

**Comment by dmoagx** [comment]
I've added this on master, but there is still a bug: The table content view filter input will steal the focus when table content view is selected. This will be more complex to fix, though.

**Comment by dmoagx** [comment]
We even have code in `-[SPTableContent setTableDetails:]` to prevent the stealing, but that doesn't work.
When we read out the `currentFirstResponder` we get an `NSTextView *` which is shared among those search fields, so the `makeFirstResponder:` later does nothing. We have to call that with the parent `NSSearchField *`.

**Comment by dmoagx** [comment]
Ok, that should fix the focus stealing.
It's not exactly what I wanted, but should be good enough.

**Comment by abhibeckert** [comment]
If you try to go down a multiple tables quickly, sometimes you get error messages. I saw multiple errors, but one example was:

![screen shot 2016-04-18 at 07 51 10](https://cloud.githubusercontent.com/assets/266088/14590304/590baa06-053a-11e6-9f87-62ad38fb77ae.jpg)

**Comment by odejonge** [comment]
You now have a dynamic list under the textinput control that is responding and posting a query when you scroll with the down key through the dynamic list. Would a solution with a dynamic _popup_ list where you can scroll through not a better idea, as it would have by it's nature focus and would only trigger the call after you select it with the down key and press enter afterwards?
![screenshot_19-04-16_13_55](https://cloud.githubusercontent.com/assets/1083086/14638256/d89677d6-0636-11e6-8c2c-e68fba9de969.png)

**Comment by abhibeckert** [comment]
@odejonge better to have a separate feature altogether for navigating tables in addition to the filter.

We're close to a new release and adding up/down arrows is easy, so it will be included, but a pop up has to wait for a future release. Can you post a new issue? Or perhaps as a comment to #2459 which is related.

**Comment by odejonge** [comment]
OK, I was just thinking it would make your life easier, since you get those errors scrolling up and down quickly. But happy to hear that you will include the up/down arrow solution in the upcoming release!

**Comment by abhibeckert** [comment]
> If you try to go down a multiple tables quickly, sometimes you get error messages.

This problem is hard to fix and doesn't happen if the database is fast, so we can afford to wait until it's fixed in planned under the hood changes for version 2.0.
