### ISSUE TITLE
Password prompt in separate window causes all windows to lock up

### ISSUE THREAD

**Issue by pdubya1234** [sequelpro/sequelpro#2469]
I have this happen at least once every day or two due to usually having 3 or 4 separate windowed sessions open to different servers. If an inactive window has a password prompt active (I'm guessing due to a timeout?), if I run a query in a completely separate window, it forces the password prompt window to the foreground and locks up all other windows with a beachball cursor. The password prompt has a blinking cursor but I'm unable to type, and all app windows stop responding to clicks. The only way to fix is to force quit which closes all sessions.

Oddly enough, this only happens when running queries in the query pane. I can open tables and manually edit in the gridview and it doesn't happen. It's only when running queries.

This seems to happen regardless if the window is behind the active window or minimized. If the window is minimized, it will activate and come to the forefront, but is still unresponsive. This happens on completely separate hardware that happen to use similar connection setups with the same machine. If it helps at all, the password prompt session is using an SSH connection that includes a password protected key. This doesn't seem to happen on other sessions that also use SSH connections but do not have password protected keys.

**Comment by abhibeckert** [comment]
Yep, we're aware of this - it's because all user interface operations occur on a single thread (Mac apps have to work this way) and something on that thread requires an active connection.

The fix will require major refactoring and is planned for version 2.0.

**Comment by pdubya1234** [comment]
Thanks for the response!

**Comment by abhibeckert** [comment]
No worries, I'm going to close this so we don't have a bunch of different issues open for one problem.
