### ISSUE TITLE
Coding problem

### ISSUE THREAD

**Issue by suhanyujie** [sequelpro/sequelpro#2471]
Hello, for my use, I have a suggestion.
In the options: " Database - > View Using Encoding ", no GBK encoding options. When I use it, the display is garbled. If you can, please add the GBK option.
thank you very much！

**Comment by dmoagx** [comment]
Sorry, I can't follow.

If your table uses `gbk` encoding Sequel Pro should already handle that correctly. There is normally no need to select the encoding in the Database menu.
Alternatively you can also use `utf8mb4` from the menu, as it should include all `gbk` characters.

If the data is displayed garbled, that usually means you used the wrong charset on INSERT, e.g. storing `gbk` data in a `latin1` column or inserting `gbk` encoded data while the mysql connection charset is still set to `latin1`.
In such a case the "View using Encoding" menu won't help, you'd have to fix the data first.

**Comment by suhanyujie** [comment]
ok,thanks for your answer....
