### ISSUE TITLE
Nightly Builds are broken

### ISSUE THREAD

**Issue by abhibeckert** [sequelpro/sequelpro#2475]
Our nightly builds are currently broken in two ways:
1. they're not automatic, builds are manually created by me
2. Sparkle updates don't work, you need to manually download from http://nightly.sequelpro.com

**Comment by abhibeckert** [comment]
Nightly builds are working now, with SSL and no more subdomain:

https://sequelpro.com/nightly

The old URL still works for manual downloads, but sparkle uses the new one.

There were two builds uploaded that are configured to use the old URL and fail because of ATS, so if you run "check for updates" and get an error, then you'll have to download the latest build manually.

**Comment by abhibeckert** [comment]
(sorry if I wasn't clear, nightly sparkle updates are fixed, I'm still having to manually run the nightly script after someone makes changes)

**Comment by abhibeckert** [comment]
@rowanbeentje please update your copes of the nightly build script to match:

https://github.com/sequelpro/sequelpro/commit/6ecd8eee7db90461a0f286bd12510be42638d392

**Comment by abhibeckert** [comment]
@rowanbeentje actually, I'll be picking up a new mac mini server for doing builds/continuous integration at the end of this week so there's no need for you to get your server running. We can wait another week for nightlies to be sorted.

**Comment by rowanbeentje** [comment]
OK - I got a 10.10 OS + Xcode set up, and the nightly build script compiled using `shc`, so just need to hook it up through buildbot if you want me to still do that at some point :)

(I tend to take the nightly build script, add the keychain passwords on an admin account, and then compile it to an executable using `shc`, which is available using homebrew; I then make that world-executable and stick it in `/usr/local/bin` so the buildbot account can run it but not see the contents.  Likely not much of an extra hoop for someone if the account is compromised, but thought it was worth doing...)

**Comment by abhibeckert** [comment]
You can hook it up if you want but it'll be removed soon anyway since I want to be using 10.11

**Comment by abhibeckert** [comment]
shc doesn't provide any security, as far as I know it's just two lines of code at a bash prompt to decompile

**Comment by rowanbeentje** [comment]
Sure but if the buildbot account can't read the file, only execute it that makes things a little better, no?

**Comment by abhibeckert** [comment]
It doesn't work by readying the file, you execute then segfault, and the crash log contains the plaintext (on linux at least, not so sure about OS X)

**Comment by rowanbeentje** [comment]
Even with the tracing flag off? Damn. So no way to conceal the keychain password from the buildbot account I suppose - guess it's all moot if it'll happily sign things anyway.

**Comment by abhibeckert** [comment]
you can conceal the keychain password by leaving the keychain unlocked

**Comment by abhibeckert** [comment]
On OS X 10.11, it is also impossible to unlock the keychain if there's any software running that is monitoring keyboard events, so you can be sure there aren't any keystroke loggers while unlocking the keychain... unfortunately this means you cannot unlock the keychain via remote desktop, so we can't use a third party mac hosting company for builds.

**Comment by linushstge** [comment]
@abhibeckert can you trigger the nightly build for us? On Sierra there are many background process issues which are fixed in [bfc53dc3](https://github.com/sequelpro/sequelpro/commit/bfc53dc39c04f4c2eb3d0d79a938cf5dea368da5).
