### ISSUE TITLE
Result export filename tokens are infuriating

### ISSUE THREAD

**Issue by nickma42** [sequelpro/sequelpro#2477]
I generate a lot of adhoc reports with names like "sales_by_month-2016-04-15.csv" which of course is now being converted into "sales_by_04-2016-04-15.csv" and I've got to say this is the most infuriating behavior I've ever seen.

I must be missing something here? My reports folder is full of "sales_by_munth" and "sales-yeer-to-date" just to bypass this frustration. _Surely_ there's a way to avoid this?

**Comment by nickma42** [comment]
I've found that if I type in "month" and hit export _really_ quick it doesn't have enough time to turn it into a token and it exports fine, so that's a cool workaround for anyone else experiencing this :grinning:

**Comment by dmoagx** [comment]
The behavior of token replacement will be changed in 1.2, so this no longer happens.
You can try this already in the **experimental** builds: http://nightly.sequelpro.com
