### ISSUE TITLE
Export/Create table: ROW_FORMAT=FIXED for InnoDB table

### ISSUE THREAD

**Issue by robsch** [sequelpro/sequelpro#2478]
I've done an export from a MySQL 5.0 database and have got a dump that contains ROW_FORMAT=FIXED for InnoDB table creations. AFAIK _FIXED_ can only be used with MyISAM tables. This has caused a problem when I've tried to import the data into a new 5.7 database.

Is it a bug? Or is it my fault (then sorry for bothering you)?

**Comment by abhibeckert** [comment]
What steps can we do to reproduce this?

**Comment by robsch** [comment]
I see this also in the info view of the table the create statement. Could it be caused by the php creation script that has created the table (old Magento shop)?

<img width="1240" alt="bildschirmfoto 2016-04-18 um 11 04 12" src="https://cloud.githubusercontent.com/assets/2900992/14599052/82df2c2a-0555-11e6-93af-fe7ea265723f.png">

**Comment by abhibeckert** [comment]
After a bit of research, `row_format=fixed` can be used with InnoDB (and works perfectly on my 5.5 server) although it doesn't make much sense to use fixed rows, due to how InnoDB works.

**Comment by abhibeckert** [comment]
MySQL 5.7 will fail if you try to create an InnoDB with row_format=fixed, and the only thing you can do is manually remove the syntax (and perhaps re-create your tables on the 5.5 server to not use fixed rows either – Magento probably chose that setting back when they were using MyISAM).

This isn't a bug in Sequel Pro, it's just a backwards compatible change to MySQL.

**Comment by robsch** [comment]
Okay, fine. Thank you.

**Comment by abhibeckert** [comment]
By the way, we are considering a new export/import data format with perfect cross compatibility between different versions of MySQL.

Currently we just ask MySQL to provide the necessary SQL to re-create a table and don't do any processing, which often causes issues like this one.

It's a big undertaking, so not part of our short-term plans.
