### ISSUE TITLE
Option to always show the Tab-Bar

### ISSUE THREAD

**Issue by akazik** [sequelpro/sequelpro#2479]
It would be great if there is an option to always show the tab bar and not only if there are two or more tabs.
Because I really started to use the coloring and it does not show without the tab bar.

**Comment by willpower232** [comment]
You should see it as the first option in the View menu

<img width="124" alt="screen shot 2016-04-18 at 16 02 36" src="https://cloud.githubusercontent.com/assets/1619102/14608800/0b18f8e0-057f-11e6-840f-e9614e08e96b.png">

**Comment by akazik** [comment]
Great!
(I've searched the preferences for it.)
Thanks.

**Comment by abhibeckert** [comment]
Also, nightly builds show a coloured strip when the tab bar is hidden:

![screen shot 2016-04-19 at 06 39 56](https://cloud.githubusercontent.com/assets/266088/14619194/a28230c8-05f9-11e6-98f5-3fd4c5bb237b.jpg)
