### ISSUE TITLE
Bug - Temporary freezes when executing (simple) queries

### ISSUE THREAD

**Issue by rfeiner** [sequelpro/sequelpro#2483]
I (and others in my dev team) experience an issue with version 1.1.2 (on OSX 10.11.4 (15E65)). Executing queries, even very simple ones (see screenshot), causes a temporary freeze of SequelPro for seconds. The actual query time (displayed in status bar after finally finishing) states 27.2ms.

![screen shot 2016-04-21 at 17 07 38](https://cloud.githubusercontent.com/assets/2319799/14714153/2812b99c-07e4-11e6-9f6f-bdcceada2124.png)

**Comment by dmoagx** [comment]
That usually happens when Sequel Pro discovers that the connection was lost and it has to reconnect first.

Please open Activity Monitor, select the Sequel Pro process, start a query in Sequel Pro, and as soon at it freezes select View > Sample Process (cmd+alt+S) in Activity Monitor and post the results.

**Comment by rfeiner** [comment]
Here's a the requested sample file 
[Sample of Sequel Pro.txt](https://github.com/sequelpro/sequelpro/files/231362/Sample.of.Sequel.Pro.txt)

**Comment by dmoagx** [comment]
How large is your Sequel Pro preferences file (`~/Library/Preferences/com.sequelpro.SequelPro.plist`)?

**Comment by rfeiner** [comment]
Is was 16776323 lines. Now I've cleared the history, now its 31 lines. But issue persists.

**Comment by dmoagx** [comment]
Have you cleared it via Sequel Pro?
Otherwise you need to quit Sequel Pro and run `killall cfprefsd` first.

**Comment by rfeiner** [comment]
That's it! Thanks for your help!
