### ISSUE TITLE
Database/Table treeview background gets the color from anything behind

### ISSUE THREAD

**Issue by eljamz** [sequelpro/sequelpro#2484]
So I have been noticing this for a while, if there's something bright in the background like a webpage or something else, the treeview of the database/tables get the color and loses the regular gray.

Is this part transparent or it is a regular light-gray? (maybe is my IPS   ##monitor)

Screenshot attached.
![screen shot 2016-04-22 at 3 41 01 pm](https://cloud.githubusercontent.com/assets/153168/14754426/eb46b0fa-08a0-11e6-88b9-589e0a623192.png)

**Comment by eljamz** [comment]
BTW this happens only with bright colors, it works as expected if there's something dark behind.

**Comment by abhibeckert** [comment]
This is the system default background colour for all sidebars and yeah, it can be really ugly at times.

In system preferences, universal access you can enable "reduce transparency" to fix it.
