### ISSUE TITLE
Night Mode / Dark Mode

### ISSUE THREAD

**Issue by rh0dium** [sequelpro/sequelpro#2485]
May we get a night mode? #

**Comment by dmoagx** [comment]
... and what would that Night mode do?

**Comment by rh0dium** [comment]
Err - I was thinking dark mode.  Not night mode.  So to be clear it would darken up the UI elements so it's not so hard on my 👀 

Thanks

**Comment by abhibeckert** [comment]
Apple doesn't provide "dark mode" for any UI elements except for the menu bar (and even those have bugs currently).

We're not able to commit development time to re-creating every UI element used in Sequel Pro. It's just too much work.

**Comment by Mahmoudz** [comment]
Damn it would amazing if someone would do that, currently everything have support for Dark mode (IDE, Terminal, Postman...) so would be nice if SequelPro looks like them on my screen!

**Comment by markpanado** [comment]
Please.. We need dark mode.. Or just a dark theme.. Not just the text editor, but the whole gui..

**Comment by abhibeckert** [comment]
@markpanado Night Shift in macOS 10.12.4 doesn't solve this problem for you?

**Comment by abhibeckert** [comment]
We'll look into how feasible this is to be included in version 2.0.

It might be too much work (replacing UIKit) to make everything black, but a much darker shade of grey may be an acceptable compromise.

**Comment by markpanado** [comment]
@abhibeckert for me I just prefer a #333 background color or similar for the tools I use. I really hope this will get included in the future versions. Thank you!

**Comment by vduke** [comment]
Personally would love to have a Dark UI as well. All my other tools for development have it such as sublime text, visual studio code, PHP Storm, PAW, etc etc etc.  the new https://tableplus.io/ app seems to have this as well but it's feature set is limited compared to Sequal Pro in my opinion. Big +1 to this :)

**Comment by huyphams** [comment]
I have implemented a dark mode on my client, you guy can use this open source for Sequel Pro:

 https://github.com/luckymarmot/ThemeKit, it easy to use and run on production already.

<img width="1226" alt="screen shot 2018-05-18 at 11 24 40 am" src="https://user-images.githubusercontent.com/3654622/40216002-195274f2-5a8e-11e8-821c-9fd47483bfd0.png">

**Comment by MattRiddell** [comment]
Especially now with Dark Mode in Mojave it would be awesome

**Comment by metalmini** [comment]
Yes, dark mode would be a nice touch!

**Comment by jvrsolis** [comment]
Ive been using this developers dark mode 

> https://medium.com/@guilhermerambo/how-to-enable-real-dark-mode-on-os-x-macos-14966f9f7d24

 conversion which is meant to convert app kit apps not electron or other applications to dark mode but it didnt really work with high sierra for this application. But I tried it in mojave and it works well enough the default black text in the table row data is the only issue for me atm

<img width="1290" alt="screen shot 2018-08-31 at 2 42 25 pm" src="https://user-images.githubusercontent.com/4006455/44932876-ab5d8800-ad2c-11e8-862c-32f3ceb78f78.png">

**Comment by dmoagx** [comment]
https://github.com/sequelpro/sequelpro/search?q=dark&unscoped_q=dark&type=Commits

**Comment by caiofbpa** [comment]
I would like to test the latest versions supporting dark mode and provide feedback, but haven't found how to do that other than building it locally. Is there an easier way?

**Comment by dmoagx** [comment]
> Is there an easier way?

No there is not atm

**Comment by lrrrs** [comment]
You just need to compile the project with Xcode 10 + 10.14. Just be sure to select 64-bit architecture for all targets first. 32-bit is gone since Mojave ...

<img width="1552" alt="bildschirmfoto 2018-09-24 um 14 55 38" src="https://user-images.githubusercontent.com/671002/45953523-9f52a680-c00a-11e8-8812-a7881f3934dc.png">

Looks already pretty good.

**Comment by MattRiddell** [comment]
This is cool.  There's some weird stuff with upside down characters and corruption of the UI occasionally but overall it's 100x nicer looking!

**Comment by h3l** [comment]
@lrrrs after build by myself. A few modify can get a more perfect experience.
* mod you query editor color setting like this
![image](https://user-images.githubusercontent.com/1664952/46146454-6b3ee600-c295-11e8-9143-b027c3fd0fbb.png)

* modify `/Source/SPTextView.m` line 255 from `whiteColor` to `blackColor` to make the popup window be black. the result is below
![image](https://user-images.githubusercontent.com/1664952/46146669-ea341e80-c295-11e8-9683-ef9f6c624165.png)

**Comment by kalieye** [comment]
a few quirks here and there but it looks pretty great already

**Comment by Stexxen** [comment]
Just spotted this in the popup window when you are using a TEXT or BLOB style field. 
Black text on dark background

![image](https://user-images.githubusercontent.com/4494301/46584167-e05da880-ca57-11e8-9e05-692bbc82ff3d.png)

**Comment by stuconnolly** [comment]
Still to be done in order to fully support dark mode:

* Icons
* Tab bar
* Shortcut recorder (see #2300)

**Comment by shishanyu** [comment]
Hey guys, thanks for your great work.
Could it be possible that the favorites with a color tag get a different color scheme? My suggestion would be to either go for the color tag to a darker tone, or getting the font to a black color, so it improves readability.

![screen shot 2018-11-06 at 11 13 57 am](https://user-images.githubusercontent.com/871724/48081186-14da9680-e1b5-11e8-9e6d-75ff7d494f89.png)

**Comment by EricLi404** [comment]
Hey guys, This is my compiled version of support maxOS Mojave's Dark Mode, which you can download [here](https://github.com/EricLi404/sequelpro/releases/tag/release-1.1.3-alpha)
![image](https://user-images.githubusercontent.com/12013112/48182064-da176080-e364-11e8-981a-9ed6e9b6587c.png)

**Comment by coredumperror** [comment]
Dark Mode is looking good so far! With h3l's suggestion for color scheme changes in the Query Editor, my one remaining issue is the active tab in the Tab bar. Its background color is bright grey and text color is white (as of build 5426), which makes it nearly impossible to read. The inactive tab is acceptable, though it does feel a little too bright next to the rest of the dark UI elements.

**Comment by mamakawama** [comment]
Noob build steps?

**Comment by stychos** [comment]
@mamakawama

Pretty easy:
- download XCode from the App Store
- download the repository Zipfile
- open project file and press "Build".

**Comment by stychos** [comment]
> I'll have to figure out how to make it a permanent local app. 

Just copy application build from ~/Library/Developer/Xcode/DerivedData/... (find there) into your /Applications directory.

**Comment by stychos** [comment]
Did some work on icons: https://github.com/sequelpro/sequelpro/pull/3386
![screen shot 2019-02-14 at 8 38 15 pm](https://user-images.githubusercontent.com/1531639/52809257-7bb2fa00-3098-11e9-8d85-e9d8fbcc8d7b.png)

**Comment by stychos** [comment]
What's left for the dark mode?

**Comment by mamakawama** [comment]
I noticed a problem with the "filter" function. It just wouldn't show up.

**Comment by stychos** [comment]
@mamakawama Can you explain what do you mean?

**Comment by mamakawama** [comment]
The filter that lets you query the table content view by a single column, that is toggled by a funnel like looking button at the bottom disappeared (blank area/row instead of drop down selector and input field)

I can give a screenshot when I'm back at work tomorrow.

**Comment by stychos** [comment]
Are you about this funnel?
![screen shot 2019-02-14 at 11 51 54 pm](https://user-images.githubusercontent.com/1531639/52820097-c2621d80-30b3-11e9-9d80-f4e506f00107.png)
Now it enables/disables the multifilter ui. Anyway, this issue is for the Dark Mode issues.

**Comment by mamakawama** [comment]
Yeah, the form glitched. Panel expanded onClick but no form elements in the formarea.

**Comment by stychos** [comment]
You can try [this build,](https://github.com/stychos/sequelpro/releases/tag/release-1.2-alpha1) I never issued that so I think it's fixed in a master branch. But even if it exists then it's not related to this topic and you will need to open new issue (if there's no issue for this trouble already exists).

**Comment by Kaspik** [comment]
https://github.com/sequelpro/sequelpro/pull/3386 - Icons done

**Comment by mitin001** [comment]
Is there a way to switch back to light mode in the latest nightly build, if your OS is in dark mode?

**Comment by stychos** [comment]
@mitin001 add the boolean NSRequiresAquaSystemAppearance key into the root of your SequelPro.app/Contents/Info.plist with the value "YES", you can force any app to white mode with this.

**Comment by abhibeckert** [comment]
To disable dark mode, use the following:

    defaults write com.sequelpro.nightly NSRequiresAquaSystemAppearance -bool yes

And to reset to default behaviour:

    defaults delete com.sequelpro.nightly NSRequiresAquaSystemAppearance

And of course, once this makes it into the public release you will need to switch the bundle identifier:

    defaults write com.sequelpro.sequelpro NSRequiresAquaSystemAppearance -bool yes
    defaults delete com.sequelpro.sequelpro NSRequiresAquaSystemAppearance

**Comment by mitin001** [comment]
> To disable dark mode, use the following:
> 
> ```
> defaults write com.sequelpro.nightly NSRequiresAquaSystemAppearance -bool yes
> ```
> 
> And to reset to default behaviour:
> 
> ```
> defaults delete com.sequelpro.nightly NSRequiresAquaSystemAppearance
> ```
> 
> And of course, once this makes it into the public release you will need to switch the bundle identifier:
> 
> ```
> defaults write com.sequelpro.sequelpro NSRequiresAquaSystemAppearance -bool yes
> defaults delete com.sequelpro.sequelpro NSRequiresAquaSystemAppearance
> ```

`com.sequelpro.nightly` or `com.sequelpro.sequelpro` did not work for me on build 5438 (664a46cd). `com.sequelpro.SequelPro` did

**Comment by coredumperror** [comment]
Is it just me, or do the tab colors make the active tab title unreadable? I have build 5438 (664a46cd).

<img width="1118" alt="Screen Shot 2019-05-09 at 11 11 08 AM" src="https://user-images.githubusercontent.com/413571/57476332-30e5f000-724b-11e9-99fe-d72ca929ac2e.png">

**Comment by stychos** [comment]
@coredumperror This is fixed in https://github.com/sequelpro/sequelpro/pull/3375
You can merge it manually or try [my build](https://github.com/stychos/sequelpro/releases/tag/release-1.2-alpha7) with few other fixes for the dark mode and filters.

**Comment by coredumperror** [comment]
<img width="1426" alt="Screen Shot 2019-08-06 at 1 20 57 PM" src="https://user-images.githubusercontent.com/413571/62574344-24266780-b84d-11e9-8deb-988bbea24374.png">

Can you tell that on line 3, the `survey_response.survey_id` code is selected? Or see the cursor? Because I sure can't. I'm using the latest build of SequelPro, and have also tried various builds from @stychos, and all of them have this problem.

This makes the query tab nearly worthless, as you essentially can't edit the contents if there's no visible cursor or selection. This is so awful that I can only assume that I'm somehow the only one experiencing this, as it surely would have been reported by someone else by now.

But what the heck could be wrong on my end that's causing this?

**Comment by MattRiddell** [comment]
Looks like your query background is super dark

**Comment by coredumperror** [comment]
Oh shoot, I didn't even realize this color scheme was a preference! Now I can fix it. Thanks.

**Comment by xlcrr** [comment]
@lrrrs can you explain how you achieved that UI please? Looks amazing!!

**Comment by aledexter** [comment]
How we can change the favorite colors when in dark mode?
Or at least it is possible to turn black the text when the  and the favorite background is colored becaus it is unreadable
![immagine](https://user-images.githubusercontent.com/11591259/74093309-7a13ea80-4ad0-11ea-8ec8-c96ec802d570.png)

**Comment by kvlknctk** [comment]
five years and no dark theme. lazy coders.

**Comment by caiofbpa** [comment]
Five years, some active coding, but no new releases. I don't understand this. Maintainers?

**Comment by Kaspik** [comment]
There are no “maintainers” anymore kind of. Use nightly build to get dark mode until someone starts working on the project again... :)

**Comment by Pysis868** [comment]
Hm, open project locally in Xcode and hit run.  Last commit f0987c5 on Sep 29, 2019.

stychos has some ready made releases if you feel comfortable running those with an included own dark mode patch: https://github.com/sequelpro/sequelpro/issues/2485#issuecomment-491033778
https://github.com/stychos/sequelpro/releases

Actually up to release-1.2-alpha8 from Jul 28, 2019, a bit before this repo's current latest.

For this project's strategy, I wasn't used to Xcode.  The project seemed to run fine enough, 2 errors, but that doesn't stop it.  Although I couldn't find the output application files from a normal or runnable build, and export isn't what I wanted.

After I realized it might be easier just to use the command line `make` command, it tells you where the output app is, and I realize Spotlight can already find it too, so I copy that to my Applications directory and that works well enough.

**Comment by ricardoalcocer** [comment]
Commenting so the bot doesn't remove this.

**Comment by JamesVanWaza** [comment]
@ricardoalcocer follow new developments on https://github.com/Sequel-Ace/Sequel-Ace

**Comment by ricardoalcocer** [comment]
> @ricardoalcocer follow new developments on https://github.com/Sequel-Ace/Sequel-Ace

Oh wow. Great. Thank you.

**Comment by adriancaragea** [comment]
But still no dark mode.

**Comment by Kaspik** [comment]
@adriancaragea Read the messages above. [https://github.com/Sequel-Ace/Sequel-Ace](https://github.com/Sequel-Ace/Sequel-Ace)

**Comment by rainb3rry** [comment]
my eyessss
