### ISSUE TITLE
Unable to save connections to bookmark

### ISSUE THREAD

**Issue by venkateshk** [sequelpro/sequelpro#2488]
I am on 1.1.2. I launched my app after a long time and noticed that all my connection bookmarks are gone and now I am no longer able to save a new connection too as save button is disabled.

I am on OSX El Capitan (10.11.3). 

Noticed the same issue with my colleague who is on 1.1

![screen shot 2016-04-28 at 3 53 09 pm](https://cloud.githubusercontent.com/assets/422478/14903898/63a1e42c-0d59-11e6-885b-258238967cec.png)

**Comment by venkateshk** [comment]
Though Add to Favourites button seemed to be enabled, nothing happens when I click on it. Also nothing happens when I click on the + icons at the bottom left corner under Quick Connect section.

**Comment by abhibeckert** [comment]
The save changes button is only available when you are editing a favourite that already exists.

I'm not sure why "ad to favourites" doesn't work, are there any error messages visible in Console.app?

**Comment by abhibeckert** [comment]
There's something weird going on - your screenshot has no "favourites" heading under the "quick connect" screen. It should look like this:

![screen shot 2016-04-29 at 9 03 17 am](https://cloud.githubusercontent.com/assets/266088/14904136/8210ec24-0de9-11e6-9cf8-f25cc55cf091.png)

Can you try moving `~/Library/Preferences/com.sequelpro.SequelPro.plist` to the desktop, then launch Sequel Pro and see if it's fixed?

**Comment by venkateshk** [comment]
I moved ~/Library/Preferences/com.sequelpro.SequelPro.plist to desktop and launched Sequel Pro again and I still don't see Favourites heading. Relaunching the app generated a new com.sequelpro.SequelPro.plist file, attached for reference if it helps to figure out what's going on.
(changed the extension to .txt so that the file could be attached)

[com.sequelpro.SequelPro.plist.txt](https://github.com/sequelpro/sequelpro/files/241752/com.sequelpro.SequelPro.plist.txt)

**Comment by venkateshk** [comment]
I see only this message related to the app in Console.app

Error retrieving data directory path: The file “Data” couldn’t be saved in the folder “Sequel Pro”.

**Comment by sequelpro** [comment]
Great, that's the problem. Favourites are saved to:

`~/Library/Application Support/Sequel Pro/Data/Favourites.plist`

There must be something wrong there, perhaps the filesystem permissions are wrong?

**Comment by venkateshk** [comment]
That is it, somehow the filesystem permissions got messed up. I fixed them and Favourites are back. Thanks for the help @abhibeckert and @sequelpro

**Comment by manwey** [comment]
Fill the fields, click connect and after File > Add to Favorites
