### ISSUE TITLE
Malformed COM_SLEEP packet

### ISSUE THREAD

**Issue by sidorares** [sequelpro/sequelpro#2490]
Hi!

I have a library implementing server side of mysql protocol and users are [reporting](https://github.com/sidorares/node-mysql2/issues/242#issuecomment-216111907) problems connecting from Sequel Pro to server using that library 

The packet it sends looks like COM_SLEEP command, but I'm not 100% sure, it might actually be incorrect padding of outgoing packet with extra zeroes. Wireshark dissector also marks packet as malformed:

![](https://cloud.githubusercontent.com/assets/177816/14948016/655bf214-0ff0-11e6-9198-c7c515433962.png)

Could you help to investigate?

cc @vogievetsky
ref: https://github.com/sidorares/node-mysql2/issues/242#issuecomment-216111907

**Comment by dmoagx** [comment]
The issue you are seeing is that Sequel Pro uses a compressed MySQL connection (`CLIENT_COMPRESS`) which looks significantly different on the wire.

Wireshark doesn't understand the full MySQL protocol, that's why it shows Malformed packet.

**Comment by dmoagx** [comment]
Btw you can disable compression in the nightly builds: https://github.com/sequelpro/sequelpro/issues/2122#issuecomment-126113804

**Comment by vogievetsky** [comment]
Can confirm, if the server does not report CLIENT_COMPRESS (0x00000020) capability flag: it works.

**Comment by sidorares** [comment]
Thanks @dmoagx , I should have noticed that myself, that's compression.
