### ISSUE TITLE
Cog Icon a bit off place

### ISSUE THREAD

**Issue by eSkiSo** [sequelpro/sequelpro#2493]
Hello, on at least (a00f2a7) the cog icon on the left side is a bit off place
![cogincon](https://cloud.githubusercontent.com/assets/671793/14977645/973875a0-110d-11e6-9e01-838237cc5d90.png)

**Comment by abhibeckert** [comment]
Thanks for testing the nightlies, it's a known bug should be fixed in the next few days.

**Comment by stuconnolly** [comment]
This has since been resolved.
