### ISSUE TITLE
use `database` edge case issue

### ISSUE THREAD

**Issue by Fudge0952** [sequelpro/sequelpro#2494]
Probably a very low class issue (could even be improvement)

If you use the "Query" tab and type `USE <db>` where <db> is the name of the database in an invalid case it will still load the contents of the database (as MySQL is case insensitive) but the drop down in the top left will have selected a blank row.

Quick example:
I have a database with 3 tables named `MyData`. I type `USE MYDATA` the list will still list my 3 tables but the drop down will show a blank item as MYDATA is not equal to MyData.

Maybe a case insensitive check? Happy to try and create a PR but it wouldn't be for a while as I'm very flat out. Happy if someone else wants to do it though

**Comment by abhibeckert** [comment]
Can you provide more details? I can't reproduce this bug.

**Comment by Fudge0952** [comment]
Sure I have attached screen shots if they help. First screenshot is a list of my databases. second one is the result of my query. Does this help at all?

![screen shot 2016-05-04 at 10 02 17 am](https://cloud.githubusercontent.com/assets/3098078/15001964/780d9b60-11df-11e6-94d5-8dd0b0664628.png)
![screen shot 2016-05-04 at 10 02 48 am](https://cloud.githubusercontent.com/assets/3098078/15001966/7a0e50f8-11df-11e6-9711-c417ebaea245.png)

**Comment by abhibeckert** [comment]
This must depend on the version of MySQL.

I tested with a couple of my servers, and found that MySQL 5.5.42 doesn't have the bug and works flawlessly, while MariaDB 5.5.44 simply fails with an "unknown database" error.

Alternatively, it might depend on wether or not the filesystem (mac vs linux) is case sensitive?

**Comment by Fudge0952** [comment]
This could be very true. I know that a lot of MySQL queries are case-insensitive so I just assumed that the db names could be case insensitive as well. Admittedly I did only test on my local machine which obviously is OS X. Further testing on my CentOS 6 Virtual Box shows that it is case sensitive on CentOS 6 (returning unknown DB when the case is incorrect). So I'm not sure what you want to do with this issue as it's present on OS X Db's but not on others. I'll leave it up for your executive decision :)

**Comment by abhibeckert** [comment]
I don't want to spend too much time investigating (you're welcome to do so), but at this point I'm going to assume this isn't a bug in Sequel Pro, but rather a bug caused by running MariaDB on a case insensitive filesystem.

MySQL doesn't have the bug on OS X (use db is case insensitive), so Sequel Pro clearly can handle case insensitive use queries.

Running on Linux MariaDB is case sensitive, and Sequel Pro respects that.

**Comment by Fudge0952** [comment]
Ok acceptable

**Comment by abhibeckert** [comment]
I'm only closing this issue to try and reduce the number of open issues, since I'm not going to investigate further.

You mentioned you might do a pull request in future, if you do that feel free to re-open this issue. :-)
