### ISSUE TITLE
Activities block is always empty

### ISSUE THREAD

**Issue by shoan** [sequelpro/sequelpro#2496]
As of nightly 4728 and maybe a couple of versions earlier, the activities block is always empty. Other than the title, all the contextual information is not visible.

![screen shot 2016-05-05 at 07 49 26](https://cloud.githubusercontent.com/assets/333168/15034740/6d734652-1296-11e6-9f8f-29e94da98609.png)

**Comment by dmoagx** [comment]
That is because you have enabled Activities view, which shows only running bundle commands. Double click on the "Activities" header to switch back to the table info view.
