### ISSUE TITLE
Export format templates

### ISSUE THREAD

**Issue by ottosmittenaar** [sequelpro/sequelpro#2497]
Hi,

I really love SequelPro. I often need to convert data structures and use SequelPro for that. I use then PHP to export the data to a specific XML format. Would it be possible to create your own XML export format templates that can be used by SequelPro to export a specific XML format? Other tips and tools are also very much appreciated.

Thanks & best,
Otto Smittenaar

**Comment by Allendar** [comment]
Could you clarify with an example XML how you would expect templates to be? For example; would it be something with multiple layers based on automatic Foreign Key detection?

**Comment by Allendar** [comment]
Extra note: if Foreign Keys have some circular reference somewhere in the database structure, this could end up very bad in code. It would need to have some limitation counter and notify the user of the situation. Allowing the code to run a self-referencing loop might end up running into a deadlock.
