### ISSUE TITLE
tabs visual identification 

### ISSUE THREAD

**Issue by jimlongo56** [sequelpro/sequelpro#2501]
If I'm viewing multiple tabs of different servers that are for all intents and purposes identical.  Staging, sandbox, production, etc.,  

Currently the only identifier of what database you're on is way up at the top of the window, my eyes seem to have to take quite a journey to get up there.  

*  In the tab it would be nice to show the Connection Name instead of (or in addition to) the database name.  Options woud give the user even more granular control over what is displayed.  
* Having the ability to add a colored background (maybe a dot, or icon of some sort) to the tabs would make it even more obvious what db you were looking at.  

**Edit**: Curious the NAME is evident when the tab is inactive, then it disappears when you activate it.  Just leaving it there would be a big improvement.

**Comment by abhibeckert** [comment]
For colours, this is a duplicate of #346 which is done in nightly builds (http://nightly.sequelpro.com).

I'm not sure why the tabs have a different name while active vs inactive – will look into it.

**Comment by dmoagx** [comment]
> I'm not sure why the tabs have a different name while active vs inactive – will look into it.

This has been discussed in the past already.
This is a feature to help you visually distinguish what DB you are working with.

If a background tab is connected to the same DB as the active tab (of which you can easily see the DB from the DB dropdown) it will only show the table name.
If both connections are to the same host but a different DB the db names will always be shown.
If you are connected to multiple different hosts it will show the favorite name on all tabs that are not connected to the same host...

> Having the ability to add a colored background (maybe a dot, or icon of some sort) to the tabs would make it even more obvious what db you were looking at.

That feature has been in Sequel Pro for > 6 months now: http://www.sequelpro.com/blog/2015.09/sequel-pro-1-1-a-touch-of-colour-for-your-databases/
