### ISSUE TITLE
Favorites storage format redesign

### ISSUE THREAD

**Issue by dmoagx** [sequelpro/sequelpro#2502]
Recent requests like #2480 as well as long standing issues like #1843 lead me to believe we should redesign our favorite storage format.

Our current format is:
- Single file for all favorites
- Plist Serialization (also note this issues from plist Caching in recent OS X versions)
- Always stored in the `~/Library/Application Support/Sequel Pro/Data` folder.

Our goals for a new format should be:
- One directory per favorite (because of the additional data like Query favorites)
- Reproducible, diff-friendly and human-readable serialization
- Stored anywhere and just linked in Favorites list
- VCS and fileshare friendly (e.g. git, Dropbox)

**Comment by abhibeckert** [comment]
Sharing would be easier if it was a single file per favourite instead of a directory?

How about JSON for the format?

How would we expose being able to save them anywhere in the GUI?

**Comment by dmoagx** [comment]
> How would we expose being able to save them anywhere in the GUI?

I don't think we need much UI for that:
* There will be a context menu item in the favorite list "Show on disk".
* If someone opens a favorite file via Finder it will be added to the favorites list
* When creating a new favorite we will just put it where we store favorites now. The user is free to later move it into a shared directory or so.
* Since the way of storing favorites would be the same for local and shared favorites there is no need for export/import anymore

**Comment by abhibeckert** [comment]
After discussion on slack, we have decided:

There will be a list of directories where favourites are stored. By default the only one is in Application Support, but users can add an extra one, perhaps shared with other users somehow.

We will scan each directory for favourite bundles, which will contain a human readable/writable JSON file for each component in the favourite (connection settings, query favourites, export settings, etc).

Opening a favourite file from disk will connect to it but not add it to favourites (allowing management outside of Sequel Pro).

Dragging a favourite file onto the list will copy it into the target favourites directory.
