### ISSUE TITLE
Can't click foreign keys referencing table in another schema

### ISSUE THREAD

**Issue by nielsiano** [sequelpro/sequelpro#2504]
When a foreign key references a table in another schema clicking the arrow does not direct you to the other table.

![image](https://cloud.githubusercontent.com/assets/947684/15251420/99b60f08-1929-11e6-9406-342c115accb8.png)

In this case clicking the `item_id`-arrow plays an error sound.

**Comment by dmoagx** [comment]
Yeah, that's currently not implemented.
