### ISSUE TITLE
Table specific permissions?

### ISSUE THREAD

**Issue by TimAEllis** [sequelpro/sequelpro#2505]
Sometimes a user is granted partial access to a table. Is there any way that Sequel can handle:
- Being able to set permissions specific to a table (In the database -> user accounts window).

For example: Say we have a table with the fields: ID, FNAME, INITIALS, LNAME, DOB, ADDRESS but we don't want some users getting access to sensitive information we do this:
`GRANT SELECT(ID, FNAME, INITIALS, LNAME) ON DB.TABLE TO 'USER'@'HOST';`

To allow USER partial access. The command `SHOW GRANTS` can be used to get the current users permissions.

So maybe another tab for Table Privileges?
- Secondly could you expand the table view to show the granted columns because right now I have to use the query tab with `SELECT LNAME, ENUM, INITIALS, FNAME FROM TABLE;`

Thoughts?

**Comment by Fudge0952** [comment]
I've noticed that this issue hasn't had any attention at all. Is this a potential feature?

**Comment by abhibeckert** [comment]
Yep it's definitely a potential feature. Thanks for writing it up.

We can't give you a timeline when it would be implemented, unless you're prepared to take on the work yourself.

**Comment by Fudge0952** [comment]
Right now I'm snowed down with uni, work and freelance work I'm happy to have a crack at it but I'm in the same position as you currently, no ETA. I'll update this issue if I get around to it, but don't wait up for me because it might not come about then 😆

**Comment by abhibeckert** [comment]
I've got ~6 months of work planned on other features in sequel pro so unless you do it or someone else does, it'll be a long wait.

**Comment by TimAEllis** [comment]
Still no love for this ticket I assume? Wondering if this project is still alive...

**Comment by stychos** [comment]
@TimAEllis there is new life in https://github.com/Sequel-Ace/Sequel-Ace fork, I propose you to create this feature request in there. Unfortunately I am not a true developer to promise you anything, but current maintainers are doing great job trying to reanimate this project in that fork.

**Comment by TimAEllis** [comment]
@stychos I created the ticket 4 years ago haha. Just wanted to prevent the ticket from being closed. I’ll move the ticket over in the morning (my time 😝)
