### ISSUE TITLE
An SQL function is displayed as a column's name instead of the column name described as a function argument

### ISSUE THREAD

**Issue by umpc** [sequelpro/sequelpro#2506]
An SQL function is displayed as a column's name instead of the column name described as a function argument.

To reproduce this:
```
SELECT DATE_FORMAT(`x`,'%Y-%m-%dT%H:%i:%sZ') FROM `y`;
```
where ```x``` is the name of a datetime column and ```y``` is the name of a table that contains the chosen datetime column.

![screenshot 2016-05-15 15 14 13](https://cloud.githubusercontent.com/assets/5883661/15276216/ba0d0036-1aaf-11e6-89e8-5f769aa0af63.png)

**Comment by dmoagx** [comment]
The output you see is the perfectly fine result for MySQL (and also Oracle and probably all other RDBMS's).

What you are looking for is called an alias: http://www.geeksengine.com/database/basic-select/column-alias.php
