### ISSUE TITLE
SSH Conection Fails unless password is re-entered

### ISSUE THREAD

**Issue by crzapata** [sequelpro/sequelpro#2509]
When attempting to establish a connection through ssh the connection will fail unless the Password is re-entered.

Environment:
MySQL Host: AWS RDS
SSH Host: AWS EC2 Instance
SSH Key is used for connection to SSH Host

**Comment by dmoagx** [comment]
Description unclear.
https://github.com/sequelpro/sequelpro/wiki/How-do-I-write-a-proper-issue-report%3F

**Comment by crzapata** [comment]
Please disregard issue. I recreated and saved the connection and it's working fine. Sorry!
