### ISSUE TITLE
interactive recovery after sleep/network can cause deadlock in UI

### ISSUE THREAD

**Issue by springstim** [sequelpro/sequelpro#2510]
After sleep or network reset where manual SSH tunnels, etc. are used - I have run into cases where after awaking from sleep (possibly on a new WiFi network)  to ask if user wants to disconnect or retry -  that it's impossible to click on more than one of those dialogue windows.  After clicking on the first to reconnect (or disconnect), there seems to be no way to click on the others.  I've tried moving all of the windows out of the way but it seems like the process is waiting for some UI event that might be impossible to trigger. At that point I have had to force-kill the process and relaunch Sequel Pro.

**Comment by dmoagx** [comment]
I made a special debug build with additional logging: http://dev.sequelpro.com/uploads/sequel-pro-i2526.dmg

Please open Console.app and search for Sequel Pro, then start the debug build and post the output from console once the hang occurs.

**Comment by dmoagx** [comment]
Closing after no user feedback.
