### ISSUE TITLE
CSV Import - UPDATE method does not work

### ISSUE THREAD

**Issue by JeremyRYoung** [sequelpro/sequelpro#2516]
I have successfully used CSV import on my datatables using the INSERT and REPLACE methods but the UPDATE method does not work - if UPDATE is selected from the dropdown menu in the dialog box  then the import button is greyed out. I will attach a screengrab to illustrate this. NB This applies whether the update is affecting all the fields or only a few.

![screen shot 2016-06-08 at 12 46 11](https://cloud.githubusercontent.com/assets/7645294/15893357/0198179a-2d77-11e6-9bc7-9bc23c9f3fea.png)

**Comment by dmoagx** [comment]
When using UPDATE you must define one or more columns to match (ie. the columns that will be the WHERE expression in the UPDATE query).
To do this, align the fields and then click on the "–" in the middle to change it to "=".
