### ISSUE TITLE
Font settings for popup sheet (feature request)

### ISSUE THREAD

**Issue by mkismy** [sequelpro/sequelpro#2517]
When I change the table view font from the settings, the changes are only applied to the table and popup sheet fonts doesn't change.
I would like to have another font settings for popup sheet.

Before
![2016-06-09 15 39 32](https://cloud.githubusercontent.com/assets/8445575/15920874/7efd0650-2e58-11e6-95eb-ec5d433a1620.png)

After
![2016-06-09 15 38 27](https://cloud.githubusercontent.com/assets/8445575/15920876/82b17506-2e58-11e6-9a4f-99df99d9de59.png)

**Comment by dmoagx** [comment]
That is already possible.
Just right click somewhere in the text, select _Font > Show Fonts_, pick a new font and close the panel. Sequel Pro will remember that setting.

**Comment by mkismy** [comment]
Thanks! It worked!
