### ISSUE TITLE
Global Log

### ISSUE THREAD

**Issue by 2ge** [sequelpro/sequelpro#2518]
Hi,

first of all thanks for superb program, love it. Sometimes it crashes, and would be useful, if there is option to turn on global query log, sometimes I write complicated SQL statements and I lose them, when there is crash. I think this feature would be useful for other developers too.

Thanks!

**Comment by abhibeckert** [comment]
Your queries are saved in the "Query History" menu. Is this not working for you?

Also, can you provide more detail about the crashes?

**Comment by 2ge** [comment]
ahm, I find it now, it is not in top window menu, but in Query window pane. OK, got it.

Next time, when it crash, I will send more info, thanks!
