### ISSUE TITLE
Select results will show ??? in UTF-8 column

### ISSUE THREAD

**Issue by withshe** [sequelpro/sequelpro#2520]
![2016-06-19 8 52 38](https://cloud.githubusercontent.com/assets/461748/16177434/c8642580-365f-11e6-8842-3d80ffb93b5a.png)

The picture above shows the problem, ???? actually are 东区 or 南区

**Comment by dmoagx** [comment]
...and what charset has the table?

**Comment by dmoagx** [comment]
Closing after no user feedback for 1 month.
