### ISSUE TITLE
Support defining bound variables in query pane

### ISSUE THREAD

**Issue by dylanvorster** [sequelpro/sequelpro#2521]
SQL Pro is essentially the best application a developer could ever ask for when it comes to database work, but something that I find myself wanting over and over, is the ability to copy a query from any programming language and have it auto fill the bound variables ( :var1, :var2 , ?,?,?,? , etc... ) with parameter placeholders that can then be filled out in the resultset panel below.

This would be useful because it would allow us to copy large queries to and fro between our IDE's as well as SQL pro without having to go run through each query and replace the bound parameters with functioning code. It will also allow us to use SQL pro for a lot more as we could setup reports (useful for Database Admins who need to run the same queries over and over) but with different variables.

Ive attached an example mockup on how this could work. 
![mockup](https://cloud.githubusercontent.com/assets/6099427/16195715/2e2c3966-36fb-11e6-8b69-90dc3a4481b2.png)

Im not sure if this would be the best way to do it, but would certainly be a really useful addition to an already very useful application.

**Comment by abhibeckert** [comment]
Something similar can be done with regular SQL:

    set @start = '2012-01-01';
    set @end = '2016-01-01';
    
    select * from page
    where modified > @start
      and modified < @end

But I agree, it would be convenient to use the standard prepared statement syntax (`:start` and `:end`) and have a simple GUI to change them/re-exectue the query.

**Comment by dylanvorster** [comment]
yeah that is actually very useful, but it wouldn't work for php PDO queries /JDBC connections for example where the queries use the colon notation to specify variables. This feature would be awesome because it would allow you to take code directly from your projects, and run it without modification in SQL pro. It would be great if you could either automatically detect such types of parameters, or at least specify which DB driver you are using such as PDO/JDBC etc.. so it knows how to interpolate your variables, to generate the bound variables.

**Comment by abhibeckert** [comment]
I'm only familiar with PHP, where the syntax is `:foo` or `?`.

What syntax do other drivers use?

**Comment by dylanvorster** [comment]
Ive just had a quick look around, I think those are actually the only two I've encountered, and have actually only been able to find. Im not sure how other drivers in languages like c# or various node drivers work, but hey if those are the only two, then its even easier and we can just infer based on colon notation or the question marks.

**Comment by alexisvincent** [comment]
+1
