### ISSUE TITLE
[REQ] Bulk export tables to individual files

### ISSUE THREAD

**Issue by rdpoor** [sequelpro/sequelpro#2523]
Currently, if you select zero tables (i.e. for the entire DB) or more than one table, SequelPro will export everything into a single file.  Being able to incorporate the table name into the filename is a great feature, but it only works if you're exporting a single table.  To export the whole DB, you must select one table, export it, and wait until the export finishes before moving to the next.

As a user, I'd like to be able to export my entire DB -- or selected tables from the DB -- into one file per table with a single operation.

(Added bonus: when saving to compressed formats, you'll get better compression since each file has its own schema, limiting the domain of what needs to be compressed.  And the likelihood of running out of memory goes way down.)

**Comment by dmoagx** [comment]
That's not so simple.
Keep in mind that MySQL is a  **relational** database.
