### ISSUE TITLE
cardinality in structure view incorrect value

### ISSUE THREAD

**Issue by squfrans** [sequelpro/sequelpro#2528]
i have a simple table (`A`) with one primary key (`id`) listing `7` values (1..7).
however the indexes pane shows the cardinality of this index as `6`.

table `B` contains number of rows for every possible value of `A.id`, used as a foreign key:
```
1	279450
2	23158
4	2681167
5	118328
6	14563
7	385
```

this keys cardinality is shown as `2`.

in my understanding cardinality is the number of unique values used, so in both cases i expected to see `7`...

**Comment by dmoagx** [comment]
1. Sequel Pro displays `7` in both cases for me. Perhaps you did not refresh the structure view after adding rows?
2. The output Sequel Pro shows is pretty much a verbatim copy of `SHOW INDEXES FROM table`, so that would rather be a MySQL problem than Sequel Pro.
