### ISSUE TITLE
Latin1 default

### ISSUE THREAD

**Issue by fulldecent** [sequelpro/sequelpro#2530]
I created a database using Sequel and it defaulted to latin1 encoding. People made fun of me because of this. Maybe the default should be utf8.

**Comment by dmoagx** [comment]
If you use the "Default" option Sequel Pro will not specify a charset at all, which means the MySQL server picks the charset based on its defaults (which are shown in parentheses in Sequel Pro).

**Comment by fulldecent** [comment]
Ah, thanks for clarifying. I had thought this meant Sequel Pro default.

**Comment by abhibeckert** [comment]
@fulldecent you can change the default character set by adding the following to `/etc/my.cnf` (create the file if it doesn't exist):

```
[mysqld]
character-set-server=utf8
collation-server=utf8_general_ci
```

You need to restart the server to apply config changes.
