### ISSUE TITLE
BINARY fields defaults to \0

### ISSUE THREAD

**Issue by vicary** [sequelpro/sequelpro#2532]
The current behaviour when you creates a BINARY field without specifying anything results by defaulting the default with the value "\0" (A NULL character).

In many use cases, if not most, people neither expect nor checks a NULL char. They usually go real NULL value, or without any default values when NOT NULL is present.

Could Sequal Pro skips the automatic default value altogether when NOT NULL?

**Comment by dmoagx** [comment]
A `binary` field has a fixed length in MySQL. That length **must** be fully filled or MySQL will automatically add `\0` at the end to fill it. Even if default could be set to 'empty' MySQL would just fill it up – resulting exactly in what is shown as default.

What you are looking for is the `varbinary` type.
