### ISSUE TITLE
Connection through SSH Key keep asking for password

### ISSUE THREAD

**Issue by benjamingauthier** [sequelpro/sequelpro#2535]
Hi,

I'm a new Sequel's user.

I wanted to connect Sequel to my Vagrant Vms. I've used a SSH connection and a SSH Key.

![screen shot 2016-07-19 at 11 13 25 am](https://cloud.githubusercontent.com/assets/5973252/16944867/cc8ec3f4-4da2-11e6-9e64-af14e9e0b622.png)

But when I click to connect, Sequel keep asking for password, which I don't have since I've not allowed SSH connection with password.

![screen shot 2016-07-19 at 11 13 38 am](https://cloud.githubusercontent.com/assets/5973252/16944901/ef803898-4da2-11e6-8723-15abc33239ad.png)

Is it the normal behavior of Sequel ?

I've tested on MySQL Workbench and it works perfectly.

Thanks!

**Comment by dmoagx** [comment]
Sequel Pro only displays the message from the SSH client.
If the SSH client asks for a password even though you specified a key file than that usually means the server rejected the key.

You should try connecting from command line with the same settings.

**Comment by markhamb** [comment]
I am having exactly this same problem connecting to a FreeBSD 10.3 server running MySQL 5.7.18.
If I use terminal, it accepts my public key without prompting for a password, and I can then connect the the mysql server.

**Comment by badroniaimi** [comment]
@benjamingauthier any luck solving this problem?
