### ISSUE TITLE
Sequel Pro crashed after deleting a column

### ISSUE THREAD

**Issue by mheiduk** [sequelpro/sequelpro#2538]
Hi,

after deleting a column from a table with 100 columns, Sequel Pro crashed. The column has been deleted though.

Size of table: 1,7 MB
Number of rows: 1.519
Number of columns: 100
Sequel Pro version: 1.1.2
OSX: 10.11.6

Thanks!

best,
Marc

**Comment by dmoagx** [comment]
https://github.com/sequelpro/sequelpro/wiki/How-do-I-write-a-proper-issue-report%3F

**Comment by dmoagx** [comment]
No response from reporter -> closed.
