### ISSUE TITLE
Grouping Query Favorites

### ISSUE THREAD

**Issue by Mikemacx** [sequelpro/sequelpro#2541]
Always wondered why I can't group my favorite queries into folders or some grouping system. I am keeping a larger and larger list and am hoping a build in the future will include this much needed feature.

**Comment by mbargeron** [comment]
This feature already exists in Sequel Pro.  At the bottom of the connections pane, there's a "folder +" icon which allows you to create a folder, then add whichever connections you want into the folder (see attachment).  I have Sequel Pro 1.1.2 (build 4541), but it has been in several prior versions.

![sequelpro1 1 2](https://cloud.githubusercontent.com/assets/706877/19215426/c5eb04b6-8d5a-11e6-9323-0f327df2850f.png)

![sequelproaddfolder](https://cloud.githubusercontent.com/assets/706877/19215427/c5eb2e46-8d5a-11e6-9d99-feb5b6b500ac.png)

**Comment by Mikemacx** [comment]
Actually I was referring to the list of saved queries. It would be nice to be able group them. My list is getting pretty long.
