### ISSUE TITLE
Avoiding focus removal from table filter textfield when text is cleared

### ISSUE THREAD

**Issue by restyler** [sequelpro/sequelpro#2543]
Sequel Pro is amazing - can't believe I was struggling with workbench ui all this time.
Small issue though: when table filter is cleared by clicking on cross control 
![2e2ca37ac98043ffa2d327e90e49eb49](https://cloud.githubusercontent.com/assets/5793864/17379481/00646392-59c3-11e6-929d-22abe6e4663c.png)
 , I'd expect focus to remain in filter textfield, but it is cleared out completely.

After click: 
![e29f0482ad2f4e2b9d4a623ca88a556a](https://cloud.githubusercontent.com/assets/5793864/17379505/158dd24e-59c3-11e6-8ed9-16af1489e012.png)

Expected after click: 
![5a12e3ad64fc4bbfaa7654ee359e2d0a](https://cloud.githubusercontent.com/assets/5793864/17379501/115eb896-59c3-11e6-9b3a-d97c1f365826.png)

Version: v.1.1.2 4541 (602e11a)

Thank you!

**Comment by dmoagx** [comment]
If your goal is to simply "overwrite" the previous term there are already two options:
a) press cmd+A to select all and start typing to overwrite it
b) if the text cursor is at the end of the input, press cmd+backspace to remove everything

**Comment by dmoagx** [comment]
After checking with 10.9 and 10.11:
This seems to be the default OS behavior: On 10.9 when clicking on the "X" the focus stays, on 10.11 it disappears (same thing with Console.app, Notes.app). We didn't change anything, so this was likely a change done by Apple in OS X.

The search boxes in Xcode behave notably different, though: They don't have the blue focus glow, don't center the label when inactive and don't lose focus when clicking on the "X".

**Comment by restyler** [comment]
it just does not make a lot of sense to me to lose focus, I think it is a bug in OS X commit then.
This is how it always worked for me (on iphone and ipad, where this clear-field pattern got its popularity) - you typically do not clear such a textfield just to clear it - you expect to start new filtering and save a few keystrokes on clearing the field.
