### ISSUE TITLE
Add indication when pasting multiple queries into the Query Editor, to avoid "Run All" / "Run Current" confusion

### ISSUE THREAD

**Issue by squfrans** [sequelpro/sequelpro#2545]
i was trying to copy a smallish table (~2400 rows) from live db
back to staging.  the quick and dirty approach being:

on live:
1. SELECT \* from table;
2. select all results, copy as SQL INSERT

on staging:
1. paste the query
2. run it.

however on 1874 rows were inserted.

i verified the copied insert statement, it had the correct amount
of lines for all 2399 records and it was 325,036 bytes long.

i scrolled down to the bottom of the INSERT query and run the query
again expecting some kind of error, but the remaining 525 rows were
inserted correctly at this point.

is this by design?
am i hitting a string limit in the query editor?  is there a limit
and if yes, how big is it?  would it be possible to have
a visual cue that the limit was crossed?

**Comment by dmoagx** [comment]
When you use "Copy as SQL Insert" with large results, Sequel Pro will create multiple INSERT batches (like with export). You probably selected "Run Current" or "Run Previous" instead of "Run All", so not all queries we executed.

**Comment by squfrans** [comment]
that doesn't seem to be the case.  i saved the query into a file and there is only one INSERT statement.

but i run the same query using the `source` command in `mysql` cli and that explains sequel pro's behaviour, although not mysql's:

```
mysql> \. file_with_query.sql
Query OK, 1874 rows affected (0.19 sec)
Records: 1874  Duplicates: 0  Warnings: 0

Query OK, 525 rows affected (0.07 sec)
Records: 525  Duplicates: 0  Warnings: 0
```

**Comment by squfrans** [comment]
perhaps it might have to do something with the `max_allowed_packet`,
https://dev.mysql.com/doc/refman/5.6/en/server-system-variables.html#sysvar_max_allowed_packet

**Comment by dmoagx** [comment]
I still think you have two queries in the file.
That is what the MySQL output suggests and also how Sequel Pro should behave.
For example I just copied 2000 rows from a random table and Sequel Pro created a new query after ~1300 rows.

`max_allowed_packet` can be a problem, but usually only for very large queries (a single query with multiple MiB in size) and Sequel Pro will display an error message if a query is too large for this limit.

**Comment by squfrans** [comment]
yes, i see the multiple queries now as well.

i guess there is no bug really here, just a confusion on my part.
there is no easy solution to signal to the user that multiple queries were created
or that multiple queries need execution instead of one.

feel free to close the issue.

**Comment by dmoagx** [comment]
I understand why this can be confusing and honestly, if I wouldn't have run into the same issue a few days prior it would probably have taken a lot of time to figure out what had happened.

It makes sense to warn the user, but probably more so when pasting _into_ the query editor than when copying. That way there is no risk that someone may forget it between C&P and the connection between a message like "x queries have been pasted." and the "Run current"/"Run all" buttons would be easier to understand.

We could use an overlay (like the `YRKSpinningProgressIndicator`) that automatically disappears after a few seconds/on user input.

**Comment by diab303** [comment]
what i often do is simply cmd+a, cmd+r - selecting text defaults cmd+r to "run selection" which will run everything after having selected all by pressing cmd+a
