### ISSUE TITLE
"Duplicate Table" only duplicates schema, not the data itself

### ISSUE THREAD

**Issue by mmcev106** [sequelpro/sequelpro#2546]
I'm not sure if this is by design.  I just tried to use this feature like a temporary backup, incorrectly assuming it copied both schema and contents.  I ended up losing my data as a result.  If this feature is intended to only copy schema, would it be appropriate to rename it to something like "Duplicate Schema to new table"?

**Comment by dmoagx** [comment]
![image](https://cloud.githubusercontent.com/assets/5793864/17643974/8cebfc3a-617a-11e6-8f76-70321a77c303.png)
