### ISSUE TITLE
Modify table structure in GUI directly cause table info lose connection when using sphinx

### ISSUE THREAD

**Issue by X-Bird** [sequelpro/sequelpro#2549]
### Reproduce Problem;

1. create table using sphinx connection like this
```mysql
CREATE TABLE `search_source`
(
    id          INTEGER UNSIGNED NOT NULL,
    weight      INTEGER NOT NULL,
    query       VARCHAR(3072) NOT NULL,
    INDEX(query)
) ENGINE=SPHINX DEFAULT CHARSET=utf8 CONNECTION='sphinx://127.0.0.1:9312/source';
```
now the GUI'S Table Info panel likes this. Pay attention on `Create syntax` filed's . It shows the connection using sphinx.
![the first step](https://cloud.githubusercontent.com/assets/1308295/17918582/d7e718ec-69f8-11e6-9843-7de583d1642a.png)

2. Alter table structure to add a column like `name`  through `Structure` panel directly .
![second step](https://cloud.githubusercontent.com/assets/1308295/17918621/3e6a0840-69f9-11e6-9427-2e35921336df.png)

3. Open up `Table Info` panel again. Pay attention on `Create syntax` filed's . It lost the connection ~!
![thrid step](https://cloud.githubusercontent.com/assets/1308295/17918645/73f0a686-69f9-11e6-9286-c3336dca1e1d.png)

### Cause Problems
* query result should return in `name` field will bot return any more instead of value `0`.

### Confirming the problem is this app causes
* create table using sphinx connection like this `add name column in the script`
```mysql
CREATE TABLE `search_source`
(
    id              INTEGER UNSIGNED NOT NULL,
    weight      INTEGER NOT NULL,
    query       VARCHAR(3072) NOT NULL,
    name       VARCHAR(255),
    INDEX(query)
) ENGINE=SPHINX DEFAULT CHARSET=utf8 CONNECTION='sphinx://127.0.0.1:9312/source';

```
* open up `Table Info` panel , it shows the connection still. Now i can get the result should return.
![fourth step](https://cloud.githubusercontent.com/assets/1308295/17918739/30e36738-69fa-11e6-9622-13ca24b15531.png)

**Comment by X-Bird** [comment]
Sequel Pro Version:
1.0.2M Build4135

**Comment by dmoagx** [comment]
1.0.2 is outdated and no longer supported (1.0.2M was never supported anyways).
See https://sequelpro.com/download

**Comment by X-Bird** [comment]
Sorry.
But, after i update sequelpro to v1.1.2 Build 4541 (602e11a).

Same problem still...

**Comment by dmoagx** [comment]
Sphinx is not officially supported by Sequel Pro.

Also you can show the Query console and will see that the query Sequel Pro executes when adding a column looks like
```sql
ALTER TABLE `search_source` ADD `name` VARCHAR(255)  NULL  DEFAULT NULL  AFTER `name`;
```

This is more likely a bug in Sphinx or and incompatibility with their ALTER syntax.

**Comment by X-Bird** [comment]
I made experiment like you said.
Maybe you are right...
