### ISSUE TITLE
Not able to select/un-select D column in Export POP UP on Mac OS X

### ISSUE THREAD

**Issue by sulemanahmed** [sequelpro/sequelpro#2550]
Dear Team - I am facing one GUI issue while un-checking the checkbox in mac os x
Please find attached file
<img width="867" alt="screen shot 2016-08-25 at 11 53 32 am" src="https://cloud.githubusercontent.com/assets/1697783/17959629/f725f102-6aba-11e6-8ad9-c88f5d1accdd.png">

**Comment by dmoagx** [comment]
Duplicate of #1757
