### ISSUE TITLE
Menu: File > Export is not active

### ISSUE THREAD

**Issue by fguillen** [sequelpro/sequelpro#2551]
Some times I find the surprise of this menu to be deactivate (among the Import one).

This is especially painful when I am trying to "export" a very long query that has taken long time to be executed and now I have not way to export the data.

![screen-shot-2016-08-25-at-09 53](https://cloud.githubusercontent.com/assets/23043/17982741/8ffea0a6-6b09-11e6-8b63-d0abaaaffaf8.jpg)
- Sequel Pro v 1.1.2

**Comment by dmoagx** [comment]
The export/import buttons are disabled because you have not yet selected a database.

To export custom query results click on the gear icons at the bottom of the screen (below the result table) and select "Export results"

**Comment by fguillen** [comment]
Thanks for the workaround @dmoagx it worked. 👍 

I have not selected DB because my query is a multi-db query and the dbs are mentioned explicitly in the query.

It is confusing the decision of deactivating the menus.
