### ISSUE TITLE
Specifying encoding for varbinary columns

### ISSUE THREAD

**Issue by digvijay01** [sequelpro/sequelpro#2552]
Question/Feature Request;
Sequel Pro version: 1.1.0.1 (Build 4500)

I am storing a a string as bytes in a table column. The column in 'varbinary'. The bytes are encoded in Base64. Expectedly, when viewing this column in Sequel Pro, only symbols are shown.
Is it possible to specify encoding to use when decoding bytes for varbinary?

**Comment by dmoagx** [comment]
I don't understand you.
Are you storing binary data base64 encoded in a varbinary column? That would be pretty silly.
Or do you want to display binary data as Base64? In that case you should create a `view` and apply the `FROM_BASE64()` MySQL function to the columns (that function only exists in MySQL 5.6.1+).

**Comment by digvijay01** [comment]
Hey, thanks @dmoagx. There was a confusion at my end at how the data was being stored - bytes are not being encoded in base64. The binary data being stored in the column is part string and part random bytes. So any decoding while reading is unlikely to make sense. Thanks.

Closing the issue.
