### ISSUE TITLE
Keyboard shortcuts in the help menu sends to a 404 page

### ISSUE THREAD

**Issue by altryne** [sequelpro/sequelpro#2553]
Specifically this link http://www.sequelpro.com/docs/Keyboard_Shortcuts leads to this page 
![image](https://cloud.githubusercontent.com/assets/463317/17977781/e5ef24f2-6aa7-11e6-95db-10f854a8ca67.png)

**Comment by altryne** [comment]
Should lead to here instead : 
https://sequelpro.com/docs/get-started/keyboard-shortcuts

**Comment by abhibeckert** [comment]
Thanks I'll sort this out today

**Comment by abhibeckert** [comment]
Fixed, along with a dozens of other pages that have moved.
