### ISSUE TITLE
is it possible to setup the favourites via command line?

### ISSUE THREAD

**Issue by lamuria** [sequelpro/sequelpro#2554]
Hi guys,

First of all, props for you because this is a really great software.

I have 1 question, is it possible to setup the favourites via command line? I ask you this because I have some scripts on my projects to boot all the things related to a project, like installing mysql, configure the ssh config file to all the environments etc etc and I would like to automate the creation of sequel pro for each project via command line. is it possible?

Thanks a lot and keep up with the good work 👍

**Comment by abhibeckert** [comment]
Sure, favourites are just stored in `~/Library/Application\ Support/Sequel Pro/Data/Favorites.plist` – which can be edited via `/usr/libexec/PlistBuddy` or any other XML parsing tool.
