### ISSUE TITLE
website is broken

### ISSUE THREAD

**Issue by okigan** [sequelpro/sequelpro#2555]
![screen shot 2016-08-29 at 1 01 39 pm](https://cloud.githubusercontent.com/assets/478302/18065452/c30e52e8-6de8-11e6-836c-04a50588e535.png)

**Comment by dmoagx** [comment]
Works for me.
![bildschirmfoto 2016-08-29 um 22 05 54 494](https://cloud.githubusercontent.com/assets/5793864/18065605/cfa61954-6e34-11e6-95fd-60aef9ce2cf9.png)

What country and what ISP are you using?
Also try opening the Developer tools and measure how long it takes to load http://sequelpro.com/images/connect.png (without cache).

**Comment by okigan** [comment]
usa - california

something up with https setup? see all the unsecure responses:
[image: Inline image 1]

**Comment by okigan** [comment]
[image: Inline image 1]

**Comment by abhibeckert** [comment]
@okigan we can't see images you emailed, can you please upload them directly to the issue tracker?

**Comment by Twiebie** [comment]
It's returning a self-signed certificate, which is marked as unsafe and prevents all the resources from loading over https.

<img width="486" alt="screenshot 2016-08-29 23 19 57" src="https://cloud.githubusercontent.com/assets/903653/18067920/424bc3f0-6e3f-11e6-9ec9-e647d87456b6.png">

<img width="733" alt="screenshot 2016-08-29 23 21 44" src="https://cloud.githubusercontent.com/assets/903653/18067944/5ec441ec-6e3f-11e6-9aad-1bba8b471ecc.png">

**Comment by abhibeckert** [comment]
Yeah, seems to be broken only on IPv6.

A bit hard for me to test, since my ISP doesn't allow IPv6 connections... working on it now.

**Comment by Twiebie** [comment]
If you need any assistance with testing, let me know. I'm on IPv6 at the moment.

**Comment by abhibeckert** [comment]
@Twiebie if you know much about configuring apache that would help? Can we chat over instant message?

**Comment by Twiebie** [comment]
Sure, send me an invite on Skype. Same nickname.

**Comment by abhibeckert** [comment]
this seems to be fixed now. Thanks @Twiebie!
