### ISSUE TITLE
Sidebar table search only does exact substring match

### ISSUE THREAD

**Issue by akholodenko** [sequelpro/sequelpro#2558]
Modern code editors support searching by multiple substrings. The sidebar search for tables is limited to a single substring

Currently, for example, if I have a table **deleted_users**, I can type in **ted_use** and the table name will come up.

The desired functionality is to be able to type in **del use** and get the same results.

**Comment by dmoagx** [comment]
> The sidebar search for tables is limited to a single substring

Wrong.
The sidebar search has full RegEx support.

**Comment by akholodenko** [comment]
Wow - this is great! Didn't realize it was that advanced. Was basing on similar behavior in IDEs.

**Comment by x0xMaximus** [comment]
I feel like this feature should be documented more clearly. Maybe I missed something blatantly obvious on the site, but this wasn't clear and I had to search through the issues to confirm the behavior. It is a huge feature for my uses and wanted to express my gratitude for having standard regex being implemented here

Thanks,
M

**Comment by abhibeckert** [comment]
@x0xMaximus can you think of any way to improve the UI so it's more visible?

**Comment by x0xMaximus** [comment]
@abhibeckert pardon the delay, but I've been thinking about this (and will continue to do so to find an elegant and non-intrusive solution)

**Initial Questions:**

- What is the most common use case for filtering tables? (is it to prevent the user from scrolling, to filter hierarchically-named tables)
- What are the most common use cases for filtering non-exact or multiple matches? Eg. when people do use regex matches, to what degree of complexity is that _really_ needed.
- Is there any filtering or UI indicators of user permissions for table granularity? (I geninually don't know, if I connect to a database with an account that can only read a certain table(s) are they visually indicated as such?). I'm trying to allude to: Does this design challenge have potential crossover with user permissions on a table level?
- What other filtering methods would be preferred by users or should be explored as potential mechanisms? (select boxes, multi-state table text colors to describe matched or unmatched, "my favorites" selection,  etc)

**Option 1:**

When you currently use command key (⌘) to select multiple tables, the filter input remains blank. As shown:

![](http://i.imgur.com/Tu0mtOz.png)

Upon release of the command key, the filter input could be populated with the vertical bar delimited listings of the selected tables, resulting in just the selected tables showing up.

Benefits: 

- Gives a _passive_ indicator of the regex match pattern
- Doesn't add any UI complexity
- Discoverable by "advanced" usage already, so will not further complicate the search functionality for novice users

Drawbacks:

- Upon release of the command key, there is no more ability to append tables to your selection without first clearing the entire search.

**Option 2:**

Change the current text filter to a basic matching strategy, but add a "Enable regex table filtering" option to:

![](http://i.imgur.com/QT8Eezf.png)

Benefits: 

- Complexity of introducing regex to users is "hidden" to advanced users that would be customizing their preferences in the first place
- Doesn't add any design or behavioral complexity to the main application views

Drawbacks:

- It may degrade basic user experiences (hard to say without knowing how most people use the filter input now) 

---------------

**General note:** If a label or input placeholder are used, it would be slightly suggestive that the search behavior is also implemented in the table column search view:
![](http://i.imgur.com/ArcGT0c.png)
 and that can't be done for non-obvious reasons to someone new to databases (which I'd assume is the large portion of your user demographic).

I will keep exploring options for how to best do this, and could be available to help implement it as well.
