### ISSUE TITLE
Table comments are truncated to 60 characters

### ISSUE THREAD

**Issue by robertlee99** [sequelpro/sequelpro#2559]
Hi, I'm using Sequel Pro 1.1.2 Build 4541.

However I enter a table comment, either by running a query or editing it on the Table Info screen, it is always truncated to 60 characters. I believe 2048 characters are allowed in MySQL.

Thanks,

Rob

**Comment by dmoagx** [comment]
Works for me as expected.

Does the `SHOW CREATE TABLE` statement also show the truncated query (is the terminating `';` still visible?
Does the comment contain non-ASCII characters?
If this also happens when you manually execute an `ALTER TABLE` query this is most likely an issue with your server.

**Comment by robertlee99** [comment]
Hi there,

Yes you’re absolutely right, this isn’t a Sequel Pro bug. The database I was using was MySQL v5.1 which has a 60 char limit on table comments. I tested it using a newer version of MySQL (v5.5.3+) and that does indeed work as expected on Sequel Pro with a much larger char limit.

Thanks for your reply. Kind regards,

Rob
