### ISSUE TITLE
If a recent change is remotely rejected the "Reloading" overlay will not go away

### ISSUE THREAD

**Issue by sammarcus** [sequelpro/sequelpro#2560]
Steps to reproduce:
1. Make an edit that is remotely rejected by the database itself
2. Observe the error message that is displayed:

![image](https://cloud.githubusercontent.com/assets/8689264/18325678/3293ef96-74f7-11e6-961f-50a6fdeb2c87.png)

. 3. Dismiss the error with either _Discard changes_ or _Edit row_

. 4. The reloading overlay will not go away and prevents any further actions in the entire window. Note that the cog is still spinning and the application is certainly not hanging, this appears to primarily be a UX issue. The only way to recover from this is to disconnect from the connection by closing the entire window and then reconnect.

**Comment by dmoagx** [comment]
Which version of Sequel Pro?

**Comment by sammarcus** [comment]
So sorry for omitting that!! Version 1.1.2 build 4541 (602e11a)

Thanks, Max

**Comment by sammarcus** [comment]
Hi, just wanted to check in if you had any ideas? Thanks for your advice!

**Comment by dmoagx** [comment]
I've not been able to reproduce this.

**Comment by dmoagx** [comment]
I think this may be the same issue as #2816 

You can try a development build from https://sequelpro.com/test-builds to check if this is fixed.

**Comment by dmoagx** [comment]
No feedback from reporter in > 1 month, closing.
