### ISSUE TITLE
Display Binary Data as Hex does not work for query results

### ISSUE THREAD

**Issue by ClutchRadio** [sequelpro/sequelpro#2564]
OS X Version: 10.11.6 (15G1004)
Sequel Pro Version: 1.1.2 Build 4541 (602e11a)
Database Version: MySQL 5.6.19

<img width="138" alt="screen shot 2016-09-13 at 4 20 56 pm" src="https://cloud.githubusercontent.com/assets/15050618/18489988/145c8d68-79ce-11e6-9aaa-d3cda7e968bd.png">

**Comment by abhibeckert** [comment]
Can you please provide more details?

**Comment by ClutchRadio** [comment]
Absolutely, what specifically are you looking for with detail?  This is during any regular query, the field contains a Hex value that is not returned correctly.  I am not sure what else I can provide that may be of assistance.  I am relatively new to MySQL administration on Mac.

**Comment by abhibeckert** [comment]
Thanks for the extra details.

Displaying binary data as hex currently only works when browsing the content of the table. It doesn't work for custom query results, because MySQL doesn't provide any metadata about the columns returned via your query.

It would be necessary to parse the query you wrote to determine what table and columns are being fetched. Perhaps we could do this with simple queries in a future version.

**Comment by ClutchRadio** [comment]
Is this limited to OS X?  I only ask because I get the same results using other SQL clients on OSX (such as Toad) but I do not get these results on a Windows environment, the actual Hex is returned correctly from the Query.

**Comment by abhibeckert** [comment]
It would be the same for all platforms.

Most likely the windows client you're using does what I suggested – parse the query to guess the data type of each column.

**Comment by nloiselle** [comment]
I wanted to update this, as I was incorrect in my initial request.

Binary columns that contain a GUID are displayed incorrectly, and when selecting items that contain that data you are required to use BinaryToGuid(ColumnName) first. 

The feature request would be to make that happen automatically, so you do not need to specify BinaryToGuid()
