### ISSUE TITLE
Visually Differentiating Connection Windows/Tabs

### ISSUE THREAD

**Issue by mneucollins** [sequelpro/sequelpro#2565]
Hi, I really appreciate this program and all of the work that has gone into it. Thank you so much!
I frequently work with two connections at the same time--one to my local development environment and the other to the production environment. I used to open up two connection windows or tabs simultaneously and work between them. But now I typically only keep one connection window open at a time because sometimes (well, okay,...often) I would get confused about which database I was working on. Luckily I managed to avoid truncating a production table or some similar disaster. But the possibility that I could do that in a fast-paced development environment convinced me to adopt the safer (but more cumbersome) strategy of one window at a time. 
However, I think I could handle two connection windows simultaneously if they were drastically visually distinct. One way to achieve this might be to allow a different color scheme to be specified for each window. I do this in the Mac terminal when I have two ssh connections open, and I have no trouble keeping track of which computer I am working on. Several times, I have found myself digging through the menus of Sequel Pro thinking "there must be a way to do this," but alas, it seems to be a non-existent menu item.
Thanks for your consideration of this request.

**Comment by dmoagx** [comment]
Which version of Sequel Pro?

**Comment by mneucollins** [comment]
version 1.1.2

**Comment by dmoagx** [comment]
You can specify a connection color on the connect screen.
Then go to View > Show Tab bar to always show the tab bar which will have the color of the connection.

This feature will be updated in the next version to stand out even more.

**Comment by mneucollins** [comment]
Yes, I was aware of the tab color. However, that is still pretty subtle, and is not directly attributable to the database screen where my attention is focused while I am working. The table from connection 1 looks exactly the same as the table from connection 2. However, if the tab color affected the background color of the tab that was open, that would be a good signal as to which database I was working in. 
Thanks.

**Comment by dmoagx** [comment]
As I've said, this will be reworked in the next version to be more prominent. If it still doesn't suit your needs then, you are free to open a new issue.

**Comment by abhibeckert** [comment]
> Yes, I was aware of the tab color. However, that is still pretty subtle

@mneucollins please try our nightly builds where this has been tweaked to be less subtle, let us know what you think.

https://sequelpro.com/Sequel_Pro_r50a0f18540.dmg

**Comment by abhibeckert** [comment]
Also, you might consider creating a user with read only access privileges on the production database.

**Comment by RikMaxSpeed** [comment]
I think this is a critical feature - it's what got me looking at the source code here :)
I'd really like the application header or the main label displaying the connection to be coloured like this. The 'show tabs' option is helpful but not optimal. Thanks!
