### ISSUE TITLE
SSH connection prompts for password after upgrade to macOS Sierra

### ISSUE THREAD

**Issue by ldebrouwer** [sequelpro/sequelpro#2570]
When trying to connect to a database through an SSH tunnel, I'm being prompted for a SSH password despite having supplied an SSH key. This started happening after updating to macOS Sierra.

I've verified that I'm able to connect to the server by CLI using the same user and key.

It complains about the permissions on the public key being to open, despite being 600. Switching to the private key resolved the issue.

**Comment by abhibeckert** [comment]
You're the second person to report this, I think it's just a change in how SSH needs to be configured, and switching to the private key is the solution.
