### ISSUE TITLE
Pointer on Pointer of NSString creates an Error

### ISSUE THREAD

**Issue by klein-artur** [sequelpro/sequelpro#2572]
File: SPMySQLResult.h in the SPMySQL Framework

```objective-c
NSString **fieldNames;
```

This line leads to the error Pointer to non-const type 'NSString *' with no explicit ownership

If you change this line to 

```objective-c
NSString *__strong *fieldNames;
```

then it works fine.

I´m working on xcode 8

regards

Artur

**Comment by dmoagx** [comment]
That looks like an ARC error message, but SPMySQL is non-ARC code.

**Comment by Geforceyu** [comment]
@dmoagx,how to use sqmysql in my arc project,thanks

**Comment by dmoagx** [comment]
You should be able to just build SPMySQL as a framework and then include that in your project. The ARC settings for frameworks and applications are independent.

**Comment by Geforceyu** [comment]
i just build SPMySQL as a framework and then include that in your project.But when i #import <SPMySQL/SPMySQL.h> and commanb+b it's error

**Comment by Geforceyu** [comment]
![2017-01-10 7 20 34](https://cloud.githubusercontent.com/assets/6335211/21804416/e1eb8740-d769-11e6-8311-d299d1929dab.png)

**Comment by dmoagx** [comment]
If you only plan to use the compiled .framework the easiest solution would be to just remove the whole `{ ... }` block from the `@interface` in the `.h` files, since that is internal implementation info that only matters when compiling the framework itself.

Otherwise, if you want to dynamically compile the framework with your app the best option would be to hide the `{ … }` blocks:

```objc
@interface SPMySQLResult : NSObject <NSFastEnumeration>
#if !__has_feature(objc_arc)
{
    // …
}
#endif
```

**Comment by Geforceyu** [comment]
thanks a lot,and there has another problem,i just write some code 
    SPMySQLConnection *connection = [[SPMySQLConnection alloc] init];
    [connection setHost:MySQLServerName];
    [connection setUsername:MySQLUserName];
    [connection setPassword:MySQLPassWord];
    [connection setPort:3306];
    BOOL coonected = [connection connect];
    BOOL selectedDB = [connection selectDatabase:MySQLDbName];
when run,error 
dyld: Library not loaded: @executable_path/../Frameworks/SPMySQL.framework/Versions/A/SPMySQL
  Referenced from: /Users/xxx/Library/Developer/CoreSimulator/Devices/C4C663C8-2FBE-40BB-8573-8A30733FF4AB/data/Containers/Bundle/Application/E1D9A310-EC4B-45FE-80BC-925BD8C9E7B3/xxx.app/xxx
  Reason: image not found

**Comment by dmoagx** [comment]
That means you didn't copy the framework to the application output.
In the Xcode settings for the target make sure to include the framework in "Embedded Binaries"
