### ISSUE TITLE
cmd + click table selection resets when performed on inactive window

### ISSUE THREAD

**Issue by Maltronic** [sequelpro/sequelpro#2575]
Using SequalPro 1.1.2 Build 4541 on Mac OS X El Capitan, after selecting several tables using the **cmd + click**

## Steps to reproduce:
1) **cmd + click** to select multiple tables in the left-hand table list (so multiple individual tables are selected / highlighted in blue)
2) click on another unrelated window (e.g. a web browser, finder etc)
3) (while SequalPro is still an inactive window) **cmd + click** on an unselected table from the left-hand table list

The selected list resets and the latest clicked table is the only one selected. Interestingly, the SequalPro window remains inactive.

Using other multi-table selection techniques produces inconsistent results:
- **cmd + shift + click**  
works as expected (activates window and adds new table to selection)
- **shift + click**  
activates SequalPro window but doesn't effect selection till 2nd click

## Current workaround:
Using **cmd + shift + click** instead of **cmd + click** prevents this issue.

**Comment by dmoagx** [comment]
That behavior is consistent with Finder.
I don't see a reason to deviate from standard OS X practices here.

Also there are no [Quallen](https://www.google.de/search?q=qualle&tbm=isch) here.
