### ISSUE TITLE
Feature Req: Delimiter option in csv

### ISSUE THREAD

**Issue by yark** [sequelpro/sequelpro#2576]
In some countries decimal separator is a comma and the value separator is a semicolon. Excel will create CSV files according to locate settings.

There are no option to import such CSV files.
It will bi nice if you add in additional settings pane option to set fields delimiter.

Year;Make;Model;Length
1997;Ford;E350;2,34
2000;Mercury;Cougar;2,38

**Comment by dmoagx** [comment]
The field delimiter can already be configured (on the dialog where the import file is chosen).
Are you perhaps referring to the decimal separator?

**Comment by yark** [comment]
Oh, i found it at additional params. I have expected it in the next dialog.

Thanks.
