### ISSUE TITLE
"time" in exported query result adds a space

### ISSUE THREAD

**Issue by fnl** [sequelpro/sequelpro#2580]
When exporting a query result, and customizing the filename with the "time" option, a space character is appended to the filename after the time itself.

**Comment by Visiluna** [comment]
I would support moving from AM/PM to 24-hour time. This would eliminate the space as well as provide a more standardized time notation.

**Comment by Visiluna** [comment]
My main argument for 24-hour time (aside from standardization) is sort order. If I'm looking at a folder full of `.sql` exports, `db-backup-2017-02-09-9-40 AM` should come before `db-backup-2017-02-09-12-32 PM`, but it doesn't.

Switching to 24-hour time would produce `db-backup-2017-02-09-09-40` and `db-backup-2017-02-09-12-32`, which would result in the correct sort order.

**Comment by abhibeckert** [comment]
@Visiluna export does use a 24 hour clock if you enable that in System Preferences -> Language and Region.
