### ISSUE TITLE
Disable autocomplete backticks unless necessary

### ISSUE THREAD

**Issue by fulldecent** [sequelpro/sequelpro#2582]
Backticks are only necessary in certain circumstances.

However, when using autocomplete, backticks are added every time.

When using autocomplete, please only insert backticks if they are necessary.

**Comment by abhibeckert** [comment]
Backticks can be disabled in Preferences.

However, it's all or nothing. It doesn't know when they're required.

**Comment by Haravikk** [comment]
Defining when back-ticks are required seems a bit tricky; words that commonly require it like `key`, `keys` or `group` can actually work in some queries without back-ticks at all.

Personally I just got into the habit of adding back-ticks to everything 😃

**Comment by fulldecent** [comment]
Would a PR that fixes this be in scope to be merged?
