### ISSUE TITLE
Add offline SQL formatter

### ISSUE THREAD

**Issue by 0x13a** [sequelpro/sequelpro#2584]
please consider a new possible feature related to sql formatter in order to format and prettify the sql query you write in the console, as MySQLWorkbench does.

thanks!

**Comment by kdougan** [comment]
At the very least, add in the option to use an external script to format the text. DBeaver allows for the specification of a python script I wrote to format the provided text and pass it back to the editor.

thanks!

**Comment by dmoagx** [comment]
Sequel Pro has had the possibility to run external scripts for ages and - in fact - the current SQL formatter uses exactly that feature. 

You should take a look at the Bundles.

**Comment by kdougan** [comment]
Thanks @dmoagx! I hadn't even noticed that.
