### ISSUE TITLE
File -> Export should be enabled?

### ISSUE THREAD

**Issue by smitchell** [sequelpro/sequelpro#2585]
I set-up a read-only account in production for reporting; however, when I connect with that account in Sequel Pro the File -> Export menu item is disabled. What permission do I need in order to export my query results?

```
GRANT SELECT ON *.* TO 'read_only'@'%' IDENTIFIED BY '**********';
GRANT SHOW DATABASES ON *.* TO 'read_only'@'%';
GRANT SHOW VIEW ON *.* TO 'read_only'@'%';
```

(Sorry, I was not able to find a user forum to post this question)

**Comment by dmoagx** [comment]
You probably have not selected a db.
This is likely a duplicate of #2551

**Comment by smitchell** [comment]
That is exactly what happened. Since the query joined tables from two different databases using fully qualified table names I did not use the "use [database];" statement. It had nothing to do with the permissions of my read-only account.
