### ISSUE TITLE
Hex editor

### ISSUE THREAD

**Issue by Haravikk** [sequelpro/sequelpro#2594]
Currently when show as hex is enabled for binary columns, it isn't possible to edit them in the UI. I'd like to request the ability to edit fields as hex.

This could be achieved by adding a "hex" option to the standard field/text editor (so we can enable it whenever we like). For binary fields displayed as hex this will be enabled by default, and the editor pre-populated with the hex value. Enabling/disabling the option will hex/unhex the value in the editor.

When a field is saved with this hex mode enabled, it will be checked for invalid (non-hex) characters, and any leading 0x trimmed, before storing the remaining characters via the UNHEX('blah') function or X'blah' notation.

**Comment by tslater** [comment]
I would actually really like in-line editing. About 3 years ago we edited the source of sequel pro to do this, and I'm still using that old build. I can't find the source to contribute though :-(
