### ISSUE TITLE
SequelPro hangs on loading table

### ISSUE THREAD

**Issue by markl181** [sequelpro/sequelpro#2595]
I am designing an application and I noticed one of my queries was running extremely slowly. I ran an explain plan, which never completed (I waited ~10 minutes then force quit). After reopening SequelPro I now cannot view or load one of the tables in the query at all (i.e. can't run a query on it, can't choose it in the viewer, nothing). Every time I do, I see a message that says 'Loading x' (where x is the table name). This immediately hangs the application, and I have to force quit. I am thinking there is some bad data in the table (it shows '~2' rows - I would expect 2) but since the application hangs, I can't even attempt to repair the table. If I click on another table (which has an FK relationship to this table) it also immediately hangs the application, this time with no message at all. I have a hang log but it's too long to paste here. 

Any ideas?

**Comment by markl181** [comment]
I killed mysql and completely rebooted my machine, and I was able to see the data in the table. I added a few use index statements and it appeared to run quicker again. However after a few times running the explain on the query again, the same thing happened.

**Comment by Haravikk** [comment]
This sounds more like you're causing MySQL to hang rather than Sequel Pro itself (it'll hang if mysql takes too long to respond).

Can you give more details about how your database is setup? It seems very strange that you're managing to do this with only two rows; can you provide the query that you're running that triggers the issue, or is it just any `EXPLAIN` query that causes the problem?

**Comment by markl181** [comment]
You may be right that mysql itself is hanging, I'm just surprised it was so easy to do it and that SequelPro didn't eventually respond. 

What I was originally trying to do was join the 2 row table to one that had ~30 rows multiple times in the same query. Since mysql kept dying on this, I rewrote it completely, but it was something like this 

select 
*
from table 
INNER JOIN table2 a ON table.id = a.id AND a.attr_id = 1
INNER JOIN table2 b ON table.id = b.id AND b.attr_id = 2
INNER JOIN table2 c ON table.id = c.id AND c.attr_id = 1

**Comment by Hpegan-PS** [comment]
I'm having the same problem. I tried to import a csv file into my mySQL database and after crashing ~80% into the (slow) import, selecting any database hangs the application. I restarted mySQL, but I might try rebooting too.

**Comment by MartinYounghoonKim** [comment]
@Hpegan-PS Did you solved this problem ?
