### ISSUE TITLE
Programmatically Updating Keychain Passwords

### ISSUE THREAD

**Issue by mbargeron** [sequelpro/sequelpro#2597]
I have written a script to dynamically modify Favorites.plist, based on the database server configurations in our constantly changing environment.  To keep our developers' environments in sync, I iterate through the Favorites.plist, get the password from a secure, remote store and then insert using Mac security:

security add-generic-password -U -T "/Applications/Sequel Pro.app" -s "Sequel Pro : %name (%id)" -a %user@%host/%database -w '%password'

Everything works great... Favorites.plist updates 100% correct every time and the Keychain is properly updated with the password matching the id.  The only problem that I have is that whenever the update script is run, _every_ host prompts with an "Allow" prompt (see attached), which causes a lot of angst from the team.  I thought the "-T" would take care of the issue, but it does not, even though "Sequel Pro.app" shows up in the access control list as it should (see attached).  Is there anything I can do to prevent this from happening every time, short of allowing everyone to see the password, which I obviously do NOT want?

![keychain_attributes](https://cloud.githubusercontent.com/assets/706877/19245856/a76b1378-8ee0-11e6-944f-b7a7c6bdfb52.png)

![keychain_access_control](https://cloud.githubusercontent.com/assets/706877/19245859/ac0bdcd2-8ee0-11e6-985a-76eed366f126.png)

![keychain_annoying_prompt](https://cloud.githubusercontent.com/assets/706877/19245866/b07a6d7e-8ee0-11e6-9cdc-eca8e32c2cd3.png)

**Comment by mbargeron** [comment]
After looking into it today with a few different systems, this has turned out to be a Sierra issue.  My code works fine on El Capitan systems.  I have no idea if they plan on fixing the problem or if it's part of their so-called "security upgrades", but it's not behaving like a rational human being would expect.

**Comment by morganweebly** [comment]
I also have this exact same issue.

**Comment by stuconnolly** [comment]
Closing as I don't believe this is something we can address seeing as it's system behaviour.
