### ISSUE TITLE
Use monospaced font for Display binary data as hex 

### ISSUE THREAD

**Issue by Haravikk** [sequelpro/sequelpro#2598]
The title of this pretty much says it all; currently when binary fields are displayed as hex Sequel Pro uses a non-monospaced font, so although fields may be of a fixed length, the displayed characters vary in width.

For example, I use a lot of `BINARY (16)` fields for UUID's, which result in 32 character hex strings (34 with the leading `0x`), but these don't line up very well in the columns when a lot of certain digits are present, so I'd like to recommend the use of a monospaced font instead such as Monaco or whatever the new default is.

On a related note, but do we really need to show the leading `0x` on fields displayed as hex? They're already highlighted in blue to show that they're different, so it seems like the leading `0x` is somewhat redundant, and just makes the fields wider.

**Comment by dmoagx** [comment]
Preferences > General > Use monospaced fonts

**Comment by Haravikk** [comment]
Thanks for the tip, but like show binary as hex itself this seems to be the all-or-nothing approach; I only really want monospaced hex output, I'm fine with everything else as it is.
