### ISSUE TITLE
New Feature Request - Log File

### ISSUE THREAD

**Issue by yougotnet** [sequelpro/sequelpro#2604]
Sequel Pro is great and I used it a lot!

I really need the ability to turn on a log file and every sql statement I run be logged into that file with a date/time stamp.

There are times when I have several sql statements in the query window and the app might crash or electricity goes out or I close it accidentally and it would be nice to have a log file that I can just open up in a text editor and get whatever I need.

It could be a sql statement I ran weeks or months ago.

**Comment by nikoskip** [comment]
This would be a cool feature.

**Comment by avcommunication** [comment]
This request is very useful.
It might be interesting to save logs of queries also in separate .txt file.
They may be stored as: _**/directory/yyyy-mm-dd.txt**_
If the **directory** could be chosen by the general settings would be great :-)

**Comment by j5ingh** [comment]
Any update on this?

**Comment by ccinelli** [comment]
Just lost all my queries on crash. This would be a great feature.

**Comment by ginachoi** [comment]
this is a great feature to have. Do we have any update on this?

**Comment by zclassy** [comment]
Would love to have this feature! 

It would be really nice to see a log file of all the queries/actions made on a db.

**Comment by r-aamir** [comment]
Looks like its a dead project, time to archive the repo?
