### ISSUE TITLE
Error: Too many arguments to function call, expected 0, have 6

### ISSUE THREAD

**Issue by bpzhang** [sequelpro/sequelpro#2608]
dev environment
macOS Sierra  xcode Version 8.1 (8B62)
build failed 

file : sequelpro/Source/SPSQLParser.m

**Comment by dmoagx** [comment]
Cannot reproduce on a new install of 10.12 with fresh Sequel Pro checkout from Github.

**Comment by bpzhang** [comment]
I have compiled in a previous version, and checkout the code again?

**Comment by bpzhang** [comment]
fixed! I checkout the code again and re-build it ;
