### ISSUE TITLE
Support editing of stored procedures

### ISSUE THREAD

**Issue by Haravikk** [sequelpro/sequelpro#2612]
So I was very pleased to see that Sequel Pro already has some support for stored procedures, in that it can list them in the sidebar under tables, as well as allowing me to show and copy the SQL for the stored procedure.

However, Sequel Pro currently lacks the ability to directly edit a stored procedure, requiring the more awkward workaround of copying into the custom query tab, and adding a drop procedure command (or right-clicking to remove the original).

This works of course, but it feels like all the pieces are there for editing stored procedures, it just needs a query tab-like view from which to do it directly.

This is kind of related to issue #82, however I think a more focused request is appropriate to raise this specific capability.

**Comment by dlbrite** [comment]
I agree, would be of helpful.

**Comment by pedrodevoto** [comment]
+1

**Comment by Ali-Hirani** [comment]
+1

**Comment by jackplan** [comment]
+1

**Comment by IoTPlay** [comment]
+1

**Comment by finferflu** [comment]
This would really be useful for me too, and would free me from the burden of MySQLWorkbench!

**Comment by jordanrw** [comment]
+1 Would love to see this feature!

**Comment by vrkansagara** [comment]
+1 , I would love to see this feature!

**Comment by essell** [comment]
+1, very useful

**Comment by toshidavila** [comment]
Dec 2019 and still no support for this :(

**Comment by tonylee2016** [comment]
> Dec 2019 and still no support for this :(

2020 may
