### ISSUE TITLE
EXC_BAD_ACCESS Crash on El Capitan when changing database

### ISSUE THREAD

**Issue by Marco-Kawon** [sequelpro/sequelpro#2614]
I thought it was fixed with issue #2513, but I am still getting random crashes when changing MySQL Database.

I am using the latest nightly build ...

Crashlog attached
[Sequel Pro_2016-11-09-102627_Marcos-iMac.crash.txt](https://github.com/sequelpro/sequelpro/files/580771/Sequel.Pro_2016-11-09-102627_Marcos-iMac.crash.txt)

**Comment by dmoagx** [comment]
The crash log is from version 50a0f18540 from 2016-06-05, but the fix was added in version d1321478bd from 2016-07-12.

⁉️

**Comment by dmoagx** [comment]
No response from reporter -> closed.
