### ISSUE TITLE
heap-buffer-overflow detected when running with Address Sanitizer on

### ISSUE THREAD

**Issue by willco007** [sequelpro/sequelpro#2618]
If you turn on Address Sanitizer in Xcode and type any character into the query field, you'll get a crash in utf8strlen() on this line u = *(size_t *)(s);.

**Comment by dmoagx** [comment]
Yes, that is technically an out of bounds read.
However this is an intentional optimization made for performance reasons.
The same technique is used by Apple's own code. See: http://stackoverflow.com/questions/25566302/vectorized-strlen-getting-away-with-reading-unallocated-memory
