### ISSUE TITLE
Missing website screenshots (404)

### ISSUE THREAD

**Issue by xmollv** [sequelpro/sequelpro#2625]
Hi there,

i saw that the screenshots in the docs are broken (404). This is just a heads up, nothing critical.

For example: https://sequelpro.com/docs/ref/core-features/relations

![screen shot 2016-12-01 at 09 48 42](https://cloud.githubusercontent.com/assets/8229382/20787312/82260584-b7ab-11e6-8ba2-a02c541bd482.png)

**Comment by josegonzalez** [comment]
The image can be retrieved from archive.org [here](https://web.archive.org/web/20130908040827/http://www.sequelpro.com/assets/screen-shot-2012-08-25-at-12.11.jpg).

**Comment by stuconnolly** [comment]
Being tracked on #2715
