### ISSUE TITLE
Clean labels in sidebar contextual menu

### ISSUE THREAD

**Issue by iBobik** [sequelpro/sequelpro#2633]
In Favorites list in sidebar there is contextual menu on saved connection item. In this menu there are two very similar items "remove" and "rename", so it requires more mental work to decide what it the right option.
![snimek obrazovky 2016-12-16 v 14 31 10](https://cloud.githubusercontent.com/assets/614232/21264496/e3bbbb02-c39c-11e6-9724-141f0616d419.PNG)
I propose to rename "remove" to "delete" (it is also used in the confirm dialog).

**Comment by stuconnolly** [comment]
Thanks for pointing this out. Will be available in the upcoming 1.2 release.
