### ISSUE TITLE
Query history by connection

### ISSUE THREAD

**Issue by albertojgomez** [sequelpro/sequelpro#2641]
Not sure if this is the right way to make a suggestion, so apologies if it's not.

I think  it would be great if the "Query history" would only show the queries made against the current DB connection. Having queries made on other databases doesn't make sense, and sometimes when you perform many queries on other databases, due to the history length, another query that you'd like to keep in history might be lost. I think this would be a nice improvement.

**Comment by justin-souter** [comment]
Hear, hear! I've been wanting this for a while as well.
