### ISSUE TITLE
Icon bug on Sierra

### ISSUE THREAD

**Issue by SergeYurchenko** [sequelpro/sequelpro#2642]
Hello, I have a strange icon bug, see screenshot:
<img width="195" alt="bildschirmfoto 2016-12-29 um 15 55 24" src="https://cloud.githubusercontent.com/assets/9249695/21546487/54a9819a-cddf-11e6-8650-b9ff6042cdba.png">

**Comment by ecnepsnai** [comment]
Duplicate of: https://github.com/sequelpro/sequelpro/issues/2623
