### ISSUE TITLE
Connection form misaligned (sticks to right window border)

### ISSUE THREAD

**Issue by runepiper** [sequelpro/sequelpro#2643]
My login form is a bit off (also when resizing, sticks always to the right).

![bildschirmfoto 2017-01-02 um 14 53 56](https://cloud.githubusercontent.com/assets/4521147/21590341/4f137d3e-d0fb-11e6-997c-2405c85fc679.png)

**Comment by dmoagx** [comment]
This seems to be a regression on #1141 

As a workaround just randomly resize the window to minimum size and bigger again and the form should be centered again.

**Comment by lfolco** [comment]
You mean minimize the window? I'm having this issue and that doesn't seem to work. Neither minimizing the window or reducing the size and resizing works.

**Comment by stuconnolly** [comment]
Duplicate of #2412
