### ISSUE TITLE
"Show MySQL help" shortcut key has collision with "delete"

### ISSUE THREAD

**Issue by HBonsai** [sequelpro/sequelpro#2645]
In macOS, I use control+h as a delete key. However, this shortcut has collision with "Show MySQL help for current word or selection" in Sequel Pro.
I hesitate to change the whole shortcut for a single function in a single app.
Could you remove this shortcut or relocate the function to another shortcut?

**Comment by dmoagx** [comment]
Duplicate of #1974 
You can override it in System Prefs > Keyboard > Shortcuts > App Shortcuts. See https://github.com/sequelpro/sequelpro/issues/1974#issuecomment-54702112

**Comment by HBonsai** [comment]
Thanks a lot! I have found that some users were confused by the same collision.
I have reassigned the function to command+control+h.
