### ISSUE TITLE
'Get involved' page in the documentation contains local file:/// links

### ISSUE THREAD

**Issue by richarddomino** [sequelpro/sequelpro#2654]
Hi,

A few of the links on the 'get involved' page of the docs are broken, as they point to local file:/// URLS.

The links in question are 'check out', 'source code', and 'chat to the developers', all of which are prefixed with file:///Users/abhi/Downloads/.

I couldn't find the docs on Github to submit a pull request, sorry!

Rich

**Comment by stuconnolly** [comment]
Closing in favour of #2715 as it has more info.
