### ISSUE TITLE
Request: 'Autosave active query session to .sql file on Exit' feature

### ISSUE THREAD

**Issue by RgnKjnVA** [sequelpro/sequelpro#2655]
I maintain a long list of sql commands in an sql file for easy reference. Since switching to Sequel Pro from Mysql Workbench after upgrading my Mac to Sierra, I miss the ability to auto-load that sql file upon connecting to a db as opposed to having to manually browse to it and select it. A first-world problem for sure but still. Setting could be simple checkbox setting that toggles opening the Last Used sql file after connections are made. I presume the location of that file is somewhere in memory and can be stored.

Oh! And auto-save on exit. I lost some queries I was working on yesterday because I didn't manually save. Another feature I miss from Workbench.

**Comment by HerbCSO** [comment]
Totally agree, this would be a hugely useful feature to have!

**Comment by mikeher** [comment]
Would be amazing!

**Comment by abhibeckert** [comment]
> Oh! And auto-save on exit. I lost some queries I was working on yesterday because I didn't manually save. Another feature I miss from Workbench.

Did you check the query history?

**Comment by RgnKjnVA** [comment]
Yeah, I found the query history and the query was probably in there as I've used it and it's filtering feature regularly since without incident. Still, I don't understand the unwillingness or inability to store the query session contents between sessions.
