### ISSUE TITLE
Update screenshot on README.md

### ISSUE THREAD

**Issue by fulldecent** [sequelpro/sequelpro#2660]
The README.md screenshot features a prior version of OS X and is visibly dated. Update to show the latest macOS version.

**Comment by abhibeckert** [comment]
The homepage screenshot for https://sequelpro.com/ is current and also retina resolution.

We can just grab one of those.

**Comment by fulldecent** [comment]
I found these

https://sequelpro.com/images/query.png
https://sequelpro.com/images/connect.png

Also, that animation is pretty boss.

**Comment by abhibeckert** [comment]
Also https://sequelpro.com/images/browse.png

**Comment by fulldecent** [comment]
Browse looks better. This is the good one:

https://github.com/sequelpro/sequelpro/pull/2663 <--
