### ISSUE TITLE
Request: "show schema changes query" feature

### ISSUE THREAD

**Issue by id0Sch** [sequelpro/sequelpro#2670]
Hi,
iv'e been using sequel-pro for all of my sql needs other than schema changes.
is it possible to support showing the query that will run when changing table structures?
this will be very helpful when changing schema using an editor and then saving the sql on the db-migration scripts we have.

great product you've got there, been using it for 2 years now!
thanks!

**Comment by dmoagx** [comment]
What about the query console? It contains all executed queries (unless you disabled it in Prefs)

**Comment by id0Sch** [comment]
sweet! i was not aware of that feature at all!
thanks!
