### ISSUE TITLE
Unable to connect to database using SSH

### ISSUE THREAD

**Issue by Lexinek** [sequelpro/sequelpro#2676]
Hi, i have issues with following settings:
<img width="458" alt="screenshot 2017-02-01 02 53 41" src="https://cloud.githubusercontent.com/assets/3995003/22492436/09a5a380-e82a-11e6-85cb-6334435355e3.png">

This is result:
<img width="423" alt="screenshot 2017-02-01 02 53 58" src="https://cloud.githubusercontent.com/assets/3995003/22492439/0d41e68e-e82a-11e6-860f-5729b3bde013.png">

When trying manually in terminal
```
ssh root@jessie -p 4444
mysql -u root
```
Everything works fine.

Version 1.1.2, build 4541 (602e11a).
I tried night build as well, unfortunately same result.

**Comment by danielzilli** [comment]
Exactly the same issue

**Comment by willpower232** [comment]
This reminded me of https://github.com/sequelpro/sequelpro/issues/2153

I believe your issue is caused by the absence of a password. Hope this helps!

**Comment by Lexinek** [comment]
@willpower232 thank you for suggestion, so does it mean i can not use empty password or basically the "NO PASSWORD" login for mysql user when connecting via ssh?

**Comment by abhibeckert** [comment]
@Lexinek we're not sure. It's most likely a configuration issue on the server.

With issue #2153 we asked the person who opened it for more details, and they closed the issue without providing anything.

However what you're seeing is different behavior to some of the testing we did there.

Try testing it manually. I think this should be roughly equivalent to what Sequel Pro is doing:

    ssh -L 4242:127.0.0.1:3306 -p 4444 root@jessie
    
    mysql -u root -P 4242 -h 127.0.0.1 

I would expect that to fail with the same error as you're seeing in Sequel Pro, but you might be able to see more details for debugging.

**Comment by Lexinek** [comment]
@abhibeckert thank you for your reply.

Let me please understand what exactly the code above does. It connects using ssh to `jessie` and redirecting local port 3306 to 4242, afterwards trying to connect to mysql on local port 4242?

If i understood correctly, this might be the issue, because our linux server is behind 2 firewalls and it has only few ports opened (4242 from the example is not one of them).

**Comment by Lexinek** [comment]
@abhibeckert yeah, that's it!!! This is how i fixed (Server version: 10.0.29-MariaDB-0ubuntu0.16.04.1 Ubuntu 16.04)

```sql
CREATE USER 'root'@'127.0.0.1';
GRANT ALL ON *.* TO 'root'@'127.0.0.1';
FLUSH PRIVILEGES;
```

Still the `mysql -u root -h 127.0.0.1` did not work so i tried this:
```sql
USE mysql;
UPDATE `user` SET plugin='' WHERE `user`='root';
FLUSH PRIVILEGES;
```

Now i was able to `mysql -u root -h 127.0.0.1` and Sequel Pro is able to connect.

I would find very useful, if there was exact log, what commands is Sequel Pro running - etc from this log i would be able to see how it is trying to connect to `jessie` using SSH and that it is using `-h 127.0.0.1` in mysql command and would debug it.

Thank you very much!

**Comment by abhibeckert** [comment]
> If i understood correctly, this might be the issue, because our linux server is behind 2 firewalls

That's incorrect. Your firewall should only need SSH port 4444 open. Nothing else is going over the firewall.

The code opens an SSH connection to your server on port 4444, and leaves it open.

Then it creates a new port 4242 on your Mac. Any any traffic sent to this port will be sent over the SSH connection, and then to localhost:3306 on the server.

> I would find very useful, if there was exact log, what commands is Sequel Pro running.

We're not using the command line MySQL client, so there's nothing to log. All you could really do is grab the source code and step through execution line by line in the debugger.

**Comment by Lexinek** [comment]
Thank you @abhibeckert for clarifying, your help was very useful!
