### ISSUE TITLE
Export DB process pauses on loss of focus

### ISSUE THREAD

**Issue by nathanpitman** [sequelpro/sequelpro#2683]
From what I can tell when I'm running a DB export if I defocus the app window after a period the DB export pauses. Once I refocus the window it appears to spring back into life. This is frustrating when pulling a dump of a large DB and switching to some other task in the foreground.

**Comment by dmoagx** [comment]
Which version of Sequel Pro?
Which exact version of OS X?

**Comment by abhibeckert** [comment]
I've recently done exports/imports that take several hours and did not experience the described behaviour.

**Comment by nathanpitman** [comment]
@dmoagx 

MacOS Sierra 10.12.2
Sequel Pro 1.1.2 (Build 4541 602e11a)

**Comment by nathanpitman** [comment]
The DB dump in question is exported using standard memory GZIP compression which gives me a ~400Mb file that unzips to ~4Gb.
