### ISSUE TITLE
It crashes sometimes when I try to edit a column of a row with TEXT datatype

### ISSUE THREAD

**Issue by tresdev** [sequelpro/sequelpro#2684]
It crashes sometimes when I try to edit a column of a row with TEXT datatype, regardless of the size of the text data.
It happens randomly, but quite often. But I couldn't find a specific condition that causes this error.
Hope it would get fixed soon.

**Comment by abhibeckert** [comment]
This is probably related to #2492 and #2622.

We're aware of it but as yet unsure how to fix it. Any additional details you can provide would be great.

**Comment by dmoagx** [comment]
No feedback from reporter in > 1 month, closing.
