### ISSUE TITLE
supplying the error code -67808

### ISSUE THREAD

**Issue by mukeshhub** [sequelpro/sequelpro#2691]
An error occured while trying to update the Keychain item. Repairing your Keychain might resolve this, but if it doesn't please report it to the Sequel Pro team, supplying the error code -67808.

**Comment by stuconnolly** [comment]
Did repairing the keychain work?

Afraid the error code doesn't give us much to go on and given we don't get many keychain issues reported suggested this isn't a widespread problem.

If this continues to occur please raise another issue with more detail including the actions you were performing when it occurred.
