### ISSUE TITLE
NOW with fractional seconds gets wrapped in quotes

### ISSUE THREAD

**Issue by gbartosz** [sequelpro/sequelpro#2692]
This is an issue very similar to #2617.
Assume you have a table with datetime field with fractional seconds:
```
CREATE TABLE `my_table` (
  `my_text_field` varchar(50),
  `my_date_field` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
);
```

When using sequelPro nightly build, when you try to make an insert like this:
![zrzut ekranu 2017-02-15 o 11 32 44](https://cloud.githubusercontent.com/assets/4162881/22970468/93247f84-f372-11e6-8633-97c907684d27.png)
It works fine.

In some situations though, when you need to fill 'my_date_field' manually, it is much more convenient to insert NOW(6) instead of CURRENT_TIMESTAMP(6), like this:

![zrzut ekranu 2017-02-15 o 11 33 19](https://cloud.githubusercontent.com/assets/4162881/22970546/d815eb14-f372-11e6-86de-eb3be751b136.png)

which makes sequelPro escape the 'NOW(6)', and depending on your mysql version or setup, results in an error, or filling my_date_field with '0000-00-00 00:00:00.000000'.

As I mentioned, I realise this issue has been solved, but not yet released for CURRENT_TIMESTAMP(). I hope you can fix it for NOW() as well.

I love sequel Pro! Keep up the good work!

**Comment by dmoagx** [comment]
#2694 needs to be fixed first.
