### ISSUE TITLE
Icon in dark mode in Sierra has a white background

### ISSUE THREAD

**Issue by altryne** [sequelpro/sequelpro#2693]
This makes it look a bit weird in dark mode, example : 
![sequel pro icon](https://cloud.githubusercontent.com/assets/463317/23032227/9978825c-f428-11e6-8f16-916a22b66bb8.gif)

**Comment by dmoagx** [comment]
Duplicate of #2623 

Please search for existing issues before opening new ones!

**Comment by altryne** [comment]
Thanks @dmoagx
I did do a search actually, looked for "dark mode". Will search for broader terms next time as I've see there's about 7 different issues that mention this
