### ISSUE TITLE
Make JSON formatter bundle use the native JSON formatter

### ISSUE THREAD

**Issue by dmoagx** [sequelpro/sequelpro#2695]
618e84a46786b90f731ad963c5e14ea78dcfe58e added a JSON formatter that gets applied to `JSON` type columns automatically.
However we also have a bundle for JSON formatting, which can be used on other types of fields but uses its own formatting code.

We should change the bundle so it will also use the native formatter to reduce duplicate code.

**Comment by AndreSchwarzer** [comment]
I'd also appreciate an option to JSON pretty print a TEXT or JSON column.

Maybe somewhere here:
<img width="344" alt="json" src="https://cloud.githubusercontent.com/assets/6991100/26034075/19e0a50a-38b7-11e7-8c5a-ecec4eece524.png">

**Comment by dmoagx** [comment]
@AndreSchwarzer This already exists: Bundles > Input Field > Format > Toogle JSON Format

**Comment by AndreSchwarzer** [comment]
Hey @dmoagx,

thanks for your reply. But this didn't pretty print my JSON for me. Maybe I'm doing something wrong.

I want to get something like this: 

```JSON
{
    "non_runner": {},
    "final_position": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
    ],
    "results": []
}
```

instead of this `{"non_runner":{},"final_position":[0,0,0,0,0,0,0,0],"results":[]}`

[Screen cap](https://youtu.be/unKWOxvx7GE)

Thanks again.

**Comment by dmoagx** [comment]
Note that there is an error message displayed as a tooltip:
> Input Field is not editable.

**Comment by AndreSchwarzer** [comment]
It is just `'Input field is not     '` 😄 
<img width="138" alt="screen shot 2017-05-14 at 20 07 26" src="https://cloud.githubusercontent.com/assets/6991100/26036618/1d52e976-38e1-11e7-9ee9-eb8028e5170b.png">

When I choose the 'COLUMN' instead of the 'QUERY' tab it works fine. 

🥇 I wanted this feature like forever, but just missed it. Thanks a lot for your hint.

**Comment by ojcitt** [comment]
I love the JSON format in the bundle, but I'm confused as to why it's there and not in the eyeball menu with HTML, PDF, etc. I get that it's pure text, but so is HTML, right?

**Comment by yordis** [comment]
@dmoagx my field is type of JSON so, how could this be `Bundles > Input Field > Format > Toogle JSON Format` the default mode when I am opening that specific field + #2810 ?
