### ISSUE TITLE
Ability to add glow to a window.

### ISSUE THREAD

**Issue by joshuaziering** [sequelpro/sequelpro#2696]
Hello. 

I'd like the window to glow (red?) if I am connected to a certain connection, in this case production. Sometimes I have a few windows floating around with one being dev and one production and I think it would be really handy if I could visually differentiate the windows and keep myself from being an idiot.

Thanks

**Comment by abhibeckert** [comment]
@joshuaziering can you try downloading this test build:

https://sequelpro.com/Sequel_Pro_r50a0f18540.dmg

Save a favourite for your production connection with a red label. This will give you a red bar under the toolbar while that connection is active. Let us know how it works for you.

**Comment by joshuaziering** [comment]
Wow this is great! So fast too. Thank you. When will this be in production??

**Comment by abhibeckert** [comment]
Maybe a month or so.
