### ISSUE TITLE
App Uninstalls After Closing Every Time

### ISSUE THREAD

**Issue by rockoh** [sequelpro/sequelpro#2698]
On macOS Sierra using a MacBook Pro 15" Retina (mid 2014) and every time I go to open the app, it uninstalls. I have to run the install file, then the program installs and opens with all my same settings, but every single time I close out or need to reopen the app, I have to go through the install process.

The app icon is still in my dock at the bottom of my screen, but it seems a bit grayed out and has a question mark over the pancake, and does nothing when I try to open (before installing again,) and only gives me the option to remove form the dock.
<img width="92" alt="sequel pro" src="https://cloud.githubusercontent.com/assets/10214444/23180900/9bcbfd0e-f838-11e6-85c1-e0587198ddde.png">

**Comment by dmoagx** [comment]
1. There is not installation for Sequel Pro. Sequel Pro is distributed as just the app itself. If you had to run any kind of "installer" you were probably scammed by malware
2. Sequel Pro is not even capable of removing itself.

Or maybe you are confused about how apps are installed on a Mac? See
http://apple.stackexchange.com/questions/1171/how-do-i-install-an-application-from-a-dmg-disk-image
https://www.howtogeek.com/177619/how-to-install-applications-on-a-mac-everything-you-need-to-know/
https://www.youtube.com/watch?v=7BrtaOfQVXQ

**Comment by rockoh** [comment]
There's a download file from the website: https://sequelpro.com

The download file gives you a .dmg which is the app, and once you double click it, the app opens up so there's technically no "Installation" but the app seems to lose itself (as seen in the photo from my original post) and I have to click the .dmg to bring up the app and run it. I have figured it out though, since most MacBook installations you drag the app to the Apps folder but it wasn't staying there for some reason, so I was able to drag the app straight to my dock and now it's staying.

**Comment by abhibeckert** [comment]
Glad to hear you've got it sorted.

At some point in the future we may use the Mac App Store for distribution, which would make the process simpler.
