### ISSUE TITLE
Failing to export JSON columns 

### ISSUE THREAD

**Issue by lukepolo** [sequelpro/sequelpro#2706]
I cannot export any tables that have json columns as when trying to import i get the error

` Cannot create a JSON value from a string with CHARACTER SET 'binary'.`

To replicate just create a json column, export, then try to import .

**Comment by abhibeckert** [comment]
This should be fixed in the next release.

Can you please confirm by testing out the latest build from: https://sequelpro.com/test-builds

**Comment by lukepolo** [comment]
worked like a charm, thanks!

**Comment by injeqt** [comment]
I'm also having export/import issues with JSON not escaping apostrophe's (single quotes).

Upon trying to import my exported file, I get these errors:
[ERROR in query 45] Cannot create a JSON value from a string with CHARACTER SET 'binary'.
[ERROR in query 70] Cannot create a JSON value from a string with CHARACTER SET 'binary'.

So I uncheck "Output BLOB fields as hex" and then I get this error:

[ERROR in query 45] You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 's Fullerton at line 17

Either way, I can't seem to import my files exported from the live server.

Any suggestions? Is there a way to get the latest (unsupported) build to see if that will help?

Thanks.

- Hugh

**Comment by DanielsCode** [comment]
Any updates?
