### ISSUE TITLE
New hash : Bcrypt

### ISSUE THREAD

**Issue by Kraddle** [sequelpro/sequelpro#2707]
Hi,
Thanks for your great App.
Is it possible to add a new hash action  ?
action  > hash > **bcrypt**

Regards

**Comment by abhibeckert** [comment]
This can be done with a bundle, using the Bundle Editor.

See the two default hash bundles to see how it works, although they use Ruby which I believe doesn't support bcrypt.

I think PHHP may be the only way to generate bcrypt on a Mac without pulling in third party implementations (and those may have bugs).

**Comment by Kraddle** [comment]
@abhibeckert 
thanks.

Go to the bundle Editor ...
