### ISSUE TITLE
Move Query Editor to the sidebar, treating multiple query editors/opened sql files similar to schema objects 

### ISSUE THREAD

**Issue by dmoagx** [sequelpro/sequelpro#2709]
The idea is to move access to query editor to the sidebar.
Just like the sidebar has a section "Tables" and "Stored Functions" etc. there would be a new section "Queries" (or so).
In that section would be a list of items that can be either
* Unsaved query editor+results views
* SQL files opened from disk

## Motivation 1
The Query tab currently sits in the toolbar besides Structure, Contents, Relations, Triggers and Info.
However those 5 items are actually a context-sensitive group of views on the current schema object. For example, if a stored procedure is selected,no Content or Triggers view is available.
In the future we may want to turn those into a segmented button control (which changes contents depending on selection) since that is a better logical representation of the way those buttons work: The change a view instead of triggering an action.

But "Query" does not fit in there. Query is only dependent on the connection, not on any schema object. Logically speaking it fits in much closer with the schema object list in the sidebar, since it creates a context (assuming an SQL file is opened in the Query view).

## Motivation 2
SP can open and act as an editor for SQL files, but once you have opened them there is **zero** indication that you actually are editing a file in the Query editor as opposed to having "pasted" file contents into the Query editor. This can cause very nasty unwanted data loss.

Having a Query section in the sidebar solves this problem, because it then would be clearly visible that you have opened a file (from the name of the item) and are editing it.
Additionally we can show a dirty indicator (like we do in the connection favorites sidebar) and an option to close a file again (display an "X" icon).

## Motivation 3
This solves the longstanding request for multiple query tabs (#1069). 
While the request is for "tabs", it would probably look rather ugly/confusing if there were two rows of tabs in the UI.
Instead, with a Query section in the sidebar we could simply treat a "Query tab" like an unsaved file. When opening a new connection there would be a single item "Untitled 1" which is the usual query view.
Users could then open a new "Query tab", that would appear as "Untitled 2" in the Query section.

![mockup](https://cloud.githubusercontent.com/assets/5793864/23531323/22b31284-ffa6-11e6-9cf3-d38018fa5f3e.jpg)

**Comment by max-wen** [comment]
+1 👍
