### ISSUE TITLE
Force SequelPro to use IPv4

### ISSUE THREAD

**Issue by gerricom** [sequelpro/sequelpro#2716]
I sometimes have trouble connecting to MySQL servers if their IPv6 isn't correctly configured or if the (poorly configured) company network isn't doing proper IPv6. With SSH there comes the handy `-4` switch. It could be useful, to have this as an (expert) option in SequelPro, too.

Thanks for this super awesome tool, by the way!

**Comment by abhibeckert** [comment]
Can you please try adding this to `~/.ssh/config` for me?

    Host example.org
      AddressFamily inet

That should force ipv4 for all ssh connections to the server, including within Sequel Pro.

See `man ssh_config` for more details.

**Comment by dmoagx** [comment]
This is a highly specific request and the method shown by @abhibeckert should be fine for those who need it.

Also, no feedback from reporter in > 1 month, closing.
