### ISSUE TITLE
Sequel Pro 1.1.2 Build 4541 (602e11a) crashes after using import update function

### ISSUE THREAD

**Issue by felipep** [sequelpro/sequelpro#2720]
Each time wenn I do an import and choose an update sequel pro crashed after updating the last entry, everything gets updated but I have to connect to the DB again.

This is the crash report:
````

Process:               Sequel Pro [50068]
Path:                  /Applications/Sequel Pro.app/Contents/MacOS/Sequel Pro
Identifier:            com.sequelpro.SequelPro
Version:               1.1.2 (4541)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Sequel Pro [50068]
User ID:               501

Date/Time:             2017-03-09 14:27:21.945 +0100
OS Version:            Mac OS X 10.12 (16A323)
Report Version:        12
Anonymous UUID:        ABCFA757-6157-A99A-2F3F-1C53ACC60380

Sleep/Wake UUID:       DBA7CEA5-1465-4247-B58A-D5461B5C0CEA
````

**Comment by dmoagx** [comment]
Please post the full crash report. The snippet you posted contains no useful information at all.

**Comment by felipep** [comment]
@dmoagx, thanks for your answer, I appended the crash reports.

[Sequel Pro_2017-03-09-141552_mb-felipe.crash.txt](https://github.com/sequelpro/sequelpro/files/833266/Sequel.Pro_2017-03-09-141552_mb-felipe.crash.txt)
[Sequel Pro_2017-03-09-141830_mb-felipe.crash.txt](https://github.com/sequelpro/sequelpro/files/833267/Sequel.Pro_2017-03-09-141830_mb-felipe.crash.txt)
[Sequel Pro_2017-03-09-142322_mb-felipe.crash.txt](https://github.com/sequelpro/sequelpro/files/833270/Sequel.Pro_2017-03-09-142322_mb-felipe.crash.txt)
[Sequel Pro_2017-03-09-142722_mb-felipe.crash.txt](https://github.com/sequelpro/sequelpro/files/833268/Sequel.Pro_2017-03-09-142722_mb-felipe.crash.txt)
[Sequel Pro_2017-03-09-143726_mb-felipe.crash.txt](https://github.com/sequelpro/sequelpro/files/833269/Sequel.Pro_2017-03-09-143726_mb-felipe.crash.txt)
[Sequel Pro_2017-03-09-144049_mb-felipe.crash.txt](https://github.com/sequelpro/sequelpro/files/833271/Sequel.Pro_2017-03-09-144049_mb-felipe.crash.txt)
[Sequel Pro_2017-03-09-144313_mb-felipe.crash.txt](https://github.com/sequelpro/sequelpro/files/833272/Sequel.Pro_2017-03-09-144313_mb-felipe.crash.txt)
[Sequel Pro_2017-03-09-144556_mb-felipe.crash.txt](https://github.com/sequelpro/sequelpro/files/833273/Sequel.Pro_2017-03-09-144556_mb-felipe.crash.txt)

**Comment by dmoagx** [comment]
ok, that is #2163.
You can try a development build from https://sequelpro.com/test-builds where it should be fixed already.
