### ISSUE TITLE
SELECT COUNT(1) ...

### ISSUE THREAD

**Issue by 1jefflee** [sequelpro/sequelpro#2722]
On some select queries, selecting a result cell (to copy its value) will result in Sequel Pro freezing, and the errant query "SELECT COUNT(1) FROM ..." to keep running on the database server. I've been yelled at a few times by database admins for this query. So now whenever this happens, I have check the processlist to kill this query.

Why would clicking a result cell result in this happening?

**Comment by dmoagx** [comment]
That query is used by SP to check if a row is uniquely identifiable, which is needed to provide editing functionality.

**Comment by 1jefflee** [comment]
Would it be possible to turn that off? I use Sequel Pro only for select queries (and not editing data). These crashes happen far too often.
