### ISSUE TITLE
[REQ] Can we add a commit button

### ISSUE THREAD

**Issue by GranitBerisha** [sequelpro/sequelpro#2729]
Hi,
sorry if it was posted early ( I searched I didn't found anything ) .

When you  try to edit/copy data in Content tab, sometimes I accidentally delete/edit something and when I press enter the changes are committed and this sometimes cost me with hourly work.
The same thing is in the structure mode.

Would be great to make the changes but to have  a button to commit so we don't accidentally push data to server 
thanks :)

**Comment by abhibeckert** [comment]
This may be something we do as part of version 2.0, or perhaps shortly after the 2.0 release.

#362 details one way of implementing this, although it's a few years old and will be reconsidered.

**Comment by abhibeckert** [comment]
Oh, and I forgot to mention... you should consider connecting with a user that has read only privileges to the database.
