### ISSUE TITLE
UI refresh

### ISSUE THREAD

**Issue by abhibeckert** [sequelpro/sequelpro#2730]
Our current user interface is out of date, we need to consider changes to bring it up to modern standards.

Xcode is probably the best interface to look at for inspiration.

**Comment by inoas** [comment]
I think `Console.app`, `Activity Monitor.app` and `Disk Utility.app` are good sources to get inspiration to bring the look&feel in line with current Mac OS.

**Comment by eivindml** [comment]
`Console.app` is a good one. 
I also think the new `Notes.app` is good for inspiration. It's really enjoyable to use, and the condensed toolbar saves some extra space. 

Let me know if there is some need for some help in creating som mockup sketches.

**Comment by eivindml** [comment]
Facebook has a macOS Sketch resource kit: https://facebook.design/desktopkit
Helpful when wire framing and designing macOS apps.
