### ISSUE TITLE
[REQ] Option to show Run Query tab beneath Content and Structure tabs

### ISSUE THREAD

**Issue by venutip** [sequelpro/sequelpro#2736]
Hey there,

When entering a query in the Run Query tab, I frequently have to switch back and forth between the Run Query, Content, and Structure tabs, either to see the data I'm trying to query, or to grab column names. I realize there is an autocomplete feature for (probably) just this reason, but I prefer not to use it – I found it was either too fast or too slow to autocomplete, and am happier working with it disabled.

As far as a possible UI, I would love to see the Run Query tab in the same space as the Query Status area. I envision it working similarly to the way you can show and hide iTerm with a system-wide hotkey.

Thank you very much for your consideration of this feature!

Best,
Paul

**Comment by dmoagx** [comment]
If it's about the table structure, you can already go to View > Show Navigator which will open an independent window for just the table layout.

**Comment by venutip** [comment]
Oh nice! Thank you, that definitely helps!
