### ISSUE TITLE
Un-/Serialize value in edit view

### ISSUE THREAD

**Issue by Eydamos** [sequelpro/sequelpro#2737]
When I edit a field with type TEXT I have the option to display the data as an image or as hex.
I would like to see an option to unserialize the content of the field.
Often I see data which is either serialized, base64 encoded or a json and it would be nice to see the data in a more readable form.

**Comment by dmoagx** [comment]
What about Bundles?

(Also JSON type columns will automatically be formatted in the next release)

**Comment by Eydamos** [comment]
What do you mean with bundles?

**Comment by dmoagx** [comment]
![bildschirmfoto 2017-03-24 um 21 34 05 363](https://cloud.githubusercontent.com/assets/5793864/24312616/a8333c92-10d9-11e7-9e5a-7cadaab9505f.png)

**Comment by Eydamos** [comment]
I wasn't even aware of this feature. I usually don't look at menus much. If something is not present in the gui itself it basically doesn't exists. xD

Still an unserialize option is missing.
Also is the B64 Decode only in the next version? I don't see it in my version.

**Comment by dmoagx** [comment]
You can download additional Bundles from https://github.com/sequelpro/Bundles

**Comment by Eydamos** [comment]
I finally had time to download and install a bundle and it is working great.
Thanks for the tip
