### ISSUE TITLE
Touch Bar (Control strip) support

### ISSUE THREAD

**Issue by tumispro** [sequelpro/sequelpro#2738]
Support for the new Touch Bar on 2016 MBP's would be cool!
Switching between tabs and / or views could be among the possible applications.

**Comment by abhibeckert** [comment]
I don't have a touch bar, and I'm reluctant to make assumptions about what buttons would actually be useful. There's limited screen space and it should not be wasted.

Should it be used to switch between tabs/connections? Switch between views within each connection? Perform specific actions within a view? I feel these are all good ideas but there may not be enough space to implement all of it.

**Comment by dmoagx** [comment]
Make it possible to execute Bundle commands?

**Comment by Makalco2** [comment]
for me, integration with touch bar to open and switch between already open favorite tabs is the goal.

I'm able to use the following menu item selection with the app BetterTouchTool to launch connection tabs:

> File;Open Recent;sequelpro_ar.spf

where squelpro_ar.spf is a saved connection (Cmd+S) after having created a connection tab.

I am curious if there is an already undocumented method fo switching tabs...either something like (Cmd + N) for next tab or (Cmd +P) for previous, or a menu item that will bring to focus one of the name, open tabs.  If so, BetterTouchTool would likely suffice in making quick integrations to open tabs (and using my method above, it already open tabs right from the touchbar).

![bettertouchtool_sequelpro_connectiontabs](https://user-images.githubusercontent.com/1694428/31551260-9859e5ae-aff9-11e7-8b30-e84e3d686503.jpg)

**Comment by tumispro** [comment]
I'm not sure if it's what you mean, but like in almost every other MacOs app you can switch tabs using Ctrl + Tab (Ctrl + Shift + Tab for prev). You can also switch windows using Cmd + ` (Tilde key, on the left bottom or top of the keyboard).

Being able to switch tabs using the Touch bar would be really cool though! Switching between upper tab views would be useful as well, but due to the limited space only one of those is possible I guess.

Per view - actions are not really useful I guess, except maybe for running queries in the query window.

**Comment by Makalco2** [comment]
Ah, Ctl+tab does switch connections.  I'm going to add it to my BetterTouchTool setup for sequelpro now.  Thx.  You can run any key combination / menu choices / apple script from your custom created buttons on the touchbar using BetterTouchTool.  It's incredible (and i'm not affiliated).  See my custom buttons above: they only took me about 5 mins each (you can choose the icon, text, width, bg color).  This is off topic, perhaps, but the point is: this feature (when sequelpro + touchbar + bettertouchtool are integrated) mostly already exists.  

as i mentioned, launching it doesn't always put the new tab into the existing window...i'm not sure why.

**Comment by tumispro** [comment]
Good to know! I have BetterTouchTool installed, so I will certainly look into it. 

For most actions I rely on the keyboard shortcuts, like CMD + {1 to 6) to switch between the view tabs. It would just be cool to use the Touch Bar for connections (like Safari does for open tabs) so you can immediately jump to a specific one.

**Comment by Makalco2** [comment]
Ug, I have Cmd + <1 - 9> assigned to desktops, that would be cool.  But just as I've added "Next Tab" (see pic) for key combo Cntl+Tab (thank you!), you could manually add buttons for your Cmd + <1-6>...as a stopgap measure at least.

![bettertouchtool_sequelpro_connectiontab-next](https://user-images.githubusercontent.com/1694428/31552681-ce824e38-affd-11e7-882b-def48dd052d8.jpg)

**Comment by tumispro** [comment]
Will try! Thank you too :)

**Comment by ccharlton** [comment]
Button group ideas:
- Views: CMD+1 through 6
- Run Current Query
- Run All Queries
- Refresh Table
- Show/Hide Console
- Help
