### ISSUE TITLE
Window dimensions occasionally resetting at startup

### ISSUE THREAD

**Issue by thecodemill** [sequelpro/sequelpro#2740]
Occasionally (once every 2/3 days) when I launch SP, the window reverts to its default dimensions and I have to manually resize it to my preferred size. I'm not sure why it forgets the preference and I can't provide instructions to reproduce the problem - it just happens. Not a huge issue, but a little irritating after a while.

I'm running SP 1.1.2 Build 4541 on macOS 10.12.3 (Sierra).

**Comment by fulldecent** [comment]
I use SequelPro all the time and have not seen this. Not sure what is going on.

**Comment by lostminds** [comment]
I started seeing this as well when I upgraded to 10.12.3. Get it every time I launch Sequel Pro. On my other machine, still running 10.11 I have the same version of Sequel Pro but never see the problem, so it's probably something to do with macOS 10.12
