### ISSUE TITLE
Copy binary data displayed as hex to clipboard. 

### ISSUE THREAD

**Issue by jim02** [sequelpro/sequelpro#2744]
Right now you can't copy binary data displayed as hex to the clipboard.

**Comment by Lexinek** [comment]
Bump!
It is really frustrating instead of copy+paste i have to write sql queries like this:
```
SELECT email, name_first_name, HEX(customer_id) FROM user;
UPDATE `event` SET customer_id = UNHEX('11E76419D61980888534B7085AB0B19B') WHERE name = 'Test Form';
```

**Comment by dmoagx** [comment]
That feature is available in development builds already https://sequelpro.com/test-builds

**Comment by Lexinek** [comment]
Awesome, i will give it a try and let you know, i had sooo many problems with binary columns so far.

**Comment by Lexinek** [comment]
I feel like im doomed or i am doing something wrong - i can not find the option to display binary data as hex. Im attaching screen how does my data look like:
<img width="285" alt="screenshot 2017-07-10 21 50 14" src="https://user-images.githubusercontent.com/3995003/28036850-d4d33b64-65b9-11e7-803c-72f559a8635f.png">

Here is the SQL dump of the table:
```sql
CREATE TABLE `user` (
  `id` binary(16) NOT NULL COMMENT '(DC2Type:customer_user_id)',
  `customer_id` binary(16) DEFAULT NULL COMMENT '(DC2Type:customer_id)',
  `email` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '(DC2Type:identity_email)',
  `currency` varbinary(255) DEFAULT NULL COMMENT '(DC2Type:money_currency)',
  `uid` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '(DC2Type:identity_uid)',
  `name_first_name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '(DC2Type:person_first_name)',
  `name_last_name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '(DC2Type:person_last_name)',
  `public_key` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `private_key` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `IDX_8D93D6499395C3F3` (`customer_id`),
  CONSTRAINT `FK_8D93D6499395C3F3` FOREIGN KEY (`customer_id`) REFERENCES `customer` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
```

**Comment by dmoagx** [comment]
![bildschirmfoto 2017-07-10 um 22 06 16 567](https://user-images.githubusercontent.com/5793864/28037581-195c61a0-65bc-11e7-9215-e0d79e31f710.png)

**Comment by Lexinek** [comment]
@dmoagx i love you, this is awesome! Thank you very much! :+1:
