### ISSUE TITLE
Show connection name in tab

### ISSUE THREAD

**Issue by e7o-de** [sequelpro/sequelpro#2748]
Would be really helpful to see the current connection name in a tab instead of the database name. Database name is visible a few pixels above in the select box anyway (and obvious by looking at the table list below) while the connection is well-hidden (only in title bar of the window, and that text is far away on macOS). Having always the issue with several identical databases (like test, dev, production ...) but named the same in the tab.

**Comment by abhibeckert** [comment]
What exactly do you mean by "connection name"? You mean the name of the favourite?

I often open several tabs to the save favourite, each with a different database selected.

**Comment by dmoagx** [comment]
You can give your connections different colors and then select `View > Show Tab Bar` to show it even with only a single connection.

**Comment by e7o-de** [comment]
Oh, yes, I guess I mean the favorite name :) Yeah, if you're opening a different tab per database, I can understand the purpose of seeing the db name (so, it would be required in addition). That might be a drawback of the select box without having a real tree (like e.g. MySQL Workbench has), which could be another feature request btw ...

The color solution is not really satisfying. Not motivated to remember a lot of color codes and getting confused when being at a collegues's computer or so ...

**Comment by abhibeckert** [comment]
> Actually, I noticed that this feature is already in for inactive tabs, so it just needs to be there for the active tab as well.

Yeah, the tab title is currently "Connection Name/Database Name/Table Name", with some conditions that determine which of those three are currently displayed, based on which tab is currently active.

I think we should either make all three permanently visible or add a preference to do so.

**Comment by corymalcolmtaylor** [comment]
If this will help me remember at a glance  that my connection tab is on a live production db and not just my local dev db then please do this soon.  In fact maybe even add some more options to basically scream the difference at me like maybe custom font settings defined in the favorites - maybe even a different color scheme for dev and production - a warning popup when making db changes etc.
