### ISSUE TITLE
Various console improvements

### ISSUE THREAD

**Issue by e7o-de** [sequelpro/sequelpro#2749]
Figured out that I'm missing the most functionality in the console. Just some random thoughts ...

* Only 100 queries saved is too less (especially if it is logging the program-internal queries as well)
* Not dockable to the main window
* A result column (like "4 rows modified" or so) would be great
* Same for runtime/execution time (like "10.02 sec")
* To re-use a query, I have to use the clipboard (and overwrite content there), a menu entry like "send to editor" or even a drag&drop functionality to it would be helpful as well. I mean, yes, I noticed the history available in the editor, but if the console would contain more features, I would use it ;)

**Comment by MrAnderson7** [comment]
Query History has a save feature, it would be complete with a restore from file feature.
Would be nice to <right>-<click> and be able to delete a Query History entry, I sometimes update / add passwords and need to delete it from the history list.
Thanks Great product.

**Comment by sammarcus** [comment]
Would also be fantastic if the calendar date was shown in the timestamp (with the time of day).
