### ISSUE TITLE
Nightly builds broken

### ISSUE THREAD

**Issue by dmoagx** [sequelpro/sequelpro#2752]
Current nightly builds are broken.
For example in https://sequelpro.com/builds/Sequel-Pro-Build-93239c0688.zip (most recent build) the `Info.plist` contains those mismatched entries:
```xml
<key>CFBundleShortVersionString</key>
    <string>Snapshot r93239c0688</string>
<key>NSHumanReadableCopyright</key>
    <string>Snapshot build for revision 93239c0688</string>
<key>SPVersionLongHash</key>
    <string>bab93f8ce74a6644c9a3d8a50fa26230f127c550</string>
<key>SPVersionShortHash</key>
    <string>bab93f8</string>
```

Also looking at the disassembly of that build:
```asm
                     -[SPTableTriggers dealloc]:
;(...)
00000001000f4733         mov        rax, qword [_OBJC_IVAR_$_SPTableTriggers.prefs]
00000001000f473a         mov        rdi, qword [rbx+rax]                        ; argument "instance" for method _objc_msgSend
00000001000f473e         lea        rax, qword [_SPUseMonospacedFonts]
00000001000f4745         mov        rcx, qword [rax]
00000001000f4748         mov        rsi, qword [0x100257198]                    ; @selector(removeObserver:forKeyPath:), argument "selector" for method _objc_msgSend
00000001000f474f         mov        rdx, rbx
00000001000f4752         call       r14                                         ; _objc_msgSend
```

That line was removed in 4d450e171fe429a5375c95dbc8372853a910c681
which should have been before 93239c0688, but after bab93f8ce74a6644c9a3d8a50fa26230f127c550

**Comment by dmoagx** [comment]
num | commit   | SPVersion*Hash
----|----------|-----------------
5165|93239c0688|bab93f8
5164|          |
5163|          |
5162|          |
5161|          |
5160|          |
5159|          |
5158|          |
5157|          |
5156|          |
5155|          |
5154|4d450e171f|bab93f8
5153|4a18651715|9ed7fd7
5152|dd468908b3|9ed7fd7 (that is 5147)
5151|30d36cbe3b|30d36cb - OK
5150|d37a2f490a|d37a2f4 - OK
5149|bab93f8ce7|bab93f8 - OK

**Comment by abhibeckert** [comment]
Something in our localization script appears to have caused uncommitted changes in the git checkout.

The script then failed to detect a failed checkout operation, and continued building commit `bab93f8ce74a6644c9a3d8a50fa26230f127c550` for all builds after that one.

I've updated the build script to make sure we're on the right revision it's working fine now, although I'm not sure what happened with the localization script.
