### ISSUE TITLE
Regression: Single Tab Bar Color

### ISSUE THREAD

**Issue by russianryebread** [sequelpro/sequelpro#2753]
In the last nightly, the background color of a single tab is no longer respected.  Since I use the color to visually let me know which server (production / staging) or which user (limited / root) - it's pretty important.

<img width="280" alt="screen shot 2017-03-30 at 12 52 20 pm" src="https://cloud.githubusercontent.com/assets/747085/24516187/c8885d66-1547-11e7-9470-301fe0480288.png">

As soon as I open another tab, the color returns:

<img width="276" alt="screen shot 2017-03-30 at 12 52 29 pm" src="https://cloud.githubusercontent.com/assets/747085/24516196/cfb6c618-1547-11e7-9e19-98454fd36854.png">

This was working up to the last nightly release that I downloaded: 5169 (db0335a)

**Comment by fulldecent** [comment]
@russianryebread Please clarify, you state that db0335a works but at the time you opened this issue that was the latest commit.

Could you please help identify which is the last GOOD commit and which is the first BAD commit?

**Comment by russianryebread** [comment]
Hi William!

The build based on db0335a was the very first time that I noticed the bug.  Perhaps I wasn’t clear, when I said:

> This was working up to the last nightly release that I downloaded: 5169 (db0335a <https://github.com/sequelpro/sequelpro/commit/db0335a4eff4a04d044f5cbd617fd21c0bec8932>)

Looking closely, it appears that the regression happened in commit 044789b, since 2aad505 is the last release where the tab bar stays colored correctly in a singular context.

Please let me know if I can help with anything else!

-Ryan

**Comment by abhibeckert** [comment]
Basically the tab bar is the wrong colour when it's hidden. Should be a simple fix and I'll do it on friday if possible.

Until then, I suggest using `View -> Show Tab Bar` to make it visible even when there's only a single tab.

**Comment by russianryebread** [comment]
> Until then, I suggest using View -> Show Tab Bar to make it visible even when there's only a single tab.

This works splendidly in the interim.  Somehow I totally missed that option.  Thank you!

**Comment by russianryebread** [comment]
Thank you so much, @abhibeckert.  It works perfectly! 👍
