### ISSUE TITLE
Allow SSH options

### ISSUE THREAD

**Issue by claudiu-cristea** [sequelpro/sequelpro#2760]
Right now we cannot add SSH options to the connection. Only user, host, port are available. But i would like to connect in this manner:

```bash
ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no user@example.com
```

But how?

**Comment by dmoagx** [comment]
You can configure a custom SSH client in Preferences. Just set that to some script that passes through all arguments and adds your custom ones.

**Comment by claudiu-cristea** [comment]
@dmoagx, true, but that will apply to all connections as I understand. But a need a per-connection configuration.

**Comment by dmoagx** [comment]
Well, you could still apply a filter based on hostname in a custom script.

The other option would be to just define a custom host in your `.ssh/config` file and set that in SP:
```
Host foobar
  Hostname real.host.name
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
```

**Comment by claudiu-cristea** [comment]
@dmoagx, again, I agree but it's not friendly. Sequel Pro is a nice GUI to MySQL. So, the users that are using it don't like to go to command line, or change system config files. Otherwise they would simply use the `mysql` command line client, not a GUI :)

**Comment by dmoagx** [comment]
This is too far out of scope.
I don't see a large enough userbase who have to configure custom SSH options and those who have such needs and know what options to configure will also be able to edit their ssh config.
Also Sequel Pro relies on the system-provided OpenSSH so the available options differ by OS version and we don't want to get involved with all that stuff.
