### ISSUE TITLE
Can't fix row default as other row default error prevents changes being saved

### ISSUE THREAD

**Issue by conorhub** [sequelpro/sequelpro#2762]
I have two timestamp rows with defaults of 0000-00-00 00:00:00 that are causing issues with this default not being valid in strict mode. From reading, I understand the error now but am having a hard time correcting it.

If I try and change the default of `problem1` row I get an error saying that it couldn't save as the default for `problem2` row is not valid. And vice-versa.

While the error is, from one perspective, a valid one, I can't see any way to correct it using Sequel Pro (v1.1.2) given that I can only correct one default at a time, unless reverting to code and bypassing the value of Sequel Pro for table editing.

**Comment by dmoagx** [comment]
> given that I can only correct one default at a time, unless reverting to code

Yes, that's how it is. Sequel Pro can only process one change to the table structure at a time.

**Comment by conorhub** [comment]
It may be my naivety with mySQL then. I thought there'd be some manner to alter a row default without mySQL running a validity check on other rows they weren't in the query. If there's not, then I can understand that Sequel Pro is stuck with this quirk. I've fixed in the mean time by running a query with code that changes both defaults at once, but I turn to Sequel Pro for times when I'm trying to avoid code.
