### ISSUE TITLE
Bastion mode for connecting to an internal db server

### ISSUE THREAD

**Issue by lamguy** [sequelpro/sequelpro#2763]
I'm not sure if the feature is there already. Here is the procedure I want to produce:

`[A: local host] -> [B: jump host] -> [C: target host] => [D: MySQL host]`

Is it possible?

**Comment by dmoagx** [comment]
What is target host supposed to be if it is not MySQL?

**Comment by lamguy** [comment]
A: my local mac machine
B: a Ubuntu in AWS with minimum installation
C: a Ubuntu in AWS with Nginx and PHP to run our website to connect to D
D: a Ubuntu in AWS with MySQL

**Comment by abhibeckert** [comment]
It's possible as long as you have SSH access to B and C and are reasonably familiar with Terminal.

You need to log into B from Terminal:

    ssh b-user@b-host.com

Then create an SSH tunnel to C (assuming MySQL is running on port 3306, and 3307 is an available unused port. You can change 3307 to another number if needed):

    ssh -L 3307:mysql-host:3306 c-user@c-host.com

This will create an active tunnel which you can cancel by closing the terminal window or pressing `ctrl-c`. As long as the tunnel is open, within Sequel Pro you can connect like this:

<img width="463" alt="screen shot 2017-04-12 at 08 39 31" src="https://cloud.githubusercontent.com/assets/266088/24933806/a6386454-1f5b-11e7-9bd6-1768b5c1a241.png">

**Comment by dmoagx** [comment]
Why not simply connect from B to D?
That much is already possible with Sequel Pro...

**Comment by abhibeckert** [comment]
@dmoagx I use this all the time where A is a dynamic IP address (such as my phone's LTE connection) and the C/D datacentre has a hardware firewall configured to whitelist B's IP address.

**Comment by dmoagx** [comment]
But if D (mysql server) has whitelisted B (jump server) there is no need to go via C (app server).
And connecting to D from B can already be configured in the SP GUI.

**Comment by abhibeckert** [comment]
In my case D can only be reached from C. No other server has access.

**Comment by lamguy** [comment]
@abhibeckert Hi Abhi, it worked! Thanks for your response. However, it doesn't look like the tunnel could be cancelled unless I have to exit out C. When I was in B and ran this command `ssh -L 3307:mysql-host:3306 c-user@c-host.com`, it just connected me to C without an "active" (use CTRL + C to cancel) tunnel. At this point, I assume that the tunnel is open not just for me because anyone was able to connect to the db through that port until I exit out.

Is there anyway to make that tunnel available to my shell session only?
