### ISSUE TITLE
Missing icon in Dock and Applications folder

### ISSUE THREAD

**Issue by AlexMcDermott** [sequelpro/sequelpro#2764]
The icon appears when the app is stored on the desktop but when the app is moved to the Application folder the icon changes to the blank application icon:
<img width="394" alt="screen shot 2017-04-13 at 12 07 43 pm" src="https://cloud.githubusercontent.com/assets/10878648/24987184/d8909016-2041-11e7-8114-fdc1a042983e.png">
The same issue happens on the dock:
<img width="170" alt="screen shot 2017-04-13 at 12 08 53 pm" src="https://cloud.githubusercontent.com/assets/10878648/24987207/ff719158-2041-11e7-92a4-ce6e5fe620a6.png">

**Comment by smg111** [comment]
any fix for this? having the same issue in 2019  😀
