### ISSUE TITLE
debug1: read_passphrase: can't open /dev/tty: Device not configured

### ISSUE THREAD

**Issue by bbrandtlv** [sequelpro/sequelpro#2771]
Hey, i'm having a problem using SSH to connect to droplet.
I can connect to the server using terminal SSH.
I can connect using terminal with same command sql pro trying to connect. But sql pro itself cannot connect. 
I think it cannot open file for readying. 
I gave full permission to both files (private and public) but still getting same problem.
Again, I can connect using terminal instead of sqlpro, but I really need it to work.
Please advice. 
I googled and tried different solutions, nothing worked. 
chmod 600 ~/.ssh/id_rsa not working as well.

Thanks

**Comment by giskard22** [comment]
I think I'm having the same problem. Only difference might be that I am not trying to use key pair. I am manually entering the password. I can connect just fine using a regular ssh command in bash.

Here's the debug output from the connection attempt:

```
Used command:  /usr/bin/ssh -v -N -S none -o ControlMaster=no -o ExitOnForwardFailure=yes -o ConnectTimeout=10 -o NumberOfPasswordPrompts=3 -o TCPKeepAlive=no -o ServerAliveInterval=60 -o ServerAliveCountMax=1 my-username@server-name -L 53842:127.0.0.1:3306

OpenSSH_7.4p1, LibreSSL 2.5.0
debug1: Reading configuration data /Users/my-username/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Control socket " none" does not exist
debug1: Connecting to server-name [10.199.1.226] port 22.
debug1: fd 5 clearing O_NONBLOCK
debug1: Connection established.
debug1: identity file /Users/my-username/.ssh/id_rsa type 1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/my-username/.ssh/id_rsa-cert type -1
debug1: identity file /Users/my-username/.ssh/id_dsa type 2
debug1: key_load_public: No such file or directory
debug1: identity file /Users/my-username/.ssh/id_dsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/my-username/.ssh/id_ecdsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/my-username/.ssh/id_ecdsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/my-username/.ssh/id_ed25519 type -1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/my-username/.ssh/id_ed25519-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.4
debug1: Remote protocol version 2.0, remote software version OpenSSH_5.3
debug1: match: OpenSSH_5.3 pat OpenSSH_5* compat 0x0c000000
debug1: Authenticating to server-name:22 as 'my-username'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: diffie-hellman-group-exchange-sha256
debug1: kex: host key algorithm: ssh-rsa
debug1: kex: server->client cipher: aes128-ctr MAC: umac-64@openssh.com compression: none
debug1: kex: client->server cipher: aes128-ctr MAC: umac-64@openssh.com compression: none
debug1: SSH2_MSG_KEX_DH_GEX_REQUEST(2048<3072<8192) sent
debug1: got SSH2_MSG_KEX_DH_GEX_GROUP
debug1: SSH2_MSG_KEX_DH_GEX_INIT sent
debug1: got SSH2_MSG_KEX_DH_GEX_REPLY
debug1: Server host key: ssh-rsa SHA256:76lDddQKoIFB23uFGPicO/x+uazPuBcD6puP/3urWI8
debug1: Host 'server-name' is known and matches the RSA host key.
debug1: Found key in /Users/my-username/.ssh/known_hosts:50
debug1: rekey after 4294967296 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey after 4294967296 blocks
debug1: Skipping ssh-dss key /Users/my-username/.ssh/id_dsa - not in PubkeyAcceptedKeyTypes
debug1: SSH2_MSG_SERVICE_ACCEPT received
|-----------------------------------------------------------------|
| This system is for the use of authorized users only.            |
| Individuals using this computer system without authority, or in |
| excess of their authority, are subject to having all of their   |
| activities on this system monitored and recorded by system      |
| personnel.                                                      |
|-----------------------------------------------------------------|
debug1: Authentications that can continue: publickey,gssapi-keyex,gssapi-with-mic,password
debug1: Next authentication method: publickey
debug1: Offering RSA public key: /Users/my-username/.ssh/id_rsa
debug1: Authentications that can continue: publickey,gssapi-keyex,gssapi-with-mic,password
debug1: Trying private key: /Users/my-username/.ssh/id_ecdsa
debug1: Trying private key: /Users/my-username/.ssh/id_ed25519
debug1: Next authentication method: password
debug1: read_passphrase: can't open /dev/tty: Device not configured
debug1: permanently_drop_suid: 501
debug1: Authentications that can continue: publickey,gssapi-keyex,gssapi-with-mic,password
Permission denied, please try again.
debug1: read_passphrase: can't open /dev/tty: Device not configured
debug1: permanently_drop_suid: 501
debug1: Authentications that can continue: publickey,gssapi-keyex,gssapi-with-mic,password
Permission denied, please try again.
debug1: read_passphrase: can't open /dev/tty: Device not configured
debug1: permanently_drop_suid: 501
debug1: Authentications that can continue: publickey,gssapi-keyex,gssapi-with-mic,password
debug1: No more authentication methods to try.
Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
```

**Comment by bbrandtlv** [comment]
Mine is little bit different.
```

Used command:  /usr/bin/ssh -v -N -S none -o ControlMaster=no -o ExitOnForwardFailure=yes -o ConnectTimeout=10 -o NumberOfPasswordPrompts=3 -i /Users/alexela/.ssh/id_rsa -o TCPKeepAlive=no -o ServerAliveInterval=60 -o ServerAliveCountMax=1 root@45.32.187.113 -L 51298:127.0.0.1:3306 -L 51299:45.32.187.113:3306

OpenSSH_6.9p1, LibreSSL 2.1.8
debug1: Reading configuration data /Users/alexela/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug1: Control socket " none" does not exist
debug1: Connecting to 45.32.187.113 [45.32.187.113] port 22.
debug1: fd 3 clearing O_NONBLOCK
debug1: Connection established.
debug1: identity file /Users/alexela/.ssh/id_rsa type 1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/alexela/.ssh/id_rsa-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_6.9
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.2p2 Ubuntu-4ubuntu2.1
debug1: match: OpenSSH_7.2p2 Ubuntu-4ubuntu2.1 pat OpenSSH* compat 0x04000000
debug1: Authenticating to 45.32.187.113:22 as 'root'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: server->client chacha20-poly1305@openssh.com <implicit> none
debug1: kex: client->server chacha20-poly1305@openssh.com <implicit> none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:pY+RIp/ICHHVh5l0V6/xNfnEV4KIKK/JVq0v
debug1: Host '45.32.187.113' is known and matches the ECDSA host key.
debug1: Found key in /Users/alexela/.ssh/known_hosts:7
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: SSH2_MSG_SERVICE_REQUEST sent
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey,password
debug1: Next authentication method: publickey
debug1: Offering RSA public key: /Users/alexela/.ssh/id_rsa
debug1: Authentications that can continue: publickey,password
debug1: Next authentication method: password
debug1: read_passphrase: can't open /dev/tty: Device not configured
debug1: permanently_drop_suid: 501
debug1: Authentications that can continue: publickey,password
Permission denied, please try again.
debug1: read_passphrase: can't open /dev/tty: Device not configured
debug1: permanently_drop_suid: 501
debug1: Authentications that can continue: publickey,password
Permission denied, please try again.
debug1: read_passphrase: can't open /dev/tty: Device not configured
debug1: permanently_drop_suid: 501
debug1: Authentications that can continue: publickey,password
debug1: No more authentication methods to try.
Permission denied (publickey,password).
```

**Comment by dmoagx** [comment]
Please try the steps I explained in https://github.com/sequelpro/sequelpro/issues/2619#issuecomment-261588771 and post the results.

**Comment by bbrandtlv** [comment]
SHELL=/bin/bash
TERM=xterm-256color
USER=root
SUDO_USER=alexela
SUDO_UID=501
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.poFnfUSe0X/Listeners
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
USERNAME=root
MAIL=/var/mail/root
PATH=/Users/alexela/.composer/vendor/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/alexela/.android-sdk-macosx/platform-tools/:/Users/alexela/.nexustools
PWD=/Users/alexela/Desktop
SHLVL=1
SUDO_COMMAND=/bin/sh /Users/alexela/Desktop/test.sh
HOME=/Users/alexela
LOGNAME=root
LC_CTYPE=UTF-8
SUDO_GID=20
_=/usr/bin/env

**Comment by dmoagx** [comment]
Wait... Why is the command running as root via sudo?

**Comment by bbrandtlv** [comment]
dont know

**Comment by dmoagx** [comment]
`sudo` explains why it doesn't work for you. `sudo` removes the necessary environment variables for auth to work in Sequel Pro.

Still, this should not happen and Sequel Pro has no internal code to run sudo.
Which version of Sequel Pro are you using?
Which OS X version?

Please run this command and post the results:
```
/usr/bin/codesign -v /Applications/Sequel\ Pro.app
/usr/bin/codesign -d -vv /Applications/Sequel\ Pro.app
/usr/bin/shasum -a 256 -b /Applications/Sequel\ Pro.app/Contents/MacOS/Sequel\ Pro
```

**Comment by bbrandtlv** [comment]
Sql 1.1.2 - 4541
OS 10.11.6

Used command:  /usr/bin/ssh -v -N -S none -o ControlMaster=no -o ExitOnForwardFailure=yes -o ConnectTimeout=10 -o NumberOfPasswordPrompts=3 -i /Users/alexela/.ssh/id_rsa -o TCPKeepAlive=no -o ServerAliveInterval=60 -o ServerAliveCountMax=1 root@45.32.187.113 -L 59814:127.0.0.1:3306 -L 59815:45.32.187.113:3306

OpenSSH_6.9p1, LibreSSL 2.1.8
debug1: Reading configuration data /Users/alexela/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug1: Control socket " none" does not exist
debug1: Connecting to 45.32.187.113 [45.32.187.113] port 22.
debug1: fd 3 clearing O_NONBLOCK
debug1: Connection established.
debug1: identity file /Users/alexela/.ssh/id_rsa type 1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/alexela/.ssh/id_rsa-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_6.9
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.2p2 Ubuntu-4ubuntu2.1
debug1: match: OpenSSH_7.2p2 Ubuntu-4ubuntu2.1 pat OpenSSH* compat 0x04000000
debug1: Authenticating to 45.32.187.113:22 as 'root'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: server->client chacha20-poly1305@openssh.com <implicit> none
debug1: kex: client->server chacha20-poly1305@openssh.com <implicit> none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:pY+RIp/ICh5sI6l0V6/xNfnEV4KIKK/JVq0vySXg
debug1: Host '45.32.187.113' is known and matches the ECDSA host key.
debug1: Found key in /Users/alexela/.ssh/known_hosts:7
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: SSH2_MSG_SERVICE_REQUEST sent
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey,password
debug1: Next authentication method: publickey
debug1: Offering RSA public key: /Users/alexela/.ssh/id_rsa
debug1: Authentications that can continue: publickey,password
debug1: Next authentication method: password
debug1: read_passphrase: can't open /dev/tty: Device not configured
debug1: permanently_drop_suid: 501
debug1: Authentications that can continue: publickey,password
Permission denied, please try again.
debug1: read_passphrase: can't open /dev/tty: Device not configured
debug1: permanently_drop_suid: 501
debug1: Authentications that can continue: publickey,password
Permission denied, please try again.
debug1: read_passphrase: can't open /dev/tty: Device not configured
debug1: permanently_drop_suid: 501
debug1: Authentications that can continue: publickey,password
debug1: No more authentication methods to try.

**Comment by giskard22** [comment]
The command from the comment on #2619 worked fine. Output pasted below. I also checked the environment for anything SSH-related, and got only `SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.fX9XC1Kjms/Listeners`.

Here's the interesting part: I have a second computer with, as far as I can tell, the same versions of everything and Sequel Pro is able to connect to the server just fine. Connection settings appear identical.

```
$ /usr/bin/ssh -v -S none -o ControlMaster=no -o ExitOnForwardFailure=yes -o ConnectTimeout=10 -o NumberOfPasswordPrompts=3 -o TCPKeepAlive=no -o ServerAliveInterval=60 -o ServerAliveCountMax=1 ssh-user@ssh-host -L 7653:127.0.0.1:3306
OpenSSH_7.4p1, LibreSSL 2.5.0
debug1: Reading configuration data /Users/local-user/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Connecting to ssh-host [10.199.1.226] port 22.
debug1: fd 5 clearing O_NONBLOCK
debug1: Connection established.
debug1: identity file /Users/local-user/.ssh/id_rsa type 1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/local-user/.ssh/id_rsa-cert type -1
debug1: identity file /Users/local-user/.ssh/id_dsa type 2
debug1: key_load_public: No such file or directory
debug1: identity file /Users/local-user/.ssh/id_dsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/local-user/.ssh/id_ecdsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/local-user/.ssh/id_ecdsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/local-user/.ssh/id_ed25519 type -1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/local-user/.ssh/id_ed25519-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.4
debug1: Remote protocol version 2.0, remote software version OpenSSH_5.3
debug1: match: OpenSSH_5.3 pat OpenSSH_5* compat 0x0c000000
debug1: Authenticating to ssh-host:22 as 'ssh-user'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: diffie-hellman-group-exchange-sha256
debug1: kex: host key algorithm: ssh-rsa
debug1: kex: server->client cipher: aes128-ctr MAC: umac-64@openssh.com compression: none
debug1: kex: client->server cipher: aes128-ctr MAC: umac-64@openssh.com compression: none
debug1: SSH2_MSG_KEX_DH_GEX_REQUEST(2048<3072<8192) sent
debug1: got SSH2_MSG_KEX_DH_GEX_GROUP
debug1: SSH2_MSG_KEX_DH_GEX_INIT sent
debug1: got SSH2_MSG_KEX_DH_GEX_REPLY
debug1: Server host key: ssh-rsa SHA256:76lDddQKoIFB23uFGPicO/x+uazPuBcD6puP/3urWI8
debug1: Host 'ssh-host' is known and matches the RSA host key.
debug1: Found key in /Users/local-user/.ssh/known_hosts:50
debug1: rekey after 4294967296 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey after 4294967296 blocks
debug1: Skipping ssh-dss key /Users/local-user/.ssh/id_dsa - not in PubkeyAcceptedKeyTypes
debug1: SSH2_MSG_SERVICE_ACCEPT received
|-----------------------------------------------------------------|
| This system is for the use of authorized users only.            |
| Individuals using this computer system without authority, or in |
| excess of their authority, are subject to having all of their   |
| activities on this system monitored and recorded by system      |
| personnel.                                                      |
|-----------------------------------------------------------------|
debug1: Authentications that can continue: publickey,gssapi-keyex,gssapi-with-mic,password
debug1: Next authentication method: publickey
debug1: Offering RSA public key: /Users/local-user/.ssh/id_rsa
debug1: Authentications that can continue: publickey,gssapi-keyex,gssapi-with-mic,password
debug1: Trying private key: /Users/local-user/.ssh/id_ecdsa
debug1: Trying private key: /Users/local-user/.ssh/id_ed25519
debug1: Next authentication method: password
ssh-user@ssh-host's password:
debug1: Authentication succeeded (password).
Authenticated to ssh-host ([10.199.1.226]:22).
debug1: Local connections to LOCALHOST:7653 forwarded to remote address 127.0.0.1:3306
debug1: Local forwarding listening on ::1 port 7653.
debug1: channel 0: new [port listener]
debug1: Local forwarding listening on 127.0.0.1 port 7653.
debug1: channel 1: new [port listener]
debug1: channel 2: new [client-session]
debug1: Requesting no-more-sessions@openssh.com
debug1: Entering interactive session.
debug1: pledge: network
Last login: Mon May  8 13:50:17 2017 from
```

**Comment by dmoagx** [comment]
@giskard22 When using the command from #2619 there is a file `userenv.txt` created on your Desktop. Please also post that.

Also, are you saying that when you enable the custom SSH client setting, the connection succeeds and when you don't, it fails?

**Comment by giskard22** [comment]
Oh, it wasn't clear which comment on the other issue you had intended. I saw the one "dmoagx commented on Nov 18, 2016" that gave an equivalent of the SSH command generated by Sequel Pro and I ran that manually. It worked.

Never mind though; I discovered a problematic keychain entry. Sorry, thanks for the assistance.

**Comment by dmoagx** [comment]
Issue state unclear, no response from user for > 4 weeks -> closed.

**Comment by vcardillo** [comment]
I'm having this problem. Sometimes it works, and sometimes it doesn't.

**Comment by simplenotezy** [comment]
I experience this problem as well, after adding a passphrase to my ssh key

**Comment by datashock** [comment]
Make sure your ssh private key has permission 600.

**Comment by lorenzznerol** [comment]
I have the same problem when using `ssh -Tv git@gitlab.com` in a Dockerfile, using a passwordless private key to authenticate.

```
#17 1.196 debug1: Authentications that can continue: publickey,keyboard-interactive
#17 1.196 debug1: Next authentication method: publickey
#17 1.196 debug1: Trying private key: /root/.ssh/id_rsa
#17 1.196 debug1: read_passphrase: can't open /dev/tty: No such device or address
```

I have created an image from the working code before the `ssh -Tv git@gitlab.com`. Then I ran a container and executed the bash in it. When I then tried to `ssh -Tv git@gitlab.com` in the bash, I was asked for the password:

Enter passphrase for key '/root/.ssh/id_rsa':
debug2: bad passphrase given, try again...
Enter passphrase for key '/root/.ssh/id_rsa':
debug2: bad passphrase given, try again...
Enter passphrase for key '/root/.ssh/id_rsa':
debug2: no passphrase given, try next key

This is a try with "", '' and just pressing enter, they all do not work.

But that would explain why it asks for /dev/tty: at some point, it needs the user to enter a password - even when the private key is passwordless, and entering the right (=empty) password does not even solve it.
