### ISSUE TITLE
Import freezes on Max OS X Sierra (10.12.4)

### ISSUE THREAD

**Issue by skumarbf** [sequelpro/sequelpro#2772]
Trying to import a large dataset (more than 6 GB of data) and the process is stuck after the screen to perform field mapping. The application is unresponsive, uses no CPU and memory usage remains constant.  I am on version 1.1.2 of Sequel Pro and OS X Sierra (10.12.4). The same version of Sequel Pro imports the exact same file just fine on El Capitan (10.11.6).

**Comment by dmoagx** [comment]
Please go to Activity Monitor, select Sequel Pro an from the gear icon in the toolbar select "Sample Process" and post the result.

Also please go to Console and search for any messages from Sequel Pro.

**Comment by dmoagx** [comment]
No response from reporter for > 4 weeks -> closed.
