### ISSUE TITLE
can't access to the download page!

### ISSUE THREAD

**Issue by WhiteInk404** [sequelpro/sequelpro#2773]
![Uploading image.png…]()

**Comment by abhibeckert** [comment]
The screenshot you posted doesn't seem to have uploaded?

**Comment by daleconboy** [comment]
Google appears to have flagged the download domain as a malicious site.

This is what I get from the download buttons on https://sequelpro.com/download

![screenshot_169](https://user-images.githubusercontent.com/1026036/28558424-b7711fec-70c6-11e7-85ae-411baa1c516f.jpg)

**Comment by dmoagx** [comment]
We use GitHub for release hosting.
Someone else has probably (ab)used GitHub to host some kind of malware and the browsers automatically blocked the whole domain.
Not much we can do about it, GitHub has to take action.

**Comment by dmoagx** [comment]
Btw you can check the download with this SHA256 hash:
```
7b34fd63c13e9e9ca4f87d548241ff9df9a266b554af23549efd7be006f387c6  sequel-pro-1.1.2.dmg
```

(I took that from a copy of the file I downloaded in Nov '16)

**Comment by dmoagx** [comment]
OK, GitHub says this is fixed now and the OP never replied to the initial problem in the first place -> closed.
