### ISSUE TITLE
Import CSV / Enum

### ISSUE THREAD

**Issue by fulldecent** [sequelpro/sequelpro#2774]
When using Import From Clipboard feature with CSV.

If the field type is ENUM then the drop down should allow you to select from those values and free form text input should be disallowed.

![screen shot 2017-04-25 at 9 30 33 am](https://cloud.githubusercontent.com/assets/382183/25388039/ad58836a-299a-11e7-877c-b3d07b893f31.png)

**Comment by dmoagx** [comment]
Having the enum values as drop down options would be OK.

I don't think free input should be disallowed, since it can produce valid enum values, e.g. by concatenating other CSV column values or SQL expressions.
