### ISSUE TITLE
the count raw is wrong

### ISSUE THREAD

**Issue by mayyang0913** [sequelpro/sequelpro#2785]
show in picture red rectangle, there are some different count number , is confused me. please check this. thanks. 

<img width="629" alt="sequel_count_bug1" src="https://cloud.githubusercontent.com/assets/9766624/25996104/154b79d6-3748-11e7-8bd4-89c5646f7214.png">

<img width="594" alt="bug2" src="https://cloud.githubusercontent.com/assets/9766624/25996103/150ce55e-3748-11e7-9981-25e2af3071ce.png">

**Comment by dmoagx** [comment]
That is expected behavior with InnoDB tables and the tilde (~) in front of the number indicates that it is an approximation.
For a detailed explanation see: http://stackoverflow.com/questions/11926259/why-is-the-estimated-rows-count-very-different-in-phpmyadmin-results/11926300
