### ISSUE TITLE
collation_connection defaults to utf8_general_ci instead of utf8mb4_unicode_ci

### ISSUE THREAD

**Issue by roelmonnens** [sequelpro/sequelpro#2786]
Hey,

I'm working with sequel pro 1.1.2 Build 4541 (602e11a) and I'm connecting to MySql 5.6.16
The server is configured to use utf8mb4.
The default encoding of sequel pro is UTF-8 Full Unicode (utf8mb4).

When I run the query:

```
SHOW VARIABLES WHERE Variable_name LIKE 'character\_set\_%' OR Variable_name LIKE 'collation%';
```

I get this result:
![resultset_wrong](https://www.dropbox.com/s/fd2mwrd6rq9z43e/Screenshot%202017-05-15%2015.57.53.png?dl=1)

you can see that collation_connection is utf8_general_ci. This is wrong.

After running this query:
````
set names utf8mb4 COLLATE utf8mb4_unicode_ci
````

you can see that my resultset is correct:
![resultset_correct](https://www.dropbox.com/s/as8wu3kgjdqoba3/Screenshot%202017-05-15%2015.54.50.png?dl=1)

Is it possible to force sequel pro to use utf8mb4_unicode_ci when choosing the default encoding?

**Comment by dmoagx** [comment]
> The default encoding of sequel pro is UTF-8 Full Unicode (utf8mb4).

No, Sequel Pro by default uses `utf8`. However it will automatically switch to the encoding of the currently selected table.

> you can see that collation_connection is utf8_general_ci.

Your screenshot says `utf8*mb4*_general_ci`.

**Comment by roelmonnens** [comment]
Ok,  
I made a typo but utf8mb4_general_ci should be utf8mb4_unicode_ci. This to have *better* sorting algorithm

**Comment by onassar** [comment]
Any updates here? Running into this issue as well.
