### ISSUE TITLE
Code Style: Merge all classes spread over multiple files back into a single file

### ISSUE THREAD

**Issue by dmoagx** [sequelpro/sequelpro#2789]
I propose to change our source code so that all classes that are spread over multiple files are merged back into a single file.
AFAIR the splitting was done to make working with the code easier by separating different tasks and reducing the size of the .m files, which can get quite large.
However, I've come to the conclusion, that this has actually the opposite effect. My arguments:
* It's not obvious: The main class `@interface`/`@implementation` does not hint that there might be more to the class in some other file, therefore it is **very** easy to overlook.
* Slows down development: When changing existing code, one of the main tasks is to check where it is used, how it is used and with what other code there are interdependencies. Spread out classes make this difficult, because you have to additionally check for their existence.
* They just hide a bigger issue instead of solving it: Some of our classes were so large, that they were split to multiple files. Now they may appear smaller, but they are just as large as before (or even larger because of the necessary boilerplate definitions) and the real problem, whether a class maybe needs to be rearchitectured, is not addressed by this change.  
* Bad code Insight: Imagine you want to find out where an ivar is used. Your only option in Xcode is to do a string search. But if you only search in the current file, you may miss code of the class in other files, so you have to resort to searching in the whole project. With some generic/often reused variables you will be buried in results which you then have to sift through (and Xcode doesn't even allow to persist results / hide false matches). This again slows down development and is demotivating. 
* Not future proof: Ivars of objects are (in most cases) an implementation detail that should not be part of it's public interface and therefore I plan to move them to the `@implementation` once we go "Modern ObjC"-only. Having the implementation spread out over multiple files makes this either impossible or significantly more awkward (have not checked that yet). 
* Demotivating to new developers: If you want to start helping a project, you'll most likely choose a problem that you can easily get an understanding of. Huge methods and strong coupling between components work directly against that, because the problem starts to get dragged around all over the place instead of being locally contained.

**Comment by abhibeckert** [comment]
I agree, we should do this.
