### ISSUE TITLE
view encoding not work.

### ISSUE THREAD

**Issue by Orz-Li** [sequelpro/sequelpro#2790]
database encoding utf-8 unicode.
view encoding utf-8 unicode bmp not work...
view encoding utf-8 full unicode not work...
view encoding utf-8 unicode via latin1 not work...
origin data is chinese.

**Comment by dmoagx** [comment]
Please be more specific.
* Post the `CREATE TABLE` statement
* Post the expected and actual values
* Post the output of `SELECT HEX(column) FROM table` for the affected field

**Comment by dmoagx** [comment]
No response from reporter for > 4 weeks -> closed.
