### ISSUE TITLE
Open db by url?

### ISSUE THREAD

**Issue by MACscr** [sequelpro/sequelpro#2794]
Is there anyway for me to create a custom url scheme so I can launch a server/db connection by url? I have to connect to a few new databases every day and and it would be nice not to have to create a bookmark for each one. They all use the same ssh key and database name, they just have a different hostname.

I am running Sequel Pro on my OSX system.

**Comment by tschoffelen** [comment]
See #2366, which implements a fix, but is based on a branch that isn't ready to be merged yet.

**Comment by tschoffelen** [comment]
This is actually already possible. Sequel Pro registers the URL scheme `mysql://`, so for example typing `open mysql://root:test@localhost:3306` into your terminal should open Sequel Pro and connect to that database.

**Comment by MACscr** [comment]
you didn't specify the database name there anywhere in your example and I need to be able to use an ssh connection. None of my mysql servers are remotely accessible directly. =/

**Comment by tschoffelen** [comment]
Database name is supported by adding `/databasename` to the path.

SSH however (and private keys as well) are not supported as there is not really a neat way to do that in a URL I think. 

If you have a suggestion about the URL format I could look at implementing it in a PR, but I don't have much hopes for that getting merged, since it might be considered to just add confusion.

**Comment by danquah** [comment]
I've tried to get ```open mysql://root:test@localhost:3306``` under Sierra, but all I get is 
```
The file <current path>/mysql://root:test@localhost:3306 does not exist
```

(I've tried with various valid credentials and hostnames)
Can anyone confirm that the URL handler is actually working under Sierra?

**Comment by dmoagx** [comment]
This is currently only available in the development builds, not in 1.0.2

**Comment by danquah** [comment]
1.1.2 right?

**Comment by dmoagx** [comment]
Yes, got that mixed up

**Comment by danquah** [comment]
👍  Looking forward to next release then, thanks for the quick reply.

**Comment by VMBindraban** [comment]
Is there a ETA for this release?

**Comment by iainnash** [comment]
+1

**Comment by MarkGrenville** [comment]
Is this available now? I get the same error. 
The file mysql:/root:test@localhost:3306 does not exist.

**Comment by Ryangr0** [comment]
Still getting this error. Is there an ETA for this to make it into master?
