### ISSUE TITLE
cannot save connection as favorite

### ISSUE THREAD

**Issue by rsperl** [sequelpro/sequelpro#2801]
When I enter connection details and choose "add to favorites," nothing happens. I can see in keychain that an entry is added named "Sequel Pro : local (-1078656729335075452)" and that sequal pro has access to it. But nothing shows up in my list of favorites.

I tried deleting the sequel entries from keychain, restarting sequel pro, and it still does not save favorites.

Sequal Pro version: snapshot build 5201 (c1930af) - tried stable release first, then the latest snapshot, and had the same problem.
macos: Siera 10.12.6 Beta (16G8c)

**Comment by dmoagx** [comment]
Never seen that. I would assume this is a bug/change in 10.12.6.

**Comment by rsperl** [comment]
Awesome - the console gave it away. The log message said it couldn't open the Data directory, which turned out to be a broken link to a folder in Dropbox. I removed the link, created the directory, and Sequel Pro worked just fine. Thanks for pointing me to the logs ;)
