### ISSUE TITLE
Icon Makes Me Hungry

### ISSUE THREAD

**Issue by pudge** [sequelpro/sequelpro#2802]
This is not a joke issue.

The icon is beautiful.  But it literally makes my mouth water, and I leave it in the Dock.  So I had to manually change the icon.

It would be nice if you changed it to something less appetizing.

<img width="512" alt="messages image 1640710262" src="https://cloud.githubusercontent.com/assets/15170/26458440/1ceff632-4128-11e7-9b3b-9c6545bebe36.png">

**Comment by dmoagx** [comment]
Use the development snapshots from https://sequelpro.com/test-builds if you want a less "appetizing" icon.

We have no plans to change the icon.
