### ISSUE TITLE
How Do I allow location services for sequel pro

### ISSUE THREAD

**Issue by Loganpi** [sequelpro/sequelpro#2803]
I need to know how to allow location services for sequel pro

**Comment by tschoffelen** [comment]
Why would you need to do that?

**Comment by Loganpi** [comment]
It says in the error box when I don't sign in correctly, to make sure
location services are turned on.

On Mon, May 29, 2017 at 3:56 PM, Thomas Schoffelen <notifications@github.com

**Comment by dmoagx** [comment]
Sequel Pro doesn't even have any code that uses location services.
Either you are talking about a different software or you have possibly somehow installed a malware version.

**Comment by Loganpi** [comment]
ok, thank you

**Comment by Loganpi** [comment]
here look at this:

**Comment by dmoagx** [comment]
> here look at this:
> 
> On Tue, May 30, 2017 at 6:51 PM, Logan Foster <...> wrote:

at what?

**Comment by Loganpi** [comment]
Can you see an image?

**Comment by dmoagx** [comment]
No, those will be removed when replying by e-mail. You'll have to post those on GitHub directly.

**Comment by dmoagx** [comment]
No response from reporter for > 4 weeks -> closed.
