### ISSUE TITLE
Delete Database invariably hangs the application.

### ISSUE THREAD

**Issue by gsafcik** [sequelpro/sequelpro#2804]
I'm copying this from https://github.com/sequelpro/sequelpro/issues/1116 (which was originally [here](https://code.google.com/archive/p/sequel-pro/issues/1116)). This still happens yet the issue was closed. Why does a drop database hang the entire application (especially for the length of time it does)?

Update for my own information:

**What steps will reproduce the problem?**

See steps in original ticket (below)

**What version of Sequel Pro are you using?**

Sequel Pro 1.1.2  Build 4541 (602e11a)

What version of MySQL are you connecting to on the server? Connecting to different MySQL servers. MySQL 5.6.34 through MAMP (Local env) and AWS RDS.

**Please provide any additional information below.**

A drop table should not hang the entire application. Instead, let the user open new connections, etc and continue working within the application. It would be understandable if that connection tab hangs (the one you're deleting the DB from). Dropping DBs in CL is WAY quicker and size of the DB shouldn't really matter for the application.

Original ticket information:

> **What steps will reproduce the problem?**
> 
> Select a database.
> Delete Database from the Database menu.
> Watch the spinning beach ball of death.
> What is the expected output? I expect the database to drop, which does complete, and the application to return, which it doesn't.
> 
> What do you see instead? The spinning beach ball of death.
> 
> What version of Sequel Pro are you using? Verified on OSX 10.6.5/6/7/8 with Sequel Pro 0.9.8 and 0.9.9, and OSX 10.7 with Sequel Pro 0.9.9.
> 
> What version of MySQL are you connecting to on the server? 5.1.57, compiled through macports.
> 
> **Please provide any additional information below.**
> There are a few other 'application doesn't respond after long running query' which may or may not be related. In the command line mysql app, drop database statements take around 5 seconds to complete. My databases range in size from 10 to 500 megs, and they all contain around 200 tables.

**Comment by dmoagx** [comment]
#1116 was about Sequel Pro _never_ responding again after deleting a database (and the issue was closed because the poster never responded with the requested information).

If your problem is only, that Sequel Pro hangs while the operation is in progress, see: #710

**Comment by gsafcik** [comment]
@dmoagx I guess I missed that detail in the original post. Also, I guess you could put it under #710 but doesn't seem to be only for large operations (as #710 suggests). Do what you will with this issue but know this is more of a usability issue (larger and medium/smaller tasks as well).
