### ISSUE TITLE
Unwanted backslashes in Db name column when applying GRANT options for a table which name contains underscores

### ISSUE THREAD

**Issue by arno1979** [sequelpro/sequelpro#2815]
I just noticed that when I use the "Users" panel to GRANT rights for user for a certain table if the name of the database contains underscores (e. g. 'example_database_name') the row in the mysql.Db table will look like this:
`%	example\_databse\_name	username	Y	Y	Y	Y	Y	Y	Y	Y	Y	Y	Y	Y	Y	Y	Y	Y	Y	Y	Y`
I think this is unwanted and points to a faulty escaping of the database name. If I manually remove the backslashes from the field Sequel Pro has no problem identifying the entry when looking at the rights for the specific user again. I can't remove or edit the rights though.

Thanks
Arno

**Comment by dmoagx** [comment]
> The _ and % wildcards are permitted when specifying database names in GRANT statements that grant privileges at the database level. This means, for example, that if you want to use a _ character as part of a database name, you should specify it as \_ in the GRANT statement, to prevent the user from being able to access additional databases matching the wildcard pattern; for example, GRANT ... ON `foo\_bar`.* TO ....

https://dev.mysql.com/doc/refman/5.7/en/grant.html

**Comment by arno1979** [comment]
Ok, thanks!
