### ISSUE TITLE
Warn user when making a non-SSL connection to an SSL-enabled server

### ISSUE THREAD

**Issue by frewsxcv** [sequelpro/sequelpro#2819]
Secure connections should be the default. Unsecure connections should be opt-in, not the other way around.

<img width="155" alt="screen shot 2017-06-15 at 10 52 40 am" src="https://user-images.githubusercontent.com/416575/27187381-1392d4be-51b9-11e7-8313-89f0719c00a2.png">

**Comment by dmoagx** [comment]
By default MySQL installations have TLS/SSL disabled (AFAIR) and even if they do have it enabled, unless you also have selected a CA certificate to verify against (which you MUST do manually as `libmysqlclient`, which Sequel Pro uses, does not use the OS X trust store) SSL would pretty much be only obfuscation.

I assume most users will use SSH for remote connections anyway, which provides sufficient protection in most scenarios.

**Comment by dmoagx** [comment]
Best we could do is patch `libmysqlclient` (again) so we get the server capability flags (which will indicate SSL support) and warn the user that he could use SSL when connecting unencrypted.
But nagging people about everything creates bad UX...
