### ISSUE TITLE
PHP Serialized Arrays Paste On Text Editor

### ISSUE THREAD

**Issue by blickfeld7** [sequelpro/sequelpro#2820]
Hi,
i don't know if it's really a Sequel Pro bug, maybe someone else can give it a try:
If i paste a php serialized array into the text editor of a LONGTEXT field, it gets converted back to `a:1:{s:12:"_multiwidget";i:1;} `by Wordpress (after page reload).
This doesn't happen when i do the same with phpMyAdmin.
Does this happen because of invalid syntax/or encoding?

Best,
Florian Frank

P.S.: Let me know if you need more information to reproduce this issue.

**Comment by dmoagx** [comment]
I don't have wordpress at hand so I can't test it, but it's likely that the data is invalid.
Please post the data in question (or send it via mail if you don't want to make it public: https://sequelpro.com/docs/contribute/contact ) so I can have a look.

Also watch out for any whitespace characters before/after the actual data as that may also cause problems.

**Comment by dmoagx** [comment]
Closing after no feedback from reporter.
