### ISSUE TITLE
List of favourite / frequently used tables

### ISSUE THREAD

**Issue by aramkarapetian** [sequelpro/sequelpro#2822]
hi guys,
would be great to have favourites in table list. will check and see if I can code this feature.
cheers

**Comment by artaex** [comment]
What's wrong with the alphabetical order?

**Comment by parangdae** [comment]
If there are many tables, it is hard to find the table. and more scroll, more search

**Comment by elincyar** [comment]
I agree that this would be a very useful feature. When you are working with only a few tables in a database of over 400 tables it would be great to easily switch between a couple of tables without constantly searching for the table you need.

**Comment by stuconnolly** [comment]
Duplicate of #1391
