### ISSUE TITLE
CSV Import crashes Sequel Pro every time.

### ISSUE THREAD

**Issue by rwolfenden** [sequelpro/sequelpro#2828]
I've just tried to upload a small CSV to my DB and found that it crashes each time. I've read a different thread on this but didnt find any resolution. 

Here's a sample from the program taken via Activity Monitor..

Thanks,
[sample.txt](https://github.com/sequelpro/sequelpro/files/1112033/sample.txt)

**Comment by dmoagx** [comment]
The sample only shows that SP hangs while trying to display the crash reporter.
Please look for messages from Sequel Pro in Console.app

**Comment by rwolfenden** [comment]
Thanks - found the issue just as you replied. Incorrect Date format of all things.

**Comment by dmoagx** [comment]
Can you give a more detailed explanation?
Sequel Pro shouldn't crash/hang, even with invalid data.

**Comment by rwolfenden** [comment]
Honestly, I don't know whats happening with it. It still crashes. I've tried using MySQL Workbench too but this gave me the error - Row import failed with error: ("Data truncated for column.... etc.

So im assuming issues with the raw data..
