### ISSUE TITLE
Access Denied 

### ISSUE THREAD

**Issue by rebeccamills** [sequelpro/sequelpro#2829]
I keep getting Access Denied when I try to log in with username root and blank password...

<img width="800" alt="screen shot 2017-06-30 at 12 42 53 pm" src="https://user-images.githubusercontent.com/5178610/27745653-2879495a-5d92-11e7-8ffb-77fa89032b6e.png">

**Comment by digipifini** [comment]
Try going in to your cpanel/whm/ensim control panel and ensure your local IP address is listed under the mysql remote settings

**Comment by rebeccamills** [comment]
I don't have cpanel...is there another way to access mysql's remote settings? (Just looked in my mysql folder for them). Thanks.

**Comment by rebeccamills** [comment]
MAMP. Looked for an option for Remote Settings under the mysql tab there...

**Comment by digipifini** [comment]
Might be better to use the terminal.app then:

/Applications/MAMP/Library/bin/mysql -h <your-IP-here> -u user_name -p database_name

**Comment by rebeccamills** [comment]
Not finding MAMP in my Applications folder when I ls, although it's there when I look in my Finder. When I open Applications/MAMP/Library/bin/mysql in my terminal from Finder, I see: 

Last login: Fri Jun 30 13:32:05 on ttys004
-bash: port: command not found
/Applications/MAMP/Library/bin/mysql ; exit;
13:36:05 ~ $> /Applications/MAMP/Library/bin/mysql ; exit;
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/Applications/MAMP/tmp/mysql/mysql.sock' (2)
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...26 completed.

[Process completed]

**Comment by digipifini** [comment]
are you sure the mysql server is running properly? I'm not that familiar with MAMP, I usually setup everything manually to be sure everything runs smoothly.

If you can login to the mysql server, using mysql -u root -p then just use the GRANT command

mysql> GRANT ALL ON *.* to root@'192.168.1.4' IDENTIFIED BY 'your-root-password';

**Comment by rebeccamills** [comment]
13:50:07 ~/Desktop/mysql $> mysql -u root -p
Enter password: 
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)

**Comment by digipifini** [comment]
I think you need to get your mysql install in order first.  Either your password is incorrect or you are using a different username for the root control.

**Comment by dmoagx** [comment]
Anyway, this is a bug tracker and not a support forum.
Since the mysql CLI client doesn't work either it's pretty safe to say this is not a bug in Sequel Pro but a configuration issue.
