### ISSUE TITLE
SSH connection failed! SSH tunnel unexpectedly closed

### ISSUE THREAD

**Issue by tlaskeyVeem** [sequelpro/sequelpro#2831]
I am receiving an error when trying to connect using ssh. I receive this error:

```
Used command:  /usr/bin/ssh -v -N -S none -o ControlMaster=no -o ExitOnForwardFailure=yes -o ConnectTimeout=10 -o NumberOfPasswordPrompts=3 -i /Users/tylerlaskey/.ssh/id_rsa.pub -o TCPKeepAlive=no -o ServerAliveInterval=60 -o ServerAliveCountMax=1 root@34.210.174.33 -L 49516:xxxxxxxxxxx:3306

Bad local forwarding specification ' 49516:xxxxxxxxxxxx:3306'
```
I am using MacOS Sierra 10.12.5
I received this error when using El Capitan and after trying multiple solutions for it without success, I installed Sierra thinking it might fix the issue. However, I still receive the same error. The only time I am able to connect is by manually inputting the command and replacing the ':' with a '/' like so:
`49516/xxxxxxxxxxxx/3306`

I have tried looking at past closed issues for a solution like #2253 but using a different version of Sequel Pro still didn't work. 
I am using OpenSSH_7.5p1, OpenSSL 1.0.2l

**Comment by dmoagx** [comment]
> I am using OpenSSH_7.5p1, OpenSSL 1.0.2l

That is strange. The ssh version that comes with 10.12.5 is:
```
$ /usr/bin/ssh -V
OpenSSH_7.4p1, LibreSSL 2.5.0
```

Perhaps you replaced ssh at some point with a custom version?

**Comment by tlaskeyVeem** [comment]
Yeah I installed a custom version through homebrew. I actually solved the issue though so all is well. My fault.

**Comment by Ashraf-Ali-aa** [comment]
Hi, am having the same issue but am running system ssh
