### ISSUE TITLE
Missing and vanishing scrollbars

### ISSUE THREAD

**Issue by neokio** [sequelpro/sequelpro#2837]
With Sequel Pro (snapshot build 5207 (38d40d0)), using OSX 10.11.3 (El Capitan), when I load a table, the scrollbars are missing. Resizing the window briefly reveals the scrollbars, but catching them in time is difficult.

[THIS VIDEO HERE](https://mega.nz/#!dV8gFTIA!LFZbof3VQS7ez9eW0qgjqAEmevPQh_dJvMWrvi9c040) perfectly demonstrates the issue.

**Comment by dmoagx** [comment]
That is exactly how every OS X app behaves, if you have enabled the clusterfuck that is disappearing scrollbars (System Prefs > General > Show Scrollbars).

**Comment by neokio** [comment]
Wow! You nailed it, thanks for that.
