### ISSUE TITLE
MariaDB 10.2.7 BC break

### ISSUE THREAD

**Issue by bilhackmac** [sequelpro/sequelpro#2839]
MariaDB 10.2.7 and future releases (5.5, 10.0 and 10.1 branches are not affected) just resolve an old bug in SQL standards implementation and introduce a BC break

Ticket that explains changes https://jira.mariadb.org/browse/MDEV-13132
Ticket that confirms (in comments) only >= v10.2.7 are affected https://jira.mariadb.org/browse/MDEV-13341

Concretely, for SequelPro, every column with _NULL_ default is seen as **'NULL'**.
I don't find any other issues… for now.

For the moment, MySQL don't have the same issue.

**Comment by dmoagx** [comment]
Sorry, I don't follow.

MariaDB introduced quotes around strings to differentiate them from SQL expressions, but `NULL` is an SQL expression. So, if Sequel Pro displays `"NULL"` then according to the issue description this would mean the default value is actually the string literal "NULL"?

Plus, we don't even use `information_schema.columns` in the first place.

**Comment by dmoagx** [comment]
No feedback from reporter in > 1 month, closing.
