### ISSUE TITLE
Duplicate multiple tables

### ISSUE THREAD

**Issue by ehausen** [sequelpro/sequelpro#2845]
When selecting a table and right clicking the user is able to choose _Duplicate Table_ and choose a new name for the new table to be created

However, when selecting multiple tables this is not possible. Why? And could this be added? If this possible with a single table, why not multiple, just repeat and repeat? Is it because of the needed enhancements in renaming interface that would be needed?

This is needed for example when creating a copy of a CMS (Wordpress, Drupal, etc) database in the same database, but a with a different prefix when creating a staging environment for example.

**Comment by abhibeckert** [comment]
Agreed, we should add this feature.

> This is needed for example when creating a copy of a CMS (Wordpress, Drupal, etc) database in the same database, but a with a different prefix when creating a staging environment for example.

Perhaps duplicate to a separate database and then write a script to rename the all of the tables back into the current one with your prefix using:

    rename table `temp_db.table` to `db.prefix_table`;

**Comment by ehausen** [comment]
If adding this feature, I guess the hassle is at adding an interface for renaming multiple tables at once?

Simplest would be maybe to spit out a long form with two columns: old name and new name and then as many rows as tables.. not very user friendly of course, but easier to implement?

**Comment by ehausen** [comment]
How about _Find and replace_ in database name? (with dry run)

**Comment by abhibeckert** [comment]
Apple's Finder app has a good interface for this that shouldn't be hard to implement.

It has three options:

 * add text prefix/suffix
 * replace text (eg for changing one prefix to a different prefix)
 * format (we could just allow the user to type a regular expression match/replace pattern)

On top of that, we should also allow duplicating (and renaming) across databases.
