### ISSUE TITLE
feature request: re-use color of connection favorite in main window

### ISSUE THREAD

**Issue by Mrten** [sequelpro/sequelpro#2851]
In the connection window, you can assign a color to a specific favorite. It would be nice if that color was repeated somewhere as a background in the main window.

We've got a lot of db servers that I connect to simultaneously and being able to differentiate between servers by color instead of reading the window title would be a huge boon, would prevent me from deleting the wrong table :)

**Comment by BlackIce1986** [comment]
I'd like to have it also. would be really nice feature

**Comment by Mrten** [comment]
have already found that connection tabs do have the color already

**Comment by BlackIce1986** [comment]
wow, thats nice, but would be even better if connection color will be used to color up whole window, or at least table list or something

**Comment by tpinne** [comment]
I would also like a feature like that really much. I know that the tabs are colored, but I often work in separate windows between local development and live database for easy comparison or other stuff. And that sometimes already led to unwanted results.......

So I would REALLY some prominent coloring. At least if a window ist not opened with tabs. I won't bother if the whole application frame turns red, green or orange (those I use to distinguish between local, staging and live databases).

Having only colored tabs I always have to look exactly which tab is the active one, if the database structures are the same.
