### ISSUE TITLE
Option to skip triggers when exporting

### ISSUE THREAD

**Issue by initializard** [sequelpro/sequelpro#2857]
It would be great to have an option to skip exporting triggers (ie. --skip-triggers). Often I don't need them and would like to skip them entirely. I've also run into problems where the user in the DEFINER of the trigger is different on the source database and target database and the triggers won't import, or they won't work after the import because of this.

**Comment by abhibeckert** [comment]
Confirmed. To reproduce:

```
CREATE TABLE account (acct_num INT, amount DECIMAL(10,2));

CREATE TRIGGER ins_sum BEFORE INSERT ON account
  OR EACH ROW SET @sum = @sum + NEW.amount;

SET @sum = 0;
INSERT INTO account VALUES(137,14.98),(141,1937.50),(97,-100.00);
SELECT @sum AS 'Total amount inserted';
```

... and then export as SQL, which will include:

```
[drop/create account table]

[insert account table rows]

DELIMITER ;;
/*!50003 SET SESSION SQL_MODE="" */;;
/*!50003 CREATE */ /*!50017 DEFINER=`root`@`localhost` */ /*!50003 TRIGGER `ins_sum` BEFORE INSERT ON `account` FOR EACH ROW SET @sum = @sum + NEW.amount */;;
DELIMITER ;
/*!50003 SET SESSION SQL_MODE=@OLD_SQL_MODE */;
```
