### ISSUE TITLE
Make autoincrement default for export

### ISSUE THREAD

**Issue by geoidesic** [sequelpro/sequelpro#2861]
I can't think of any reason why one would not want "Auto increment value"  checkbox for export to default to true. Alternately export default settings should be configurable. At the very least it should remember your last setting. It really slows me down having to always remember to tick the checkbox before exporting.

**Comment by abhibeckert** [comment]
It does remember your last setting for me.

Can you please confirm:

 * do an export with auto increment enabled
 * quit/relaunch sequel pro
 * go into the export panel, check if auto increment is enabled

If it's not working, what build are you using?

Finally check the output of this in Terminal:

    defaults read com.sequelpro.sequelpro | grep SQLIncludeAutoIncrementValue

**Comment by jordanboston** [comment]
In version 1.1.2 Build 4541 it works fine after I have checked it once and ran it.  When I come back the auto increment works just fine.  This **does not seem** to be a bug in this version.

**Comment by rikzuiderlicht** [comment]
The last settings are not  remembered we tested this on two machines. Used version of Sequel Pro (1.1.2)

The AutoIncrement value checkbox is always unsigned when the export window is shown. We were unable to find a way to make this a default setting.

**Comment by dmoagx** [comment]
No feedback from reporter on the requested input in > 1 month, closing.

**Comment by h-archer** [comment]
Version 1.1.2 (MacOS High Sierra) 

This setting does not save. 

When opening the panel for exporting a database this option is always unticked.
