### ISSUE TITLE
Can't decrypt spf file

### ISSUE THREAD

**Issue by sfarver** [sequelpro/sequelpro#2862]
saved login info under pass. no ability to decrypt and get the pass info to login from another place other than sequelpro.

**Comment by abhibeckert** [comment]
SPF files are not encrypted, they're plain XML. However, they also do not contain any passwords.

You can access passwords by searching for "Sequel Pro" in the macOS Keychain Access app.

**Comment by sfarver** [comment]
Thanks for the reply and continued help - was unable to find any password for Sequel Pro in the Keychain Access app - I apologize if I'm missing something obvious here.

To give you a bit more context, I have a SQL login connection that I saved. Previously I saved without any pass to access and was able to view the XML via a text editor. Now, however, because I saved with a pass, I am unable to do so - it's saying that it's encrypted with a key.

I'm just looking to get the actual pass so I can use it via another application besides Sequel Pro (in Excel).
