### ISSUE TITLE
Crash when connecting to Laradock MySQL container from my host machine

### ISSUE THREAD

**Issue by harmoniclauri** [sequelpro/sequelpro#2865]
Sequel Pro crashes when connecting to a docker MySQL container from http://laradock.io/
As I am able to connect and operate normally on the same database using MySQL Workbench, with the exact same settings, I’m assuming this is a Sequel Pro issue.

My settings are as [standard Laradock container settings](https://github.com/laradock/laradock/blob/master/env-example), using port 3306.

In the Sequel Pro connection details page, the Test Connection functionality returns "Connection Succeeded", but upon connecting and trying to fetch tables from that database, Sequel Pro launches the error report functionality and hangs indefinitely. The tables are never listed.

This behavior happens 100% of the time.

![image](https://user-images.githubusercontent.com/30488641/29548705-7f9e2d28-8735-11e7-898f-c6dff63f0fd0.png)

**Comment by craigharman** [comment]
Same thing happens to me. Listing the contents of all mysql databases seems to work, but accessing the database itself produces the above error.

**Comment by dmoagx** [comment]
I think that was already fixed in #2606 
You can try a development build of the next version: https://sequelpro.com/test-builds

**Comment by anthonys-harmonic** [comment]
@dmoagx Thank you, build https://sequelpro.com/builds/Sequel-Pro-Build-e59f679f6c.zip works as intended. Much appreciated!

**Comment by harmoniclauri** [comment]
@dmoagx Thank you, build build https://sequelpro.com/builds/Sequel-Pro-Build-e59f679f6c.zip works.

**Comment by kiankji** [comment]
Same error with the newest version of sequel pro
