### ISSUE TITLE
Show value of related column

### ISSUE THREAD

**Issue by markpanado** [sequelpro/sequelpro#2866]
In **phpmyadmin** you can see the value of related columns by adjusting setting in designer tab:

![image](https://user-images.githubusercontent.com/3646720/29651426-531af642-88d3-11e7-821e-ffd05f20fd9b.png)

In **Sequel Pro** I can't see an option similar to that. So rows will be displayed as plain value.

![image](https://user-images.githubusercontent.com/3646720/29651620-28662466-88d4-11e7-9138-93ec6304ac80.png)

How can we do this in **Sequel Pro**?

**Comment by abhibeckert** [comment]
How do you specify which column is displayed instead of the primary key?

**Comment by markpanado** [comment]
In **phpmyadmin**'s Designer tab, you need to set which column to be displayed to another table that has relation to it.

Demo:

![kapture 2017-08-25 at 11 13 42](https://user-images.githubusercontent.com/3646720/29698213-7d3e4362-8986-11e7-96c1-1a6d84d0febb.gif)

**Comment by abhibeckert** [comment]
Thanks for the details, this is something I'd also like to see implemented one day, but I can't make promises when it will happen.
