### ISSUE TITLE
How to indent multiple lines?

### ISSUE THREAD

**Issue by mikeher** [sequelpro/sequelpro#2867]
When marking multiple lines and pressing the tab button I would normally expect the query editor to indent all the selected lines. However, instead they get replaced with a tab. Is there a neat way to indent (and remove indentation) for multiple lines at a time?

I often find myself copy/pasting huge queries between Sequel Pro and another text editor because of this.

**Comment by dmoagx** [comment]
Like in any other Mac app: alt+cmd+6 to indent, alt+cmd+5 to outdent (at least with German keyboard layout)

**Comment by markpanado** [comment]
**cmd** + **[** or **cmd** + **]** works for me

**Comment by abhibeckert** [comment]
> When marking multiple lines and pressing the tab button I would normally expect the query editor to indent all the selected lines.

Sequel Pro does support this, but looking into it the feature is broken:

 * it's only active if "soft indent" (use tabs instead of spaces) is enabled – dunno why this decision was made but it was clearly intentional
 * tab will only indent if the insertion point (or beginning of the selected range) is in the leading whitespace
 * shift tab doesn't de-indent

**Comment by carlosdelros** [comment]
CMD + ] Indent
CMD + [ Outdent

**Comment by mikeher** [comment]
> The way markpanado has posted (cmd+[ and cmd+]) does work but I use many other tools on my mac (and linux and windows as well) and tab/shift+tab does the indent/unindent operation evrywhere. It would be nice if sequelpro would support the same hotkeys beside the cmd+[/cmd+].

@halmai I totally forgot I authored this thread. By now my best advise here is to abandon ship. Sequel Pro is nice, but it is not maintained at all and more and more bugs are popping into existence. I am gradually working towards utilising a different tool for my database work.

Yes I know this is way off topic, but I suspect the sweet people not maintaining their product couldn't care less about what goes on at their github page as well.

**Comment by dmoagx** [comment]
> but I suspect the sweet people not maintaining their product couldn't care less about what goes on at their github page as well.

Or instead of "suspecting" you could just have taken the 30 seconds it takes to click on the "Insights" tab at the top and see that this is complete nonsense!

**Comment by halmai** [comment]
> > The way markpanado has posted (cmd+[ and cmd+]) does work but I use many other tools on my mac (and linux and windows as well) and tab/shift+tab does the indent/unindent operation evrywhere. It would be nice if sequelpro would support the same hotkeys beside the cmd+[/cmd+].
> 
> @halmai I totally forgot I authored this thread. By now my best advise here is to abandon ship. Sequel Pro is nice, but it is not maintained at all and more and more bugs are popping into existence. I am gradually working towards utilising a different tool for my database work.
> 
> Yes I know this is way off topic, but I suspect the sweet people not maintaining their product couldn't care less about what goes on at their github page as well.

Just check the most recent commits here on github (https://github.com/sequelpro/sequelpro/commits/master). There are several commits practically every day. I do think they are working on it. So, I hope my request will be heard. :)
