### ISSUE TITLE
Font size tables pane

### ISSUE THREAD

**Issue by Fossil01** [sequelpro/sequelpro#2872]
Running on a 4K screen now I have set the query and tables font sizes from 10 to 12. But the text in the tables pane on the left does not increase.

Is there a way to do this?

**Comment by abhibeckert** [comment]
It's not possible to change the font.

We should add that feature, and also the default font should be larger - the current size is smaller than the system default.

**Comment by pedrosalpr** [comment]
Any release date prediction @abhibeckert ?

**Comment by dflow** [comment]
Same issue here , table pane text size  is too small on a mac screen

**Comment by samuelchlui** [comment]
This enhancement is very useful , could it be reopen again?

**Comment by shemtov1** [comment]
Please reopen this issue.  I have to put my face to the screen to see the table names in the left panel.

**Comment by lxmorj** [comment]
Agreed. It would be very helpful

**Comment by Rich1000** [comment]
I'd still love to see this feature

**Comment by wangx1ng** [comment]
3 yrs passed and still, we'd love to see this feature

**Comment by ghost** [comment]
Move to either TablePlus or Sequel Ace.

**Comment by cjhope** [comment]
I and everyone that I do a screenshare with would like to see this feature

**Comment by blakegearin** [comment]
Any updates?

**Comment by lxmorj** [comment]
Try Sequel Ace

Sent via Superhuman ( ***@***.*** )
