### ISSUE TITLE
Unable to donate via Paypal

### ISSUE THREAD

**Issue by barats** [sequelpro/sequelpro#2874]
Thanks for your efforts, I really like this software. 

BTW, I tried to donate via Paypal on page http://www.sequelpro.com/donate/ , but it says that 'This recipient is currently unable to receive money'.

Plz take some time to fix this, I think I'd love to donate.

**Comment by abhibeckert** [comment]
Thanks, PayPal had restricted the account because they needed me to confirm some details. I've done so now and you should be able to make a donation.

**Comment by barats** [comment]
Already donated $20, thanks for ur efforts.
