### ISSUE TITLE
[REQ] Filter/search column names in Content view

### ISSUE THREAD

**Issue by JonLaliberte** [sequelpro/sequelpro#2875]
Often I'll be looking through the content of tables with 50-100 columns, and need to find a specific column's data. This usually means scrolling back and forth a few times trying to find it, which can be a bit tedious. And worse is when there are 3 or 4 columns that need to compared and are not near each other.

I'm not sure the exact UI/way to implement this, but it'd be great if you could search and filter by checking/unchecking which columns would be displayed within the Content view. A "Select/Deselect all" would be wanted. Then as you search, you can click the checkbox, search for the next column, check it, etc. Then the content view (for this table) would only show those fields until that column filter were cleared.

**Comment by samuelbradshaw** [comment]
How about a drop-down menu with checkmarks, as in the suggestion here? https://ux.stackexchange.com/questions/110077/best-practices-to-allow-user-to-hide-show-columns-in-a-data-table
