### ISSUE TITLE
Add 'Auto Reconnect' option

### ISSUE THREAD

**Issue by adamabernathy** [sequelpro/sequelpro#2878]
The servers I work on have a very quick timeout, so it would be nice if there was a 'Auto Reconnect' option that would rather than prompt me all the time to reconnect, it would just do it for me.

**Comment by abhibeckert** [comment]
Sequel Pro should automatically reconnect whenever your connection drops out.

Is this not working for you?

**Comment by adamabernathy** [comment]
Then there might be a bug somewhere.  I connect to my server via SSH, and I often get the "Connection Lost" message.  Maybe there needs to be a keep alive ping or something added to the SSH connection?

**Comment by dmoagx** [comment]
Sequel Pro already does a keep alive ping (also for SSH).
The "Connection Lost" message only appears after SP failed to reconnect once. Were you continuously using your Mac when the message appears or did it switch to screensaver/standby at some point in between?

You could also enable TCP keep alive in your SSH config file.

**Comment by adamabernathy** [comment]
@dmoagx, yeah I'm continuously use the program and will get alerted of the error. Often its within seconds of just reconnecting.  It does this regardless of the server I'm connected to.  Also, I have it installed on several Macs, that are used on different networks.  Which should eliminate the network variable in the equation.

I'll add the TCP option to my SSH config and see if that helps.

**Comment by adamabernathy** [comment]
So i've run several tests with the following added to my SSH file

```
Host remotehost:
    HostName remotehost.com
    ServerAliveInterval 15

Host *
    TcpKeepAlive yes
    ServerAliveInterval 0
    ServerAliveCountMax 3 
```

and I'm still getting the re-connect message.  Is there a way to access a dump file or something that I can send you?

**Comment by abhibeckert** [comment]
> Is there a way to access a dump file or something that I can send you?

I’ll let @dmoagx answer that, he’s more familiar than me. But can you tell us some more about the server?

What Linux distro, what version of SSH/MySQL/MariaDB, any unusual config settings if you know of any, etc.

**Comment by abhibeckert** [comment]
Also, if you just ssh into the server... is that reliable?

**Comment by adamabernathy** [comment]
Using Ubuntu/MySQL and TokuDB.  SSH is reliable.

**Comment by adamabernathy** [comment]
I haven't seen too much of this issue since updating my SSH file.  I recommend we close it as it was more than likely isolated to that.

**Comment by abhibeckert** [comment]
thanks for the followup
