### ISSUE TITLE
Confirm Exit

### ISSUE THREAD

**Issue by JodyLognoul** [sequelpro/sequelpro#2879]
Hello,

Is there a way to have a confirmation on exit (cmd + q) ?

Thanks

**Comment by dmoagx** [comment]
I guess we could do something similar to Chrome, where you have to hold down cmd + Q for a few seconds and it shows an overlay meanwhile.

**Comment by Narcotic** [comment]
Would be nice...I lost so many things by typing **cmd+q** instead of **cmd + a**. 
:-)
