### ISSUE TITLE
Support table check constraints

### ISSUE THREAD

**Issue by eirinhart** [sequelpro/sequelpro#2880]
Number and year does not work. 
WHAT DO I DO?

I have used it on another program and it works then

CREATE TABLE vehicle 
(reg_No CHAR(6) PRIMARY KEY,
make VARCHAR(10) NOT NULL,
model VARCHAR(10) NOT NULL,
period NUMBER(4) CHECK(year >= 2011),
colour CHAR(2) REFERENCES colour(colour),

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'NUMBER(4) CHECK(year >= 2011),
colour CHAR(2) REFERENCES colour(colour),' at line 7

**Comment by dmoagx** [comment]
Check Constraints are not supported in 1.1.2
Use a development build from https://sequelpro.com/test-builds which has partial support for this.
