### ISSUE TITLE
User permissions configuration

### ISSUE THREAD

**Issue by danielwhatmuff** [sequelpro/sequelpro#2881]
Within Users > Schema Privileges, sometimes when permissions are added or revoked for a particular db there is an error message saying it failed to apply but then it actually seems to have worked when you go back in. Sometimes it says it didnt apply and it actually didn't.

**Comment by dmoagx** [comment]
That description is too vague to be helpful, but I assume you are seeing a variant of this issue: https://github.com/sequelpro/sequelpro/issues/2229#issuecomment-265291365

**Comment by dmoagx** [comment]
Closing since there is no feedback from reporter.
