### ISSUE TITLE
Block `on update current timestamp` behaviour when editing a value in the GUI

### ISSUE THREAD

**Issue by thatChadM** [sequelpro/sequelpro#2885]
Using version 1.1.2, build 4541, on mac OS 10.12.6.

Whenever any field is edited the existing timestamp field is changed to the current timestamp after hitting enter or clicking to another row.  If the timestamp field itself is edited, the edited value remains.

If you look at row 434 in content-original, you will see that the "deleted_on" value is 0.  If you look at the same row in content-updated, it shows that after I updated the name the timestamp was changed to reflect the current time.

I did confirm that the timestamp field is updated regardless of what the original value is, so it isn't getting triggered just because the value is 0.

![table_info](https://user-images.githubusercontent.com/31999519/30504175-4522ced8-9a3b-11e7-8a1a-4ecbd5a53229.png)
![content-original](https://user-images.githubusercontent.com/31999519/30504381-695f1bc0-9a3c-11e7-832e-dcb5834fa9d8.png)
![content-updated](https://user-images.githubusercontent.com/31999519/30504382-69607312-9a3c-11e7-9ec4-8838f124e23a.png)

---

Edit by @abhibeckert MySQL forces "on update current timestamp" behaviour on timestamp columns that are not null. We should have a preference (enabled by default) to detect this MySQL feature and block it by specifying a timestamp in the update query when a user changes another value in a row.

**Comment by dmoagx** [comment]
Look at the Console view to see whether Sequel Pro adds the date to the query.
If not, you probably have an `on update` condition or a trigger.

**Comment by abhibeckert** [comment]
@dmoagx I tested, we are not adding a date to the query.

Also running a custom query will also change the timestamp to the current date:

    select * from test;
    # 1	alice	0000-00-00 00:00:00
    
    UPDATE `test` SET `foo` = 'bob' WHERE `id` = '1';
    
    select * from test;
    # 1	bob	2017-09-15 19:52:02

**Comment by abhibeckert** [comment]
However with my server, if you create a `timestamp NOT NULL` column, it automatically changes to `timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`

Perhaps other releases of MySQL have this behaviour but do not display it as clearly as mine?

@thatChadM I recommend you allow null on your table column.

**Comment by abhibeckert** [comment]
Closing, this is not a bug in sequel pro. It is just how MySQL behaves.

**Comment by thatChadM** [comment]
That might explain the behavior with a field value of 0, but why does
the date change when there is an existing date in place?  I clearly
stated the date field was changed regardless of the value of the field
(0 or non-0).

And no, there is no trigger to update the field.  This is an extremely
stupid database.  That value must be 0 for the row to be considered
valid.  If it is a non-0 value it means the item in the row was deleted
at that time and is no longer considered a live item.  In other words
the value -must- be 0 for the row to be considered a live item. 
Changing it to a non-0 value simply because some other field is updated
would be disastrous.

-Chad

----- Original message -----

**Comment by thatChadM** [comment]
I'm also about 95% certain that this behavior didn't exist in an older version, but I can't verify until I get back in the office.

**Comment by abhibeckert** [comment]
> That might explain the behavior with a field value of 0, but why does
the date change when there is an existing date in place

If `ON UPDATE CURRENT_TIMESTAMP` is active, then the date will change whenever the row is updated unless you specify a value for the timestamp as part of the update query. Sequel Pro doesn't include the column unless you specifically enter a value.

I'm going to change this to a feature request. It would be good to have a preference to detect "on update current_timestamp" columns and prevent them from changing. I think this should probably be the default behaviour.

**Comment by thatChadM** [comment]
Well huh, I even get that behavior from the command line interface.  And I know I made updates in that table in the past and but I don't remember having to reset the deleted_on field.

Poking around a bit it looks like it is this: https://bugs.mysql.com/bug.php?id=41137.  Specifically: "With neither DEFAULT nor ON UPDATE clauses, it is the same as DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP."

This app is still using MySQL 3.23.54, and that behavior wasn't changed until 5.6.6 according to the bug note.  Freaking annoying, as who expects a field to get changed when there is nothing in the table description saying it would do so.

So, my apologies.  Not a bug, user error due to unexpected (and unwanted) behavior due to the table definition.  Not sure why I didn't run into this until now.  Or maybe I did and I just didn't notice it, in which case I may have some some records in limbo.

Thanks @abhibeckert !

**Comment by markusweb** [comment]
i just came around this problem. i have a table with a timestamp field like

`eingang` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
`
so every time i do an insert or an update the field "eingang" will be set to the current time. 

BUT: i want to have an option to prevent this auto-update in Sequel. So when edititing a field in a row the field "eingang" should keep its value.

at the moment i am using a html/perl GUI for editing/managing the database. there i can "check" the field to keep it's value

![Editing.pjng](https://user-images.githubusercontent.com/536804/45544584-05c01380-b818-11e8-8dd6-735f9fd39a1e.png)
so i can check the field eingang to keep it's value and change or update any of the other fields.

Markus
