### ISSUE TITLE
SSH tunnel cannot be established when using unrecognized ssh config directives

### ISSUE THREAD

**Issue by edwardkenfox** [sequelpro/sequelpro#2893]
## Environment

- OS: macOS 10.12.1
- Sequel Pro version: 1.1.2

## Details of the problem

I get the following error when trying to connect to a database server through a ssh tunnel:

```
OpenSSH_7.2p2, LibreSSL 2.4.1
debug1: Reading configuration data /Users/edwardkenfox/.ssh/config
/Users/edwardkenfox/.ssh/config: line 1: Bad configuration option: include
/Users/edwardkenfox/.ssh/config: terminating, 1 bad configuration options
```

and the below is the top part of my ssh config file:

```
Include ~/.ssh/other-ssh-configs

# other configurations...
```

And my local openssh version is 7.6p1 installed via homebrew.

The problem is that the [Include directive](https://man.openbsd.org/ssh_config#Include) had been introduced in [openssh release-7.3](https://www.openssh.com/txt/release-7.3) and I use it in the 1st line of my ssh config file. However, since Sequel Pro uses older version of openssh (7.2p2) which doesn't support the `Include` directive while always trying to use my ssh config file, it will always fail to establish a ssh connection. 

## Suggestions

1. Allow configuring ssh config file location other than `~/.ssh/config`
2. Update openssh version used in Sequel Pro

Would also appreciate if anybody knows a workaround for this issue as well.

## Related issue

-  [Sequel Pro should use SSH config if present](https://github.com/sequelpro/sequelpro/issues/776)

**Comment by dmoagx** [comment]
Sequel Pro does not bundle OpenSSH, so there is nothing to update. Sequel Pro uses the OS X ssh client. If you want to use another client you can set it in Prefs > Advanced

**Comment by edwardkenfox** [comment]
Oh I guess I was misunderstanding about that, thanks a lot.
