### ISSUE TITLE
Database encoding utf8mb4 is not autodetected

### ISSUE THREAD

**Issue by inoas** [sequelpro/sequelpro#2897]
### Problem

Cannot work with utf8mb4 because it is not autodetected.

#### Schema

```sql
CREATE TABLE `cms_links_translations` (
  `path` varchar(660) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT ''
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```

#### Existing data (best insert through utf8mb4 capable client/command)

```sql
INSERT INTO `cms_links_translations` (`path`) VALUES ('/willkömm💕n');
```

```sql
SELECT * FROM cms_links_translations WHERE path = '/willkömm💕n';
```

```
Illegal mix of collations (utf8mb4_bin,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '='
```

#### In

```sql
SELECT DEFAULT_CHARACTER_SET_NAME, DEFAULT_COLLATION_NAME FROM information_schema.SCHEMATA S
WHERE SCHEMA_NAME = 'my_app'
    AND (DEFAULT_CHARACTER_SET_NAME != 'utf8' OR DEFAULT_COLLATION_NAME NOT LIKE 'utf8%');
```

#### Out

<img width="1680" alt="screen shot 2017-10-13 at 23 42 14" src="https://user-images.githubusercontent.com/20972207/31567523-33305ede-b070-11e7-8cf6-640359ad3432.png">

### Env

- SequelPro Build 5224 (3477d223)
- `$ mysql --version` : `mysql  Ver 15.1 Distrib 10.2.7-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2`

### Workaround

- SequelPro.app -> Preferences -> General -> Default Encoding -> UTF-8 Full Unicode (utf8mb4)

**Comment by dmoagx** [comment]
Sequel Pro will by default use the charset that is the default for the selected table (I consider this a bug in itself, but that's a different story). 
You created the table with `utf8mb4`, but if the last table you selected was a `utf8` table, that is what your connection will be set to and explains the mix of charsets in the error message.

**Comment by vuminhvuongit** [comment]
@dmoagx can you explain detail for: 

>  but if the last table you selected was a utf8 table, that is what your connection will be set to and explains the mix of charsets in the error message.

Thanks!

**Comment by dmoagx** [comment]
@vuminhvuongit 
> Sequel Pro will by default use the charset that is the default for the selected table
