### ISSUE TITLE
Improvement: Save Query, confirm overwrite

### ISSUE THREAD

**Issue by shawnhooper** [sequelpro/sequelpro#2898]
More than once I've opened a previously saved query, and then replaced it with something else in the query editor.  Not realizing I had an open .sql file, I've then hit Save Query expecting to get the Save dialog and instead it overwrites the query I had originally opened.

1. It would be nice, if there was an open file, for it to be shown somewhere clearly in that tab.
2. When overwriting an existing query, a confirmation dialog would be really useful.

**Comment by dmoagx** [comment]
I think this should be solved as outlined in #2709
