### ISSUE TITLE
OS X 10.13 Favorites Keychain Error -25293

### ISSUE THREAD

**Issue by dirtroof** [sequelpro/sequelpro#2900]
An error occured while trying to add the password to your Keychain. Repairing your Keychain might resolve this, but if it doesn't please report it to the Sequel Pro team, supplying the error code -25293.

**Comment by dmoagx** [comment]
`-25293` is `errSecAuthFailed` - that isn't very useful.

* Did you update macOS or move your files from one computer to another before the issue appeared?
* Did you update Sequel Pro before the issue appeared?

**Comment by landerover** [comment]
I have the same problem after formatting...

**Comment by fromthestone** [comment]
@dirtroof take a look [here](https://github.com/sequelpro/sequelpro/issues/2948) maybe for you is working...
I have the same problem, and a reboot doesn't solve it.
my Sequel Pro Version is 1.1.2 Build 4541 and my OsX version is 10.12.6

**Comment by jacks808** [comment]
use `keychain access.app` to search `sequel pro` and delete all keys. Then remove database connection info from sequel, and add again will fix this.

**Comment by hniemann** [comment]
Same problem here I have 10.13.6
I have no sequel pro entry in keychain that I could remove.
Sequel pro is a fresh install

**Comment by dmoagx** [comment]
1. Reboot
2. If that doesn't help create a new user account on your Mac and try it with that.

**Comment by dmoagx** [comment]
No feedback from original reporter in > 1 month, closing.

**Comment by hooch** [comment]
I have this problem as well, 10.13.6, fresh install of both OS X and Sequel Pro.

"please report it to the Sequel Pro team, supplying the error code -25293"

I checked the Console but there's only "sendAction:" with no additional data.

![](https://user-images.githubusercontent.com/13162479/38979924-17333e9c-43ee-11e8-88f1-a3adbb6db137.png)

**Comment by haochencheng** [comment]
> I guess we need to change the error message from "please report it to the Sequel Pro team" to "please report it to Apple, since they f**ed up Keychain with their craptastic iCloud implementation in the first place"

how could i report it to Apple ,that  annoyed me!

**Comment by haochencheng** [comment]
> 1. Reboot
> 2. If that doesn't help create a new user account on your Mac and try it with that.

after reboot my mac ,i resolve it.

**Comment by dmoagx** [comment]
> how could i report it to Apple

https://bugreport.apple.com
But don't expect anything from that. They will usually ignore reported issues for a few months and then close them as duplicate.

**Comment by calxu** [comment]
> 1. Reboot

After reboot my mac, I also resolve it.

**Comment by cullen911** [comment]
good  jobs
