### ISSUE TITLE
Feature Request — Add Server Start and Stop

### ISSUE THREAD

**Issue by rei-vilo** [sequelpro/sequelpro#2901]
I need to start the mySQL server before using SequelPro and stop it after using SequelPro.

Wouldn't be nice to enter bash commands for both, so we could automate the start and the stop of mySQL?

This is a feature [MySQL Workbench](https://www.mysql.com/products/workbench/) includes.

<img width="900" alt="capture 2017-10-19 a 20 27 30" src="https://user-images.githubusercontent.com/951776/31787469-28d60eac-b50c-11e7-8b53-d2d1c59c7148.png">

Thanks you!

**Comment by stuconnolly** [comment]
There's already the option to shutdown the server under the 'Database' menu once connected.

<img width="275" alt="screenshot 2018-10-03 at 14 04 10" src="https://user-images.githubusercontent.com/223144/46412075-635bc780-c715-11e8-9aab-589899bb92b1.png">
