### ISSUE TITLE
SSH Hangs indefinitely when the remote server's key changes...

### ISSUE THREAD

**Issue by nvahalik** [sequelpro/sequelpro#2902]
I have a remote connection on which the SSH key gets regenerated whenever the system gets rebuilt. When that happens while the connection is open, Sequel Pro provides the following message and then spinning beach ball until Force-Quit and then reset:

<img width="654" alt="monosnap 2017-10-20 21-02-33" src="https://user-images.githubusercontent.com/632120/31847058-bedb1b26-b5da-11e7-827f-de29b062f168.png">

Note that you cannot click on either button...

**Comment by dmoagx** [comment]
When it hangs go to Activity Monitor, select Sequel Pro, click on View > Sample Process and post the results.

**Comment by nvahalik** [comment]
Will do.

**Comment by dmoagx** [comment]
No feedback from reporter in > 1 month, closing.
