### ISSUE TITLE
You have entered 'localhost' for a non-socket connection

### ISSUE THREAD

**Issue by itsash--** [sequelpro/sequelpro#2904]
I understand this has been reported a number of times, but it's _still_ a bug.

The issue is, I want to SSH tunnel to a vagrant box and I do not want to have to work around the bug by logging in as root and `GRANT` the user access to `127.0.0.1` - the ssh tunnel will work using `localhost` but this software does not allow for that and it's really frustrating, especially when the error is:

> To MySQL, 'localhost' is a special host and means that a socket connection should be used.

That's completely invalid and irrelevant 😟

**Comment by dmoagx** [comment]
> That's completely invalid and irrelevant 😟

No, it is not and I could even prove it to you with the source of the official mysql client library (which we use).
If you give MySQL the hostname "localhost" to connect to, it WILL attempt a socket connection and that's it.

Second, and I've explained that over and over again, it doesn't even matter to the server!
MySQL doesn't send "127.0.0.1" or "localhost" or whatever you type as the hostname to the server.
The server makes a completely independent decision on whether a client comes from "127.0.0.1" or "localhost" and if `--skip-name-resolve` is set, that decision is very simple:
A socket connection comes from `localhost` and everything else comes from `a.b.c.d`

So you either remove that option, in which case `127.0.0.1` and `localhost` are equivalent or you'll have to wait for #2054

**Comment by itsash--** [comment]
Granted I was frustrated at the fact that because of this error I lost a bit of time resetting the root password on mysql (in vagrant).  I should not have needed to do this.

Is there any reason for the hardcoded error message though? Because MySQL Workbench can connect to a server via SSH tunnel using host `localhost`, i'm therefore unsure why SequelPro refuses to connect to mysql on `localhost` via an ssh tunnel.

**Comment by ne0c0de** [comment]
Hi,

I'm experiencing the same issue.

I entered the host name as localhost on SSH tunnel connection but it's changing it to 127.0.0.1 and the connection was failed.

I grant my root user to allow on 127.0.0.1 `GRANT ALL PRIVILEGES ON *.* TO 'root'@'127.0.0.1' IDENTIFIED BY 'xxx';` and mysql is listening 127.0.0.1 but still can't connect to server. what should i do in this case? 

Suggestion: can you put this localhost->127.0.0.1 auto detection as an option in settings?
