### ISSUE TITLE
Weird bug when firing up another window

### ISSUE THREAD

**Issue by jpike88** [sequelpro/sequelpro#2911]
When dragging a tab out into another window, the left column of it has weird inverted colours.

Using macOS High Sierra 10.13.1
Sequel Pro 1.1.2

![screen shot 2017-11-01 at 1 34 58 pm](https://user-images.githubusercontent.com/9585787/32262836-7928af02-bf09-11e7-9395-638e6a6f8d0f.png)

**Comment by jpike88** [comment]
WHAT THE HELL!?! The screenshot looks fine!?!?

**Comment by jpike88** [comment]
![img_0675](https://user-images.githubusercontent.com/9585787/32262892-c5343588-bf09-11e7-867c-ea67edfd9c67.JPG)

phone photo attached.

**Comment by dmoagx** [comment]
Duplicate of #2286
