### ISSUE TITLE
Feature request - Possibilty to send running query to background

### ISSUE THREAD

**Issue by kasperhartwich** [sequelpro/sequelpro#2913]
Sometimes i start a big query, but find out i want to abort. I click the "Stop query" button, but it just hangs and waits for the query to end.
It would be nice to be able to send the running query to the background, so i can start a new one.

See http://g.recordit.co/WdNu5JlbSU.gif
![image](https://user-images.githubusercontent.com/616231/32413212-df4bee10-c20c-11e7-9e89-a1083dd2f60c.png)

**Comment by dmoagx** [comment]
That is not so easy.
MySQL treats query cancellation pretty much as optional. Sometimes it works, most of the time it doesn't and the MySQL protocol is strictly single operation - a single connection can only have a single pending operation (that also means you can't cancel a query using the connection which it is running on).
The only way out in this case would be to open a new connection, but that also means any session state is lost. And this exact behavior can already be achieved by using "Duplicate Tab" (alt+T)...

**Comment by kasperhartwich** [comment]
Actually, what i am doing at the moment is opening another connection and sometimes open up server processes and kill the query.
