### ISSUE TITLE
Deleting a row does not work

### ISSUE THREAD

**Issue by acrodrig** [sequelpro/sequelpro#2915]
When trying to delete a row in the query editor using the keyboard, it does not work. When I press the DELETE keyboard as stated in the [keyboard shortcuts](https://sequelpro.com/docs/get-started/keyboard-shortcuts) I hear a blocking sound.

**Comment by dmoagx** [comment]
What do you mean?
Delete via Backspace (⌫) is supported only for "Table Structure" and "Table Content" views, but not for custom queries. That is also what the linked document says.
