### ISSUE TITLE
date and time chooser

### ISSUE THREAD

**Issue by ftrotter** [sequelpro/sequelpro#2925]
When clicking a field with a type of "date" a date chooser (as well as text field to enter a date) should appear. 

When clicking a TIMESTAMP or DATETIME field, a date and time chooser should appear. Similar choosers should be available for TIME and YEAR fields. 

This dramatically accelerates software development. 

<img width="1421" alt="date and time chooser" src="https://user-images.githubusercontent.com/83133/32930218-e790bc30-cb22-11e7-99f7-0203e09089bb.png">

It would also be nice to automatically support the calling of sensible functions when editing datetime fields. Things like NOW()  CURRENT_DATE() and CURRENT_TIME(). The following video shows how this happens in phpmyadmin. 

https://screencast.com/t/Vvr7smsfs

I know that this could be asking for a lot, given how clean and simple the sequelpro interface is. But it would really accelerate data entry and data modification tasks. 

Obviously, this  a feature request and not a bug. Thank you for your efforts!
-FT

**Comment by dmoagx** [comment]
Sequel Pro already supports `NOW()` and `CURRENT_TIMESTAMP` in date/time table fields.
