### ISSUE TITLE
Export JSON type fields with a CONVERT function wrapping

### ISSUE THREAD

**Issue by fosron** [sequelpro/sequelpro#2926]
When trying to import an export with JSON type fields there's an error about BINARY not importable as type.This Stackoverflow thread suggests this approach (which works) https://stackoverflow.com/a/42029919 . Could this be added to the export as an option?

**Comment by dmoagx** [comment]
Sequel Pro 1.1.2 doesn't support the JSON type and will therefore export it as HEX.
The future releases will support JSON and export it as text, so this should not be an issue.
You can try a development build from https://sequelpro.com/test-builds until then.

**Comment by fosron** [comment]
Thanks!
