### ISSUE TITLE
How to choose colomn?

### ISSUE THREAD

**Issue by bukatoff** [sequelpro/sequelpro#2928]
Hello!

I want to choose several cells in colomn. And copy it to other colomn. When I select its select rows. How to select some info from name and copy it to other?
![image](https://user-images.githubusercontent.com/33782655/32980365-08a6157e-cc76-11e7-81c7-fc724df0e54c.png)

**Comment by dmoagx** [comment]
You can't. This is a limitation of macOS' table UI.
Duplicate of #2313
