### ISSUE TITLE
Undo falsely says there is a syntax error in the code. Cut-Paste the same and it works

### ISSUE THREAD

**Issue by ramesh-katreddi** [sequelpro/sequelpro#2931]
I have run this aggregation query. 
select sum(a) from table_name where b='TEXT_TO_UNDO' 

Then 

select sum(a) from table_name where b='NEW_TEXT' 

Now when I do cmd + z ( = number of letters in NEW_TEXT times)

select sum(a) from table_name where b='TEXT_TO_UNDO' 

But at this point if I run "Run Selection"

it says "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'TEXT_TO_UNDO' at line 1"

Select the same statement -> cut -> paste

It will work well again. 

Version: 

Sequel Pro 1.1.2

Build 4541 ( 602e11a)

**Comment by dmoagx** [comment]
Undo also restores your selection, so if you selected "TEXT_TO_UNDO" and then started typing over it, undo will restore "TEXT_TO_UNDO" and it will also be selected again.

And "Run Selection" does exactly what its name says: It runs the selected query, which in your case is "TEXT_TO_UNDO".
