### ISSUE TITLE
Problem with utf8mb4 import into Sequel PRO

### ISSUE THREAD

**Issue by seabasss** [sequelpro/sequelpro#2932]
I'm using the Encoding UTF-8 Unicode (utf8mb4) and Collation utf8mb4_unicode_520_ci for both tables and fields in my MySQL database.

When I export the database from Sequel Pro and open the exported .sql file in a text editor my test character 𝌆 appears correctly, but when I import the file back into Sequel Pro it appears as ????

In the import window I've tried Autodetect and Unicode (UTF-8) without success (there is no utf8mb4 option). I've also tried Preferences > Default Encoding > Autodetect|utf8|utf8mb4 without success. utf8 or utf8mb4 as default encoding gives me a single ? both for export and import, while autodetect gives me the actual character in the export, but ???? on import.

Any ideas? Here's a picture of what I'm trying to do. It seems like my "odd" character is on track all the way until I'm trying to import the .sql file back into Sequel PRO.

![encoding_preview-1](https://user-images.githubusercontent.com/5793864/33399672-c1e7288a-d553-11e7-8ce3-99975e219a86.jpg)

**Comment by dmoagx** [comment]
Before importing run this query:
```sql
set sql_mode = 'STRICT_ALL_TABLES';
```

This will make the import fail with an error. Please post the error message.

**Comment by seabasss** [comment]
How do I do that? I tried to run it under the Query tab in Sequel PRO, but nothing happens on import.
I also pasted it at the top of the .sql file and no errors.

**Comment by seabasss** [comment]
@dmoagx Ok, I pasted everything inside the Query tab and now I got `Incorrect string value: '\xF0\x9D\x8C\x86' for column 'note' at row 477`. If I open the .sql file that character is 𝌆

**Comment by seabasss** [comment]
@dmoagx Thank you again for helping out. Do you know how I can use the error message?

**Comment by dmoagx** [comment]
`\xF0\x9D\x8C\x86` is the correct UTF-8 value of 𝌆.
That means MySQL receives the correct value from SP but can't interpret it.
This could either be because the the connection is not using `utf8mb4` charset (check that via Database > Show Server Variables > Search for "char") or the destination column type is not using `utf8mb4` and can't store the value.

**Comment by seabasss** [comment]
@dmoagx Aha, one step closer!

> character_set_client = utf8
character_set_connection = utf8
character_set_database = utf8mb4
character_set_filesystem = binary
character_set_results = utf8
character_set_server = latin1
character_set_system = utf8
character_sets_dir = /usr/local/mysql-5.7.17-macos10.12-x86_64/share/charsets/
session_track_system_variables = time_zone,autocommit,character_set_client,character_set_results,character_set_connection

This is on my local server on my mac. Do I need to change that in the server, not in Sequel PRO? Thanks!

**Comment by dmoagx** [comment]
`character_set_connection` is the important one. That one is controlled by Sequel Pro and SP will by default switch to the charset of the currently selected table (or `utf8` if no table has been selected), unless you have disabled automatic detection in Preferences > Default Charset.

Also note that SP 1.1.2 cannot export `utf8mb4` SQL files. You'll have to _at least_ manually change the line
```sql
/*!40101 SET NAMES utf8 */;
```
to read
```sql
SET NAMES utf8mb4;
```

**Comment by seabasss** [comment]
@dmoagx Thanks! Makes sense. Yeah, now my 𝌆 gets exported as ? in the sql file
So in 1.1.2 there is no way around this? Do you think there will be an update that can export utf8mb4?

Any other way to export all the data with correct characters? Thanks again!

**Comment by dmoagx** [comment]
The test builds already support utf8mb4 exports (as will the 1.2 release).
Other than that `mysqldump` should be the preferred tool for SQL exports.

**Comment by seabasss** [comment]
@dmoagx Sound good! Thanks! I'll wait for the 1.2 release.

**Comment by dmoagx** [comment]
Closing issue, since there is nothing left to be done here.

**Comment by montchr** [comment]
Considering this is still an issue in the stable release 1.1.2, should this issue be re-opened?

**Comment by ghost** [comment]
Is this still an issue? I tried exporting but still appears as question mark in exported sql file and also when imported to other db

**Comment by sameera-dot** [comment]
This is still open and I am still facing it. I am using version 1.1.2 (Build 4541)

`30 Jun 2024 at 11:28:58 AM: SPMySQL Framework has encountered the MySQL encoding 'utf8mb3' which it is unable to process correctly; falling back to UTF8 mapping.
`
