### ISSUE TITLE
JSON detection and editing

### ISSUE THREAD

**Issue by jpike88** [sequelpro/sequelpro#2934]
It's common nowadays for serialised JSON/XML/etc to be stored in cells. Would be great for a built in JSON editor to detect and format them for any inline tweaking.

**Comment by calumk** [comment]
+1 on this

**Comment by 7ammer** [comment]
MySQL has a JSON data type now.
https://dev.mysql.com/doc/refman/8.0/en/json.html

It would be nice to see this formatted for easier reading.

Cheers

**Comment by ralbear** [comment]
`JSON` column type was available from `5.7` actually!
