### ISSUE TITLE
CMD+N when editing favourite queries deletes non-global group and contained favourites

### ISSUE THREAD

**Issue by dergab** [sequelpro/sequelpro#2937]
Somehow (since somewhen) I had a "Untitled 1" group in favourites editing view (apart from the "Global" one). Changing the name or order of these groups wasn't possible, though.

As I have quite a lot of favourite queries, I decided to move some of them into the "Untitled 1" group. Which worked. They were shown in these groups as well in the favourite-queries drop-down in the query editor.

Having achieved this, I tried to create another group by pressing CMD+N in the edit favourites view. This caused a second Sequel Pro window to be opened. In the second window I opened a connection and navigated to the edit favourites view. It only showed the "Global" group and a new (empty) "Untitled 2" group. All favourites which I previously had moved to "Untitled 1" group (in the first Sequel Pro window) weren't there. So I closed the second window and clicked on "Save" in the still open edit-favourites view of the first window. This caused a "Sequel Pro encountered an unexpected error." report-dialog to be opened (which I "send"). The (first) Sequel Pro window was still open, the favourites drop-down still showed my favourite ("Global" + "Untitled 1") groups and related queries. But once I closed this Sequel Pro window and opened a new one, only the "Global" and (empty) "Untitled 2" groups were there. "Untitled 1" and related queries were gone.

As I found out the favourite queries are stored in ``` /Users/<USER>/Library/Preferences/com.sequelpro.SequelPro.plist```, so I used timemachine to recover one of the previous versions.

I'm using a MacBook Pro (Retina, early 2015) with macOS 10.13.1 and Sequel Pro 1.1.2.

**Comment by dmoagx** [comment]
"Untitled 1" is the name of your current session document. You moved the favorites from the global store to the per-session store and then closed the session window without saving the session document thus losing the query favorites in that document.
When you opened a new connection window, you created a new session document called "Untitled 2".

Session documents are a rather obscure feature of SP, but it should've asked about saving the changes made to the "Untitled 1" document.

**Comment by dmoagx** [comment]
Also, did you include an e-mail address or a comment when you submitted the crash report?

**Comment by dergab** [comment]
Well, I clicked on "Save" (at the end) in the edit favourites view/window. Or should I've seen an additional save-dialog?

Unfortunately I didn't input my email address when sending the error report. And for whatever reason I can't reproduce the error-report dialog. Yesterday it showed up several times. Today - without having restarted the system or such alike - it just doesn't come up anymore.

**Comment by dmoagx** [comment]
I think I found the crash report and also the cause: It will happen when you close the edit favorites sheet via "Save" while there is an unconnected window in the background.
That is unrelated issue #2266 though.
