### ISSUE TITLE
Code signature mismatch detected. The matching rule is therefore not being applied.

### ISSUE THREAD

**Issue by wearymax** [sequelpro/sequelpro#2945]
My Little Snitch catch a code signature by an unknown developer, but the process is now signed by a developer with identifier Y48LQG59RS. This could mean that the application was replaced by another one from a different developer. The matching rule is therefore not being applied.

![screen shot 2017-12-04 at 21 30 19](https://user-images.githubusercontent.com/31094125/33569388-8bc35ce8-d93a-11e7-9cb9-10e951561079.png)

**Comment by dmoagx** [comment]
Y48LQG59RS is the correct TeamIdentifier for release versions.
