### ISSUE TITLE
When I put space after my username, I could not log in.

### ISSUE THREAD

**Issue by jun-oka** [sequelpro/sequelpro#2946]
If there are spaces after the username when I log in from the desktop app on Mac, I could not log in even when I put right username.
Can I try to fix it and make PR?

**Comment by dmoagx** [comment]
I just tried:
```sql
CREATE USER 'space '@'localhost' IDENTIFIED BY '1234';
```
On Mysql 5.5 and 5.7.9 the trailing space is silently discarded, even when the user name is quoted.
However I can't find a clear mention of this behavior in the MySQL docs (or source code).
Also the `mysql` cli client will still pass a trailing space to the server and the server does not remove it this time:
```
$ mysql -u 'space ' -p -h 192.168.14.141
Enter password: 
ERROR 1045 (28000): Access denied for user 'space '@'192.168.14.1' (using password: YES)
```

Personally I think highlighting a trailing space would be better than removing it, but that's even more effort.

**Comment by dmoagx** [comment]
Ok, silly me.
The username is stored in a `CHAR` column and those columns always drop trailing spaces upon **retrieval**: https://dev.mysql.com/doc/refman/5.7/en/char.html
