### ISSUE TITLE
Upgrading from macOS 10.13.2 beta to 10.13.2 final results in error -25293

### ISSUE THREAD

**Issue by fredsted** [sequelpro/sequelpro#2948]
![Link to screenshot](https://static.easir.com/simon/171208-104927_icq5b.png)

All  the saved passwords disappeared after upgrading, and I started getting this error after clicking `Save changes` when I tried to re-insert the passwords.

What can I do to fix this? How can I provide you guys with more information to debug this?

**Comment by dmoagx** [comment]
`-25293` is `errSecAuthFailed`.
So Sequel Pro can find the item in Keychain, but Keychain denies access.
This is most likely a bug on Apple's side or Keychain corruption - not much we can do there.

Have you tried rebooting?

**Comment by fredsted** [comment]
@dmoagx  After a reboot all the logins are back. Thanks for the tip.

**Comment by Positvman** [comment]
![image](https://user-images.githubusercontent.com/13162479/38979924-17333e9c-43ee-11e8-88f1-a3adbb6db137.png)

**Comment by Positvman** [comment]
MAC upgrade to 10.13.4 sequel pro save password when the error, restart the database information back, but the password did not come back, again to enter or to the errors, if there is a solution Thank you very much
