### ISSUE TITLE
TEXT gets imported as MEDIUMTEXT in 1.1.2

### ISSUE THREAD

**Issue by seabasss** [sequelpro/sequelpro#2950]
I have some TEXT columns that gets exported as "text" to a .sql file, but when I import it again it converts to MEDIUMTEXT instead. Is there a setting somewhere where I turn this off?

I don't remember it happening when I was using utf8 before, but now it is once going utf8mb4 (not 100% sure about this though).

Ideas? Thank you!

**Comment by dmoagx** [comment]
I've never seen something like that.
Have you tried importing the file with the `mysql` CLI client instead? What result does that give?

**Comment by seabasss** [comment]
@dmoagx Thank you! I have not tried that. Is there an easy way to in OS X?

It almost seems like it’s analyzing the data and picks an optimized field type based on that. Which made me think that it’s a setting in Sequel Pro. My data might fit in a mediumtext, but future posts might not so it shouldn’t change.

Thanks for ideas.

**Comment by dmoagx** [comment]
Sequel Pro does not change anything during import.
The mysql CLI is included, e.g. with MAMP. To import a file do
```
 /Applications/MAMP/Library/bin/mysql -u user -h host -p database < import_file.sql
```

**Comment by dmoagx** [comment]
Closing after no feedback from reporter.
