### ISSUE TITLE
nightly builds "pending" for the last 3 months

### ISSUE THREAD

**Issue by vesper8** [sequelpro/sequelpro#2953]
Just wondering how come the latest nightly build is 3 months old and the last 5 builds are marked as "pending" ?

https://sequelpro.com/nightly

On a related note, I tried to build from source following the simple instructions laid out in the readme.. on Xcode 9.2. Couldn't get it to work on a fresh install of Xcode 9.2. "Run" is greyed out and I couldn't find the reason why. Nothing out of place in "Manage Schemes" either

**Comment by dmoagx** [comment]
I had no problems building on Xcode 9.2 beta / 10.13 so far.

**Comment by wojtekcz** [comment]
Still "pending" on Feb 27th :-(

**Comment by dmoagx** [comment]
Yes, and the crash reports server also has...crashed.
Well maybe that's a good thing both are down, so we won't miss any crash reports at least 🙈

**Comment by timlinde** [comment]
Its been 3 months now. Is someone going to look into this, or should we just build it ourselves these days in Xcode?

**Comment by anotherdevs** [comment]
Hi @dmoagx 

You closed the other issue, but didn't answer @timlinde.

I have been running an old nightly build, but I am eager to update. Is the server up and running again?

Circle CI give open source projects build ressources: https://circleci.com/pricing/

Travis CI give away for open source projects as well: https://travis-ci.com/plans

**Comment by dmoagx** [comment]
@anotherdevs I don't have access to the server, so I can't answer that question. But since this issue is still open, there is no need to create a second one.

**Comment by ngocphamm** [comment]
Because I don't use and don't want to install Xcode, I tried to make Travis CI to be the builder for me, and I was able to get a green build status after a few blindly tries. If I can just make it release the built app somehow, it would be incredible 😆 I just don't know anything about building an app with Xcode at all.

https://github.com/ngocphamm/sequelpro/blob/20258fc01f11ffcee570a5cdbd03472e35faf571/.travis.yml

**Comment by robertoschwald** [comment]
So its July '18 now and still the buildservers don't work. We badly need nightlies, especially for the Mojave fixes to test them.

**Comment by stuconnolly** [comment]
Nightly builds are now back up and running:

https://sequelpro.com/test-builds

**Comment by mmplanet** [comment]
This should be reopened, pending for over a month now.

**Comment by rowanbeentje** [comment]
I've checked the build server and that's running but unable to talk to the build coordinator - @stuconnolly I've tried to login to that buildbot instance but don't think I have SSH access any more, could you give the server a restart? 🙇

**Comment by briantully** [comment]
any updates or has this project been abandoned?

**Comment by jpike88** [comment]
It’s dead. Use tableplus

**Comment by robertoschwald** [comment]
I switched to Querious recently. This project is dead.
