### ISSUE TITLE
SPMySQL Framework - Can't run multiple statements separated by semicolon within a single call 

### ISSUE THREAD

**Issue by alex-techlab** [sequelpro/sequelpro#2956]
Does the SPMySQL framework support running multiple sql statements separated by semicolon?

For example I have several CREATE TABLE statements separated by semicolon and I'm trying to send them all in one go using the SPMySQLConnection.queryString method. 

The problem I have is that If i execute each CREATE statement separately using the queryString method it works, but when I put them all in a single String variable I get a syntax error.

Below is a sample of a semicolon separated set of statements that throws errors:

```
CREATE TABLE `wp_commentmeta` (
`meta_id` bigint(20) unsigned NOT NULL auto_increment,
`comment_id` bigint(20) unsigned NOT NULL DEFAULT '0',
`meta_key` varchar(255) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
`meta_value` longtext COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
 PRIMARY KEY (`meta_id`),
 KEY `comment_id` (`comment_id`) ,
 KEY `meta_key` (`meta_key`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
CREATE TABLE `wp_term_relationships` (
`object_id` bigint(20) unsigned NOT NULL DEFAULT '0',
`term_taxonomy_id` bigint(20) unsigned NOT NULL DEFAULT '0',
`term_order` int(11) NOT NULL DEFAULT '0',
 PRIMARY KEY (`object_id`, `term_taxonomy_id`),
 KEY `term_taxonomy_id` (`term_taxonomy_id`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
```
When this runs I get a syntax error:

> You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CREATE TABLE `wp_term_relationships`

Running these statements in one go using the command line mysql client works...

**Comment by dmoagx** [comment]
Since SPMySQL is based on libmysqlclient the same restrictions apply: https://dev.mysql.com/doc/refman/5.7/en/c-api-multiple-queries.html
