### ISSUE TITLE
TIMEOUT ISSUE

### ISSUE THREAD

**Issue by lbechdol** [sequelpro/sequelpro#2959]
When I attempt to connect with a remote mysql database via vpn, the connection times out.  How do I lengthen the time allowed to make the connection.  The remote database is hosted on a linux server at work.

**Comment by dmoagx** [comment]
Preferences > Network > Timeout

**Comment by lbechdol** [comment]
Sorry, there is not a choice in preferences for network.

**Comment by dmoagx** [comment]
![bildschirmfoto 2018-01-04 um 21 02 19 444](https://user-images.githubusercontent.com/5793864/34581956-a0c0c9b2-f192-11e7-8e88-6da43f2a9679.png)

**Comment by lbechdol** [comment]
Hi,

Interesting.  I don’t see the tabs when I visit this SSH screen.  I’m not using SSH since I am using VPN as my security tunnel.  Here is what I see:

[cid:C7130DED-80DF-452F-B652-76F217403D1F]

Larry

On Jan 4, 2018, at 2:02 PM, Max Lohrmann <notifications@github.com<mailto:notifications@github.com>> wrote:


[bildschirmfoto 2018-01-04 um 21 02 19 444]<https://user-images.githubusercontent.com/5793864/34581956-a0c0c9b2-f192-11e7-8e88-6da43f2a9679.png>

**Comment by igor-kamil** [comment]
same problem here. It's timing out when connecting using SSH + VPN

**Comment by dmoagx** [comment]
@lbechdol You can't include screenshots when replying by mail. Post it again via the GitHub website.

@igor-kamil So...have you changed the timeout setting?

**Comment by igor-kamil** [comment]
@dmoagx I already updated my answer above ↑. sorry for chaos. also nice to see you react promptly!

**Comment by lbechdol** [comment]
No I have not changed the timeout setting, because I don't see the same screen you sent to me.  On my copy of the program there is no place to change the timeout setting.  Here is the screen shot I tried to send before.
![2018-01-04_14-16-14](https://user-images.githubusercontent.com/26870401/34915345-9bc66a7a-f8ea-11e7-9928-a4d9150a74f0.png)

**Comment by dmoagx** [comment]
Yeah, that's what I though: That is not Sequel Pro.
Perhaps you've fallen for the marketing ploy of our competitor "SQL Pro"?

**Comment by lbechdol** [comment]
Apparently so. I had no idea there are two companies with same “name”

I’ll check further when I’m home from my day trip

Thanks for your help.

Sent from my iPhone

On Jan 14, 2018, at 11:36 AM, Max Lohrmann <notifications@github.com<mailto:notifications@github.com>> wrote:


Yeah, that's what I though: That is not Sequel Pro.
Perhaps you've fallen for the marketing ploy of our competitor "SQL Pro"?
