### ISSUE TITLE
Open multiple connections

### ISSUE THREAD

**Issue by davidcv91** [sequelpro/sequelpro#2967]
Hi, is there an option to open multiple connections at the same time?

If there is no way to do this, it would be very useful for me if you add this feature in the future, please.

I manage several databases hosted on different servers, and sometimes I have to run the same query opening several connections one by one.

**Comment by dmoagx** [comment]
You can manually open the connections, then go to File > Save Session and use that session file in the future.

**Comment by davidcv91** [comment]
@dmoagx Thank you! I will try this option.
