### ISSUE TITLE
Problem with SequelPro - Hangs on attempting to move screen

### ISSUE THREAD

**Issue by s-miller** [sequelpro/sequelpro#2972]
Sequel Pro installed and initially worked fine with sakila db.
Have now added a second db and find that I can't move the window without the pinwheel appearing and CPU going up to above 50% and often approaching 100%.  Just to be clear, I'm not running any queries, just trying to move the window.
All other applications working fine (altho obviously impacted by the high CPU spikes)
Uninstall/reinstall has not resolved (including deleting  ~/Library/Preferences/com.sequelpro.SequelPro.plist 
and
~/Library/Application Support/Sequel Pro )
Unable to find report of similar issues anywhere.
OS is High Sierra 10.13.3.

**Comment by dmoagx** [comment]
When it hangs, launch Activity Monitor, select Sequel Pro and go to View > Sample Process and post the result here.

**Comment by s-miller** [comment]
Shortly after reporting this, I ended up with widespread faults across the machine (to the point it became unuseable after a few days).  
Given the above info, and that no one else has reported a similar fault to this, it is possible that this was machine related, rather than the app (despite, at the time, only occurring with SequelPro) .  
Unfortunately, I can't investigate with Activity Monitor as machine has now gone for rebuild - apologies.
