### ISSUE TITLE
No Retina Icons

### ISSUE THREAD

**Issue by tomatoTom** [sequelpro/sequelpro#2974]
<img width="169" alt="bildschirmfoto 2018-02-01 um 09 48 32" src="https://user-images.githubusercontent.com/17672858/35669357-1dd893d2-0735-11e8-9b48-cd8dca827e8d.png">

<img width="345" alt="bildschirmfoto 2018-02-01 um 09 48 20" src="https://user-images.githubusercontent.com/17672858/35669358-1df37968-0735-11e8-891d-912684c30f8e.png">

**Comment by stuconnolly** [comment]
Duplicate of #1432 

We just need to get nightly builds back up and running and a release out... (see #3034).
