### ISSUE TITLE
Feature request: allow an SSH tunnel (SSH host) on a non-standard port

### ISSUE THREAD

**Issue by jasonfb** [sequelpro/sequelpro#2975]
This may be a support question or a Feature request.

I am attempting to make a MysQL connection through an SSH tunnel (SSH host). unfortunately, the SSH host requires that the SSH connection itself come in on port 80, not the standard 22. 

Other SQL GUIs (I have consulted with my colleagues) allow this by parsing the SSH Host by the proper colon syntax, so you'd use
```x.x.x.x:80```

to create the SSH tunnel on port 80.

Alternatively, the interface could provide an explicit port for the SSH tunnel

when I attempt the server setup using the colon (not pasting here to keep my client's IP confidential), I get this 

(Note: I have obscured my client's IP by replacing it with 255.255.255.255 but all other output is the same)

```
Used command:  /usr/bin/ssh -v -N -S none -o ControlMaster=no -o ExitOnForwardFailure=yes -o ConnectTimeout=10 -o NumberOfPasswordPrompts=3 -i /Users/jason/.ssh/id_rsa -o TCPKeepAlive=no -o ServerAliveInterval=60 -o ServerAliveCountMax=1 deploy@255.255.255.255:80 -L 60010:192.168.3.1:3306

OpenSSH_7.4p1, LibreSSL 2.5.0
debug1: Reading configuration data /Users/jason/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Control socket " none" does not exist
ssh: Could not resolve hostname 255.255.255.255: nodename nor servname provided, or not known
```

although the message says ```255.255.255.255:``` (notice the colon) "nodename nor servname provided", this is actually because of the colon not because the IP can't resolve (like I said, the IP resolves and 255.255.255.255 is NOT the real IP)

when I remove the ```:80``` from the SSH host, I get this instead:

```
debug1: Reading configuration data /Users/jason/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Control socket " none" does not exist
debug1: Connecting to 255.255.255.255 [77.239.105.111] port 22.
debug1: connect to address 255.255.255.255 port 22: Operation timed out
ssh: connect to host 255.255.255.255 port 22: Operation timed out
```

(Again I have obscured my client's IP, the IP works fine to resolve).

This is because SSH port 22 is not enabled on the tunnel box. 

Can anything be done to Sequel Pro to address this or add this a feature?

**Comment by dmoagx** [comment]
Huh?
![bildschirmfoto 2018-02-01 um 21 54 42 498](https://user-images.githubusercontent.com/5793864/35702887-a5c295c6-079a-11e8-8ae7-bc0e9df94535.png)

**Comment by jasonfb** [comment]
doh!
