### ISSUE TITLE
Connect using SSL - causing app to freeze

### ISSUE THREAD

**Issue by TheDigitalOrchard** [sequelpro/sequelpro#2980]
For an existing (saved) SSH configuration, choosing "Connect using SSL" causes the app to freeze.

1. Set up a connection via SSH.
2. Save.
3. Tick the checkbox for "Connect using SSL"
(freeze occurs)

Reproduced multiple times with two separate SSH connections.

Attached is a process sample.

[Sequel Pro - Connect using SSL.txt](https://github.com/sequelpro/sequelpro/files/1715122/Sequel.Pro.-.Connect.using.SSL.txt)

**Comment by dmoagx** [comment]
That sample looks like Sequel Pro is pretty much idle.
There is no indication of a connection attempt or any code from SP involved at all.

Are you sure that you took the sample while the app was frozen?
Do the close/minimize/maximize buttons still animate when you hover over them?

**Comment by TheDigitalOrchard** [comment]
Sorry for the late reply. Was not notified of your message.

Tried exact same steps on March 14th (today) and same thing occurred. Attached is a new sample while the app is frozen / not responding.

[Sample of Sequel Pro (March 14).txt](https://github.com/sequelpro/sequelpro/files/1813843/Sample.of.Sequel.Pro.March.14.txt)

**Comment by dmoagx** [comment]
* Do the close/minimize/maximize buttons still animate when you hover over them?
* Does this happen once you click on the "Connect using SSL" checkbox or when you click on the "Connect" button?

**Comment by dmoagx** [comment]
No feedback from reporter in 30 days -> closing
