### ISSUE TITLE
add support to open/edit/save and run queries form a text file

### ISSUE THREAD

**Issue by virtualintegrity** [sequelpro/sequelpro#2986]
Could you please add support to open/edit/save and run queries form a text file? In a lot of cases it's much more convenient to work with text files instead of spf as it give flexibility to edit those from any editor and run queries from shell

**Comment by dmoagx** [comment]
Sequel Pro can do all of that already. You can just open .sql-Files, edit them in the query editor and save them again via File > Save Query.
The problem is much rather that Sequel Pro does not show that you are editing a file.
