### ISSUE TITLE
mysql5-15.pro host with instant "Unknown MySQL server host"

### ISSUE THREAD

**Issue by mattcabb** [sequelpro/sequelpro#2988]
When connecting with `mysql5-15.pro ` 10 second timeout is ignored, goes straight to error message. Can't establish connection with DB.

**Comment by dmoagx** [comment]
https://github.com/sequelpro/sequelpro/wiki/How-do-I-write-a-proper-issue-report%3F

**Comment by dmoagx** [comment]
No feedback from reporter in 30 days -> closing
