### ISSUE TITLE
Sequel pro is too slow in performance

### ISSUE THREAD

**Issue by rbncha** [sequelpro/sequelpro#2990]
Hi,

Recently Sequel Pro is way slow opening the app, selecting db, tables, moving around tabs of table, querying. Am I only one facing this ? Here is screen record to show how it is : https://www.useloom.com/share/02f5c762217b4dbf865832d06a3a09da

Thanks

**Comment by dmoagx** [comment]
You most likely have a huge query in your query history. Try clearing it.

**Comment by rbncha** [comment]
Yeah! clearing history made it faster again. But I wished those query history be there.

Thankx @dmoagx

**Comment by dmoagx** [comment]
Duplicate of #687
