### ISSUE TITLE
Cannot connect to mysql 8.0

### ISSUE THREAD

**Issue by cpapidas** [sequelpro/sequelpro#2991]
I am trying to connect to mysql 8.0 and I got the following error.

Unable to connect to host 127.0.0.1, or the request timed out.

Be sure that the address is correct and that you have the necessary privileges, or try increasing the connection timeout (currently 10 seconds).

MySQL said: Authentication plugin 'caching_sha2_password' cannot be loaded: dlopen(/usr/local/lib/plugin/caching_sha2_password.so, 2): image not found

**Comment by cpapidas** [comment]
After start mysql with `-default-authentication-plugin=mysql_native_password` everything is fine on login. 

But after this I get the following error:

```
NSInvalidArgumentException

-[_NSInlineData isEqualToString:]: unrecognized selector sent to instance 0x600000e45520

(
	0   CoreFoundation                      0x00007fff5788800b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff7e464c76 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff57920cd4 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff577fe3f0 ___forwarding___ + 1456
	4   CoreFoundation                      0x00007fff577fddb8 _CF_forwarding_prep_0 + 120
	5   Sequel Pro                          0x000000010002fce3 -[SPDatabaseDocument setDatabases:] + 783
	6   Sequel Pro                          0x00000001000f3681 -[SPWindowController performSelector:withObject:] + 172
	7   AppKit                              0x00007fff5557c75a -[NSApplication(NSResponder) sendAction:to:from:] + 312
	8   AppKit                              0x00007fff550115f7 -[NSMenuItem _corePerformAction] + 323
	9   AppKit                              0x00007fff5501137f -[NSCarbonMenuImpl performActionWithHighlightingForItemAtIndex:] + 114
	10  AppKit                              0x00007fff55096fba -[NSMenu performActionForItemAtIndex:] + 133
	11  AppKit                              0x00007fff55096f25 -[NSMenu _internalPerformActionForItemAtIndex:] + 94
	12  AppKit                              0x00007fff55096d55 -[NSCarbonMenuImpl _carbonCommandProcessEvent:handlerCallRef:] + 106
	13  AppKit                              0x00007fff54f5d6b2 NSSLMMenuEventHandler + 882
	14  HIToolbox                           0x00007fff56af2814 _ZL23DispatchEventToHandlersP14EventTargetRecP14OpaqueEventRefP14HandlerCallRec + 1541
	15  HIToolbox                           0x00007fff56af1b5d _ZL30SendEventToEventTargetInternalP14OpaqueEventRefP20OpaqueEventTargetRefP14HandlerCallRec + 374
	16  HIToolbox                           0x00007fff56b06e61 SendEventToEventTarget + 39
	17  HIToolbox                           0x00007fff56b50489 _ZL18SendHICommandEventjPK9HICommandjjhPKvP20OpaqueEventTargetRefS5_PP14OpaqueEventRef + 411
	18  HIToolbox                           0x00007fff56b793be SendMenuCommandWithContextAndModifiers + 49
	19  HIToolbox                           0x00007fff56b7937a SendMenuItemSelectedEvent + 188
	20  HIToolbox                           0x00007fff56b79254 _ZL19FinishMenuSelectionP13SelectionDataP10MenuResultS2_ + 96
	21  HIToolbox                           0x00007fff56c91b9c _ZL19PopUpMenuSelectCoreP8MenuData5PointdS1_tjjPK4RecttjS4_S4_PK14__CFDictionaryPK10__CFStringPP13OpaqueMenuRefPt + 1662
	22  HIToolbox                           0x00007fff56c91017 _ZL26_HandlePopUpMenuSelection8P13OpaqueMenuRefP14OpaqueEventRefj5PointtjjPK4RecttS6_S6_PK14__CFDictionaryPK10__CFStringPS0_Pt + 409
	23  HIToolbox                           0x00007fff56b594bc _HandlePopUpMenuSelectionWithDictionary + 268
	24  AppKit                              0x00007fff5508dada _NSSLMPopUpCarbonMenu3 + 5632
	25  AppKit                              0x00007fff5508c434 -[NSCarbonMenuImpl popUpMenu:atLocation:width:forView:withSelectedItem:withFont:withFlags:withOptions:] + 439
	26  AppKit                              0x00007fff550fc59c -[NSPopUpButtonCell trackMouse:inRect:ofView:untilMouseUp:] + 570
	27  AppKit                              0x00007fff5501fa64 -[NSControl mouseDown:] + 965
	28  AppKit                              0x00007fff5571b959 -[NSWindow(NSEventRouting) _handleMouseDownEvent:isDelayedEvent:] + 5891
	29  AppKit                              0x00007fff557185b0 -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] + 2359
	30  AppKit                              0x00007fff5571785c -[NSWindow(NSEventRouting) sendEvent:] + 497
	31  Sequel Pro                          0x000000010012e644 -[SPWindow sendEvent:] + 783
	32  AppKit                              0x00007fff55578617 -[NSApplication(NSEvent) sendEvent:] + 307
	33  AppKit                              0x00007fff54dd9d9d -[NSApplication run] + 812
	34  AppKit                              0x00007fff54da8f1a NSApplicationMain + 804
	35  Sequel Pro                          0x0000000100002454 start + 52
	36  ???                                 0x0000000000000001 0x0 + 1
)
```

**Comment by cpapidas** [comment]
Fix at https://sequelpro.com/test-builds

**Comment by dmoagx** [comment]
Duplicate of #2699

**Comment by hasidiluk** [comment]
I got the same problem and I fixed it by using below mysql command.

`ALTER USER username@host IDENTIFIED WITH mysql_native_password BY 'password';`

**Comment by hos4m** [comment]
This issue is because you're using the new `Strong Password Encryption` which is a new feature in MySQL 8, if you installed MySQL 8 using the `.dmg` file, you can go to `System Preferences > MySQL` and then click on `Initialize Database` type your password and select the second option `Use Legacy Password Encryption`.

**Comment by voquanghoa** [comment]
> This issue is because you're using the new `Strong Password Encryption` which is a new feature in MySQL 8, if you installed MySQL 8 using the `.dmg` file, you can go to `System Preferences > MySQL` and then click on `Initialize Database` type your password and select the second option `Use Legacy Password Encryption`.

Thanks, it works for me!!

**Comment by ricalvesa** [comment]
> This issue is because you're using the new `Strong Password Encryption` which is a new feature in MySQL 8, if you installed MySQL 8 using the `.dmg` file, you can go to `System Preferences > MySQL` and then click on `Initialize Database` type your password and select the second option `Use Legacy Password Encryption`.

How can it be done while keeping strong encryption enabled?

**Comment by dmoagx** [comment]
@ricalvesa #3037

**Comment by luffyke** [comment]
i met the same issue just now, my gitea version is 1.5.3 and still get the same error after updating mysql user to native password.
```
ALTER USER 'gitea'@'%' IDENTIFIED WITH mysql_native_password BY 'newpassword'
```

It's normal now after upgrading gitea to 1.6.1 version, maybe 1.6.1 update some deps, don't know the details.

**Comment by s2t2** [comment]
If anyone has concerns about changing the auth mechanism for their root user, try creating a new user just for logging into sequel pro:

```sql
CREATE USER 'sequelpro'@'localhost' IDENTIFIED BY '_______';
ALTER USER 'sequelpro'@'localhost' IDENTIFIED WITH mysql_native_password BY '______';
```

ht/: https://github.com/sequelpro/sequelpro/issues/2991#issuecomment-418645475

**Comment by mr-z-ro** [comment]
Still seeing this issue in Sequel Pro 1.1.2, but I see this ticket is closed.

Is the official Sequel Pro recommendation still to disable MySQL's default auth features? Because frankly, that doesn't really seem like a solution to me, so much as a band-aid. But maybe I'm missing something?

**Comment by WesleyVestjens** [comment]
I agree with @mr-z-ro, I sure hope this issue is still on the radar to resolve, downgrading security because of missing features is dangerous.

**Comment by mr-z-ro** [comment]
@WesleyVestjens it's worth noting here that [Sequel Ace](https://github.com/Sequel-Ace/Sequel-Ace), which is an actively developed community fork of Sequel Pro, has addressed this issue and that development of Sequel Pro itself is more or less stagnant at this point. Sorry I didn't follow up on my last comment earlier, but hopefully that works for you.

**Comment by kosternokke** [comment]
> > This issue is because you're using the new `Strong Password Encryption` which is a new feature in MySQL 8, if you installed MySQL 8 using the `.dmg` file, you can go to `System Preferences > MySQL` and then click on `Initialize Database` type your password and select the second option `Use Legacy Password Encryption`.
> 
> Thanks, it works for me!!

thanks !
