### ISSUE TITLE
MariaDB two-factor authentication

### ISSUE THREAD

**Issue by AskeFC** [sequelpro/sequelpro#2995]
We recently enabled two-factor authentication on our database, running MariaDB version 10.2.13.
Here we have windows, linux and mac clients accessing the database and we specifically have problems with Sequel Pro because it does not support two-factor authentication.
I have read from previous issue discussions that Sequel Pro will not enable MYSQL_ENABLE_CLEARTEXT_PLUGIN but I guess it should not pose a problem in this case.
Anyway, I think it would be appropriate for Sequel Pro here in 2018 to support a sufficient level of security, so I would assume this classifies as more than a mere feature request.

**Comment by dmoagx** [comment]
The cleartext plugin is a serious security risk because it makes stealing passwords trivially easy.
So, in order to "to support a sufficient level of security" it is disabled by default.

Also it is still possible to use the plugin: https://github.com/sequelpro/sequelpro/issues/2247#issuecomment-144567527

Duplicate of #2247

**Comment by AskeFC** [comment]
Sorry if my OP was not clear enough...
We do not want to use MYSQL_ENABLE_CLEARTEXT_PLUGIN.
We have two-factor authentication enabled.
We want to use two-factor authentication in Sequel Pro.
Two-factor authentication works on for other DB software.
Is two-factor authentication something Sequel Pro will support ?

**Comment by dmoagx** [comment]
You just specifically asked for support of the cleartext plugin:
> Sequel Pro will not enable MYSQL_ENABLE_CLEARTEXT_PLUGIN but I guess it should not pose a problem in this case.

**Comment by AskeFC** [comment]
I'd really just like to know about two-factor authentication in Sequel Pro.
At the moment connections are refused in Sequel Pro, with error message 'authentication plugin dialog.so could not be loaded', when trying to connect to the DB.
