### ISSUE TITLE
MariaDB two-factor authentication

### ISSUE THREAD

**Issue by AskeFC** [sequelpro/sequelpro#2996]
We recently enabled two-factor authentication on our database, running MariaDB version 10.2.13.
Here we have windows, linux and mac clients accessing the database and we specifically have problems with Sequel Pro because it does not seem to support two-factor authentication.
Connections are refused in Sequel Pro, with error message 'authentication plugin dialog.so could not be loaded', when trying to connect to the DB.

**Comment by dmoagx** [comment]
We could add the dialog plugin. That would basically require some patching of the libmysql source so it is built embedded instead of a dylib and adding the UI code to Sequel Pro to prompt the user.
But the dialog plugin is basically an extended cleartext plugin, so this depends on #2979

**Comment by AskeFC** [comment]
Sounds great!
Would it be safe to expect you could implement it within 2018 or is that unreasonable to ask.

**Comment by dmoagx** [comment]
I've added support for this in the `callback-auth` branch, however:
* I can't test it since I don't have a server with dialog auth at hand
* No idea when/if this will be included in a release (or nightly) build. Your best option is to download Xcode and try to compile it yourself.

**Comment by dmoagx** [comment]
@vuther 
Here is a build with the changes:
[Sequel Pro.zip](https://github.com/sequelpro/sequelpro/files/1813575/Sequel.Pro.zip)

Note that this build is not signed (since it is not an official build) and therefore OS X will block it unless it is launched via right click > Open and you may be prompted whether to allow keychain access.

**Comment by vuther** [comment]
Hi dmoagx,

Thanks for compiling the build! Unfortunately, MySQL is coming back w/ access denied. I'm using the correct password. I tested it w/ command line + HeidiSQL.

However, I'm curious as to why you prompt for the password twice and why you specify a warning message that it's insecure. Using the dialog plugin, passwords are sent encrypted - not in cleartext.

<img width="605" alt="upload" src="https://user-images.githubusercontent.com/13244625/37613937-b2b29afc-2b7f-11e8-9b42-b0b966f26c28.png">

**Comment by dmoagx** [comment]
> Unfortunately, MySQL is coming back w/ access denied.

Did you enter your regular password in the first prompt (in the screenshot) and the second factor in the second prompt? or don't you even see a second prompt?

>  why you specify a warning message that it's insecure. Using the dialog plugin, passwords are sent encrypted - not in cleartext.

No, as I've said above the dialog plugin is just an extended cleartext plugin.
Whatever you pass into it is transmitted as is. This can include the user's password.
`dialog` would only be secure if *ALL* of the following conditions are met:
* SSL/TLS is enabled for the connection
* A server certificate is configured for the connection
* The mysql client library is newer than 5.5.55 (for the 5.5 branch, other branches require different versions); this build of Sequel Pro uses 5.5.59
* Insecure cipher suites are excluded from the cipher suite list (which may currently not be the case by default)

**Comment by vuther** [comment]
Percona's documentation: https://www.percona.com/doc/percona-server/LATEST/management/pam_plugin.html
MariaDB documentation: https://mariadb.com/kb/en/library/development-pluggable-authentication/

I do not see anywhere in the docs about the password being sent over plain-text. In Percona's docs, it says using auth_pam_compat does use plain-text though.

**Comment by dmoagx** [comment]
Well, here is the source code of the dialog plugin from mysql (abbreviated for readability):
```c
  /*
    asking for a password with an empty prompt means mysql->password
    otherwise we ask the user and read the reply
  */
  if ((cmd >> 1) == 2 && *pkt == 0)
    reply= mysql->passwd; // <- the plaintext user password
  else
    reply= ask(mysql, cmd >> 1, (const char *) pkt, reply_buf, sizeof(reply_buf)); // <- display a prompt and get the user's input

  if (!reply) return CR_ERROR;

  /* send the reply to the server */
  res= vio->write_packet(vio, (const unsigned char *) reply, (int)strlen(reply)+1);
```
Original file can be found here: https://github.com/mysql/mysql-server/blob/5.7/plugin/auth/dialog.c

**Comment by dmoagx** [comment]
Perhaps the server does some magic by first using a secure auth plugin and then switching to dialog for the second factor.
Sequel Pro would still display a warning in that case because the dialog plugin *could* transmit the password insecurely.
But I don't have a server to check that.

**Comment by vuther** [comment]
@dmoagx,

Thanks for sending me the code. I'm getting a confirmation from Percona on how it actually works. I'll let you know soon.

**Comment by vuther** [comment]
They said it is sent in clear text. I've been told by them before that it was encrypted. Their documentation also leads someone to believe it's encrypted. 

Is there anyway you can not prompt for the password with the dialog plugin? I think that's an unnecessary step. 

Thanks!

**Comment by vuther** [comment]
Also, the plugin doesn't seem to work. It's access denying when I specify the correct password.

**Comment by dmoagx** [comment]
> Is there anyway you can not prompt for the password with the dialog plugin? 

That will only happen once we implement the SSL checks I mentioned above and have made some changes to the way passwords are stored for security purposes.

> Also, the plugin doesn't seem to work. It's access denying when I specify the correct password.

https://github.com/sequelpro/sequelpro/issues/2996#issuecomment-374321213

**Comment by dmoagx** [comment]
So how many prompts do you see in total and how do they look?

**Comment by vuther** [comment]
First prompt is the security warning asking for a password and the second prompts for my password. It just says "Password"

**Comment by dmoagx** [comment]
@vuther Here is an updated build:
[Sequel Pro.zip](https://github.com/sequelpro/sequelpro/files/1835146/Sequel.Pro.zip)

The only difference is additional debug logging.
After you have tried to log in, open Console.app, search for Sequel Pro and post the results.

**Comment by vuther** [comment]
default  11:52:42.884079 -0400  Sequel Pro  -[SPMySQLConnection(PrivateAPI) _mysqlConnection:wantsPassword:withPlugin:]: --> connection=0x7fc19780e000 plugin=mysql_native_password
default  11:52:42.884197 -0400  Sequel Pro  -[SPMySQLConnection(PrivateAPI) _mysqlConnection:wantsPassword:withPlugin:]: will use delegate <SPDatabaseDocument: 0x7fc19683a600> for password
default  11:52:42.884430 -0400  Sequel Pro  -[SPMySQLConnection(PrivateAPI) _mysqlConnection:wantsPassword:withPlugin:]: passwd=1 length=10
default  11:52:42.884519 -0400  Sequel Pro  -[SPMySQLConnection(PrivateAPI) _mysqlConnection:wantsPassword:withPlugin:]: cLength=10 connectEncodingNS=4
default  11:52:42.884654 -0400  Sequel Pro  -[SPMySQLConnection(PrivateAPI) _mysqlConnection:wantsPassword:withPlugin:]: <--
default  11:52:42.924122 -0400  Sequel Pro  -[SPMySQLConnection(PrivateAPI) _mysqlConnection:wantsPassword:withPlugin:]: --> connection=0x7fc19780e000 plugin=dialog
default  11:52:42.924226 -0400  Sequel Pro  -[SPMySQLConnection(PrivateAPI) _mysqlConnection:wantsPassword:withPlugin:]: will use delegate <SPDatabaseDocument: 0x7fc19683a600> for password
default  11:52:42.924430 -0400  Sequel Pro  -[SPMySQLConnection(PrivateAPI) _mysqlConnection:wantsPassword:withPlugin:]: passwd=0 length=0
default  11:52:43.288588 -0400  Sequel Pro  Not yet implemented.
default  11:52:43.288678 -0400  Sequel Pro  Not yet implemented.
default  11:52:45.822455 -0400  Sequel Pro  Not yet implemented.
default  11:52:45.822547 -0400  Sequel Pro  Not yet implemented.
default  11:52:45.823312 -0400  Sequel Pro  Not yet implemented.
default  11:52:45.823380 -0400  Sequel Pro  Not yet implemented.
default  11:52:45.927450 -0400  Sequel Pro  -[SPMySQLConnection(PrivateAPI) _mysqlConnection:wantsPassword:withPlugin:]: --> connection=0x7fc1958ab000 plugin=mysql_native_password
default  11:52:45.927612 -0400  Sequel Pro  -[SPMySQLConnection(PrivateAPI) _mysqlConnection:wantsPassword:withPlugin:]: will use delegate <SPDatabaseDocument: 0x7fc19683a600> for password
default  11:52:45.927856 -0400  Sequel Pro  -[SPMySQLConnection(PrivateAPI) _mysqlConnection:wantsPassword:withPlugin:]: passwd=1 length=0
default  11:52:45.959311 -0400  Sequel Pro  -[SPMySQLConnection(PrivateAPI) _mysqlConnection:wantsPassword:withPlugin:]: --> connection=0x7fc1958ab000 plugin=dialog
default  11:52:45.959617 -0400  Sequel Pro  -[SPMySQLConnection(PrivateAPI) _mysqlConnection:wantsPassword:withPlugin:]: will use delegate <SPDatabaseDocument: 0x7fc19683a600> for password
default  11:52:45.960008 -0400  Sequel Pro  -[SPMySQLConnection(PrivateAPI) _mysqlConnection:wantsPassword:withPlugin:]: passwd=1 length=0
default  11:52:45.960181 -0400  Sequel Pro  -[SPMySQLConnection(PrivateAPI) _mysqlConnection:dialogPrompt:type:outBuffer:size:]: --> connection=0x7fc1958ab000 prompt=Password:  type=2 buf=0x70000d3df2d0 buf_len=1024
default  11:52:46.238899 -0400  Sequel Pro  Not yet implemented.
default  11:52:46.238996 -0400  Sequel Pro  Not yet implemented.
default  11:52:48.589104 -0400  Sequel Pro  Not yet implemented.
default  11:52:48.589203 -0400  Sequel Pro  Not yet implemented.
default  11:52:48.589898 -0400  Sequel Pro  Not yet implemented.
default  11:52:48.589964 -0400  Sequel Pro  Not yet implemented.
default  11:52:48.592465 -0400  Sequel Pro  -[SPMySQLConnection(PrivateAPI) _mysqlConnection:dialogPrompt:type:outBuffer:size:]: result=1 length=0
default  11:52:48.592543 -0400  Sequel Pro  -[SPMySQLConnection(PrivateAPI) _mysqlConnection:dialogPrompt:type:outBuffer:size:]: cLength=0 connectEncodingNS=4
default  11:52:48.592590 -0400  Sequel Pro  -[SPMySQLConnection(PrivateAPI) _mysqlConnection:dialogPrompt:type:outBuffer:size:]: <-- by using mysql buf=0x70000d3df2d0
default  11:52:49.555703 -0400  Sequel Pro  Not yet implemented.
default  11:52:49.555796 -0400  Sequel Pro  Not yet implemented.

**Comment by dmoagx** [comment]
OK, disregard the "Not yet implemented." lines, that is unrelated.

libmysql first tries to authenticate with `mysql_native_password` (which it always does) and receives a password from Sequel Pro:
```
default  11:52:42.884079 -0400  Sequel Pro  -[SPMySQLConnection(PrivateAPI) _mysqlConnection:wantsPassword:withPlugin:]: --> connection=0x7fc19780e000 plugin=mysql_native_password
default  11:52:42.884197 -0400  Sequel Pro  -[SPMySQLConnection(PrivateAPI) _mysqlConnection:wantsPassword:withPlugin:]: will use delegate <SPDatabaseDocument: 0x7fc19683a600> for password
default  11:52:42.884430 -0400  Sequel Pro  -[SPMySQLConnection(PrivateAPI) _mysqlConnection:wantsPassword:withPlugin:]: passwd=1 length=10
default  11:52:42.884519 -0400  Sequel Pro  -[SPMySQLConnection(PrivateAPI) _mysqlConnection:wantsPassword:withPlugin:]: cLength=10 connectEncodingNS=4
default  11:52:42.884654 -0400  Sequel Pro  -[SPMySQLConnection(PrivateAPI) _mysqlConnection:wantsPassword:withPlugin:]: <--
```
The server then decides that it wants to use `dialog` instead at which point Sequel Pro terminates the connection and opens the warning dialog:
```
default  11:52:42.924122 -0400  Sequel Pro  -[SPMySQLConnection(PrivateAPI) _mysqlConnection:wantsPassword:withPlugin:]: --> connection=0x7fc19780e000 plugin=dialog
default  11:52:42.924226 -0400  Sequel Pro  -[SPMySQLConnection(PrivateAPI) _mysqlConnection:wantsPassword:withPlugin:]: will use delegate <SPDatabaseDocument: 0x7fc19683a600> for password
default  11:52:42.924430 -0400  Sequel Pro  -[SPMySQLConnection(PrivateAPI) _mysqlConnection:wantsPassword:withPlugin:]: passwd=0 length=0
```
After you have confirmed the dialog Sequel Pro reconnects and MySQL will try `mysql_native_password` again, but this time using the password you just entered (which apparently was empty):
```
default  11:52:45.927450 -0400  Sequel Pro  -[SPMySQLConnection(PrivateAPI) _mysqlConnection:wantsPassword:withPlugin:]: --> connection=0x7fc1958ab000 plugin=mysql_native_password
default  11:52:45.927612 -0400  Sequel Pro  -[SPMySQLConnection(PrivateAPI) _mysqlConnection:wantsPassword:withPlugin:]: will use delegate <SPDatabaseDocument: 0x7fc19683a600> for password
default  11:52:45.927856 -0400  Sequel Pro  -[SPMySQLConnection(PrivateAPI) _mysqlConnection:wantsPassword:withPlugin:]: passwd=1 length=0
```
The server then switches to `dialog` and Sequel Pro again prepares the password you just entered:
```
default  11:52:45.959311 -0400  Sequel Pro  -[SPMySQLConnection(PrivateAPI) _mysqlConnection:wantsPassword:withPlugin:]: --> connection=0x7fc1958ab000 plugin=dialog
default  11:52:45.959617 -0400  Sequel Pro  -[SPMySQLConnection(PrivateAPI) _mysqlConnection:wantsPassword:withPlugin:]: will use delegate <SPDatabaseDocument: 0x7fc19683a600> for password
default  11:52:45.960008 -0400  Sequel Pro  -[SPMySQLConnection(PrivateAPI) _mysqlConnection:wantsPassword:withPlugin:]: passwd=1 length=0
```
Then the server requests the password using the password prompt:
```
default  11:52:45.960181 -0400  Sequel Pro  -[SPMySQLConnection(PrivateAPI) _mysqlConnection:dialogPrompt:type:outBuffer:size:]: --> connection=0x7fc1958ab000 prompt=Password:  type=2 buf=0x70000d3df2d0 buf_len=1024
default  11:52:48.592465 -0400  Sequel Pro  -[SPMySQLConnection(PrivateAPI) _mysqlConnection:dialogPrompt:type:outBuffer:size:]: result=1 length=0
default  11:52:48.592543 -0400  Sequel Pro  -[SPMySQLConnection(PrivateAPI) _mysqlConnection:dialogPrompt:type:outBuffer:size:]: cLength=0 connectEncodingNS=4
default  11:52:48.592590 -0400  Sequel Pro  -[SPMySQLConnection(PrivateAPI) _mysqlConnection:dialogPrompt:type:outBuffer:size:]: <-- by using mysql buf=0x70000d3df2d0
```
... where an empty string was entered as password.
So the question is: Did you leave both password dialogs empty?

**Comment by vuther** [comment]
@dmoagx,

No, I inputted the same password for each dialogs.

**Comment by dmoagx** [comment]
OK, it seems there is something strange going on with the text fields, which I'll have to investigate.

Please try it again, but make sure that both input fields have a blue border around them when you type the text.
If they are in focus but don't have a blue border try clicking at the border (where the text cursor turns into a regular cursor)

**Comment by vuther** [comment]
They had the blue borders around the input fields when I submitted.

**Comment by dmoagx** [comment]
Here is another attempt:
[Sequel Pro.zip](https://github.com/sequelpro/sequelpro/files/1869760/Sequel.Pro.zip)

**Comment by vuther** [comment]
So, still not working. Same issue - not correct password. Here's the log:

default  11:11:06.250033 -0400  Sequel Pro  -[SPMySQLConnection(PrivateAPI) _mysqlConnection:wantsPassword:withPlugin:]: --> connection=0x7fe2ab944800 plugin=mysql_native_password
default  11:11:06.250204 -0400  Sequel Pro  -[SPMySQLConnection(PrivateAPI) _mysqlConnection:wantsPassword:withPlugin:]: will use delegate <SPDatabaseDocument: 0x7fe2ab84be00> for password
default  11:11:06.250526 -0400  Sequel Pro  -[SPMySQLConnection(PrivateAPI) _mysqlConnection:wantsPassword:withPlugin:]: passwd=1 length=10
default  11:11:06.250604 -0400  Sequel Pro  -[SPMySQLConnection(PrivateAPI) _mysqlConnection:wantsPassword:withPlugin:]: cLength=10 connectEncodingNS=4
default  11:11:06.250715 -0400  Sequel Pro  -[SPMySQLConnection(PrivateAPI) _mysqlConnection:wantsPassword:withPlugin:]: <--
default  11:11:06.289441 -0400  Sequel Pro  -[SPMySQLConnection(PrivateAPI) _mysqlConnection:wantsPassword:withPlugin:]: --> connection=0x7fe2ab944800 plugin=dialog
default  11:11:06.289567 -0400  Sequel Pro  -[SPMySQLConnection(PrivateAPI) _mysqlConnection:wantsPassword:withPlugin:]: will use delegate <SPDatabaseDocument: 0x7fe2ab84be00> for password
default  11:11:06.289908 -0400  Sequel Pro  -[SPMySQLConnection(PrivateAPI) _mysqlConnection:wantsPassword:withPlugin:]: passwd=0 length=0
default  11:11:06.635302 -0400  Sequel Pro  Not yet implemented.
default  11:11:06.635409 -0400  Sequel Pro  Not yet implemented.
default  11:11:08.969322 -0400  Sequel Pro  Not yet implemented.
default  11:11:08.969421 -0400  Sequel Pro  Not yet implemented.
default  11:11:08.969991 -0400  Sequel Pro  Not yet implemented.
default  11:11:08.970049 -0400  Sequel Pro  Not yet implemented.
default  11:11:09.075291 -0400  Sequel Pro  -[SPMySQLConnection(PrivateAPI) _mysqlConnection:wantsPassword:withPlugin:]: --> connection=0x7fe2ab007400 plugin=mysql_native_password
default  11:11:09.075451 -0400  Sequel Pro  -[SPMySQLConnection(PrivateAPI) _mysqlConnection:wantsPassword:withPlugin:]: will use delegate <SPDatabaseDocument: 0x7fe2ab84be00> for password
default  11:11:09.075780 -0400  Sequel Pro  -[SPMySQLConnection(PrivateAPI) _mysqlConnection:wantsPassword:withPlugin:]: passwd=1 length=10
default  11:11:09.075899 -0400  Sequel Pro  -[SPMySQLConnection(PrivateAPI) _mysqlConnection:wantsPassword:withPlugin:]: cLength=10 connectEncodingNS=4
default  11:11:09.076002 -0400  Sequel Pro  -[SPMySQLConnection(PrivateAPI) _mysqlConnection:wantsPassword:withPlugin:]: <--
default  11:11:09.120609 -0400  Sequel Pro  -[SPMySQLConnection(PrivateAPI) _mysqlConnection:wantsPassword:withPlugin:]: --> connection=0x7fe2ab007400 plugin=dialog
default  11:11:09.120764 -0400  Sequel Pro  -[SPMySQLConnection(PrivateAPI) _mysqlConnection:wantsPassword:withPlugin:]: will use delegate <SPDatabaseDocument: 0x7fe2ab84be00> for password
default  11:11:09.121148 -0400  Sequel Pro  -[SPMySQLConnection(PrivateAPI) _mysqlConnection:wantsPassword:withPlugin:]: passwd=1 length=10
default  11:11:09.121279 -0400  Sequel Pro  -[SPMySQLConnection(PrivateAPI) _mysqlConnection:wantsPassword:withPlugin:]: cLength=10 connectEncodingNS=4
default  11:11:09.121386 -0400  Sequel Pro  -[SPMySQLConnection(PrivateAPI) _mysqlConnection:dialogPrompt:type:outBuffer:size:]: --> connection=0x7fe2ab007400 prompt=Password:  type=2 buf=0x70000f299280 buf_len=1024
default  11:11:09.402619 -0400  Sequel Pro  Not yet implemented.
default  11:11:09.402714 -0400  Sequel Pro  Not yet implemented.
default  11:11:11.485313 -0400  Sequel Pro  Not yet implemented.
default  11:11:11.485396 -0400  Sequel Pro  Not yet implemented.
default  11:11:11.485994 -0400  Sequel Pro  Not yet implemented.
default  11:11:11.486055 -0400  Sequel Pro  Not yet implemented.
default  11:11:11.499827 -0400  Sequel Pro  -[SPMySQLConnection(PrivateAPI) _mysqlConnection:dialogPrompt:type:outBuffer:size:]: result=1 length=10
default  11:11:11.499907 -0400  Sequel Pro  -[SPMySQLConnection(PrivateAPI) _mysqlConnection:dialogPrompt:type:outBuffer:size:]: cLength=10 connectEncodingNS=4
default  11:11:11.499948 -0400  Sequel Pro  -[SPMySQLConnection(PrivateAPI) _mysqlConnection:dialogPrompt:type:outBuffer:size:]: <-- by using mysql buf=0x70000f299280
default  11:11:11.904620 -0400  Sequel Pro  -[SPMySQLConnection(PrivateAPI) _mysqlConnection:wantsPassword:withPlugin:]: <--
default  11:11:12.268816 -0400  Sequel Pro  Not yet implemented.

**Comment by dmoagx** [comment]
Hmm, well, at least this time the password seems to have made it through from what is shown here:
```
default  11:11:09.121386 -0400  Sequel Pro  -[SPMySQLConnection(PrivateAPI) _mysqlConnection:dialogPrompt:type:outBuffer:size:]: --> connection=0x7fe2ab007400 prompt=Password:  type=2 buf=0x70000f299280 buf_len=1024
default  11:11:11.499827 -0400  Sequel Pro  -[SPMySQLConnection(PrivateAPI) _mysqlConnection:dialogPrompt:type:outBuffer:size:]: result=1 length=10
default  11:11:11.499907 -0400  Sequel Pro  -[SPMySQLConnection(PrivateAPI) _mysqlConnection:dialogPrompt:type:outBuffer:size:]: cLength=10 connectEncodingNS=4
default  11:11:11.499948 -0400  Sequel Pro  -[SPMySQLConnection(PrivateAPI) _mysqlConnection:dialogPrompt:type:outBuffer:size:]: <-- by using mysql buf=0x70000f299280
```
Does your password perhaps include any non-ASCII characters?

**Comment by vuther** [comment]
The password is "hello@642"

**Comment by dmoagx** [comment]
OK, I found the issue. Here is a hopefully working build.
[Sequel Pro.zip](https://github.com/sequelpro/sequelpro/files/1881960/Sequel.Pro.zip)

**Comment by vuther** [comment]
@dmoagx,

That fixed it! For some reason though, it prompts for password a 3rd time once logged in. Any idea?

**Comment by vuther** [comment]
Can you not take the password from the connection setup for dialog plugin instead of prompting? Not sure why it prompts for the password when it's specified when you setup the connection's profile.

**Comment by dmoagx** [comment]
The dialog plugin _could_ use the password from the connection dialog. But that is decided by the server and in your case the server said 
> Show an input prompt with label "Password:" and mask the characters

instead of 
> give me the password the user entered

**Comment by vuther** [comment]
HeidiSQL uses the dialog plugin and it does not prompt for a password. It uses the password that you input when setting up the connection's profile.

**Comment by dmoagx** [comment]
Because HeidiSQL uses libmysql from MariaDB and their definition is:
```
      /*
        asking for a password in the first packet mean mysql->password, if it's set
        otherwise we ask the user and read the reply
      */
```
While Sequel Pro uses libmysql from MySQL and their definition is:
```
      /*
        asking for a password with an empty prompt means mysql->password
        otherwise we ask the user and read the reply
      */
```

**Comment by vuther** [comment]
Wanna switch to MariaDB's libmysql? :-) The prompting is quite annoying.

**Comment by dmoagx** [comment]
Well, technically speaking both implementations are incompatible, but the MySQL one is a bit more compatible, since it will also work if the server's first prompt is for a password that is not the connection password.

We could add a hidden switch to favorites to make it behave like the MariaDB plugin, but either way you will end up with a prompt*:
* When using the dialog plugin as is there would be the password prompt from the server (although not the one from Sequel Pro that is currently shown)
* When SP is configured to automatically give the user password to the dialog plugin there would be no prompt from the server, but the warning from Sequel Pro

So in the end it boils down to the requirement for encrypted communication I mentioned above.

*: We can change the warning dialog that is currently always shown when using an insecure plugin to be only shown when the insecure plugin actually accesses the connection password

**Comment by vuther** [comment]
> When SP is configured to automatically give the user password to the dialog plugin there would be no prompt from the server, but the warning from Sequel Pro

Or better yet... it only prompts the warning when SSL isn't used! :-)

**Comment by dmoagx** [comment]
> Or better yet... it only prompts the warning when SSL isn't used! :-)

Well, of course, that is the goal.

**Comment by vuther** [comment]
Thanks for all of your work on this! I'll wait to push out this update to my company until you release an official version. Do you need me to test anything else?

**Comment by vuther** [comment]
At what point will it no longer be experimental status?

**Comment by uttamsahu-01** [comment]
> We recently enabled two-factor authentication on our database, running MariaDB version 10.2.13. Here we have windows, linux and mac clients accessing the database and we specifically have problems with Sequel Pro because it does not seem to support two-factor authentication. Connections are refused in Sequel Pro, with error message 'authentication plugin dialog.so could not be loaded', when trying to connect to the DB.


I want to do 2MFA in maria db how can I do but I want to do in server not in a control panel

**Comment by XYZodiac1** [comment]
> > We recently enabled two-factor authentication on our database, running MariaDB version 10.2.13. Here we have windows, linux and mac clients accessing the database and we specifically have problems with Sequel Pro because it does not seem to support two-factor authentication. Connections are refused in Sequel Pro, with error message 'authentication plugin dialog.so could not be loaded', when trying to connect to the DB.
> 
> I want to do 2MFA in maria db how can I do but I want to do in server not in a control panel

check my repository
