### ISSUE TITLE
"Copy as Insert" without null columns

### ISSUE THREAD

**Issue by cja769** [sequelpro/sequelpro#2997]
This might not be common outside of my database configuration but a lot of the tables in our schema allow null values in a lot of the columns and being able to "Copy as Insert" without all of the null columns would be fantastic. I've seen other feature requests in the same vein and I think in general just a richer/smarter "Copy as Insert" would be nice and would save a lot of time when writing SQL.

**Comment by dmoagx** [comment]
I don't see how omitting `NULL` columns would improve anything?

**Comment by cja769** [comment]
Here's an example
```
INSERT INTO `blc_page` (`PAGE_ID`, `ACTIVE_END_DATE`, `ACTIVE_START_DATE`, `ARCHIVED`, `CREATED_BY`, `DATE_CREATED`, `DATE_UPDATED`, `UPDATED_BY`, `DESCRIPTION`, `ADMIN_ADDITION_STATUS`, `OVERRIDE_GENERATED_URL`, `SNDBX_CATALOG_FLAG`, `SNDBX_ORIG_ITEM_ID`, `SNDBX_ORIG_RECORD_ID`, `SNDBX_ID`, `SNDBX_ARCHIVED_FLAG`, `SNDBX_DELETED_FLAG`, `SNDBX_TMPLT_RECORD_ID`, `SNDBX_TIER`, `SITE_DISC`, `EXCLUDE_FROM_SITE_MAP`, `FULL_URL`, `META_DESCRIPTION`, `META_TITLE`, `OFFLINE_FLAG`, `PRIORITY`, `PAGE_TYPE_ID`, `PAGE_TMPLT_ID`)
VALUES
	(-100, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'About Us', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, -13, NULL, '/about-us', NULL, 'About Us', NULL, NULL, -100, -100);
```
I'm aware that this would only be added as a feature in the event a richer "Copy as Insert" was added since simply adding this support wouldn't be worth the development time. Possibly it would be better for a feature request for simply a more robust "Copy as Insert" function so that "Copy as Update", "Copy as Delete" and the various 10s of feature requests around the "Copy as Insert" feature could be done.
