### ISSUE TITLE
sequelpro.com is down?

### ISSUE THREAD

**Issue by allpwrfulroot** [sequelpro/sequelpro#3000]
Cannot access any pages via Safari or Chrome

**Comment by dmoagx** [comment]
Works for me

**Comment by allpwrfulroot** [comment]
Weird. Still says it can't establish a secure connection, must be something on my end

**Comment by TheDigitalOrchard** [comment]
Works for me, too, but do note that the site is not configured to correctly redirect from http:// to https://, as any website should ideally do these days.

**Comment by abhibeckert** [comment]
> Weird. Still says it can't establish a secure connection, must be something on my end

Are you able to find a message of any kind? I've verified the site with SSL Labs and it doesn't pick up any problems.

We're using Lets Encrypt, which is new enough there could be problems.

> the site is not configured to correctly redirect from http:// to https://

My position is if somebody wants to load something from our server without SSL we should allow that.

Every link to the site, including internal links and anything from search engines or the "Siri suggested website" integrated into Safari's URL bar will use SSL.

**Comment by stuconnolly** [comment]
Closing. This appears to have been an isolated case.
