### ISSUE TITLE
Run query with cmd+enter

### ISSUE THREAD

**Issue by dstarh** [sequelpro/sequelpro#3002]
Since there is no menu item for Run Current, I can't override that in OSX.  It's rather common among osx utils to use cmd+enter to perform some sort of action.  Is there any way to do this in sequelpro?

**Comment by dmoagx** [comment]
fn+return or enter (on a full size keyboard) can also be used to launch queries.

**Comment by abhibeckert** [comment]
You can use the bundle editor to create a script triggered by cmd-enter. For example:

<img width="917" alt="screen shot 2018-03-16 at 9 10 58 am" src="https://user-images.githubusercontent.com/266088/37495674-1561b710-28fa-11e8-99c0-790ed5ae0f27.png">
