### ISSUE TITLE
how to set a column as a auto_increment

### ISSUE THREAD

**Issue by zhanggang807** [sequelpro/sequelpro#3007]
as title

**Comment by enekochan** [comment]
Select the table you want to change, then go to "Structure" and choose "auto_increment" in the "Extra" column for the column of the table you want it to be applied to.

<img width="925" alt="screen shot 2018-04-21 at 23 09 33" src="https://user-images.githubusercontent.com/1836845/39088821-57488290-45b9-11e8-922a-4b1defdd5b9d.png">
