### ISSUE TITLE
Sidebar server names are blank [Postgres]

### ISSUE THREAD

**Issue by skylarmb** [sequelpro/sequelpro#3009]
If I connect to my localhost I can see the details of what server I am connected to. If I connect to a remote server (with SSH tunneling) I just get blank placeholders in the sidebar. Yes, I did name the connections when creating them.

<img width="348" alt="screen shot 2018-03-19 at 11 06 13 am" src="https://user-images.githubusercontent.com/7543705/37613727-fe0d009c-2b65-11e8-908d-26dc1d664aff.png">

**Comment by dmoagx** [comment]
That is not a screenshot of Sequel Pro. You are using a different tool.

**Comment by skylarmb** [comment]
Wow, you are right. I am using "SQLPro for Postgres"
