### ISSUE TITLE
Name overwritten by DB host address on SSH tunnel

### ISSUE THREAD

**Issue by geoffoliver** [sequelpro/sequelpro#3015]
**Issue**
When creating a new favorite using an SSH tunnel connection, the name gets overwritten by the value entered into "MySQL Host" field.

**Steps to reproduce**
- Create a new favorite
- After the favorite has been created, while the name is displayed as a text field (in the favorites list), type a name into it and hit "Enter"
- Switch to the "SSH" tab
- Enter a host into the "MySQL Host" field.
- The "Name" field should now display the value entered into the "MySQL Host" field.

**Comment by dmoagx** [comment]
Works fine for me. What exact Sequel Pro version and what OS version are you using?

**Comment by atom-goliver** [comment]
Sequel Pro: 1.1.2, Build 4541 (602e11a)
MacOS 10.13.3.

See video for reference - https://www.dropbox.com/s/kvd5qb4iscdx974/weird%20bug.mov?dl=0

**Comment by dmoagx** [comment]
OK, I see it now. The important part is that _automatic sorting of favorites has to be disabled_ for the issue to appear.
