### ISSUE TITLE
SSH Port forwarding failed when trying to connect to remote database via SSH (target server and jump server are the same machine)

### ISSUE THREAD

**Issue by zzpwestlife** [sequelpro/sequelpro#3017]
Here are the config and error message. 

![img_6100](https://user-images.githubusercontent.com/12382180/37962157-d654a77a-31ec-11e8-9a60-8f03deca6922.PNG)

![screen shot 2018-03-27 at 6 10 51 pm](https://user-images.githubusercontent.com/12382180/37961390-b8d96caa-31ea-11e8-99df-69b1570e2df7.png)

I've tried change host to 'localhost' or '127.0.0.1', no luck.

And I've tried Navicat, no errors met.

Hope to get some answers. Thanks.

**Comment by dmoagx** [comment]
Well IMHO the error message is pretty clear: The SSH connection works, but MySQL either does not know a user `mzapp@localhost` (or `mzapp@%`) or the password was wrong.

Does your password contain any non-ASCII characters?

**Comment by zzpwestlife** [comment]
The password does not contain any non-ASCII characters. 
Other tools like Navicat, MySQLWorkbenck all work OK.
So I guess there is something wrong with Sequel Pro.

**Comment by dmoagx** [comment]
What does Navicat/MySQLWorkbench show when you run query `SELECT USER()`?

**Comment by zzpwestlife** [comment]
@dmoagx 
```
mzapp@centos7-mysql_master-0_201
```

**Comment by dmoagx** [comment]
So it looks to MySQL like your connections are coming from different machines:
```
mzapp@centos7-mysql_master-0_201
```
vs
```
mzapp@localhost
```
You can try to check what IP `centos7-mysql_master-0_201` is mapped to in the `/etc/hosts` file on the MySQL server.
