### ISSUE TITLE
High Sierra - Cannot connect to any server using .spf files or mysql:// link

### ISSUE THREAD

**Issue by xNarkon** [sequelpro/sequelpro#3018]
Hey,

I noticed that on High Sierra I'm unable to connect to any server with .spf and mysql:// link due to application not responding. CPU usage is neat at 100% all the time and it just hangs...

Here u are with sample of process while this strange hang is...

[sample_of_sequel_pro_high_sierra.txt](https://github.com/sequelpro/sequelpro/files/1854774/sample_of_sequel_pro_high_sierra.txt)

**Comment by dmoagx** [comment]
No idea what is going on there.
There is hardly any Sequel Pro code running in that sample and the rest of the code looks like a regular GUI update cycle.

But at least I can reproduce it on a 10.13 Mac.

**Comment by dmoagx** [comment]
Actually this is a duplicate of #2903
