### ISSUE TITLE
Spatial query incorrectly returns null values

### ISSUE THREAD

**Issue by padraig2** [sequelpro/sequelpro#3021]
When I run this code from the query window : 
set @g1 = Point(1,1), @g2 = Point(2,2);
SELECT ST_Equals(@g1, @g1), ST_Equals(@g1, @g2)

I get 2 null values.

When I run it from the command line I correctly get 1 and 0.

In other words Sequel Pro is correctly returning null when it should return 1 and 0.

**Comment by padraig2** [comment]
My mistake - I didn't have the correct table highlighted in the left hand column. 

You need to highlight the table in question.

**Comment by dmoagx** [comment]
Works for me:
![bildschirmfoto 2018-03-30 um 21 52 40 913](https://user-images.githubusercontent.com/5793864/38151721-b149d7d2-3464-11e8-9c23-1ab9c6a4d719.png)

You probably picked "Run current" instead of "Run All" so the first query was not executed and `@g1` and `@g2` were undefined.
