### ISSUE TITLE
Verify download

### ISSUE THREAD

**Issue by NathanHaley** [sequelpro/sequelpro#3024]
How to verify download?

I download dmg file and can run shasum -a 256 sequel-pro-1.1.2.dmg in terminal and do get a key BUT I cannot find a reference to match against on sequelpro.com or at the github project.

**Comment by dmoagx** [comment]
If you want to verify a download the best option is if you already have a previous version of Sequel Pro to verify the sha signature with the DSA public key as described here: https://github.com/sparkle-project/Sparkle/issues/896#issuecomment-252355818

The public key file is located in `/Applications/Sequel Pro.app/Contents/Resources/sparkle-public-key.pem`.
