### ISSUE TITLE
"Run selection" does not select query correctly

### ISSUE THREAD

**Issue by paolodona** [sequelpro/sequelpro#3026]
Hi I think there is an issues with the "Run selection" feature.

I have multiple queries in my editor.

With the cursor on the first query, when I press ```fn + enter```, I see that not all of the query gets selected, so only a snippet of the full SQL gets executed, causing an error (seems like the selection can't capture the full query). 

To get around this, I try to select the full SQL myself, however, when I press ```fn + enter``` my selection gets wiped and the wrong/incomplete selection appears again.

I have recorded a short video of what happens here: https://www.dropbox.com/s/97ptqjgwyvdoyrp/SequelPro_run_selection_bug.mov?dl=0

Hope this helps! 
thanks for the great tool

**Comment by dmoagx** [comment]
What you are seeing is that Sequel Pro automatically highlights the part of the query that is mentioned by MySQL in the `You have an error in your syntax... near 'xyz'` error message.

If you are not sure what SP actually executed just open the Query Console.

**Comment by dmoagx** [comment]
Btw: The issue with your query is that you tried to use the reserved keyword `long` unquoted as a column alias.

**Comment by paolodona** [comment]
Thanks Max

On Tue, Apr 3, 2018 at 9:16 PM, Max Lohrmann <notifications@github.com>
wrote:

> Closed #3026 <https://github.com/sequelpro/sequelpro/issues/3026>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://mailtrack.io/trace/link/5edff7970719ef2d56b3d456856ede77c3100361?url=https%3A%2F%2Fgithub.com%2Fsequelpro%2Fsequelpro%2Fissues%2F3026%23event-1555011250&userId=1881529&signature=8d965b6ac6fe7649>,
> or mute the thread
> <https://mailtrack.io/trace/link/1de41b20530e08ea26c0b0f2b5ea9a059cec0876?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAAMrQNZiquILHMpwQCjqvRlNxGl3X1jks5tk9icgaJpZM4TE_Nr&userId=1881529&signature=56234f6c2ecff427>
> .
>



-- 
Paolo Dona' | http://paolodona.com
<https://mailtrack.io/trace/link/bd84cf0fcb6b9c340fd12d1c619c54ebb40ba4d1?url=http%3A%2F%2Fpaolodona.com&userId=1881529&signature=c2c08a00b3a2f79e>
