### ISSUE TITLE
Column names missing when query result has many columns

### ISSUE THREAD

**Issue by pianojosh** [sequelpro/sequelpro#3027]
Running Sequel Pro 1.1.2 on Mac OS X 10.13.3.

If I run a query with a few columns, all is well:
<img width="558" alt="screen shot 2018-04-03 at 8 06 49 am" src="https://user-images.githubusercontent.com/33679/38258261-d4cd6f66-3716-11e8-877f-369e3fd0f7f8.png">

But if I do a SELECT * or run a procedure that returns many columns, the columns in the result panel end up missing:
<img width="1310" alt="screen shot 2018-04-03 at 8 07 03 am" src="https://user-images.githubusercontent.com/33679/38258287-ed0847e0-3716-11e8-94d7-95836e8a03ab.png">

Same bug when calling a procedure:
<img width="1076" alt="screen shot 2018-04-03 at 8 14 23 am" src="https://user-images.githubusercontent.com/33679/38258339-0e0c8bc2-3717-11e8-93cd-4b331d6a9e6a.png">

**Comment by dmoagx** [comment]
11 isn't exactly many columns.
* Does this happen always for the queries where it happens?
* Have you tried shaking and resizing the window?
* Does the database or tables in the database use utf16 encoding?

**Comment by dmoagx** [comment]
No feedback from reporter in 30 days -> closing
