### ISSUE TITLE
A little inconvenience for the installer

### ISSUE THREAD

**Issue by yos-hatt** [sequelpro/sequelpro#3030]
Dear, sequel pro developers.

[Version] v1.1.2(sequel-pro-1.1.2.dmg)
[OS] macOS (High Sierra 10.13.4)

I feel a little inconvenience for the installer.
<img width="368" alt="2018-04-12 14 01 21" src="https://user-images.githubusercontent.com/16183193/38659552-fe0d9ec8-3e64-11e8-8b88-84df51731cb0.png">

The install image(dmg) does not have neither shortcut to the "Application" directory, nor README that described how to install it.

Like this, to use install guidance, install process will be more easy, I think.
![image](https://user-images.githubusercontent.com/16183193/38659574-110a7294-3e65-11e8-8e21-3cda38290c9c.png)

Example installer (Libre Office) :  
https://www.libreoffice.org/download/download/

**Comment by dmoagx** [comment]
I think the reason behind this was that Safari will automatically unpack and remove the .dmg after Download, if it only contains a single file.
