### ISSUE TITLE
blob previews are incorrect size

### ISSUE THREAD

**Issue by tomhumphrey** [sequelpro/sequelpro#3032]
I've got a column that stores image files in it with the majority of the images around 1000x600 pixels. However, when double clicking on the field the preview window shows them a lot smaller then they actually are (tiny in fact). Could this be fixed so that they're displayed as their correct size?

**Comment by dmoagx** [comment]
* What exact Sequel Pro version?
* What exact OS version?
* Please provide test data.

**Comment by dmoagx** [comment]
No response from user within 30 days -> closing
