### ISSUE TITLE
Sequel Pro 1.1.2 "save as pdf" crash issue

### ISSUE THREAD

**Issue by Barsegyanka** [sequelpro/sequelpro#3033]
Hello,

Since the last macOS update (10.13.4) my team has been experiencing an issue. Every time we try to save the results from Sequel Pro as PDF - the program just closes and we see a pop up - Program "Sequel Pro" unexpectedly finished its work.

Could you please advise?

Many thanks in advance,
Yana

**Comment by dmoagx** [comment]
Duplicate of #3025
