### ISSUE TITLE
Feature Request: Split Screen

### ISSUE THREAD

**Issue by rakesh-verma-16** [sequelpro/sequelpro#3035]
Hi,

Can we implement a Split Screen for the Content View page in Sequel Pro?
The only way I can see data from multiple tables is by writing Queries but If I had the option to split the screen into multiple tables, It'd be so much easier and useful.

Also, I'd love to contribute to it as well.

**Comment by dmoagx** [comment]
Why not simply but two windows side by side?

**Comment by rakesh-verma-16** [comment]
@dmoagx Yes, that'd work as well.
