### ISSUE TITLE
左侧表菜单字体大小问题

### ISSUE THREAD

**Issue by jibingbing123** [sequelpro/sequelpro#3036]
mac外接显示器后，sequel pro左侧表显示很小，字体不能调整

**Comment by dmoagx** [comment]
English only, please.

**Comment by jibingbing123** [comment]
After the MAC external display, the left table of sequel pro is small and the font cannot be adjusted.

**Comment by dmoagx** [comment]
That is not a useful issue description.

https://github.com/sequelpro/sequelpro/wiki/How-do-I-write-a-proper-issue-report%3F

**Comment by stuconnolly** [comment]
Duplicate of #2872
