### ISSUE TITLE
Cannot connect to MySQL 8.0.4 (caching_sha2_password plugin is missing)

### ISSUE THREAD

**Issue by rasmusbe** [sequelpro/sequelpro#3037]
MySQL made caching_sha2_password the default authentication plugin in 8.0.4, see https://mysqlserverteam.com/mysql-8-0-4-new-default-authentication-plugin-caching_sha2_password/

Sequel Pro seems to not support caching_sha2_password yet, I have tried the testbuilds without success.

**Comment by dmoagx** [comment]
Sequel Pro doesn't officially support MySQL 8.0 at all at the moment.

**Comment by bramski** [comment]
Uhh. sweet!

**Comment by dmoagx** [comment]
Side note: Support for `caching_sha2_password` will probably not happen anytime soon.
Sequel Pro currently uses the 5.5 MySQL client and this plugin is only included with the most recent 8.0 client.
Since there may be internal changes between those versions and we made some customizations ourselves, we have to go 5.5 -> 5.6 -> 5.7 -> 8.0 and check compatibility at each step.

But not even the switch to 5.6 is scheduled for the next release.

**Comment by aronbudinszky** [comment]
A possible "workaround" is a feature to add/alter users using the `IDENTIFIED WITH mysql_native_password` clause. This could be a checkbox that displays on MySQL version 8.0+ like so:
<img width="827" alt="screenshot 2018-06-28 11 28 55" src="https://user-images.githubusercontent.com/1391360/42026275-f77f21fa-7ac6-11e8-98e1-f8633747d03a.png">

Although this wouldn't solve the initial connection issue it would allow admins to create additional users who can still access MySQL with older clients/connectors.

I'm happy to implement this feature if you agree.

**Comment by lechie** [comment]
Need  8.0 support,too,  thank you

**Comment by mnabialek** [comment]
Any progress with this? Today I've installed latest nightly build (they are finally repaired) and hoped now it will connect with MySQL database without any problem but unfortunately I have same message when connecting to remote MySQL 8 server:

> MySQL said: Authentication plugin 'caching_sha2_password' cannot be loaded: dlopen(/usr/local/mysql/lib/plugin/caching_sha2_password.so, 2): image not found

**Comment by dmoagx** [comment]
https://github.com/sequelpro/sequelpro/issues/3037#issuecomment-398490129

**Comment by mnabialek** [comment]
@aronbudinszky But you cannot use this method for remote server you don't own, can you?

**Comment by mnabialek** [comment]
@aronbudinszky The problem is I don't. At the moment I need to use other client to connect to customer MySQL 8.0 databse.

**Comment by paulmillr** [comment]
How to convert MySQL 8.0 auth to legacy format: https://stackoverflow.com/questions/50169576/mysql-8-0-11-error-connect-to-caching-sha2-password-the-specified-module-could-n

You will need to change .ini config and to re-execute ALTER USER on all users

**Comment by spnkr** [comment]
please fix this. i'm not changing my mysql 8 server to use an older auth method just for the GUI I use to connect to it. i've switched to Querious and TablePlus until you fix this. but i'd rather use sequel pro!

**Comment by lechie** [comment]
> please fix this. i'm not changing my mysql 8 server to use an older auth method just for the GUI I use to connect to it. i've switched to Querious and TablePlus until you fix this. but i'd rather use sequel pro!

You can use **nightly build app** , it has supported MySQL 8.0.
[https://sequelpro.com/test-builds ](url)

**Comment by dmoagx** [comment]
> You can use nightly build app , it has supported MySQL 8.0.

Nope, nightly builds don't support `caching_sha2_password` either.

**Comment by benlieb** [comment]
What a disappoinment

**Comment by johncoles** [comment]
Still an issue.

**Comment by bchewy** [comment]
MySQL 8.0.12 here and it works just fine now. (I was missing a my.cnf file and i also had to alter and add a password.

- https://stackoverflow.com/questions/51179516/sequel-pro-and-mysql-connection-failed

Tested Today and it works just fine!

**Comment by ktamas77** [comment]
Although I understand it's challenging, I hope MySQL 8 support will come soon to Sequel Pro.
Some ISPs, such as Digital Ocean, are supporting MySQL 8 only, and Sequel Pro cannot be used with these databases anymore.

**Comment by abulwcse** [comment]
Is there any update on this issue ? When can we expect a stable relate that support MySQL8

**Comment by hackdavid** [comment]
if you are facing "caching_sha2_password" error during connectivity of your mysql database using python ,
go through this
https://www.youtube.com/watch?v=YNq-EuQEJos

**Comment by cgriego** [comment]
Still an issue.
