### ISSUE TITLE
Sequel Pro Mac - Can't Create Tables?

### ISSUE THREAD

**Issue by fukdapiggz** [sequelpro/sequelpro#3038]
I'm trying to add tables in Sequel Pro on macOS High SIerra, it's greyed out and won't let me add them and its greyed out??

**Comment by fukdapiggz** [comment]
https://imgur.com/a/i5fL4tM - shown here 😀

**Comment by dmoagx** [comment]
That doesn't look greyed out to me. Note the "Add Table" button is in the lower left corner of the window.

**Comment by fukdapiggz** [comment]
Yeah, when you click the button it does nothing

**Comment by dmoagx** [comment]
Open Console.app, search for messages from Sequel Pro and post them here.

**Comment by dmoagx** [comment]
No feedback from reporter in 30 days -> closing.

**Comment by aFcFzF** [comment]
![Uploading image.png…]()

**Comment by aFcFzF** [comment]
![image](https://user-images.githubusercontent.com/19820728/98003321-95c2dc00-1e29-11eb-9501-ae42aa55ec74.png)
