### ISSUE TITLE
The sequel pro doesn't support the latest version of mysql.

### ISSUE THREAD

**Issue by xiezhuojin** [sequelpro/sequelpro#3040]
I had try so many times that the sequel pro seems not compatible with the mysql8.0.But the dev version of workbench seems work perfectly.Hope you guy can fit the problem.

**Comment by lexilya** [comment]
According to #2699, the latest test builds should support 8.0. All the recent builds at [https://sequelpro.com/test-builds](https://sequelpro.com/test-builds) have status pending though.

**Comment by dmoagx** [comment]
Duplicate of #2699

The last test build that is available already has this fixed.
