### ISSUE TITLE
crashing sequel in mysql 8

### ISSUE THREAD

**Issue by rafalogan** [sequelpro/sequelpro#3045]
everytime that I start the application it hangs and  I have to close sequel.
then it will not start any more.

**Comment by dmoagx** [comment]
What exactly is your issue?

The tile says it crashes when you connect to MySQL 8, but the text says it crashes as soon as you open it...

**Comment by JasinYip** [comment]
same here. Connect testing is fine, but after running a query or switch a database(actually it's query too), it will get crashed and shows a error dialog witch is useless(can't send error log and cannot exit the dialog)

**Comment by dmoagx** [comment]
I'm pretty sure this is a duplicate of #2699

**Comment by boyfox** [comment]
Please, increasing publishing next release time with supporting mysql 8 , we waiting next release sequel pro!

**Comment by gvanbeck** [comment]
+1

**Comment by dmoagx** [comment]
Since no one did provide additional infos I'm closing this as a duplicate of #2699
