### ISSUE TITLE
Sequel Pro crashes while connect MySQL 8

### ISSUE THREAD

**Issue by zaisahil** [sequelpro/sequelpro#3053]
I am trying to connect MySQL 8 without using SSH. If I test my connection, it gets successful but if I connect, Sequel Pro gets crashed. 

Does it support MySQL 8?

**Comment by zaisahil** [comment]
I don't think this is duplicate as their is no fix found on issue number: [2699](https://github.com/sequelpro/sequelpro/issues/2699)

By the way, here is the exception on crash:

`NSInvalidArgumentException

-[_NSInlineData isEqualToString:]: unrecognized selector sent to instance 0x60400003fd60

(
	0   CoreFoundation                      0x00007fff3709532b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff5e70bc76 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff3712de04 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff3700b870 ___forwarding___ + 1456
	4   CoreFoundation                      0x00007fff3700b238 _CF_forwarding_prep_0 + 120
	5   Sequel Pro                          0x000000010002fce3 -[SPDatabaseDocument setDatabases:] + 783
	6   Sequel Pro                          0x000000010002f2a9 -[SPDatabaseDocument setConnection:] + 610
	7   Foundation                          0x00007fff391462b5 __NSThreadPerformPerform + 334
	8   CoreFoundation                      0x00007fff3702da61 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	9   CoreFoundation                      0x00007fff370e747c __CFRunLoopDoSource0 + 108
	10  CoreFoundation                      0x00007fff370104c0 __CFRunLoopDoSources0 + 208
	11  CoreFoundation                      0x00007fff3700f93d __CFRunLoopRun + 1293
	12  CoreFoundation                      0x00007fff3700f1a3 CFRunLoopRunSpecific + 483
	13  HIToolbox                           0x00007fff362f7d96 RunCurrentEventLoopInMode + 286
	14  HIToolbox                           0x00007fff362f7b06 ReceiveNextEventCommon + 613
	15  HIToolbox                           0x00007fff362f7884 _BlockUntilNextEventMatchingListInModeWithFilter + 64
	16  AppKit                              0x00007fff345aaa73 _DPSNextEvent + 2085
	17  AppKit                              0x00007fff34d40e34 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 3044
	18  AppKit                              0x00007fff3459f885 -[NSApplication run] + 764
	19  AppKit                              0x00007fff3456ea72 NSApplicationMain + 804
	20  Sequel Pro                          0x0000000100002454 start + 52
	21  ???                                 0x0000000000000001 0x0 + 1
)
`

**Comment by huyphams** [comment]
The issue was marked as duplicated that means it was reported. it doesn't mean it resolve or not.
Sequel Pro is broken on MySQL 8.0 because the new MySQL release has changed some meta columns. You can make a PR for it or using another tool before its fix.

**Comment by zaisahil** [comment]
Thanks for the clarifications. Is there any update on the fix?

**Comment by GSolari79** [comment]
Is there a fix to the issue? Thanks in advance

**Comment by zheoreh** [comment]
Two years have passed... Is it so difficult to fix it?

**Comment by onemoreahmad** [comment]
This is what worked for me 

I downloaded test version from here 
https://sequelpro.com/test-builds

then I did I changed the encryption of the user's password by doing this

Open the command line 
Login to mysql 

`mysql -uroot -p`

Put mysql password 

Then run this command:
`ALTER USER 'yourusername'@'localhost' IDENTIFIED WITH mysql_native_password BY 'youpassword';
`

Of course change [yourusername] and [yourpassword] to your own

Found [there](https://stackoverflow.com/questions/49194719/authentication-plugin-caching-sha2-password-cannot-be-loaded)

**Comment by raymondjplante** [comment]
@zheoreh  Just donated... now I can complain with impunity--LET'S GET A STABLE RELEASE OUT PLEASE!

**Comment by vitobotta** [comment]
Just found out that Sequel Pro doesn't work with MySQL 8.0 offered by DigitalOcean :(

Any news?

**Comment by okryvorotko** [comment]
Try this build `a2e6c1198d` from https://sequelpro.com/test-builds

**Comment by chimdiadi** [comment]
Works! Thanks.

**Comment by emjayess** [comment]
I haz questions...

**Q: Can the "stable" release and the Nightly both be installed, side-by-side?**
> ![side-by-side](https://user-images.githubusercontent.com/194904/72908723-82f87400-3cfb-11ea-982d-e4265ced5b36.png)

**Q: If I install the nightly (whether or not side-by-side my existing installation), will the nightly preserve and pickup things like all my settings, query faves/history, etc?** Or would it be a _lossy_ experience?... 
* Query history, in particular, is indispensable to my present workflows, which has prevented me from taking this step thus far.

---

Thanks in advance for any insights.

**Comment by chimdiadi** [comment]
The build preserved my settings without issue.

**Comment by paulisloud** [comment]
The build worked for me as well

**Comment by israelmw** [comment]
The build worked perfect!! Thanks

**Comment by ruden91** [comment]
If you want to solve this problem, use Sequel Ace!
this problem is MySQL 8.x issue.

https://apps.apple.com/us/app/sequel-ace/id1518036000?ls=1

**Comment by TannerGi** [comment]
Sequel Ace worked like a charm.. Thank you.

**Comment by acermez** [comment]
I can confirm that Sequel Ace worked like a charm with MySQL 8 (Homestead, Ubuntu), the interface is so familiar I almost didn't feel the difference, thank you @ruden91 & @TannerGi (for confirming it worked :) )

**Comment by Chengrongrong** [comment]
> Try this build `a2e6c1198d` from https://sequelpro.com/test-builds


Works! Thanks.
mysql version 8.0.16

**Comment by dkuss** [comment]
> If you want to solve this problem, use Sequel Ace! this problem is MySQL 8.x issue.
> 
> https://apps.apple.com/us/app/sequel-ace/id1518036000?ls=1

Thanks for this tip! 🙏 
Works great with MySql 8.0 and 5.6 too. (on macOs 12.6 Monterey)
Also "fixes" the crashes when closing a connection, especially annoying with multiple windows opened.
And supports dark mode as well 😄 👍

**Comment by ranjeetranjan** [comment]
Use Sequel Ace the best alternative solution. 

https://apps.apple.com/us/app/sequel-ace/id1518036000?ls=1

**Comment by basskriangkrai** [comment]
Thank you very much.

**Comment by perdomon** [comment]
Sequel Pro walked so Sequel Ace could run. Glad I found this thread.

**Comment by vh2c** [comment]
I've been struggling with this issue all the weekend, then I have found SEQUEL ACE in the AppStore. It's free and it has exactly the same "face" of Sequel Pro...and the best, it works !
https://sequel-ace.com/
