### ISSUE TITLE
when I select database after I already logged in, bug occurs.

### ISSUE THREAD

**Issue by lvhuichao** [sequelpro/sequelpro#3058]
when I select database after I already logged in, bug occurs.

**Comment by huyphams** [comment]
When releasing a product (such as Sequel Pro), we have tested it with all the basic cases (including your case). So if's impossible to reproduce a bug with `when I select database after I already logged in, bug occurs.` it's too short and useless.

You had better do something like:
1.Enviroments:
-  Sequel Pro version: 1.1.2 build 4541
- OSX: 10.13.1
- MySQL `8.0`

2. Step to preproduce.
 - After logged in.
- Query with query:
```
Select * from blah blah
```

**Comment by dmoagx** [comment]
No feedback from reporter in 30 days -> closing.
