### ISSUE TITLE
BUG: Wrong character set in VIEW

### ISSUE THREAD

**Issue by wszk1992** [sequelpro/sequelpro#3068]
When I create a VIEW to join two tables, I found that the Encoding of fields changed from UTF-8 to cp1252 West, which cause a bad display of Arabic characters. Please help to fix this.

![image](https://user-images.githubusercontent.com/14061819/40819898-0d5f5b8a-6590-11e8-9978-8699c518968e.png)

![image](https://user-images.githubusercontent.com/14061819/40819975-5ee70ce6-6590-11e8-8393-de327f05b8c6.png)

**Comment by dmoagx** [comment]
Sequel Pro sets the connection encoding to the encoding of the last table that was selected. MySQL stores and reuses the encoding that was used when the view was created.
You should check in `information_schema.views` which encoding is stored for the view.

**Comment by dmoagx** [comment]
No feedback from reporter in 30 days -> closing.
