### ISSUE TITLE
[SSH+TCP/IP] Sequel Pro vs. jump host via `ProxyJump`?

### ISSUE THREAD

**Issue by seelensonne** [sequelpro/sequelpro#3069]
Our database servers (db.example.com) are on a dedicated network, so in order to connect, we need to go through a jump host (db.example.com). We have something like this in `~/.ssh/config`, so regular SSH usage is seamless (i.e., `ssh user@db.example.com` just works):

```
Host db.example.com
    ProxyJump user@jump.example.com
```

However, Sequel Pro doesn't seem to like it and fails with "Unable to connect to host 127.0.0.1, or the request timed out".

We tried modifying the SSH command generated by Sequel Pro (via a simple script configured in "Preferences > Network > SSH Client"), but still no success.

Any ideas, suggestions, config snippets, etc. are greatly appreciated! -- Thanks!

Connection settings:

- MySQL Host: 127.0.0.1
- Username: hello
- Password: test123
- Database: (blank)
- Port: (blank)
- SSH Host: db.example.com
- SSH User: world
- SSH Password: (via public key)
- SSH Port: (blank)
- Connect using SSL: (not checked)

Environment:

- macOS 10.13.4 (17E202)
- Sequel Pro 1.1.2
- Sequel Pro 5224 (3477d223)
- MariaDB 5.5.56

The underlying SSH/MySQL setup is ok. Regular SSH and other database clients, e.g. IntelliJ IDEA, connect just fine.

**Comment by dmoagx** [comment]
Sequel Pro only supports one level of SSH tunneling:
```
Client ---> SSH Host ---> MySQL
```

In which case you would specify the SSH Host in "SSH Host" and in "MySQL Host" give the MySQL Hostname/IP as it is seen by the ssh host.

This scenario is not supported:
```
Client ---> SSH Jump Host ---> SSH Host ---> MySQL
```
It may still work, but that depends entirely on how the `ProxyJump` command works.

**Comment by seelensonne** [comment]
Thanks @ dmoagx!

**Comment by mstaack** [comment]
any workarounds known? facing a similiar problem

**Comment by bacbos** [comment]
+1

**Comment by AntonEvers** [comment]
+1

**Comment by JacobBarba** [comment]
+1

**Comment by houndegnonm** [comment]
@dmoagx  any chance the new version of sequelPro will support ProxyJump

**Comment by andrewtch** [comment]
Can someone please reopen this? )

**Comment by houndegnonm** [comment]
following tips works for me using Sequel Pro on Mac.
SequelPro (local) -------> jumpServerName -------> databaseServerName 

assume you have netcat setup on the `jumpserverName`, you can edit your `~/.ssh/config` file.

```
Host jump
  User mySSHUserID
  Hostname jumpServerName

Host  databaseServerName
  User mySSHUserID
  ProxyCommand ssh -q jump nc %h 22
```

**Comment by chandanbansal** [comment]
### Following works for me on Mac:

1. Add below lines in "**~/.ssh/config**" file.
2. "**mysqlpro.example.com**" is a virtual host making a proxy to the machine, not need to change the value, other than the domain as per proxy settings.
3. **$hostname** is any production machine IP which you can access from local via proxy.
4. Then use **mysqlpro.example.com** as **SSH Host** in sequel pro other settings will be the same as before.
 
```
Host *.example.com
    ProxyJump jump.example.com

Host mysqlpro.example.com
    Hostname $hostname
    ProxyCommand ssh -q -W %h:%p jump.example.com
```

**Comment by claudioromano** [comment]
The solution from @chandanbansal works great!
Thanks.

I was able to connect to the mysql server inside a internal network through a proxy using an ssh key and custom port.

```
Host proxy1
    HostName x.x.x.x
    User root
    Port 31234

Host mysql.master
    Hostname 10.10.x.100
    User root
    ProxyCommand ssh -q -W %h:%p proxy1

Host mysql.slave1
    Hostname 10.10.x.101
    User root
    ProxyCommand ssh -q -W %h:%p proxy1
```

Then on sequel pro just use:

MySQL Host: `127.0.0.1`
Username: `[your db username]`
Password:  `[your db password]` 

SSH Host: `mysql.master `
SSH User: `empty`
SSH Pass: `empty`
