### ISSUE TITLE
Cannot remove the filter box

### ISSUE THREAD

**Issue by lexilya** [sequelpro/sequelpro#3071]
Running a build based on https://github.com/sequelpro/sequelpro/commit/720bb5f2339ed8085f8aadf2630610fee1d6f400, I am unable to disable the filter bar after having filtered content using "Table" -> "Filter Content".

If I just remove the value from the filter box and then do anything with the table (like sorting or switching from one table and back to this one), it tells me this:

<img width="648" alt="skarmklipp 2018-06-04 11 30 55" src="https://user-images.githubusercontent.com/8910071/40910039-650dd962-67eb-11e8-86e7-0f316545f354.png">

**Comment by dmoagx** [comment]
Use the filter button at the bottom of the window to hide and disable the filtering

**Comment by lexilya** [comment]
Ah, it was that simple. Takes some getting used to the new GUI. Thanks for the input, and thanks for the great work you do on the client.

**Comment by dmoagx** [comment]
The UI could probably be improved here to allow multiple ways to disable the filter.

**Comment by humiaozuzu** [comment]
@dmoagx Yes. In previous versions, when there is only one filter, press `Esc` can dismiss the last one.
Or do not hide the minus button for last filter tab

**Comment by goldengecko** [comment]
This confused me too. Perhaps a "-" button at the top right like when you have multiple filters?

**Comment by dmoagx** [comment]
I think this is mostly covered by #3302

**Comment by dmoagx** [comment]
Last filter can now also be removed by pressing "-", so I consider this issue done.
