### ISSUE TITLE
can not connect to mysql 8.0 installed by homebrew~

### ISSUE THREAD

**Issue by YSMull** [sequelpro/sequelpro#3089]
even with the test builds

**Comment by venjiang** [comment]
I have same problem.

**Comment by kookan107** [comment]
Me too@

**Comment by loranger** [comment]
Since homebrew upgrade updated mysql to 8.0, there should be a massive _me too_ wave incoming 🤔 
Here is an issue to follow-up: #2699

**Comment by dmoagx** [comment]
Duplicate of #2699, #3037
