### ISSUE TITLE
SQL INSERT doesn't really insert all data.

### ISSUE THREAD

**Issue by Umiiii** [sequelpro/sequelpro#3090]
OS Version: `macOS 10.13.4 (17E202)`
Sequel Pro Version : `1.1.2 Build 4541(602e11a)`

Step to reproduce the issue:

There are two databases:
A : MySQL 5.5.57-0ubuntu0.14.04.1
B:  MySQL 5.5.5-10.1.21-MariaDB

All I do is to execute a select SQL command with a large amount of result(~12000),
then I select all and Copy as SQL INSERT.
At the end, I paste them into another session connected with B.

It's saying that all rows works.
However, only 2002 rows inserted.
<img width="520" alt="qq20180619-190401 2x" src="https://user-images.githubusercontent.com/29030474/41593736-9eb69744-73f3-11e8-835c-1e9d810b87c9.png">

<img width="159" alt="qq20180619-190428 2x" src="https://user-images.githubusercontent.com/29030474/41593734-9de08992-73f3-11e8-86a1-249dd3176f1a.png">

**Comment by dmoagx** [comment]
https://github.com/sequelpro/sequelpro/wiki/How-do-I-write-a-proper-issue-report%3F

**Comment by dmoagx** [comment]
No feedback from reporter in 30 days -> closing.
