### ISSUE TITLE
Multiple If statements inside trigger

### ISSUE THREAD

**Issue by Philwn** [sequelpro/sequelpro#3092]
I cant add multiple If statements inside a trigger.

if (old.tradePackQty <> new.tradePackQty) then
	INSERT INTO logs(user_id, tableName, tableKey, description, tableField, oldValue, newValue) VALUES (99, 'products', OLD.id, 'Updated Product', 'tradePackQty', old.tradePackQty, new.tradePackQty);
end if;

if (old.tradePrice <> new.tradePrice) then
	INSERT INTO logs(user_id, tableName, tableKey, description, tableField, oldValue, newValue) VALUES (99, 'products', OLD.id, 'Updated Product', 'tradePrice', old.tradePrice, new.tradePrice);
end if;

<img width="1045" alt="screen shot 2018-06-21 at 12 13 37" src="https://user-images.githubusercontent.com/11190520/41715845-8fcabe2c-754c-11e8-9be4-244f838fa6e7.png">

**Comment by dmoagx** [comment]
https://dev.mysql.com/doc/refman/5.7/en/begin-end.html
