### ISSUE TITLE
I think I broke Sequel Pro

### ISSUE THREAD

**Issue by Hpegan-PS** [sequelpro/sequelpro#3096]
I tried uploading a csv file, after a long import, the app crashed, asked for a crash report, crashed again. After that every attempt to open a database, submit a report was met with more crashing. I restarted mySQL, checked my global plist cache, restarted Sequel, and tried again to find more crashing. Then I did all that again, rebooted my Mac, and found it was still crashing. I followed that by uninstalling the application, and reinstalling to find the same results. Any help would be wonderful.

**Comment by dmoagx** [comment]
Please post the crash reports.

**Comment by Hpegan-PS** [comment]
I eventually figured it out! My directory wasn't working correctly because I had previously installed Anaconda and I had two versions of MySQL installed and had to clean that up. Thank you for your fast response!
