### ISSUE TITLE
Unexpected error every time I try and connect

### ISSUE THREAD

**Issue by BrianKauffman** [sequelpro/sequelpro#3105]
I am running version 1.1.2 on my Macbook OS 10.13.5 and am unable to connect to any DB. I keep getting an "Unexpected Error" pop-up. The error is:

NSInvalidArgumentException

-[_NSInlineData isEqualToString:]: unrecognized selector sent to instance 0x600000230b40

**Comment by dmoagx** [comment]
Duplicate of #2699
