### ISSUE TITLE
Host-specific query favourites only show for 'unnamed 1'

### ISSUE THREAD

**Issue by Jay2k1** [sequelpro/sequelpro#3113]
I am trying to save a few queries as favourites, but because I only need them on a certain host, I didn’t want to add them as global favs. 
However, the only other option I see is `unnamed 4` (it's the 4th open connection tab in this case). If I close the tab, make a new via `Cmd+T` and re-open the same host favourite, the 'Favourites' dropdown is only showing `unnamed 5` and `global` headings. Repeat and you get 6.

![image](https://user-images.githubusercontent.com/2070503/42819347-95fe1ed8-89d3-11e8-9ee7-4f8c7d1af587.png)

I am using version 1.1.2 build 4541 (602e11a) and am using a connection favourite with SSH (yes, it has a name).

I don't understand what I am missing. Shouldn't there be a connection between the host and the query favourites?

**Comment by dmoagx** [comment]
"Unnamed 1" is the name of the connection document. 
You can save it via File > Save connection.
This is unrelated to connection favorites.
