### ISSUE TITLE
About opening a table in the new tab, thanks with my best wishes!

### ISSUE THREAD

**Issue by oknixus** [sequelpro/sequelpro#3117]
Hi, Sequel Pro is a very good db tool.  But I have a question. How to open a table in the new tab without login again? Thank you very much. Best wishes!

**Comment by dmoagx** [comment]
Right Click on the table in the tables list and Select "Open Table in New Tab" or go to File > Duplicate Tab (hold down the alt key)

**Comment by oknixus** [comment]
@dmoagx Good, thanks a lot. Is there a shortcut key on this action ?

**Comment by oknixus** [comment]
I have look up it in [shortcut key](https://sequelpro.com/docs/get-started/keyboard-shortcuts). Nothing about the action
