### ISSUE TITLE
[REQ] Copy/Paste support for fields in Table structure view

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#312]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=312
Reporter:avenja...@gmail.com Date:2009-06-24 17:56:31 Status:Accepted

Similar to the Content View feature where you can copy rows as SQL insert statements it would be 
good to support copying of columns/fields in the Structure view as SQL alter statements.

This would allow the user to copy columns from one table and add them to another table easily.

Where there is a conflict of column/field name then present a dialog with 3 options:
- Keep existing column
- Keep new column - this would update the structure of the existing column - not replace it
- Keep both - changing the name of the new column by appending some string eg &quot;copy&quot; or &quot;new&quot;

**Comment by fulldecent** [comment]
I recommend to close this in favor of #213 

The transaction could produce a SQL statement that you could replay elsewhere.
