### ISSUE TITLE
Loading DB but not tables

### ISSUE THREAD

**Issue by sasafister** [sequelpro/sequelpro#3123]
Everything was working fine, but suddenly it stoped working. I have localhost setup and it's really basic stuff. When I load that config it connect's, but when I select one DB I want to see, it stop working.

![Image of Yaktocat](https://i.imgur.com/dxgm0nO.png)

**Comment by dmoagx** [comment]
Duplicate of #2699

**Comment by sasafister** [comment]
This doesn't solve this issue. I have macbook air and everything works fine, but on my new macbook pro it doesn't work :/
