### ISSUE TITLE
Remind or save export options

### ISSUE THREAD

**Issue by muuvmuuv** [sequelpro/sequelpro#3134]
Would be great if SequelPro would remind the boxes I have checked on export a database or if I could save those export settings as a preset somewhere.

**Comment by dougc84** [comment]
I came here to suggest this.  I routinely (several times a week) pull a copy of our production database, but always exclude the content within some tables (excessively large for an export, unnecessary for local use, etc.).  It would be great to be able to save a template of what's checked and unchecked, and set a default for anything that might not have been present next time (i.e. include and/or exclude S C D for new tables, etc.).

A simple solution could be a simple JSON file that's loaded into a new menu option (File > Export from template...), then drops you into the export window with the proper S C D checkboxes checked or unchecked, a filename set to the syntax specified, and the include S C D and advanced options on the right hand panel saved.

**Comment by dmoagx** [comment]
That feature already exists on master branch.

**Comment by dougc84** [comment]
@dmoagx Care to explain where then?
