### ISSUE TITLE
[REQ] Save query history per connection

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#314]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=314
Reporter:timmycha...@gmail.com Date:2009-06-26 11:26:05 Status:Accepted

I often work with multiple windows, each connected to a different MySQL server. Since query history 
is saved globally, I often lose query history in all but the last Sequel Pro window I close.

It would be nice if query history was saved in association with the connection or favorite instead of 
globally. That way, when I connect to server A, my query history shows the queries I recently ran on 
server A, and when I open a new window to connect to server B, all of my server B query history is 
listed in that window, and both windows will save future queries to their respective histories.

I realize that this might be addressed by some of the other &quot;tabbed interface&quot; requests, so feel free 
to combine this request as needed. Thanks.

**Comment by fulldecent** [comment]
Recommend to closed as fixed.

![screen shot 2017-03-27 at 8 24 18 pm](https://cloud.githubusercontent.com/assets/382183/24383526/65ea9872-132b-11e7-891a-fc3e685fd049.png)

**Comment by abhibeckert** [comment]
It's not fixed, the console is global for all connections.

We need a separate console for each connection. The "connection" column is just the domain name of the server, which is often just "localhost" even for a remote server.

Also, the console should be saved to disk as part of the favourite so you can view queries executed 3 days ago.
