### ISSUE TITLE
Opening a table as a new tab

### ISSUE THREAD

**Issue by sb16** [sequelpro/sequelpro#3144]
Hi,

I use sequel pro quite a lot to check and manipulate data.
It would be better if a new table is opened in a new tab.
The problem is if I want to check in a different table, the last table closes and I need to search again the data in last table.

**Comment by stuconnolly** [comment]
This can be achieved by right-clicking a table and selecting 'Open Table in New Tab.

<img width="339" alt="screenshot 2018-10-13 at 23 08 53" src="https://user-images.githubusercontent.com/223144/46910483-2aa1c680-cf3d-11e8-9b2e-aa3563e7e912.png">
