### ISSUE TITLE
Progress bar hangs when app is not in foreground

### ISSUE THREAD

**Issue by boehle** [sequelpro/sequelpro#3149]
The progress bar showing e.g. the import progress does not progress when the app is not the active app, whereas the text showing the progress e.g. "2.2 GiB of 2.4 GiB imported" gets updated.

![progress not updated](https://user-images.githubusercontent.com/5307838/44987587-faebc000-af87-11e8-9c36-17dec5f43b41.png) ![progress updated](https://user-images.githubusercontent.com/5307838/44987588-fde6b080-af87-11e8-8ef9-725e9c3c4c59.png)

**Comment by dmoagx** [comment]
Which version of Sequel Pro / OS / db server?

**Comment by dmoagx** [comment]
No feedback from reporter in > 1 month, closing.

**Comment by boehle** [comment]
Didn't get around to it. Just stumbled upon it again.
Back then I was running Mojave beta as well as Sequel Pro 1.1.2 and thought maybe it's due to the beta.
But now I'm running the release version for 10.14 and Sequel Pro 1.1.2 (4541) and the issue still persists.

**Comment by dmoagx** [comment]
Bugs filed against 1.1.2 will no longer be looked at.
Try a nightly build from https://sequelpro.com/test-builds

**Comment by boehle** [comment]
kk. I'll check it out later.
