### ISSUE TITLE
Sequel pro hanging on loading database.

### ISSUE THREAD

**Issue by Gavin-Currie** [sequelpro/sequelpro#3153]
Hey Folks,
Hey I'm doing a laravel blog tutorial and I'm up to the part where you migrate a database called 'blog'
so, I've connected to sequel pro, and I go to load the database from the dropdown and......
the 'please wait' avatar is still spinning as I type this.
I think I have all the .env settings correct (i hope)
hmm. I'm rubbing my chin a lot.
any tips?
flick me an email: gavincurrie0gmail.com

**Comment by dmoagx** [comment]
https://github.com/sequelpro/sequelpro/wiki/How-do-I-write-a-proper-issue-report%3F

**Comment by dmoagx** [comment]
Invalid
