### ISSUE TITLE
How can I connect to AWS RDS using IAM Authentication?

### ISSUE THREAD

**Issue by TheKnightCoder** [sequelpro/sequelpro#3159]

**Comment by dmoagx** [comment]
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.Connecting.AWSCLI.html

The equivalent of `--enable-cleartext-plugin` with Sequel Pro is to either use the unofficial test build mentioned in https://github.com/sequelpro/sequelpro/issues/2996#issuecomment-379089685 or to launch SP as mentioned in https://github.com/sequelpro/sequelpro/issues/2247#issuecomment-144567527

**Comment by jdrydn** [comment]
This would be slick - especially if it supported the `~/.aws` credentials from disk!

Also if this is still in "planning"/enhancement stage, throwing in support for different AWS profiles would be greatly appreciated!

**Comment by wulfmann** [comment]
Is there anybody still looking at this? I'd love to have this feature.

**Comment by phundisk** [comment]
I think you should reopen this as there does not appear there are any SQL clients that integrate with the new AWS RDS IAM access model.  This would be a good feature to have.

**Comment by amazingandyyy** [comment]
Can we re-open this, since apparently this issue is not resolved and it's a feature really needed?

**Comment by ghost** [comment]
+1 we need this feature
