### ISSUE TITLE
Sequel Pro crashes each time I close a tab with an open tunnel connection

### ISSUE THREAD

**Issue by abbatis** [sequelpro/sequelpro#3160]
When connected to a database through a tunnel using SSH while having multiple tabs open, close the tab with the open tunnel connection. Sequel Pro will crash.

**Comment by dmoagx** [comment]
Duplicate of #3116

**Comment by tiredoy** [comment]
https://github.com/sequelpro/sequelpro/issues/3116#issuecomment-432148453
