### ISSUE TITLE
SPF file not saved when connection lost

### ISSUE THREAD

**Issue by eugene-kulak** [sequelpro/sequelpro#3163]
Steps to reproduce:

1. open connection (tab)
2. type some queries, save
3. change queries
4. close connection (kill db, disable network, etc)
5. your changes to spf file lost now

Possible fix:
- ask 'user' before closing tab 'do you want to save your changes'
- do not use modal dialogs
- allow tab to be open even if connection closed

**Comment by dmoagx** [comment]
Duplicate of #1016
