### ISSUE TITLE
Move sequel pro group from slack to gitter

### ISSUE THREAD

**Issue by jpike88** [sequelpro/sequelpro#3178]
Instead of trying to extract a slack invite from members (which I never got responses to), doesn't it make more sense to use something everyone already has credentials for? Right now to an outsider it looks like there is zero movement, and it's hard to get involved if some people are difficult to contact.

**Comment by toddstoffel** [comment]
@jpike88 or @dmoagx Can you both let me know how to reach you outside of Github?  I might be able to assist with this project in a substantial way.  I have written to @abhibeckert but I do not know if those messages were received.  I would like to see this project continue.

**Comment by jpike88** [comment]
I’m on the outside still

**Comment by toddstoffel** [comment]
@jpike88 That's ok, I just wanted to make sure we don't start forking this thing out of frustration. I'm hoping that I might be able to assist in finding a permanent open source home for this project. It appears you have had trouble getting ahold of the project owner and I'm sort of just trying to determine the project hierarchy at this point. I though maybe you had information you could share.

**Comment by jpike88** [comment]
@dmoagx is the guy to ask I think, he's close to the top of the hierarchy as far as I know

**Comment by dmoagx** [comment]
Well the project hierarchy consists of two project owners and the others are project members. I'm a project member, so, yes I'm close to the top but also in the bottom tier at the same time 😀

Matt has announced that he will have a talk with Abhi about the project status over the weekend, so we'll wait what comes out of that.

Also you can find my mail address by looking at my older commits.

**Comment by Kaspik** [comment]
@jpike88 I wanted to invite you but you never gave us email.

**Comment by jpike88** [comment]
Eh I mailed Abhi directly a few times and thought that was enough... glad to see things are moving though

**Comment by jpike88** [comment]
Josh

At

S t r e a k a

Dot 

Com

**Comment by fake-fur** [comment]
i'd also be interested to help in some way when things get moving again

**Comment by pedzed** [comment]
![image](https://user-images.githubusercontent.com/8146593/47069804-23eeaa00-d1f0-11e8-933d-6d577596c8b9.png)

https://get.slack.help/hc/en-us/articles/201330256-Invite-new-members-to-your-Slack-team
