### ISSUE TITLE
Crash when I close 1 of 2 tabs on new Mac OS Mojave 10.14

### ISSUE THREAD

**Issue by jlcanizales** [sequelpro/sequelpro#3183]
if I have more than 1 tab of connections and I close on the "x" of any connection it will kill sequel app.
im using Sequel pro 1.1.2 (compilation 4541 602e11a) on Mac OS Mojave 10.14, it doesn't happens on the last version of Mac OS High Sierra

**Comment by anotherdevs** [comment]
Duplicate of #3182 #3177 #3176 #3175 #3124 #3116 #3075

Which is just sad that you didn't bother using the search function. Allow me to help you: https://github.com/sequelpro/sequelpro/issues?utf8=%E2%9C%93&q=Mojave

However see this: #3034 @abhibeckert and @mattlangtree have abandoned Sequel Pro and @dmoagx will carry it on in a fork.

**Comment by jlcanizales** [comment]
sorry for duplicate, and thanks for the answer

**Comment by sarthaksavvy** [comment]
Thanks for answer, sorry for this
