### ISSUE TITLE
How does Spotlight know I mean SequelPro when I search for "pancakes"?

### ISSUE THREAD

**Issue by cviebrock** [sequelpro/sequelpro#3188]
Just discovered this today: if I open Spotlight and start typing `pancakes`, the first suggestion it makes is for SequelPro.

Is this something in the code, or is it just magic?

**Comment by raunsbaekdk** [comment]
https://github.com/sequelpro/sequelpro/blob/c541d630ac2e57dcafb2ae15c99cfa3a6e84cfee/Scripts/build.sh#L126

**Comment by dmoagx** [comment]
This is an inappropriate discussion for an issue tracker.
