### ISSUE TITLE
Publish a new release

### ISSUE THREAD

**Issue by leaxoy** [sequelpro/sequelpro#3191]
I noticed that the last official build is one year ago, there many feature during this year(mysql 8 support, dark mode..) we can't use, so it's great to publish a new release.

**Comment by brunnopleffken** [comment]
I agree... It's been two and a half years since the last update, I'm not using Sequel Pro anymore because it just doesn't support MySQL 8... BTW, after upgrading to macOS Mojave, the UI seems a little out of place...

**Comment by daniesy** [comment]
@brunnopleffken what are you using now?

**Comment by brunnopleffken** [comment]
> @brunnopleffken what are you using now?

I'm using TablePlus, for both MySQL 8 and PostgreSQL.

**Comment by daniesy** [comment]
Thanks, i'll give it a shot

**Comment by dmoagx** [comment]
Duplicate of #3034
