### ISSUE TITLE
Crashing after closing tab on macOS Mojave

### ISSUE THREAD

**Issue by stianulriksen** [sequelpro/sequelpro#3198]

**Comment by schmoove** [comment]
+1

**Comment by dmoagx** [comment]
I'll take that as a +1 for [no more work on Sequel Pro](https://github.com/sequelpro/sequelpro/issues/3175#issuecomment-424452480).

**Comment by thewinterwind** [comment]
This is happening to me as well. Closing a tab on 1.1.2 on Mojave crashes it.
