### ISSUE TITLE
Can't scroll left or right when you only have a mouse and no trackback

### ISSUE THREAD

**Issue by pjebs** [sequelpro/sequelpro#3200]
For the table that shows the data, can't scroll left or right.

**Comment by feisar-uk** [comment]
This depends on the type of mouse you have.

If you use an Apple Magic Mouse you can scroll left and right using the touch surface.

Alternatively, in **System Preferences > General**, do you have the **Show scroll bars** setting set to **Always**? Then you can use the visible window scrollbars to scroll left and right.

**Comment by dmoagx** [comment]
Also most better mice nowadays support sideways scrolling by pressing on the side of the scroll wheel.

Also OS X changes the scroll axis if you hold down the shift key while scrolling.
