### ISSUE TITLE
SequelPro crashes when closing tabs on macOS Mojave 10.14

### ISSUE THREAD

**Issue by feisar-uk** [sequelpro/sequelpro#3201]
Crash log attached
[Sequel Pro_2018-10-03-081732_Mac-mini.txt](https://github.com/sequelpro/sequelpro/files/2441012/Sequel.Pro_2018-10-03-081732_Mac-mini.txt)

**Comment by phpanos** [comment]
I have the same issue.

**Comment by feisar-uk** [comment]
Sorry, didn't see existing report here: 
https://github.com/sequelpro/sequelpro/issues/3116

**Comment by stuconnolly** [comment]
Duplicate of #3116

**Comment by yadgen** [comment]
Me, too.

**Comment by octante** [comment]
+1

**Comment by bannostookaylo** [comment]
This keeps happening to me as well... replacing what software I use today... sorry SequelPro

**Comment by bannostookaylo** [comment]
Well I deleted my previous comment on here because I saw this was a duplicate issue... BUT that other issue is closed to new comments... I am still having a crashing issue every time I close a tab.

**Comment by bannostookaylo** [comment]
Looks like using https://github.com/sequelpro/sequelpro/files/2506508/Sequel.Pro-2.zip solved my issue
