### ISSUE TITLE
App crashes all the time on Mojave

### ISSUE THREAD

**Issue by gregblass** [sequelpro/sequelpro#3208]
Ever since I upgraded to Mojave, the app has become fairly unstable. Lots of random crashes. Anyone else experiencing this? I can give more details if necessary, but wanted to throw a feeler out there. Was surprised no one else had reported anything yet.

**Comment by gregblass** [comment]
It seems to be that it crashes once on load, and then reloads, and is fine.

**Comment by stuconnolly** [comment]
Duplicate of #3116

**Comment by gregblass** [comment]
I was not opening two tabs at all. This is not a duplicate.

**Comment by gregblass** [comment]
Unless the issue is un-related to opening two tabs. But I only had one tab open.
