### ISSUE TITLE
Fix compiler warnings

### ISSUE THREAD

**Issue by stuconnolly** [sequelpro/sequelpro#3221]
We currently have about 183 compiler warnings which we should address since they're warnings for a reason.

Note, that some of them will be because we're still targeting the 10.6 SDK.

**Comment by Kaspik** [comment]
PR https://github.com/sequelpro/sequelpro/pull/3218 - fixing:
- `SPConnectionController.m` + `SPFilterTableController.m` - "Object can not respond to selector" - `respondsToSelector` is checked so changed type of object
- `SPEditorPreferencePane.m` + `SPTextView.m` + `SPCustomQuery.m` - return type of method to `NSFontPanelModeMask` type as it's subclass of method that has this return type
- `SPNavigatorController.m` + `SPTextView.m` - missing default case
- `SPRuleFilterController.m` - Compare NSUInteger vs NSInteger - changed type to NSUInteger for all comparasions

**Comment by Kaspik** [comment]
Except PR https://github.com/sequelpro/sequelpro/pull/3218 currently postponed until we release 1.2 and then drop 10.6 - 10.x support as a lot of warnings is there because of 10.6 - 10.10 support.
