### ISSUE TITLE
Update Multiple Connection Favorites Simultaneously

### ISSUE THREAD

**Issue by deepSymmetry** [sequelpro/sequelpro#3227]
Currently there is no way to do a bulk update passwords of multiple connections when passwords for all the different connections (to different hosts/databases) are same. My password expire often (company policy) and I then need to iteratively update 20+ connections (A password each for SQL and SSH host, hence 40+ times).

Unfortunately, MacOs doesn't allow bulk update to Keychain. If it is possible then please let me know so that I may use in the interim.

Thank you for the nicest MacOS SQL tool.

**Comment by dmoagx** [comment]
This is a highly specific request.
I agree that the same SSH host+port+username could all be stored only once in keychain for multiple favorites.
It has been this way in the past, but that has caused other issues IIRC.

Not sure what to do about this.
The only thing we could perhaps do is when a user is updating a favorite and saving it, check if there are other favorites with the same host+port+username and ask if they want to change all favorites.

**Comment by deepSymmetry** [comment]
That will be perfect. Just to clarify, by host you mean the SQL host (usually the loopback address - 127.0.0.1) and not the SSH host because each connection favorite is for a different host machine. Thank you.

**Comment by dmoagx** [comment]
Hm, that won't work.
We could detect a SSH password change when there are multiple connections with the same ssh host+ssh port+ssh user and we could detect a MySQL password change when there are multiple connections with same ssh host+ssh port+ssh user+mysql host+mysql port+mysql user.

But different SSH hosts won't work.
I also have a lot of connections with same mysql host+port+user (namely 127.0.0.1+3306+root) and different SSH connections, which naturally are completely different installations (as I think would be the case for the vast majority of people).
