### ISSUE TITLE
Get Involved/Contribute: bad links

### ISSUE THREAD

**Issue by tewha** [sequelpro/sequelpro#3230]
I spotted a couple broken links related to source code and development.

From `https://sequelpro.com/docs/contribute/get-involved`:

* `file:///Users/abhi/Downloads/www.sequelpro.com/docs/Source_Code.html`
* `file:///Users/abhi/Downloads/www.sequelpro.com/get-involved.html#chat-to-the-developers`

From `https://sequelpro.com/docs/contribute/coding`:

* `docs/Compiling_Sequel_Pro`
* `docs/Developer_Tools`
* `docs/Source_Code`

Should probably just link to Github. :)

**Comment by stuconnolly** [comment]
Duplicate of #2715
