### ISSUE TITLE
Crashed after closing tabs - Mojave

### ISSUE THREAD

**Issue by tajhulfaijin** [sequelpro/sequelpro#3246]
- Sequel Pro Version: 1.1.2
- macOS Version: 10.14
- MySQL Version:

**Description**
After I upgrading my OS to OSX Mojave, everytime I open multiple tabs then closing one of it, the sequelpro always crashed

**Steps To Reproduce**
1. Connect to db in multiple tabs
2. Close one of it

**Expected Behaviour**
Not crashed. 

<img width="1054" alt="screen shot 2018-10-18 at 21 06 56" src="https://user-images.githubusercontent.com/2231253/47160301-d0787b00-d319-11e8-9932-c1cedda47c1b.png">

**Comment by mbuk** [comment]
See here:
[https://github.com/sequelpro/sequelpro/issues/3116](https://github.com/sequelpro/sequelpro/issues/3116)

Here: [https://github.com/sequelpro/sequelpro/issues?utf8=%E2%9C%93&q=is%3Aissue+mojave++crash](https://github.com/sequelpro/sequelpro/issues?utf8=%E2%9C%93&q=is%3Aissue+mojave++crash)

**Comment by stuconnolly** [comment]
Duplicate of #3116
