### ISSUE TITLE
When I connected database I got an error

### ISSUE THREAD

**Issue by AlexanderBoogai** [sequelpro/sequelpro#3252]
Like this (https://prnt.sc/l9m883)

**Comment by stuconnolly** [comment]
Any chance of more details, specifically what's detailed in the bug report template?

https://github.com/sequelpro/sequelpro/issues/new?template=bug_report.md

**Comment by dmoagx** [comment]
Yeah, not going to bother casing after issue descriptions to what in the end will just be another MySQL 8.0 duplicate
