### ISSUE TITLE
Command + f without selecting a table crashes the app

### ISSUE THREAD

**Issue by n3t0cfg** [sequelpro/sequelpro#3255]
- Sequel Pro Version: Snapshot Build 481 (f9f6908)
- macOS Version: 10.14

**Description**
Just after connecting to a database, if you press 'Command + f' to open the search bar without selecting a table crashes the app.

**Steps To Reproduce**
1. Open Sequel Pro.
2. Connect to a database.
3. Press 'Command + f'.
4. Click a table from the list.

**Expected Behavior**
Search bar should not open if there's no table selected

![screen shot 2018-10-25 at 2 51 03 pm](https://user-images.githubusercontent.com/1394795/47523166-673abf80-d865-11e8-832b-d09f363d75a2.png)

**Comment by stuconnolly** [comment]
Could you possibly provide the exception details as I'm unable to reproduce this?

**Comment by n3t0cfg** [comment]
Note: Editor empty space needs to be focused (you need to click it first)

### Exception tab

> NSRangeException
> 
> *** -[__NSArrayM objectAtIndex:]: index 0 beyond bounds for empty array
> 
> (
> 	0   CoreFoundation                      0x00007fff315e7571 __exceptionPreprocess + 256
> 	1   libobjc.A.dylib                     0x00007fff5d594efb objc_exception_throw + 48
> 	2   CoreFoundation                      0x00007fff31627080 -[CFPrefsConfigurationFileSource initWithConfigurationPropertyList:containingPreferences:] + 0
> 	3   CoreFoundation                      0x00007fff3151f417 -[__NSArrayM objectAtIndex:] + 151
> 	4   Sequel Pro                          0x0000000104fd3875 -[SPRuleFilterController _serializeSubtree:includingDefinition:] + 728
> 	5   Sequel Pro                          0x0000000104fd346a -[SPRuleFilterController _serializedFilterIncludingFilterDefinition:] + 322
> 	6   CoreFoundation                      0x00007fff3153d0ec __invoking___ + 140
> 	7   CoreFoundation                      0x00007fff3153cfb7 -[NSInvocation invoke] + 311
> 	8   CoreFoundation                      0x00007fff3159e1a1 -[NSInvocation invokeWithTarget:] + 56
> 	9   Foundation                          0x00007fff3393b1f5 -[NSObject(NSThreadPerformAdditions) performSelector:onThread:withObject:waitUntilDone:modes:] + 1123
> 	10  Foundation                          0x00007fff33942d9a -[NSObject(NSThreadPerformAdditions) performSelectorOnMainThread:withObject:waitUntilDone:] + 131
> 	11  Sequel Pro                          0x0000000104fb0a52 -[SPMainThreadTrampoline forwardInvocation:] + 157
> 	12  CoreFoundation                      0x00007fff3158653c ___forwarding___ + 762
> 	13  CoreFoundation                      0x00007fff315861b8 _CF_forwarding_prep_0 + 120
> 	14  Sequel Pro                          0x0000000104f7d855 -[SPHistoryController updateHistoryEntries] + 298
> 	15  Sequel Pro                          0x0000000104f0856c -[SPTablesList tableViewSelectionDidChange:] + 333
> 	16  CoreFoundation                      0x00007fff31592076 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
> 	17  CoreFoundation                      0x00007fff31591ff0 ___CFXRegistrationPost_block_invoke + 63
> 	18  CoreFoundation                      0x00007fff31591f11 _CFXRegistrationPost + 398
> 	19  CoreFoundation                      0x00007fff3159a24d ___CFXNotificationPost_block_invoke + 87
> 	20  CoreFoundation                      0x00007fff315013a4 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1804
> 	21  CoreFoundation                      0x00007fff31500649 _CFXNotificationPost + 854
> 	22  Foundation                          0x00007fff338a0bab -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
> 	23  AppKit                              0x00007fff2ec3049f -[NSTableView _sendSelectionChangedNotificationForRows:columns:] + 230
> 	24  AppKit                              0x00007fff2ee2d5ee -[NSTableView mouseDown:] + 6236
> 	25  AppKit                              0x00007fff2ecb0797 -[NSWindow(NSEventRouting) _handleMouseDownEvent:isDelayedEvent:] + 5668
> 	26  AppKit                              0x00007fff2ebe47cf -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] + 2319
> 	27  AppKit                              0x00007fff2ebe3c75 -[NSWindow(NSEventRouting) sendEvent:] + 481
> 	28  Sequel Pro                          0x0000000104fe89fc -[SPWindow sendEvent:] + 712
> 	29  AppKit                              0x00007fff2ea80f4c -[NSApplication(NSEvent) sendEvent:] + 336
> 	30  AppKit                              0x00007fff2ea6e795 -[NSApplication run] + 755
> 	31  AppKit                              0x00007fff2ea5de97 NSApplicationMain + 780
> 	32  Sequel Pro                          0x0000000104e9a394 start + 52
> )
>
