### ISSUE TITLE
Incorrect character set/collation when connecting to server

### ISSUE THREAD

**Issue by dlangh** [sequelpro/sequelpro#3257]
- Sequel Pro Version: 1.1.2
- macOS Version: 10.14
- MySQL Version: MariaDB 10.2.16, MariaDB 10.2.18, MariaDB 10.3.10 and mysql 5.5.60

**Description**
When you use Sequel Pro to connect to a mysql or mariaDB server it does not use the correct collation or even the correct character set when it is set to auto-detect.  I have several MariaDB servers that are all using UTF8mb4 and collation UTF8MB4_unicode_ci, however it is not possible for me to get Sequel Pro to ever connect with that, either via auto-detect encoding or UTF8 Full Unicode options.  Autodetect results in utf8_general_ci and UTF8 full unicode results in utf8mb4_general_ci.  The problem with this  is that whenever I create a view it's fields are set to the collation that Sequel Pro has chosen and it causes collation errors when interacting with those views, for example when joined with another table, the ON or where clauses will throw errors.  It is my understanding that the server can specify the desired character set and collation for clients to use, but Sequel Pro ignores this.  Finally the one Mysql Server I have is actually set for latin1_swedish_ci, but with autodetect Sequel Pro also chooses the wrong encoding there.

**Steps To Reproduce**
1. Configure your mysql/MariaDB server for UTF8mb4_unicode_ci ( or really anything other than utf8_general_ci).  I configured mine with these settings in my.cnf:

```
[client]
default-character-set=utf8mb4

[mysql]
default-character-set=utf8mb4

[mysqld]
character-set-client-handshake = FALSE
character-set-server=utf8mb4
collation-server=utf8mb4_unicode_ci
init_connect='SET collation_connection = utf8mb4_unicode_ci'

```
2. Using either Sequel Pro or mysql client on server, create a table with some varchar/char/text fields, confirm they are using the collation set on the server.  I don't know why but creating a table even in sequel pro it uses the collation set by the server.
2. Connect to the database with Sequel Pro, the run the following query:
`SHOW VARIABLES LIKE 'coll%';`  The first variable is the collation in use for the client.  It won't be correct.  Further, if you connect to the same server using the linux mysql command line app and run the same command you'll see that it is the correct collation.  If you happen to have phpMyAdmin, use that to connect, running the same command will also result in the correct collation.
3. Create a view, it does not need to be complicated, but it must have varchar/char/text  fields in it,  once you do view the structure for that view, note that the varchar/char/text fields all have the collation set by Sequel Pro which will be the wrong collation.  Now if you use that view (I discovered it when I used a SELECT statement against it inside a stored procedure and tried to use an IN variable in a where clause.  I got a collation error when running that stored procedure.
4. Finally run this in Sequel Pro: SET collation_connection=utf8mb4_unicode_ci;  Now repeat step 3 you will see that the structure shows to correct collation.

**Expected Behaviour**
I expect when using Auto-Detect that Sequel Pro will use the character set and collation that the server defaults to.  If that is not possible (I don't know the ins and outs of how the mysql connect api works) then it would be great if an additional encoding option could be added to support utf8mb4_unicode_ci.  I chose this collation after reading about shortcoming with the general collation that resulted in incorrect sorting in some languages and many posts that recommended unicode over general.

**Additional Context**
For what it is worth, MYSQLWorkBench has the same problems here as Sequel Pro, but the mac app 'SQLPro for MYSQL' does not have this issue, it connects with the correct encoding and seems to use whatever the server is set for

**Comment by dmoagx** [comment]
Sequel Pro never explicitly sets a collation, which means the server will use whatever collation is the default for the charset.
You can look this up in the `information_schema.character_sets` table.

This is unrelated to what you configured as the default charset and default collation for the server or connection. If a client executes `SET NAMES charset;` (which SP does), MySQL will use the collation seen in the information_schema table. 

I think you have to actually recompile MySQL to change these defaults.

**Comment by mjaggard** [comment]
I don't think I've changed anything either in MySQL or in Sequel Ace and I've just started getting this annoying popup. Did anyone have a fix?

**Comment by mjaggard** [comment]
FYI for anyone facing this error: https://github.com/Sequel-Ace/Sequel-Ace/issues/1064
