### ISSUE TITLE
New UI (build 5418) Connection details label text color not changable

### ISSUE THREAD

**Issue by jeffkreska** [sequelpro/sequelpro#3264]
In the build mentionen, the connection label color have changed slightly and the text color has changed to white.  There is not enough contrast with most of the colors available to easily read the text.

Ability to change the text color and/or ability to use any color instead of the 8 pre choosen colors.

I have attached a screenshot showing previous version and current version for comparision.

![screen shot 2018-10-30 at 8 06 33 am](https://user-images.githubusercontent.com/2659845/47719967-c4929000-dc1a-11e8-9928-4f73c9955de7.png)

**Comment by dmoagx** [comment]
The color is white because you are using dark mode.
Also the favorite colors have always been changeable, since this feature has been added (there is just no GUI for it).

**Comment by wang-zc** [comment]
When you open a single window, the color will be displayed. Is this a feature or a bug?
![default](https://user-images.githubusercontent.com/3386972/47763760-f714b980-dcfc-11e8-9f22-629bddc36e23.png)

**Comment by lucasmezencio** [comment]
I agree that the contrast is terrible!

**Comment by kaidesu** [comment]
> When you open a single window, the color will be displayed. Is this a feature or a bug?
> ![default](https://user-images.githubusercontent.com/3386972/47763760-f714b980-dcfc-11e8-9f22-629bddc36e23.png)

That's a feature - has always been that way as far as I remember. It's very useful!

**Comment by KarimGeiger** [comment]
I second that request. The green labels are barely readable. I'd prefer either the option to be completely free in picking the color, or to reduce the colors to a more subtile tone.

**Comment by aledexter** [comment]
> The color is white because you are using dark mode.
> Also the favorite colors have always been changeable, since this feature has been added (there is just no GUI for it).

How to change color without GUI?
