### ISSUE TITLE
Import shows "Reading File" and doesn't update progress unless blurred/focused

### ISSUE THREAD

**Issue by obfuscode** [sequelpro/sequelpro#3266]
- Sequel Pro Version: 5418 (78067124)
- macOS Version: 10.14
- MySQL Version: 5.5.61
- macOS Dark Mode: Yes

**Description**
When importing a large file (~400MB), the import progress window displays "Reading File" and only updates the progress if you blur the app (click on another app) or focus the app when it is not focused already. The import succeeds but the progress never updates during import nor does it show which tables it's importing like it used to.

**Steps To Reproduce**
1. Open SequelPro
2. Import DB

**Expected Behaviour**
The import progress window to update the progress bar on its own. To show what tables it is currently importing.

**Additional Context**
I am running in Dark Mode.

![import_update_on_focus](https://user-images.githubusercontent.com/2160089/47793429-a13c1380-dcf4-11e8-9da1-ea99d870ff77.gif)

**Comment by freezey** [comment]
I'm seeing the same issue with build 5418 as well. I'm trying to load a 500MB .tar.gz file (~5GB of uncompressed SQL data).

**Comment by jkjkjkkl** [comment]
I have the same problem. I'm trying to load a 200MB .sql file.Do you solve the problem?

**Comment by gms8994** [comment]
Can confirm, same behavior on build 5425 (df10e20) macOS Version 10.14.

**Comment by jkjkjkkl** [comment]
@gms8994, I download the newest version app, but the problem still exist._

**Comment by philippechevieux** [comment]
I'm facing the same issue. Does someone has an idea what could cause this ?

**Comment by gms8994** [comment]
@philippechevieux probably switch to Sequel Ace as Sequel Pro is effectively dead.
