### ISSUE TITLE
Mac 10.14 system crashed

### ISSUE THREAD

**Issue by pengleelove** [sequelpro/sequelpro#3269]
Mac OS 10.14. Open multiple TAB tabs and crash when closed. Please check

**Comment by tang2606** [comment]
me too .

**Comment by larsjanssen6** [comment]
me too.

**Comment by jbrooksuk** [comment]
You can confirm this by:

1. Open multiple tabs
2. Close one of the tabs
3. See crash

**Comment by mitoop** [comment]
The build version with last commit slove this problem. 
Also , the sequel official at last build in the [Nightly Builds](https://sequelpro.com/test-builds)

**Comment by phmunhoz** [comment]
This issue is a duplicate of #3116. Someone may close it?
