### ISSUE TITLE
i got a question when i use two tab pages

### ISSUE THREAD

**Issue by yangqingmang** [sequelpro/sequelpro#3270]
I opened two tab pages, switched back and forth, and then there was garbled
this is the first tab
![image](https://user-images.githubusercontent.com/18325564/47848206-907cc200-de08-11e8-9113-f725df29cac3.png)

this is the second tab
![image](https://user-images.githubusercontent.com/18325564/47848241-af7b5400-de08-11e8-966c-9f396c9463cc.png)

**Comment by yangqingmang** [comment]
mac 10.14

**Comment by dmoagx** [comment]
#3214
