### ISSUE TITLE
Sequel Pro sometimes hangs when following a foreign key

### ISSUE THREAD

**Issue by RonaldFindling** [sequelpro/sequelpro#3275]
- Sequel Pro Version: 1.1.2 BUild 4541 (602e11a)
- macOS Version: High Sierra 10.13.6 (17G65)
- MySQL Version: Ver 14.14 Distrib 5.7.24

**Description**
Sometimes when following a foreign key using the little arrow in the content view of a table sequel pro gets unresponsive and has to be killed and restarted manually.

**Steps To Reproduce**
Click on the arrow key next to a foreign key in the content view of a table -- the UI will get unresponsive.
Happens sporadically -- I can't reliably reproduce it.

**Expected Behaviour**
The content few changes it's filter criteria to the foreign key value to show me this entry.

**Additional Context**
I have mostly seen this on references from a table to the same table -- not sure if it is exclusive.
I don't know where to find logs of sequel pro -- so I can't add further information atm.

**Comment by dmoagx** [comment]
We will no longer look into issues filed against 1.1.2.
Please retry with a current nightly build: https://sequelpro.com/test-builds

However, you will most likely see #2792 then.

**Comment by dmoagx** [comment]
Closing after no feedback from reporter
