### ISSUE TITLE
Use monospaced fonts doesn't work 5422 (81986f5d)

### ISSUE THREAD

**Issue by rsmck** [sequelpro/sequelpro#3284]
The Preferences > General > Use monospaced fonts option does not appear to affect display as expected in the recent nightly build 5422 (81986f5d)

**Comment by dmoagx** [comment]
And what do you expect?

**Comment by dmoagx** [comment]
Closing after no feedback from reporter

**Comment by rsmck** [comment]
Sorry, I didn't get a notification of this so missed it entirely, only found my own issue again when searching to log a new one... 

Seems this is the same in Build 5446 (97c1b857) - monospaced fonts are not used in the table view when "Use monospaced fonts" is selected. The checkbox below that ("Display vertical grid lines") works as expected.
