### ISSUE TITLE
[REQ] Edit multiple cells

### ISSUE THREAD

**Issue by cawa-93** [sequelpro/sequelpro#3285]
Today has faced a simple task: it is necessary to wash certain rows, and for each one to change one cell. I tried to highlight the column I needed, but I did not find anything like "Edit All" or "Set Value to Highlighted" in the interface. In my opinion, it would be good to have this opportunity.

**Comment by samuelbradshaw** [comment]
What if it behaved like a spreadsheet, where you could select several cells, then paste from the clipboard to all of the selected cells? You would want to have a confirmation message to make sure somebody doesn't overwrite a bunch of data accidentally.
