### ISSUE TITLE
When the fix for bug with crash if close a tab in Mojave will be released?

### ISSUE THREAD

**Issue by dmitrykinakh** [sequelpro/sequelpro#3286]
It's really annoying to keep using sequelpro due to issue https://github.com/sequelpro/sequelpro/issues/3116

A lot of users use more than one tab and all the time when you run something one tab and close another one you think...holy crap...

**Comment by lasergoat** [comment]
Yes, it's crashing all the time, including when you close the main SequelPro window

**Comment by dmoagx** [comment]
Everything that needs to be said has been said in #3116 already.
