### ISSUE TITLE
"Add index" Should not List JSON Columns

### ISSUE THREAD

**Issue by 9ae8sdf76** [sequelpro/sequelpro#3288]
Currently, the `Add index` interface will not allow TEXT columns to be added to an index. However, it does allow adding JSON columns, which results in the following error:

> MySQL said: JSON column 'my_column' cannot be used in key specification.

I am using `build 5423 (dee3201d)` with MySQL `5.7.22` on macOS High Sierra `10.13.5 (17F77)`.

**Comment by dmoagx** [comment]
> Currently, the Add index interface will not allow TEXT columns to be added to an index.

Sequel Pro does allow adding TEXT columns to indexes, as long as the index is either a FULLTEXT index or the indexing length of the column is specified…
