### ISSUE TITLE
Case Sensitivity on export

### ISSUE THREAD

**Issue by heffneil** [sequelpro/sequelpro#3292]
I noticed if I export a database all case sensitivity is lost.  This is a big problem when working with others on common assets.  Using ubuntu and latest version of mysql my installation is case sensitive.  

A developer created a stored procedure but unfortunately it didn't work because the tables are capitalized differently.

**Comment by dmoagx** [comment]
https://github.com/sequelpro/sequelpro/wiki/How-do-I-write-a-proper-issue-report%3F

**Comment by heffneil** [comment]
Hey buddy go suck an egg. If you could be any more prickish you could be POTUS
