### ISSUE TITLE
Changing screen sizes doesn't adjust height of content section appropriately

### ISSUE THREAD

**Issue by rwbarg** [sequelpro/sequelpro#3293]
- Sequel Pro Version: Build 5425 (df10e204)
- macOS Version: 10.14.1
- MySQL Version: 5.7.24

**Description**
When switching from a tall monitor to laptop (shorter monitor), the top of the window underneath the tab gets cut off. Similarly, when using a window-snapping tool (currently using BetterTouchTool), there is a large space between tab and content/query section. In other words, the height of the content/query section stays fixed when the height of the application jumps from one height to another.

**Steps To Reproduce**
Example 1
1. Use an external monitor that has more real estate than your laptop monitor and have Sequel Pro open and extended from top to bottom.
2. Unplug external monitor.

OR

Example 2
1. Have Sequel Pro open, but not full height of screen.
2. Use a window-snapping tool to "snap" to a size of the full height of screen.

**Expected Behaviour**
The height of the section below tabs (content section?) should adjust appropriately.

**Additional Context**

Example 1 screenshots:
![image](https://user-images.githubusercontent.com/4173769/48377945-dea98500-e694-11e8-8d9d-0a1ff3f5337c.png)
![image](https://user-images.githubusercontent.com/4173769/48377989-06005200-e695-11e8-960f-6d3af0ce3713.png)

Example 2 screenshots:
![image](https://user-images.githubusercontent.com/4173769/48378016-229c8a00-e695-11e8-9584-348a76fb5635.png)
![image](https://user-images.githubusercontent.com/4173769/48378031-2cbe8880-e695-11e8-9228-bafe218b85db.png)

**Comment by AaronHolbrook** [comment]
Yup I get the same exact issue when using Zooom to resize.

Worked fine before the latest nightly build.

**Comment by dmoagx** [comment]
For any windows resizing/alignment tools: #3091

Please check if the issue of changing screen sizes also occurs if you have those tools disabled.

**Comment by ivanmmj** [comment]
If it's the same issue that I'm having, the top height of the Query tab gets incorrectly set well above the actual height of the window.
This has the effect of not being able to see anything typed for the first several rows.

**Comment by adepssimius** [comment]
I also have this issue. Both with window snapping tool and when moving between monitors of different size with the tool disabled.

**Comment by rhoglund** [comment]
Same problem. Using BetterTouchTool to resize. This is pretty annoying.

**Comment by xiangbohua** [comment]
I'm facing this issue too.
I got two monitors and when i drag the window from the big one to my build-on monitor the window will hidden some elements.

**Comment by bladepop** [comment]
Any updates on this?

**Comment by MikeBeas** [comment]
It looks like this might be a duplicate of #3091 and _possibly_ #3287 as well. All three are marked as required for 1.2, but if they are all the same issue, could two of them be closed as duplicates and leave #3091 as the only one required for the next release?

It looks like a PR was made for #3091 over a year ago, so that issue could probably be moved into the In Progress column on the project board. Could that be reviewed and merged to get that issue all the way into the Done status?
