### ISSUE TITLE
saved queries stored as user directory (to enable simple cross-platform sync)

### ISSUE THREAD

**Issue by distraqt** [sequelpro/sequelpro#3297]
The problem: I want to update Sequel Pro saved queries on my macbook and have those updated queries available to other members of the team who work on the same databases. IMHO that's best served by a git repo jointly accessed and contributed to by members of the team.

The proposed solution: Sequel Pro should store the saved queries as separate .sql files on the local machine.

**Comment by samuelbradshaw** [comment]
I currently store queries that I want to use again as .txt files in a folder I keep backed up, then copy/paste them into the query editor. You would need to have some way in Sequel Pro to select a folder as your "saved queries" folder.

**Comment by xiangbohua** [comment]
I feel this should be done by my self because this feature will make this software to complex.Other software like Navicat should have this feature.
