### ISSUE TITLE
Error Adding Field to Wordpress wp_posts table

### ISSUE THREAD

**Issue by truecastdesign** [sequelpro/sequelpro#3300]
An error occurred when trying to add the field 'path' via

ALTER TABLE `wp_posts` ADD `path` VARCHAR(255)
 NOT NULL
 DEFAULT '/'
 AFTER `post_title`

MySQL said: Invalid default value for 'post_date'

The 'post_date' default value is the same as the other date fields 0000-00-00 00:00:00

There is no issue with it that I can see. But I can't add a field to the table because of this error.

Thanks

**Comment by dmoagx** [comment]
Not a Sequel Pro issue.
You should search for MySQL strict mode and dates.
