### ISSUE TITLE
Add button to clear the current content filter

### ISSUE THREAD

**Issue by dmoagx** [sequelpro/sequelpro#3302]
The old single-filter UI had an "X" button (bound to Esc key) to clear the current filter and reload the table.

The new filter UI should also provide a way to clear the filter and reload the table with a single button / key press.

**Comment by bartclaeys** [comment]
Still not resolved?

**Comment by macsrwe** [comment]
Reading the threads about this new filter UI behavior, I saw someone point out the "funnel" icon in the bottom row, so I tried using it to turn off a filter I no longer needed. I was surprised to find out that the funnel icon didn't actually _disable_ the filter, it just _hid_ it. I continued to get errors about "No valid SQL expression could be generated" from the empty field in the filter line, except now there wasn't even a filter line apparent. This is actually worse behavior. There really needs to be an intuitive way to _dismiss_ a filter, such as an X or uparrow icon next to the filter.

**Comment by stychos** [comment]
@dmoagx Are you working on this enhancement? I can try to do some enhancements, but I can't promise any timeframes and results yet.

**Comment by macsrwe** [comment]
I thought some work had already been done on it. It used to be that clicking the funnel button would hide the filter but not remove it, so that you would continue to get error messages about an empty filter. Recently, I found the funnel button seemed to be successfully removing the filter as well as hiding it, although I did have to refresh the table because the data contents did not fully reappear until I did.

**Comment by stychos** [comment]
@macsrwe yeah, some work definitely done, but as far as I can understand this particular issue is not about errors, it's about closing behavior (close/minus button on a panels or/and escape key).

**Comment by macsrwe** [comment]
I think we're on the same page. It's at least usable now, without throwing errors in your face that you can't get rid of, but the user interface is nowhere near as convenient as the original one.

**Comment by tebruno99** [comment]
I agree 

> I think we're on the same page. It's at least usable now, without throwing errors in your face that you can't get rid of, but the user interface is nowhere near as convenient as the original one.
> […](#)

I agree completely here.  Gone are the days of just Hitting Content and quickly typing something and then erasing to remove the filter.  The new filter options are really cool. If we could have the old input method but with the new add/remove feature that would be super nice.  For now however I've had to start using other tools.

**Comment by dmoagx** [comment]
This has been fixed:
* There is now a reset button to remove all filters and reload the table
* If you are inside a text field of a filter row you can now press shift+backspace
** This will remove the filter condition and reload the table
** If there is only one filter condition it will behave like a reset
