### ISSUE TITLE
Add option enable/disable filter criteria (without deleting them)

### ISSUE THREAD

**Issue by dmoagx** [sequelpro/sequelpro#3303]
> One thing I have been thinking about it adding checkboxes in front of the filter rows, so it becomes possible to disable/enable criteria. We could add the first row as "disabled" and enable it, once the user changes it or starts typing.

**Comment by catcatcatcatcatcatcatcatcatcat** [comment]
On Mac OS X Mojave, for many builds, including 5438, multiple users in my team are not able to remove the final filter. Clearing it causes an error message to appear whenever reloading or re-sorting by a field.

**Comment by dmoagx** [comment]
Implemented with the two commits shown above
