### ISSUE TITLE
Store filter visibility in prefs

### ISSUE THREAD

**Issue by dmoagx** [sequelpro/sequelpro#3304]
Currently the visibility of the table content filter is not preserved across sessions.

User feedback suggests that we should store the last choice for new sessions for increased productivity.

**Comment by tedens** [comment]
Honestly, I was coming on here to make a new issue but it would be nice if we could set a pref to always show the filter option as that is what is generally doing every time I load a table. However, I do love the ability to multi-filter tables without writing the sql myself.

**Comment by xiangbohua** [comment]
Agree with you. I feel very fast to open a new tab and filter a table in old versions. But in the newest build. I have to open filter tab manually(I didn't know Command + f can open it before). And I didn't understand why the input must be clear after I changed the filter field. I have to type or copy my keywords again maybe considering about the data types. I hope the input can preserve when the data type was same.
This was my opinion.

**Comment by aradapilot** [comment]
+1 to this, solution that makes everyone happy.  I'd like it back to always visible, but saved is better for everyone

**Comment by CodingFishWu** [comment]
@xiangbohua Hi, do you know how to hide filter tab quickly? In previous release version, I can leave filter content blank and it will ignore the filter, but it will alert "invalid filter" now. It's very annoying.

**Comment by stychos** [comment]
@CodingFishWu https://github.com/sequelpro/sequelpro/pull/3422

**Comment by dmoagx** [comment]
SP will now store the last action for the filter button in prefs. So if you have enabled the filter view and open a new connection the filter view will also be enabled by default there.
