### ISSUE TITLE
Add ability to hide content filter by pressing cmd+f

### ISSUE THREAD

**Issue by dmoagx** [sequelpro/sequelpro#3305]
Some users wish to have the option to toggle the visibility of the content filter by pressing cmd+f (currently this will only enable it)

**Comment by dmoagx** [comment]
Personally I'm undecided about this approach.

Apple's search UI (both panel and bar) also can only be enabled by pressing cmd+f.
They can on the other hand by dismissed by pressing Esc, but I'm not sure that is an appropriate key in a scenario with multiple filters…

**Comment by stychos** [comment]
I think that Super+F must put focus into last filter, Esc close a filter with cursor (and transfer cursor to the next filter in list).

**Comment by olibraga** [comment]
Adding a minus button to the first/only filter should solve the problem.

cmd-f closing a search field is unorthodox GUI behaviour hence BAD.

**Comment by catcatcatcatcatcatcatcatcatcat** [comment]
On Mac OS X Mojave, for many builds, including 5438, multiple users in my team are not able to remove the final filter. Clearing it causes an error message to appear whenever reloading or re-sorting by a field. This feature (being able to remove the final filter) would also solve that bug.

**Comment by dmoagx** [comment]
Together with the changes for #3071 I don't think there is something left to do here.
Since cmd+F can only be used to enable search pretty everywhere in OS X I don't feel like deviating from that.
