### ISSUE TITLE
Content filter: Preserve arguments when changing column/ operator

### ISSUE THREAD

**Issue by dmoagx** [sequelpro/sequelpro#3306]
When changing the column or the operator of a filter row in the new filter UI all following argument fields will be reset.

Instead the filter should preserve the user input where possible.

Use case:
A user types in an argument and only then realises that they want to do a "contains" search instead of a "=" search and they change the operator. Currently this action will void the action made in the first step, requiring the user to type in the argument again.

**Comment by billynoah** [comment]
was just about to come and file the exact same issue.  IMO, this should be labelled "Bug". not be "Enhancement" — as it's clearly not the intended behavior and every stable release of this application already preserves arguments as requested here.

**Comment by dmoagx** [comment]
I could go into detail why the "Enhancement" label is correct, but let's be realists: That categorization has (currently) no effect on how likely it will be done.

**Comment by dmoagx** [comment]
This has been implemented
