### ISSUE TITLE
(Discussion) Continue developing by providing pro features with minimal pricing

### ISSUE THREAD

**Issue by muuvmuuv** [sequelpro/sequelpro#3313]
I don't know how many people are really working on this project but I really like SequelPRO, using it for years now to access my databases across the web. IMHO a simple donate button is not enough to maintain this project and provide more features/fixing bugs. You, the maintainers, should think about splitting it Sequel and SequelPro, least would have more features like connect to AWS, save more favourites etc. I would use a minimal pricing, so poor students don't need to empty their purse for it (40€ forever license or 3€/per month something like that).

**Comment by muuvmuuv** [comment]
@xleeuwx I totally agree. I just thought this would help removing bugs and creating features people suggest here in GitHub issues tab. Right now, as you can see, it takes way to long for anything and there is currently no good alternative around, from what I know.

**Comment by dmoagx** [comment]
This has been discussed over and over again in all kinds of issues.
As a spare time project (which Sequel Pro is and has always been) there is no benefit in "minimal pricing".
For a full time job the price we'd have to go for would be too expensive for most people (just for reference: the money from donations we received in the last 10 years would probably still not be enough to pay for the (optimistic) estimate of one man year to implement PGSQL support)
