### ISSUE TITLE
Support for Postgres on Google Cloud Platform?

### ISSUE THREAD

**Issue by pthieu** [sequelpro/sequelpro#3314]
- Sequel Pro Version: 1.1.2 Build 4541
- macOS Version: 10.12.6
- MySQL Version: Not MySQL but PostgreSQL on version 9.6

**Description**
Trying to connect with IPv4 on port 5432 (default PSQL port)

**Steps To Reproduce**
0. Set up GCP Cloud SQL instance CIDR to be `0.0.0.0/0` to allow all public connections
1. Install using `brew`
2. Create new DB Connection
3. Enter in IPv4 address, port (5432), username, password
4. Click `Connect`
5. Get the following error:

![image](https://user-images.githubusercontent.com/2908721/49028479-7ff20a00-f170-11e8-9f6e-4be364b90d1e.png)

**Expected Behaviour**
DB connection does not time out and connection is successful, showing me a list of DBs

**Additional Context**
I'm thinking there may not be support for Postgres as I can connect to the DB fine with Postico.

**Comment by dmoagx** [comment]
Sequel Pro does not support PostgreSQL
