### ISSUE TITLE
Shortcut CMD-S should default to save query

### ISSUE THREAD

**Issue by fulldecent** [sequelpro/sequelpro#3318]
I started downloading other apps because Sequel Pro does not have simple support for saving queries.

Whenever you press CMD-S it saves to some weird format that is NOT an .SQL file.

Much later I found out that the way to save a query is not CMD-S but rather CTRL-CMD-S.

---

CMD-S should be reserved for the much more common use case of saving a query rather than "saving a connection" whatever that means.

**Comment by dmoagx** [comment]
Every tab in Sequel Pro is a "connection document". This is consistent with e.g. every window in Word or TextEdit being a "text document".

That is actually one of the core concepts in Cocoa: Document based applications.

A document file is supposed to contain all information to restore the application to the state it was in when the document was last saved. That is what Sequel Pro's "connection documents" do and this is also why they are bound to cmd+s.

So Sequel Pro's behavior is in line with how apps are supposed to behave under macOS.

**Comment by stychos** [comment]
But ⌘+S in Text Edit and any other Apple application propose to save a file in some format, isn't it?
