### ISSUE TITLE
MySQL8 support - auth login fail

### ISSUE THREAD

**Issue by parisnakitakejser** [sequelpro/sequelpro#3332]
When i login to my MySQL8 i get this error
MySQL said: Authentication plugin 'caching_sha2_password' cannot be loaded: dlopen(/usr/local/mysql/lib/plugin/caching_sha2_password.so, 2): image not found

what i need its posibule to login to MySQL8 with the new secerty support, and not MySQL 5.7, and its will be cool if we can export / import from old system => new system.

**Comment by romainnorberg** [comment]
Duplicates of #3037
