### ISSUE TITLE
ETA on 1.2?

### ISSUE THREAD

**Issue by rnbwspctrm** [sequelpro/sequelpro#3334]
I see no estimated release for 1.2. The crashes are unbearable and I do not want to start using this program with no end to this behavior in site. Please add somewhere obvious when the expected fix for these crashes will be released.

**Comment by Wharenn** [comment]
Latest test build is fixing the issue: https://sequelpro.com/test-builds

**Comment by mikemike396** [comment]
Latest snapshot build is working great for me -> 
https://sequelpro.com/builds/Sequel-Pro-Build-df10e20443.zip

**Comment by dmoagx** [comment]
Duplicate of #3034
