### ISSUE TITLE
Follow Foreign-Keys in Query view

### ISSUE THREAD

**Issue by samputer** [sequelpro/sequelpro#3335]
Please forgive me if this has been posted before, however I did look and was unable to see any duplicates.

I love the feature whereby you can follow foreign-key constraints from within the UI, it's tremendously helpful. It is however disappointing that you can't do this when viewing a result set from SQL that had been run (in the Query view).

Steps to Reproduce
1 - Select a table (that has FKs) on the leftmost navbar
2 - Select the Content view
3 - Notice the arrow in the FK column
4 - Click that arrow to follow the relation to the next table
5  - Go to the Query view
6 - Run a simple `select *` query on the same table
7 - Notice that there is no such arrow in the result set.

It would be great to see the same arrow that would open up the Content view with the target table and filter set for this FK.

Thanks again for a great product.

Sam

**Comment by ruu1989** [comment]
I'd love to see this! 👍
