### ISSUE TITLE
[REQ] Empty Cells to Nulls on CSV Import

### ISSUE THREAD

**Issue by aparduhn** [sequelpro/sequelpro#3336]
Sequel Pro currently treats empty cells as empty strings.  An option could be added to the dialog to allow empty cells to be written with a null.  

I'm assuming the import feature just calls the `LOAD DATA` function in MySQL, so the process could execute something similar to the following code:

`LOAD DATA infile '/tmp/testdata.txt'`
`INTO TABLE moo`
`fields terminated BY ","`
`lines terminated BY "\n"`
`(one, two, three, @vfour, five)`
`SET four = nullif(@vfour,'')`
`;`

Where the field that wants to be treated as a null is first inserted into a variable, then the actual field is set to that variable. Perhaps because this can be done on a field-by-field basis, this can be added to the **CSV Import Field Mapping** section?

**Comment by dmoagx** [comment]
> I'm assuming the import feature just calls the LOAD DATA function in MySQL,

No, it does not.

But the CSV column mapping has always allowed you to include any kind of custom SQL:
![bildschirmfoto 2018-12-20 um 20 47 01 607](https://user-images.githubusercontent.com/5793864/50307386-9736c580-0498-11e9-95d3-bc4b20b6bf83.png)
