### ISSUE TITLE
Sequel Pro closed unexpectedly when I close one connection

### ISSUE THREAD

**Issue by fcdeveloper** [sequelpro/sequelpro#3337]
When I have at least one or more connection open and close one of them Sequel Pro exit unexpectedly, this is very annoying and need a solution ASAP.

iMac (Retina 5K, 27-inch, Late 2015)
macOS Mojave
Version 10.14.1

**Comment by dmoagx** [comment]
Yeah, and I need people to learn basic issue tracker etiquette ASAP

Duplicate of #3116
