### ISSUE TITLE
open db is error

### ISSUE THREAD

**Issue by huzhijia** [sequelpro/sequelpro#3338]
NSInvalidArgumentException

-[_NSInlineData isEqualToString:]: unrecognized selector sent to instance 0x6080002336e0

(
	0   CoreFoundation                      0x00007fff456482db __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff6c7e5c76 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff456e0db4 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff455be820 ___forwarding___ + 1456
	4   CoreFoundation                      0x00007fff455be1e8 _CF_forwarding_prep_0 + 120
	5   Sequel Pro                          0x00000001000587cd -[SPTablesList updateTables:] + 1338
	6   Sequel Pro                          0x00000001000469c5 -[SPDatabaseDocument _selectDatabaseAndItem:] + 454
	7   Foundation                          0x00007fff476cd1f8 __NSThread__start__ + 1197
	8   libsystem_pthread.dylib             0x00007fff6d717661 _pthread_body + 340
	9   libsystem_pthread.dylib             0x00007fff6d71750d _pthread_body + 0
	10  libsystem_pthread.dylib             0x00007fff6d716bf9 thread_start + 13
)
mysql -version
mysql  Ver 8.0.12 for osx10.13 on x86_64 (Homebrew)

**Comment by dmoagx** [comment]
creating duplicate ticket is error
