### ISSUE TITLE
Unable to update from 1.1 to 1.1.2 in Mojave

### ISSUE THREAD

**Issue by ortsed** [sequelpro/sequelpro#3339]
- Sequel Pro Version: 1.1
- macOS Version: 10.14.1
- MySQL Version: N/A

**Description**
SequelPro asks about updating to newest version on startup (or when requested from menu). After hitting ok to update, update is downloaded, but when it's completed downloading it opens the error:

"Update Error! An error occurred while extracting the archive. Please try again later."

**Steps To Reproduce**
1. Choose "Check for Updates" from SequelPro menu in OSX.
2. Choose Install Update to update from 1.1 to 1.1.2

**Expected Behaviour**
Should install the update and either continue operating or ask to restart the application.

**Additional Context**
Is there maybe a permissions issue? Unable to overwrite a protected directory or unable to update while the application is running?

**Comment by dmoagx** [comment]
1.1 has been outdated for nearly 3 years.
And even 1.1.2 is no longer recommended when working with 10.14.1

We just don't have enough people to look into issues with versions that are no longer supported, so I'll close this.

Just manually download a new version from https://sequelpro.com/download or https://sequelpro.com/test-builds
