### ISSUE TITLE
Refreshing table does commit changes

### ISSUE THREAD

**Issue by jishnu2292** [sequelpro/sequelpro#3350]
Refresh Databases as well as table doesn't work.

- Sequel Pro Version:1.1.2
- macOS Version:10.12
- MySQL Version:

**Description**
I have updated database fields through my php code. But on refreshing the database as well as refreshing the table does not reflect it on the database. 
So i took the table structure and added a field to the table. After that, on selecting the table content, the table refreshes and the old updated values have reflected. Im able to view the changes only on doing the above process.

**Comment by dmoagx** [comment]
Check if the data is shown when you manually run the query in the Query Editor.
If not then your server has most likely disabled autocommit and set some overzealous transaction isolation level…

**Comment by dmoagx** [comment]
No feedback from reporter in > 1 month. Closing.
