### ISSUE TITLE
CSV import doesn't handle quoted multiline strings

### ISSUE THREAD

**Issue by bubach** [sequelpro/sequelpro#3351]
- Sequel Pro Version: All

**Description**
When importing CSV it's kind of implied that the format should follow some simple rules - defined in this text for example
https://tools.ietf.org/html/rfc4180#page-2

I know it says there is no formal specification - but the most common rules is
```
column1, column2, "column3"\n(\r)
````
with last entrys line ending being optional and anything enclosed in quotes be treated as a string and may contain newlines. Its not very hard. Yet I'm presented with a whole bunch of options, I mena if the seperator isn't a bleeping comma - then it can hardly be a "comma separated value" - can it?

And quoted string spanning more then one line is apperantly a show-stopper?  WTAF.

```
 6.  Fields containing line breaks (CRLF), double quotes, and commas
       should be enclosed in double-quotes.  For example:

       "aaa","b CRLF
       bb","ccc" CRLF
       zzz,yyy,xxx
```

**Steps To Reproduce**
1. Try importing any "normal" CSV file qith some strings quoted
2. Be mad as hell

**Expected Behaviour**
It should be able to handle be BASIC CSV type before even trying with all those options that doesn't help at all.

**Additional Context**
I'm mad. As hell.

**Comment by mikesale** [comment]
I'm in the same boat. This is not rare to have multiline quoted fields in CSV.
