### ISSUE TITLE
Sequel Pro crashes everytime i close a tab

### ISSUE THREAD

**Issue by tsndr** [sequelpro/sequelpro#3359]
It's been almost 4 months since the release of macOS Mojave and still there is no update for Sequel Pro. I'm using this software on a daily basis, i also donated a while ago because i love using it. But those crashes are super annoying, please fix it.

**Comment by dmoagx** [comment]
Duplicate of #3116 
Also #3034

**Comment by tsndr** [comment]
Then fix it already.
