### ISSUE TITLE
Sequelpro does not want to install

### ISSUE THREAD

**Issue by SirKaya** [sequelpro/sequelpro#3363]
When i click on dmg a black window appear with Sequel's logo and I can't put in my application. 

I'm on Mojave

**Comment by RobertCristian** [comment]
This is weird, you can try to copy and paste it by keyboard to your application or maybe just try to drag/copy somewhere else first then to application..hope it works!

**Comment by Kaspik** [comment]
Are you installing nightly build or latest stable build?

**Comment by dmoagx** [comment]
No feedback from reporter, closing.
