### ISSUE TITLE
Crash between tabs workflow on macOS Mojave 10.14.2 

### ISSUE THREAD

**Issue by StanBarrows** [sequelpro/sequelpro#3364]
According to #3116 
```
I have locked this issue.
This has been fixed long before this issue was even opened and 99% of the 
discussion going on here is violating the 
very basics of issue tracker etiquette!
```
Not sure what and where you have tested it but since I've upgraded to macOS Mojave the app is still not usable for a production environment.

- Sequel Pro Version: 1.1.2
- macOS Version: 10.14.2
- MySQL Version: 5.7.*

**Description**
The app crashes on a lot of daily interactions within my workflow. Hard to tell every way the app crashes. The most popular occurs between switching tabs.

**Steps To Reproduce**
1. Open tab / switch tabs / close tabs

**Comment by aromka** [comment]
Seems to work fine again after latest Mojave update (10.14.3)
