### ISSUE TITLE
Multi-Cursor or Multiple Cursors and Select Next, Support in Query Editor

### ISSUE THREAD

**Issue by JamesHamiltonDotCodes** [sequelpro/sequelpro#3366]
# Multi-Cursor and Select Next Support
One feature I've wished and hoped for in any SQL browser/editor is the ability to edit SQL code in a similar way that I can with Atom.io and Sublime text.

This would be a very powerful feature if added to Sequel Pro and would make a lot of DBAs and Developers so happy and thankful for increased efficiency and productivity:
![Animated Image, Demo Select Next and Multi-Cursors in an SQL Query](https://i.imgur.com/QxJ1fUS.gif)
Link to Demo Animated Gif: https://imgur.com/a/FBvqwt1

Multi-Cursors sometimes called Multiple Cursors is a very useful feature that I use daily in Atom.io editor as well as in Sublime Text 3. I also use another feature in atom editor called Select Next which is another way I am able to start to select and use multiple cursors in Atom. Usage example:

Say I wanted to correct all instances of the words orderTable in a sql query and change to orderTbl. If it worked like Atom or Sublime, I could highlight the first occurrence of the word orderTable, pressed Cmd+D to highlight the next occurrence, continue to do so, then use the left arrow key to change my multiple selections into multiple cursors.

This is a fabulous example of multi-cursors in action in atom:
![Animated Image, Showing Multiple Cursors](https://i.github-camo.com/c6b86d97d1f83b748a51af958dd84ed8804e1808/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f662e636c2e6c792f6974656d732f32583339334d31753147304b305a3036314f30302f6d756c74692d637572736f722e676966)

This is an example of using Select Next feature to create multiple text selections:
![Animated Image, Showing Select Next](https://i.stack.imgur.com/zYMH4.gif)

Related Links:
Multi-Cursor Package from Atom.io: https://atom.io/packages/multi-cursor
Multi-Cursor Plus Package Atom.io https://atom.io/packages/multi-cursor-plus
You-Tube Demo Multi-Cursors in Sublime: https://www.youtube.com/watch?v=5UyWX5nhgck
Multiple-Selection/Multi-Cursors Keyboard Shortcut Documentation in Sublime: https://www.sublimetext.com/docs/3/multiple_selection_with_the_keyboard.html

**Comment by dmoagx** [comment]
Sequel Pro's SQL editor is pretty messy and by a wide margin outside of the core competencies of the project.

IMHO we should just rely on a source code editor framework like most other projects, however there seems to be little in that direction for OS X.

I think it may be worth looking into integrating the editor engine of SubEthaEdit, since it recently has become open source and in the past has been used as the foundation of the editor in Coda...
