### ISSUE TITLE
Nightly builds broken again

### ISSUE THREAD

**Issue by robertoschwald** [sequelpro/sequelpro#3369]
Nightly builds job does not finish again since some days.

**Comment by jbfriedrich** [comment]
@dmoagx It seems you are one of the most active contributors. I do not know anything about programming on macOS, I like the app very much though. Would it be helpful to crowdfund or donate an instance on a cloud service like https://xcloud.me/ or https://www.macincloud.com/? Or is the problem not related to the infrastructure, but something else entirely? Do you have any insights? Is there anything I can do to help, if I cannot contribute to the code?

**Comment by dmoagx** [comment]
Seems to be back now.
Not sure what the issue was, @rowanbeentje can probably answer that.
