### ISSUE TITLE
Instructions to obtain latest stable version

### ISSUE THREAD

**Issue by pjebs** [sequelpro/sequelpro#3372]
The website downloads version 1.1.2 which is 3 years old.

Is it possible to put a note on README that suggests how to obtain the latest stable version?

**Comment by pjebs** [comment]
Why is this the case?

**Comment by gregblass** [comment]
I have no affiliation with this company, but if people are looking for a stable alternative, this program was well worth the license fee: https://tableplus.io/

It also has support for PostgreSQL in the same program, which was amazing for me. Exports and imports MySQL JSON fields no problem too! And has a dark mode.

**Comment by dmoagx** [comment]
Duplicate of #3034
