### ISSUE TITLE
Loading forever when selecting database.

### ISSUE THREAD

**Issue by pgooch** [sequelpro/sequelpro#3374]
- Sequel Pro Version: 1.1.2
- macOS Version: 10.14.2
- MySQL Version: 8.0.14

**Description**
When selecting a database from the dropdown it seems to hang forever (I've literally waited minutes).

**Steps To Reproduce**
1. Connect to database (I'm doing it with a standard connection to 127.0.0.1)
2. Once you have logged in select a table from the menu.

**Expected Behaviour**
To load the selected database.

**Additional Context**
If I tell it to connect to the database I want to work with directly (using the Database option on the login screen) it will instantly throw up an error (which I have submitted) and while the dropdown says your in the database no tables show up (and I know there are tables in this database because it's a working WordPress installation). Crash log attached (and report with Feedback). Looking at previous issues it points me to thinking it's related to @2688, but given the age of that ticket I don't think it is. If it is then I'm with joseluisq, I'd be happy to pay for a working commercial version.

[Sequel Pro_2019-02-01-190520_Phillips-Mac-mini.crash.txt](https://github.com/sequelpro/sequelpro/files/2823994/Sequel.Pro_2019-02-01-190520_Phillips-Mac-mini.crash.txt)

**Comment by Sujin1135** [comment]
I just got same experience. how can I solve it?

**Comment by Hubertnator** [comment]
Nightly builds is the only solution....

**Comment by pahrulirfan** [comment]
download and install nightly builds

https://sequelpro.com/test-builds
