### ISSUE TITLE
Mac OS issues on while updating permissions through GUI

### ISSUE THREAD

**Issue by BalajiSubramanianGit** [sequelpro/sequelpro#3378]
Sequel Pro MAC OS issues on while updating permissions through GUI.

**Comment by BalajiSubramanianGit** [comment]
I’m updating permissions on Insert / update but it’s not refelecting properly

**Comment by dmoagx** [comment]
https://github.com/sequelpro/sequelpro/wiki/How-do-I-write-a-proper-issue-report%3F

**Comment by dmoagx** [comment]
No feedback from reporter, closing.
