### ISSUE TITLE
Just to add I have same issue, close any tab and it instantly crashes.  v1.1.2 Build 4541 macOS 10.14.3  Thanks

### ISSUE THREAD

**Issue by is4hil** [sequelpro/sequelpro#3379]
- Sequel Pro Version:
- macOS Version:
- MySQL Version:

**Description**

**Steps To Reproduce**
1.
2.

**Expected Behaviour**

**Additional Context**

**Comment by dmoagx** [comment]
Wow. This is probably a new low…
