### ISSUE TITLE
Can't connect to remote MySQL db via SSH tunnel

### ISSUE THREAD

**Issue by nmjk** [sequelpro/sequelpro#3381]
[Sequel Pro Build 5427 (d78907bd), OS X 10.14.3 (Mojave)]

**I'm trying to connect to a remote MySQL database via SSH tunnel using ~SSL~ public/private key authentication.**
I have tried to be as thorough as possible in providing details about the problem, the config details, etc., all provided below.

### THE ERROR

> #### **SSH port forwarding failed**
> 
> Unable to connect to host HOSTNAME because the port connection via SSH was refused.
> 
> Please ensure that your MySQL host is set up to allow TCP/IP connections (no --skip-networking) and is configured to allow connections from the host you are tunnelling via.
> 
> You may also want to check the port is correct and that you have the necessary privileges.
> 
> Checking the error detail will show the SSH debug log which may provide more details.
> 
> MySQL said: Lost connection to MySQL server at 'reading initial communication packet', system error: 0

### "SHOW DETAIL"

Here's what I get when I click "Show Detail": [debug_details.txt](https://github.com/sequelpro/sequelpro/files/2842489/debug_details.txt)
(placeholders inserted for hostname/IP, username, etc)

### WHAT I ALREADY KNOW

- My **SSL authentication works** because I can use it to manually create an SSH tunnel from the command line
- The **remote server configuration (SSH, MySQL) is correct** because I can connect using [mysql-shell](https://dev.mysql.com/downloads/shell/) (command line) via the aforementioned SSH tunnel
- The exact same Sequel Pro configuration works on my old Mac, running El Capitan (OS 10.11.6)

### DETAILS

Sequel Pro configuration fields: 
<img width="445" alt="sequel_pro_config" src="https://user-images.githubusercontent.com/136594/52440052-ff397d80-2ad1-11e9-8b70-a4709feb69ae.png">

Additional details:
- There is no passphrase required for the ~SSL~ SSH key
- The settings in ~/.ssh/config that are applied are: ServerAliveInterval (250), ServerAliveCountMax (2), HostName, User, Port, IdentityFile
- I have tried setting the MySQL Host (in the Sequel Pro config window) to the hostname (yielding the info above), the public IP address (same problem), and 127.0.0.1 ("MySQL said: SSL connection error: Server doesn't support SSL")
- This is my first attempt using a test build. I still successfully use the last official release, Sequel Pro 1.1.2, on the old Mac, but I have given up on 1.1.2 on Mojave due to operating system changes. (I was hoping moving to Sequel Pro test builds would fix everything... alas!)

**Comment by stychos** [comment]
SSH is not SSL. If you're configured IdentityFile property in your ~/.ssh/config, then you don't need to point that keyfile in the SSL section. This is my connection profile for remote host I connecting with the keyfile without a password:

![screen shot 2019-02-07 at 10 45 08 pm](https://user-images.githubusercontent.com/1531639/52441806-5703d300-2b2a-11e9-837b-44b8ddf92088.png)

**Comment by dmoagx** [comment]
You are mixing SSH and SSL, which are completely separate things.
Setting an SSH key in the SSL key file options will never work.

Also the SSH log is pretty clear in what is wrong:
```
debug1: Connecting to HOSTNAME [HOST_IP] port 22.
…
debug1: Connection to port 49913 forwarding to HOST_IP port 3306 requested.
debug1: channel 2: new [direct-tcpip]
channel 2: open failed: connect failed: Connection refused
```

You are trying to open the MySQL connection to the public IP of the server, even though you are going through an SSH tunnel.
That is wrong in 99.9% of cases. The MySQL Host setting in Sequel Pro should be 127.0.0.1 instead.

**Comment by stychos** [comment]
> error I was consistently receiving
This error is from the MySQL side. So if you're getting it, then again it's not related in any type to the SSH/SSL. Check user permissions quadruple times. If you are using MySQL 8 then there's some headache with the socket-only connections and with the password restrictions.

**Comment by nmjk** [comment]
> This error is from the MySQL side. So if you're getting it, then again it's not related in any type to the SSH/SSL.

I don't understand how the problem could be with the MySQL side of things. I can connect fine from Sequel Pro on the old computer (using the same configuration) *and* from this computer when I manually create a tunnel and connect using mysql-shell. Am I missing something?

Here are the commands I'm using to successfully connect via  command-line:
$ /usr/bin/ssh USER@HOSTNAME -L 3306:127.0.0.1:3306 -N &
$ /usr/local/bin/mysqlsh --sql --host=127.0.0.1 --port=3306 -u USER -p
*(password is saved by keychain, and I have checked it 20+ times to make sure it's entered correctly in the Sequel Pro config screen)*

The only difference between the two is the version of operating system. And according to Apple, that puts the onus on the vendor to update how the application code interfaces with the operating system and its new and more stringent policies. However, I gather that at least some people are successfully using Sequel Pro from Mojave, so that still leaves me stranded...

**Comment by dmoagx** [comment]
Perhaps there is something in your `~/.ssh/config` file or some other SSH config file that is not identical to your old Mac.

Also if you had set your MySQL Host to 127.0.0.1 the error message would say

> Unable to connect to host 127.0.0.1 because access was denied.

and not

> Unable to connect to host missionsfestvancouver.ca because access was denied.

**Comment by nmjk** [comment]
(Ahhhhh dang it, I thought I had caught all the specifics. Oops. I've edited mine... any chance you can edit yours? I know it's still findable, but still..)

But as I said, I get the same error **regardless** of what I enter into the Hostname field.

I have been trying all sorts of things with my current ~/.ssh/config, granted, but at various points in all my testing I have made an exact copy of the one on the old computer to the new computer. So the problem can't be there.

**Comment by dmoagx** [comment]
Do you have a local MySQL server running on your Mac?

Check with `ps aux | grep -i mysql`

**Comment by dmoagx** [comment]
In Sequel Pro go into the password field, press cmd+A and backspace to delete and retype your password. You *must* use cmd+A, don't try to select it with your mouse etc.

**Comment by nmjk** [comment]
@dmoagx Well shoot. That seems to have fixed it! Good grief.
In all the times I previously entered it (whether re-typing or pasting), I must either have been missing a non-displayed character by using the mouse to select, or when I got the password correct it must have been one of the other problems that previous responses have corrected (SSL checkbox, public IP, etc) so I didn't notice the difference.

Thanks to both of you, @dmoagx and @stychos, for uncovering all the problems. It seems that the recent builds of Sequel pro are—appropriately!—more exacting when it comes to host configurations, and that the password field will accept hidden characters.

**Comment by chrisjimallen** [comment]
> In Sequel Pro go into the password field, press cmd+A and backspace to delete and retype your password. You _must_ use cmd+A, don't try to select it with your mouse etc.

This is the answer ( for me at least )

**Comment by hardvintage** [comment]
> In Sequel Pro go into the password field, press cmd+A and backspace to delete and retype your password. You _must_ use cmd+A, don't try to select it with your mouse etc.

This fixed my issue perfectly! Thanks a lot.
