### ISSUE TITLE
No Floating Point Data Types Offered for CSV Import to New Table

### ISSUE THREAD

**Issue by leftcoastryan** [sequelpro/sequelpro#3382]
- Sequel Pro Version: 1.1.12
- macOS Version: 10.14.2
- MySQL Version: 5.7.25

**Description**
I am unable to import a CSV with floating point values because no floating point data types are offered as options for those fields. Text and integer data types are offered, but no floating point types.

**Steps To Reproduce**
1. Click the "Export Data" link on [this baseball website](https://www.fangraphs.com/leaders.aspx?pos=all&stats=bat&lg=all&qual=y&type=1&season=2018&month=0&season1=2018&ind=0&team=0&rost=0&age=0&filter=&players=0).
2. Import the downloaded CSV in Sequel Pro.
3. Select option for creating a new table.
4. The pull-down menus offering data types do not include floating point types.

**Expected Behaviour**
I expect FLOAT/DOUBLE/DECIMAL types to be offered for handling fields in the CSV file.

**Additional Context**
[The problem may have been around for a year or more](https://stackoverflow.com/questions/48071981/setting-decimal-datatype-in-sequel-pro).

![screen shot 2019-02-10 at 12 56 22 am](https://user-images.githubusercontent.com/471862/52531878-36c24880-2cd1-11e9-9976-300801a99cc8.png)
<img width="636" alt="screen shot 2019-02-10 at 12 56 02 am" src="https://user-images.githubusercontent.com/471862/52531879-36c24880-2cd1-11e9-9edf-d70068e83598.png">

**Comment by hoenth** [comment]
I know this is rather old, but you can import decimal information. Though it doesn't include a decimal field in the list of options, you can type DECIMAL(10,2) (or any other type, for that matter) in the field.
