### ISSUE TITLE
Possibility to add filter criteria from the context menu of a table field

### ISSUE THREAD

**Issue by dmoagx** [sequelpro/sequelpro#3383]
We should provide a way to add the value of a field as a filter criteria via context menu to provide an easy drill down option.

E.g. this is how the context menu looks in Wireshark when clicking on a field:
![bildschirmfoto 2019-02-10 um 23 41 32 632](https://user-images.githubusercontent.com/5793864/52540778-b281cb00-2d8d-11e9-9341-226c281a2ff7.png)

**Comment by lostminds** [comment]
I was just planning to add a similar suggestion when I found this. And I think a much simpler first version could go a long way as well, with just a context menu option on table cells to "Add filter for [column name] = '[value]'". That way you can very quickly add simple filters, and it's easy to then modify that in the filter UI if you want something other than the simple equals criteria.

![add_filter_mockup](https://user-images.githubusercontent.com/17763524/68526428-241a8580-02dc-11ea-9d1f-f810492b2203.jpg)
