### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by k0rsair** [sequelpro/sequelpro#3390]
App crashed when use hotkey command+w.

**Comment by stychos** [comment]
https://github.com/sequelpro/sequelpro/wiki/How-do-I-write-a-proper-issue-report%3F

**Comment by user004** [comment]
@stychos, I'm not OP, but I have experienced this issue, and have added your required info.

macOS version: 10.14.3 (18D109)
Sequel Pro version: 1.1.2 Build 4541 (602e11a)
MySQL DB versions: 5.7.23, 5.1.73-0ubuntu0.10.04.1, and 5.5.46
Crash Log: [crash.log](https://github.com/sequelpro/sequelpro/files/2881788/crash.log)
Step-by-step:

1. Open Sequel Pro
2. Connect to DB
3. Use shortcut or use UI "X" on tab to close connection
4. Note that app has quit

How often: 95% of the time I close a connection
One or multiple servers: I can replicate it on multiple servers
Connection types: I tested a local MAMP server (TCP/IP), and two remote servers (SSH+TCP/IP)

I did not update Sequel Pro recently, but our office did allow the newest macOS update recently, that's about when I noticed.

**Comment by stychos** [comment]
@user004, @k0rsair it seems that you're using old builds, download latest version from https://sequelpro.com/test-builds or I can propose my unofficial [build](https://github.com/stychos/sequelpro/releases) which also have merged fixes for the Dark Mode.

**Comment by dmoagx** [comment]
Duplicate of #3116
