### ISSUE TITLE
View Import Command Used by Sequel Pro UI

### ISSUE THREAD

**Issue by kirill-demtchouk** [sequelpro/sequelpro#3391]
Is it possible to view exactly what command Sequel Pro is submitting when I ask it to import data into a table via the File -> Import... menu item?

The console accessible via View->Show Console does not seem to record the command used to load data. Thanks for your help!

**Comment by stychos** [comment]
Are you tried that?
![screenshot 2019-02-19 at 21 46 09](https://user-images.githubusercontent.com/1531639/53042964-0e380c80-3490-11e9-9e77-9078957ea807.png)

**Comment by kirill-demtchouk** [comment]
That solves it! Thank you!
