### ISSUE TITLE
Duplicate Database support for no locking, or just row locking

### ISSUE THREAD

**Issue by bytor99999** [sequelpro/sequelpro#3393]
Sorry for asking a stupid question, but when you run database/duplicate database option, I am assuming as it is copying into the new database with data, that it is locking tables while it copies table by table? Or an I incorrect in that assumption.

If it does lock, I recommend an option on the duplicate database popup to allow options like not locking tables, or I think I saw with MySQLDump that you can set locking row by row.

Reason I request and ask is I think I did a stupid thing in doing a backup of my prod data using duplicate database and it locked up our application.

Thanks

Mark

p.s I love Sequel Pro, you guys did an awesome job. I am a former Oracle DBA that used Toad for so many years in the early 2000s, that I love Sequel Pro as much as I loved Toad back then,

**Comment by bytor99999** [comment]
It is a shame that it appears no one is reading any open issues posted here on GitHub for this project.

**Comment by stychos** [comment]
@bytor99999 check it out the new fork https://github.com/Sequel-Ace/Sequel-Ace
