### ISSUE TITLE
Save this layout proportions on the application exit.

### ISSUE THREAD

**Issue by yadgen** [sequelpro/sequelpro#3395]
- Sequel Pro Version: Build 5438 (664a46cd)
- macOS Version: macOS Mojave 10.14.3
- MySQL Version: mysql  Ver 15.1 Distrib 10.3.13-MariaDB, for osx10.14 (x86_64) using readline 5.1

**Description**
Save this layout proportions on the application exit.
I think this is a very good suggestion.

<img width="1226" alt="2019-02-27 12 15 27" src="https://user-images.githubusercontent.com/1206012/53428147-3b9f3000-3a25-11e9-8afc-53c3e91d250a.png">

**Comment by stychos** [comment]
Just change your editor color scheme settings in the application preferences: https://github.com/sequelpro/sequelpro/issues/2485#issuecomment-425076354

**Comment by yadgen** [comment]
> Just change your editor color scheme settings in the application preferences: [#2485 (comment)](https://github.com/sequelpro/sequelpro/issues/2485#issuecomment-425076354)

Set and restart, It's not working.
<img width="1227" alt="2019-02-27 12 36 17" src="https://user-images.githubusercontent.com/1206012/53429505-c08b4900-3a27-11e9-8d19-12372fce65e4.png">

**Comment by stychos** [comment]
Now try to set your "Text" colour to some White, and "Background" to some Dark.

**Comment by yadgen** [comment]
> Now try to set your "Text" colour to some White, and "Background" to some Dark. Then expand "Create Syntax" using appropriate handle on the divider.

I don't understand, I have not found "Create Syntax".
Can you export theme to share with me? Thanks.

**Comment by stychos** [comment]
Sorry, language barrier here. I meant that if you wish to expand the whole "Create Syntax" block then you need to expand it manually by the appropriate handle:
![screenshot 2019-02-26 at 18 51 38](https://user-images.githubusercontent.com/1531639/53430734-c79a6300-39f7-11e9-8529-36ad0c7a6235.png)
Change of the theme colours will help you to see that handle.

**Comment by yadgen** [comment]
> Sorry, language barrier here. I meant that if you wish to expand the whole "Create Syntax" block then you need to expand it manually by the appropriate handle:
> ![screenshot 2019-02-26 at 18 51 38](https://user-images.githubusercontent.com/1531639/53430734-c79a6300-39f7-11e9-8529-36ad0c7a6235.png)
> Change of the theme colours will help you to see that handle.

Thanks for sharing.
I know there is a way to drag the settings, but there will be problems next time I open it.

**Comment by stychos** [comment]
I don't think that's an error. Rather it's an enhancement request to save this layout proportions on the application exit.

**Comment by yadgen** [comment]
> I don't think that's an error. Rather it's an enhancement request to save this layout proportions on the application exit.

Ok, I know, thank you very much for your help.

**Comment by stychos** [comment]
I think you can change the issue name and content to an enhancement request and reopen it. It may be helpful for maintainers to plan the future enhancements knowing this UI nuance, it has some weight to think about it.

**Comment by yadgen** [comment]
> I think you can change the issue name and content to an enhancement request and reopen it. It may be helpful for maintainers to plan the future enhancements knowing this UI nuance, it has some weight to think about it (at least from my own point of view).

I can only close in the bug, re-open an issue in the feature.

**Comment by stychos** [comment]
Stop spawning issues 😆 This one was enough, it has some description, images to look at, question history to read for. One change I would like to see is the description is the "Sequel Pro doesn't remember the height / proportions of the **Create syntax** layout block in the **Table Info** tab, please enhance application to save this layout or to allow user to configure it in the options" instead of "Save this layout proportions on the application exit".

**Comment by yadgen** [comment]
> Stop spawning issues 😆 This one was enough, it has some description, images to look at, question history to read for. One change I would like to see is the description like _"Sequel Pro doesn't remember the height / proportions of the **Create syntax** layout block in the **Table Info** tab, please enhance application to save this layout or to allow user to configure it in the options"_ instead of _"Save this layout proportions on the application exit."_
> You may formulate that even better.

Sorry, my English is not very good, I can only use your words to express, I hope you don't mind.
