### ISSUE TITLE
missing checkboxes on csv export

### ISSUE THREAD

**Issue by jasonbronson** [sequelpro/sequelpro#3399]
- Sequel Pro Version: 1.1.2
- macOS Version: 10.14.3
- MySQL Version: 5.5.5-10.3.13-MariaDB-1:10.3.13

**Description**
When exporting tables to CSV I noticed the checkboxes were missing to check which tables to export (see screenshot)
Only way to export was to hit the mass checkbox button and then export button was able to be enabled.
![ae325eb3cb9446289dee4ccf108aeb72](https://user-images.githubusercontent.com/5793864/53682922-177c7100-3cfb-11e9-9f06-960c258b797c.png)

**Steps To Reproduce**
1. open sql pro
2. export to csv
3. see missing checkboxes in UI

**Expected Behaviour**
able to see checkboxes

**Comment by dmoagx** [comment]
Issues filed against 1.1.2 are no longer being looked into.
Please try a nightly build from https://sequelpro.com/test-builds

**Comment by jasonbronson** [comment]
Thanks I recently switched to another database tool tableplus for now. Lots of stability issues with sql pro lately.
