### ISSUE TITLE
Crash on MacOS Mojave when closing tab

### ISSUE THREAD

**Issue by andykarczewski** [sequelpro/sequelpro#3401]
- Sequel Pro Version: 1.12
- macOS Version: Mojave 10.14.3
- MySQL Version: 

Crashes when closing a second tab

Saw the 19th Jul 2018 post but surely can't be related - look at the date; must have been a patch released since then?

**Comment by dmoagx** [comment]
Duplicate of #3116

**Comment by andykarczewski** [comment]
any idea on an ETA for the fix on #3116? 

It's been 8 months since it was officially confirmed as a bug
