### ISSUE TITLE
unity 2017.4.15 crashing on export package

### ISSUE THREAD

**Issue by XfactorGameStudio** [sequelpro/sequelpro#3403]
I have two unity versions(2017.4 and 2018.3.6) on mac book pro late 2013. both of unity crashes when i try to export package from any of the version. A window appears which shows a long report copied below. how i can get rid from this

Process: Unity [591] Path: /Applications/Unity 2017.4/Unity 2017.4.app/Contents/MacOS/Unity Identifier: com.unity3d.UnityEditor5.x Version: Unity version 2017.4.15f1 (2017.4.15f1) Code Type: X86-64 (Native) Parent Process: ??? [1] Responsible: Unity [591] User ID: 501

Date/Time: 2019-03-04 08:56:21.246 +0500 OS Version: Mac OS X 10.14.3 (18D109) Report Version: 12 Anonymous UUID: CCFE4D87-8DFF-C67A-810F-F0C09D34F3EB

Time Awake Since Boot: 620 seconds

System Integrity Protection: enabled

Crashed Thread: 82 Dispatch queue: com.apple.root.user-interactive-qos.overcommit

Exception Type: EXC_CRASH (SIGABRT) Exception Codes: 0x0000000000000000, 0x0000000000000000 Exception Note: EXC_CORPSE_NOTIFY

Application Specific Information: *** Terminating app due to uncaught exception 'NSGenericException', reason: 'NSRunAlertPanel may only be invoked from the main thread. Behavior on other threads is undefined.' abort() called terminating with uncaught exception of type NSException

**Comment by dmoagx** [comment]
![wat-gigantic-duck](https://user-images.githubusercontent.com/5793864/53725462-5847c780-3e6c-11e9-9d28-cf5899d4477a.jpg)

And your issues with a game development tool called "Unity" are exactly how related to a MySQL database client called "Sequel Pro"?
