### ISSUE TITLE
Unable to import csv file

### ISSUE THREAD

**Issue by seefan** [sequelpro/sequelpro#3404]
- Sequel Pro Version:build 5438
- macOS Version:10.14.3
- MySQL Version:5.7.22

**Description**
Cannot import csv files, but with a lower version of sequel pro you can import

**Steps To Reproduce**
1.click file->import
2.select csv

**Expected Behaviour**
show this message
----
The CSV was read as containing more than 512 columns, more than the maximum columns permitted for speed reasons by Sequel Pro.

This usually happens due to errors reading the CSV; please double-check the CSV to be imported and the line endings and escape characters at the bottom of the CSV selection dialog.
**Additional Context**

amount.csv

customer,business_time,amount_money,approve_money,total_money,cable_money,reject_money,review_money,advertiser_id,network_id,ym
a1,2017/1/31,77776.62,77776.62,77776.62,0.00,0.00,77776.62,0,107,201701
b1,2017/1/31,121842.00,121842.00,121770.20,71.80,0.00,121842.00,0,114,201701

**Comment by dmoagx** [comment]
Please provide a test dataset that causes the issue.
You can send it in private to sequelpro@northofthree.com

**Comment by seefan** [comment]
File sent, which is exported by excel.
the build 4541 is ok

**Comment by dmoagx** [comment]
Thanks, I received the file.
Importing it works fine, but you need to have "Lines terminated by:" set to "\r" for Sequel Pro to be able to read the file.

**Comment by seefan** [comment]
It's ok ,thank you
