### ISSUE TITLE
Key links randomly fail

### ISSUE THREAD

**Issue by macsrwe** [sequelpro/sequelpro#3407]
I'm displaying a table of records where one column is constrained to be a key value from another table. 

In this case, Sequel Pro has always displayed a handy circled arrow to indicate the presence of this relationship. Clicking that arrow has always switched to a view of the other table with the matching record highlighted. 

Since the UI changes of a couple months back, it's now a crapshoot as to whether or not this feature will work. Sometimes it works fine, as it used to. Other times, it switches to a view of the other table with nothing highlighted, a screen full of records, and a hearty "Good Luck, Charlie."

**Comment by dmoagx** [comment]
duplicate of #2792
