### ISSUE TITLE
window resize error when drags between 2 mointors

### ISSUE THREAD

**Issue by lechie** [sequelpro/sequelpro#3409]
When user works with 2 mointors, one is macbook with a 13" or 15" screen monitor, and the other is a big monitor such as 21" or 23" whatever.

1. Open sequelpro app and maxmize the window in the big monitor;
2. Drag the Sequelpro app to the small monitor;

Sequelpro will lost some display area. 
Even drag it back to the big moitor, the lost display area will not be fixed. 
The only solution is restart Sequelpro. 

Thank you.

**Comment by joshluongo** [comment]
+1 this. I'm not sure if this has something to do with different screen densities?

**Comment by dmoagx** [comment]
duplicate of #3287
