### ISSUE TITLE
Autocomplete feature not listed in menu

### ISSUE THREAD

**Issue by kirankotari** [sequelpro/sequelpro#3418]
- Sequel Pro Version: 1.1.2
- macOS Version: 10.14.3
- MySQL Version:

**Description**
I came to know autocomplete feature will work on esc key but it's not in menu, due to the option not in menu I couldn't able to change the short key for autocomplete.

**Comment by kirankotari** [comment]
Oh, I raised a bug. I even forgotten about it :)

**Comment by Kaspik** [comment]
Please see https://github.com/sequelpro/sequelpro/issues/3705
