### ISSUE TITLE
When importing a dump into a production database, ask "are you sure?" first

### ISSUE THREAD

**Issue by aacook** [sequelpro/sequelpro#3425]
Sometimes I accidentally import a dump into a production database by mistake, when I meant to import into my development environment. This is especially true in the past couple months, after I memorized the cmd+shift+i shortcut. 😅

It would be nice to have a simple flag in the settings for each connection, tagging it as a production database. 

That way when I go to import a dump into production by mistake, Sequel Pro can ask, "Are you sure?" 😀

**Comment by dmoagx** [comment]
Personally I don't think that would be useful.
Experience shows that people will simply develop muscle memory and confirm the message without reading.

I think the only thing we could do is use the connection favorite color (and maybe favorite name) in the export dialog somewhere.

But in general I can only recommend the same thing as always: For production always create two separate mysql user accounts: One with read only permissions and one with read-write permissions.
Do not store the password for the read-write user in Keychain and only use the read-only user for regular tasks.

**Comment by necmettin** [comment]
I have a connection that allows access to both the development and the production databases. The isProduction filter would have to be not connection based, but server+database based.
