### ISSUE TITLE
changing the host when connecting and fails

### ISSUE THREAD

**Issue by jpita** [sequelpro/sequelpro#3426]
changing the host when connecting? I set 127.0.0.1 and you change to 10.11....
I'm using mysqlworkbench with the same exact details and I'm able to connect.

![image](https://user-images.githubusercontent.com/5482105/54821585-edd3bb80-4ca2-11e9-9849-c69f6f42c73e.png)

**Comment by dmoagx** [comment]
Wow...just wow...
Generation Twatter strikes again.

Please keep using MySQL Workbench. The Sequel Pro community does not have the resources to deal with this level of ignorance
