### ISSUE TITLE
Layout problems with Magnet

### ISSUE THREAD

**Issue by bencummins** [sequelpro/sequelpro#3428]
- Sequel Pro Version: Nightly 5438
- macOS Version: 10.14.3 
- MySQL Version: N/A

**Description**
When using shortcut keys in Magnet window manager to resize the window (i.e CTRL+OPTION+RIGHT) to  resize the window, the layout of the main application area (query window, results table etc) gets broken -making it unusable.

**Steps To Reproduce**
1. Have magnet running
2. Open a table
3. CTRL+OPTION+RIGHT (to make it take over the right half of the screen)

**Expected Behaviour**
Layout of all components reassessed after a resize

**Comment by dmoagx** [comment]
Duplicate of #3091
