### ISSUE TITLE
Support for MSSQL Server

### ISSUE THREAD

**Issue by matias-miranda** [sequelpro/sequelpro#3429]
I use SequelPro a lot, and recently I had to work on a project integrating an application with MSSQL server, I tried many other tools (GUI), and none of these worked as good as SequelPro with MySQL (and also they are not open source, nor free)

I think that would be great if SequelPro adds support for MSSQL Server.

**Comment by dmoagx** [comment]
See #362 for multi RDBMS support.

Realistically speaking, I don't think that will ever happen, though.
