### ISSUE TITLE
crashes when closing tabs

### ISSUE THREAD

**Issue by QusaiFarraj** [sequelpro/sequelpro#3431]
this issue has been going on for a while now and it needs to be addressed.

Every time I close a tab, Sequel Pro crashes and quit like I never used it. When I reopen it, I get this message, please report this to sequel pro and I did a lot. for like 3 months now with no action.

I reported this issue to Apple and no actions have been taken so far.

from the crash log:

> Termination Reason:    Namespace OBJC, Code 0x1

**Comment by wadehammes** [comment]
Seconded. Happens everyday. Same error, with ability to report.

**Comment by twjackson** [comment]
Same here. Everyday, all day.

**Comment by pingcheng** [comment]
get the test build instead, https://sequelpro.com/test-builds
the issue had been fixed there.

use it and wait for the stable release

**Comment by kaystrobach** [comment]
@pingcheng what's the plan for the next stable release, since the last one is 2 years old - thank you for your work.

**Comment by twjackson** [comment]
Thanks @pingcheng

**Comment by wadehammes** [comment]
Thanks @pingcheng. LOVE the dark mode!

**Comment by pingcheng** [comment]
> @pingcheng what's the plan for the next stable release, since the last one is 2 years old - thank you for your work.

hi， @kaystrobach, I am also a user as well :smile:
but according to the project board https://github.com/sequelpro/sequelpro/projects/2, there are still three issues are under consideration 😂

**Comment by dmoagx** [comment]
Duplicate of #3116

**Comment by QusaiFarraj** [comment]
@dmoagx Thanks for taking care of this issue.

**Comment by polycode-nz** [comment]
@dmoagx Is your recommendation for us to fix this to use a test build? Last time I grabbed a nightly it deleted all my favourites and I couldn't get them back.
