### ISSUE TITLE
"Sequel Pro appears to have lost the connection"

### ISSUE THREAD

**Issue by macsrwe** [sequelpro/sequelpro#3432]
- Sequel Pro Version: 66a46cd
- macOS Version: 10.13.6
- MySQL Version: 8.0.13

**Description**
Sequel Pro complains that it "appears to have lost the connection" when attempting to access tables after not having been used for a while (like 24 hours).

**Steps To Reproduce**
This bug can't be replicated on demand, but is very consistent. I run the MySQL server on my own machine, and it stays running all the time. 

On the first launch of the day, Sequel Pro will work OK as long as I click on *views* in the left-hand column, or (sometimes) very small tables; but when I click on one of my main tables (100 to 2500 rows) it immediately complains, "Sequel Pro appears to have lost the connection." It offers to retry or cancel. If I cancel, I can use command-N to open up another connection window and try again. If I retry, not only does it fail the same way, but I can't do squat with that Sequel Pro session from then on until I quit out of it completely and relaunch. It will do this over and over until I spend some time working with one of the views or tables it agrees to open off the bat. Once I "have the oil warmed up," all of a sudden it's happy to access and work with any of my tables. 

I tried updating to today's copy in case it got fixed, but it's still broken. I haven't the slightest idea what else to send you that would help you find this. If you suggest something, I'll capture it for you.

**Expected Behaviour**
I want to be able to click on a table and call up its contents, natch.

**Additional Context**
This behavior started only about a couple weeks ago.

**Comment by dmoagx** [comment]
If the "appears to have lost the connection" error occurs without any network being involved that usually means the server closed the connection in a panic. The most common causes for that would be:
* The server doesn't understand the packet structure of the client (or vice versa)
* The server had an issue in a critical code path (e.g. could not allocate memory or corrupt tables).

In your MySQL server log (or data) directory should be a file named "mysql_error_log.err" (or similar). Look there for any error messages.

Also if you have updated MySQL make sure that the `mysql_upgrade` tool has been run.

**Comment by macsrwe** [comment]
Does this help?

2019-04-02T14:03:16.791069Z 0 [System] [MY-010116] [Server] /usr/local/mysql/bin/mysqld (mysqld 8.0.13) starting as process 126
2019-04-02T14:03:16.797182Z 0 [Warning] [MY-010159] [Server] Setting lower_case_table_names=2 because file system for /usr/local/mysql/data/ is case insensitive
2019-04-02T14:03:17.325043Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
2019-04-02T14:03:17.348329Z 0 [System] [MY-010931] [Server] /usr/local/mysql/bin/mysqld: ready for connections. Version: '8.0.13'  socket: '/tmp/mysql.sock'  port: 3306  MySQL Community Server - GPL.
2019-04-02T14:03:17.547340Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Socket: '/tmp/mysqlx.sock' bind-address: '::' port: 33060
2019-04-04T01:26:03.187703Z 8 [ERROR] [MY-013183] [InnoDB] Assertion failure: dict0dict.cc:3289:for_table || ref_table thread 123145555501056
InnoDB: We intentionally generate a memory trap.
InnoDB: Submit a detailed bug report to http://bugs.mysql.com.
InnoDB: If you get repeated assertion failures or crashes, even
InnoDB: immediately after the mysqld startup, there may be
InnoDB: corruption in the InnoDB tablespace. Please refer to
InnoDB: http://dev.mysql.com/doc/refman/8.0/en/forcing-innodb-recovery.html
InnoDB: about forcing recovery.
01:26:03 UTC - mysqld got signal 6 ;
This could be because you hit a bug. It is also possible that this binary
or one of the libraries it was linked against is corrupt, improperly built,
or misconfigured. This error can also be caused by malfunctioning hardware.
Attempting to collect some information that could help diagnose the problem.
As this is a crash and something is definitely wrong, the information
collection process might fail.

key_buffer_size=8388608
read_buffer_size=131072
max_used_connections=2
max_threads=151
thread_count=3
connection_count=2
It is possible that mysqld could use up to 
key_buffer_size + (read_buffer_size + sort_buffer_size)*max_threads = 67867 K  bytes of memory
Hope that's ok; if not, decrease some variables in the equation.

Thread pointer: 0x7f9c469bfe00
Attempting backtrace. You can use the following information to find out
where mysqld died. If you see no messages after this, something went
terribly wrong...
stack_bottom = 70000f175e90 thread_stack 0x46000
0   mysqld                              0x00000001060e1d4c my_print_stacktrace(unsigned char*, unsigned long) + 60
1   mysqld                              0x000000010550f456 handle_fatal_signal + 678
2   libsystem_platform.dylib            0x00007fff7b47cf5a _sigtramp + 26
3   ???                                 0x0000000000000000 0x0 + 0
4   libsystem_c.dylib                   0x00007fff7b21a1ae abort + 127
5   mysqld                              0x000000010648ae99 ut_dbg_assertion_failed(char const*, char const*, unsigned long) + 329
6   mysqld                              0x000000010622911b dict_foreign_add_to_cache(dict_foreign_t*, char const**, bool, bool, dict_err_ignore_t) + 1707
7   mysqld                              0x0000000106242867 dd_table_load_fk_from_dd(dict_table_t*, dd::Table const*, char const**, dict_err_ignore_t, bool) + 1543
8   mysqld                              0x0000000106248aa3 dict_table_t* dd_open_table_one<dd::Table>(dd::cache::Dictionary_client*, TABLE const*, char const*, dd::Table const*, THD*, std::__1::deque<char const*, ut_allocator<char const*> >&) + 8403
9   mysqld                              0x0000000106239315 dd_table_open_on_dd_obj(dd::cache::Dictionary_client*, dd::Table const&, dd::Partition const*, char const*, dict_table_t*&, THD*) + 2213
10  mysqld                              0x000000010623bb1f dd_table_open_on_name(THD*, MDL_ticket**, char const*, bool, unsigned long) + 1887
11  mysqld                              0x000000010631b689 innobase_get_table_statistics(char const*, char const*, unsigned long long, dd::Properties const&, dd::Properties const&, unsigned int, ha_statistics*) + 1401
12  mysqld                              0x0000000106098b8c dd::info_schema::Table_statistics::read_stat_from_SE(THD*, String const&, String const&, String const&, String const&, unsigned int, unsigned int, unsigned long long, char const*, char const*, dd::info_schema::enum_table_stats_type, handlerton*) + 1068
13  mysqld                              0x00000001060985a9 dd::info_schema::Table_statistics::read_stat(THD*, String const&, String const&, String const&, char const*, String const&, unsigned int, unsigned int, String const&, unsigned long long, char const*, char const*, unsigned long long const&, unsigned long long const&, dd::info_schema::enum_table_stats_type) + 857
14  mysqld                              0x00000001051ada62 dd::info_schema::Table_statistics::read_stat(THD*, String const&, String const&, String const&, char const*, unsigned long long, char const*, char const*, unsigned long long const&, unsigned long long const&, dd::info_schema::enum_table_stats_type) + 130
15  mysqld                              0x00000001051a3672 get_table_statistics(Item**, unsigned int, dd::info_schema::enum_table_stats_type, bool*) + 946
16  mysqld                              0x00000001051a3298 Item_func_internal_table_rows::val_int() + 40
17  mysqld                              0x00000001051385e2 Item::save_in_field_inner(Field*, bool) + 578
18  mysqld                              0x000000010513c7c6 Item_ref::save_in_field_inner(Field*, bool) + 86
19  mysqld                              0x0000000105143fe4 Item_ref::save_in_result_field(bool) + 84
20  mysqld                              0x0000000105375d66 end_write(JOIN*, QEP_TAB*, bool) + 374
21  mysqld                              0x0000000105377785 evaluate_join_record(JOIN*, QEP_TAB*) + 613
22  mysqld                              0x000000010537714d sub_select(JOIN*, QEP_TAB*, bool) + 909
23  mysqld                              0x0000000105377785 evaluate_join_record(JOIN*, QEP_TAB*) + 613
24  mysqld                              0x00000001053772b8 sub_select(JOIN*, QEP_TAB*, bool) + 1272
25  mysqld                              0x0000000105377785 evaluate_join_record(JOIN*, QEP_TAB*) + 613
26  mysqld                              0x000000010537714d sub_select(JOIN*, QEP_TAB*, bool) + 909
27  mysqld                              0x0000000105377785 evaluate_join_record(JOIN*, QEP_TAB*) + 613
28  mysqld                              0x000000010537714d sub_select(JOIN*, QEP_TAB*, bool) + 909
29  mysqld                              0x0000000105377785 evaluate_join_record(JOIN*, QEP_TAB*) + 613
30  mysqld                              0x000000010537714d sub_select(JOIN*, QEP_TAB*, bool) + 909
31  mysqld                              0x0000000105377785 evaluate_join_record(JOIN*, QEP_TAB*) + 613
32  mysqld                              0x000000010537714d sub_select(JOIN*, QEP_TAB*, bool) + 909
33  mysqld                              0x0000000105371750 JOIN::exec() + 912
34  mysqld                              0x0000000105410278 handle_query(THD*, LEX*, Query_result*, unsigned long long, unsigned long long) + 632
35  mysqld                              0x00000001053ce09e execute_show(THD*, TABLE_LIST*) + 654
36  mysqld                              0x00000001053c8c6c mysql_execute_command(THD*, bool) + 4652
37  mysqld                              0x00000001053c6403 mysql_parse(THD*, Parser_state*, bool) + 915
38  mysqld                              0x00000001053c407d dispatch_command(THD*, COM_DATA const*, enum_server_command) + 4173
39  mysqld                              0x00000001053c5c83 do_command(THD*) + 467
40  mysqld                              0x00000001054f7744 handle_connection(void*) + 388
41  mysqld                              0x00000001064efadc pfs_spawn_thread(void*) + 316
42  libsystem_pthread.dylib             0x00007fff7b486661 _pthread_body + 340
43  libsystem_pthread.dylib             0x00007fff7b48650d _pthread_body + 0
44  libsystem_pthread.dylib             0x00007fff7b485bf9 thread_start + 13

Trying to get some variables.
Some pointers may be invalid and cause the dump to abort.
Query (7f9c4508ea28): SHOW TABLE STATUS LIKE 'locations_full'
Connection ID (thread ID): 8
Status: NOT_KILLED

The manual page at http://dev.mysql.com/doc/mysql/en/crashing.html contains
information that should help you find out what is causing the crash.

**Comment by dmoagx** [comment]
Yeah, that output shows that the mysql server thread died.
This is usually a bug in MySQL, so you should report it to them.
However the most likely cause is that your InnoDB data file is corrupt as the message says:
```
InnoDB: If you get repeated assertion failures or crashes, even
InnoDB: immediately after the mysqld startup, there may be
InnoDB: corruption in the InnoDB tablespace. Please refer to
InnoDB: http://dev.mysql.com/doc/refman/8.0/en/forcing-innodb-recovery.html
InnoDB: about forcing recovery.
```
I'll close this issue, as there is nothing on Sequel Pro's side that can be done here.
