### ISSUE TITLE
Interprete data as pretty JSON 

### ISSUE THREAD

**Issue by e3duardo** [sequelpro/sequelpro#3434]
Hi, I'm always storing JSON data on LONGTEXT Field. I would like to know if there is a possibility to create a prettify for JSON like these interpreters of this image.

![image](https://user-images.githubusercontent.com/12123036/55244271-a5c31480-521f-11e9-862f-3b40355ece30.png)

_I have no experience with this type of code, but I'm interested in implementing this if you can help me._

**Comment by ralbear** [comment]
I actually use a lot of `JSON` type fields and if you right click on the field editor and go to `Bundles>Format>Toggle JSON Format`(⌥⌘J) you can prettify the content.

**Comment by e3duardo** [comment]
I didn't know this formatter. But I sent the pull request #3446  with the structure I thought to solve this problem.

Thanks @ralbear, I'm not using my version of sequel anymore, so this will be very useful for me.

**Comment by e3duardo** [comment]
I'm closing this, since I no longer use Sequel
