### ISSUE TITLE
App Crash - utf8mb4_0900_ai_ci collation

### ISSUE THREAD

**Issue by sivrish** [sequelpro/sequelpro#3437]
I just opened a database and it crashed. I think it’s because my tables are in collation utf8mb4_0900_ai_ci and I’m using mysql 8.0.15

**Comment by dmoagx** [comment]
Which version of Sequel Pro?

**Comment by sivrish** [comment]
> Which version of Sequel Pro?

Sequel Pro 1.1.2 Build 4541

**Comment by sivrish** [comment]
Just checked on the nightly build. The crash is not occurring and the dark mode support looks dope.
