### ISSUE TITLE
create sql pro for windows and linux please

### ISSUE THREAD

**Issue by arditi-t2s** [sequelpro/sequelpro#3447]
Please create a version for windows and linux, there is nothing that comes even close to this software, you HAVE SPOILED US NOW CAN'T GO BACK TO TRASH SOFTWARE

**Comment by stychos** [comment]
it's barely alive in macOS, so I don't believe that's possible

**Comment by dmoagx** [comment]
Duplicate of #2578

**Comment by AdityaAnand1** [comment]
> it's barely alive in macOS, so I don't believe that's possible

Supporting a bigger OS such as Windows would likely fix that 😃
