### ISSUE TITLE
dark mode not respected in tab bar

### ISSUE THREAD

**Issue by kaystrobach** [sequelpro/sequelpro#3449]
relateed #2485 

## Current Behaviour

![grafik](https://user-images.githubusercontent.com/1185776/56109474-ff7e4b00-5f50-11e9-993d-980391a7aa08.png)

## Expected Behaviour

* tab titles readable
* somehow darker tabs

**Comment by stychos** [comment]
You can try to merge https://github.com/sequelpro/sequelpro/pull/3375 manually

**Comment by stuconnolly** [comment]
Being tracked under #2485
