### ISSUE TITLE
seqluelpro for mac is not stable

### ISSUE THREAD

**Issue by ivanzly** [sequelpro/sequelpro#3450]
![image](https://user-images.githubusercontent.com/29794167/56175808-5fe1bb00-602b-11e9-8774-2cd632ca0b96.png)

**Comment by link1st** [comment]
I am also in this situation.

**Comment by link1st** [comment]
This problem has been fixed
[#3116](https://github.com/sequelpro/sequelpro/issues/3116)
#3116 

(New Download address)[https://sequelpro.com/test-builds]

This is a duplicate bug, please close it after seeing it later.
Thank you.
