### ISSUE TITLE
Sequel pro encountered an unexpected error.

### ISSUE THREAD

**Issue by skyweaver213** [sequelpro/sequelpro#3451]
Mac os: 10.13.6 
Select any database will be encountered an unexpected error.
![image](https://user-images.githubusercontent.com/5363176/56465314-b5ec9f00-642d-11e9-8a73-e5f0b38579a9.png)

Details:

NSInvalidArgumentException

-[_NSInlineData isEqualToString:]: unrecognized selector sent to instance 0x61400002caa0

(
	0   CoreFoundation                      0x00007fff2d24f2db __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff544d2c76 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff2d2e7db4 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff2d1c5820 ___forwarding___ + 1456
	4   CoreFoundation                      0x00007fff2d1c51e8 _CF_forwarding_prep_0 + 120
	5   Sequel Pro                          0x00000001000587cd -[SPTablesList updateTables:] + 1338
	6   Sequel Pro                          0x00000001000469c5 -[SPDatabaseDocument _selectDatabaseAndItem:] + 454
	7   Foundation                          0x00007fff2f2d41f8 __NSThread__start__ + 1197
	8   libsystem_pthread.dylib             0x00007fff55404661 _pthread_body + 340
	9   libsystem_pthread.dylib             0x00007fff5540450d _pthread_body + 0
	10  libsystem_pthread.dylib             0x00007fff55403bf9 thread_start + 13
)

**Comment by dmoagx** [comment]
#2699

**Comment by Gideonmacha** [comment]
Fixed 100% working. Previously Sequel pro had problems with the latest version of mac os Mojave 10.14 and mysql 8.0, to ensure sequel pro works fine during the whole process of development you need to download Sequel pro Test build version here: https://sequelpro.com/test-builds
