### ISSUE TITLE
Dark Mode in High Sierra

### ISSUE THREAD

**Issue by lowercase00** [sequelpro/sequelpro#3458]
Hello.
I've managed to get the Dark Mode by building from the image using Xcode, but It didn't work on my desktop using High Sierra (couldn't find any option to change it as well).
Is there any way to switch to Dark Mode while using High Sierra?
If not, any plans on enabling it?
Cheers

**Comment by dmoagx** [comment]
Dark Mode is a OS X system feature that was only introduced with 10.14.
It won't work on older OS versions.
