### ISSUE TITLE
[REQ] Environment warning signs

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#346]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=346
Reporter:kevin.li...@gmail.com Date:2009-07-29 03:53:41 Status:Accepted

Can we please have the ability to set a particular connection such that it 
shows big ugly warning signs on the window for that connection?  I have a 
live and a test server with open connection to each, it'd be nice if the live 
window had big yellow-and-black stripes on it or something to show that it's 
a dangerous server.  That, or perhaps we can set a &quot;read-only&quot; to be sure no 
inserts or updates or deletes or alters get executed?

Ta,

**Comment by Loyen** [comment]
Any updates on this? I don't really want to ask for an ETA, but it feels like, based on the last TODO list @dmoagx wrote, that the issues left should be somewhat done by now. What is left to do to get this out to stable?

**Comment by dmoagx** [comment]
The drawing bug should be fixed now. (There is however another drawing bug when dragging tabs)
I haven't yet looked at highlighting the favorite.
I looked at coloring the table-list background, but as it turns out this is surprisingly difficult (probably even more so with 10.10)

Those are no blocking issues, though. What is holding us back right now are some hard to find 10.10 bugs.

**Comment by Loyen** [comment]
Just checking in what your status is on this, any updates?

I've noticed a version called "1.0.2M" (notice the M) that contains colored tabs, but I havn't seen any other visual changes. This version seems to have been available for about 6 months (if not more), but it isn't available through any source from you. Any idea what it is?

**Comment by dmoagx** [comment]
1.0.2M is most likely an unauthorized build distributed with MAMP.

**Comment by Loyen** [comment]
It seems to have been installed on several computers that runs MAMP 3.x (without their knowledge, it's been "auto updated").

**Comment by dmoagx** [comment]
Yeah, we haven't really decided what to do about that.
We could have them sign a Unterlassungserklärung (Cease & Desist) for infringing upon our name & logo rights, but so far we have assumed they did it without ill intent.
It is still problematic though as we have no way to check what this 1.0.2M build might be doing under the hood.

**Comment by Loyen** [comment]
I mailed them regarding this and this is what they responded with (I can send the the whole mail in a private message or something if required):

> Yes, we have included our own integrated edition. Without, you would have to configure your SP to work with MAMP PRO. This version of SP is signed, so you can see that we made it.
>
> If you don't want to use this version you can just throw it away, and get one from the Sequel Pro website.

**Comment by Loyen** [comment]
Feels like I'm spamming away on this one, but this request was created here almost 2 years ago (and the original request seems to be from 2009!) and it's still one a request heavily requested.

Seeing how many opened issues regarding this has been done during the time it's been on github, *can you estimate a time interval when we might be able to see this being dropped?* I'm well aware of the no ETA rules usually used, but this has been there for a very long time now, it's about time to push it into stable.

More than a year ago you said "[very soon](https://github.com/sequelpro/sequelpro/issues/346#issuecomment-55085045)", recommending me to run nightlies if I want the feature now. It might be safe enough, but nightlies *can* break so I would rather wait for a stable version.

Seeing MAMP auto updating sequel pro to nightlies with their edits, it might be safe enough to use? Last time I tried (I don't use MAMP anymore) you can't get around MAMP auto updating sequel to their M suffixed edition, but it might have changed.

**Comment by dmoagx** [comment]
1.1 will be released (probably) today.

**Comment by abhibeckert** [comment]
This feature is broken - when you only have one tab open there's nothing to warn users they're on a production server.

I think 1.2 should be updated to address the issue somehow... perhaps if there's no tab bar and the current connection has a colour, show a thin coloured line where the tab bar would be.

**Comment by dmoagx** [comment]
Well, you can always enable the tab bar even with only one tab.

My idea was to change the color shade of the table list view, but that's rather difficult.

**Comment by shadypierre** [comment]
@dmoagx thank you I didn't know we can enable the tab bar even with only one tab. :+1:

**Comment by abhibeckert** [comment]
This is implemented in the latest nightly build

**Comment by fulldecent** [comment]
Implemented here https://sequelpro.com/news/post?id=f91da543-470f-4443-8966-398be2fc946e

Recommending close.

![sequel-pro-1 1-connect-screen](https://cloud.githubusercontent.com/assets/382183/24383557/9dccb5f4-132b-11e7-89ac-55dcdf7a931f.png)

**Comment by abhibeckert** [comment]
@fulldecent the `Fixed-AwaitingRelease` label means this is fixed in nightly builds and will be part of 1.2.

Regarding your screenshot, that's not reliable since tabs are not always visible. It can't be trusted as a warning that you're on a production server.
