### ISSUE TITLE
Crashes when opening local database

### ISSUE THREAD

**Issue by paragonsoftwaresolutions** [sequelpro/sequelpro#3460]
Every time I attempt to open a database after connecting to my local development environment the application crashes. I get the popup to submit the error, but that fails to send as well. After that it just sits at the Loading database screen. I have no issues if I connect to my product environment, only the local one.

**Comment by paragonsoftwaresolutions** [comment]
Exception Error:
-[_NSInlineData isEqualToString:]: unrecognized selector sent to instance 0x6000002f43e0

(
	0   CoreFoundation                      0x00007fff44626cf9 __exceptionPreprocess + 256
	1   libobjc.A.dylib                     0x00007fff6f1baa17 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff446a0b06 -[NSObject(NSObject) __retain_OA] + 0
	3   CoreFoundation                      0x00007fff445c90ef ___forwarding___ + 1485
	4   CoreFoundation                      0x00007fff445c8a98 _CF_forwarding_prep_0 + 120
	5   Sequel Pro                          0x00000001000587cd -[SPTablesList updateTables:] + 1338
	6   Sequel Pro                          0x00000001000469c5 -[SPDatabaseDocument _selectDatabaseAndItem:] + 454
	7   Foundation                          0x00007fff467bc87e __NSThread__start__ + 1194
	8   libsystem_pthread.dylib             0x00007fff70bd62eb _pthread_body + 126
	9   libsystem_pthread.dylib             0x00007fff70bd9249 _pthread_start + 66
	10  libsystem_pthread.dylib             0x00007fff70bd540d thread_start + 13
)

**Comment by inigosola** [comment]
Same for me

**Comment by thiagolte** [comment]
Same for me

**Comment by sojoudian** [comment]
same here

**Comment by D0zingcat** [comment]
same for me.

**Comment by abeger** [comment]
Same here. Running against `mysql  Ver 8.0.16 for osx10.14 on x86_64 (Homebrew)`.

Database was created via Sequel Pro, data imported from a `.sql` file and then a crash. Progress bar never updated, but percentage did. Looking at the DB from the command line, the data appears to have imported correctly, but any time I try to access via Sequel Pro, I get a crash as described above.

**Comment by sojoudian** [comment]
this issue is caused by some variables which mysql 8 is return and sequelpro is not compatible with them. So, use the latest test build which is working fine with mysql 8 from : https://sequelpro.com/test-builds

**Comment by abeger** [comment]
That fixed it for me!! Thanks!

**Comment by Arslankhan422** [comment]
I tired the Test build and it's working for me. Thanks @sojoudian

**Comment by rootDEV2990** [comment]
same test build worked for me too got rid of my issues 
https://sequelpro.com/test-builds

This was my error i had tried test build can now load tables no prob


NSInvalidArgumentException

-[_NSInlineData isEqualToString:]: unrecognized selector sent to instance 0x60000032bc20

(
	0   CoreFoundation                      0x00007fff37b65be7 __exceptionPreprocess + 250
	1   libobjc.A.dylib                     0x00007fff7093d5bf objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff37be4c77 -[NSObject(NSObject) __retain_OA] + 0
	3   CoreFoundation                      0x00007fff37aca44b ___forwarding___ + 1427
	4   CoreFoundation                      0x00007fff37ac9e28 _CF_forwarding_prep_0 + 120
	5   Sequel Pro                          0x00000001000587cd -[SPTablesList updateTables:] + 1338
	6   Sequel Pro                          0x00000001000469c5 -[SPDatabaseDocument _selectDatabaseAndItem:] + 454
	7   Foundation                          0x00007fff3a1787a2 __NSThread__start__ + 1064
	8   libsystem_pthread.dylib             0x00007fff71ce9109 _pthread_start + 148
	9   libsystem_pthread.dylib             0x00007fff71ce4b8b thread_start + 15
)

**Comment by Amrgumaa** [comment]
thanks alot you saved me

**Comment by vanukw** [comment]
> this issue is caused by some variables which mysql 8 is return and sequelpro is not compatible with them. So, use the latest test build which is working fine with mysql 8 from : https://sequelpro.com/test-builds

This is really help for me, Thank you!

**Comment by zinwalin** [comment]
> this issue is caused by some variables which mysql 8 is return and sequelpro is not compatible with them. So, use the latest test build which is working fine with mysql 8 from : https://sequelpro.com/test-builds

many thanks.

**Comment by kvdml** [comment]
> this issue is caused by some variables which mysql 8 is return and sequelpro is not compatible with them. So, use the latest test build which is working fine with mysql 8 from : https://sequelpro.com/test-builds

thanks. is still the solution in 2024
