### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Snow741** [sequelpro/sequelpro#3462]
When I close the tab, the software will crash;
it happened on macOS Mojave 10.14.2; 
version : sequel-pro-1.1.1 and sequel-pro-1.1.2

**Comment by necmettin** [comment]
Happens to me multiple times every single time. I've been meaning to create a bug report, consider this one.

Almost every time I close a tab, the application will crash.

**Comment by dvdhoek** [comment]
I'm experiencing the same issue. Already filed a bug report

**Comment by khallouki** [comment]
Yes, me to and many of my colleagues are experiencing the same.

**Comment by Read1337** [comment]
Same here, for the last month's sequel pro is crashing after closing a tab.
sequel-pro-1.1.2
macOS Mojave version 10.14.4

**Comment by georgexsh** [comment]
did anybody notices the pinned issue? https://github.com/sequelpro/sequelpro/issues/3116

**Comment by necmettin** [comment]
According to that bug report, it's been fixed ~6 months ago, and is still not released. Six months?

**Comment by georgexsh** [comment]
no new release since 2016.

**Comment by necmettin** [comment]
I guess the project is abondoned? :/

Downloaded and built the app, 2 errors and ~50 warnings, but seems to be working.

**Comment by georgexsh** [comment]
test build is downloadable from its website.

**Comment by Snow3721** [comment]
> I guess the project is abondoned? :/
> 
> Downloaded and built the app, 2 errors and ~50 warnings, but seems to be working.

oh, it's unbelievable, in fact, I think sequel is the best db software on mac;

**Comment by Snow3721** [comment]
> test build is downloadable from its website.

额，这个粉红色的标签栏看起来是真的丑;

**Comment by sonicwong** [comment]
@georgexsh any link?

**Comment by sonicwong** [comment]
Download link:
https://sequelpro.com/test-builds

**Comment by ThanmayaB** [comment]
This same issue has been occurring consistently with me for the past few months:
Sequel Pro 1.1.12
Build 4541 (602e11a)

Mac OS Mojave 10.14.4

**Comment by DanielBickley** [comment]
Same problem. I'll download the "test build" as it sounds like that might be the most stable release oddly enough.

**Comment by fredbradley** [comment]
## Same here

Sequel Pro 1.1.2 (4541)
Mac OS X 10.14.4 (Mojave)

## More detail
To clarify the problem only happens when you have more than one connection open - either another window or another tab. 

I'm reluctant to download a test build. If it's fixed in the test build, how long under a patched update will be released?

**Comment by andrew-dixon** [comment]
Same here, with same versions as @fredbradley above.

**Comment by raymondjplante** [comment]
**Don't Let the Perfect Be the Enemy of the Good.**   Been almost  3 years since last release, should probably move ahead with a new incremental release with whatever they've got.

**Comment by georgexsh** [comment]
for anyone want the developers work for him, I wonder have you donated to the developer?

**Comment by necmettin** [comment]
> for anyone want the developers work for him, I wonder have you donated to the developer?

where is this coming from? nobody was that rude to the developers? nobody in this thread said anything to the developer?

**Comment by fordnox** [comment]
where can i donate to fix this issue? i love sequel pro and it just brings me to tears when i see this window multiple times per day.

Also it may be related to dark mode that `Mojave` introduced.

<img width="632" alt="Screenshot 2019-06-04 at 17 38 56" src="https://user-images.githubusercontent.com/398619/58888360-f3f90600-86ef-11e9-948f-b62bf9044585.png">

**Comment by andrew-dixon** [comment]
@fordnox I think at this point, your best option might be to fork to the project if you want to take over maintaining it.

**Comment by stychos** [comment]
@fordnox you can use test builds available on the official website, this trouble is resolved long time ago in them. Also you can try my fork, it contains some improvements for the dark mode and the filters error handling: https://github.com/stychos/sequelpro/releases/

**Comment by andrew-dixon** [comment]
@stychos Any ideas why there has never been another release here?

**Comment by stychos** [comment]
@andrew-dixon I don't know. As I see from my point of view original authors abandoned project. No project maintainer and no active developers for the actual macOS version here. I am not related to the Sequel Pro development team in any way, so it's my own opinion and may be wrong. That would be great if I am wrong.
