### ISSUE TITLE
Crash with two DB Connections

### ISSUE THREAD

**Issue by ChrisGitIt** [sequelpro/sequelpro#3463]
Hi, my SequelPro is constantly crashing when i open more than one DB connection at a time and try to close one later on => crash while closing one (close window, via Menu or Keyboard shortcut).

With "Db connection", I mean a new window to a new db. Working with tabs for tables (which seem to create a new DB connection) does not result in a crash.

Currently, these DB connects are over ssh, key based and on a custom ssh port. It does not matter if I opened up a table or anything. Just opening two db connections so that two windows appear. Closing one of the windows results in an immediate crash.

Also, sending a crash report does not seem to work (timeout of the remote server).

This issue is not critical, but its annoying and probably is easy to fix. Unfortunately, I'm not much into MacOS programming ... no time to learn. Sorry I can not help more with that issue!

Greets,

Chris

**Comment by andrew-dixon** [comment]
Duplicate of #3462
