### ISSUE TITLE
If I have two tabs open, then close one, the app crashes.

### ISSUE THREAD

**Issue by mitchumowen** [sequelpro/sequelpro#3464]
If I have two tabs open, then close one, the app crashes.  I see several other users are having the same issue, but I'm not sure why their tickets have been closed.  The issue has been persistent for me for over a year, and it seems the issue is not resolved.

Also, I'm not able to report the error using the built-in crash reporting.

<img width="578" alt="image" src="https://user-images.githubusercontent.com/2132136/57483961-b9b95780-725c-11e9-8f84-c6ed7d26c873.png">

<img width="645" alt="image" src="https://user-images.githubusercontent.com/2132136/57484036-ee2d1380-725c-11e9-9617-7d5574c2032f.png">

![image](https://user-images.githubusercontent.com/2132136/57484086-0bfa7880-725d-11e9-88c6-7b6455c5283a.png)

**Comment by christiangun** [comment]
Version 1.1.2 is the latest release but that was made in 2016 so it doesn't have the changes the issues refer to. Unfortunately it appears there are no new releases coming out of the project. Either download the nightly builds or, if you can, build it yourself from source.

This issue can shed some light on the situation: https://github.com/sequelpro/sequelpro/issues/3385

**Comment by yifanfu** [comment]
> Version 1.1.2 is the latest release but that was made in 2016 so it doesn't have the changes the issues refer to. Unfortunately it appears there are no new releases coming out of the project. Either download the nightly builds or, if you can, build it yourself from source.
> 
> This issue can shed some light on the situation: #3385

Hi, thanks for the input, do you know when will be the next release? Thanks heaps mate.

**Comment by techouse** [comment]
If you want the latest and greatest (by that I mean dark mode <3) simply clone the master from GitHub and build it in Xcode.

**Comment by viion** [comment]
I am also getting this, are nightly builds the only way to go? Not having a release for 3 years makes it sound like this app is dead?
