### ISSUE TITLE
Add databases to a list after connected

### ISSUE THREAD

**Issue by joshwcorbett** [sequelpro/sequelpro#3466]
It feels unnecessary having to put my database information in everytime I open sequel pro. I'd like for it to greet you with 'recent' databases or 'saved' databases much like SQL Workbench. Feels like a necessary feature.

**Comment by joshwcorbett** [comment]
It feels unnecessary having to put my database information in everytime I open sequel pro. I'd like for it to greet you with 'recent' databases or 'saved' databases much like SQL Workbench. Feels like a necessary feature.

**Comment by shaneparsons** [comment]
You can click "Add to favourites" to save them to the Quick Connect panel.
