### ISSUE TITLE
关闭标签即闪退

### ISSUE THREAD

**Issue by KENYHU** [sequelpro/sequelpro#3468]
- Sequel Pro Version:
- macOS Version:  10.14.4 (18E226)
- MySQL Version:  5.6.26

**Description**
关闭标签即闪退

**Steps To Reproduce**
1. 添加大于2个MySQL链接的标签Tag
2. 关闭其中的任何一个

**Comment by pingcheng** [comment]
#3464

**Comment by KENYHU** [comment]
谢谢，Thank you so much!

**Comment by jr1949** [comment]
> 谢谢，Thank you so much!

看不懂，如何解决

**Comment by KENYHU** [comment]
> > 谢谢，Thank you so much!
> 
> 看不懂，如何解决

看了下，答题意思是： 发行版是落后于代码提交版本的，自己build一个新版本的！  但是我不是MacOS的开发，有点难度，只能请朋友帮忙了！

**Comment by KENYHU** [comment]
> > 谢谢，Thank you so much!
> 
> 看不懂，如何解决

大体

**Comment by pingcheng** [comment]
这里有比较新的 test build 可以直接下载https://sequelpro.com/test-builds

**Comment by jr1949** [comment]
> > > 谢谢，Thank you so much!
> > 
> > 
> > 看不懂，如何解决
> 
> 看了下，答题意思是： 发行版是落后于代码提交版本的，自己build一个新版本的！ 但是我不是MacOS的开发，有点难度，只能请朋友帮忙了！

非常感谢

**Comment by jr1949** [comment]
> 这里有比较新的 test build 可以直接下载https://sequelpro.com/test-builds
> 
> Anyone who has the permission here can close this issue as the solution is presented

好的，我试试

**Comment by KENYHU** [comment]
> > 这里有比较新的 test build 可以直接下载https://sequelpro.com/test-builds
> > Anyone who has the permission here can close this issue as the solution is presented
> 
> 好的，我试试

不过，这个test_build 因为是测试包，我还是持保留意见！

**Comment by pingcheng** [comment]
> > > 这里有比较新的 test build 可以直接下载https://sequelpro.com/test-builds
> > > Anyone who has the permission here can close this issue as the solution is presented
> > 
> > 
> > 好的，我试试
> 
> 不过，这个test_build 因为是测试包，我还是持保留意见！

他的test build也是从master上编译的，和你直接拉一下来是一样的。
