### ISSUE TITLE
SQL ERROR when granting "delete versioning rows" on a specific database to a specific user

### ISSUE THREAD

**Issue by e-gaulue** [sequelpro/sequelpro#3471]
- Sequel Pro Version: Build 5438
- macOS Version: 10.14.2
- MySQL Version: mysql  Ver 15.1 Distrib 10.3.14-MariaDB

**Description**
SQL ERROR when granting "delete versioning rows" on a specific database to a specific user. All the other ones are OK.

**Steps To Reproduce**
1. Well Database > User accounts... > ... 

**Expected Behaviour**
No error

<img width="446" alt="Capture d’écran 2019-05-20 à 21 15 57" src="https://user-images.githubusercontent.com/4291874/58046039-7c9a7280-7b44-11e9-9e0a-1a18842747f6.png">

**Comment by rlphnger** [comment]
Build 5446 has the same problem with mysql Ver 15.1 Distrib 10.3.15-MariaDB

**Comment by jsonUK** [comment]
Same issue with me - running MariaDB 10.3.12.
