### ISSUE TITLE
Binary as hex displayed in unreadable color when using Mojave's dark theme

### ISSUE THREAD

**Issue by poige** [sequelpro/sequelpro#3473]
- Sequel Pro Version: Build 5438 664a46cd
- macOS Version: 10.14.5

![image](https://user-images.githubusercontent.com/600779/58261307-3fcbb700-7da2-11e9-80ec-b43255101db5.png)

**Comment by poige** [comment]
ok, bringing in more activity

**Comment by Kaspik** [comment]
Please see https://github.com/sequelpro/sequelpro/issues/3705
