### ISSUE TITLE
Version 1.1.2 - systematic crash on Mac OSX 10.14.5 

### ISSUE THREAD

**Issue by RikMaxSpeed** [sequelpro/sequelpro#3477]
The app crashes systematically & reproducibly by opening a 2nd tab connected to a different database, and closing the first tab.

They don't even need to be tabs, the same problem happens if you have them in multiple windows. It simply doesn't like closing the first connection.

Looks like this has been reported multiple times already. I do hope you can fix!

**Comment by DaveLo** [comment]
Pinned issue for this exact problem #3116 

I don't work on the project, but I know the nightly build mentioned in the pinned issue is currently your best bet (https://sequelpro.com/test-builds)
