### ISSUE TITLE
Sequel Pro Docs link problem

### ISSUE THREAD

**Issue by d35k** [sequelpro/sequelpro#3478]
**Description**
Hi all,

I was checking Get Involved section of Sequel Pro's docs page, and I saw a little bug in the Programmers Section.

**Steps To Reproduce**
1. Go to this link: https://sequelpro.com/docs/contribute/get-involved
2. Check the URL of 'check out' link below Programmers section.

you can check the screenshot of problem with this link: https://pasteboard.co/Ii3vWCg.png

**Comment by stuconnolly** [comment]
#2715
