### ISSUE TITLE
macOS 10.15 - crash when clicking on show table content filters 

### ISSUE THREAD

**Issue by S8ER01Z** [sequelpro/sequelpro#3481]
- Sequel Pro Version: Build 5438 (664a46cd)
- macOS Version: Version 10.15 Beta (19A471t)
- MySQL Version: 5.5.42

**Description**
When clicking on "Show/Hide Table Content Filters" icon in the Content view causes the application to close.

**Steps To Reproduce**
1. Open Sequel Pro
2. Choose a db from the dropdown list
3. Select a table in the db to view
4. Select "Content View"
5. Click on the  "Show/Hide Table Content Filters" icon 

**Expected Behaviour**
I expect the filter panel to appear above the row of results.

> Application Specific Information:
Crashing on exception: The window has been marked as needing another Update Constraints in Window pass, but it has already had more Update Constraints in Window passes than there are views in the window.

[SequelPro-CrashLog.txt](https://github.com/sequelpro/sequelpro/files/3262957/SequelPro-CrashLog.txt)

**Comment by hhatfield** [comment]
I, too, am witnessing weirdness in the 10.15 beta, but seeing as they never released the fixes needed for 10.14, I wouldn't hold my breath.

**Comment by orcinus** [comment]
Issue still present in 19A487l.

**Comment by jpike88** [comment]
It's broken to hell on Catalina so I think moving forward it's time to lose all hope.

TablePlus works well and is free for 2 tabs max or something

**Comment by orcinus** [comment]
2 tabs per window, but 2 workspaces, so 4 tabs total.

Switched to TablePlus too for now.
If it pans out for my day-to-day stuff, i think i'm going to take the plunge.

**Comment by S8ER01Z** [comment]
This is resolved on latest macOS release 10.15 Beta (19A501i) "Beta 3"

I am going to close this out, I suspect they are still working on APIs so it's likely to break again prior to PROD release in the fall.
