### ISSUE TITLE
Sequel Pro requests access to Photos

### ISSUE THREAD

**Issue by jwcmd** [sequelpro/sequelpro#3483]
- Sequel Pro Version: 1.1.2 (Build 4541)
- macOS Version: 10.14.5
- MySQL Version: N/A

**Description**
Sequel Pro has requested access to my photos, which feels well outside the purview of a database GUI and goes against the principle of least astonishment.

**Steps To Reproduce**
Unfortunately this is not reproducible.
This was triggered after I had used Sequel Pro about a half hour ago, but had since finished my troubleshooting and had left Sequel Pro minimized.

This happened to me once before, but I clicked Don't Allow and didn't think much of it at the time. Chewing on it later I wished I'd taken a screenshot and noted details of when that happened to assist in filing a ticket just like this.

**Expected Behaviour**

**Additional Context**
Happy to answer any questions, but I'm afraid I don't know what else to add.
I was working with the CLI mysql client to troubleshoot an SSL issue with a MySQL server when this popped up. Sequel Pro was open, but was not and had not been used in ~15-30 minutes.

<img width="420" alt="Screen Shot 2019-06-10 at 3 09 56 PM" src="https://user-images.githubusercontent.com/48369976/59230670-13ca7700-8b93-11e9-90a3-bc75d1be2336.png">

**Comment by italktocomputers** [comment]
This is something new with Mojave and has nothing to do with SequelPro (as far as I can see).  Mojave introduced new privacy settings.  For example, if you attempt to enter the photos directory from within Sequel Pro, you will get this prompt.  You can safely click the "Don't Allow" button.  If you clicked "OK" already, you can go to System Preferences >> Security and Privacy >> Privacy, and under Photos, uncheck Sequel Pro.

**Comment by rowanbeentje** [comment]
What is weird is what in Sequel Pro could possibly have triggered this if it wasn't being used 🤔  It doesn't sound like it had been navigated in a file dialog to the photos directory, and I can't think what else would have caused this...
