### ISSUE TITLE
MySsql lower case table name in view

### ISSUE THREAD

**Issue by richardpbull** [sequelpro/sequelpro#3488]
Note that the case of tables referred to in a view may not match the case of the actual table names. tblhotel vs tblHotel..

This means the view cannot be copied to another server for instance, but cutting and pasting the view's create syntax.

https://www.dropbox.com/s/boeecwynqce6i04/Screenshot%202019-06-19%2011.07.42.png?dl=0

https://www.dropbox.com/s/bikcoeugv2c7wfk/Screenshot%202019-06-19%2011.10.51.png?dl=0

**Comment by italktocomputers** [comment]
Strange.  When building off of master or using the current binary version, I do not see this issue. 
![Screen Shot 2019-07-08 at 8 21 19 PM](https://user-images.githubusercontent.com/25874157/60850632-2cdc3d00-a1be-11e9-9da8-c875e088e90e.png)

**Comment by richardpbull** [comment]
I have this version...

[image: Screenshot 2019-07-09 13.43.36.png]
I still get this output... let me know if there is anything I can do to
help provide any more info...
Richard

[image: Screenshot 2019-07-09 13.44.30.png]

**Comment by italktocomputers** [comment]
Sorry, I was unable to see your screenshots.  I'm guessing because you replied via email?

**Comment by richardpbull** [comment]
Better as a link?

https://wetransfer.com/downloads/f459fecf172a0764437e7c877900d8ec20190710123925/fd571b34c6f10ce697399d9150e7443c20190710123925/0535b9
