### ISSUE TITLE
Linking and navigating not working

### ISSUE THREAD

**Issue by Sofianio** [sequelpro/sequelpro#3491]
- Sequel Pro Version: Nightly build 5446 (97c1b857)
- macOS Version: 1.14.3
- MySQL Version: 5.6.28

**Description**
Linking and navigating [Request] #209 isn't working in recent builds

**Steps To Reproduce**
1. go to any table with a foreign key
2. click the foreign key (little arrow)

**Expected Behavior**
It use to take you to the related table and show the selected index only, now it only opens the table

**Additional Context**
This used to work fine in 1.1.2, it was soooo helpful.

Please bring it back

**Comment by Dalamar** [comment]
Same build same issue. 
This is one of the most valuable features of the Sequel Pro.
I really miss it.
Hope it will be fixed soon.

**Comment by Ultima2876** [comment]
Even worse, it seems to (confusingly) use the row ID instead of the foreign ID to highlight a row. E.g I have a row with id "5", user_id "1073" [foreign key]. If I click that user ID, I would expect to see row 1073 in the users table - instead it takes me to row 5.

**Comment by Sofianio** [comment]
Close the issue because it's stale? Really?
So if the devs ignore an issue it just goes away?

**Comment by Ultima2876** [comment]
Use TablePlus instead. This is abandonware.

**Comment by stychos** [comment]
@Sofianio @Ultima2876 check it out https://github.com/Sequel-Ace/Sequel-Ace

**Comment by Sofianio** [comment]
@stychos This issue exits in Sequel-Ace also ... Do I create an issue there too?
I don't like the icon too, but that's unrelated

**Comment by stychos** [comment]
@Sofianio yes, better to create issue there.
There is a sketch of better icon: https://github.com/Sequel-Ace/Sequel-Ace/issues/31, I think it will be applied to the next release. And always welcome if you can propose anything better!

**Comment by Sofianio** [comment]
@stychos Done! 
And I like the suggested new icon

**Comment by Kaspik** [comment]
@Sofianio Sorry for the stale bot info - I added it tonight so everyone is aware there is "some" activity here. But as mentioned in top of the Readme starting today - this project is being replaced.

Thanks for creating a new issue there!

For reference in the future and other folks: https://github.com/Sequel-Ace/Sequel-Ace/issues/54
We will take a look on that.
