### ISSUE TITLE
Upgrade libmysqlclient.a for TLSv1.1 support (for MariaDB 10.4 default installs)

### ISSUE THREAD

**Issue by noahwilliamsson** [sequelpro/sequelpro#3492]
Sequel Pro currently appears to ship a `libmysqlclient.a` library from the 5.5.x series.  This libary only supports the older and (security wise) broken TLSv1.0 protocol.

- https://github.com/sequelpro/sequelpro/commits/master/Frameworks/SPMySQLFramework/MySQL%20Client%20Libraries

The most recent GA release of MariaDB, version 10.4.6, replaces the embedded yaSSL library (not maintained) with wolfSSL (maintained, supports modern TLS) and ships with a newly introduced `tls_version` setting that defaults to `TLSv1.1,TLSv1.2,TLSv1.3`.  References:

- https://mariadb.com/kb/en/library/secure-connections-overview/#enabling-specific-tls-protocol-versions
- https://mariadb.com/kb/en/library/ssltls-system-variables/#tls_version
- https://jira.mariadb.org/browse/MDEV-19542 (Disable SSLv3 and TLSv1.0)
- https://jira.mariadb.org/browse/MDEV-18531 (Use WolfSSL instead of YaSSL as "bundled" SSL)

A `libmysqlclient.a` library from the 5.7.x series appears to support both TLSv1.0 and TLSv1.1:

- https://bugs.mysql.com/bug.php?id=75239

Would it be possible to upgrade the MySQL client library to a newer release to make it support a slightly more modern version of TLS?  That would allow Sequel Pro to connect to MariaDB 10.4 servers out of the box and also improve security.

**Comment by dmoagx** [comment]
Hey Noah,

"wolfSSL" is AFAIK just a rebranding of yaSSL.

SP is mostly stuck with 5.5 because IIRC 5.6 introduced breaking changes in how some functions in the client libraries behave, thus someone would have to step through the source code or the changelogs and compare those in detail, which is quite a bit of effort.

Personally I think it would be better to get rid of the SSL library dependency altogether and use the Apple provided library (SecureTransport or CF Networking), like all native OS X apps would, but that also is a lot of effort.

**Comment by noahwilliamsson** [comment]
Thanks for the feedback.

Right, it seems they renamed CyaSSL to wolfSSL in 2015.  CyaSSL was their C port/product of their C++ yaSSL SSL library.

Any idea what these functions in the client libraries would be?  I did `git log --grep mysqlcl -p` but didn't find anything obvious besides #2979 (backed out again I think?).

In the process I found a build script for building `libmysqlclient.a`, which led me to an attempt to build Sequel Pro with a 5.7 series libmysqlclient on a macOS Sierra (10.12) machine.

1. Download a `.dmg` from https://cmake.org/download/ and install it to /Applications
2. Download Boost 1.59 from https://sourceforge.net/projects/boost/files/boost/1.59.0/boost_1_59_0.tar.gz/download (file should end up in `~/Downloads`)
3. See below

```
cd ~/Downloads
git clone https://github.com/sequelpro/sequelpro.git
git clone --depth 50 --branch 5.7 https://github.com/mysql/mysql-server.git
tar zxf boost_1_59_0.tar.gz
export PATH=$PATH:/Applications/CMake.app/Contents/bin

cd sequelpro/Frameworks/SPMySQLFramework
vi build-mysql-client.sh   # modify the following lines:
  MIN_OS_X_VERSION=10.13   # Last SDK supporting i386 arch?
  CONFIGURE_OPTIONS        # Add this switch: -DWITH_BOOST=~/Downloads/boost_1_59_0

# Build libmysqlclient.a
./build-mysql-client.sh -s ~/Downloads/mysql-server -d

# The script will fail with an error due to changed paths but lets ignore that for now and just:
cp ~/Downloads/mysql-server/archive_output_directory/libmysqlclient.a "MySQL Client Libraries/lib/"

open SPMySQLFramework.xcodeproj
# Patch up linker flags for SPMySQLFramework:
# Under Build Settings > All > Linking > OTHER_LDFLAGS, add `-lc++` to SPMySQL.framework targets

# Finally, open the Sequel Pro project and build everything with an updated libmysqlclient.a
open ../../sequel-pro.xcodeproj
```

FWIW, I ended up with something that allowed me connect to MariaDB 10.4.6 (requires TLSv1.1) and a few AWS RDS MySQL 5.6 and Aurora MySQL servers (still using TLSv1.0).

![SequelPro-mysql-5 7](https://user-images.githubusercontent.com/91926/60228172-1f57b680-9892-11e9-9363-b92b0eb0241f.png)
