### ISSUE TITLE
IMPORTANT: Crashes on macOS 10.15 when trying to find

### ISSUE THREAD

**Issue by jpike88** [sequelpro/sequelpro#3494]
When trying to press command+f or edit>find>find, sequel pro crashes.
Crash log attached
[log.txt](https://github.com/sequelpro/sequelpro/files/3332725/log.txt)

**Comment by soitif** [comment]
When close a connection , Crashes too
macOS 10.15

**Comment by jpike88** [comment]
@soitif I'm using TablePlus now

**Comment by italktocomputers** [comment]
I've seen this error before as well (when closing a connection).  I'm very curious what the problem is here and will try to take a look later tonight.

**Comment by LinusU** [comment]
> I've seen this error before as well (when closing a connection)

@italktocomputers this issue has been fixed since over a year ago, but unfortunately there haven't been a new release yet 😞 

https://github.com/sequelpro/sequelpro/issues/3116#issuecomment-434442059

**Comment by italktocomputers** [comment]
I see, thanks.
