### ISSUE TITLE
25293

### ISSUE THREAD

**Issue by wangzhaoyii** [sequelpro/sequelpro#3497]
An error occured while trying to add the password to your Keychain. Repairing your Keychain might resolve this, but if it doesn't please report it to the Sequel Pro team, supplying the error code -25293.

**Comment by italktocomputers** [comment]
This error looks to be caused by ```Authorization and/or authentication failed```: https://developer.apple.com/documentation/security/1542001-security_framework_result_codes/errsecauthfailed?language=objc.

Try going to your keychain and revealing a password.
