### ISSUE TITLE
Keeps on crushing in MacOS Mojave

### ISSUE THREAD

**Issue by veslorde** [sequelpro/sequelpro#3499]
Keeps on crushing in MacOS Mojave

**Comment by CodyFitzpatrick** [comment]
This issue has been solved in a future release.

**Comment by CodyFitzpatrick** [comment]
This issue has been resolved and the solution will be present in a future release.

**Comment by veslorde** [comment]
When is the future release?

**Comment by rohandeshmukh91** [comment]
Any update when the new release will be available?

**Comment by b2un0** [comment]
use the latest test build from here, works like a charm (also with dark mode support!) ;)
https://sequelpro.com/test-builds

**Comment by thiagok** [comment]
Will the testa build auto load into a Official build? Or we need to download the official when it's available?

**Comment by Neo2SHYAlien** [comment]
Thank you very much. I had crashing on every tab close. Latest nightly works fine!!!

**Comment by danielgarcia** [comment]
Had the same issue. Just use the latest test build from here, works perfectly. 
Im using the 97c1b85783 commit 

https://sequelpro.com/test-builds
