### ISSUE TITLE
Unable to use Sequel Pro in Mac Catalina

### ISSUE THREAD

**Issue by Sivasankaramalan** [sequelpro/sequelpro#3502]
In MacOS Catalina beta, we are unable to open the Sequel Pro. getting below error.

MySQL said: Authentication plugin 'dialog' cannot be loaded: dlopen(/usr/local/lib/plugin/dialog.so, 2): no suitable image found.  Did find:
	/usr/local/lib/plugin/dialog.so: code signature in (/usr/local/lib/plugin/dialog.so) not valid for use in process using Library Validation: Library load disallowed by System Policy

“dialog.so” can’t be opened because Apple cannot check it for malicious software.

**Comment by kabaluyot** [comment]
issue still exist and confirm it with latest sequelpro, macos catalina

**Comment by HabedyOmid** [comment]
Confirming that the issue unfortunately has not appeared to have any solution yet. its kinda destroyed our development environment after updating MacOS. but to get up and running quick you may want install MAMP comes with MySql and this way you can use Sequel Pro using MAMP mysql creds to login. thats doesnt sound right and not the best way, i know. but to avoid any downtime of development, this would get you up and running. 

still hoping we are going have this issue resolved soon.

**Comment by JackEdwardLyons** [comment]
Any news on this? It's not working for me either :(

**Comment by kabaluyot** [comment]
I installed MySQL Workbench until this issue is fixed :/

**Comment by danielgarcia** [comment]
Had the same issue. Just use the latest test build from here, works perfectly.

https://sequelpro.com/test-builds

**Comment by jicksonjohnson** [comment]
@danielgarcia is right, I tried the commit **97c1b85783** and it works fine on macOs catalina ( version 10.15.3 )
