### ISSUE TITLE
Passwords are not stored in keychain

### ISSUE THREAD

**Issue by alexanderkraemer** [sequelpro/sequelpro#3503]
- Sequel Pro Version: nightly build 5446 (97c1b857)
- macOS Version: Mojave 10.14.5 (18F203)
- MySQL Version: 8.0

**Description**

**Steps To Reproduce**
1. save a connection to your favourites
2. close sequel pro
3. reopen it
4. see, that there is no password stored

**Expected Behaviour**
Password should be stored in the connection

**Comment by gomcarter** [comment]
restart your mac.

**Comment by alexanderkraemer** [comment]
figured out, it was because of using the `LIBMYSQL_ENABLE_CLEARTEXT_PLUGIN`.
Unfortunately, when you use this, passwords don't get stored anymore.
