### ISSUE TITLE
List of tables sorted alphabetically in relation modal

### ISSUE THREAD

**Issue by skiiiks** [sequelpro/sequelpro#3506]
When you create a relation, it appears a modal, and one of the fields is to select the table.
This list is sorted (randomly?) and it's a mess when you have tons of tables.

It should be sorted alphabetically in order to find the name of the table faster.
thank you !

**Comment by adantart** [comment]
this feature is so easy to implement and so painful to suffer ... :-(  please! do not forget this one ;-)

<img width="424" alt="Captura de pantalla 2019-09-20 a las 12 31 50" src="https://user-images.githubusercontent.com/695272/65320744-d5d1eb80-dba2-11e9-846b-65b60dc45792.png">
