### ISSUE TITLE
Any Support for this software?

### ISSUE THREAD

**Issue by Hubertnator** [sequelpro/sequelpro#3508]
Do we have any hope of a new release? This software crashes on MacOS Mojave, an yet MacOS Catalina is getting closer. Is there hope of a new release, or should we just... use alternatives like TablePlus?

**Comment by Fossil01** [comment]
Sadly not... I am now trying to use TablePlus but don't like it at all.

**Comment by Hubertnator** [comment]
The only thing I have is a fork - that fixes very few bugs...
[Here it is...](https://github.com/Hubertnator/sequelpro)

**Comment by peternijssen** [comment]
You can use the latest test build: https://sequelpro.com/test-builds

**Comment by Fossil01** [comment]
I have, and there are still issues. The search bar is gone for example.

**Comment by sylvaindeloux** [comment]
Is a stable version coming soon?

`release-1.1.2` tag dates from 2016…

**Comment by Fossil01** [comment]
Wouldn't count on it...

**Comment by tsunamilx** [comment]
I am sorry to say that but it looks like dead to me...
