### ISSUE TITLE
Crashes when closing a 2 tabs window (and there's other window)

### ISSUE THREAD

**Issue by adantart** [sequelpro/sequelpro#3513]
- Sequel Pro Version: 1.1.2 Compilation 4541
- macOS Version: 10.14
- MySQL Version: mysql  Ver 15.1 Distrib 10.3.15-MariaDB, for osx10.14 (x86_64) using readline 5.1

**Description**
When you close a window with more than 1 tab, and there's other window (with anything) program crashes

**Steps To Reproduce**
1. open a window, then at least 2 different connections (2 tabs or more)
2. open a new window, do whatever
3. close the first one
4. it crashes

**Expected Behaviour**
Close the window and leave the other(s) alive without crashing ;-)

https://pastebin.com/wzaVzUkW

**Comment by ahmadsyamim** [comment]
Duplicate of #3116

**Comment by jonathangreco** [comment]
https://sequelpro.com/test-builds

**Comment by pbassut** [comment]
There's a pinned issue for this.
