### ISSUE TITLE
Consistent crash when selecting a DB

### ISSUE THREAD

**Issue by guytavor** [sequelpro/sequelpro#3514]
to reproduce:
connect to a local machine via socket
choose a DB via the dropdown.
CRASH
SequelPro 1.1.2 Build 4541 (602e11a) running on Mac OS 10.14.5 (18F203), MySql 8.0.17 (MySQL Community Server - GPL)

**Comment by mytrile** [comment]
Get the latest test build - https://sequelpro.com/test-builds

**Comment by guytavor** [comment]
fixed it, thanks
