### ISSUE TITLE
Unable to report crash, hostname does not exist

### ISSUE THREAD

**Issue by Keydex** [sequelpro/sequelpro#3515]
- Sequel Pro Version: 1.1.2
- macOS Version: 10.14.5
- MySQL Version: 5.6

**Description**
When trying to report a crash, I get this error.

![image](https://user-images.githubusercontent.com/6903446/62556011-a1e07800-b839-11e9-9e33-0451b4940f25.png)

**Steps To Reproduce**
1. Have your app crash (In any known way, in my case opening a new tax in sequel pro and closing it.
2. Reopen sequel pro and report the crash. 

**Expected Behaviour**
I expect the crash report to successfully send.

**Additional Context**

**Comment by direktornswe** [comment]
Same here

**Comment by direktornswe** [comment]
Despite being a year since reported this has not yet been fixed.

**Comment by Kaspik** [comment]
Please see https://github.com/sequelpro/sequelpro/issues/3705
