### ISSUE TITLE
Sequel Pro Crashes on Mojave on 1.1.2 - Update 3116 Thread

### ISSUE THREAD

**Issue by Keydex** [sequelpro/sequelpro#3516]
For application crashes on macOS 10.14 (Mojave) please see issue #3116. ->

I looked at issue #3116 , this crash is still happening and **I can reproduce it on version 1.1.2**. However, you guys closed the discussion of it. I can see that it is tagged waiting release, but it's been two years. Either comment at the very bottom of that chain to just use test builds, or make a note on your site that this release version is unstable for mac mojave.

**For those reading this, the solution is to use the [latest test build](https://sequelpro.com/test-builds).** But this ticket is here because I do not feel that should be the preferred solution.

- Sequel Pro Version: **1.1.2**
- macOS Version: 10.14.5
- MySQL Version: 5.6

**Description**
When you close any tab on sequel pro, the application will crash.

**Steps To Reproduce**
1. Open Sequel Pro on a mac with mojave
2. Open a new tab
3. Close the tab

**Expected Behaviour**
The application shouldn't crash if I close the tab.

**Additional Context**
I have tried disabling night mode on it to see if it fixes anything, it doesn't. And I can reproduce this on 3x macbook pros 2018.

`default write com.sequelpro.SequelPro NSRequiresAquaSystemAppearance -bool no`

**Comment by Keydex** [comment]
This is fixed in the test builds from two months ago, but you should at least comment on the #3116 cause that's the first google result to use the test build. 97c1b85783

But some of us would rather have non-test build released. For example a lot of your users are downloading 1.1.2 on the internet and using it. At least push that fix out as a release or something.

**Comment by mloballer** [comment]
I can also duplicate the same issue after upgrading to Mojave on 1.1.2, I prefer using the non-test build version over the test build, wish they had a fix for this on the non-test build.

**Comment by cyberrranger** [comment]
same problem

**Comment by kleberangotti** [comment]
Happens to me too. But it happens right after I connect to the MySQL, it crashed.
Macos: 10.14.6

**Comment by Jeremy1026** [comment]
@Keydex this really isn't a solution, its a half-hearted workaround.

**Comment by evilsideburns** [comment]
Same problem. Sequel Pro 1.1.2 (build 4541) on macOS Mojave. Crashes every single time I close a tab.

**Comment by stratboy** [comment]
Same problem here

**Comment by JannieT** [comment]
Conspiracy theory: this bug is sponsored by the marketing department of Navicat, TablePlus or DataGrip

**Comment by stratboy** [comment]
> Conspiracy theory: this bug is sponsored by the marketing department of Navicat, TablePlus or DataGrip

HAHA!

**Comment by tgirotto** [comment]
tested @Keydex solution and it works on mojave 10.14.4 [https://sequelpro.com/test-builds](url)

**Comment by JannieT** [comment]
Just posting here to keep stalebot from closing this important issue.

**Comment by stychos** [comment]
@JannieT https://github.com/Sequel-Ace/Sequel-Ace/

**Comment by Kaspik** [comment]
Please see https://github.com/sequelpro/sequelpro/issues/3705
