### ISSUE TITLE
Unable to update users in MariaDB 10.4.1+

### ISSUE THREAD

**Issue by lukewhitt** [sequelpro/sequelpro#3517]
- Sequel Pro Version: Nightly Build 5446 (97c1b857)
- macOS Version: 10.14.5
- MariaDB Version: 10.4.6

**Description**
Using the 'Users' GUI, I am unable to create or update any user details for users in MariaDB 10.4.1+.

**Steps To Reproduce**
1. Ensure MariaDB installation is 10.4.1 or above
2. Open Sequel Pro and attempt to create a new user via the UI

**Expected Behaviour**
You should be able to create a new user via the UI successfully. Other operations such as updating permissions should work within that UI too. 

**Additional Context**
MariaDB as of 10.4.1 have modified the way they structure and store permissions internally. The `mysql.user` table is now a read-only view onto the new table `mysql.global_priv`. When attempting to update the user via the SequelPro UI, it appears the following query is run: 
`UPDATE mysql.user SET max_questions = 0, max_updates = 0, max_connections = 0 WHERE User = '<user>' AND Host = 'localhost';` - this operation fails due to the new read only view.

**Comment by gridsystem** [comment]
For anyone else struggling to google their way to this bug, the exact error from Sequel Pro is 

> Column 'max_questions' is not updatable

**Comment by gridsystem** [comment]
This issue also seems to leave me unable to add privileges to users, which is pretty much all I normally use Sequel Pro for 🤷‍♂

**Comment by SenH** [comment]
It's fixed in  PR #3504
You can clone & compile this repo ftm: https://github.com/ahoz/sequelpro

**Comment by lukewhitt** [comment]
@SenH Apologies, I did perform a search but didn't find any references to Maria 10.4.1+

**Comment by crankeye** [comment]
Visit this link if you are having trouble compiling @SenH 's branch:
https://github.com/sequelpro/sequelpro/issues/3582
