### ISSUE TITLE
"unknown error number" when attempting to connect via SSL with CA cert

### ISSUE THREAD

**Issue by jwhazel** [sequelpro/sequelpro#3520]
- Sequel Pro Version: Nightly build 5446
- macOS Version: 10.14.6
- MySQL Version: 8.0.17 via Brew

**Description**
When attempting to connect via SSL with a CA cert issued, it results in a Connection failed! dialog that states `MySQL said: SSL connection error: unknown error number`

**Steps To Reproduce**
1. Populate connection info for an SSL instance
2. Make sure to include the CA cert in the corresponding field

**Expected Behaviour**
The program should connect to the instance or at least provide a more verbose error.

**Additional Context**
This was discovered while testing Digital Oceans new managed MySQL service that was just released: https://www.digitalocean.com/docs/databases/mysql/. The connection params aren't anything exotic other than maybe the port number.
```username = ***
password = ***
host = db-mysql-nyc1-71474-do-user-****-0.db.ondigitalocean.com
port = 25060
database = defaultdb
sslmode = REQUIRED
```

I've managed to successfully connect to it using MySQL cli, TablePlus, and Querious.

**Comment by Gys** [comment]
Came here for exactly the same issue. I can confirm connect is also successful in MySQLWorkBench (latest) and through some standard Golang code.

**Comment by shornuk** [comment]
Same here

**Comment by katimari** [comment]
same issue here

**Comment by StanBarrows** [comment]
**same here**
![image](https://user-images.githubusercontent.com/10268813/64131561-a745c980-cdc9-11e9-95ac-829fdb86df01.png)

**Comment by code91** [comment]
same here

**Comment by craigpearson** [comment]
Same here

**Comment by goldwaterenterprises** [comment]
Same here

**Comment by spham** [comment]
same here

**Comment by npalmqvist** [comment]
+1

**Comment by micheleriva** [comment]
Same here

**Comment by michaelotoole** [comment]
+1

**Comment by jderdock** [comment]
+1

**Comment by jessety** [comment]
Same here

**Comment by keyban** [comment]
same here

**Comment by brianherbert** [comment]
Ditto.

**Comment by nateSchroader** [comment]
+1

**Comment by egbertwietses** [comment]
+1

**Comment by liamcharmer** [comment]
+1

**Comment by Asparagirl** [comment]
+1

**Comment by tjaworski** [comment]
+1

**Comment by lyudad** [comment]
+1

**Comment by lyudad** [comment]
I resolve issue by upgrate Workbench to version 8

**Comment by Gys** [comment]
@lyudad Mysql 8 had seemingly some changes which broke with previous implementations. There are alternatives for Sequal Pro that implemented those changes and therefore will work. Mysql Workbench is obviously one of them ;-) I use it also and sometimes alternatively TablePlus.

But I prefer to keep working with Sequel Pro so I hope those needed changes will make it here some day as well. I would not mind if that is as a payed upgrade.

**Comment by berkayk** [comment]
Same here.

**Comment by gmkey** [comment]
MariaDB 10.4 same issue

**Comment by hesa2020** [comment]
Same issue also on digital ocean.

**Comment by Gys** [comment]
@hesa2020 It is a consequence of the mysql version (8+) , so it will be with any provider and even installed locally.

**Comment by remiwinks** [comment]
I've managed to connect to my DO MySQL 8 by setting up an SSH tunnel between my local machine and DO server, however, I had to download the nightly test build of Sequel Pro for this to work.

**Comment by liamcharmer** [comment]
> I've managed to connect to my DO MySQL 8 by setting up an SSH tunnel between my local machine and DO server, however, I had to download the nightly test build of Sequel Pro for this to work.

Can confirm the SSH Tunnel works perfectly, sadly trying to connect directly to it still doesn't work but will just remember to have to run the SSH Tunnel everytime. THANK YOU REMI!

**Comment by theorbital** [comment]
Same issue for me

**Comment by OnArs** [comment]
The same issue also on digital ocean!

**Comment by douglasjunior** [comment]
Any updates on this?

**Comment by douglasjunior** [comment]
Just changed to Sequel Ace and everything works! 

https://github.com/Sequel-Ace/Sequel-Ace

**Comment by tjaworski** [comment]
ok, as the guy above said, you can use Sequel-Ace, but I did get it to work with the nightly build:

<img width="208" alt="Screen Shot 2020-08-21 at 6 18 46 PM" src="https://user-images.githubusercontent.com/6331880/90939828-c5da1180-e3da-11ea-99d6-72a56d38b654.png">
 
but you will have to create a "Legacy – MySQL 5.x" user on DigitalOcean's mysql db:

<img width="1238" alt="Screen Shot 2020-08-21 at 6 13 43 PM" src="https://user-images.githubusercontent.com/6331880/90939619-33d20900-e3da-11ea-88e5-9668a75ab84f.png">

make sure the Connect using SSL is turned off:

<img width="526" alt="Screen Shot 2020-08-21 at 6 16 07 PM" src="https://user-images.githubusercontent.com/6331880/90939784-ac38ca00-e3da-11ea-8916-38708b1f2b4c.png">

and you're in:

<img width="1187" alt="Screen Shot 2020-08-21 at 6 22 26 PM" src="https://user-images.githubusercontent.com/6331880/90940005-59134700-e3db-11ea-85e5-18f132adad25.png">

Unfortunately, it does crash from time to time.

stay safe everyone!

**Comment by Gys** [comment]
The regular build (not nightly) should work fine with any 5.x mysql database? And in my experience the regular build is less crash prone (the nightly is probably not merged for a reason).

**Comment by douglasjunior** [comment]
I see no reason to insist on Sequel Pro, as the Sequel Ace project is a fork of this one and is constantly being updated.
