### ISSUE TITLE
UI: Dark mode and colours not compliant

### ISSUE THREAD

**Issue by aledexter** [sequelpro/sequelpro#3521]
MACOS build 5446 Dark mode on

It is not an important ISSUE But i want report that when using the dark mode the colours of the favorites have a contrast too low with the white text and it is not compliant. 

I attach an image for example where we use the dark theme and use the color to highlight the favorites. The colour are pastel and very clear so the white of the text it's not readable.

<img width="339" alt="1" src="https://user-images.githubusercontent.com/11591259/65070224-83b77d00-d98c-11e9-908d-06e2a1cc5ebd.png">

We could use tools as 
https://contrastchecker.com/
or similar to calculate the perfect contrast but i have not the real HEX code of the favoruties color. I suppose that we can make 2 ways of resolution:

When in dark mode

1) Leave the text of favorites white but **change the colours of the favorites** with darker ones (checking their compliance with tools like contrastchecker) .
or
2) Leave the colours of the favorites as is but, when one favorites is coloured, **CHANGE the colour of the text in black** instead of white. That should be the fastest resolution imho.

<img width="334" alt="2" src="https://user-images.githubusercontent.com/11591259/65069823-c75db700-d98b-11e9-80d1-a2691130bbd0.png">

Thank you

**Comment by aledexter** [comment]
I see now that there is yet a similar request
 #2485

**Comment by rockymontana** [comment]
Love that your issue is about colors not being readable and then use an unreadable color to point out what color to use (red text stating that black is readable). Oh the irony 😘 😂

**Comment by aledexter** [comment]
> Love that your issue is about colors not being readable and then use an unreadable color to point out what color to use (red text stating that black is readable). Oh the irony 😘 😂

That's so damn true :) I uploaded a better image
