### ISSUE TITLE
Database import progress bar does not update unless you unfocus and refocus on the window

### ISSUE THREAD

**Issue by mgbellaire-mc** [sequelpro/sequelpro#3525]
These two images are from one single import process. The first one is a few seconds after the initial process was started and then the second is when I "command-tabbed" away from the window and then went back. It always updates when I do that, but never when I don't lose focus on the window. Also, notice on the second image that the import is nearly done and the progress bar is only about 1/3rd full.

<img width="1380" alt="Screen Shot 2019-09-02 at 9 40 06 AM" src="https://user-images.githubusercontent.com/52426566/64118520-d3c7fa00-cd65-11e9-8703-19bc994f5647.png">
<img width="1380" alt="Screen Shot 2019-09-02 at 9 40 52 AM" src="https://user-images.githubusercontent.com/52426566/64118521-d3c7fa00-cd65-11e9-9045-b4fff2267582.png">

**Comment by philippechevieux** [comment]
I'm facing the same issue. Does someone has an idea what could cause this ?
