### ISSUE TITLE
When closing one of the connection tabs on mac, Sequel pro crashes

### ISSUE THREAD

**Issue by decklord** [sequelpro/sequelpro#3527]
I'm using Sequel Pro 1.1.2 Build 4541 (602e11a).
When I close a tab, Sequel Pro crashes.
https://imgur.com/a/F4NPt9x

**Comment by Hashymawan** [comment]
> I'm using Sequel Pro 1.1.2 Build 4541 ([602e11a](https://github.com/sequelpro/sequelpro/commit/602e11a4143305eac04110b390b035e2a3e1b996)).
> When I close a tab, Sequel Pro crashes.
> https://imgur.com/a/F4NPt9x

facing same issue

**Comment by xealgo** [comment]
Same thing on my Mac (and my last Mac). Every single time. It doesn't even matter if I'm connected to a database or not. If I close a tab, it crashes. It's been happening for at least the last 2 years I've been using it.

**Comment by rockymontana** [comment]
Use the nightly builds / betas. They've fixed it there.
