### ISSUE TITLE
Format the sql query

### ISSUE THREAD

**Issue by amarjeetanandsingh** [sequelpro/sequelpro#3530]
Hi
I tried to format the sql query in the Query tab, but cannot see any option.

Anybody can help??

**Comment by peierlong** [comment]
Click `Menu > Bundle > Bundle Editor > Input Filed > Format > Format Sql`

Like this

![image](https://user-images.githubusercontent.com/18136549/64665131-fd7ad280-d483-11e9-8149-eca09f9c9c93.png)

by: https://github.com/andialbrecht/sqlparse

**Comment by peierlong** [comment]
```python
#![your python path]
#coding=utf-8
import sqlparse
import sys
sql = sys.stdin.read()
statements = sqlparse.split(sql)
first = statements[0]
print(sqlparse.format(first, reindent=True, keyword_case='upper'), end = '')
```

**Comment by amarjeetanandsingh** [comment]
Hi @peierlong 
Thanks for your response.

I did the changes but it throws bash error as command not found.
<img width="421" alt="Screenshot 2019-09-11 at 8 52 02 AM" src="https://user-images.githubusercontent.com/9883805/64665824-a3711180-d471-11e9-9fb1-786fbf8611bd.png">
<img width="902" alt="Screenshot 2019-09-11 at 8 51 01 AM" src="https://user-images.githubusercontent.com/9883805/64665841-aff56a00-d471-11e9-8f84-5d1bc532dc73.png">
