### ISSUE TITLE
Question - When are you going to do another release?

### ISSUE THREAD

**Issue by bakeruk** [sequelpro/sequelpro#3532]
Hi Guys,

When are you going to do another release of Sequal Pro?

The last release was in 2016. Is there a major change that you are working on?

Also is there a road map for releases etc?

Many thanks,

Luke

**Comment by dcposch** [comment]
this kind of hurts to watch.

you have a popular open source project, totally in ways that have been fixed for about a year... but the last release was 3+ years ago and the maintainers refuse to create a new release. 

it's puzzling. see discussion from April 2018: https://github.com/sequelpro/sequelpro/issues/3034

@bakeruk in the meantime you can run a nightly build here: https://sequelpro.com/test-builds

works with MacOS Mojave, supports MySQL 8

**Comment by vstokarev** [comment]
This project is dead. Just accept it and move on. Although I must admit I still use it every day, as I couldn't find any replacement. TablePlus, DataGrip, others - they all are just simply not as good as SequelPro. But after couple years of following this repo and reading discussions I already lost my hope and I don't think they will ever release an update.
