### ISSUE TITLE
Inline Filter: Set focus to value input after the field or condition inputs change

### ISSUE THREAD

**Issue by thomasruns** [sequelpro/sequelpro#3534]
When a user changes either the field or condition inputs on an inline filter, set focus to value input.

If a user just changed either of those dropdowns, there's a really good chance the next thing they want to do is set the value for the filter so it just makes sense to automatically set the focus to that input.

**Comment by ericpurwaka** [comment]
+1 on this. The older version worked like this, which was nice.

I'd like to add: open the filter by default, again the older version worked like this too

**Comment by cl-lc** [comment]
+1
