### ISSUE TITLE
1.2 and Pull Requests

### ISSUE THREAD

**Issue by Hubertnator** [sequelpro/sequelpro#3536]
The excuse for not releasing a 1.1.3 / 1.2 Beta / 1.2, is "not having enough time to focus on the last bugs" (#3385, #3034) 
However, if we look at the Pull Requests tab, we have a lot of pull requests that do not have conflicts with the main branch, and fix issues. This has been also mentioned in #3051. Could someone explain me why we haven't merged these?

**Comment by stychos** [comment]
Sad, but I think it's dead. Don't see at my badge here, it's earned accidentally for a single line of code and I'm not related to the team. Hope I wrong.

**Comment by Hubertnator** [comment]
Yes I know, I read the whole thing in #3385 :)

The thing is @stychos that for some odd reason they just left the project. And yet @Kaspik still claims that 1.2 is still a valid project!
You probably don't have credentials to make a release, but I don't know what to say, when I see these:
#2936 
#2957 
#2947 
As these pull requests do solve issues, have no conflicts with other branches, and yet they still haven't merged these. That just proves that this project is not being developed.

@redcapua did some amazing work but it wasn't merged. Yet the SP team say that if you want to help make a pull request! Yeah sure, I'll make one, with no conflicts, but it's still not going to be merged! Comedy!

If anyone from the SP team wants to prove me wrong, please merge the following PRs or justify wy we haven't merged these to the main branch.

**Comment by stychos** [comment]
Here is no maintainer, nuff said 😐

**Comment by Hubertnator** [comment]
I mean I just checked the test build page, and found that he was noted there 6 months ago...

So the only people here are @dmoagx and @stuconnolly? At leat it looks like it.
