### ISSUE TITLE
Closing tabs will cause the app to break and completely close

### ISSUE THREAD

**Issue by ermamud** [sequelpro/sequelpro#3540]
when having multiple tabs open, after closing one of them the app crashes causing to completely close and lose everything you are doing

**Comment by danaquila** [comment]
I will do whatever is needed to help debug/test this. I concur that it crashes on every tab close, whether triggered by user click or by connection timeout.

**Comment by lomo1** [comment]
@ermamud , i had same issue on osx 10.14.6, i re-install sequal pro (Build: 5446 [97c1b85783](https://sequelpro.com/builds/Sequel-Pro-Build-97c1b85783.zip) ), you can download it from https://sequelpro.com/test-builds, and i tried it out, it's ok now
