### ISSUE TITLE
Connection tabs are not displaying properly with dark mode.

### ISSUE THREAD

**Issue by nathan-fiscaletti** [sequelpro/sequelpro#3543]
- Sequel Pro Version: Snapshot Build (97c1b857)
- macOS Version: Mojave 10.14.5

**Description**
Connection tabs are not displaying properly with dark mode.

**Additional Context**

![image](https://user-images.githubusercontent.com/1699763/65447004-3d827380-ddfb-11e9-9899-a200057ede55.png)

**Comment by nathan-fiscaletti** [comment]
Don't close this please, i would like my dark tabs :(

**Comment by stychos** [comment]
@nathan-fiscaletti check it out https://github.com/Sequel-Ace/Sequel-Ace, this trouble is already fixed in it

**Comment by Kaspik** [comment]
Please see https://github.com/sequelpro/sequelpro/issues/3705
