### ISSUE TITLE
Broken UI when switching monitors

### ISSUE THREAD

**Issue by ericpurwaka** [sequelpro/sequelpro#3554]
- Sequel Pro Version: Build 5446
- macOS Version: Mojave

Switching between monitors with different resolution or plugging-unplugging from external monitor would break the Sequelpro rendering: seems like a portion of the top part is cut off, which means tabs and some of the tables are no longer accessible.

Steps:
1. Connect to external monitor
2. Move Sequelpro to the external monitor
3. Disconnect from external monitor -> Sequelpro UI is broken
4a. Re-connect to the same monitor -> Sequelpro UI is working again
4b. Close then re-open Sequelpro -> Sequelpro UI is working again

**Comment by mmplanet** [comment]
👍 this is super frustrating.
