### ISSUE TITLE
Sidebar width inconsistent in macOS Catalina

### ISSUE THREAD

**Issue by brennenberkley** [sequelpro/sequelpro#3558]
- Sequel Pro Version: Build 5446 (97c1b857)
- macOS Version: 10.15 (Catalina)
- MySQL Version: 5.7.25

**Description**
When opening a new window or tab in macOS Catalina, the sidebar width is not saved. It generally takes up about 2/3 of the window and has to be resized every time to be able to see the main content.

**Steps To Reproduce**
1. Open a new window or tab
2. Observe that the sidebar takes up >50% of the window width

**Expected Behaviour**
The sidebar is the same width as the last window I opened, which is what happened in macOS Mojave

<img width="1441" alt="Screen Shot 2019-10-10 at 10 17 35 AM" src="https://user-images.githubusercontent.com/28460318/66591171-32dc1400-eb47-11e9-9060-184bdad8cbae.png">

**Comment by gboudreau** [comment]
I found the most hackish way I ever saw to fix this: https://github.com/gboudreau/sequelpro/commit/55bfcc5b4ab441ab32ee4b251cbd73751fa5c155

I have no idea why that works!! I tried to debug, but all I could find was that the values saved, and the values restored, resulted in a different layout... And for some reason, a 1.88 multiplier fixed the issue!

**Comment by guice** [comment]
Now if there was just some way to get this into a night (that's failing) build? I'm having the same annoyances. It's bugging me.

**Comment by gboudreau** [comment]
> Now if there was just some way to get this into a night (that's failing) build? I'm having the same annoyances. It's bugging me.

If you are comfortable running a build created by a random guy on the internet (me), you can use this one: [Sequel Pro-3558.zip](https://github.com/sequelpro/sequelpro/files/3798491/Sequel.Pro-3558.zip) (zip password is `patate 123`).

**Comment by filiplikavcan** [comment]
Could it somehow related to new permissions that many apps keep asking me to grant? Could this be because SequelPro cannot save the width of the sidebar? I'm not familiar with SequelPro development so this is just a wild guess.

**Comment by jaspertandy** [comment]
Is there any word on getting this into a test build? This is such a minor annoyance, but by the end of the day it has me raging!

**Comment by dpslwk** [comment]
even when using @gboudreau versions when I hit cmd-t to open a new tab the sidebar width grows by an amount until its at 50% width

screen recording here https://www.dropbox.com/s/eo2ddt5ho5unkty/Screen%20Recording%202019-12-20%20at%2002.04.25.mov?dl=0

**Comment by bcalik** [comment]
This is driving me crazy. I'm about to switch some other app.

**Comment by waiylgeek** [comment]
> This is driving me crazy. I'm about to switch some other app.

Same here, I'm switching to Table Plus!

**Comment by ablyeom** [comment]
Hi, I have similar error.
Unexpected layout margin above sidebar and main area. see my screenshots.

![image](https://user-images.githubusercontent.com/2979043/71797417-5e609300-3091-11ea-852f-35a29be2761a.png)

**Comment by frankos44** [comment]
Try this:

1) Click "Sequel Pro" -> 'Hide Others"
2) Close completely
3) Click "Sequel Pro" -> "Show All"
4) Resize split window
5) Close completely

After that it seems fine for me.

**Comment by jorenvh1** [comment]
Any update on this getting into a nightly build? Really annoying me 😛

**Comment by alexandrosharvey** [comment]
Receiving the same issue for me on macOS Catalina 10.15.3 (19D76), Sequel Pro 1.1.2 Build 4541 (602e11a). Also, the resize happens in chunks. If you drag the sidebar to the smallest width and close Sequel pro down and re-open the sidebar will be bigger. Repeat and the sidebar grows even more. Repeat until sidebar grows to half the window.

**Comment by IgorErmakov** [comment]
Have the same issue. 
Love the app, but this thing makes me crazy..
it it's still crashes if I close the tab (mysql 5.7 only)

**Comment by guice** [comment]
Worth mentioning, this appears to have been a bug in Catalina as it seems to have auto-resolved itself. At least for me...

**Comment by ShawnConn** [comment]
Also noting I've seen the issue in Catalina and it is no longer an issue.

**Comment by Jason-Morcos** [comment]
Still seeing this issue on Catalina, myself. I know my coworker is still experiencing it too, latest OS and nightly.

**Comment by bcalik** [comment]
I haven't seen this issue for a few months. I think its also fixed for me too.

**Comment by rikiless** [comment]
I stopped using Sequel Pro (Night Build) because of this. But I can confirm now problem has been fixed. macOS 10.15.5.

**Comment by Kaspik** [comment]
We are aware of this, but it happens randomly. Also, please see https://github.com/sequelpro/sequelpro/issues/3705
