### ISSUE TITLE
MacOSCatalina - SequelPro crashes on 'close tab'

### ISSUE THREAD

**Issue by steviepitman** [sequelpro/sequelpro#3565]
On pressing <command> and the letter W (i.e. the 'close tab' command) Sequel Pro completely crashes when using Catalina.

**Comment by at0dd** [comment]
@steviepitman there are other open issues for this (see #3116) and it is fixed whenever 1.2 releases. You can download test builds here: https://sequelpro.com/test-builds

**Comment by FranckyLFS** [comment]
I confirm the test build does not crashed when a tab is closed on Catalina 10.15.3.

**Comment by fari-99** [comment]
had the same problem
sequel pro v1.1.2 build 4541
catalina v10.15.6

how to reproduce
1. create one tab, connect to db
2. create another tab, connect to db (the same is ok too)
3. create another tab, connect to db (the same is ok too)
4. close one tab. sudden crash.

**Comment by milanbavishi** [comment]
Same issue
sequel pro v1.1.2 build 4541

- creating one or more tab works
- close any one tab sequelpro crashes

same as @fari-99

**Comment by milanbavishi** [comment]
Okay I saw the pinned issue #3705 I guess time to move to Sequel Ace
