### ISSUE TITLE
Crashing when connecting to AWS mysql db

### ISSUE THREAD

**Issue by jasonloeve** [sequelpro/sequelpro#3569]
- Sequel Pro Version: 1.1.2 build 4541
- macOS Version: Mojave v10.14.6

**Description**
Been trying for a couple week now to connect to AWS mysql databases, connection succeeds but crashes when opening the database.

**Error Details**

NSInvalidArgumentException

-[_NSInlineData isEqualToString:]: unrecognized selector sent to instance 0x60000026eea0

(
	0   CoreFoundation                      0x00007fff45a6a2fd __exceptionPreprocess + 256
	1   libobjc.A.dylib                     0x00007fff70138a17 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff45ae4106 -[NSObject(NSObject) __retain_OA] + 0
	3   CoreFoundation                      0x00007fff45a0c18f ___forwarding___ + 1485
	4   CoreFoundation                      0x00007fff45a0bb38 _CF_forwarding_prep_0 + 120
	5   Sequel Pro                          0x00000001000587cd -[SPTablesList updateTables:] + 1338
	6   Sequel Pro                          0x00000001000469c5 -[SPDatabaseDocument _selectDatabaseAndItem:] + 454
	7   Foundation                          0x00007fff47c0d5c2 __NSThread__start__ + 1194
	8   libsystem_pthread.dylib             0x00007fff71afa2eb _pthread_body + 126
	9   libsystem_pthread.dylib             0x00007fff71afd249 _pthread_start + 66
	10  libsystem_pthread.dylib             0x00007fff71af940d thread_start + 13
)

**Comment by micaelehn** [comment]
Having this exact same issue. It works when connecting to an AWS Aurora instance (running MySQL 5.7), but not to an RDS instance running MySQL 8.0.16.
