### ISSUE TITLE
Offer to pay for updates to Sequel Pro to support latest versions of OS X

### ISSUE THREAD

**Issue by thomasgriffin** [sequelpro/sequelpro#3571]
I've already emailed, but in case I cannot get in touch, I wanted to drop an issue here. Sequel Pro is a big part of the development process for many people. The UI is good and works better than other clients for Mac. As is well known, the last couple versions of OS X have made working with Sequel Pro much more unpleasant.

My offer: I want to pay you to fix the app and make it work on latest versions of (Catalina and below) as a benefit to the greater developer community.

Again, I've already emailed you about this so we can discuss further. I assure you this is a serious offer!

For all those reading, give a thumbs up so this gets further attention. Thanks!

**NOTE:** To clarify, this offer is for a large sum, not just a "I want to pay $99/yr" type of offer (although I would be happy to pay $xx/yr if made available).

**Comment by xhezairi** [comment]
I did thumbs up the post, and I'd happily follow the initiative to becoming a paying customer, although in all honesty, I've switched to TablePlus since about a year now, the enormous SequelPro crashes with newer MySQL versions were simply blocking me from making any real progress.

Fingers-crossed this call won't fall on deaf ears.

**Comment by danielswe88** [comment]
Btw @thomasgriffin did you try Sequel Pro Nightly builds? I downloaded the latest one. Works on Mojave, doesn't crash when you close tabs and it has dark theme. Haven't tested on Catalina though.

Is Sequel Pro totally not working on Catalina?

**Comment by thomasgriffin** [comment]
@danielswe88 is this on a different branch than master? Master does not build on Catalina.

And yes, Sequel Pro does not work at all on Catalina with download from website.

**Comment by danielswe88** [comment]
@thomasgriffin I haven't upgraded my work mac to catalina yet... Do you mind testing the nightly build on catalina and post the result? Maybe that will work for you also...?

**Comment by thomasgriffin** [comment]
@danielswe88 the latest complete nightly build does appear to work on Catalina.

Why is this not a general release that is available to download? Puzzling if it fixes some of these bugs and is available.

**Comment by danielswe88** [comment]
@thomasgriffin I have no idea why it is a general release, I guess it has some flaws which makes it not beeing a general release. But for me it fixed two things on Mojave. And the latest nightly build is released 4 months ago (a while before Catalina was released to the big audience).

But yeah... I would totally buy if they released some kind of Sequel Pro 2.0 which would have a one time fee. It is the best MySQL client I have tried on mac.

**Comment by tancredolt** [comment]
Sequel it's been updated once in a while, in Catalina have a lot of crashes. If have it a paid version that works properly I think that a lot of people would be happy in paying for a license.

**Comment by vstokarev** [comment]
It was already discussed a year or so ago here. One of the developers replied that "the problem is not in money". We'll probably never know what the actual problem is.

**Comment by tancredolt** [comment]
The thing is… the issues are growing faster than the solutions… and nobody say anything about!

**Comment by vstokarev** [comment]
Most of the issues are related to crashes. Authors even pinned two most popular issues on top of the page, but some people don't seem to bother themselves with checking the list of latest issues thought. Some of the problems were solved in nightly builds and I saw people asking maintainers many times why did they refuse to release an update. They said they won't release it until they close all critical issues. Issues were not closed, update was never released. According to this page there's still at least one critical bug left: https://github.com/sequelpro/sequelpro/projects/2. And also it looks like maintainer cannot release an update on his own, because he doesn't have enough permissions? So, like I said, it's hard to say for sure what exactly is going on with this project.

**Comment by diego-vieira** [comment]
As many of you know, Vue creator, Evan You, works full time on Vue with the help of donations via his Patreon.

https://www.patreon.com/evanyou

I can see this working for Sequel Pro as long as a developer is willing to accept the offer of being paid to work full time on Sequel Pro.

**Comment by diego-vieira** [comment]
@dmoagx just wondering if the above is something you would be interested in.

Many thanks

**Comment by dmoagx** [comment]
@diego-vieira I know the donation amounts we received back when this project (and the Mac opensource community as a whole) was much more healthy and based on that I don't believe this could work.
Also I have personal reasons why this is not an option for me.

**Comment by diego-vieira** [comment]
@dmoagx thank you for taking the time to give us your feedback. For some projects, there comes a time when it's not enjoyable as it used to be when you wrote your first lines of code or personal circumstances change (family, getting older, job, moving to another place, etc). I truly understand your position and thank you for donating your time to build such a wonderful tool that has helped millions of fellow developers out there like me.

**Comment by rubenjleon** [comment]
@dmoagx Thanks for your work on this project!  It has been truly great software achieving something that many other DB tools haven't accomplished in terms of being a super fast and effective, yet easy to use db tool.  More importantly, this tool brought functionality to the Mac platform giving developers an opportunity to develop on the Mac.

**Comment by boyanraichev** [comment]
Sequel Pro was indeed one of the best pieces of software on Mac and hands down the best mysql db manager on any OS. None of the rest comes even close. And it needs very little to continue to be so good for years ahead. I really hope the project owners find a bit of time to fix the few bugs and make a new release. As many others have also stated here - I would be happy to pay for this software, I have paid for software that is not even remotely as good as this one.

**Comment by dmoagx** [comment]
@thomasgriffin If you are interested we could probably arrange something through my employer. But I'll be upfront: that would result in at least a five figure amount

**Comment by auckenox** [comment]
@dmoagx maybe you could arrange something like a croudfunding? (wouldn't hurt to try?)
i can't pay a 5 figure amount, but i'm more than happy to pay for this amazing software!
i'm one of the donators that donated (nearly) every month, because i really love Sequel Pro and i use it everyday.

**Comment by vstokarev** [comment]
I'm paying for DataGrip subscription right now, but I'd be glad to pay for Sequel Pro instead if it would allow be to do my stuff again (Sequel Pro is like 10-20 times faster). I like the idea of croudfunding  and I'd definitely join it.

**Comment by thomasgriffin** [comment]
I made a follow-up to this topic here so it does not get lost: https://github.com/Sequel-Ace/Sequel-Ace/issues/60
