### ISSUE TITLE
Instability with macOS Catalina

### ISSUE THREAD

**Issue by theovln** [sequelpro/sequelpro#3577]
Hi, 

Thanks for the great work you've been doing ! Just wanted to let you know that there are a lot of bugs on the latest release of MacOS, Sequel is very often crashing.

Thanks a lot,

Cheers

**Comment by frumbert** [comment]
I'm using Catalina and the sequelpro build 5446 (97c1b857) and it opens like this

![Sequel_Pro_and_Instability_with_macOS_Catalina_·_Issue__3577_·_sequelpro_sequelpro_·_GitHub_and_Fwd__PracticeHub_Moodle_overview_—_tim_stclair_coursesuite_com__All_Mail__and_css_—_ssh_root_avideelearning_com_—_110×40](https://user-images.githubusercontent.com/592257/67725703-6bc92380-fa37-11e9-8578-b519b12330d1.jpg)

I can resize the middle pane, but it always opens that way, it won't remember that setting

Other than that certainly far more stable that the most recent release listed on the site.
