### ISSUE TITLE
Sidebar resize

### ISSUE THREAD

**Issue by kevmz** [sequelpro/sequelpro#3581]
- Sequel Pro Version: 1.1.2
- macOS Version: 10.15
- MySQL Version: 

**Description**
When open SequelPro the sidebar size takes the half screen. 

**Steps To Reproduce**
1. Open Sequel Pro 
2. Make Sequel Pro full screen size
3. Sidebar takes half of the screen.

**Expected Behaviour**
Sidebar should have fixed size value, despite of resize of window

**Additional Context**

**Comment by simonl65** [comment]
Yup - happens for me too.
I tried cloning the latest version and building in XCode, but that fails horribly with 13 errors about being unable to find various frameworks in the keychain [FeedbackReporter, Growl, PSMTabBar, QueryKit, SPMySQL, ShortcutRecorder, Sparkle, UniversalDetector, Sequel Pro.qlgenerator, SequelProTunnelAssistant, Sequel Pro.app]

**Comment by frumbert** [comment]
Build 5446 (97c1b857)

Panes seem to open as percentages - tables / main are 50% (super noticable when you open on a 4k display). Resizing works, but doesn't remember after app quits.

The Table Information pane has a percentage-based size too - seems about 33% high, without the ability to resize. Certainly never needs all the space allocated on my screen; should be fixed height.
