### ISSUE TITLE
Cannot code-sign with XCode 11.1

### ISSUE THREAD

**Issue by robertoschwald** [sequelpro/sequelpro#3582]
- Sequel Pro Version: master
- macOS Version: 10.14.6
- MySQL Version: irrelevant

**Description**
Cannot compile current master (f0987c53) due to Code Signing failing.

xx/Library/Developer/Xcode/DerivedData/sequel-pro-gcndvbczphiafnbvgdgsluvfemiq/Build/Products/Debug/Sequel Pro.app: 
code object is not signed at all
In subcomponent: xx/Library/Developer/Xcode/DerivedData/sequel-pro-gcndvbczphiafnbvgdgsluvfemiq/Build/Products/Debug/Sequel Pro.app/Contents/Frameworks/ShortcutRecorder.framework
Command CodeSign failed with a nonzero exit code

**Steps To Reproduce**
1. Clone repo
2. Open in XCode 11.1
3. Click "run" button.

**Expected Behaviour**
Project compile and signing is successful

**Additional Context**
None known. This is very bad currently, as Sequel Pro does not work with MariaDB 10.4.1+ due to changed user table structure there. The fixed fork mentioned in #3517 is also affected (its based on 97c1b857 , so the problem seems to exist for a longer period.

Tried on 2 different iMacs with same macOS and XCode versions.

**Comment by robertoschwald** [comment]
Seems the frameworks are not code signed automatically. When I code sign them manually, it works.

**Comment by crankeye** [comment]
For anyone who can't find how to change "Embed without Signing" to "Embed & Sign":
<img width="1258" alt="sequel-pro_xcodeproj" src="https://user-images.githubusercontent.com/588934/71707431-08e16900-2da7-11ea-8866-61fcb83f8f3a.png">
