### ISSUE TITLE
crash when i close a tab

### ISSUE THREAD

**Issue by gongchangyou** [sequelpro/sequelpro#3585]

**Comment by gongchangyou** [comment]
macos Catalina
version 10.15

**Comment by direktornswe** [comment]
Yea same here, Mojave 10.14.6 here.

**Comment by davbru71** [comment]
Same here, solved with @zzeligg suggestion.

**Comment by CuteGEM** [comment]
But @zzeligg 's version doesn't have quick query on the top of table. ToT.

**Comment by Kaspik** [comment]
Please read about the future in new topic - https://github.com/sequelpro/sequelpro/issues/3705
