### ISSUE TITLE
Application crashes where closing tab

### ISSUE THREAD

**Issue by StephaneRodrigues** [sequelpro/sequelpro#3586]
Hi!
Every time I close a tab, Sequel Pro crashes.
Thanks for your help !
Version 1.1.2
Mac OS Mojave 10.14.6

**Comment by davbru71** [comment]
Same here, solved with

https://github.com/sequelpro/sequelpro/issues/3585#issuecomment-548506314

**Comment by newfield86** [comment]
I'm sorry but that is not a proper solution imho. A nightly build can change any moment, so I prefer to see a stable version fix for this annoying issue 😅

**Comment by Kaspik** [comment]
Please read about the future in new topic - https://github.com/sequelpro/sequelpro/issues/3705
