### ISSUE TITLE
App Crashing on Close

### ISSUE THREAD

**Issue by rikdavis** [sequelpro/sequelpro#3588]
When is someone going to actually fix this issue with the entire app crashing upon closing a connection window or tab? This is seriously getting old.

**Comment by martiendt** [comment]
Yeah, they didn't release new stable build for long time, you can use latest test build https://sequelpro.com/builds/Sequel-Pro-Build-97c1b85783.zip it's works well for me

**Comment by rikdavis** [comment]
Sounds to me like the owner/developer needs to relinquish control of the
code to someone that will take far better care of a project that many
people find so useful. Seems a pity to let this just fall to the wayside
like this.

**Comment by rubenjleon** [comment]
Well I happen to think these developer(s) are gold.  It's great software and probably wouldn't be the same under different hands.

**Comment by Kaspik** [comment]
Please read about the future in new topic - https://github.com/sequelpro/sequelpro/issues/3705
