### ISSUE TITLE
window closes, when closing the last tab

### ISSUE THREAD

**Issue by Nedudi** [sequelpro/sequelpro#3591]

**Comment by martiendt** [comment]
you can try latest test build https://sequelpro.com/builds/Sequel-Pro-Build-97c1b85783.zip
it's run well for me

**Comment by craighooghiem** [comment]
Been reported 1000 times

**Comment by CarlosMGomez** [comment]
This is fixed on the nightly builds. The maintainer hasn't cut a new release in years, so don't expect it to hit mainline soon.

Link: https://sequelpro.com/test-builds
Link (from another issue): https://sequelpro.com/builds/Sequel-Pro-Build-97c1b85783.zip
