### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by zomars** [sequelpro/sequelpro#3592]
I'm trying to open discussion for this topic. And if it is, are there any alternatives?

**Comment by antelle** [comment]
Looks like it's abandoned, unfortunately. A lot of latest issues don't have labels or comments from authors, and some fixes of crashes like [this one](https://github.com/sequelpro/sequelpro/issues/3116) are not released, although they're fixed in test builds.

Take a look on alternatives [here](https://www.quora.com/What-is-the-best-MySQL-client-for-Mac-OS-X-or-Windows), some of them are quite good, however I still can't find a good one that would work as good as Sequel Pro with my setup. It's a pity that such a project is dead.

Also: #3532, #3571, #3485

**Comment by jpomykala** [comment]
Try MySQL Workbench it's not that bad.

**Comment by Crysis21** [comment]
Unfortunately I had to switch yo MySQL Workbench also, but it sucks big time compared to SequelPRO. It has way more features than what I need but it's not as practical sa SequlPRO. It's a pity this project it's abandoned.

**Comment by robertoschwald** [comment]
No reaction from the devs to anything.

- 36 pending PRs (some of them are critical)
- over 1000 open issues, and last release in 2016. 

Maybe it's really time for a fork.

**Comment by auckenox** [comment]
sadly, i really think this project is abandoned.
I use [TablePlus](https://tableplus.com/) now, it costs 59$/year. (per seat)
I donated more than 59$/year for SequelPro.
so long, Sequel Pro 😶

**Comment by PrestonL** [comment]
I really wish that someone could track down one of the organizers and get the project and funds handed off to an entity that can properly maintain it.  This is a huge blow to F/OSS and I think we'd all rather donate to making this work; just need to make sure the funds are falling into the right hands.

**Comment by noahbetzen-wk** [comment]
Until the TLS 1.2 issue in #2854 is fixed, my company can't use SequelPro. We use the free edition of [DBeaver](https://dbeaver.io/) as our primary SQL client now.

**Comment by Nezteb** [comment]
Until the TLS 1.2 issue in #2854 is fixed, my company can't use SequelPro. We use the free edition of [DBeaver](https://dbeaver.io/) as our primary SQL client now.

**Comment by rjhancock** [comment]
I think it's safe to say it's abandoned. It's a wonderful tool. I've started looking at a rebuild of it and using the DB abstraction used in Vapor to handle more than just MySQL. It's just a matter of finding the time for it.

**Comment by nam-co** [comment]
https://www.araelium.com/querious looks like a good option, full mysql 8 support

**Comment by brandon-bt** [comment]
> https://www.araelium.com/querious looks like a good option, full mysql 8 support

Thanks for this. Given the state of this project I have been looking at different MySQL tools and have been really disappointed. Querious is the first one I've come across that seems to have the speed and UI nimbleness I've come to expect from Sequel Pro.

**Comment by nam-co** [comment]
it's is a good option @brandon-bt , I like it a lot, I just wish it had iCloud sync and a reload button with easy access

**Comment by Jason-Morcos** [comment]
Checkout the Sequel Ace fork of Sequel pro. MySQL 8 support is coming next major release (beta available now in GitHub releases)! https://github.com/Sequel-Ace/Sequel-Ace

**Comment by Kaspik** [comment]
Please read about the future in new topic - https://github.com/sequelpro/sequelpro/issues/3705
