### ISSUE TITLE
When will mysql 8 support appear?

### ISSUE THREAD

**Issue by roma4u** [sequelpro/sequelpro#3593]
When will mysql 8 support appear?

**Comment by cotiga** [comment]
I like Sequel
I have worked for years and I would never thank his fellow creators enough.
But today, we must face the facts, Sequel is unusable with MySQL 8.
It is with nostalgia that I unfortunately passed to DBeaver, but it's a necessary evil
Goodbye Sequel
[DBeaver](https://dbeaver.io/)

**Comment by rubenjleon** [comment]
@cotiga I've been using the latest nightly build with MySQL 8 (8.0.18) without any issues.  It's great!

**Comment by roma4u** [comment]
@cotiga I could not download the latest nightly build due to the lack of a download link. Last build was there was a five-month-old assembly. https://sequelpro.com/test-builds

**Comment by cotiga** [comment]
I tried to work with nightly build.
Believe me that I made the effort to continue using Sequel, but I encountered SSH connections problems on MySQL 8 servers and I also noticed some interface bugs.
Sequel is the best MySQL tool but not for MySQL 8

**Comment by rubenjleon** [comment]
**Correction:**  I should have said the latest test build instead of the latest nightly build.  I am connecting to MySQL 8 via SSH and using Sequel Pro to connect to all my servers.  I have yet to find any issues myself.  So, in my opinion, Sequel Pro does work with MySQL 8.

**Comment by Kaspik** [comment]
Please read about the future in new topic - https://github.com/sequelpro/sequelpro/issues/3705
