### ISSUE TITLE
App Crash 

### ISSUE THREAD

**Issue by mircoraffinetti** [sequelpro/sequelpro#3594]
In case of multiple session opened, the app crash (forced closed) if you close one of sessions.

Osx Catalina 10.15.1

**Comment by mircoraffinetti** [comment]
Issue duplicated. Solved with this version: https://sequelpro.com/builds/Sequel-Pro-Build-97c1b85783.zip

**Comment by parelius** [comment]
I had the same issue and can confirm, that the nightly Build named above fixes this issue. Thanks.

**Comment by sinri** [comment]
Is there a plan to release next official version and when?

**Comment by Kaspik** [comment]
Please read about the future in new topic - https://github.com/sequelpro/sequelpro/issues/3705
