### ISSUE TITLE
Show progress bar when duplicating database

### ISSUE THREAD

**Issue by ExTexan** [sequelpro/sequelpro#3596]
The duplicate database operation can sometimes take a while.  It would be nice to see a progress bar instead of a spinning mouse icon.

**Comment by ExTexan** [comment]
I got a notice that this had been marked "stale", so I'm just posting a nudge to keep this on radar.

**Comment by Kaspik** [comment]
Please see https://github.com/sequelpro/sequelpro/issues/3705
