### ISSUE TITLE
Crashing on exit

### ISSUE THREAD

**Issue by klysiak** [sequelpro/sequelpro#3599]
The app is awesome, but it is crashing on exit - every time. It is even crashing when closing an active tab. macOS 10.15.1 but it was crashing on previous one as well.

**Comment by ddides** [comment]
This is fixed on the nightly builds. The maintainer hasn't cut a new release in years, so don't expect it to hit mainline soon.

**Comment by scheinercc** [comment]
Can this issue be left open and pinned, so that others can easily find that link? Though I think your first link was better as more general/future proof: https://sequelpro.com/test-builds ;)

**Comment by byustephen** [comment]
Upgrading to the nightly build fixed it for me. I like the new layout. 

I wonder when the maintainer will make the current version a new release?
