### ISSUE TITLE
how long release the new version to fix the crash when close a tab?

### ISSUE THREAD

**Issue by bpzhang** [sequelpro/sequelpro#3603]

**Comment by ricardoaugusto** [comment]
@bpzhang this works for me https://github.com/sequelpro/sequelpro/issues/3116#issuecomment-433749348

**Comment by bpzhang** [comment]
> @bpzhang this works for me [#3116 (comment)](https://github.com/sequelpro/sequelpro/issues/3116#issuecomment-433749348)

Yes i know but i want to use a stable version instead of a test-build

**Comment by Hubertnator** [comment]
It looks like they just quitted the project :(
I keep referring back to #3385...

**Comment by scheinercc** [comment]
I would rather recommend reading:
https://github.com/sequelpro/sequelpro/issues/3385#issuecomment-465590344
+
https://github.com/sequelpro/sequelpro/issues/3385#issuecomment-471842886
+
https://github.com/sequelpro/sequelpro/issues/3385#issuecomment-472177723

and check if you can help push the release forward by contributing to:
https://github.com/sequelpro/sequelpro/projects/2

:)

**Comment by Hubertnator** [comment]
This might not work.

You see, there are so many pull requests, that have no conflicts with the main branch, that solve issues **still not merged**. #3051, #3536 

I'm not a SP hater, but if I see that the last commit has been done 3-4 months ago, and that @dmoagx  is the only one working on this, I lost my hopes...

**Comment by Briones** [comment]
It's a dead project, it's better to accept that and move to another tool.

**Comment by scheinercc** [comment]
I'd say there were bigger gaps in the past until people had the time to push out a new nightly build: https://sequelpro.com/test-builds

I am grateful for all the time and effort that got pored in so far and besides, it works for me right now, so I am ok with it. ¯\_(ツ)_/¯
