### ISSUE TITLE
build failed with code signing problem

### ISSUE THREAD

**Issue by DongChengliang** [sequelpro/sequelpro#3606]
`
Showing All Messages
CodeSign /Users/dcl/Library/Developer/Xcode/DerivedData/sequel-pro-gsxtwyudrscknleeyukoxqedueli/Build/Products/Debug/Sequel\ Pro.app (in target 'Sequel Pro' from project 'sequel-pro')
    cd /code/mac/sequelpro
    export CODESIGN_ALLOCATE=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
    
Signing Identity:     "-"

    /usr/bin/codesign --force --sign - --entitlements /Users/dcl/Library/Developer/Xcode/DerivedData/sequel-pro-gsxtwyudrscknleeyukoxqedueli/Build/Intermediates.noindex/sequel-pro.build/Debug/Sequel\ Pro.build/Sequel\ Pro.app.xcent --timestamp=none /Users/dcl/Library/Developer/Xcode/DerivedData/sequel-pro-gsxtwyudrscknleeyukoxqedueli/Build/Products/Debug/Sequel\ Pro.app

/Users/dcl/Library/Developer/Xcode/DerivedData/sequel-pro-gsxtwyudrscknleeyukoxqedueli/Build/Products/Debug/Sequel Pro.app: code object is not signed at all
In subcomponent: /Users/dcl/Library/Developer/Xcode/DerivedData/sequel-pro-gsxtwyudrscknleeyukoxqedueli/Build/Products/Debug/Sequel Pro.app/Contents/Frameworks/ShortcutRecorder.framework
Command CodeSign failed with a nonzero exit code

`

**Comment by tilhoft** [comment]
Same here,
on MacOs Catalina 10.15.1
Xcode Version 11.2.1 (11B500)

**Comment by tilhoft** [comment]
I have figured it out at general tab, we need to change framework settings 'Embed without signing' to 'Embed & sign' as wrote here: #3582
