### ISSUE TITLE
Sequel Pro Crashes When Opening DB

### ISSUE THREAD

**Issue by jyllstuart** [sequelpro/sequelpro#3609]
MySQL Version 8.018
Mac OS Catalina 10.15.01

[_NSInlineData isEqualToString:]: unrecognized selector sent to instance 0x600000308b60

(
	0   CoreFoundation                      0x00007fff321bcf53 __exceptionPreprocess + 250
	1   libobjc.A.dylib                     0x00007fff68282835 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff32247106 -[NSObject(NSObject) __retain_OA] + 0
	3   CoreFoundation                      0x00007fff321636cb ___forwarding___ + 1427
	4   CoreFoundation                      0x00007fff321630a8 _CF_forwarding_prep_0 + 120
	5   Sequel Pro                          0x00000001000587cd -[SPTablesList updateTables:] + 1338
	6   Sequel Pro                          0x00000001000469c5 -[SPDatabaseDocument _selectDatabaseAndItem:] + 454
	7   Foundation                          0x00007fff347a5932 __NSThread__start__ + 1064
	8   libsystem_pthread.dylib             0x00007fff697f1d36 _pthread_start + 125
	9   libsystem_pthread.dylib             0x00007fff697ee58f thread_start + 15
)

Additionally tried to email crash report via interface, but received error "hostname not found."

**Comment by razum90** [comment]
Having the same problem!

**Comment by feixie1980** [comment]
I have the same issue, but only when opening database locally.  I am running Catalina.

**Comment by NikxDa** [comment]
Same here. Is there a fix coming?
