### ISSUE TITLE
Extremely frustrating performance and crashing constantly with slow connections

### ISSUE THREAD

**Issue by travisdetert** [sequelpro/sequelpro#3610]
I've been forced into using a vpn connection to connect to a mysql server in the cloud and the experience has been incredibly frustrating to say the least.  This connection routinely drops connections, is just slow in general, etc...  

When connection dropouts occur, sequelpro goes into a state where the beach ball is spinning and there is no possible recovery without force quitting.  It never regains stability even if my connection is otherwise stable.  When I'm working on these servers, I need a variety of queries and result sets that are all now lost because either the app crashed, or I had to force quit it, and now I have to start completely from scratch to continue working.  For the amount of time this wastes I'd happily pay hundreds of dollars to buy something that doesn't do this.

That said, since I really do like this app, I would happily contribute time and coding effort to kill this insanely annoying bug, because this app is very good otherwise.  Beggars can't be choosers, after all, so I'm definitely willing to help out here where I can, this section of the app MUST be improved.  I'm not trying to sound harsh, but there's no way tons of other people don't experience this, it's a quite glaring oversight in an otherwise great application.  Please advise as to how I can be of help to resolve this one.

**Comment by MikeBeas** [comment]
I have also experienced this when my VPN does the same thing. The app hangs and never recovers.
