### ISSUE TITLE
Incorrectly displaying data on table's charset vs column collation charset

### ISSUE THREAD

**Issue by salvor-hardin** [sequelpro/sequelpro#3612]
- Sequel Pro Version: Nightly 5446 (97c1b857)
- macOS Version: 10.14.6
- MySQL Version: 5.7.28

**Description**
Data displayed on a table should be using character set by collation of the column, not by the table charset.

**Steps To Reproduce**
CREATE TABLE `t_utf8_utf8` (
  `value` varchar(128) NOT NULL DEFAULT ''
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

INSERT INTO `t_utf8_utf8` (`value`)
VALUES
	('Apple iPhone アクセサリ');

![t_utf8_utf8](https://user-images.githubusercontent.com/40695717/70558959-bb922300-1b7d-11ea-8b75-3ac68ea90493.png)

CREATE TABLE `t_utf8_latin` (
  `value` varchar(128) CHARACTER SET utf8 NOT NULL DEFAULT ''
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

INSERT INTO `t_utf8_latin ` (`value`)
VALUES
	('Apple iPhone アクセサリ');

![t_utf8_latin](https://user-images.githubusercontent.com/40695717/70558942-b6cd6f00-1b7d-11ea-892c-dd7280da5e54.png)

You should see the same on both tables, as the table or the column is defined as uft8, however the client prints ??? for the Japanese characters (probably using the table charset for all the contents vs the COLLATED charset) when utf8 is the collation of the column but latin1 the charset of the table.

**Expected Behaviour**
I expect to see the same info on both tables.

**Additional Context**

Including screenshots.

**Comment by salvor-hardin** [comment]
Wondering if this will ever be fixed. Doesn't seem that complicated.

**Comment by Kaspik** [comment]
Please see https://github.com/sequelpro/sequelpro/issues/3705
