### ISSUE TITLE
Regression: Foreign key links do not isolate selected record

### ISSUE THREAD

**Issue by amacrobert-meq** [sequelpro/sequelpro#3614]
- Sequel Pro Version: Nightly Build 5446 (97c1b857)
- macOS Version: Mojave 10.14.6
- MySQL Version: 8.0.13

**Description**
In the table content view, columns that have a foreign key constraint have a button to the right of the value that is supposed to link to the foreign key's referenced row.

In previous versions of Sequel Pro, clicking that button would take the user to the table content view with just the referenced row visible.

In Build 5446, the referenced table is opened in the content view, but the referenced row within that table is not isolated, selected, or otherwise made known.

**Steps To Reproduce**
1. Create 2 tables -- one with a foreign key that references a column in the other
2. Add rows to both tables
3. In the table content view, click the button next to the column with a foreign key

**Expected Behaviour**
Only the referenced row should be visible after clicking the button next to a foreign key value.

**Additional Context**
n/a

**Comment by shmert** [comment]
Having the same issue. I think this is because the always-present filter is no longer there. The foreign key click used to set this value in the destination table, but now there's nothing for it to set.
