### ISSUE TITLE
Sequel Pro crashes when closing any of its open windows

### ISSUE THREAD

**Issue by JonLevischi** [sequelpro/sequelpro#3616]
Almost everytime I try to close one of the instances or the only instance opened Sequel Pro (latest version) crashes.
It's been happening on macOS Catalina and macOS Mojave.
I tried to send error report, but it also got an error.
Screen shot with errors below.

<img width="599" alt="Screen Shot 2019-12-14 at 03 29 28" src="https://user-images.githubusercontent.com/700091/70844575-2ebbc380-1e22-11ea-9897-d374d54f5570.png">

<img width="1112" alt="Screen Shot 2019-12-14 at 03 37 54" src="https://user-images.githubusercontent.com/700091/70844687-7858de00-1e23-11ea-912b-397ba67471db.png">

<img width="592" alt="Screen Shot 2019-12-14 at 03 38 32" src="https://user-images.githubusercontent.com/700091/70844688-7858de00-1e23-11ea-99c8-636f54e0e34f.png">

<img width="592" alt="Screen Shot 2019-12-14 at 03 38 38" src="https://user-images.githubusercontent.com/700091/70844696-7a22a180-1e23-11ea-8bce-dea5691af813.png">

<img width="592" alt="Screen Shot 2019-12-14 at 03 38 42" src="https://user-images.githubusercontent.com/700091/70844698-7a22a180-1e23-11ea-8592-8884a53576ba.png">

<img width="592" alt="Screen Shot 2019-12-14 at 03 38 49" src="https://user-images.githubusercontent.com/700091/70844700-7a22a180-1e23-11ea-8339-df5940688b21.png">

**Comment by JonLevischi** [comment]
<img width="1112" alt="Screen Shot 2019-12-14 at 03 37 54" src="https://user-images.githubusercontent.com/700091/70844669-4d6e8a00-1e23-11ea-8985-5c10dba43971.png">
<img width="592" alt="Screen Shot 2019-12-14 at 03 38 32" src="https://user-images.githubusercontent.com/700091/70844670-4d6e8a00-1e23-11ea-8e5e-df5316b15c4d.png">

![Uploading Screen Shot 2019-12-14 at 03.38.42.png…]()
![Uploading Screen Shot 2019-12-14 at 03.38.49.png…]()

**Comment by ccedgordon** [comment]
Also experiencing this issue.

**Comment by efaves** [comment]
This has been happening for a while... moving to a test build (until the next versioned release goes out... which may be never?) will fix the issue you are seeing. 

http://www.sequelpro.com/test-builds

**Comment by JonLevischi** [comment]
Thanks for the tip. Gonna try right now! :D

**Comment by KhimeraSpawn** [comment]
Experienced this issue as well. I might try a test build as suggested.

**Comment by masoodaslami** [comment]
I am still facing the same issue with version 1.1.2 in January 2020. When will this issue be fixed?

**Comment by notmessenger** [comment]
I too am on Mojave 10.14.6 and experiencing this same issue with version 1.1.2.  I installed the 97c1b85783 build and am still experiencing the crashing when closes open windows, although I was able to successfully submit a bug report.

**Comment by krunkosaurus** [comment]
After spending what seems to be years with this issue I finally dug in to try to find a solution. I confirmed the test build of this fixes the crashing issue. Download it here: https://sequelpro.com/test-builds

Wherever the original developers went, thanks for the software and I hope you come back.

**Comment by Kaspik** [comment]
Please read about the future in new topic - https://github.com/sequelpro/sequelpro/issues/3705

**Comment by KhaledJU** [comment]
Experienced this issue as well. I might try a test build as suggested.

**Comment by Kaspik** [comment]
@KhaledJU Have you red the #3705 and checked Sequel Ace?

I feel like we are going in circles, people are writing here after 3 years...

**Comment by panique** [comment]
Totally bizarre! This is broken for 3 years, and nothing happens. Sequel Ace seems to be a copy of Sequel Pro, but a bad one. You cannot even do a simple search/filter query without writing everything manually by hand.

Can somebody with the skillset please have a look to fix this and/or release the latest test-build as stable? ;)

**Comment by Jason-Morcos** [comment]
> Totally bizarre! This is broken for 3 years, and nothing happens. Sequel Ace seems to be a copy of Sequel Pro, but a bad one. You cannot even do a simple search/filter query without writing everything manually by hand.
> 
> 
> 
> Can somebody with the skillset please have a look to fix this and/or release the latest test-build as stable? ;)

Sequel Ace dev here - you definitely can filter and search without writing stuff by hand. Cmd+F from a table view to get to filters if they're not showing.

We forked directly off Sequel Pro because nobody would release.

**Comment by albertmenglongli** [comment]
> After spending what seems to be years with this issue I finally dug in to try to find a solution. I confirmed the test build of this fixes the crashing issue. Download it here: https://sequelpro.com/test-builds
> 
> Wherever the original developers went, thanks for the software and I hope you come back.

Thanks

**Comment by dirkpostma** [comment]
Tip: use Sequel Ace in stead, stable fork of Sequel Pro, https://sequel-ace.com/
