### ISSUE TITLE
We REALLY need an update on the state of Sequel Pro's development...

### ISSUE THREAD

**Issue by JackWH** [sequelpro/sequelpro#3617]
Sequel Pro is an absolutely indispensable tool for many of us. We rely on it to do our jobs. We recommend it to our friends and colleagues. We don't just use it in development — we know it can be trusted in production too. We've had confidence in Sequel Pro, stuck by the project for years, and some of us have even donated to support it.

Bearing in mind how much users love Sequel Pro, it's such a shame to see:

- Over 1000 unresolved issues
- Nearly 40 unmerged Pull Requests
- No updates on the Twitter account for over 1 year
- No new test release builds in 6 months
- **No new stable releases in nearly 4 years!**

I'm well aware I can download a test build. But I'm sure I'm not the only developer who's reluctant to use unstable software against production databases.

**Just look at the [changelog for v1.2](https://github.com/sequelpro/sequelpro/wiki/Release-1.2). These are great improvements... But _nobody knows about them!_ The people who contributed to v1.2 may as well have not bothered, if users will never receive any updates.** We may never know the number of developers who've abandoned Sequel Pro as a result of the notorious tab-closing crash, because they're simply not aware fixes are being worked on. And the sad truth is that these issues _are_ being fixed — they're just never seeing the light of day.

Can anyone involved in this project provide an update? If it's been abandoned, fair enough — we had a great run together! But if it hasn't, _please_ can the maintainers:

- Release an official update to fix the tab-closing issues (first reported 18 months ago!)
- Post an acknowledgement that the project is still being developed
- Provide a rough estimate of when the next release is likely to be?
- Post a tweet to let your users know the project hasn't been abandoned

It just hurts me to see issues piling up, whilst the hard work contributors make to fix these bugs goes unreleased to end-users for _literally years_ at a time.

Apologies for the rant. I hope you realise it comes from a place of love for one of my most relied-upon developer tools ❤️

**Comment by Nezteb** [comment]
Until the TLS 1.2 issue in #2854 is fixed, my company can't use SequelPro. We use the free edition of [DBeaver](https://dbeaver.io/) as our primary SQL client now.

**Comment by MikeBeas** [comment]
I have been using the nightly builds for over a year now because of the tab-closing crash but even the nightly builds now have problems on Catalina with the sidebar not being sized properly on launch. I haven't found any other DB clients I like as much as this one and I'll be sorely disappointed if it's abandoned.

I would also really like an snser about the status of this project. I heard some people were considering the idea of a fork? Is that happening?

**Comment by lagnat** [comment]
@dmoagx @stuconnolly @Kaspik @stychos What's the status of this project?

**Comment by dmoagx** [comment]
@lagnat There are no secrets (at least I'm not aware of any) about the status of the project. Everything that is there to know has already been discussed in this issue tracker.

**Comment by lagnat** [comment]
@dmoagx My apologies if this had already been discussed.  I scanned a few pages of issues and didn't see anything, so it seemed like a reasonable question to ask.  I'll dig a little deeper but if you're already aware of a status discussion thread, that would help.

**Comment by MattRiddell** [comment]
Yeah I'm super keen to know too - willing to put my money where my mouth is if it helps.

Sequel Pro is by far the best MySQL DB management app!

**Comment by jpike88** [comment]
It's a sad state of affairs and I don't expect it to improve anytime soon, this situation has been the case for years now.

I switched to TablePlus about six months ago (which has a free version) and I haven't looked back. My advice to everyone struggling with sequel pro's dysfunctional situation: stop worrying and switch to something that's actually being maintained, stable and cross-platform. This project shouldn't have any more pressure/expectation placed on it until it has clear leadership and proper release activity.

**Comment by markcarver** [comment]
This topic is <del>getting</del> ridiculous. Please just make a release already... it doesn't have to be 100% perfect; just mostly working and actually usable (unlike the current "stable" 1.1.2 version).

**Comment by thomscode** [comment]
Without any stable releases I will probably switch to another tool once I take the time to find one I like. Until that time, I did find the most recently successful [nightly build](https://sequelpro.com/test-builds) (built about 6 months ago) to resolve the issues I was having.

**Comment by nilbus** [comment]
> Everything that is there to know has already been discussed in this issue tracker.

If anyone can find what's being referred to here about the project status, some comment links would be helpful. Thanks!

**Comment by snebes** [comment]
@nilbus @lagnat #3385 is the most recent thread.

**Comment by Jason-Morcos** [comment]
Some of us have forked Sequel Pro into a new project! It's undergoing rapid development, but on App Store (for free) already. Latest beta supports MySQL 8 and will be submitted to App Store at some point soon! https://github.com/Sequel-Ace/Sequel-Ace

**Comment by Kaspik** [comment]
Please read about the future in new topic - https://github.com/sequelpro/sequelpro/issues/3705
