### ISSUE TITLE
link on website broken

### ISSUE THREAD

**Issue by lgelauff** [sequelpro/sequelpro#3625]
On https://sequelpro.com/docs/get-started/get-connected/local-mysql the link to "Where are MySQL's Files?" gives a 404 at https://sequelpro.com/docs/Where_are_MySQL%27s_Files%3F

**Comment by shellen** [comment]
I'm still seeing this too. ETA on when this will be fixed? This whole page if full of broken links:

https://sequelpro.com/docs/get-started/get-connected
