### ISSUE TITLE
Reordering fields with DEFAULT current_timestamp() doesn't work

### ISSUE THREAD

**Issue by dimitre** [sequelpro/sequelpro#3627]
- Sequel Pro Version: 1.1.2
- macOS Version: 10.14.6
- MySQL Version: 10.4.10-MariaDB

**Description**
Drag and drop to reorder fields, using DEFAULT current_timestamp() causes an error
```
An error occurred while trying to move the field.

MySQL said: Invalid default value for 'stamp'
```

**Comment by dimitre** [comment]
Issue is still 'working'
steps to reproduce:
```sql
CREATE TABLE `test` (
  `DateOfAddmission` datetime DEFAULT current_timestamp(),
  `Name` varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```

go to structure
and reorder fields with drag and drop twice

results are : 
Error moving field
MySQL said: Invalid default value for 'DateOfAddmission'

**Comment by Kaspik** [comment]
Please see https://github.com/sequelpro/sequelpro/issues/3705
