### ISSUE TITLE
Sequel Pro quitting when a tab is closed

### ISSUE THREAD

**Issue by kweyukevin** [sequelpro/sequelpro#3630]
Hi guys,

Im using Sequel Pro 1.1.2 on mac os catalina and every time i close a tab, the whole application quits and throws an error on the application quitting unexpectedly. It throws the same error on restart but continues to work fine. See attached screenshots of App and OS version
<img width="503" alt="Screenshot 2020-01-09 at 11 04 29" src="https://user-images.githubusercontent.com/4582289/72049548-36ab3e00-32d0-11ea-96b8-bb3697b249a8.png">
<img width="587" alt="Screenshot 2020-01-09 at 11 04 50" src="https://user-images.githubusercontent.com/4582289/72049549-36ab3e00-32d0-11ea-81bc-2224a0e04bd2.png">

Let me know if you need further info on this and ill update.

Regards,
Kweyu

**Comment by xiongminglang** [comment]
had the same issue, please to https://sequelpro.com/test-builds

**Comment by OwenMelbz** [comment]
Dupe.. https://github.com/sequelpro/sequelpro/issues/3116

**Comment by efraim14** [comment]
Do i have to install manually via test-builds? will the release version on sequelpro.com / https://github.com/sequelpro/sequelpro/releases going to be updated? i'm using brew cask to install sequel pro and it always said that v1.1.2 is the newest version.

I'm having the same problem on crashing.

**Comment by phil93883** [comment]
Please stop saying that this is a dupe of #3116.  #3116 was locked because it was "fixed" but it is not fixed.  On the latest version of Catalina (10.15.2), this happens constantly:

1. Upon opening the application, it "crashes" but continues to work.
2. Upon exiting the application, it crashes but this is minor since you're exiting the application anyways.
3. Upon closing a tab, it crashes hard and takes all other tabs with it.
<img width="720" alt="Screen Shot 2020-01-13 at 22 03 38" src="https://user-images.githubusercontent.com/59853419/72310765-98f99b00-3650-11ea-866a-adf85857261f.png">

**Comment by FVenneri** [comment]
Same here, it's very annoying.

**Comment by driq** [comment]
This may indeed be fixed in the master branch, but the fix never ended up in a release. So we are all still suffering for it.

**Comment by FVenneri** [comment]
> This may indeed be fixed in the master branch, but the fix never ended up in a release. So we are all still suffering for it.

It's a shame because I really like it but today I'm using the official client because I'm really annoyed for this problem...

**Comment by krunkosaurus** [comment]
After spending what seems to be years with this issue I finally dug in to try to find a solution. I confirmed the test build of this fixes the crashing issue. Download it here: https://sequelpro.com/test-builds

Wherever the original developers went, thanks for the software and I hope you come back.

**Comment by FVenneri** [comment]
Hello,

I'm trying the last build and it seems to work fine.
Thank you!

Il giorno gio 5 mar 2020 alle ore 05:00 Mauvis Ledford <
notifications@github.com> ha scritto:
