### ISSUE TITLE
Dark mode makes connections too faint

### ISSUE THREAD

**Issue by christatedavies** [sequelpro/sequelpro#3635]
- Sequel Pro Version: Nightly Build 5446 (97c1b857)
- macOS Version: 10.15.2
- MySQL Version: N/A

**Description**
If you have the new Catalina dark mode on and you colour your favourites, then the text is too light to read easily.

**Steps To Reproduce**
1. See image

**Expected Behaviour**
I would think the best option would be to allow users to choose a forecolor in addition to the background. Would solve all.

![Screenshot 2020-01-15 at 09 55 36](https://user-images.githubusercontent.com/1114343/72424021-3651ed80-377d-11ea-9f2a-487f4ac1cec4.png)

**Comment by willoller** [comment]
Another option would be to use the OSX dark-mode color palate (found in Preferences -> General -> Highlight color).
![Screen Shot 2020-01-30 at 3 33 30 PM](https://user-images.githubusercontent.com/127107/73499781-e296f500-4375-11ea-8431-93ab6e02902d.png)

**Comment by kaylanx** [comment]
I fixed this on PR https://github.com/sequelpro/sequelpro/pull/3644.

I took @willoller 's approach...

<img width="912" alt="dark-mode" src="https://user-images.githubusercontent.com/6442803/74487444-6644fb80-4eb7-11ea-8525-662cbe766349.png">
<img width="912" alt="light-mode" src="https://user-images.githubusercontent.com/6442803/74487454-6a711900-4eb7-11ea-94a2-0c619738e2f3.png">

**Comment by christatedavies** [comment]
Looks good. Looking forward to release. Thanks guys

**Comment by gustaflindqvist** [comment]
This is really looking good! Will it get merge to master soon?
