### ISSUE TITLE
build with xcode 11 error

### ISSUE THREAD

**Issue by jsonz** [sequelpro/sequelpro#3637]
![image](https://user-images.githubusercontent.com/159246/72628563-830a1400-3989-11ea-8d08-7b6644fd16af.png)
![image](https://user-images.githubusercontent.com/159246/72628713-d8debc00-3989-11ea-89e1-04c2f7c137e4.png)

**Comment by BenVim** [comment]
the same

**Comment by bartasdiver** [comment]
I was managed to build using [this solution](https://github.com/sequelpro/sequelpro/issues/3622).

**Comment by jsonz** [comment]
![image](https://user-images.githubusercontent.com/159246/74223931-baeb4980-4cf2-11ea-8c54-07c5c61defab.png)

changed "embed without signing" to "embed and sign"
