### ISSUE TITLE
For end users, issue 3116 (crashing when closing a tab) is not "Fixed" until there is a release with that fix in it

### ISSUE THREAD

**Issue by driq** [sequelpro/sequelpro#3638]
- Sequel Pro Version: 1.1.2
- macOS Version: 10.15
- MySQL Version: not relevant

**Description**
The fix for https://github.com/sequelpro/sequelpro/issues/3116 should end up in a release.
 
**Steps To Reproduce**
1. Open a tab
2. Close it

**Expected Behaviour**
No crash
**Additional Context**

I can't believe that https://github.com/sequelpro/sequelpro/issues/3116 has been reported almost two years ago, has been fixed in master, but that there is no release containing this fix.

The fact that you had to pin this issue confirms its urgency.

Locking https://github.com/sequelpro/sequelpro/issues/3116 is nice, but won't help except for creating issue spam like this:
* https://github.com/sequelpro/sequelpro/issues/3634
* https://github.com/sequelpro/sequelpro/issues/3628
* https://github.com/sequelpro/sequelpro/issues/3630
* https://github.com/sequelpro/sequelpro/issues/3616
* https://github.com/sequelpro/sequelpro/issues/3613
* https://github.com/sequelpro/sequelpro/issues/3611
* https://github.com/sequelpro/sequelpro/issues/3603
* https://github.com/sequelpro/sequelpro/issues/3603 
* https://github.com/sequelpro/sequelpro/issues/3599
* https://github.com/sequelpro/sequelpro/issues/3591
* https://github.com/sequelpro/sequelpro/issues/3590
* https://github.com/sequelpro/sequelpro/issues/3588
* https://github.com/sequelpro/sequelpro/issues/3585
* https://github.com/sequelpro/sequelpro/issues/3568
* https://github.com/sequelpro/sequelpro/issues/3567

And probably a few more that I missed

I was just reminded of this when reading https://www.codesimplicity.com/post/suck-less/ - thisis about patience of users running out when major bugs are simply not addressed.

**Comment by driq** [comment]
Hmmm... it looks like this project is abandoned (https://github.com/sequelpro/sequelpro/issues/3592).

Ufortunately I don't have the time right now to pick up this project. For my daily work I move to the SQL UI in the JetBreains IDEs, but I really miss using SequelPro.

**Comment by esstein** [comment]
SequelPro is really good, but I'm trying SQuirreL and DBeaver until crash bugs are fixed.

**Comment by ender1977** [comment]
just tried "Querious". Same look and feel like Sequel Pro, but stable, Finally the search has an end!

**Comment by jjboostability** [comment]
> just tried "Querious". Same look and feel like Sequel Pro, but stable, Finally the search has an end!
I've been tinking around with Querious today and it does feel like the closest to Sequel Pro. I'm liking it so far. Thanks for the suggestion!

**Comment by e-gaulue** [comment]
Is this a fork?

**Comment by ender1977** [comment]
don´t think its a fork. The GUI is similar, but the functionality in detail is different. i use querious since a week and made following experience: At some points sequel pro was more intuitive on i.e. implicitely saving changes. in querious changes on columns have to be applied. if you just leave the form, changes are lost. the behavior of querious is better, because you can do multiple changes on a table and they are made in one query, what is advantageous on big tables. But i have to get used to it. all in all querious is a bit more complicated and more powerful. And it is so wonderful to close a tab without crashing the app :)

**Comment by Kaspik** [comment]
Please read about the future in new topic - https://github.com/sequelpro/sequelpro/issues/3705
