### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by siavashrad** [sequelpro/sequelpro#3639]
![Screen Shot 2020-01-28 at 3 25 12 PM](https://user-images.githubusercontent.com/7073501/73314415-a7b08800-41e2-11ea-909e-e8dea256f378.png)

- The specified item could not be found in the keychain.
- Command PhaseScriptExecution emitted errors but did not return a nonzero exit code to indicate failure

**Comment by ricardomartos** [comment]
[this](https://github.com/sequelpro/sequelpro/issues/3637) worked for me, hope it helps you
