### ISSUE TITLE
Please mark resolved close-crash issue as really fixed in the top of the first message with link to fix

### ISSUE THREAD

**Issue by bronius** [sequelpro/sequelpro#3641]
As the title says: Please make it clear on #3116 that that issue is resolved, not released, but easily fixed with the latest build.

I apologize if this looks like issue-trolling, but I had been watching #3116 for months with frustration and humor ... only to eventually, on a whim, follow trails to easily install and run build 97c1b85783 found on https://sequelpro.com/test-builds which does not exhibit the issue.

I don't know the supposed stability of this release, but the fact that closing tabs in Sequel Pro in Mojave/Catalina no longer crashes Sequel Pro is elating to me! :) Thanks for the great and simple to use software.

**Comment by jasonfb** [comment]
@bronius -- I can confirm, I am having a different problem with Mojave (not exactly as described in 3116 but similar) 

the test build of the latest head is here https://sequelpro.com/test-builds
https://sequelpro.com/builds/Sequel-Pro-Build-97c1b85783.zip

it appears to fix the problem I was having with Mojave

it seems like the project is abandoned.

**Comment by krunkosaurus** [comment]
After spending what seems to be years with this issue I finally dug in to try to find a solution. I confirmed the test build of this fixes the crashing issue. Download it here: https://sequelpro.com/test-builds

Wherever the original developers went, thanks for the software and I hope you come back.

**Comment by Kaspik** [comment]
Please read about the future in new topic - https://github.com/sequelpro/sequelpro/issues/3705
