### ISSUE TITLE
Abandoned project

### ISSUE THREAD

**Issue by prhost** [sequelpro/sequelpro#3642]
if they are not going to keep it, pass it on to anyone who wants to collaborate. One of the best opensource tool for mac and dead.

**Comment by datashaman** [comment]
![Screenshot from 2020-02-11 09-40-58](https://user-images.githubusercontent.com/59514/74218380-a5562f80-4cb2-11ea-83a4-7f8adf543678.png)

**Comment by jasonfb** [comment]
the test build of the latest head is here https://sequelpro.com/test-builds
https://sequelpro.com/builds/Sequel-Pro-Build-97c1b85783.zip

it appears to fix the problem I was having with Mojave (my problem was not exactly as described in 3116 but is a crash when you choose a Database)

**Comment by Hubertnator** [comment]
@jasonfb We all know about them. It's just that they don't want to make a release, because... the project is dead.

**Comment by prhost** [comment]
https://sequelpro.com/donate

Do you receive donations from large companies and individual collaborators, what happens to have pull requests open since 2015, and more than 1k issues? I believe that the excuse is not money.

**Comment by jasonfb** [comment]
I paid $49 just recently for a macOS replacement for this for Catalina and it isn't ½ as good as Sequel Pro was in its day. why don't someone take the code, rename it, package it up, and release it in the App store and make a ton of $$$$$$$$$$$ ?  does its license say derivative work can't be sold?

**Comment by Jason-Morcos** [comment]
My fork of Sequel Pro is now notarized so it can be installed on any Mac. Please beware there may be bugs, but it's aimed at being released on the Mac App Store at some point soon! If you're tired of broken nightly builds, give it a try. PRs gladly accepted!

https://github.com/Sequel-Ace/Sequel-Ace/releases/tag/2.0-beta2

**Comment by Kaspik** [comment]
Please read about the future in new topic - https://github.com/sequelpro/sequelpro/issues/3705
