### ISSUE TITLE
Sidebar - OS 10.15.3

### ISSUE THREAD

**Issue by DavidWhicker** [sequelpro/sequelpro#3649]
Hello

The sidebar is always half the widget of the window on startup. It doesnt hold the new widget when reopening the app.

**Comment by rafamrs** [comment]
I think this was working great before... what happened?

**Comment by xoniq** [comment]
Possibly a change in Catalina's windowing system, and this project being abandoned.

**Comment by xoniq** [comment]
A separate reply, I used this branch:

https://github.com/corecoding/sequelpro/tree/graphing

Downloaded the ZIP, compiled in Xcode, and **YES it's fixed**.

**Comment by rafmst** [comment]
How do I build the app? I followed the README steps, but I never done this before, and it feels like something is missing. Thanks

**Comment by xoniq** [comment]
I'm on my other Mac, so I did it again on this one and did a little write-up for you:

# Install / test

- Close your regular Sequel Pro application for the entire process
- Download zip
- Unpack
- Open `sequel-pro.xcodeproj`
- Select `Sequel Pro` > `My Mac` near the 'STOP' button
- Run ('PLAY' button or `CMD` + `R`)
- Check if everything works
- Stop (STOP button or `CMD` + `.`) the Sequel Pro app will be stopped

# Create executable .app file

This is the file which will replace the 'original' app in the Applications folder.

- Top bar: `Product` > `Archive`
- Wait for it to archive the build
- A window will appear with the archived build
  - If it doesn't: `Window` > `Organizer`
- Right click on your new build > `Show in Finder`
- Right click on the filde `Sequel Pro XX-XX-XXXX, XX.XX.xcarchive` (XX = date)
- Show contents
- Go to `Products` > `Users` > `your username` > `Applications`
- Copy `Sequel Pro.app` to your Applications folder (replace it)

**Comment by rafmst** [comment]
Wow, great! Thanks for the fully detailed guide, I managed to make it work perfectly. Cheers

**Comment by xoniq** [comment]
@rafmst you’re welcome. Above write-up can be used for most Mac applications you can build from source. So it’s useful for later.

**Comment by pynixwang** [comment]
should drop support macos < 10.10

**Comment by zxins** [comment]
update file: sequelpro/Source/Views/SPSplitview.m

![image](https://user-images.githubusercontent.com/17568462/84224774-ef8bd800-ab0f-11ea-9bd2-5692c496fab8.png)
