### ISSUE TITLE
Lost connection -> accept closing this tab -> kills / closes also all other (healthy) connections

### ISSUE THREAD

**Issue by srothe** [sequelpro/sequelpro#3650]
Hey,
we often have connection to two db server open, for each of them we need different vpn connections.
cause one the vpn connection is shut down regularly we get the "connection lost" for this one.
when we accept to close this lost connection tab the whole application crashes (disappears immediately). even the healthy connection is killed and as already mentioned in another bug ticket all unsaved sql statements in any open tab get lost.
best
sven

**Comment by krunkosaurus** [comment]
After spending what seems to be years with this issue I finally dug in to try to find a solution. I confirmed the test build of this fixes the crashing issue. Download it here: https://sequelpro.com/test-builds

Wherever the original developers went, thanks for the software and I hope you come back.
