### ISSUE TITLE
Error closing tabs

### ISSUE THREAD

**Issue by jeroqueiroz** [sequelpro/sequelpro#3657]
Whenever I close a tab it ends the application with an error and displays the message to send the data to Apple support.

**Comment by henryh** [comment]
Yes, I have the same.

**Comment by kirilltitov** [comment]
Please see pinned issue https://github.com/sequelpro/sequelpro/issues/3116

**Comment by categoryshell** [comment]
The last nightly build was months ago, same as the last commit.

I'd consider this project dead and move on. Tableplus, although paid, is a good replacement

**Comment by ajoslin103** [comment]
TablePlus offers a LOT of database connection options !! 

(PostgreSQL, Redshift, MySQL, MariaDB, MSSQL, Cassandra, Mongo(beta), Snowflake, Redis, SQLLite, Oracle, Cockroach, & Vertica)

Even tho' it's a little clunkier than SequelPro I switched immediately -- It's certainly cheaper than paying multiple licenses for multiple clients

(SQLPro for Postgres is now a monthly subscription)
