### ISSUE TITLE
GUI scaling issue

### ISSUE THREAD

**Issue by klausny** [sequelpro/sequelpro#3659]
Whenever I open Sequel Pro from start or a new tab it will scale the left tab "quick connect" very large (check image), so every time I'm dragging it to a better size, but I have to to this each time which is quite annoying, as it resets to the large scaling on new tabs and when I open the app again, any fix? (I'm on Mac)

I tried deleting the app and installing again, but didn't work.

GUI Screenshot: 
![7b61b9c3ffe1adda8240eca0c0591345](https://user-images.githubusercontent.com/14151003/77315698-48658480-6d08-11ea-8a30-a7d59a626f7e.png)

**Comment by mstnorris** [comment]
This is a duplicate of https://github.com/sequelpro/sequelpro/issues/3649
