### ISSUE TITLE
user is too long.

### ISSUE THREAD

**Issue by jogvana** [sequelpro/sequelpro#3663]
- Sequel Pro Version: 1.1.2
- macOS Version: Mojave 10.14.1
- MySQL Version: Ver 15.1 Distrib 10.1.44-MariaDB

When I click on "Database" on the top menu and then "User accounts.." the error "user is too long." occurs. When I click on OK the second error message says "Multiple validation errors occurred." and that one keeps coming endlessly.

**Comment by jogvana** [comment]
Any update on this issue?

**Comment by Kaspik** [comment]
Please see https://github.com/sequelpro/sequelpro/issues/3705
