### ISSUE TITLE
APP crash when open a database in local mysql server on my macbook.

### ISSUE THREAD

**Issue by woo2000** [sequelpro/sequelpro#3664]
Hi,

The app cannot report problem by itself.

So I post here.

<img width="480" alt="1" src="https://user-images.githubusercontent.com/5175347/77637416-9b516d00-6f90-11ea-913b-51f8fa9a6f27.png">
<img width="723" alt="2" src="https://user-images.githubusercontent.com/5175347/77637430-a1474e00-6f90-11ea-9753-2aceed0ccbd9.png">

[Preferences.txt](https://github.com/sequelpro/sequelpro/files/4386606/Preferences.txt)
[Exception.txt](https://github.com/sequelpro/sequelpro/files/4386648/Exception.txt)

[Crash Log.txt](https://github.com/sequelpro/sequelpro/files/4386835/Crash.Log.txt)

[Console.txt](https://github.com/sequelpro/sequelpro/files/4386855/Console.txt)

**Comment by rmncv** [comment]
same

**Comment by italoroldo** [comment]
same

**Comment by Joelith** [comment]
Same issue. Download the test build it fixed the problem for me.

**Comment by jaroslawhartman** [comment]
> Same issue. Download the test build it fixed the problem for me.

What do you mean by _test build_?
Thank you

**Comment by ademola-raimi** [comment]
I am getting this issue too, I think this has something to do with the fact that it does not support the latest MySQL version 8.0.19 (might be wrong). It used to work before I upgraded my MySQL version. Is this project still maintained?

**Comment by JakeCasey** [comment]
@jaroslawhartman I downloaded the test build from [here](https://sequelpro.com/test-builds) and it fixed this problem for me!

**Comment by oddlots** [comment]
@Joelith @JakeCasey Thank you! downloading the "latest" test build fixed all my issues. The fact that it is 6+ months old suggests that finding an alternative to SequelPro might be looming.
