### ISSUE TITLE
Table List partially disappears

### ISSUE THREAD

**Issue by bytor99999** [sequelpro/sequelpro#3666]
- Sequel Pro Version:
Build 5546
- macOS Version:
10.15.3
- MySQL Version:
RDS Instance 5.7.x

**Description**
We have about 100 tables, and on the left where the list of tables goes part of the list goes blank/disappears. Then if you select in the blank area, those table names will now appear. Then you scroll up or down and that section that you scroll to now shows blank section where table names should appear.

**Steps To Reproduce**
1. Have a list of tables that makes for there being scrollbars
2. Scoll around and see blank spaces 

**Expected Behaviour**
I expect to always see all the tables in the list, instead of blank lines that you have to click on to try and find out what table it actually is.

**Additional Context**
I don't know if it is a memory issue or the amount of time the application has been open with a connection. But even if I restart the app it still happens right away.
<img width="248" alt="Screen Shot 2020-03-26 at 10 40 05 PM" src="https://user-images.githubusercontent.com/410140/77715747-c8167c00-6fb2-11ea-9724-60cc00b778bf.png">

**Comment by bytor99999** [comment]
Seriously? No one has looked into this yet. It has a huge negative impact on productivity here. I spend a good 30 minutes fighting this bug every day.

**Comment by stychos** [comment]
@bytor99999 give a try to https://github.com/Sequel-Ace/Sequel-Ace

**Comment by bytor99999** [comment]
@stychos That is pretty low trying to promote your own product on an issues ticket. You have very questionable ethics doing that.

**Comment by stychos** [comment]
@bytor99999 I am not promoting my own product, I am just pointing you to the same product which is forked in efforts to reanimate this one. Also, I tried to help this repository too, but dead is dead.

**Comment by bytor99999** [comment]
I did not know SequelPro was dead. I thought these betas kept coming out with newer versions.

On Jun 22, 2020, at 3:46 PM, Dan Ray <notifications@github.com> wrote:

﻿
@bytor99999 I am not promoting my own product, I am just pointing you to the same product which is forked in efforts to reanimate this one. Also, I tried to help this repository too, but dead is dead.

**Comment by stychos** [comment]
I can only wish to raise your own ethics, sorry. If you'd even been interested in the fate of the Sequel Pro you'd know this project is dead for several years. There was some "activity" more than a year ago, but now it's completely stale. And this is the usual open-source way － if someone stopping product maintaining, then someone stepping in and grabs it in his hands or makes a fork. Better address your words to the people that promotes commercial products like Table+ here.

**Comment by bytor99999** [comment]
Obviously, you have no idea the definition of the word ethics.

**Comment by stychos** [comment]
@bytor99999 go protest on the streets lol

**Comment by bytor99999** [comment]
And now it shows even more. You are a dick without ethics. Thanks.

**Comment by bytor99999** [comment]
Since this is a dead project I will close this and my other tickets.
