### ISSUE TITLE
Can't connect to remote MySQL db via SSH tunnel: You have entered 'localhost' for a non-socket connection

### ISSUE THREAD

**Issue by shadyanwar** [sequelpro/sequelpro#3667]
**Description**
I know this issue has been reported a number of times before. I have tried this in the command-line:
`mysql -h 127.0.0.1 -u <username> -p`
but it has not worked.

Meanwhile:
`mysql -h localhost -u <username> -p`
has worked.

On the SequelPro client, using 127.0.0.1 gave:

> MySQL said: Access denied for user 'shezlong'@'127.0.0.1' (using password: YES)

While using localhost gave:

> You have entered 'localhost' for a non-socket connection

Please allow `localhost` to be used in the host field.

**Comment by bram1028** [comment]
Why not just use a socket connection? Even with `mysql -h localhost`, will, by default, use a socket connection.
