### ISSUE TITLE
Losing filters and sorting when changing tables.

### ISSUE THREAD

**Issue by bytor99999** [sequelpro/sequelpro#3670]
- Sequel Pro Version:
Build 5446
- macOS Version:
10.15.3
- MySQL Version:
5.7

**Description**
In older versions the filter bar at the top would always be showing, that was nice. Now you have to click filter icon at the bottom and then you can add your filter. If you select another table you will lose your previous filter on the other table if you go back. Also if you had sorted the first table and then come back to it, it loses its sorting. This is very frustrating and you are usually using these filters and sort to fix a bug or data issue you might be having and usually you have to look in multiple tables because of their relations. Sometimes those filters are based on string/data that has to be copied and pasted from other sources. When you lose those filters you have to go back to copying and pasting from the other source, which might have been an PK id from another table that you had had filtered to just that row, but when you go back to that table to re-copy the id, that table is no longer filtered. This is a huge waste of time and productivity. It used to work perfectly in older versions.

**Steps To Reproduce**
1. Select a table, add a filter and/or sort.
2. Select another table and try to filter and/or sort it.
3. Go back to the first table, is the filter and sort still there. If so, keep repeating steps 1 and 2 with even other tables and pretty soon you will lose some filter or sort that you had had.

**Expected Behaviour**
If I select a table and add a sort and/or filter, and have to go to a few other tables doing the same, I expect those sorts and filters to remain on those other tables, so that when I go back to them they are still there, until I clear them out.

**Additional Context**

**Comment by bytor99999** [comment]
This is still  happening, Posting because it is being marked as stale. But it is far from being stale. It is a very annoying bug that affects productivity in SequelPro.

**Comment by jordanade** [comment]
It appears that one filter is being applied to all tables which of course must be a bug. Also if I click a foreign-key arrow it hardly ever works because of this issue. Clicking a foreign-key arrow should disable the filter so that the appropriate row can be displayed.
