### ISSUE TITLE
Please make a new nightly build

### ISSUE THREAD

**Issue by joelsdc** [sequelpro/sequelpro#3672]
Hi, 

The latest snapshot build is pretty old: 97c1b85783 -> http://sequelpro.com/test-builds

Any chance you can make another build? I'm specially interested in the latest commits in master :-(

I tried building myself unfortunately I get errors of missing stuff in the keychain in the `building and signing` phase.

Thanks!

**Comment by Jason-Morcos** [comment]
My fork of Sequel Pro is now notarized so it can be installed on any Mac. Please beware there may be bugs, but it's aimed at being released on the Mac App Store at some point soon! If you're tired of broken nightly builds, give it a try. PRs gladly accepted!

https://github.com/Sequel-Ace/Sequel-Ace/releases/tag/2.0-beta2

**Comment by Kaspik** [comment]
Please read about the future in new topic - https://github.com/sequelpro/sequelpro/issues/3705
