### ISSUE TITLE
Unexpected error occurs while establishing connection to database

### ISSUE THREAD

**Issue by siimleetberg** [sequelpro/sequelpro#3675]
- Sequel Pro Version: 1.1.2
- macOS Version: 10.15.3
- MySQL Version: 8.0.18-9 (Percona Server (GPL), Release 9, Revision 53e606f)

**Description**
Unexpected error occurs while establishing connection to database

**Steps To Reproduce**
1. Open Sequel Pro 
2.  Select connection from Favorites
3. Click Connect
4. Unexpected exception occurs

**Expected Behaviour**
Would expect for Sequel Pro to establish new connection and open new tab

**Additional Context**

**Exception:**

NSInvalidArgumentException

-[_NSInlineData isEqualToString:]: unrecognized selector sent to instance 0x60000038d260

(
	0   CoreFoundation                      0x00007fff3adca8ab __exceptionPreprocess + 250
	1   libobjc.A.dylib                     0x00007fff71084805 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff3ae49b61 -[NSObject(NSObject) __retain_OA] + 0
	3   CoreFoundation                      0x00007fff3ad2eadf ___forwarding___ + 1427
	4   CoreFoundation                      0x00007fff3ad2e4b8 _CF_forwarding_prep_0 + 120
	5   Sequel Pro                          0x000000010002fce3 -[SPDatabaseDocument setDatabases:] + 783
	6   Sequel Pro                          0x000000010002f2a9 -[SPDatabaseDocument setConnection:] + 610
	7   Foundation                          0x00007fff3d42b8ab __NSThreadPerformPerform + 254
	8   CoreFoundation                      0x00007fff3ad4eb21 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	9   CoreFoundation                      0x00007fff3ad4eac0 __CFRunLoopDoSource0 + 103
	10  CoreFoundation                      0x00007fff3ad4e8d4 __CFRunLoopDoSources0 + 209
	11  CoreFoundation                      0x00007fff3ad4d740 __CFRunLoopRun + 1272
	12  CoreFoundation                      0x00007fff3ad4cbd3 CFRunLoopRunSpecific + 499
	13  HIToolbox                           0x00007fff398a265d RunCurrentEventLoopInMode + 292
	14  HIToolbox                           0x00007fff398a239d ReceiveNextEventCommon + 600
	15  HIToolbox                           0x00007fff398a2127 _BlockUntilNextEventMatchingListInModeWithFilter + 64
	16  AppKit                              0x00007fff37f12ba4 _DPSNextEvent + 990
	17  AppKit                              0x00007fff37f11380 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1352
	18  AppKit                              0x00007fff37f0309e -[NSApplication run] + 658
	19  AppKit                              0x00007fff37ed5465 NSApplicationMain + 777
	20  Sequel Pro                          0x0000000100002454 start + 52
	21  ???                                 0x0000000000000001 0x0 + 1
)

**Comment by JakeCasey** [comment]
Downloading the test build from [this page](https://sequelpro.com/test-builds) fixed a similar issue for me.

**Comment by JavaBasketball** [comment]
@JakeCasey good job! thank you for solving it to save my two hours!

**Comment by shingler** [comment]
@JakeCasey Thanks Bro, you saved my ass.
