### ISSUE TITLE
Sequel Pro abandoned

### ISSUE THREAD

**Issue by Hubertnator** [sequelpro/sequelpro#3679]
Seen as this project is anyway not being developed, maybe it's time to stop paying for servers, openly say that this project is abandoned, and give links to  few forks that have regular commits. There is no pont in having a website for software whch doesn't work above MacOS 10.13.

**Comment by webcoderkz** [comment]
Probably abandoned, i moved away to TablePlus 3 years ago, i have no regrets.

**Comment by Hubertnator** [comment]
@webcoderkz It **is** abandoned, but why pay for servers, and give donations to this project? Last commit 7 months ago, so why donate? Just shut this whole thing down and give links to forks that have regular commits...

**Comment by MattRiddell** [comment]
Are there any forks?

**Comment by Hubertnator** [comment]
<img width="122" alt="Screen Shot 2020-05-17 at 08 37 25" src="https://user-images.githubusercontent.com/41962554/82137558-ad75bc00-9819-11ea-8128-94a99e5661d3.png">

Yes

**Comment by fengerzh** [comment]
> Probably abandoned, i moved away to TablePlus 3 years ago, i have no regrets.

No, TablePlus is not open source and not free. We want some open source tools.

**Comment by Jason-Morcos** [comment]
If there is enough interest, the license appears at least that we could just fork it and start our own tool. If the community is interested, it would be fairly trivial to release the latest nightly build with a new name/logo and go from there. At least the latest nightly build is pretty solid for me.

**Comment by Jason-Morcos** [comment]
My fork of Sequel Pro is now notarized so it can be installed on any Mac. Please beware there may be bugs, but it's aimed at being released on the Mac App Store at some point soon! If you're tired of broken nightly builds, give it a try. PRs gladly accepted!

https://github.com/Sequel-Ace/Sequel-Ace/releases/tag/2.0-beta2

**Comment by jamesstout** [comment]
Interested. I started looking through the code and seeing simple issues like calling UI on background threads. I started fixing some, then came here to check if anyone else was looking at it and found it's actually abandoned... maybe go with @Jason-Morcos's fork?

**Comment by Jason-Morcos** [comment]
@jamesstout Yeah I've noticed a lot of those kind of simple issues in the code. Any of them you have fixed/want to fix, I'd gladly take look at a PR! I think one of the biggest issues at Sequel Pro is nobody is reviewing PRs.

**Comment by jamesstout** [comment]
I see you’ve fixed some already. But I’ll keep looking.

**Comment by jamesstout** [comment]
I've noticed a few ways they use to switch execution to the main thread:

1. - [onMainThread](https://github.com/sequelpro/sequelpro/blob/c541d630ac2e57dcafb2ae15c99cfa3a6e84cfee/Source/SPMainThreadTrampoline.m#L40) in `SPMainThreadTrampoline` which seems to by synchronous.
2. - [SPMainQSync](https://github.com/sequelpro/sequelpro/blob/c541d630ac2e57dcafb2ae15c99cfa3a6e84cfee/Source/SPFunctions.m#L35) - synchronous and using deprecated `dispatch_get_current_queue`
3. - [dispatch_async(dispatch_get_main_queue()](https://github.com/Sequel-Ace/Sequel-Ace/blob/78353b90e52843096ae54f1fb0013ffc79a6157f/Source/SPAppController.m#L2422) - which is of course async.

I wrote a few performance tests to compare [an updated version of] 2 and 3 (but switching to dispatch_sync). 

There was basically no difference. I'd like to test `onMainThread` but I kept getting `unrecognized selector sent to instance` no matter what object I used.

Anyway, to get to my question, any preference on which to use?

**Comment by rowanbeentje** [comment]
`onMainThread` *should* be available on anything which extends NSObject, which is a lot! For a lot of the older code doing UI things on the main thread where they shouldn't, it's almost certainly naïve and might expect sync execution - it might be safest to use sync methods unless you can't see side effects or any issues with retain/release cycles (although that may have changed a lot since I last worked on ObjC!)...

**Comment by Kaspik** [comment]
Please read about the future in new topic - https://github.com/sequelpro/sequelpro/issues/3705
