### ISSUE TITLE
Error upon connecting to db and on sending error report

### ISSUE THREAD

**Issue by lyurko** [sequelpro/sequelpro#3685]
Upon connecting to my db it gives me an error window w/"SequelPro has encountered an unexpected error" and I try to send the report but upon hitting send I get "Error: A server with the specified hostname could not be found."

The app spins and never loads any of the tables.

Here is the info it would have been sending:

NSInvalidArgumentException

-[_NSInlineData isEqualToString:]: unrecognized selector sent to instance 0x600000426b40

(
	0   CoreFoundation                      0x00007fff36bb22db __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff5dd69c76 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff36c4adb4 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff36b28820 ___forwarding___ + 1456
	4   CoreFoundation                      0x00007fff36b281e8 _CF_forwarding_prep_0 + 120
	5   Sequel Pro                          0x00000001000587cd -[SPTablesList updateTables:] + 1338
	6   Sequel Pro                          0x000000010002f333 -[SPDatabaseDocument setConnection:] + 748
	7   Foundation                          0x00007fff38c702b5 __NSThreadPerformPerform + 334
	8   CoreFoundation                      0x00007fff36b4aa11 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	9   CoreFoundation                      0x00007fff36c0442c __CFRunLoopDoSource0 + 108
	10  CoreFoundation                      0x00007fff36b2d470 __CFRunLoopDoSources0 + 208
	11  CoreFoundation                      0x00007fff36b2c8ed __CFRunLoopRun + 1293
	12  CoreFoundation                      0x00007fff36b2c153 CFRunLoopRunSpecific + 483
	13  HIToolbox                           0x00007fff35e16d96 RunCurrentEventLoopInMode + 286
	14  HIToolbox                           0x00007fff35e16b06 ReceiveNextEventCommon + 613
	15  HIToolbox                           0x00007fff35e16884 _BlockUntilNextEventMatchingListInModeWithFilter + 64
	16  AppKit                              0x00007fff340c7a73 _DPSNextEvent + 2085
	17  AppKit                              0x00007fff3485de34 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 3044
	18  AppKit                              0x00007fff340bc885 -[NSApplication run] + 764
	19  AppKit                              0x00007fff3408ba72 NSApplicationMain + 804
	20  Sequel Pro                          0x0000000100002454 start + 52
)

**Comment by Mohammed-Alama** [comment]
Use the [nightly test build](https://sequelpro.com/builds/Sequel-Pro-Build-97c1b85783.zip):  it will work ok with you.
