### ISSUE TITLE
Tab crashes (workaround)

### ISSUE THREAD

**Issue by ktorn** [sequelpro/sequelpro#3688]
The issue was fixed long ago, but for some reason the project hasn't issued a release in ages.

The latest [test build](https://sequelpro.com/test-builds) works.

Can someone please pin this until a release is issued?

**Comment by geerlingguy** [comment]
Older issue, for reference: https://github.com/sequelpro/sequelpro/issues/3116

I'm not sure if anyone's currently maintaining the project, but at least that original issue is still pinned, which should give people a hint that it is fixed... just not in a stable release.

**Comment by Kaspik** [comment]
As mentioned in top of the Readme starting today - this project is being replaced with fork called Sequel-Ace.

Please refer to that - https://github.com/Sequel-Ace/Sequel-Ace
