### ISSUE TITLE
Crash when export or open new tab on macOS Catalina

### ISSUE THREAD

**Issue by bsrinisrini** [sequelpro/sequelpro#3692]
macOS Mojave it doesn't crash

- Sequel Pro Version: 1.1.2 Build 4541
- macOS Version: 10.15.4 OS Catalina
- MySQL Version: 8.0

**Description**
Crash when export or open new tab

I knew there is an existing issue for crashing. But the OS and mySQL version is different.

**Comment by geerlingguy** [comment]
See: https://github.com/sequelpro/sequelpro/issues/3116 — it's the same issue.
