### ISSUE TITLE
Importing .csv causes crash/freeze on Catalina 10.15.5 

### ISSUE THREAD

**Issue by ericleversen** [sequelpro/sequelpro#3698]
MacOS 10.15.5
SequelPro 1.1.2 Build 4541
When I import certain .csv files I get a crash warning (see attached) and the current window freezes. I can open a new window but it won't accept any keyboard input into it nor can I close the frozen window so I have to Force Quit the app and start again.

Since the app stops accepting keyboard input, I am unable to fill out the Crash Report. (See attached).
<img width="1248" alt="Screen Shot 2020-06-15 at 11 15 47 AM" src="https://user-images.githubusercontent.com/1933891/84682109-c9dd4500-aefa-11ea-94eb-4748aee5aab1.png">

This does not happen with the same version 1.1.2 on macOS 10.13.6

I'm unable to provide the .csv file since it has sensitive data in it.

Let me know if I can help with troubleshooting.

**Comment by ericleversen** [comment]
Its still not working if that will help freshen the issue up a bit...

**Comment by Kaspik** [comment]
Please see https://github.com/sequelpro/sequelpro/issues/3705 .
