### ISSUE TITLE
When I click the new connection tab close button, the software crashes

### ISSUE THREAD

**Issue by huangzhenwen** [sequelpro/sequelpro#3702]
System：macOS Catalina
Version：10.15.5

**Comment by yg-dba** [comment]
When you have multiple tabs open, and close one of the tabs, the entire application quits.  

Please fix asap, it's causing lost work :(.

**Comment by stychos** [comment]
@huangzhenwen @yg-dba use new fork: https://github.com/Sequel-Ace/Sequel-Ace

**Comment by yg-dba** [comment]
Many thanks for offering a solution!!!  So nice of you to contribute your talents to the world of devs and DBAs :).

**Comment by Kaspik** [comment]
Please see https://github.com/sequelpro/sequelpro/issues/3705
