### ISSUE TITLE
how long release the new version to fix the crash when close a tab

### ISSUE THREAD

**Issue by bpzhang** [sequelpro/sequelpro#3704]

**Comment by Jason-Morcos** [comment]
Looks like it's not gonna happen @bpzhang 
https://github.com/sequelpro/sequelpro/issues/3701

Check out Sequel Ace on the App Store/GitHub
https://apps.apple.com/us/app/sequel-ace/id1518036000?mt=12
https://github.com/Sequel-Ace/Sequel-Ace

**Comment by bpzhang** [comment]
Well Done @Jason-Morcos

**Comment by Kaspik** [comment]
As mentioned in top of the Readme starting today - this project is being replaced with fork called Sequel-Ace.

Please refer to that - https://github.com/Sequel-Ace/Sequel-Ace
