### ISSUE TITLE
IPhone not working

### ISSUE THREAD

**Issue by ilhamkabir** [sequelpro/sequelpro#3707]
Hi, I purchased SQLPro Premium for a year. It’s working fine on my Mac but I can’t use the subscription on my iPhone. Being able to use it on my iPhone is the main reason I purchased this. If I click “Restore purchase” I just get a spinner on the top right for a second and then nothing happens. Screenshot attached. Please advise.

**Comment by rowanbeentje** [comment]
Hi Ilham, I think you want https://www.sqlprostudio.com and not this project!
