### ISSUE TITLE
Error in Catalina 

### ISSUE THREAD

**Issue by rootDEV2990** [sequelpro/sequelpro#3733]
NSInvalidArgumentException

-[_NSInlineData isEqualToString:]: unrecognized selector sent to instance 0x60000032bc20

(
	0   CoreFoundation                      0x00007fff37b65be7 __exceptionPreprocess + 250
	1   libobjc.A.dylib                     0x00007fff7093d5bf objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff37be4c77 -[NSObject(NSObject) __retain_OA] + 0
	3   CoreFoundation                      0x00007fff37aca44b ___forwarding___ + 1427
	4   CoreFoundation                      0x00007fff37ac9e28 _CF_forwarding_prep_0 + 120
	5   Sequel Pro                          0x00000001000587cd -[SPTablesList updateTables:] + 1338
	6   Sequel Pro                          0x00000001000469c5 -[SPDatabaseDocument _selectDatabaseAndItem:] + 454
	7   Foundation                          0x00007fff3a1787a2 __NSThread__start__ + 1064
	8   libsystem_pthread.dylib             0x00007fff71ce9109 _pthread_start + 148
	9   libsystem_pthread.dylib             0x00007fff71ce4b8b thread_start + 15
)

**Comment by kenmaclord** [comment]
Yes got the same, not tables are loading

**Comment by rootDEV2990** [comment]
Try the beta version of sequel pro it works and got rid of my issues...can now load tables no problem.  hope it helps, happy coding ✌🏽

https://sequelpro.com/test-builds
