### ISSUE TITLE
Crash on tab closure

### ISSUE THREAD

**Issue by mvbaxter** [sequelpro/sequelpro#3734]
Anytime I close any tab, the entire application crashes.  This has been going on for a while.  I have upgraded OS X twice and the issue persists.  Unfortunately, this did NOT happen with the first version of Sequel Pro I installed.  I'm not sure, but that was at least two dot versions ago.

Mac OS X 10.15.6
64-bit Quad core 2.9Ghz
16GB memory
Sequel Pro 1.1.2 Build 4541

I have also submitted anonymous system profiles with each check for updates.

I also just finished a complete uninstall and re-install, using App Cleaner to capture all legacy files.   The problem persists.

Hope the details help.  Love your product.  Just hate all the crashes.

**Comment by Kaspik** [comment]
Please see https://github.com/sequelpro/sequelpro/issues/3705 as well as https://github.com/sequelpro/sequelpro/issues/3116

**Comment by benjaminkohl** [comment]
I swear someone reports this issue once per week. Download Sequel Ace from the App Store.

**Comment by mvbaxter** [comment]
Thanks!  Installed Sequel Ace after @Kaspik pointed me in the right direction.  Thanks for being a major grump @benjaminkohl.

**Comment by benjaminkohl** [comment]
@mvbaxter A major grump, eh? As a courtesy to developers, try learning to search open issues before posting so the developer doesn't get overwhelmed by redundant issues in the repo. There's a good possibility that contributed to why this free and popular piece of software is practically abandonware now. It takes a few seconds to search "tab" or "crash" in the open issues list and can save developers a lot of time and effort sifting through redundant open issues.
