### ISSUE TITLE
Localhost mysql db crashes the app every time I connect

### ISSUE THREAD

**Issue by AcriCAA** [sequelpro/sequelpro#3737]
Process:               Sequel Pro [7874]
Path:                  /Applications/Sequel Pro.app/Contents/MacOS/Sequel Pro
Identifier:            com.sequelpro.SequelPro
Version:               1.1.2 (4541)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Sequel Pro [7874]

**Comment by Kaspik** [comment]
Please see https://github.com/sequelpro/sequelpro/issues/3705 and if you want try this [fork](https://github.com/Sequel-Ace/Sequel-Ace).

**Comment by AcriCAA** [comment]
I will give it a try. Thank you @Kaspik
