### ISSUE TITLE
Optimize experience

### ISSUE THREAD

**Issue by TuringZhu** [sequelpro/sequelpro#3738]
![21603158914_ pic_hd](https://user-images.githubusercontent.com/13805470/96531235-bf252900-12bb-11eb-84ea-c746f65a3d90.jpg)

**Comment by Kaspik** [comment]
Please see https://github.com/sequelpro/sequelpro/issues/3705 and if you want try https://github.com/Sequel-Ace/Sequel-Ace :)

Also it's probably related to CPU usage mentioned in the fork: https://github.com/Sequel-Ace/Sequel-Ace/issues/269

**Comment by jamesstout** [comment]
There's also a built-in delay: 



```objc
[self performSelector:@selector(doAutoCompletion) 
              withObject:nil 
               afterDelay:[[prefs valueForKey:SPCustomQueryAutoCompleteDelay] doubleValue]];
```

<img width="580" alt="Screenshot 2020-11-09 at 12 21 09 PM" src="https://user-images.githubusercontent.com/1576190/98500059-5d3a5c80-2286-11eb-8e2b-997dd89b46f2.png">

Try changing to 0.5 seconds.
