### ISSUE TITLE
Sequel Pro crashes when closing a tab

### ISSUE THREAD

**Issue by bolef2k** [sequelpro/sequelpro#3743]
I'm experiencing the issue for months and was wondering if this is something that can be resolved.

Whenever I have a tab or connection open and then try to close that tab or window, the whole Sequel Pro App crashes including all other instances and tabs. That is really annoying as you can only open new tabs/windows, but never close w/o killing the others.

I have sent the crash report several times,

Process:               Sequel Pro [82822]
Path:                  /Applications/Sequel Pro.app/Contents/MacOS/Sequel Pro
Identifier:            com.sequelpro.SequelPro
Version:               1.1.2 (4541)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Sequel Pro [82822]
User ID:               501

Date/Time:             2020-11-13 14:54:19.180 +0100
OS Version:            Mac OS X 10.15.7 (19H2)
Report Version:        12
Bridge OS Version:     4.6 (17P6610)
Anonymous UUID:        C2D7C594-8C90-4B06-9D96-EE3568521463

Sleep/Wake UUID:       387A78DF-6735-4B51-88DB-1386D92F34B3

Time Awake Since Boot: 670000 seconds
Time Since Wake:       67000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000020
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [82822]

This is part of the error report...not sure if I need to provide rest of it.

**Comment by SanderVanLeeuwen** [comment]
This project is abandoned, use the fork instead: https://github.com/Sequel-Ace/Sequel-Ace . It doesn't crash ;)

**Comment by bolef2k** [comment]
Hey! That explains a lot, thank you!! Appreciate the help

**Comment by Kaspik** [comment]
Can be closed. :)

**Comment by leopinzon** [comment]
> Hey! That explains a lot, thank you!! Appreciate the help

😞  Such a shame, this continues to be a great contribution to the community!

**Comment by robertlipe** [comment]
Please close this report. This is reported every few days for the last several years.

This project is clearly abandoned. Sequel Ace started from the same code and operates similarly, but is maintained by people that don't care that the app crashes hundreds of times a day for users around the world. Please close this issue and move to Sequel Ace and contribute to its development.

Your penance is telling the NEXT five people that report this problem to move to Sequel Ace. :-) That helps the user, it helps reduce clutter here, and it helps Sequel Ace gain traction.

**Comment by bolef2k** [comment]
Sorry about that snd yes, sequel Ace helped a lot!
