### ISSUE TITLE
Feature Request: Always ask to reset auto increment ids when deleting rows

### ISSUE THREAD

**Issue by d42ohpaz** [sequelpro/sequelpro#3761]
I don't know the threshold that Sequel Ace uses, but if a large enough number of rows are being deleted from a table you are given a checkbox on whether or not you want to reset the auto increment id. This request is to ask that regardless of the number of rows being deleted that the auto increment checkbox always be available. Thank you.

**Comment by vstokarev** [comment]
Wrong repository :)

**Comment by d42ohpaz** [comment]
Apologies, and thanks for letting me know. :)
