### ISSUE TITLE
Crashes EVERY TIME for years, on every system used

### ISSUE THREAD

**Issue by panique** [sequelpro/sequelpro#3768]
I've to use Sequel Pro for several years on lots of different systems now, and it crashes literally (!) every single time I use it.
Additionally, for around 4 years the crash-report popup doesnt work, as it doesn't send anything anywhere. It's crazy.

This has nothing to do with any specific setup, it happens on all macOS of the last 4 years, all kinds of MacBooks, iMacs, Mac minis and Hackintoshs. I'd love to add something useful and help with a fix, but it's impossible to send bug reports :)

The error message is too big to post it here, but basically it's this:

```
Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [14704]
```

**Comment by robertlipe** [comment]
It's been broken for years. See #3751 Consider closing this as a dupe to reduce maintenance burden.
