### ISSUE TITLE
username length limitation is too short !

### ISSUE THREAD

**Issue by Lorem3** [sequelpro/sequelpro#3821]
Length of my accoountname which I cant change  is near 100, I cant login to the db (show passworder or username error),  I guess  sequelpro trunacate my account name,

**Comment by waleed-dawood** [comment]
You can try https://github.com/Sequel-Ace/Sequel-Ace.

Sequel Ace is the "sequel" to the longtime macOS tool Sequel Pro. Sequel Ace is a fast, easy-to-use Mac database management application for working with MySQL & MariaDB databases.

**Comment by Lorem3** [comment]
> You can try https://github.com/Sequel-Ace/Sequel-Ace.
> 
> Sequel Ace is the "sequel" to the longtime macOS tool Sequel Pro. Sequel Ace is a fast, easy-to-use Mac database management application for working with MySQL & MariaDB databases.

thank you for your reply, I found that it's a bug of libmysqlclient,the buffer of userName is only 16 bytes, I changed it to 200 and rebuild it. now it works fine :)
