### ISSUE TITLE
Pop up frequently and close pop ups accidentally

### ISSUE THREAD

**Issue by tanuki-cat** [sequelpro/sequelpro#3834]
![image](https://user-images.githubusercontent.com/64060318/154628868-74505fe5-4734-496e-8ab1-da7028818017.png)

system：monterey 12.2.1 
cpu: m1max

**Comment by tanuki-cat** [comment]
sequel pro  version: 1.1.2

**Comment by remfath** [comment]
this project is dead.

**Comment by tanuki-cat** [comment]
ok,thank you. I will look for a new util to instead 
















At 2022-02-24 22:34:56, "remfath" ***@***.***> wrote:

this project is dead.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
