### ISSUE TITLE
Stored Procedure

### ISSUE THREAD

**Issue by christatedavies** [sequelpro/sequelpro#3847]
I raised a question on Stackoverflow - which turned out to be an issue with SequelPro

https://dba.stackexchange.com/questions/315508/procedure-not-looping-properly?noredirect=1

Ignore the fact I messed up the backticks, I had it right on my local. And SequelPro does not run this query correctly. The SO issue has the necessary DB schema etc so you can test.

Thanks,

**Comment by Kaspik** [comment]
This project is dead, please read https://github.com/sequelpro/sequelpro/issues/3705

**Comment by christatedavies** [comment]
Sorry, I meant Sequel Ace anyway! My bad, I'll move it over to the other project.
