### ISSUE TITLE
App crashes when clicks on connect

### ISSUE THREAD

**Issue by kaggrwal** [sequelpro/sequelpro#3854]
After filling the details, test connection is successful. 

```
NSInvalidArgumentException

-[_NSInlineData isEqualToString:]: unrecognized selector sent to instance 0x600000dc51a0

(
	0   CoreFoundation                      0x00007ff810d90773 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007ff810af0bc3 objc_exception_throw + 48
	2   CoreFoundation                      0x00007ff810e1535b -[NSObject(NSObject) __retain_OA] + 0
	3   CoreFoundation                      0x00007ff810cf7555 ___forwarding___ + 1356
	4   CoreFoundation                      0x00007ff810cf6f78 _CF_forwarding_prep_0 + 120
	5   Sequel Pro                          0x000000010002fce3 -[SPDatabaseDocument setDatabases:] + 783
	6   Sequel Pro                          0x000000010002f2a9 -[SPDatabaseDocument setConnection:] + 610
	7   Foundation                          0x00007ff811b92527 __NSThreadPerformPerform + 179
	8   CoreFoundation                      0x00007ff810d1517b __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	9   CoreFoundation                      0x00007ff810d150e3 __CFRunLoopDoSource0 + 180
	10  CoreFoundation                      0x00007ff810d14e5d __CFRunLoopDoSources0 + 242
	11  CoreFoundation                      0x00007ff810d13878 __CFRunLoopRun + 892
	12  CoreFoundation                      0x00007ff810d12e3c CFRunLoopRunSpecific + 562
	13  HIToolbox                           0x00007ff8199c25e6 RunCurrentEventLoopInMode + 292
	14  HIToolbox                           0x00007ff8199c234a ReceiveNextEventCommon + 594
	15  HIToolbox                           0x00007ff8199c20e5 _BlockUntilNextEventMatchingListInModeWithFilter + 70
	16  AppKit                              0x00007ff81374cfad _DPSNextEvent + 927
	17  AppKit                              0x00007ff81374b66a -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1394
	18  AppKit                              0x00007ff81373dd19 -[NSApplication run] + 586
	19  AppKit                              0x00007ff813711c97 NSApplicationMain + 817
	20  Sequel Pro                          0x0000000100002454 start + 52
	21  ???                                 0x0000000000000001 0x0 + 1
)
```

**Comment by Nilpo** [comment]
I'm having the same issue here. Test works fine, connection crashes.

    NSInvalidArgumentException

    -[_NSInlineData isEqualToString:]: unrecognized selector sent to instance 0x600000da74b0

    (
        0   CoreFoundation                      0x00007ff80eac9e9b __exceptionPreprocess + 242
        1   libobjc.A.dylib                     0x00007ff80e82be48 objc_exception_throw + 48
        2   CoreFoundation                      0x00007ff80eb4e88e -[NSObject(NSObject) __retain_OA] + 0
        3   CoreFoundation                      0x00007ff80ea3191a ___forwarding___ + 1356
        4   CoreFoundation                      0x00007ff80ea31338 _CF_forwarding_prep_0 + 120
        5   Sequel Pro                          0x000000010002fce3 -[SPDatabaseDocument setDatabases:] + 783
        6   Sequel Pro                          0x000000010002f2a9 -[SPDatabaseDocument setConnection:] + 610
        7   Foundation                          0x00007ff80f803527 __NSThreadPerformPerform + 179
        8   CoreFoundation                      0x00007ff80ea4f35a __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
        9   CoreFoundation                      0x00007ff80ea4f2c2 __CFRunLoopDoSource0 + 180
        10  CoreFoundation                      0x00007ff80ea4f040 __CFRunLoopDoSources0 + 242
        11  CoreFoundation                      0x00007ff80ea4da50 __CFRunLoopRun + 892
        12  CoreFoundation                      0x00007ff80ea4d014 CFRunLoopRunSpecific + 562
        13  HIToolbox                           0x00007ff817b6a5e6 RunCurrentEventLoopInMode + 292
        14  HIToolbox                           0x00007ff817b6a34a ReceiveNextEventCommon + 594
        15  HIToolbox                           0x00007ff817b6a0e5 _BlockUntilNextEventMatchingListInModeWithFilter + 70
        16  AppKit                              0x00007ff8113bdfad _DPSNextEvent + 927
        17  AppKit                              0x00007ff8113bc66a -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1394
        18  AppKit                              0x00007ff8113aed19 -[NSApplication run] + 586
        19  AppKit                              0x00007ff811382c97 NSApplicationMain + 817
        20  Sequel Pro                          0x0000000100002454 start + 52
    )

**Comment by Nilpo** [comment]
Looks like this issue has been around for over 2 years. It is fixed in the latest [nightly build](https://sequelpro.com/test-builds), but I also found a suggestion to use [Sequel Ace](https://sequel-ace.com/) which is still in current development. Both worked.

**Comment by kaggrwal** [comment]
@Nilpo I have downloaded Sequel Ace, it is working fine. Thanks for the suggestion :)
