### ISSUE TITLE
The button colors in confirmation box are inverted.

### ISSUE THREAD

**Issue by egarcia111** [sequelpro/sequelpro#3877]
**not always**, but for most Mac UX the accent color is the "yes" or confirmation, and grey is "cancel"

 I wouldn't be surprised if people have hit "delete" out of muscle memory intending to cancel. 

<img width="265" alt="Screen Shot 2023-11-03 at 10 26 37 AM" src="https://github.com/sequelpro/sequelpro/assets/6527292/5e8c1dd2-4ce3-4677-8bc2-ea7d7dd2d91d">

**Comment by Jobjeuh** [comment]
Use Sequel Ace. This repo isn't maintained anymore and Ace is the updated fork of this project: [https://github.com/Sequel-Ace/Sequel-Ace](https://github.com/Sequel-Ace/Sequel-Ace)

**Comment by egarcia111** [comment]
Thanks for the FYI @Jobjeuh
