### ISSUE TITLE
Dropping multiple databases is a pain

### ISSUE THREAD

**Issue by ghost** [sequelpro/sequelpro#413]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=413
Reporter:craig.s.gardner Date:2009-09-21 14:09:03 Status:WontFix Closed:2009-09-01

Dropping multiple databases can get to be a pain.  It would be nice if I
were able to delete multiple databases similarly to how I would delete
multiple tables within a database.

**Comment by Zannisdf** [comment]
2020 and its still a pain

**Comment by jakeb-k** [comment]
2024 and working with a tenancy based db system, this is a massive pain I can't delete multiple dbs at a time, after running a bunch of tests and unwittingly creating a bunch of dbs along with it lol.
