### ISSUE TITLE
[REQ] Import feature: allow records to be updated

### ISSUE THREAD

**Issue by ghost** [sequelpro/sequelpro#464]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=464
Reporter:sandro...@gmail.com Date:2009-11-18 06:20:42 Status:Implemented Closed:2010-02-01

Right now (version 0.9.6), during the import process, if a record is already in the database (defined 
by the primary key) the application displays the following message:

[ERROR in line X] Duplicate entry '...' for key 1

The application should allow to update a record during the import process (i.e., if the primary key 
already exists, it should run an UPDATE command instead of an INSERT command).

As an example, the MySQL-Front application contains a checkbox, to enable this option, in the 
import dialog window.

**Comment by stuartmichelle** [comment]
I am not quite sure what to type in the ON DUPLICATE KEY box - I want to update some rows of data with new data, how do I use this box to do this?

**Comment by lephleg** [comment]
@stuartmichelle Normally it should accept the {column}={value} format like the SQL command. 
However Its not clear to me too how to pass the bindings..
