### ISSUE TITLE
[REQ] Remove table names from syntax highlighter reserved words

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#466]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=466
Reporter:mainstre...@gmail.com Date:2009-11-18 08:43:24 Status:Accepted

I have a table simply called 'data', which evidently is a SQL reserved word.

When I'm entering in a custom query, &quot;select \* from data&quot;, the syntax hilighter corrects it to &quot;SELECT 
- FROM DATA&quot;, and now &quot;DATA&quot; is an invalid table.

Obviously, I should be including the table name in backticks, but if it was excessively easy to ignore 
table and column names from the hilighter, that'd be aces.

**Comment by fulldecent** [comment]
Original scope of this issue is "Remove table names from syntax highlighter reserved words" and that will not happen because it requires extra network access. Therefore I recommend close issue.

**Comment by abhibeckert** [comment]
We already maintain a list of tables cached in RAM, there's no need for any network access.
