### ISSUE TITLE
[REQ] Search & Replace

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#47]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=47
Reporter:j...@jedisthlm.com Date:2008-09-06 02:40:40 Status:Accepted

This is not a bug but a wish for new feature, not sure if this is the right
place for this, if not please let us know where to start a list :)
1. Search &amp; replace, I know this can be done with SQL but it would be
   easier for two input fields that this could be done.

**Comment by pibo5** [comment]
+1

**Comment by fulldecent** [comment]
Recommending to close as out of scope for now.

Too many issues are open and this may not be addressed any time soon.
