### ISSUE TITLE
[REQ] Index Columns with Sizes

### ISSUE THREAD

**Issue by ghost** [sequelpro/sequelpro#480]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=480
Reporter:sparks.phill Date:2009-11-24 05:30:32 Status:Implemented Closed:2010-09-01

<b>What steps will reproduce the problem?</b>
1. Add an index to a table
2. Try to specify a column index with a size, eg:
2.1. object(333)
2.2. `object` ( 333 )

What would I expect?  What happens?
I would expect this to add an index of the object field with a length of 333; instead it reports 
&quot;Key column 'object(333)' doesn't exist in table&quot;.

Version:
Nightly Version 1571 on 10.6.2 connected to MySQL 5.0.67 via SSH

Comments:
I expect that the columns are being escaped literally (i.e., `object(333)`) rather than identifying 
the name and size (i.e., &quot;`object` (333)&quot;).

Suggestions:
1. Parse each column to identify the size before escaping and building the query
2. Alter the UI to have a dedicated box for entering the size (attached are some ideas)

**Comment by DJANGRA** [comment]
Just specify the primary keys without quotes.
Eg: PRIMARY KEY (a, b, c)
