### ISSUE TITLE
Crashes when deleting multiple records or truncating a table

### ISSUE THREAD

**Issue by ghost** [sequelpro/sequelpro#542]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=542
Reporter:ben.schw...@gmail.com Date:2010-01-18 20:18:08 Status:Fixed Closed:2010-01-01

<b>What steps will reproduce the problem?</b>
1. delete more than one record or truncate table
<b>2.</b>
<b>3.</b>

<b>What is the expected output? What do you see instead?</b>
Causes crash of sequel pro

<b>What version of the product are you using? On what operating system?</b>
Nightly 1691

<b>Please provide any additional information below.</b>
Tables have referential links.  Deleting records / truncating works fine in
phpmyadmin.

**Comment by CMSHostingLLC** [comment]
I still have this issue, it seems when ever i try to delete much more then 2000 records it prompts for password again and wont let me type into it... I have a Mac Pro 12 cores and 128gb of ram... I need to delete 368,000 records thats abouty 54.5MB  I have been at it for several hours already... Thinking phpMyAdmin might just be faster...

**Comment by CMSHostingLLC** [comment]
> Author:[rowanb@gmail.com](mailto:rowanb@gmail.com) Date:2010-01-20 16:22:44
> 
> Hi Ben,
> 
> You should find this is resolved in [r1697](/p/sequel-pro/source/detail?r=1697). Thanks for the report!

This link is 404.
