### ISSUE TITLE
[REQ] Add drag 'n' drop support to Import data from a local .sql dump file.

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#552]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=552
Reporter:folle...@gmail.com Date:2010-01-27 03:19:56 Status:Accepted

I wasn't thinking about it and I just tried to import data from a local dump .sql 
file doing drag'n'drop on the tables panel of Sequel Pro.

I think this could be a really nice idea, with maybe a popup to confirm it in 
order to avoid &quot;errors&quot;. :)

**Comment by fulldecent** [comment]
Importing from a SQL file already works. Just drag to the query window. Confirmed working.

As for CSV that's a separate issue.

Recommend close as fixed.

**Comment by abhibeckert** [comment]
CSV/TSV is the preferred format, since it is up to ~20x faster.

**Comment by fulldecent** [comment]
Yes, but that is a different issue.

META: In general, I'm a fan of finding (legitimate) excuses to close an old issue if it is not active. Then someone will reopen a new issue if they care about it. I'm still learning the culture here on how maintainers on this project work.
