### ISSUE TITLE
Jump to ( the right arrow icon ) in the tables with foreign keys is not working properly.

### ISSUE THREAD

**Issue by ghost** [sequelpro/sequelpro#574]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=574
Reporter:gign...@gmail.com Date:2010-02-22 07:46:17 Status:Fixed Closed:2010-02-01

<b>What steps will reproduce the problem?</b>
1. Open table content view for a table with foreign keys.
2. Click on the right arrow icon of one row to jump to foreign table
3. Go back to the content view of Step 1
4. Select a different than step 2, and click different foreign key arrow.

The second time around the Jump to should of have used the selected foreign
key id.  Instead, it keeps using the id from step 2. 

It is broken since build Sequel_Pro_r1790.dmg.  The last build it works
properly is <a href="/p/sequel-pro/source/detail?r=1787">r1787</a>.  

This is one of the best and thoughtful feature of the product I use every
single day.

**Comment by gignesh** [comment]
Hello,

This functionality broke again with rev. bed1cff292.   It works fine @ dfab0cd76c.

- Gignesh

**Comment by dmoagx** [comment]
See #2792
