### ISSUE TITLE
[REQ] Add filter to database drop down

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#582]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=582
Reporter:sim...@gmail.com Date:2010-03-05 14:17:07 Status:Accepted

I have many databases on the localhost: It's very difficult to get a quick look on all databases.
I attached an exemple of the appearance of the database selection.
![database](https://cloud.githubusercontent.com/assets/5793864/10377595/7dcb9022-6e04-11e5-84aa-105729b94337.jpg)

**Comment by jrpisd** [comment]
+1 on the filter.  I maintain a MariaDB Galera cluster with close to 1000 databases.  Sequel Pro is the best tool I've found for general MySQL/MariaDB access, but trying to scroll to the right database in a list that long is frustrating.

**Comment by dmoagx** [comment]
A "database filter" has already been implemented for some time and even is part of 1.1. See #1857

This issue is only for the grouping of DBs in the database dropdown.

**Comment by fulldecent** [comment]
Recommend closing issue. "Go to database" should be good enough for now.

**Comment by abhibeckert** [comment]
We need to keep issues like this open for consideration when we re-design the interface for v2.0
