### ISSUE TITLE
[REQ] Configurable next/previous word characters

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#588]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=588
Reporter:trevorly...@gmail.com Date:2010-03-10 16:19:31 Status:Started

I habitually use opt-left arrow and opt-right arrow to navigate within
lines of text. It'd be great if I could configure a list of word characters
(as Textmate does) that define where my cursor stops.

For instance, using opt-right arrow with my cursor at the indicated place
in this query:
SELECT \* FROM |database.table

Takes me here:
SELECT \* FROM database.table|

If I could add a period to my word characters, I would instead go here:
SELECT \* FROM database|.table

This makes selecting sections of text much, much easier. Would it be easy
to configure the editor to accomplish this?

**Comment by fulldecent** [comment]
Confirmed still an issue in 1.1.2.
