### ISSUE TITLE
Refresh Databases doesn't work

### ISSUE THREAD

**Issue by ghost** [sequelpro/sequelpro#599]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=599
Reporter:dejan.ra...@gmail.com Date:2010-03-18 12:26:27 Status:Invalid Closed:2010-03-01

<b>What steps will reproduce the problem?</b>
1. Create database
2. Go to created databases
3. Outside of sequel-pro create tables
4. Back to sequel-pro pressing shift + command + R doesn't refresh database, same as choosing 
from Database menu -&gt; Refresh Databases.

<b>What is the expected output? What do you see instead?</b>
I expected to see newly created tables inside sequel-pro. But instead i didnt saw any changes.

<b>What version of the product are you using? On what operating system?</b>
0.9.7 Mac version

<b>Please provide any additional information below.</b>

**Comment by jishnu2292** [comment]
Refresh Databases as well as table doesn't work. I have updated database fields through my php code. But on refreshing the database as well as refreshing the table does not reflect it on the database. So i took the table structure and added a field to the table. After that, on selecting the table content, the table refreshes and the old updated values have reflected. Im able to view the changes only on doing the above process.
