### ISSUE TITLE
[REQ] support for \G style query results

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#613]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=613
Reporter:mainstre...@gmail.com Date:2010-03-29 03:17:33 Status:Duplicate Closed:2011-01-01

Some custom queries, such as SHOW SLAVE STATUS, return only one record, and winds upi being 
displayed in a single line with truncated cells.

A more useful alternate is a view where each row in the view is a database column:value pair.  For 
multiple results in this view, a pair of back&amp;forward arrows would be nice.

This mimics the behavior of &quot;show slave status \G&quot;

**Comment by one10** [comment]
pretty cryptic, this is a duplicate of what? what happened to this request? 5 yrs later, is there a way to do \G? Can't seem to find it (the fact that it's not a very searchable \G doesn't help either...)

**Comment by dmoagx** [comment]
The "Duplicate of what" info was not migrated from Google Code, and when Google "archived" their site, they dropped it, too.

But no, this was never implemented.

**Comment by ulriksenstian** [comment]
+1 Would love this functionality
