### ISSUE TITLE
[REQ] Include table type in table icon

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#628]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=628
Reporter:mainstre...@gmail.com Date:2010-04-07 05:30:30 Status:Accepted

the &quot;yellow grid&quot; icon should be augmented to somehow indicate the table type, most importantly, 
InnoDB vs MyISAM.  Perhaps just overlay a letter, unless one of your users volunteers some nice 
icons for the various types.

**Comment by fulldecent** [comment]
The data is already available when you click the table. I do not think this is necessary. Recommending close.
