### ISSUE TITLE
[REQ] Allow multiple table content filters

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#63]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=63
Reporter:schlabbe...@gmail.com Date:2008-10-07 10:52:06 Status:Accepted

Something for later:

The search and filtering feature of Sequel Pro is currently really limited.
I would prefer a more advanced search like Spotlight offers.

**

I attached a basic mockup of what I think would be a nice interface.
![_igp6257](https://cloud.githubusercontent.com/assets/5793864/2554636/18a7791c-b6b4-11e3-8c53-336853ba2c86.jpg)

However there is a problem with this:
From the image it is not clear whether the query should be

```
SELECT * FROM t1 WHERE 
    username LIKE 'joe%' OR 
    (   username LIKE 'jane%' AND 
        date_joined >= DATE_SUB(NOW(),INTERVAL 3 WEEK) );
```

or

```
SELECT * FROM t1 WHERE 
    (   username LIKE 'joe%' OR  
        username LIKE 'jane%' ) AND 
    date_joined >= DATE_SUB(NOW(),INTERVAL 3 WEEK);
```

**

I think Spotlight uses NSPredicateEditor which supports nested queries (try
clicking on the + icon while holding down the ALT key) but this seems to
get really unintuitve for MySQL as the second query from above would be
written as.

```
-------------------------------------------------
| [Any] [of the following is true]          - + |
|   [username] [is like] "joe%"             - + |
|   [username] [is like] "jane%"            - + |
| [date_created] [is within] "3" [weeks]    - + |
-------------------------------------------------
```

**

When this has been accomplished there should maybe also be a feature
similar to &quot;Smart Folders&quot;.

**Comment by daverogers** [comment]
+1. The advanced filter dialog is pretty clunky and unintuitive, two things one doesn't normally associate with SP :) This feature would be fantastic, as it is in Navicat.

**Comment by ursbraem** [comment]
+1

**Comment by abhibeckert** [comment]
In many ways our "basic" filter is currently more powerful than the "advanced" filter and it's very easy to use.

I think we should improve the basic filter to support multiple rules, and then drop the advanced filter dialog.

**Comment by ursbraem** [comment]
@abhibeckert this sounds smart and is according to my experience (I wasn't aware of the advanced filter until I read about it, but failed using it)

**Comment by AcademyLime** [comment]
Any plans to have this feature in near future?

**Comment by abhibeckert** [comment]
@AcademyLime it won't happen for 1.2 since that's close to being released and is feature locked.

We won't be making any concrete plans for the next release until after 1.2 is shipped.

**Comment by Mikuz** [comment]
+1. Ended up making the primary query in Content view, copying the query from console and adding additional conditions in Query view. Because it was much easier than the "advanced" filter.

**Comment by TUNER88** [comment]
@abhibeckert any news on this topic?

**Comment by abhibeckert** [comment]
@tuner88 no change since my last comment

**Comment by daveredfern** [comment]
This would be great.

**Comment by pibo5** [comment]
+1

**Comment by joshdavenport** [comment]
Gotta +1 this

**Comment by peterjaap** [comment]
+1!!!

**Comment by hubdotcom** [comment]
+1

**Comment by myrandor** [comment]
+1

**Comment by antoineazar** [comment]
+1

**Comment by hurlibuz** [comment]
+1

**Comment by approached** [comment]
+1

**Comment by Pysis868** [comment]
+1

**Comment by fulldecent** [comment]
@everyone, please use GitHub +1 feature, not comments.

Also, does anyone have screenshots to share of how other software handles this?

**Comment by ytorbyk** [comment]
+1

**Comment by vetalkab** [comment]
+1

**Comment by pixedelic** [comment]
+1

**Comment by grossga** [comment]
+1

**Comment by eriktelepovsky** [comment]
Hi. Any news for this? Such feature would be really useful. Thank you for your time and effort.

**Comment by jdavidbakr** [comment]
This is something I do on a regular basis and have to go back to phpMyAdmin for.  Would seem to be a fairly simple feature to add and would make Sequel Pro so much more ... Pro.

**Comment by dmoagx** [comment]
The "Pro" version of multiple table content filters is already in Sequel Pro: Table > Advanced Filter. ;-)

**Comment by eriktelepovsky** [comment]
Hi @dmoagx.. I haven't noticed that, thank you for this. I am wondering if it is possible to change AND operator to OR (or a combination)?

**Comment by jdavidbakr** [comment]
Ah, thanks @dmoagx - maybe that could be a button added to the current search box?

**Comment by neatnate** [comment]
I've wished for this feature for awhile also.

**Comment by dblazeski** [comment]
+1

**Comment by admon** [comment]
+1

**Comment by keremgunduz** [comment]
+1

**Comment by kimegede** [comment]
👍 would like to see this feature too :)

**Comment by hcancelik** [comment]
+1

**Comment by radugroza** [comment]
@fulldecent @abhibeckert
I think HeidiSQL nailed it in this regard. 
https://www.screencast.com/t/L2Z4y07etc
You have a single text box for keywords (right side). When typing there, the query on ALL columns is automatically constructed. If you wish to search a single column, you just type your search condition in the large (left) textbox, e.g: `post_title LIKE '%Copy of Child 1%'`

I have used HeidiSQL a lot and found this pretty darn useful. I've switched over to Mac, and would really like to see something like this in SequelPro

Thank you for your time & effort on this software!

**Comment by itcentralstation** [comment]
+1 
It's a bit of travesty that should a great tool is missing something so fundamental.

The advanced filter is clunky when tables have lots of columns. And it doesn't recognise field types like dates, booleans and integers. As a start, use the diagram in the first request. Don't worry about implementing OR's or NOTS. Just allow multiple lines on the simple filter. Here's how Postico does it simply and elegantly.

<img width="1144" alt="screen shot 2018-05-01 at 19 37 02" src="https://user-images.githubusercontent.com/14926586/39482291-289c9222-4d77-11e8-8f22-0e9c0e6b09c7.png">

**Comment by feelsguess** [comment]
+1 I'm using TablePlus for MySQL but they're still missing triggers, they also have a pretty good advanced filter.

<img width="943" alt="screen shot 2018-05-02 at 1 11 51 am" src="https://user-images.githubusercontent.com/26889378/39486310-e44533ca-4da5-11e8-8742-2e29cebbbd09.png">

Would love to see it in Sequel Pro.

**Comment by joshdavenport** [comment]
Really good examples, those two look very nice. I don't suppose it wouldn't be trivially easy to add this functionality, but I do think it would be easy to fit this into the current UI already in use, especially based on these examples.

e.g. from:

![before](https://user-images.githubusercontent.com/757828/39519206-b7c5393c-4dfd-11e8-8e93-05b297c33bff.png)

to:

![after](https://user-images.githubusercontent.com/757828/39519209-ba3e18a0-4dfd-11e8-90d7-2206066a0f59.png)

**Comment by fulldecent** [comment]
@joshdavenport Saying "I think this would be easy" is not productive.
@itcentralstation Saying "It's travesty that this feature is missing" is not productive.

To be productive, please click here https://www.bountysource.com/issues/4664766-req-allow-multiple-table-content-filters and click one of the TEAL buttons on the right.

**Comment by neatnate** [comment]
@fulldecent  Your comment was made as if it is assumed that we know to go and fund each feature that we want. It was my assumption that this software has programmers who support it, but perhaps that isn't the case. Perhaps I need to find software that is actively supported.

**Comment by ursbraem** [comment]
Hi guys. It's an awesome, reliable tool and thanks to all the maintainers. Maybe it would be a good idea to clarify the structure of the project: who's the PO, _are_ there people willing to work on it for a crowdfunding, _would_ such changes be merged if financed, is the bountysource poll relevant etc. I see it's tiresome to get notifications every day by people (like me) whining for free features. Also as users, it's cool to know who you have to ask and what chances you get if you ask and what you can do to support the project ...

**Comment by joshdavenport** [comment]
Indeed @fulldecent saying that is not productive, with that in mind I suggested that the current interface fits in with what was previously suggested and as such wouldn't require rethinking the interface entirely instead of simply saying "I think this would be easy" as you implied.

If the core contributors are open to providing an official method for us to fund features, perhaps a lot of us would be open to contributing to get nice to have features like this.

**Comment by dmoagx** [comment]
I've added support for multiple table content filters:
<img alt="" src="https://user-images.githubusercontent.com/5793864/39680418-d0a9ec9e-51a0-11e8-91ad-f59fcc717169.png">

It's not yet polished and there are some remaining issues, but I'd like to get feedback (if you can compile SP yourself, that is 🤔)

**Comment by eriktelepovsky** [comment]
That's perfect :)

**Comment by oldo** [comment]
@dmoagx the multi filter feature looks great and would solve the only pain point that I have with Sequel Pro. How can I try it out? It doesn't seem to be an option in latest release (v1.1.2).
Thanks :-)

**Comment by toshim45** [comment]
> @dmoagx the multi filter feature looks great and would solve the only pain point that I have with Sequel Pro. How can I try it out? It doesn't seem to be an option in latest release (v1.1.2).
> Thanks :-)

download nightly build ? https://sequelpro.com/test-builds

**Comment by oldo** [comment]
Epic, thanks @toshim45 👍

**Comment by Jiia** [comment]
The filters work fine in the nightly build, but it breaks the links on foreign key columns to the related tables. If you click on a column that links to another table, the new table opens but it won't show the related row, just a bunch of random rows.

**Comment by kimegede** [comment]
@Jiia maybe a new ticket is needed for that issue?

**Comment by lcsqlpete** [comment]
Late to this, but just downloaded the last available nightly build to try it.

To be honest, I'm perfectly happy with the shift-command-f filter especially now that there's a horizontal scroll bar and you can see the full column names.

On the new filter feature at the top of the content screen, the screenshot earlier in this thread showed there was an "OR" capability but I can't find any way to invoke that.  Did it make it into the feature?

**Comment by quyle92** [comment]
> 

sorry but where can I find this multi-filter feature... it seems that there is only single filter at the moment.

**Comment by ursbraem** [comment]
I have it in a nightly build. Thing is: https://sequelpro.com/test-builds doesn't react.

![grafik](https://user-images.githubusercontent.com/1446443/146404515-f21b02e1-72ed-4547-9db8-025b4e3f4980.png)

**Comment by ursbraem** [comment]
By the way. Is it possible to see my query I have created in the GUI? That would be super powerful

**Comment by quyle92** [comment]
hi @ursbraem ,
Thanks for your reply.
My sequel pro only has single filter at the moment...
<img width="1069" alt="image" src="https://user-images.githubusercontent.com/59790219/146537592-0c6dbc10-96df-47a9-b066-5022ad3ca5b2.png">
Btw, your link got blank when I clicked on it.

**Comment by quyle92** [comment]
for anyone having issue with Sequel Pro not showing multiple filter, switch to Test Build version. Here is download link: https://sequelpro.com/test-builds

**Comment by ursbraem** [comment]
Thanks! I discovered table plus in the meantime as an alternative
