### ISSUE TITLE
Connection/favourite fields accept linebreaks

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#636]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=636
Reporter:rowanb@gmail.com Date:2010-04-14 03:12:43 Status:Accepted

On the connection screen and in the favourites manager, a number of fields accept linebreaks.  As 
each field only displays a single line, this can cause confusion.

In addition, multiline IP addresses work in the host field (!), breaking MySQL dump files.  We 
probably need to both prevent the initial entry (eg via pasting) of newlines, and also clean up 
favourites.

**Comment by fulldecent** [comment]
Confirmed fixed in 1.1.2. Recommending close issue.
