### ISSUE TITLE
Cleanup 'Create Table' and 'Copy Create Table' menu items

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#639]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=639
Reporter:jabakobob@gmail.com Date:2010-04-16 15:29:16 Status:Accepted

At the moment, Sequel Pro offers three methods to access the create table syntax:
1) Click on table info
2) Select &quot;Show CREATE TABLE syntax...&quot; from the &quot;Table&quot; menu
3) Select &quot;Copy CREATE TABLE syntax&quot;

The menu items were originally created to replace the toolbar items of Cocoa Mysql. In my eyes, 
the two menu items are not required anymore because:
1) To show the table syntax, you can just select the &quot;table info&quot; view
2) To copy the table syntax, you can select the table syntax shown in the &quot;table info&quot; view and 
press Cmd-C
3) To save the CREATE TABLE syntax to a file, you can export a MySQL dump and choose to 
ignore the table content

Therefore I suggest we remove the two menu items &quot;Show CREATE TABLE...&quot; and &quot;Copy CREATE 
TABLE&quot; from the table menu. This would allow us to remove some redundant code and make  
DView.xib a little smaller again -- making SP just a little bit easier to maintain.

Does anybody regularily use these commands or believe they provide necessary functionality?

**Comment by fulldecent** [comment]
Recommend reduce scope of request to:

> Remove COPY CREATE TABLE SYNTAX menu item.

This will make it actionable today and it will solve 50% of the problem.

**Comment by abhibeckert** [comment]
> Remove COPY CREATE TABLE SYNTAX menu item.

Sometimes I use that menu item several times a day, and I'm sure it's the same for others.

I agree the interface should be cleaned up, but not by removing that feature.

**Comment by fulldecent** [comment]
The COPY button is also available under SHOW CREATE TABLE SYNTAX.

**Comment by stuconnolly** [comment]
Agreed. I don't think we should be changing anything here. There is no drawback to having access to the same functionality in more than one place. It's not like we're displaying all 3 of them on screen at once. 

They're are lot of other things we can do to make the codebase more maintainable, but I don't think removing access to functionality is one of them.

Closing this. Any future UI changes should be done with regard to #2730
