### ISSUE TITLE
Wrong row duplicated if duplicate button used while editing

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#641]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=641
Reporter:jabakobob@gmail.com Date:2010-04-19 11:28:43 Status:Accepted

<b>What steps will reproduce the problem?</b>
1. Make sure &quot;Reload Table after editing rows&quot; is enabled in the prefs
2. Order the table by a field
3. Make a change in that field that would cause the order of the rows to change
4. Without committing the change, press Delete or Duplicate
5. The row below or above the actually selected row is deleted/duplicated

This issue is because I changed saveRowOnDeselect in <a href="/p/sequel-pro/source/detail?r=2103">r2103</a> to fix a different bug. (Note that 
<a href="/p/sequel-pro/source/detail?r=2103">r2103</a> caused a third bug ( <a href="http://spbug.com/634" rel="nofollow">http://spbug.com/634</a> ), which was fixed in <a href="/p/sequel-pro/source/detail?r=2110">r2110</a>.)

**Comment by fulldecent** [comment]
Confirming bug fixed in 1.1.2 as per given test case.

Recommending close as fixed.
