### ISSUE TITLE
Font Size settings

### ISSUE THREAD

**Issue by ghost** [sequelpro/sequelpro#658]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=658
Reporter:m...@skandix.ag Date:2010-04-30 07:52:57 Status:WontFix Closed:2010-04-01

Thanks so far for a really great tool!

When working on a screen with high resolution it becomes hard to read the contents of the listings 
and tables.
Would be great if you offer a settings-option for font size!

best regards
Marcel

**Comment by shemtov1** [comment]
Agreed that it would be more useful if the font settings would also affect the structure view and
the side pane with the tables list.
Because of this problem I sometimes switch to Mysql Workbench

**Comment by creativejatins** [comment]
I am having the same issue. I am on 5k 27 Inch, and hard to read the UI text. What we can change is the content text, not the UI itself. I would highly appreciate it if you could add an option to change the UI font size.

**Comment by mfakhrys** [comment]
+1 for font size in Structure view and others.. It's very small in a large screen.. Thanks in advance..
