### ISSUE TITLE
[REQ] Improve MySQL documentation viewer

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#669]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=669
Reporter:ctst...@googlemail.com Date:2010-05-04 16:42:03 Status:New

When using the Query view, it would be really nice to have a panel available like in Numbers where 
it shows you all the available commands and a description of what they do...

Alternatively code completion, code sense and live previewing of queries as you type in the Query 
view would be a nice feature.

**Comment by fulldecent** [comment]
Would somebody that has access to Numbers please include a screenshot that documents the requested behavior.

**Comment by abhibeckert** [comment]
Closing.

This doesn't describe an actual problem that needs to be solved, and it would be copyright infringement to just make it work the same as another app (unless the app is open source of course).
