### ISSUE TITLE
0.9.8 hangs periodically

### ISSUE THREAD

**Issue by ghost** [sequelpro/sequelpro#677]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=677
Reporter:inspir...@gmail.com Date:2010-05-07 14:44:24 Status:Fixed Closed:2010-07-01

Sorry, I haven't noticed a pattern.

Idling.  Long running queries sometimes.  I've had to force-kill it 3 times today.

mysql version 5.1.37

thanks for a great product!

**Comment by barracuda156** [comment]
> Author:[rowanb@gmail.com](mailto:rowanb@gmail.com) Date:2010-07-31 15:37:15
> 
> I've committed the fix for this to trunk in [r2482](/p/sequel-pro/source/detail?r=2482). You have no idea how incredibly glad I am that this bug is fixed - it's been incredibly frustrating :)
> 
> Jerome, Justin, inspire22, sgrosmark, Ted, Robert, Adam: many, many thanks for all your testing and feedback on this. Without you guys, this would never have been fixed as I simply wasn't able to reproduce it.
> 
> We'll get working on a 0.9.8.1 so everyone can benefit from this.
> 
> Thanks again all :D

@sequelpro Oh, the link is dead now. What was the fix?

**Comment by JamesVanWaza** [comment]
@barracuda156 use https://github.com/Sequel-Ace/Sequel-Ace as Sequel Pro is no longer updated.
