### ISSUE TITLE
[REQ] Create 'Copy as Alter Table' to edit menu for columns

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#685]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=685
Reporter:mainstre...@gmail.com Date:2010-05-14 07:32:00 Status:Accepted

In the Structure view, i'd like to be able to copy columns, so an Edit menu item called &quot;Copy as SQL 
ALTER TABLE&quot; would be useful.

**Comment by brandonbird** [comment]
+1 This would be great for quickly applying schema changes made in a dev/test database to production

**Comment by abhibeckert** [comment]
Agreed, this would be a very useful feature. Removing stu from the assign list, since he hasn't worked on the project recently.

**Comment by simderoemer** [comment]
+1 That would be amazing!
