### ISSUE TITLE
[REQ] Add copy selection as SQL REPLACE and UPDATE

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#694]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=694
Reporter:zer...@gmail.com Date:2010-05-19 02:45:08 Status:Accepted

Add an option to export selected rows.

**Comment by natrim** [comment]
*ping*
i would like this one too (namely the Copy as UPDATE)

**Comment by ddroescher** [comment]
Another vote for this, it would be a great addition to the INSERT copy. 

Side note: I used this on RazorSQL today, and it worked well enough. They don’t use the primary keys for row selection, but reference all fields in a row – which is overkill IMO. If there is a unique key, UPDATE should use that.

**Comment by ianlintner** [comment]
+1
