### ISSUE TITLE
[REQ] Thread ALTER TABLE operations

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#710]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=710
Reporter:mainstre...@gmail.com Date:2010-05-27 03:42:44 Status:Accepted

Alter a huge table, such as changing TEXT to VARCHAR(255).  Sequel Pro beachballs.

**Comment by nexbridge** [comment]
Just to add a few test cases for you to use as and when, in case the initial fix only solves some but not all.

The following are changes made via the GUI in the Structure tab:

1)  Changing the column type
2)  Changing the length of a VARCHAR column
3)  Adding/removing "Allow Null" for a column

Then there's also:

4)  Duplicating a table (including its content) via the GUI in the TABLES pane
5)  Changing the table engine type via the GUI in the Table Info tab

These essentially lock the entire Sequel Pro window (i.e. all connection tabs) until the query is complete - so for example if it's a very large table and it takes an hour to complete then that means you're unable to work on any other connection tabs during that time!

**Comment by hparadiz** [comment]
+1 on this one. I know it's probably a huge structural challenge to make this happen but yea any long standing database operating coming from the GUI should not lock up the GUI.
