### ISSUE TITLE
Keywords in backticks are auto-capitalized

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#752]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=752
Reporter:dohpaz@gmail.com Date:2010-07-01 05:42:03 Status:Started

<b>What steps will reproduce the problem?</b>
1. Build a SQL query that uses keywords as table names
2. Quote the table/column names with backticks (`)
3. Edit the query a few times, as the capitalization seems random

<b>What is the expected output? What do you see instead?</b>
When using the backtick (`), I would expect the editor to ignore the contents. Instead, the keywords in the backticks are capitalized, which causes me to have to lowercase them so the query won't fail due to case-sensitivity.

<b>What version of Sequel Pro are you using? What version of MySQL are you</b>
<b>connecting to on the server?</b>
Sequel Pro 0.9.8 (Build 2210)
MySQL 5.1.29-rc (x86_64) Community Edition, Protocol Version 10

<b>Please provide any additional information below.</b>
This doesn't seem to be an issue with the keyword table names in the column list of the SELECT.

For example, the following query:

SELECT DISTINCT `list`.`list_uid`, `list`.`list_title`, `list_category`.``
FROM`list`
INNER JOIN`record`ON (`record`.`list_uid`=`list`.`list_uid`AND`record`.`is_company`= 0 AND`record`.`is_person`= 0)
INNER JOIN`list_category`ON (`list_category`.`list_uid`=`list`.`list_uid`)
WHERE`list`.`pub_uid` = 1;

ends up appearing as:

SELECT DISTINCT `list`.`list_uid`, `list`.`list_title`, `list_category`.``
FROM`LIST`
INNER JOIN`record`ON (`record`.`list_uid`=`LIST`.`list_uid`AND`record`.`is_company`= 0 AND`record`.`is_person`= 0)
INNER JOIN`list_category`ON (`list_category`.`list_uid`=`LIST`.`list_uid`)
WHERE`LIST`.`pub_uid` = 1;

while editing.

**Comment by fulldecent** [comment]
Confirming fixed in 1.1.2. Recommending close issue.
