### ISSUE TITLE
[REQ] Add preference to (not) add backticks around keywords

### ISSUE THREAD

**Issue by ghost** [sequelpro/sequelpro#764]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=764
Reporter:roberto....@gmail.com Date:2010-07-20 04:38:22 Status:Accepted

I'd like to turn on and off the quotes for table atribute names in preferences dialog.

Best Regards

**Comment by christatedavies** [comment]
Great tip about using CMD+Z after the autocomplete has been performed to remove the ticks. That'll do for now, I can't see them adding this option.
