### ISSUE TITLE
[REQ] Usability: in the list of indexes, change 'non_unique' column to be 'unique' - easier to understand at a glance

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#774]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=774
Reporter:laust.rud Date:2010-07-30 02:21:15 Status:Accepted

I'm usually interested in quickly answering the question &quot;is this a unique index?&quot; - switching to the Structure | Indexes view for a table, you quickly see the answer to &quot;is this a not unique index&quot;. 

Inverting the shown information should be a small change, and it would certainly make my brain happier.

**Comment by andrhamm** [comment]
Please!

**Comment by jeffbyrnes** [comment]
:+1:

**Comment by atironati** [comment]
:+1: This would make my life so much better

**Comment by EdHurtig** [comment]
:+1:

**Comment by rowanbeentje** [comment]
So a big thumbs up from EverTrue there ;)

I still think a larger rework of the Structure tab is required, but a few small changes to the table views would be much faster...
