### ISSUE TITLE
SP does not use UI scale factor

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#782]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=782
Reporter:schlabbe...@gmail.com Date:2010-08-09 17:21:25 Status:Accepted

When running OS X with another [[self window] userSpaceScaleFactor] than 1.0 the Preferences Interface will break.

**Comment by dmoagx** [comment]
Works fine on HiDPI screens in 10.9 and userSpaceScaleFactor has been deprecated anyway, so I'll close this.
