### ISSUE TITLE
Saved passwords lost, unable to save again

### ISSUE THREAD

**Issue by ghost** [sequelpro/sequelpro#801]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=801
Reporter:kchr...@gmail.com Date:2010-08-31 16:59:25 Status:WontFix Closed:2010-08-01

<b>What steps will reproduce the problem?</b>
1. No sure, exactly. For me it just started, having worked fine just a few days ago. Today my saved passwords are gone and attempting to save them again results in the message:

An error occured while trying to add the password to your Keychain. Repairing your Keychain might resolve this, but if it doesn't please report it to the Sequel Pro team, supplying the error code -25293.

Connections work fine when I enter the password, but they cannot be saved. 

Other applications can access and write to my keychain fine. Repairing my keychain has no effect on the problem. I have not installed any Sequel Pro, MySQL, or OS X updates since it worked last.

<b>What version of Sequel Pro are you using? What version of MySQL are you</b>
<b>connecting to on the server?</b>
- Sequel Pro 0.9.8.1 build 2492
- MySQL 5.1.38 on OS X (but my passwords were lost for MySQL servers on four different hosts)
- OS X 10.6.4

Thanks.

**Comment by fhofman** [comment]
Work for me, Thank you very much!
