### ISSUE TITLE
Support MySQL stored procedures, functions & views

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#82]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=82
Reporter:talksens...@gmail.com Date:2008-11-12 05:02:13 Status:Started

<b>What steps will reproduce the problem?</b>
1. select a schema with stored procedures, views &amp; user defined functions
<b>2.</b>
<b>3.</b>

<b>What is the expected output? What do you see instead?</b>
Ability to see and manipulate the stored procs, views, functions, etc.

<b>What version of the product are you using? On what operating system?</b>
0.9.2 os-x 10.5.5

<b>Please provide any additional information below.</b>
I wasn't able to figure out how to get into a design mode for procs, views,
etc.   This is necessary for any serious work using the product.

**Comment by tyteen4a03** [comment]
Would love to see this feature in Sequel Pro.

**Comment by fulldecent** [comment]
Is this request to simply view and edit text of stored procedures?

Is there another project that has syntax highlighting rules we can steal?

**Comment by abhibeckert** [comment]
We currently display procedures and functions in the left sidebar, and you can rename/delete them.

But you cannot execute them, or view their definition, or change their definition, or create new stored procedures. All of this must be done with the custom query feature presently.

**Comment by neokio** [comment]
This is one of the oldest open issues, and a surprising omission from such an excellent app. Is there something about how procedures are stored – or some other technical obstacle – that makes developing this feature exceptionally difficult?
