### ISSUE TITLE
Triggers and procedures

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#870]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=870
Reporter:it.digiv...@gmail.com Date:2010-10-21 08:09:44 Status:Accepted

It would be nice to see the TRIGGERS and PROCEDURES created in the table create syntax window

**Comment by fulldecent** [comment]
Duplicate of #639.

**Comment by abhibeckert** [comment]
Duplicate of #82
