### ISSUE TITLE
[REQ] Allow sorting while in Structure view

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#882]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=882
Reporter:braxton....@gmail.com Date:2010-11-03 18:51:41 Status:New

It would be helpful to be able to sort the rows of fields listed in the Structure view of a table.

**Comment by benn-be** [comment]
I would really like to have this too.

**Comment by herecomesthesun** [comment]
Would love to see this as well. It's so hard to find a field in that view.

Also in the "add an index" drop-down selector... you can't type to select, and leaving it unsorted makes it hard to find the right field:

![image](https://cloud.githubusercontent.com/assets/11964962/15154280/85963e48-1691-11e6-930d-765dfcecd4cc.png)

**Comment by fulldecent** [comment]
Confirmed broken in 1.1.2.

**Comment by bsiver** [comment]
I would love to see the ability to sort by column name in the structure view as well!
