### ISSUE TITLE
[REQ] Add support for editing existing indices

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#889]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=889
Reporter:goo...@dwilga.gotdns.org Date:2010-11-08 11:32:01 Status:New

Currently, it is not possible to edit existing indices, like you can with data in tables. It would be very helpful to be able to do this, rather than having to delete the index and re-add it.

**Comment by xvilo** [comment]
+1 still not availbe, have no way to show and delete indexes in sequel.

**Comment by dmoagx** [comment]
It is possible to show, add and delete indexes in Sequel Pro and has been for years.

This issue is just about the ability to edit them without deleting and re-adding.

**Comment by xvilo** [comment]
Couldn't find the option and after a quick google search I was redirected here... 

Sorry, will google harder ;)

**Comment by dmoagx** [comment]
Maybe you've hidden it?

In that case press this button:
![bildschirmfoto 2015-12-30 um 00 15 01 266](https://cloud.githubusercontent.com/assets/5793864/12043965/8962f7f6-ae8a-11e5-8efe-462e7bb05e73.png)

**Comment by fulldecent** [comment]
Confirmed working in 1.1.2. Recommending close issue.

**Comment by jerearaujo03** [comment]
Still don't have the option to edit index names.
