### ISSUE TITLE
[REQ] Allow multi-column sorts by shift-clicking on column header

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#891]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=891
Reporter:misterpa...@gmail.com Date:2010-11-09 16:00:29 Status:Accepted

In &quot;Content&quot; view shift-click multiple column titles to sort by multiple columns. This will easily and visually achieve 
&quot;ORDER BY `some_field`,`other_field` DESC&quot;

For example, if there is an actions table with:
`id`,`user_id`,`action`,`action_value`.

Clicking `user_id` will order the rows displaying rows entered by users next to one another. Then Shift+clicking the `action_value` column title, will secondarily sort the rows according to action value. It's a pretty simple concept, that would greatly improve accessibility to visual interpretation of any data if necessary.

**Comment by rkulla** [comment]
Is this still not possible?

**Comment by Bytesmiths** [comment]
I was about to add this as a request, but found it existed already. This is what I was about to post:
----------------
When browsing a table, you can sort by clicking on a column header of any of the fields.

If you click on a different field, the previous sort is totally lost.

According to the Console, this is implemented by an "ORDER BY" clause, as expected.

ORDER BY can take more than one argument, to do multi-column sorts.

This could be implemented by remembering the last column clicked, and using that as a minor sort key, or perhaps by using a modifier key to select multiple columns for sort.

I imagine the first solution is almost trivial to implement, but it has UI implications, and may be confusing to some people. Perhaps it could be implemented by requiring the use of a modifier key when clicking on the new major sort key.

The second proposed solution would take more UI programming to make it intuitive and clear.

Then there's the whole issue of how many minor sort keys to allow, and how do you indicate precedence order, etc.

I would be perfectly happy with the first proposed solution, limited to two total sort columns, but I realize that you may prefer to "back burner" this until you can come up with a totally general solution. But perhaps you could "slide in" the first solution and seek feedback.

Thanks for listening! And thanks for a great product!
