### ISSUE TITLE
[REQ] Fully support handling multiple result sets

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#899]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=899
Reporter:Nina.Els...@gmail.com Date:2010-11-13 15:37:11 Status:Accepted

<b>What steps will reproduce the problem?</b>
<b>1.</b>
```
drop procedure if exists dupa;

DELIMITER $$

create procedure dupa(in_date varchar(20))
begin
    select \* from event;
end$$

DELIMITER ;
```
<b>2.</b>
```
call dupa('laaa');
```
<b>What is the expected output? What do you see instead?</b>

Latest error message:
PROCEDURE test.dupa can't return a result set in the given context

<b>What version of Sequel Pro are you using? What version of MySQL are you</b>
<b>connecting to on the server?</b>

0.9.8.1

<b>Please provide any additional information below.</b>

It works as expected in the command-line:
```
mysql> call dupa('aaa');
+---------+------------------+------------+-----------------+
| eventID | eventDirectoryID | locationID | eventCategoryID |
+---------+------------------+------------+-----------------+
|       1 |                2 |          3 |               4 |
|       2 |                3 |          4 |               5 |
+---------+------------------+------------+-----------------+
2 rows in set (0.00 sec)

Query OK, 0 rows affected (0.00 sec)

mysql>
```

**Comment by boroth** [comment]
Are there any updates available at the moment that allow showing multiple result sets from a stored procedure?
