### ISSUE TITLE
[REQ] Change default editor font

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#910]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=910
Reporter:rotherham@gmail.com Date:2010-11-26 06:28:08 Status:New

This is purely a cosmetic issue but it makes Sequel Pro feel out of date.

Based on this article, and the behaviour of several &quot;modern&quot; OSX applications I'd suggest changing the Monaco font in the query editor to something else: <a href="http://arstechnica.com/apple/news/2009/06/font-changes-coming-to-mac-os-x-snow-leopard.ars" rel="nofollow">http://arstechnica.com/apple/news/2009/06/font-changes-coming-to-mac-os-x-snow-leopard.ars</a>

Panic Coda, MacRabbit's Espresso and Apple's Menlo typeface are all based off the Bitstream Vera Sans Mono project (or DejaVu Sans for more Unicode support): <a href="http://dejavu-fonts.org/wiki/Main_Page" rel="nofollow">http://dejavu-fonts.org/wiki/Main_Page</a>

What do you think? I think the query editor looks brilliant using DejaVu Sans Mono.

**Comment by stuconnolly** [comment]
Agree we should change this Menlo 11pt.
