### ISSUE TITLE
[REQ] Add SOCKS Proxy

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#918]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=918
Reporter:schlabbe...@gmail.com Date:2010-12-02 00:41:31 Status:Accepted

Can we add support for SOCKS (direct mysql as well as OpenSSH)?

**Comment by johnshine** [comment]
I set system network proxy, but sees not work

**Comment by Cellophan** [comment]
Yes it's needed. We can't afford to switch a full host just for accessing the DBs on different stages.
