### ISSUE TITLE
[REQ] Binary Columns should be displayed as Hex

### ISSUE THREAD

**Issue by ghost** [sequelpro/sequelpro#919]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=919
Reporter:tedivm@tedivm.com Date:2010-12-02 09:38:33 Status:Accepted

I have a table with a few binary columns, and whenever I view it the rows returned are basically random strings of text as the program tries to display the binary data as a string.

My suggestion would be to simply display it as hexadecimal, rather than directly outputting it, as this would look so much better and would be much easier to work with.

**Comment by julian-weinert** [comment]
@stuconnolly is this already released?! I don't find any setting in the current build...

**Comment by dmoagx** [comment]
View > Show binary as Hex

**Comment by larissagaulia** [comment]
Hello. 
I have View > Show binary as Hex checked. 
On El Capitan (10.11.6), for sequel pro 1.1.2 I still get random strings on by BINARY columns...

**Comment by dmoagx** [comment]
@larissagaulia 
Please open a new issue for that.
Also see: https://github.com/sequelpro/sequelpro/wiki/How-do-I-write-a-proper-issue-report%3F

**Comment by joe-boudreau** [comment]
YOU SHOULD BE ABLE TO COPY THE HEX THOUGH C'MON! 😩
