### ISSUE TITLE
Rework Table Content View

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#935]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=935
Reporter:schlabbe...@gmail.com Date:2011-01-05 07:37:06 Status:Accepted

This bug will serve as a collection of all bugs that are related to a more advanced table content view.

**Comment by fulldecent** [comment]
Recommend close. Not actionable.

**Comment by abhibeckert** [comment]
Duplicate of #2313
