### ISSUE TITLE
Edit sorted views

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#972]
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=972
Reporter:bish...@gmail.com Date:2011-02-04 00:15:25 Status:Started

<b>What steps will reproduce the problem?</b>
1. Create a view
2. Click a column to sort it
3. Try to edit a value

<b>What is the expected output? What do you see instead?</b>
Sequel Pro doesn't allow me to edit the value. It only works if the table is not sorted.

<b>What version of Sequel Pro are you using? What version of MySQL are you</b>
<b>connecting to on the server?</b>
Build 3179 / MySQL 5 over SSH

**Comment by fulldecent** [comment]
Recommending close issue.

**Comment by abhibeckert** [comment]
Confirmed fixed.
